### ISSUE TITLE
[Issue] Existing resource references appear as "created" in output log

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1001]
In templates we reference existing resources, like:
https://github.com/Azure-Samples/todo-nodejs-mongo-aca/blob/main/infra/app/api.bicep#L40

When we do an azd deploy on that file, those references are listed as "Created"

![image](https://user-images.githubusercontent.com/2163001/197896821-c474afb3-327a-4fc6-8b17-8469a5df01b8.png)

We should see if we can determine if the resource was referenced or created and update the output accordingly.

**Comment by pamelafox** [comment]
I was going to suggest something similar, though I was imagining three states: "Created", "Updated" (properties change), and "Already created" (something to signify no change). Don't know if that granularity is possible.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 recent changes on UX improvements has this handled. Can we close this?

**Comment by vhvb1989** [comment]
yeah, this is no longer valid
