### ISSUE TITLE
Exception has been occured while execute bash

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-dev#1005]
**Describe the issue:**
Exception has been occured while execue `test-templates.sh`

**Repro Steps:**
Run command: `bash ./test-templates.sh  -t <template_name> -b staging -c false`

**Error Message:**
![image](https://user-images.githubusercontent.com/74638143/197948090-564138d0-ccfb-4a3d-9c83-c8a751b71347.png)

**Environment:**
Azd Version:  azd version 0.3.0-beta.4-daily.1943817 (commit 75d070a7099a1691a96c2ea930b50b6de9fa0c78)
OS: Codespace, DevContainer, Linux desktop 
All Templates:
https://github.com/Azure-Samples/todo-csharp-cosmos-sql
https://github.com/Azure-Samples/todo-nodejs-mongo
https://github.com/Azure-Samples/todo-nodejs-mongo-aca
https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func
https://github.com/Azure-Samples/todo-python-mongo
https://github.com/Azure-Samples/todo-python-mongo-aca
https://github.com/Azure-Samples/todo-python-mongo-swa-func
https://github.com/Azure-Samples/todo-csharp-sql
https://github.com/Azure-Samples/todo-python-mongo-terraform
https://github.com/Azure-Samples/todo-nodejs-mongo-terraform
https://github.com/Azure-Samples/todo-csharp-sql-swa-func
https://github.com/Azure-Samples/todo-java-mongo
https://github.com/Azure-Samples/todo-java-mongo-aca

**Expected behavior:**
Run `bash ./test-templates.sh -c false -t <template_name> -b staging -c false` can run successfully.

@rajeshkamal5050  for notification.

**Comment by rajeshkamal5050** [comment]
Fixed as part of #1008 Please try with the latest bits and keep up posted.
