### ISSUE TITLE
Support Azure DevOps in Pipeline Commands

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#101]
Today `azd pipeline config` supports GitHub workflows. Let's also add support for Azure DevOps Pipelines

A sample pipeline and full instructions in README to get it all setup can be found here
https://github.com/Azure/azure-dev/tree/main/templates/common/.azdo/pipelines

1. Every template should include both
2. azd pipeline config will default to GitHub
3. Add a param, something like --provider {github|azdo} to facilitate more providers in the future

## Plan
1.  https://github.com/Azure/azure-dev/issues/236
2.  https://github.com/Azure/azure-dev/issues/237
3.  https://github.com/Azure/azure-dev/issues/238
4.  https://github.com/Azure/azure-dev/issues/239

**Comment by TroyWitthoeft** [comment]
Would be looking for this as well.

**Comment by johnnyreilly** [comment]
Very interested in this!
