### ISSUE TITLE
Only one Key Vault is purged after running AZD down

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/azure-dev#1018]
**Output from `azd version`**
```
azd version 0.3.0-beta.5 (commit 38169d7067ac73dc4e214e6913bee5e5359b8b15)
```

**Output from `az version`** 
```
{
  "azure-cli": "2.41.0",
  "azure-cli-core": "2.41.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "containerapp": "0.3.13",
    "log-analytics": "0.2.2",
    "rdbms-connect": "1.0.4"
  }
}
```

**Describe the bug**
Deployed an app that has 2 Key Vault resources. After running `azd down --no-prompt --force --purge` we're seeing that only one of two KV resources was purged

**To Reproduce**
1. run azd init
2. choose todo-csharp-sql
3. add a 2nd Key Vault instance
```
module keyVault2 './core/security/keyvault.bicep' = {
  name: 'keyvault2'
  params: {
    environmentName: environmentName
    location: location
    principalId: principalId
    keyVaultName: '${toLower(uniqueString(subscription().id, environmentName, location))}kv2'
  }
}
```
4. run azd provision
5. run 'azd down --no-prompt --force --purge'

**Expected behavior**
Expected both vaults to be removed

**Environment**
Information on your environment:
    * PwSh 7.2.7

**Comment by KSchlobohm** [comment]
@weikanglim @rajeshkamal5050

**Comment by vhvb1989** [comment]
Can you reproduce it if, instead of adding the second key vault after the first provision, you added it before and just run provision once?

The general problem might be that, after adding/updating the original bicep, we are not getting the full list of resources from the deployment.  So, the purge might be a side effect.   

@wbreza , do you know what's the expectation for the case of adding more resources after an initial provision?  Do we create a new deployment operation?

**Comment by KSchlobohm** [comment]
Quick workaround assumes you have less than 6 vaults.

```
deletedKeyVaultSvcName=$(az keyvault list-deleted --query "[? properties.vaultId.contains(@,'$resourceGroupName')] | [0].name" -o tsv)
currentRetryCount=0

while [ ${#deletedKeyVaultSvcName} -ne 0 ]
do
  if [[ $currentRetryCount -gt 6 ]]; then
    echo "FATAL ERROR: Tried to purge key vault too many times" 1>&2
    exit 14
  fi

  if [[ ${#deletedKeyVaultSvcName} -gt 0 ]]; then
    echo "Purging $deletedKeyVaultSvcName"
    az keyvault purge --name $deletedKeyVaultSvcName
  else
    echo "Done purging key vaults"
  fi

  currentRetryCount=$((currentRetryCount + 1))
  deletedKeyVaultSvcName=$(az keyvault list-deleted --query "[? properties.vaultId.contains(@,'$resourceGroupName')] | [0].name" -o tsv)
done
```
