### ISSUE TITLE
`azd provision` broken with incorrect `subscription`

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-dev#1020]
**Describe the issue:**
Exception has been occured while execue `test-templates.sh`

**Repro Steps:**
Run command: `bash ./test-templates.sh -t <template_name> -b staging -c false`

**Error Message:**
![image](https://user-images.githubusercontent.com/74638143/198180223-3cb45c4d-bde0-4468-b926-94d0093b5883.png)

**Environment:**
Azd Version: azd version 0.3.0-beta.6-daily.1947218 (commit e20ee4e6819f464f1f19d768d62bfaef493d46d8)
OS: Linux desktop, MacOS desktop, WSL, Codespace, DevContainer, 
All Templates:
https://github.com/Azure-Samples/todo-csharp-cosmos-sql
https://github.com/Azure-Samples/todo-nodejs-mongo
https://github.com/Azure-Samples/todo-nodejs-mongo-aca
https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func
https://github.com/Azure-Samples/todo-python-mongo
https://github.com/Azure-Samples/todo-python-mongo-aca
https://github.com/Azure-Samples/todo-python-mongo-swa-func
https://github.com/Azure-Samples/todo-csharp-sql
https://github.com/Azure-Samples/todo-python-mongo-terraform
https://github.com/Azure-Samples/todo-nodejs-mongo-terraform
https://github.com/Azure-Samples/todo-csharp-sql-swa-func
https://github.com/Azure-Samples/todo-java-mongo
https://github.com/Azure-Samples/todo-java-mongo-aca
The infomation of loginned azure account
![image](https://user-images.githubusercontent.com/74638143/198183437-246185dd-4b75-461e-b2ad-47675582572d.png)

**Expected behavior:**
Run `bash ./test-templates.sh -c false -t <template_name> -b staging -c false` can run successfully.

@rajeshkamal5050 for notification.``

**Comment by v-xuto** [comment]
Modify its subscription by executing command `azd config set defaults.subscription 'faa080af-c1d8-40ad-9cce-e1a450ca5b57'`. Now, this issue will not reproduce. We will close the issue.
