### ISSUE TITLE
Update and sync copy edits of learn.microsoft.com in azure.yaml.json 

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#1027]
https://github.com/Azure/azure-dev/blob/main/schemas/v1.0/azure.yaml.json#L67
`                        "description": "Optional. If not specified, the resource name will be constructed from current environment name concatenated with service name (<environment-name><resource-name>, for example 'prodapi')."`

From @wbreza, "is not true.  It will default to the behavior of the bicep implementation, but the user can override the name that should be used or azd will infer it from tag name azd-service-name matching the name/key of the service in the azure.yaml."

**Comment by savannahostrowski** [comment]
@puicchan Do you know if this is still needed?

**Comment by puicchan** [comment]
An old issue. No longer relevant. Closing.
