### ISSUE TITLE
[Issue] azd update notice happens to late, interrupting my flow

### ISSUE THREAD

**Issue by timheuer** [Azure/azure-dev#1031]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 0.3.0-beta.2 (commit 91a2c014887ebda63a0af2e623278f8ac40ce376)

**Output from `az version`** 
{
  "azure-cli": "2.41.0",
  "azure-cli-core": "2.41.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "azure-dev": "0.0.1b1539385",
    "containerapp": "0.3.13"
  }
}

**Describe the bug**
I started along the process (starting in VSCode) and was greeted with prompts to start providing information...then to be abruptly stopped because the tool I was using was out of date.

```
 *  Executing task: azd init -t "Azure-Samples/todo-csharp-sql" 

Initializing a new project in D:\source\repos\azdvscode

? Please enter a new environment name: development

? Please enter a new environment name: development
? Please select an Azure location to use: 48. (US) West US (westus)
? Please select an Azure Subscription to use: 23. ca-timheuer-demo-test (39efd248-7fd1-467e-9de3-cc501e6609d8)
warning: your version of azd is out of date, you have 0.3.0-beta.2 and the latest version is 0.3.0-beta.5

To update to the latest version, run:
powershell -ex AllSigned -c "Invoke-RestMethod 'https://aka.ms/install-azd.ps1' | Invoke-Expression"
```

**To Reproduce**
Have an out of date version of azd
Start an init

**Expected behavior**
If I was out of date in my toolset and that was going to prevent me from doing something in subsequent steps, tell me immediately, not when I'm a few steps in.  Do a "is my azd current" "is my az" current FIRST if those are required to be latest and/or specific versions.

As a result even doing the update is more abruptly disrutpting my flow because it asks me effectively 'restart all your tools now'

```
An entry for C:\Users\timheuer\AppData\Local\Programs\Azure Dev CLI is already in PATH
Azure Developer CLI (azd) installed successfully. You may need to restart running programs for installation to take effect.
- For Windows Terminal, start a new Windows Terminal instance.
- For VSCode, close all instances of VSCode and then restart it.
```

**Comment by rajeshkamal5050** [comment]
@wbreza can you triage this? so that we can give user the notice earlier and not during a command execution.

**Comment by vhvb1989** [comment]
By looking at the output, it looks like this is coming from the `Azd VSCode extension`.  
@karolz-ms FYI

**Comment by karolz-ms** [comment]
@vhvb1989 I might be wrong about this but I do not think this is related to VS Code.

What I think is happening is we have (1) logic when we prompt for parameters required for a command, and also (2) logic that checks whether azd is up-to-date. It looks like (1) is happening before (2), or maybe (2) is asynchronous and is finishing after (1).

Perhaps emitting the warning about outdated version should happen at the end of everything. The point that @timheuer is making is that doing it in the middle of command execution is interrupting user flow. I agree.

**Comment by savannahostrowski** [comment]
@rajeshkamal5050 I believe we decided as a team to keep the behaviour as is for now.
