### ISSUE TITLE
azd env new should accept positional argument for name

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1040]
I expected this to work
![image](https://user-images.githubusercontent.com/2163001/199048332-fef952cb-b42f-43cc-bbd5-7883340f503a.png)

But it asks me for an environment name.

**Comment by vhvb1989** [comment]
I think we need to use `-e` or `--environment-name`.

If we support positional arg here. What would it happen if we do `azd env new foo -e bar` ?

**Comment by weikanglim** [comment]
Duplicate of #502
