### ISSUE TITLE
Ability to pin to specific version of azd in CICD pipeline

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#1049]
I should be able to pin to specific version of azd so that my pipeline will run despite of breaking change in later version.

**Comment by jongio** [comment]
You can change this line:

```
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
```

To a version from here:
https://mcr.microsoft.com/en-us/product/azure-dev-cli-apps/tags


Like:

```
      image: mcr.microsoft.com/azure-dev-cli-apps:0.3.0-beta.5
```
