### ISSUE TITLE
[Issue] Strange formatting during resource provisioning.

### ISSUE THREAD

**Issue by Petermarcu** [Azure/azure-dev#1058]
**Output from `az version`** 
azd version 0.3.0-beta.5 (commit 38169d7067ac73dc4e214e6913bee5e5359b8b15)

**Describe the bug**
Bad formatting when provisioning resources:
![image](https://user-images.githubusercontent.com/8228359/199296118-7c3ecc6d-36f5-4afb-9e49-ad1a06c1bd3e.png)

**To Reproduce**
azd up a standard template

**Expected behavior**
nicer formatting

**Environment**
Information on your environment:
Windows plain command prompt

**Comment by ellismg** [comment]
We continue to get bit by our strategy of trying to push everything through `colorable.NewColorableStdout` to translate the ANSI codes into windows console color commands which are processed as we print the string.  For places where we forget to do this, we get behavior like the above.

I think we need to just embrace the fact that ANSI sequences won and [turn console support on for them](https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) and get rid of all this windows specific complexity.
