### ISSUE TITLE
Automating reference doc generation in learn.microsoft.com

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#1067]
Consider:
- context sensitive content. 
  e.g., in config.go, userConfigPath & output.WithBackticks(defaultConfigPath) will now output the path from the running linux agent.
  we expect in learn.microsoft.com:

        The default value of the config directory is:
               - $HOME/.azd on Linux and macOS
               - %USERPROFILE%\.azd on Windows

**Comment by danieljurek** [comment]
Discussed items in email

* Generate ToC for all docs (do not concat files) 
* Remove leading `$` from command documentation (e.g. `$ azd up --template ...`) 
* Pave over existing ref docs in GitHub repo, open up PR

**Comment by puicchan** [comment]
@danieljurek - since we will not be publishing to the ref repo, we can keep to the same concat file for TOC (i.e., single TOC.) I have removed 1st item from your list of todo. I will grab the current published MD and share with you off line. Additional update may be needed.
