### ISSUE TITLE
[Issue] Permission denied accessing config.json

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#1070]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
```
azd version 0.4.0-beta.1 (commit 2bf7a529914d86d8e9f5d7b6f95a4f20a2351e01)
```

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 

```
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "containerapp": "0.3.11",
    "containerapp-compose": "0.2.2"
  }
}
```

**Describe the bug**

After doing some installs/uninstalls, I started getting this error for anything azd related (azd up, azd init, etc):

Error: failed opening azd configuration file: open /Users/pamelafox/.azd/config.json: permission denied

When I looked at the details for that folder, I saw:
```
drw-r--r--    3 pamelafox  staff         96 Nov  2 09:31 .azd
```

So I ran `chmod 755 ~/.azd` and that made the error go away.

**To Reproduce**

I'm not sure if I just happened to get into some really funky state, or if this error would happen for everyone. You could try to replicate by pulling the latest version locally and seeing if it happens for you. It happened in both VS Code and the standard Terminal app for me. I was *not* in a devcontainer in either case, since devcontainer support doesn't work on the M1 yet.

**Environment**
Information on your environment: Mac OS X Ventura, M1

VS Code
Version: 1.72.2 (Universal)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:30.254Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No

**Additional context**

Before running it, I had rm'ed the .azure folder in my local project, as I was trying to start completely from scratch. I don't think that should affect the permissions of .azd in my root folder, however!

**Comment by vhvb1989** [comment]
Thank you @pamelafox 

This is a known issue for customers who has previously used an old azd version in their environment. See the root cause here: https://github.com/Azure/azure-dev/issues/1041

**Comment by pamelafox** [comment]
Ah, thanks!
