### ISSUE TITLE
[Issue] Constantly increasing numbers for N of N completed

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#1073]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

```
azd version 0.4.0-beta.1 (commit 2bf7a529914d86d8e9f5d7b6f95a4f20a2351e01)
```

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 

```
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "containerapp": "0.3.11",
    "containerapp-compose": "0.2.2"
  }
}
```

**Describe the bug**

When `azd` is provisioning resources, it reports N of ~N completed, but ~N constantly increases. It seems like it'd be better to just not report ~N, if it's unknowable?

Screenshots from one session:

![Screenshot 2022-11-02 at 3 04 07 PM](https://user-images.githubusercontent.com/297042/199611340-119c536b-485e-4b8f-9c11-f1e76ba79732.png)

![Screenshot 2022-11-02 at 3 04 14 PM](https://user-images.githubusercontent.com/297042/199611338-4361edc1-da94-486e-8c82-bb9771b5689f.png)

![Screenshot 2022-11-02 at 3 04 21 PM](https://user-images.githubusercontent.com/297042/199611332-a73581fa-7b89-4821-b230-7762a222a1b1.png)

**To Reproduce**

I believe I've seen this on every `azd up`. 

1. git clone https://github.com/pamelafox/msdocs-django-postgresql-sample-app-azd/
2. Run azd up

**Expected behavior**

I expect to see a constant denominator.

**Environment**
Information on your environment: Mac OS X Ventura M1

VS Code
Version: 1.72.2 (Universal)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:30.254Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No

**Additional context**

I imagine the team is aware of this, but I couldn't find a related issue in the tracker.

**Comment by rajeshkamal5050** [comment]
@weikanglim @ellismg remember we having a similar request to show the total # of resources being provisioned upfront?

**Comment by rajeshkamal5050** [comment]
maybe there is a limitation on the ARM APIs to provide us deterministic set of resources being provisioned upfront and we get updated results from ARM. Will let the team chime-in

@weikanglim @ellismg @jongio

**Comment by weikanglim** [comment]
@rajeshkamal5050 The current way of how the progress it shown is indeed non-deterministic at provision time.

The way Azure provisioning works through ARM is that the client submits an ARM template JSON (which can be compiled from a Bicep template), and Azure will return a deployment. As the template is further evaluated, the deployment's state changes. We currently poll the deployment's state to get the number of resources being provisioned, and number of resources provisioned.

I don't think we can get a number of resources upfront that is also accurate given that the ARM template requires evaluation, and this evaluation itself could depend on querying other Azure resources that exist.

**Comment by pamelafox** [comment]
Hm, have you considered just not showing a number, versus showing the ever changing numbers? Currently, it feels buggy (for me at least), and doesn't seem to provide much information since it keeps changing.

**Comment by rajeshkamal5050** [comment]
@pamelafox with the new UX updates. This issue is not applicable anymore. Closing this.
