### ISSUE TITLE
`todo-python-mongo-aca` has func/.devcontainer.json

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1075]
Examine the file: https://github.com/Azure-Samples/todo-python-mongo-aca/blob/main/.devcontainer/func/devcontainer.json

Not sure why this file exists. The sample isn't a Azure Function sample, so I would not expect an Azure Function related devcontainer to show up

**Comment by jongio** [comment]
Looks like a bug in the repo.yaml file
