### ISSUE TITLE
[Issue] todo-java-mongo template runs error.

### ISSUE THREAD

**Issue by fangjian0423** [Azure/azure-dev#1077]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 0.4.0-beta.1 (commit 2bf7a529914d86d8e9f5d7b6f95a4f20a2351e01)

**Output from `az version`** 

```json
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.5",
    "spring": "1.1.10"
  }
}
```

**Describe the bug**

Command `azd up` get error message.

```bash
$ azd up
Error: required external tools are missing:
 - error checking for external tool Java JDK: converting to semver version fails: Version string empty
```

**To Reproduce**

Just follow [Get started using Azure Developer CLI](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/get-started?tabs=devcontainer&pivots=programming-language-java).

```bash
$ azd init --template todo-java-mongo
Initializing a new project in /Users/jimmy/...

? Please enter a new environment name: my-rg
? Please select an Azure Subscription to use: my-sub
? Please select an Azure location to use: 42. (US) East US 2 (eastus2)
$ azd up
Error: required external tools are missing:
 - error checking for external tool Java JDK: converting to semver version fails: Version string empty
```

**Expected behavior**

`azd up` works good, no error.

**Environment**

MacOS 12.6

**Additional context**

NodeJS template works good for me.

**Comment by fangjian0423** [comment]
`todo-java-mongo-aca` template works good for me.

Here are the steps:

```bash
$ azd init --template Azure-Samples/todo-java-mongo-aca
Initializing a new project in /Users/jimmy/...

? Please enter a new environment name: my-rg
? Please select an Azure Subscription to use: my-sub
? Please select an Azure location to use: 42. (US) East US 2 (eastus2)
$ azd up

Infrastructure provisioning plan completed successfully
Provisioning Azure resources can take some time.

You can view detailed progress in the Azure Portal:
...

Created Resource group: my-rg
Created Key vault: my-kv
...
```

**Comment by weikanglim** [comment]
@fangjian0423 Which JDK are you using?

The following steps would help:

1. Do you have `JAVA_HOME` specified? If so, what is the output of `$JAVA_HOME/bin/javac --version`?
2. Otherwise, do you have `javac` in `PATH`? What is the output of `javac --version`?

**Comment by weikanglim** [comment]
It's possible that older versions of `javac` didn't include `--version` as a flag. 

Example:
https://docs.oracle.com/javase/1.5.0/docs/tooldocs/windows/javac.html

And if so, this error is indicating it's an old version of JDK that will be fixed by installing a 17+ JDK version.

**Comment by fangjian0423** [comment]
hi @weikanglim 

This is the output of each commands:

```bash
$ echo $JAVA_HOME
/Users/jimmy/.sdkman/candidates/java/current
$ $JAVA_HOME/bin/java -version
java version "19" 2022-09-20
Java(TM) SE Runtime Environment (build 19+36-2238)
Java HotSpot(TM) 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)
$ $JAVA_HOME/bin/javac -version
javac 19
$ javac -version
javac 19
```

It's very confuse that `todo-java-mongo-aca` template works good for me. why `todo-java-mongo` not good?

**Comment by vhvb1989** [comment]
> It's very confuse that todo-java-mongo-aca template works good for me. why todo-java-mongo not good?

the `todo-java-mongo-aca` depends on Docker, and on the docker file that is on the template. `aca` stands for `Azure Container Apps`. `azd` runs docker to build a container which contains all the required dependencies (like Java) to build and run the application.  Once the container is built, it is pushed to an Azure registry.

So, in summary, you don't need Java to be locally installed when using `aca`. Java, and any other dependencies would be inside the container.

**Comment by vhvb1989** [comment]
One possible workaround (for now) is to use [OpenJDk](https://jdk.java.net/19/), which would give you the expected version output:
![image](https://user-images.githubusercontent.com/24213737/199871442-4abe4bc1-5eb3-4cf1-a4fc-c5989c874026.png)

This is only while we update `azd` to support this other output

**Comment by fangjian0423** [comment]
Thank you @vhvb1989 , when change JDK version to OpenJDK 19.0.1 (OpenJDK 19 still get the same error), it works good 😄

**Comment by vhvb1989** [comment]
Let's keep it open. We need to fix it for version 19, as it's a valid version
