### ISSUE TITLE
[Issue] Community Team Feedback - winget installer, need linux apt and homebrew

### ISSUE THREAD

**Issue by spboyer** [Azure/azure-dev#108]
"scary to copy paste" - `powershell -c "Set-ExecutionPolicy Bypass Process -Force; irm '[https://aka.ms/install-azd.ps1'](https://aka.ms/install-azd.ps1%27) | iex"`

Why don't we have `winget install azd` ?

"We need linux, homebrew, apt...these are most important"

**Comment by spboyer** [comment]
Also homebrew/linuxbrew for Mac and WSL

**Comment by rajeshkamal5050** [comment]
Closing this in favor of https://github.com/Azure/azure-dev-pr/issues/1322

**Comment by tebeco** [comment]
wrong link @rajeshkamal5050 ?
![image](https://user-images.githubusercontent.com/2266487/192097549-949a8708-a7e3-41dc-8b46-17f899cbe2c5.png)
