### ISSUE TITLE
December doc plan

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#1098]
Following doc updates are needed for Jan 11 release
- [x] update how to azdev-ify in dev hub  (@hhunter-ms ) - done

Dependency on release in Jan. Point to release branch: `release-azd-updates`
- [x] #1149 
  - PR in DevHub: MicrosoftDocs/azure-dev-docs-pr#3957
- [x] #1212 
  - PR in DevHub: MicrosoftDocs/azure-dev-docs-pr#3983
- [x] #1227
   - PR in DevHub: MicrosoftDocs/azure-dev-docs-pr#3842
- [x] #1281 
   - PR for DevHub: MicrosoftDocs/azure-dev-docs-pr#3842
- [x] #1283
   - PR in DevHub: MicrosoftDocs/azure-dev-docs-pr#3973
- [x] #1286 
   - PR in DevHub: MicrosoftDocs/azure-dev-docs-pr#3978

- [x] Updates for MSI install
  - [x] PR in DevHub: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4028

Push from `release-azd-updates` branch to live on 1/11/23:
- [x] PR: MicrosoftDocs/azure-dev-docs-pr#4042

**Comment by hhunter-ms** [comment]
FYI, release branch: https://github.com/MicrosoftDocs/azure-dev-docs-pr/tree/release-azd-updates

**Comment by jongio** [comment]
I reviewed all PRs.  They look good to me.

**Comment by puicchan** [comment]
Completed and merged.
