### ISSUE TITLE
`azd init` ux minor refinements

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1106]
## Issue 1: Warning prompt for overriding files

I created a `.gitignore` file before running `azd init`. This was the prompt I was shown:

![image](https://user-images.githubusercontent.com/2322434/200684055-7d91d5c2-8ebf-4364-a85d-3881f12f0977.png)

The UX looks off to me (could just be me). I also wonder if we should breaking apart `azd init` into 
1. Downloading code to temp directory...
2. Copying files to `d:\repos\azd-sources\empty`

which this prompt would come in.

## Issue 2: Running `init` on an existing directory with `azure.yaml` defined

The "Initializing a project" header isn't printed here, which the indented "Downloading template code" seems out-of-place

![image](https://user-images.githubusercontent.com/2322434/200684870-b577f684-116c-4c30-a5df-70669c19dd7e.png)

**Comment by weikanglim** [comment]
@Austinauth @vhvb1989 for quick thoughts. I hit these issues while trying to make suggestions for `azd init` to handle git repositories, just trying to see if these are indeed the intended UX with the new changes.

**Comment by vhvb1989** [comment]
nice catch.
I'll add the warning formatting to them and post a video for @Austinauth to review

**Comment by weikanglim** [comment]
@Austinauth I like it. The extra spacing + warning highlight definitely helps separate out the different elements.

I think if we wanted to hide the extra task, we could rearrange it so that the prompt appears before we say we've downloaded the template code to `<path>`

Something like:

```
WARNING: the following files will be overwritten..
* .gitignore

? Overwrite files

"Done: Downloading template code to `<path>`"
```

**Comment by Austinauth** [comment]
@weikanglim If that's possible I think thats a great suggestion.

**Comment by weikanglim** [comment]
Another thing that @ellismg and I noticed in https://github.com/Azure/azure-dev/pull/1285#discussion_r1051229348_ is that we currently print out the message "Creating a new azure.yaml file", as a spinner step. From a technical point of view, it seems odd because this is an extremely fast operation, which usually fits under a "log message" category instead of a spinner.

**Comment by Austinauth** [comment]
If I'm understanding the scenario you're describing you're expecting success here to be styled as a log message rather than a completed item (✓ Done) in a progress report? 

There are advantages for displaying the completion of this step in the way that we have (progress report style), but I can see why this might seem odd at first glance since the loading step is almost instantaneous.

@weikanglim if possible can you share a visual of your example? I want to make sure I understand the issue entirely before giving my complete thoughts.

**Comment by vhvb1989** [comment]
@Austinauth , while I create a PR for the issue #1, can you review and provide the expected flow for issue #2 ?

`Issue 2: Running init on an existing directory with azure.yaml defined` (see issue description)

Thank you

**Comment by vhvb1989** [comment]
Looking the code and the current implementation, this issue has been already addressed by @weikanglim . Thank you <3
