### ISSUE TITLE
azd env does not read explicit parameters correctly

### ISSUE THREAD

**Issue by abpiskunov** [Azure/azure-dev#1109]
Here is what we pass:

# azd env new --environment rtrtrgfgftrtrtrgfgfg --subscription 07268dd7-4c50-434b-b1ff-67b8164edb41 --location japaneast --cwd Z:\test\azdev\CosmosDBApp --no-prompt

ERROR: creating new environment: reading environment name: no default response for prompt 'Please enter a new environment name:'

Here is the help message suggesting that we doing everything right... 

antonpis@AP-DESK2 C:\Users\antonpis
# azd env new --help
Create a new environment.

Usage:
  azd env new <environment> [flags]

Flags:
  -h, --help                  Gets help for new.
  -l, --location string       Azure location for the new environment
      --subscription string   Name or ID of an Azure subscription to use for the new environment

Global Flags:
  -C, --cwd string           Sets the current working directory.
      --debug                Enables debugging and diagnostics logging.
  -e, --environment string   The name of the environment to use.
      --no-prompt            Accepts the default value instead of prompting, or it fails if there is no default.

Please let us know how we are doing: https://aka.ms/azure-dev/hats

**Comment by ellismg** [comment]
For some more context, on @abpiskunov's case he's running azd programmatically from within VS, where there's no direct connection to the user (we are run in a background terminal), hence the `--no-prompt`.

**Comment by abpiskunov** [comment]
it starts interactive mode. We are trying to avoid interactive mode explicitly by passing --no-prompt from VS.

**Comment by vhvb1989** [comment]
after our last [update](https://github.com/Azure/azure-dev/blob/main/cli/azd/CHANGELOG.md#breaking-changes), you need to change from:
`azd env new --environment rtrtrgfgftrtrtrgfgfg`
to:
`azd env new rtrtrgfgftrtrtrgfgfg`

**Comment by abpiskunov** [comment]
then help message should also be changed?

**Comment by weikanglim** [comment]
@abpiskunov Are you running on the `daily` build of `azd`? That change has not yet been released to `latest` -- hence I was hesitant to suggest that as the issue.

Also, the help text looks like the following for me `azd env new <environment> [flags]` which is indeed correct:

```
PS D:\repos\azd-sources\new-initr> azd env new --help
Create a new environment.

Usage:
  azd env new <environment> [flags]

Flags:
  -h, --help                  Gets help for new.
  -l, --location string       Azure location for the new environment
      --subscription string   Name or ID of an Azure subscription to use for the new environment

Global Flags:
  -C, --cwd string           Sets the current working directory.
      --debug                Enables debugging and diagnostics logging.
  -e, --environment string   The name of the environment to use.
      --no-prompt            Accepts the default value instead of prompting, or it fails if there is no default.

Please let us know how we are doing: https://aka.ms/azure-dev/hats
```

Unfortunately, `-e` is there as a global option that controls what environment the command runs under. In this case, it has no effect for `azd env new`

**Comment by abpiskunov** [comment]
i downloaded latest daily couple hours ago

**Comment by abpiskunov** [comment]
it has this part in it:  -e, --environment string   The name of the environment to use.

**Comment by abpiskunov** [comment]
Yes it does, however it also print --environment as an optional parameter.. If it is not actionable it should not be printed.

**Comment by weikanglim** [comment]
I agree completely. We'll figure out an improvement here.

**Comment by weikanglim** [comment]
`azd env new` (and other commands) no longer include `-e` as a flag

Updated usage:

https://github.com/Azure/azure-dev/blob/2b121e92c266fcfd35bdbfd74ee5c6af57776a10/cli/azd/cmd/testdata/TestUsage-azd-env-new.snap

Closing this issue.
