### ISSUE TITLE
[Issue] Microsoft.Web/sites does not respect ipSecurityRestrictions For Deny All

### ISSUE THREAD

**Issue by aolszowka** [Azure/azure-dev#1112]
I recognize that this might not be the correct repository to submit this to, if I could be pointed in the right direction, I would appreciate it.

**Describe the bug**
I believe I have found a corner case in creating a new `Microsoft.Web/sites` resource in ARM wherein `ipSecurityRestrictions` is not respected when attempting to block all traffic when created without additional firewall rules.

**To Reproduce**
The following ARM Template will reproduce the issue; you may need to generate yourself a new GUID to allow the site name to be Globally Unique:

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
    },
    "variables": {
        "guidToUse": "f6358587-2652-41f2-92b0-932e0d9a50d8",
        "serverFarmName": "[concat(variables('guidToUse'), '-sf')]",
        "websiteName": "[concat(variables('guidToUse'), '-ws')]"
    },
    "resources": [
        {
            "type": "Microsoft.Web/serverfarms",
            "apiVersion": "2022-03-01",
            "name": "[variables('serverFarmName')]",
            "location": "northcentralus",
            "sku": {
                "name": "F1"
            },
            "properties": {
            }
        },
        {
            "type": "Microsoft.Web/sites",
            "apiVersion": "2022-03-01",
            "name": "[variables('websiteName')]",
            "location": "northcentralus",
            "dependsOn": [
                "[resourceId('Microsoft.Web/serverfarms', variables('serverFarmName'))]"
            ],
            "properties": {
                "siteConfig": {
                    "ipSecurityRestrictions": [
                        {
                            "ipAddress": "Any",
                            "action": "Deny",
                            "priority": 2147483647,
                            "name": "Deny all",
                            "description": "Deny all access"
                        }
                    ],
                    "scmIpSecurityRestrictions": [
                        {
                            "ipAddress": "Any",
                            "action": "Allow",
                            "priority": 2147483647,
                            "name": "Allow all",
                            "description": "Allow all access"
                        }
                    ]
                },
                "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', variables('serverFarmName'))]"
            }
        }
    ]
}
```

**Expected behavior**
I would expect Access Restrictions for this deployed site to be set to `Deny`:

![image](https://user-images.githubusercontent.com/2592881/200897305-ccfa91a9-cf8a-4428-934d-47fb3ee7b7e9.png)

**Additional context**
Interestingly enough if you configure this via the Console like so:

![image](https://user-images.githubusercontent.com/2592881/200897620-a555a22a-3082-46a8-9471-bcbf3be71f29.png)

These changes will apply:

![image](https://user-images.githubusercontent.com/2592881/200897866-eda438be-d16c-42dc-8477-dd1d237d5b73.png)

Exporting an ARM Template from this site will generate a very similar template which if you attempt to redeploy does not work.

Furthermore, if you add a single rule this appears to work as well, I suspect that most people are adding in an allow rule of some sort which is why this was never caught in testing/is a corner case:

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
    },
    "variables": {
        "guidToUse": "f6358587-2652-41f2-92b0-932e0d9a50d8",
        "serverFarmName": "[concat(variables('guidToUse'), '-sf')]",
        "websiteName": "[concat(variables('guidToUse'), '-ws')]"
    },
    "resources": [
        {
            "type": "Microsoft.Web/serverfarms",
            "apiVersion": "2022-03-01",
            "name": "[variables('serverFarmName')]",
            "location": "northcentralus",
            "sku": {
                "name": "F1"
            },
            "properties": {
            }
        },
        {
            "type": "Microsoft.Web/sites",
            "apiVersion": "2022-03-01",
            "name": "[variables('websiteName')]",
            "location": "northcentralus",
            "dependsOn": [
                "[resourceId('Microsoft.Web/serverfarms', variables('serverFarmName'))]"
            ],
            "properties": {
                "siteConfig": {
                    "ipSecurityRestrictions": [
                        {
                            "action": "Allow",
                            "ipAddress": "93.184.216.34/32",
                            "priority": 100,
                            "name": "Allow Example.com's IP",
                            "description": "Test Allowing IP"
                        },
                        {
                            "ipAddress": "Any",
                            "action": "Deny",
                            "priority": 2147483647,
                            "name": "Deny all",
                            "description": "Deny all access"
                        }
                    ],
                    "scmIpSecurityRestrictions": [
                        {
                            "ipAddress": "Any",
                            "action": "Allow",
                            "priority": 2147483647,
                            "name": "Allow all",
                            "description": "Allow all access"
                        }
                    ]
                },
                "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', variables('serverFarmName'))]"
            }
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/2592881/200898711-d13030f5-d59a-487c-ae26-faad7d047687.png)

**Comment by jongio** [comment]
@alex-frankel - Do you know where this should be filed?

**Comment by alex-frankel** [comment]
This should be filed as an Azure support ticket so it can be routed to the Web Resource Provider team. Tagging @naveedaz / @seligj95 as FYI

**Comment by seligj95** [comment]
I actually came across this today with a deployment I was working on. Please open the support ticket. I'll also try to route this internally.

**Comment by aolszowka** [comment]
Done I've got ticket 2211090010003456 assigned let's see where it goes.

**Comment by madsd** [comment]
No need for a support ticket, @seligj95  @aolszowka. You cannot define a Deny All rule through the ipSecurityRestrictions property. To configure Deny All, you need to set ipSecurityRestrictionsDefaultAction to Deny

**Comment by aolszowka** [comment]
@madsd Interesting; can you point out where that is documented? I didn't see anything on either of these pages:

https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites?pivots=deployment-language-arm-template
https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites/config-web?pivots=deployment-language-arm-template

It looks like someone noticed it missing in the Bicep world 22 days ago: https://github.com/Azure/bicep/issues/784#issuecomment-1282208703

Should I open a support ticket on the documentation to see what happened?

**Comment by madsd** [comment]
Not sure how that part of the documentation is updated. It is a site config property. You can see the property in JSON view in the portal, or doing a GET REST call on a site resource

**Comment by alex-frankel** [comment]
@madsd the documentation is based off of the PUT schema defined in the resource type's swagger spec. Should a PUT with those settings fail instead of silently ignoring the desired properties?

**Comment by madsd** [comment]
Deny All and Allow All cannot be configured in the rule list itself. It is based on the DefaultAction (if configured) or if the list has rules or not, if DefaultAction is not configured.

**Comment by alex-frankel** [comment]
Based on this statement:
>cannot define a Deny All rule through the ipSecurityRestrictions property

It sounds like this setting below is being ignored:

```json
                "siteConfig": {
                    "ipSecurityRestrictions": [
                        {
                            "ipAddress": "Any",
                            "action": "Deny",
                            "priority": 2147483647,
                            "name": "Deny all",
                            "description": "Deny all access"
                        }
                    ],
```

Would you say that is right? 

If so, I am wondering if a PUT with those settings should fail. Today it appears to succeed, even though the setting is not being applied.

**Comment by aolszowka** [comment]
Closing the Loop on my end, support confirmed the above and opened up https://github.com/MicrosoftDocs/azure-docs/issues/101666.

As far as an error, that probably would be helpful but doesn't sound like its in the cards. Thank you for all your help.
