### ISSUE TITLE
[devcontainer and codespace]The command "az login" failed

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-dev#1121]
**Describe the issue:**
The command `az login` failed.

**Repro Steps:**
1. Open the template, such as `todo-python-mongo-aca` in `DevContainer` or `Codespace` with browser.
2. Excute command `az login`

**Error Message:**
![image](https://user-images.githubusercontent.com/74638143/201022467-152d5744-f60d-4adc-a5c9-4a63dffd86c6.png)

**Environment:**
- 1. OS: DevContainer
 https://github.com/azure-samples/todo-python-mongo 
 https://github.com/azure-samples/todo-python-mongo-aca  
 https://github.com/azure-samples/todo-python-mongo-swa-func 
 https://github.com/Azure-Samples/todo-python-mongo-terraform 
   2. OS: Codesapce
 https://github.com/azure-samples/todo-python-mongo 
 https://github.com/azure-samples/todo-python-mongo-aca  
 https://github.com/azure-samples/todo-python-mongo-swa-func 
 https://github.com/Azure-Samples/todo-python-mongo-terraform 
 https://github.com/azure-samples/todo-nodejs-mongo 
 https://github.com/azure-samples/todo-nodejs-mongo-aca  
 https://github.com/azure-samples/todo-nodejs-mongo-swa-func 
 https://github.com/Azure-Samples/todo-nodejs-mongo-terraform 
- Azd version: 0.4.0-beta.1-daily.1974838 (commit 8949cee8ebb2bec1de772c3dcbe71f0cb51485d5)

**Expected behavior:**
The command `az login` can run successfully.

@rajeshkamal5050  for notification.

**Comment by rajeshkamal5050** [comment]
@weikanglim can you take a look? looks like something regressed? seems similar to the https://github.com/Azure/azure-dev/issues/370#issuecomment-1308352777

**Comment by weikanglim** [comment]
I can confirm this is indeed related to the devcontainer feature `ghcr.io/devcontainers/features/python:1.0.11` release. 

Reverting to `ghcr.io/devcontainers/features/python:1.0.10` works.

**Comment by weikanglim** [comment]
To workaround the curernt issue:

Change the python feature in `devcontainer.json`, like the following:
https://github.com/Azure/azure-dev/blob/0ffb37f94688800e6d1e4189879eb59973071c23/templates/common/.devcontainer/devcontainer.json/python/devcontainer.json#L23

to:

`ghcr.io/devcontainers/features/python:1.0.10`
