### ISSUE TITLE
[Issue] azd deploy failed

### ISSUE THREAD

**Issue by doggy8088** [Azure/azure-dev#113]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

```txt
azd version 0.1.0-beta.2 (commit 13ec2b11aa755b11640fa16b8664cb8741d5d300)
```

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 

```txt
Azure-cli    Azure-cli-core    Azure-cli-telemetry
-----------  ----------------  ---------------------
2.33.1       2.33.1            1.0.6
```

**Describe the bug**
Description of issue you're seeing...

```log
Deploying service api
Error: deploying service: deploying service api package: deploying service api: failed running az deployment source config-zip: exit code: 1, stdout: , stderr: ERROR: There may be an ongoing deployment or your app setting has WEBSITE_RUN_FROM_PACKAGE. Please track your deployment in https://app-api-uyicu7wr543da.scm.azurewebsites.net/api/deployments/latest and ensure the WEBSITE_RUN_FROM_PACKAGE app setting is removed. Use 'az webapp config appsettings list --name MyWebapp --resource-group MyResourceGroup --subscription MySubscription' to list app settings and 'az webapp config appsettings delete --name MyWebApp --resource-group MyResourceGroup --setting-names <setting-names> to delete them.
: exit status 1
````

The error message is not helping in my case. I don't have `WEBSITE_RUN_FROM_PACKAGE` in my appsettings of the `api` webapp. 

**To Reproduce**
Steps to reproduce the behavior...

```sh
azd init -e azd-demo1 -t Azure-Samples/todo-nodejs-mongo
azd up
azd up (When started 5 seconds, hit Ctrl-C break)
azd deploy
```

**Expected behavior**

The CLI has been canceled. The deployment seems keep in `Pending` state. I don't know how to stop it.

![image](https://user-images.githubusercontent.com/88981/179267296-d5eb31a1-2d32-408e-bd9e-695055c44476.png)

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

I'm not using IDE. Simply CLI.

**Additional context**

**Comment by vhvb1989** [comment]
Hello @doggy8088 , thank you for trying `azd` and for filling the issue.

I am trying to reproduce with no success over here.  Are you able to reproduce consistently?  or was this a one time issue?

I tried two different approaches based on the `repro` steps provided. The first one cancelling `azp up` after 5 seconds, then using `azd deploy`. 
For this approach, `azd deploy` fails with an error about `resources are not found` , as the provisioning of resources is still happening. So, this is expected.
For the second approach, I ran `azd up` and let it finish. Then I ran `azd up` again and I cancelled it after 5 seconds.  And then I ran `azd deploy`.  But this time deploy works fine.

Please let me know if you are able to reproduce this. If yes, can you run `azd` commands adding `--debug`  and share the logs? 

Thank you.

**Comment by doggy8088** [comment]
OK. I'll take a try another time. Thanks.
