### ISSUE TITLE
Can not find Azure developer environments.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-dev#1135]
**Describe the issue:**
`Task` in VS Code cannot be started normally, prompting `No Azure developer environments found`.

**Repro Steps:**

1. Open the project in VS Code.
2. Execute command: `bash ./test-templates.sh -c false -t Azure-Samples/todo-nodejs-mongo -b pr/1129 -s ***`.
3. Hit F1, Run Task, Start API and Web, you will be prompted as below:
![image](https://user-images.githubusercontent.com/81678720/201307388-a99a2fe4-e35a-4784-abbd-6f09ba3aa2a7.png)
But actually, we already have the env:
![image](https://user-images.githubusercontent.com/81678720/201308184-5cbaaace-12e0-47eb-8503-77e9d13c9ff2.png)

**Environments:**
OS: Codespaces, WSL, Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code
Template: https://github.com/azure-samples/todo-nodejs-mongo
Azd version: 0.4.0-beta.1-pr.1982037 (commit 0cb9c7c50e1fcdd8b0821587548e8c2a57023666)
Branch: [pr/1129](https://github.com/Azure/azure-dev/pull/1129)
**With Az CLI** and **Without Az CLI**

**Expected behavior:**
`Task` can be started normally.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@ellismg @karolz-ms @philliphoff can you triage if this is a generic VS Code issue or anything w.r.t to the azd authn changes?

Note: this failure was on the PR branch https://github.com/Azure/azure-dev/pull/1129

**Comment by philliphoff** [comment]
@rajeshkamal5050 I see the same error when using the PR branch version of `azd`, but do *not* see any issues when using the latest released version of `azd`.

**Comment by philliphoff** [comment]
@rajeshkamal5050 With the PR branch version of `azd`, listing environments results in a "not logged in" error:

```
% azd env list --output json
Error: fetching current user: not logged in, run `azd login` to login
```

**Comment by karolz-ms** [comment]
Looks like a bug introduced by latest authN changes. My understanding is listing environments should not trigger authentication. @ellismg

**Comment by karolz-ms** [comment]
That said, we might want to double check that "under the covers" invocations of `azd` by the extension do not include use cases that involve authentication. If there are such cases, we probably should have special handling for "not authenticated" error.

**Comment by philliphoff** [comment]
> If there are such cases, we probably should have special handling for "not authenticated" error.

Some of the results output/streaming that we've discussed previously should help with that.  For example, I'd expect that errors come back in a more structured way when using `--output json`.

**Comment by ellismg** [comment]
Thanks for the excellent debugging work here, @philliphoff and @karolz-ms and sorry to have broken you.  I opened #1138 which I think should address this issue.  Still working through writing a regression tests, but wanted to get something open.  I'll also add this fix to the PR branch, @zedy-wj.

**Comment by karolz-ms** [comment]
Thanks for quick turnaround @ellismg !!

**Comment by zedy-wj** [comment]
@ellismg - We retested according to your [pr/1138](https://github.com/Azure/azure-dev/pull/1138), but this issue still occurs.  Any ideas?

-  `azd` version: [pr/1138](https://github.com/Azure/azure-dev/pull/1138#issuecomment-1312281448) builds: 0.4.0-beta.1-pr.1984529 (commit bf0e47c39cc2177edfc1e47113a837152943f386)

Besides, when we do the **Azd Nov 16 Release - Manual Testing**, this issue also exists in all templates and environments.

- azd version:  Daily builds: 0.4.0-beta.1-daily.1984957(commit https://github.com/Azure/azure-dev/commit/92b9cbc1457adcf425edeacf390118a730d7cd0a)

- Environments: Codespaces, WSL, Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code

- Templates: 
https://github.com/Azure-Samples/todo-csharp-cosmos-sql
https://github.com/Azure-Samples/todo-nodejs-mongo
https://github.com/Azure-Samples/todo-nodejs-mongo-aca
https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func
https://github.com/Azure-Samples/todo-python-mongo
https://github.com/Azure-Samples/todo-python-mongo-aca
https://github.com/Azure-Samples/todo-python-mongo-swa-func
https://github.com/Azure-Samples/todo-csharp-sql
https://github.com/Azure-Samples/todo-python-mongo-terraform
https://github.com/Azure-Samples/todo-nodejs-mongo-terraform
https://github.com/Azure-Samples/todo-csharp-sql-swa-func
https://github.com/Azure-Samples/todo-java-mongo
https://github.com/Azure-Samples/todo-java-mongo-aca

**Comment by weikanglim** [comment]
Reproduced on daily build with template: https://github.com/Azure-Samples/todo-nodejs-mongo, template branch: staging

**Comment by weikanglim** [comment]
It's due to regression from #1108 where `azd` is incorrectly writing the final JSON output to `stderr`
