### ISSUE TITLE
azd pipeline config - Device is not in required device state: compliant

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-dev#1136]
**Describe the issue:**
The command `azd pipeline config` failed.

**Repro Steps:**
1. Run command: `bash ./test-templates.sh -c false -t Azure-Samples/todo-nodejs-mongo -b pr/1129`
2. Run command: `azd pipeline config` or `azd pipeline config --provider azdo`

**Error Message:**
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/74638143/201317628-969261c6-bf27-4529-98c3-4c17bbc57502.png)

**Environment:**
OS: devcontainer.
Template: https://github.com/azure-samples/todo-nodejs-mongo
azd version: 0.4.0-beta.1-pr.1982037 (commit 0cb9c7c50e1fcdd8b0821587548e8c2a57023666)
Branch: https://github.com/Azure/azure-dev/pull/1129

**Expected behavior:**
`azd pipeline config` or `azd pipeline config --provider azdo` can run successfully.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@ellismg @vhvb1989 can you triage if this is a generic pipeline issue or anything w.r.t to the azd authn changes?

Note: this failure was on the PR branch #1129

**Comment by vhvb1989** [comment]
@hongli750210 how are you doing auth?  Are you calling `azd login` ?  

I opened a template in a devcontainer and installed `azd` from this PR.  Then I tried `azd login` and I got:

![image](https://user-images.githubusercontent.com/24213737/201411667-7f8a2412-7d68-4e10-a562-718f7c5b8466.png)

**Comment by hongli750210** [comment]
@vhvb1989 
The command [ azd login ] will call the browser to complete user authentication, so I run this command in devcontainer with VS Code and loggin successfully, you can try this way.

**Comment by vhvb1989** [comment]
Yes. I was blocked by other issue from on my side, which was not allowing the browser to be launched.
I will try this again.
Thank you

**Comment by vhvb1989** [comment]
The azd version used to create this issue forces the device-code auth when azd is running in devcontainers (VSCode running in dev container).
Running `azd login` starts the device-code auth, asking user to open a browser and do the login with a code.
Hence, it is expected that azd fails to create a service principal later when using a Tenant with conditional access enabled (like Microsoft)
