### ISSUE TITLE
"azd login" is also required after "az login".

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-dev#1146]
**Describe the issue:**
`azd login` is also required after `az login`.
Last week we only needed `az login` for follow-up testing, but after `azd` was updated to the latest daily version(0.4.0-beta.1-daily.1984957 (commit 92b9cbc1457adcf425edeacf390118a730d7cd0a)) today, after `az login` it prompted that `not logged in, run azd login to login` when executed `bash ./test-templates.sh -c false -t <template_name> -s xxx`.

**Repro Steps:**

1. Download from daily builds: `curl -fsSL https://aka.ms/install-azd.sh | bash -s -- --version daily`
2. Login with `az login`
3. Run command `bash ./test-templates.sh -c false -t <template_name> -s xxx` and you will get the error: `not logged in, run azd login to login`
![image](https://user-images.githubusercontent.com/81678720/201601402-188a903f-79f0-4954-933c-47f25a700d96.png)

**Environments:**
OS: Codespaces, WSL, Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code
Template: All templates.
Branch: staging
Azd version: 0.4.0-beta.1-daily.1984957(commit 92b9cbc1457adcf425edeacf390118a730d7cd0a)

**Expected behavior:**
Run command `bash ./test-templates.sh -c false -t <template_name> -s xxx` can pass after `az login`.

@rajeshkamal5050 for notification.

**Comment by vhvb1989** [comment]
This is expected.  we no longer depend on `az login`

**Comment by vhvb1989** [comment]
If the test documentation/steps are asking for `az login`, we need to have that updated.
