### ISSUE TITLE
`azd init` can fail when switching accounts due to saved default subscription

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1148]
1. `azd login` with Account1
3. `azd init` and complete the initialization, selecting a subscription and location. This should save `default.subscription`.
4. `azd logout`
5. `azd login` with a different account, Account2, that does not have access to Account1's subscription
6. Run `azd init`

Expected:
`azd init` should succeed

Actual:
`azd init` fails with the following error:
```
? Please enter a new environment name: my-env-1
ERROR: loading environment: initializing environment: listing accounts: the subscription id '7c5b731d-a3c1-43b6-8aab-a8eb3e5fc173' is either invalid or you no longer have access.
                        Check your configuration with 'azd config list'. failed getting subscription for '7c5b731d-a3c1-43b6-8aab-a8eb3e5fc173'
```

Workaround:
Run `azd config reset`

I suspect we want to tie the default subscription to the user to avoid erroring out.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 is this similar to the issue which you were talking about during our PM <-> Engg discussion?

**Comment by vhvb1989** [comment]
yes, fixed by: https://github.com/Azure/azure-dev/pull/1415

**Comment by vhvb1989** [comment]
fixed by https://github.com/Azure/azure-dev/pull/1478
