### ISSUE TITLE
VS Code <-> Azd integration requires additional `az login` for local app development use-cases

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-dev#1157]
**Describe the issue:**
 Task on the api requires authentication. 

**Repro Steps:**

1. Open the project in VS Code.
2. Login with `azd login`.
3. Hit F1, Run Task, Start API and Web. During the api startup process, you will get the error as below:
![image](https://user-images.githubusercontent.com/81678720/201888027-8e220d1d-0a20-48da-aa23-79221b8ddd51.png)
Besides, if we execute `az login` according to the promption, this error can be fixed. But this operation is a bit strange because we have performed `azd login`.

**Environment:**
OS: Codespaces, WSL, Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code
Template: All templates.
Branch: [pr/1153](https://github.com/Azure/azure-dev/pull/1153)
Azd version: 0.4.0-beta.1-pr.1988386 (commit 7b6248aa6788d586bcf0b9a9491187866dad5cca)

**Expected behavior:**
After we `azd login`, we can start the api without other authentication.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
Do we now require **_az and azd login_** to be performed for the VS Code integration to work?

@ellismg can you triage this? cc: @karolz-ms @bwateratmsft

**Comment by karolz-ms** [comment]
@rajeshkamal5050 The `DefaultAzureCredential` that our templates use can fish for credentials from environment variables, VS Code/VS token store and Azure CLI credentials. It does not know anything about AZD credentials though.

It is really a design gap and there are many ways we could solve it. E.g. we could "teach" `DefaultAzureCredential` about AZD and its credential store. Or we could teach AZD how to launch a program and "inject" credentials into it--then VS Code and other tools leverage that. There are probably other options. We should have a discussion.

**Comment by rajeshkamal5050** [comment]
@karolz-ms  @bwateratmsft 

> Besides, if we execute az login according to the promption, this error can be fixed. But this operation is a bit strange because we have performed azd login.

Post the removal of Azure Azzount extension dependency https://github.com/Azure/azure-dev/pull/1159 will the above az login workaround still work?

**Comment by ellismg** [comment]
> Post the removal of Azure Account extension dependency https://github.com/Azure/azure-dev/pull/1159 will the above az login workaround still work?

Yes - it will.

**Comment by ellismg** [comment]
We had a discussion among the team today to figure out what to do here.  We are still noodling on what our right long-term plan is (should we try to get `azd` added to DefaultAzureCredential?  If so, do we need to GA before we do that?  Is there other stuff the identity team is working on).

Right now, we want to support the scenario where our templates are deployable and debugable from a clean machine, without having any other tools installed.  To support this, we plan to do the following work:

1. Build `azd get-access-token` which can be used to fetch a token for the current logged in user to AZD.
2. Create an `AzureDeveloperCLICredential` type, which shells out to `azd get-access-token` (this is similar to how AzureCLICredential works internally, we should be able to leverage much of that code).
3. Add this to our templates, replacing the use of DefaultAzureCredential with a ChainedTokenCredential that uses the new AzureDeveloperCLICredential and then falls back to DAC if that fails.

This is tactical set of work to unblock us releases these larger auth changes while we figure out what the right long term decision is here.

**Comment by zedy-wj** [comment]
@rajeshkamal5050 - This issue also occurs in other environments:

- OS: WSL, Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code, Codespaces


- Template: https://github.com/azure-samples/todo-csharp-cosmos-sql

- Branch: [pr/1130](https://github.com/Azure/azure-dev/pull/1130)

- Azd version: 0.4.0-beta.1-daily.1991269 (commit 27c40858a0ccb13d9084b175a5bda73ca4b5b554)

**Comment by v-xuto** [comment]
@rajeshkamal5050 This issue also occurs in the following cases:

- OS: WSL, Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code, Codespaces
- Template: All templates
   1. Except todo-python-mongo-terraform and todo-nodejs-mongo-terraform in all envs
   2. Except todo-python-mongo, todo-python-mongo-aca,todo-python-mongo-swa-func in Windows desktops
- Branch: Staging
- Azd version: 0.4.0-beta.2-daily.2010605 (commit https://github.com/Azure/azure-dev/commit/b6c8218e832d75a5eb5d0915016390347d3be29f)

**Comment by rajeshkamal5050** [comment]
@v-xuto fixes #1171 #1172 #1173 #1174 #1175 were made to handle this. Did you face this issue in the December iteration testing?

@ellismg for the upcoming Release 0.5(Jan1 11) with just `azd login` and custom cred handlers in just our templates. 

Until we get the cred handlers into SDK's. In the interim any options/thoughts for externally authored templates without custom credential handlers?

**Comment by v-xuto** [comment]
> @v-xuto fixes #1171 #1172 #1173 #1174 #1175 were made to handle this. Did you face this issue in the December iteration testing?
We didn't face this issue in the December iteration testing.

**Comment by rajeshkamal5050** [comment]
Closing since we did not face this during testing.
