### ISSUE TITLE
Add command to get current environment name

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1165]
When scripting it would be helpful to be able to get the current environment name without have to dig into the config.json file.

Something like `az account show`

**Comment by ellismg** [comment]
We already have `azd show` for use by tooling - maybe we can just add this to that.

**Comment by savannahostrowski** [comment]
Is this not handled by `azd env list` which updates as you set the use select the environment?

**Comment by jongio** [comment]
I wanted to get the name programmatically. With az cli I can use --query to get just the name, with azd I have to manually parse the results.  Maybe the answer is to support --query and return json.

**Comment by savannahostrowski** [comment]
Ah I see - that make sense. Thanks for clarifying.
