### ISSUE TITLE
Make tasks.json/launch.json more generic for easy re-use

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#1169]
When azdev-ifying a template, I should be able to add tasks.json/launch.json and can easily F5 to run and debug. 

Options:
- based on existing azd app-templates 
- VS Code extension to help me scaffold the tasks.json and launch.json files.

Today, it's not that easy to figure out what are the right pieces to pick.

**Comment by savannahostrowski** [comment]
@puicchan What specific problems are we seeing and trying to solve for here?

In talking with @bwateratmsft, it seems that reusability of these files within the same language is pretty high.

**Comment by bwateratmsft** [comment]
Somewhat related to #830.

**Comment by puicchan** [comment]
Closing in favor of https://github.com/Azure/azure-dev/issues/3960
