### ISSUE TITLE
Azdevify eShopOnContainers

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1182]
https://github.com/dotnet-architecture/eShopOnContainers

Let's convert this to aca and azdevify it.

**Comment by zedy-wj** [comment]
@jongio, @rajeshkamal5050 - This [repo](https://github.com/dotnet-architecture/eShopOnContainers) is not an Azure Sample. Do we still want to azdevify it?

**Comment by jongio** [comment]
Yes, please do a PR to the repo for this one.  Thanks

**Comment by zedy-wj** [comment]
@jongio, @rajeshkamal5050 - The [repo](https://github.com/dotnet-architecture/eShopOnContainers) has been achieved. And eShop has moved to [here](https://github.com/dotnet/eShop). Do we need to azdevify the new repo now?

**Comment by jongio** [comment]
@zedy-wj @v-xuto - The .NET team has decided to only publish the Aspire version of eShop.  So the whole effort to azdevify eShop can stop.  Thank you for the effort, but we can close this now.

cc @rajeshkamal5050
