### ISSUE TITLE
Deployment 'apim-deployment' could not be found.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-dev#1184]
**Describe the issue:**
When we set variable `useAPIM` to `false`, Azure API Management service will not be created. But when executing `azd up`, an error is reported: `DeploymentNotFound: Deployment 'apim-deployment' could not be found.`

**Repro Steps:**
1. Login with `azd login`.
2. Run command: `azd init`.
3. Run command: `azd up` and you will see:
![image](https://user-images.githubusercontent.com/81678720/202657010-d1e1dc6c-7a73-4ef8-ae29-708f39a85eb8.png)

**Environment:**
OS: WSL, Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code, Codespaces
Template: https://github.com/Azure-Samples/todo-csharp-cosmos-sql
Branch: [pr/1130](https://github.com/Azure/azure-dev/pull/1130)
Azd version: 0.4.0-beta.1-daily.1991269 (commit 27c40858a0ccb13d9084b175a5bda73ca4b5b554)

**Expected behavior:**
`azd up` can pass.

@jongio, @rajeshkamal5050 for notification.

**Comment by vieiraae** [comment]
Seems that we are not considering conditional resource deployment

**Comment by weikanglim** [comment]
@zedy-wj This is fixed now. Can you run another test pass on CSharp projects for pr/1130?

**Comment by zedy-wj** [comment]
@weikanglim - We are testing based on the latest daily version of azd, this issue will not reproduce. We will closed it, thanks!
