### ISSUE TITLE
[Issue] Display endpoint of API Management service OR provide way to override endpoint URIs

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#1192]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

```
azd version 0.4.0-beta.1 (commit 2bf7a529914d86d8e9f5d7b6f95a4f20a2351e01)
```

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 

```
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

**Describe the bug**

I have created a template that deploys an API Management service in front of an authentication-required Azure Function. The function endpoint won't work without a function-key (it's `authLevel` is "function"), so the API Management documentation endpoint is the more appropriate endpoint to display. 

I was hoping that I could perhaps use Bicep outputs to override the displayed output, since I wouldn't expect you to guess the optimal URL (i.e. AZURE_ENDPOINT_URI = apimService.properties.url or some such), but I don't see that sort of mechanism in the code.

Or, perhaps there could be a way to turn off the endpoint display?

For now, I will direct people in the readme about how to find the docs.

**To Reproduce**

Run 'azd up' for https://github.com/pamelafox/fastapi-azure-function-apim

**Comment by pamelafox** [comment]
Neat, so we just need to output SERVICE_API_ENDPOINTS ?
Or actually, it looks more flexible than that, SERVICE_<SERVICENAME>_<PROPERTYNAME>?

Is there an issue about documenting this?

**Comment by weikanglim** [comment]
@pamelafox This fix was released today, and mentioned in the release [notes](https://github.com/Azure/azure-dev/releases/tag/azure-dev-cli_0.5.0-beta.1) but not yet in user-facing docs. We're still figuring out how we can best start documenting well-known input/output variables.

For any service you create, you can specify a bicep/terraform output `SERVICE_<name>_ENDPOINTS`. `<name>` is the service name specified in `azure.yaml`. The variable should be a list/array.

Here's an [example](https://github.com/Azure-Samples/todo-java-mongo-aca/blob/a16ceb9a4447604c998023ae564a9e065702de57/infra/main.bicep#L194). If one isn't specified, `azd` will perform the default host-specific detection for you.

**Comment by pamelafox** [comment]
Works great! That improves the experience for my APIM sample. Thanks!
(Maybe something to note in docs is that it has to be set in main.bicep, setting it in resources.bicep didn't affect anything.

Diff for my sample:
https://github.com/pamelafox/fastapi-azure-function-apim/commit/dbf31e0436c441c5ebdd0254224f8467db20d797
