### ISSUE TITLE
Issue forking template due to exceeding description length

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1199]
@savannahostrowski That's odd. I was able to create a fork and open in Codespace.

If I needed to guess, that error is indeed from our GitHub repository's descriptions being over the validated length -- this either is a new requirement, or we had created this through our innersource Portal which may have bypassed the requirements.

The repository description on https://github.com/Azure-Samples/todo-python-mongo-aca is:

```
A complete ToDo application that includes everything you need to build, deploy, and monitor an Azure solution.
This application uses the Azure Developer CLI (azd) to get you up and running on Azure quickly, React.js for the Web application, Python (FastAPI) for the API, Azure Cosmos DB API for MongoDB for storage, and Azure Monitor for monitoring and logging.
```

Length = 361

I wonder if we can shorten the description to the thing that is different about this repository vs. others. The full description is still in the readme file.

```
A complete ToDo application that includes everything you need to build, deploy, and monitor an Azure solution.
This application uses the Azure Developer CLI (azd) to get you up and running on Azure quickly, Python (FastAPI) for the API on Azure Container Apps, Azure Cosmos DB API for MongoDB for storage.
```

_Originally posted by @weikanglim in https://github.com/Azure/azure-dev/issues/370#issuecomment-1314565655_

**Comment by rajeshkamal5050** [comment]
@hemarina please you work with @savannahostrowski to update and shorten the descriptions.

**Comment by weikanglim** [comment]
Verified all repositories have shortened descriptions. Closing out.
