### ISSUE TITLE
Cannot connect to the Docker in Cloud Shell

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-dev#1206]
**Describe the issue:**
Can't start the docker in Cloud Shell.

**Repro Steps:**
1. Login to Azure Portal
2. Open `Cloud Shell` terminal
3. Installation: to install run “mkdir -b ~/bin && curl -fsSL https://aka.ms/install-azd.sh | bash -s -- --install-folder ~/bin”
4. Create a folder for test templates 
5. Run command `azd init -t <template>` 
6. Run command  `azd up`

**Error Message:**
![image](https://user-images.githubusercontent.com/74638143/203503461-d63e1ee5-d63e-4e10-9134-c7f856556ce3.png)

**Error Trace:**
After investigation, docker needs to be started, but we are neither the root user nor do we know the root password, so we can't start docker.
![image](https://user-images.githubusercontent.com/74638143/203504715-f14e8167-b26a-4ec5-ab3d-ee6c38e2816a.png)

**Environment:**
OS: Cloud Shell
Template: 
- https://github.com/Azure-Samples/todo-nodejs-mongo-aca
- https://github.com/Azure-Samples/todo-python-mongo-aca

Azd version: 0.4.0-beta.1 (commit 2bf7a529914d86d8e9f5d7b6f95a4f20a2351e01)

**Expected behavior:**
The docker service can successfully start.

@danieljurek for notification.

**Comment by rajeshkamal5050** [comment]
@danieljurek should we reach-out to the Cloud Shell team on this for making our ACA templates work in Cloud Shell?

**Comment by danieljurek** [comment]
Possible solution... use an ACR task to build in the ACR instance. https://learn.microsoft.com/en-us/azure/container-registry/container-registry-tasks-overview#quick-task

**Comment by savannahostrowski** [comment]
Pinged the Cosmos team to check in on if there are particular scenarios they are targeting, which might help inform our path forward.

**Comment by savannahostrowski** [comment]
I think we can proceed and document this as a known limitation for now. I'll mark as docs, cc: @gkulin

**Comment by rajeshkamal5050** [comment]
Should be added to doc in the release which contains CloudShell support in Azd. Currently it is blocked with the JDK upgrade #1207

**Comment by v-xuto** [comment]
@danieljurek The same issue also occurs in the following cases, failed to connect to the Docker.
- **OS:** CloudShell.
- **Azd version:** 0.6.0-beta.2 (commit https://github.com/Azure/azure-dev/commit/c4a201e55a13eba77f9037b296a90e0f81b00dbe)
- **Error Message:**
![image](https://user-images.githubusercontent.com/57166602/218671197-42d0f893-5e5f-436b-bf53-d354f45be14b.png)
- **Repro Steps:**
1.Run `git clone https://github.com/danieljurek/CloudShell.git -b add-azd-validation`
2.Run `docker build -f ./linux/base.Dockerfile -t base_cloudshell .`

**Comment by gkulin** [comment]
closed with https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4193

it was added to the troubleshooting page: https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/troubleshoot#cannot-connect-to-the-docker-daemon-in-cloud-shell
