### ISSUE TITLE
CloudShell: JDK version not high enough

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#1207]
When attempting to run `azd up` on java templates there is an error: 

```
required external tools are missing: - need at least version 17.0.0 or later of Java JDK installed. Visit the website for your installed JDK to upgrade Java JDK version"
```

Running `java --version` in CloudShell reveals: 

```
$ java --version
openjdk 11.0.17 2022-10-18 LTS
OpenJDK Runtime Environment Microsoft-6841889 (build 11.0.17+8-LTS)
OpenJDK 64-Bit Server VM Microsoft-6841889 (build 11.0.17+8-LTS, mixed mode)
```

@weikanglim -- Would our samples be able to run with the tools in place on CloudShell? 

Repro steps: 

1. Launch CloudShell session 
2. Install azd in user folder `mkdir -b ~/bin && curl -fsSL https://aka.ms/install-azd.sh | bash -s -- --install-folder ~/bin”` 
3. Create a folder for test templates and cd into that folder
4. `azd init -t todo-java-mongo` 
5. `azd login --use-device-code` 
6. `azd up`

Expected: Deploy succeeds
Actual: Deploy fails with above error

**Comment by rajeshkamal5050** [comment]
@weikanglim https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions#jdk-version-range based on the spring vs jdk compatibility matrix. Can we make it work in cloud shell by moving our templates jdk deps down? Is that even possible?

**Comment by rajeshkamal5050** [comment]
@danieljurek can we talk to CloudShell team about bumping JDK to 17?

**Comment by weikanglim** [comment]
@rajeshkamal5050 

Our todo sample depends on spring-boot-starter 2.7.4 -> Spring framework 5.3 -> Java 8, 11, 17 LTS.

We do want to migrate our todo sample to spring-boot-starter 3.0.0 -> Spring framework 6.0 -> Java 17-21

Currently, azd is pretty opinionated on supporting a new version of language SDK. For example, we require dotnet >6.0. There's a question there whether this is going to be limiting long-term, but otherwise the Java 17 requirement is in line with that.

**Comment by rajeshkamal5050** [comment]
@danieljurek do we have an issue tracking on the CloudShell team for the JDK version bump? Can you reference it here?

**Comment by danieljurek** [comment]
CloudShell work item -- https://msazure.visualstudio.com/One/_sprints/taskboard/Azure%20Cloud%20Shell/One/Custom/Azure/CY2022H2%20-%20Zinc/2%20-%20February?workitem=16907221

**Comment by danieljurek** [comment]
Following up... Local docker testing with the workaround succeeds.

**Comment by danieljurek** [comment]
A new version of the Maven package is available. The CloudShell team can integrate that into their image.

**Comment by danieljurek** [comment]
New Java version has been deployed in prod CloudShell. Testing for Java builds in CloudShell are successful. Closing.
