### ISSUE TITLE
Test terraform templates requires additional `az login`

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#1212]
**Describe the issue:**
Test terraform templates after `azd login`. When Run command `bash ./test-templates.sh -c false -t <template_name> -s xxx` , we see the following errors：

![image](https://user-images.githubusercontent.com/80496810/204248332-cba704e2-1cff-41b3-a4a6-5f6679c9dfd0.png)

According to the error message, it can work normally after running ` az login`.

**Repro Steps:**

1. Login with `azd login`
2. Run command `bash ./test-templates.sh -c false -t <template_name> -s xxx` .

**Environment:**
OS: Codespaces, Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code
Template: todo-nodejs-mongo-terraform and todo-python-mongo-terraform
Branch: staging
Azd version: 0.4.0-beta.2-daily.2010605  (commit https://github.com/Azure/azure-dev/commit/b6c8218e832d75a5eb5d0915016390347d3be29f)

**Expected behavior:**
Run command `bash ./test-templates.sh -c false -t <template_name> -s xxx` can pass after `azd login`.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@wbreza @puicchan 

Given that our upcoming `azd` release in Jan 2023 will remove Az CLI dependency from our core and also our providers.

Should we document the fact that terraform CLI requires Az CLI?

**Comment by rajeshkamal5050** [comment]
cc @savannahostrowski @jongio

**Comment by savannahostrowski** [comment]
I think that we can probably point users toward the official TF docs for its dependencies in our docs: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli

**Comment by puicchan** [comment]
Update:
- https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/use-terraform-for-azd
- https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/configure-devops-pipeline?tabs=GitHub

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 This issue also occurs in the following cases:


- OS: WSL, MacOS desktop, Linux desktop, Devcontainer in VS Code, Codespaces, Windows desktop.
- Template: todo-nodejs-mongo-terraform and todo-python-mongo-terraform
- Branch: Staging
- Azd version: 0.4.0-beta.2-daily.2081395  (commit https://github.com/Azure/azure-dev/commit/852cee7207fd484858205c0bab7de22a13740e83)

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 This issue also occurs in the following cases:


- OS: WSL, MacOS desktop, Linux desktop, Devcontainer in VS Code, Codespaces, Windows desktop.
- Template: todo-nodejs-mongo-terraform and todo-python-mongo-terraform
- Branch: Staging and [pr/1323](https://github.com/Azure/azure-dev/pull/1323)
- Azd version: 0.4.0-beta.2-daily.2103577  (commit https://github.com/Azure/azure-dev/commit/d2f80f2b38cc98e3c23e18ab97ff6351018e7ab5)

When removing Az CLI in test environment, run `bash ./test-templates.sh -c false -t <template_name> -s xxx` or `azd up`, and get the following error:
![image](https://user-images.githubusercontent.com/80496810/211515996-6db5085e-5254-42db-bbc2-9052766953dc.png)

**Comment by rajeshkamal5050** [comment]
@v-jiaodi Az CLI is required for the execution of Terraform templates.

**Comment by v-xuto** [comment]
@rajeshkamal5050 Okay. We will close this issue. Besides, when testing the Terraform template, we will install the Az CLI.
