### ISSUE TITLE
Terraform templates create resources failed in WSL

### ISSUE THREAD

**Issue by blow-hey** [Azure/azure-dev#1213]
**Describe the issue:**
Test terraform templates after azd login. When Run command `bash ./test-templates.sh -c false -t <template_name> -s xxx `, we see the following errors：
![image](https://user-images.githubusercontent.com/112381413/204254186-fbc32899-0f63-4088-af8e-6eca98580ca9.png)

**Repro Steps:**
1. Login with `azd login`
2. Run Command `bash ./test-templates.sh -c false -t <template_name> -s xxx`

**Environment:**
OS: WSL in VS Code
Template: todo-python-mongo-terraform and todo-nodejs-mongo-terraform.
Branch: Staging
Azd version: 0.4.0-beta.2-daily.2010605  (commit https://github.com/Azure/azure-dev/commit/b6c8218e832d75a5eb5d0915016390347d3be29f)

**Expected behavior:**
Run command `bash ./test-templates.sh -c false -t <template_name> -s xxx` can pass after `azd login`.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@wbreza @vhvb1989 any specific config needs to be done in WSL for terraform templates?

**Comment by vhvb1989** [comment]
It looks like this link might be `down` while the test was ran:
![image](https://user-images.githubusercontent.com/24213737/204380413-5db30153-c34c-46ba-9037-3f64f09dff9c.png)

The terraform cli uses that link to get a library, but it couldn't fetch it.  

I'd wait for the next run to see this issue automatically resolved, or request a re-run to re-verify

**Comment by rajeshkamal5050** [comment]
@blow-hey based on the above update. Can you re-run the tests and provide an update? cc: @v-xuto

**Comment by blow-hey** [comment]
> @blow-hey based on the above update. Can you re-run the tests and provide an update? cc: @v-xuto

We re-run the tests, and one template ran three times. this issue still reproduced. Besides, we tested with the latest azd version and the version is 0.4.0-beta.2-daily.2037084 (commit 58eb19abfde1abbb32f67751fb0f74a51c1b36f9).

**Comment by rajeshkamal5050** [comment]
@blow-hey can you try with the latest and let us know?

**Comment by zedy-wj** [comment]
> @blow-hey can you try with the latest and let us know?


@rajeshkamal5050  We tested with the latest version of `azd: 0.5.0-beta.4-daily.2144544 (commit eea52e7c8737831e556c3b9c1f27bb795ea02368)` and this issue can still be reproduced.

**Comment by rajeshkamal5050** [comment]
@wbreza can you take a look at this issue?

**Comment by wbreza** [comment]
Not able to reproduce the issue.  Appears to be a transient DNS/internet issue downloading the terraform modules.

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 This issue also occurs in the following cases:

- OS: WSL.
- Template: todo-nodejs-mongo-terraform, todo-python-mongo-terraform
- Branch: Staging
- Azd version: 0.7.0-beta.2-pr.2672227  (commit https://github.com/Azure/azure-dev/commit/dec4eb2c9f5932d3bd41f7e66b41c775c050ad48)

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 This issue also occurs in the following cases:

- OS: WSL.
- Template: todo-nodejs-mongo-terraform, todo-python-mongo-terraform
- Branch: Staging
- Azd version:  0.7.0-beta.2-daily.2681609  (commit https://github.com/Azure/azure-dev/commit/81b97e0268a78c521ef0017c5c9531c4ba7e0399)

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 This issue also occurs in the following cases:

- OS: WSL.
- Template: todo-nodejs-mongo-terraform, todo-python-mongo-terraform
- Branch: Staging
- Azd version: 0.8.0-beta.2-daily.2713284  (commit https://github.com/Azure/azure-dev/commit/cb28058af1e7139be4381532f6b1167d9cd948fb)

**Comment by wbreza** [comment]
Still not able to reproduce this.  As mentioned earlier it appears to be a transient HTTP issue where terraform downloads the required providers/files.

Please try again on a more stable internet connection.

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 This issue also occurs in the following cases:

- OS: WSL.
- Template: todo-java-postgresql-terraform
- Branch: Staging
- Azd version: 0.9.0-beta.2-daily.2772915  (commit https://github.com/Azure/azure-dev/commit/08ff66607eb70b25d189aefce0d21070fe84630d)

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 This issue also occurs in the following cases:

- OS: WSL.
- Template: todo-java-postgresql-terraform
- Branch: Staging
- Azd version: azd version 1.1.0-beta.1-daily.2845223 (commit https://github.com/Azure/azure-dev/commit/9e11674b30a1b0c456fbd8a042d6f5af77ec6188)
