### ISSUE TITLE
[Codespaces] Use `deviceCode` login in codespaces

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#1216]
https://github.com/Azure/azure-dev/pull/1156

**Comment by danieljurek** [comment]
cc @weikanglim

**Comment by rajeshkamal5050** [comment]
@weikanglim @danieljurek can you work with @savannahostrowski on what the behavior should be,
1. automatically do device code flow and prompt user to follow and do the device code flow. @vhvb1989 was mentioning there were some issues around this flow when we get to pipeline config. But data shows most of the users are doing only operations until deploy and pipeline operations are less. May be even more less from codespaces.
2. or the manual steps which we are expecting the user to follow and set it up. In general, we should do the above option and simplify the manual steps required for user to do.

**Comment by weikanglim** [comment]
Checking around if there's a way to detect if Codespaces is running on VSCode browser. The interactive login works on VSCode Desktop.

**Comment by danieljurek** [comment]
* Can we detect if the current token was created using device code flow? If yes, we can surface a warning to re-authenticate during `azd pipeline config` (if the `azd pipeline config` would fail in the environment due to the configuration)

**Comment by weikanglim** [comment]
Resolved with #1261

> Can we detect if the current token was created using device code flow? If yes, we can surface a warning to re-authenticate during azd pipeline config (if the azd pipeline config would fail in the environment due to the configuration)

It's a little complicated to do this correctly. I don't think there's a way to detect the token type. The error we get back is that the device platform is unknown and hence untrusted, which might be due to `deviceCode`, or due to some custom OS the user is running on.

I think documenting this sounds like the best way to do it for now. Opened #1286 for documentation.
