### ISSUE TITLE
[Issue] Integrating apps after deployment

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-dev#122]
Hi, Team.

When we deploy applications to Azure, there are usually three steps involved:

1. Provision resources onto Azure
2. Deploy apps to Azure
3. Integrate between apps on Azure

For example, if I have Azure APIM and Azure Functions app,

1. Provision both APIM and AzFunc instances through Bicep, Portal or Azure CLI
2. Deploy AzFunc app through Azure CLI, CI/CD pipelines or other developer tools
3. Integrate AzFunc app to APIM through OpenAPI document

This azd CLI coverts the first two - provisioning and deployment - but I don't see the third part.

In order to cover those all three steps, I use Bicep's DeploymentScript feature. Here's my sample:

* Sample repository: [APIM OpenAPI Integration Sample](https://github.com/devkimchi/APIM-OpenAPI-Sample)
* Blog post: [Azure Apps Autopilot #2 - Deployment Script](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-apps-autopilot-2-deployment-script/ba-p/3275979)

I wonder whether you've considered this scenario, and it's a part of the roadmap or not?

**Comment by wbreza** [comment]
@justinyoo We have a couple items in the backlog that should help with cases similar to yours.  

- Script hooks - Ability to add pre/post hooks that can run after azd CLI commands.  In your case either a `postdepoy` or `postprovision` hook would give you the ability to run your custom shell script.
- Reviewing the shell script in your example it looks relatively straight forward.  Have you explored converting this to a raw bicep template that can orchestrate the required appsettings changes for your apps after main resources provisioning has completed?

**Comment by justinyoo** [comment]
> * Script hooks - Ability to add pre/post hooks that can run after azd CLI commands.  In your case either a `postdepoy` or `postprovision` hook would give you the ability to run your custom shell script.

Oh, it's what I looked for!

> * Reviewing the shell script in your example it looks relatively straight forward.  Have you explored converting this to a raw bicep template that can orchestrate the required appsettings changes for your apps after main resources provisioning has completed?

Probably it could, but I can't find the proper solution for my case. The sample scenario above is really simple so I might find another solution. However, I've got some real-world scenario that is too complex to think of another approach.

Back to the topic, in the sample code, I should rely on DeploymentScripts feature. Therefore, the workflow looks like this:

1. Resource provisioning (Bicep)
2. App deployment (Bicep - DeploymentScripts)
3. Configuration (Bicep - DeploymentScripts)

If no 3 can be done outside Bicep/DeploymentScripts, it should be doable. That's something I haven't explored yet because I read somewhere that the DeploymentScripts bicep should be the last execution (correct me if I'm wrong) If it's true no 3 has to be done within DeploymentScripts.

**Comment by jongio** [comment]
Can you please share your azd version of this so I can poke at it?

**Comment by justinyoo** [comment]
Sure. Mine is... `azd version 0.1.0-beta.2 (commit 13ec2b11aa755b11640fa16b8664cb8741d5d300)`

![image](https://user-images.githubusercontent.com/1538528/180091682-a0cafaeb-8257-424b-9d84-d8b74b91f113.png)

**Comment by jongio** [comment]
Sorry, I meant the azd version of your app, with the azure.yaml file and bicep files, scripts, etc.

**Comment by justinyoo** [comment]
Just FYI - I've set up the dev CLI template in this repo: https://github.com/justinyoo/google-naver-maps-custom-connector-sample.

It's still unavailable to achieve the 3rd option - integrating APIM with Azure Function app, and update app settings with secerts (like API keys). My curreent workflow for this app provision/deployment/integration is like this:

1. Provision APIM (service) and Azure Functions
2. Deploy Azure Functions
3. Update App Settings with some API keys (secrets) of Azure Functions
4. Provision APIM (API & operations) by integrating Azure Functions

---

* 1 can be done by `azd provision`,
* 2 can be done by `azd deploy --service fncapp`, but
* 3 and 4 are not covered by azd now.

**Comment by rajeshkamal5050** [comment]
@justinyoo as of February azd release, we have the hooks capability. Please try it and let us know for any feedback - https://devblogs.microsoft.com/azure-sdk/azure-developer-cli-azd-february-2023-release/#support-for-command-and-service-hooks

**Comment by rmeshksar** [comment]
@justinyoo , did you find the solution to this using hooks?
I have been having the same problem and was not able to use postdeploy hook properly. 
In my case I am having an ASP.NET Web API with Swagger and I would like to reference that in the APIM definition. 
I thought I could add a post build event to my ASP.NET project, to generate and save the swagger.json file and then reference this file in the APIM definition but it only works if I can do build before provision which at this point seems not to be possible.

**Comment by justinyoo** [comment]
@rajeshkamal5050 Alright, I did a few try with this newer update, and here's what I got:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/1538528/229263852-3fb625ad-ca44-43b4-8a14-3eaf846a4e06.png)

According to the doc: https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/azd-extensibility#hook-configuration, I don't need to explicitly specify the shell. But, it should be declared; otherwise I get the error message like above.

```
ERROR: failed running post hooks: failed running scripts for hooks 'infra create,provision', hook configuration for 'postprovision' is invalid, unable to determine script type. Ensure 'Shell' parameter is set in configuration options
```

I used the `postprovision` hook at the root level.

**Comment by justinyoo** [comment]
@rajeshkamal5050 Here's another observation:

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/1538528/229263913-9964f9e9-f09c-48a0-b057-980cf3c6f5c1.png)

* Even if the syntax is correct, it shows the read line (error line).
* I thought `azure.yaml` file could understand `.env` file, but at least the hooks don't seem to understand the environment variables stored in the `.env` file. They're used for `azd up`, though.

**Comment by wbreza** [comment]
Hi @justinyoo - can you confirm which version of azd you are currently using?

Also, it's difficult to view from your most recent screenshot but are you specifying the `postprovision` hook at the root as a command hook or within a service as a service hook?

`postprovision` is only available as a root level command hook at the moment.

When hooks are executed they have access to both your shell level environment variables as well as any environment variables available within the `.env` file of your azd environment.

Please ensure that are you referencing these environment variables as expected by your specified shell.

sh: `${ENV_VAR_NAME}`
pwsh: `$env:ENV_VAR_NAME`

To test out your hooks you could also save them as a local script file and invoke them locally to ensure they are working as expected.  When testing scripts this way be sure to export/source the required azd environment variables into your shell before executing your script.

**Comment by rajeshkamal5050** [comment]
Waiting on inputs from @justinyoo for further triaging. Moving it to Backlog.

@wbreza pull this back into RC milestone, if there is indeed an issue or doc improvements needed.
