### ISSUE TITLE
Support OnBoarding - Integration details and Problem/Error classification

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#1220]
If a user runs into an issue with `azd` and they request help from support how does support determine whether the problem is coming from `azd` or one or more of the tools `azd` is using.

General advice: 

* Errors from tools should provide enough information to help the user
* Run again (issue may be transient)
* Run again with `--debug` 

For `azd` we could classify errors: 

* An error in `azd` 
* An error in the "gluing" of tools that `azd` uses
* An error thrown by the tool suggesting that its inputs are invalid and user needs to adjust inputs

We want to have a strategy for annotating errors 

In failure cases should we have a "full recording" or "diagnostic log" of some sort... or "run again with `--trace output.log`".

**Comment by rajeshkamal5050** [comment]
This is required for CSS Onboarding. Related onboarding work item - https://dev.azure.com/SupportabilityCheckList/Developer%20Tools/_workitems/edit/121074/

cc: @savannahostrowski

**Comment by rajeshkamal5050** [comment]
@danieljurek @weikanglim can you work together and come up with some guidance/document on the initial triaging, debugging of errors/logs for the support folks?

**Comment by rajeshkamal5050** [comment]
@danieljurek has created a document for us to capture the different integration touchpoints, its details, dependencies and error scenarios/classifications. Split them as below for you to go and add to it. Please feel free to add more such focus areas and adjust/swap amongst us.

- [ ] Packaging and installation @danieljurek 
- [ ] Authentication and authorization  @weikanglim 
- [ ] Telemetry  @weikanglim 
- [ ] Languages, build tools and frameworks  @weikanglim 
- [ ] Supported Host targets  @wbreza 
- [ ] Supported IaC 's @wbreza 
- [ ] Supported Pipelines  @vhvb1989 
- [ ] Client Integrations  @vhvb1989

**Comment by rajeshkamal5050** [comment]
Marking this as complete. Since we now have a doc capturing integration and error classification details captured.
