### ISSUE TITLE
Doc Update: Explicitly callout GitHub CLI prerequisite only for GitHub pipeline config workflows

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#1227]
- Based on data we see almost 80-90% of azd users are doing up(init, provision and deploy) workflow i.e., our P0/Day-0 workflow to see their apps deployed in azure.
- Today in the docs we mandate GitHub CLI as a prerequisite for everyone using Azd. But at runtime, we don't mandate it up until someone tries the pipeline config operation.

Hence, it would be good to update the docs to let users know that GitHub CLI is required only for azd pipeline config. One less deps to make customers install, if they aren't going to try any of the pipeline ops @savannahostrowski @puicchan @jongio thoughts?

Context: Came up in the discussion w.r.t to GitHub CLI removal and what specific azd commands/workflows we depend on. cc @Petermarcu @spboyer

**Comment by savannahostrowski** [comment]
I think that distinction is fine as an initial step to simplify our dependency story.

However, I'd still be interested to know what the lift is to just inline the bits we require from the GH CLI in azd as opposed to require it as a dependency for pipeline config though. Let's make sure that we have an item tracking that.

**Comment by puicchan** [comment]
Update https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/install-azd?tabs=baremetal%2Cwindows and add (only required by `azd pipeline config`) for t he GitHub CLI pre-req.

**Comment by puicchan** [comment]
Completed
