### ISSUE TITLE
[Issue] Error on opening todo-nodejs-mongo in Codespace

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1245]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 0.4.0-beta.1 (commit 2bf7a529914d86d8e9f5d7b6f95a4f20a2351e01)

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 
```
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

**Describe the bug**
Seeing this error when opening todo-nodejs-mongo in Codespace
![image](https://user-images.githubusercontent.com/8949415/206298202-7d7c1667-19b0-43e0-9fed-085b4768cee3.png)

The output window shows something about missing `dotenv` for a second and then it disappears (I haven't been successful in screenshotting it).

**To Reproduce**
1. Open todo-nodejs-mongo in a Codespace
2. See prompt in bottom corner

**Expected behavior**
No error

**Environment**
Codespaces

**Comment by vhvb1989** [comment]
I've seen that error when the azd vscode extension is not installed (it brings the dotenv dependency for the tasks).

So, as soon as the extension is automatically installed by the vscode settings, the error is gone.

@karolz-ms is there a way to make the tasks ti wait until vscode has finished all the remote container setup before it checks the tasks? Or, maybe we can install the dotenv dependency in the container directly

**Comment by karolz-ms** [comment]
@vhvb1989 @savannahostrowski I do not think merely opening an AZD-enabled project should result in **running** any tasks. What I suspect is happening is overly-eager validation of task file syntax, which results in an error that disappears after our extension finishes installation.

I am not really sure if this is a Codespaces issue or VS Code issue. Will ping my VS Code contacts.

**Comment by weikanglim** [comment]
@karolz-ms @savannahostrowski @vhvb1989 We had logged https://github.com/microsoft/vscode/issues/165292 a few weeks ago

**Comment by karolz-ms** [comment]
Opened https://github.com/microsoft/vscode/issues/168494 to have VS Code people look at this. Probably external.

**Comment by savannahostrowski** [comment]
Going to close this as I haven't seen it in awhile/it was upstream.
