### ISSUE TITLE
Create new APIM arch diagram

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1252]
Here's a mock
![image](https://user-images.githubusercontent.com/2163001/206729019-e256e50f-a94f-4040-8b3c-17518eacc1d4.png)

let's figure out a good way to abstract the lang and db, so we only have to create one of these that can be used in all templates.

**Comment by jongio** [comment]
Backstory.
1. Each template has an architecture diagram located in the arch diagram section of the README i.e. https://github.com/Azure-Samples/todo-csharp-sql#application-architecture
2. We are adding APIM to each of the templates.
3. We are adding APIM as an additional feature that can be added by using a flag in the parameters file.
4. We are adding a new section to the readme that informs the user of this feature and shows them how to use it.
5. In that new section we'd like to have a diagram that is identical to the diagram above, but adds APIM between the Web and APIM nodes.


Tasks:

1. Find the source of this file: https://github.com/Azure-Samples/todo-csharp-sql#application-architecture
1. Find the APIM icon
1. Add a new box between web and apim called APIM
1. Draw a line from web to apim and then from apim to api
1. Draw a line from apim to monitor box.
1. Repeat the above steps for each of the templates, which can be found here: https://aka.ms/azd/templates

**Comment by Austinauth** [comment]
Here's the updated visual.

![image](https://user-images.githubusercontent.com/6994218/207376489-3f7714ee-9877-48d4-bf27-d5c4da80b7ce.png)

And here's a link to `.png` file: https://microsoft.sharepoint.com/:i:/t/AzureDeveloperExperience-AzureAcceleratorsTeamInternal/EXZYCoFr3DxGrh668nZ9YC4BB0ZlBB8SfDAVJla5g8dotg?e=pRekSJ

<hr>

I'll try to knock out an updated visual for the remaining todo apps by the end of the week!

**Comment by jongio** [comment]
I spoke with Austin and we realized that APIM shouldn't be in the App Service Plan box, so he is updating.

**Comment by Austinauth** [comment]
Updated the links and image above to reflect the tweak!

**Comment by Austinauth** [comment]
Had a request for the version with Cosmos. Here it is

![image](https://user-images.githubusercontent.com/6994218/207718685-0f0a327e-4ad7-4624-b685-2991059d5593.png)

And here's a link to .png file: https://microsoft.sharepoint.com/:i:/t/AzureDeveloperExperience-AzureAcceleratorsTeamInternal/ESJfDb8hX4BNvFzfohlXJ-kBW98pXgqcqWQe9aNnT_0-LQ?e=ZHE2LT

**Comment by jongio** [comment]
The APIM main PR was merged, but let's keep this one open so we can collect the rest of the images here and add them to templates as APIM is added to them.

**Comment by Austinauth** [comment]
Will update this comment as I complete the diagrams. There's a bunch of these, so please let me know if I made any errors.

<hr>

### todo-csharp-cosmos-sql
![image](https://user-images.githubusercontent.com/6994218/207950538-e77a08e0-f6d5-4c28-b98f-2c1842809c6f.png)

Link to image file (coming soon)

<hr> 

### todo-csharp-sql
![image](https://user-images.githubusercontent.com/6994218/207950707-05a11a44-e65b-4302-a9b6-bc840ce6b9ae.png)

Link to image file (coming soon)

<hr>

### todo-csharp-sql-swa-func

[TBD]

Link to image file (coming soon)

<hr> 

### todo-python-mongo-aca

[TBD]

Link to image file (coming soon)

<hr> 

### todo-python-mongo

![image](https://user-images.githubusercontent.com/6994218/207951324-91b8bed8-2b4c-4491-8e98-d129b66948da.png)

Link to image file (coming soon)

<hr> 

### todo-python-mongo-swa-func

[TBD]

Link to image file (coming soon)

<hr> 

### todo-python-mongo-terraform

![image](https://user-images.githubusercontent.com/6994218/207951580-c527a87f-7aa1-40de-93cb-0678bd34cc02.png)

Link to image file (coming soon)

<hr> 

### todo-nodejs-mongo-aca

[TBD]

Link to image file (coming soon)

<hr> 

### todo-nodejs-mongo

![image](https://user-images.githubusercontent.com/6994218/207951897-de85140a-ae1f-4bc2-8c36-92d4cf8d5b7f.png)

Link to image file (coming soon)

<hr> 

### todo-nodejs-mongo-swa-func

[TBD]

Link to image file (coming soon)

<hr> 

### todo-nodejs-mongo-terraform

![image](https://user-images.githubusercontent.com/6994218/207952147-86a2c525-167f-4853-9580-79046dc6f329.png)

Link to image file (coming soon)

<hr> 

### todo-nodejs-mongo-swa

[TBD]

Link to image file (coming soon)

**Comment by weikanglim** [comment]
Hey @Austinauth just checking if you have the remaining visuals ready, so that we can merge #1323

**Comment by Austinauth** [comment]
@weikanglim @jongio 

Updated the remaining diagrams. All should be in the post above with links to the full sized `.png`.

As an aside, these were all assembled using existing assets before my time, they look a bit clunky. I think eventually we'll want to go back and redo all of these, making the icons and line work more consistent between diagrams.
