### ISSUE TITLE
[Issue] Support passing `build-arg` to docker builds

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-dev#1270]
When deploying apps that are within a container, such as Container Apps, there can be scenarios where you need to provide build-time variables to the Dockerfile. An example of this I described in [this issue comment](https://github.com/Azure/azure-dev/issues/121#issuecomment-1350391556), but there are other reasons you may need an environment variable to trigger different aspects of the container build.

Looking at the Docker `build` function here: https://github.com/Azure/azure-dev/blob/037e7638041f46ad94b33418279a29a7841ed031/cli/azd/pkg/tools/docker/docker.go#L43-L60

There's no way to provide a `build-arg` flag to the `docker build` command. I suggest we expand the `docker.properties` part the `azure.yaml` schema (https://github.com/Azure/azure-dev/blob/037e7638041f46ad94b33418279a29a7841ed031/schemas/v1.0/azure.yaml.json#L110-L139) so that we can provide `build-args` as desired.

**Comment by jongio** [comment]
Great idea!  Thanks for the request.

**Comment by weikanglim** [comment]
We should consider how this plays well with #1810

**Comment by aaronpowell** [comment]
> We should consider how this plays well with #1810

Sure. I'll have a read of #1810 and add thoughts.

> Also, do we expect `envsubt` to work with this parameter configuration? Or should the configuration be configurable via env variables?

I think we should support substitution of environment variables, both from a system level _and_ from the azd output. I described a particular scenario in https://github.com/Azure/azure-dev/issues/121#issuecomment-1350391556 in which I wanted to take the output from one service and use it in another via `buildArgs`, so that's my end goal here.

**Comment by savannahostrowski** [comment]
Is this now complete via #2266 ?
