### ISSUE TITLE
Doing `azd up` on the `todo-csharp-sql` creates SQL resources but doesn't list them in the output

### ISSUE THREAD

**Issue by bwateratmsft** [Azure/azure-dev#1282]
**Output from `azd version`**
azd version 0.4.0-beta.1 (commit 2bf7a529914d86d8e9f5d7b6f95a4f20a2351e01)

**Output from `az version`** 
```json
{
  "azure-cli": "2.42.0",
  "azure-cli-core": "2.42.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
```

**Describe the bug**
I did `azd up` on a `todo-csharp-sql` app, and it _did_ deploy the SQL resources, but did not list them in the output log:
![image](https://user-images.githubusercontent.com/36966225/208169204-34c5106a-ed11-4606-b4ab-fbd5a1610149.png)

**To Reproduce**
1. `azd init`, choose `todo-csharp-sql`
2. `azd up`

**Expected behavior**
The SQL resources would be included in the output

**Environment**
Information on your environment:
    * .NET 7.0 installed
    * VSCode 1.74.1

**Comment by jongio** [comment]
dupe: https://github.com/Azure/azure-dev/issues/857
