### ISSUE TITLE
Document `azd pipeline config` failure due to device code login

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1286]
# Document troubleshooting guide

## `azd pipeline config` failure due to Conditional Access Policy

When running `azd pipeline config` user receives an error, "AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors".

## Problem description

This error is related to your Azure Active Directory's tenant enablement of Conditional Access Policies. The specific policy requires that you are signed in into a supported device platform. It can also be due to the fact that you are logged in using the device code mechanism, which prevents Azure Active Directory from detecting your device platform correctly.

## Recommendation

1. First, ensure that you're running on a device that is listed as supported in the error message.
2. Otherwise, rerun `azd login` with the flag `--use-device-code=false` appended, i.e.:
    ```
    $) azd login --use-device-code=false
   ````
   - If running Codespaces in the browser, you may receive a 404 error in the browser after logging in. Copy the URL, and run `curl <pasted url>` in the VSCode shell. The login should now succeed.
   - After logging in, rerun `azd pipeline config`.
 

Raw error message:
```
PS D:\repos\azure-dev\cli\azd> ./azd pipeline config --cwd D:\repos\azd-sources\devcontainer-az-login
Using pipeline provider: GitHub
Creating or updating service principal az-dev-12-16-2022-21-10-26.


ERROR: failed to create or update service principal: failed retrieving application list, failed executing request: http call(https://login.microsoftonline.com/common/oauth2/v2.0/token)(POST) error: reply status code was 400:
{"error":"invalid_grant","error_description":"AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.\r\nTrace ID: be3438c1-42fc-4c37-96d8-0e723ac54f01\r\nCorrelation ID: f535565f-9f3c-4014-ad65-403f514bf892\r\nTimestamp: 2022-12-16 21:10:37Z","error_codes":[50005],"timestamp":"2022-12-16 21:10:37Z","trace_id":"be3438c1-42fc-4c37-96d8-0e723ac54f01","correlation_id":"f535565f-9f3c-4014-ad65-403f514bf892"}
````

**Comment by puicchan** [comment]
@weikanglim - is this for Codespaces only?
