### ISSUE TITLE
[Issue] Hyphenated service names will create invalid container image env variables

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-dev#1290]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
_verified by running off the `main` branch of this repo (commit bae2521)_

**Describe the bug**
I have a service which deploys to Container Apps, defined as so:

```yaml
name: test
services:
  blog-cms:
    project: packages/blog-cms
    host: containerapp
    module: app/blog-cms
```

When I do `azd deploy` it builds the container and then hangs trying to compile the Bicep template because, while I have a parameter of so:

```json
"imageName": {
      "value": "${SERVICE_BLOG_CMS_IMAGE_NAME}"
    }
```

The `.env` file contains `SERVICE_BLOG-CMS_IMAGE_NAME`, with a `-` in `BLOG_CMS`, not `_` as with all others.

The issue comes from https://github.com/Azure/azure-dev/blob/main/cli/azd/pkg/project/service_target_containerapp.go#L104, where it outputs the service name as entered, but the package we use for variable substitution [doesn't support `var-<name>` syntax](https://github.com/drone/envsubst#unsupported-functions).

**To Reproduce**
Create a service that deploys to Container Apps but has `-` in the name, provision the infrastructure and attempt to deploy. Deployment will be unable to find the container image.

**Expected behavior**
Name of the service is sanitized to meet the rules of https://github.com/drone/envsubst when writing out the image name.

**Comment by ellismg** [comment]
Was fixed with #1291 by [aaronpowell](https://github.com/Azure/azure-dev/commits?author=aaronpowell).  Thanks, Aaron!
