### ISSUE TITLE
[Issue] Support `azd env list--remote` or similar to grab environment names upstream

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1305]
I often work across machines (desktop, laptop). As I was setting up my personal website for development (which is an azd template! https://github.com/savannahostrowski/terminal-personal-site) on my desktop machine (I'd previously done all my development on my laptop), I had forgotten the name of my environment on Azure to use with `azd env refresh`. It would be great if we had a command like `azd env list --remote` to grab the names of the environments upstream so that I didn't have to jump over to the portal to grab the env name.

**Comment by jongio** [comment]
I'd add a param to `azd env list` to get the remote envs.  It would be unique list of rgs that have `azd-env-name` tag.

**Comment by savannahostrowski** [comment]
Ha, I typo'd while multitasking, completely agree, it should be on azd env list. I'll update the issue to avoid confusion

**Comment by vhvb1989** [comment]
wouldn't this be a duplication of using the Azure Portal to list all resource groups with a tag?  or using the Azure CLI ?

What about making `azd env refresh` to ask the user if he/she wants to look for previously created environments within a subscription when running the command on a folder without an azd env?

For example, right now, if I run `azd env refresh` within an empy folder, I get:
![image](https://user-images.githubusercontent.com/24213737/210668112-b97b2b1b-9150-46b5-b8e0-d3debd23ffc5.png)

So, I need to first remember the name of a previously created env and use it to init my env right?
Well, I would prefer if `azd`  would ask me to select a subscription and list if there are any previously created azd envs.  And I would even like it better if the list of environments are only the ones created by me (to avoid getting noisy environments from my friends in the same subscription)

**Comment by savannahostrowski** [comment]
Going to close this as we now have --hint and also #2531 

cc: @wbreza
