### ISSUE TITLE
[Issue] Improve `azd env docs`

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1306]
DevHub doesn't currently include a lot of information around how to use our `azd env` command, specifically `azd env refresh` (https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/reference#azd-env-refresh). 

I think it'd be really helpful if we detailed out the specific behaviour of this command (because it's rather powerful) and why you'd use it (e.g. maybe you want to develop across machines, maybe you want to pull down an existing env that your coworker configured).

Perhaps as an FAQ or a how-to?

**Comment by rajeshkamal5050** [comment]
We can probably enhance the docs one @ellismg environment changes are in.

**Comment by savannahostrowski** [comment]
Related https://github.com/Azure/azure-dev/issues/1458

**Comment by savannahostrowski** [comment]
Needed before content freeze

**Comment by savannahostrowski** [comment]
Ac

**Comment by puicchan** [comment]
https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4458
