### ISSUE TITLE
`azd down` in VS Code

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#132]
Right now, we don't provide the option for a developer to clean up their resources in VSCode via `azd down`

We want to provide an easy way for developers to "nope out" should they so desire 😄.

**Comment by ellismg** [comment]
`azd provision` is an alias for `azd infra create` which is exposed.  Note that `azd provision` is the older term we used for the `azd infra create` gesture but we created the extension back when we only had `azd provision`

**Comment by savannahostrowski** [comment]
Let's scope this to adding `azd down` to VSCode. We'll deal with the `azd infra create` convo separately.

**Comment by karolz-ms** [comment]
Moving to Backlog since there is ongoing work to better organize the set of CLI commands and rename some of them, which may affect whether we have aliased `infra create` + `down` commands.

**Comment by savannahostrowski** [comment]
I think we've tabled the discussion around restructuring commands (not sure that we have any evidence to currently support such a rework). @rajeshkamal5050 Can we get this added to On Deck?

**Comment by bwateratmsft** [comment]
This is included in #853.
