### ISSUE TITLE
Support for `azd init` without a template in VS Code

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#133]
A valid scenario is that a developer is in VS Code, working on their project and then decides that they want to start azd-ifying it/turn it into a template.

Right now, if you open the Command Palette and click `azd init`, you are not provided with an option to init on your current repo. You must select a template or enter a path to a GitHub repo.

![image](https://user-images.githubusercontent.com/8949415/179630018-8527dbda-6bf0-49b7-9f10-16176bcfa9a3.png)

The workaround right now is to init via the command line outside VSCode or manually enter the command in the VSCode embedded terminal but we should support the azd-ify path from within the editor (via command palette) as well.

**Comment by karolz-ms** [comment]
I had some discussions with @puicchan about this. The scenario is definitely valid and important, but we were wondering if we need to have a separate command, or a family of commands, that would assist with making a project compatible with `azd`, like `azd enable` or something. 

Having `init` command cover this use case, as well as the regular "consume a template" use case might lead to confusion...

**Comment by savannahostrowski** [comment]
That's interesting - I'll think about this some more.

My main concern is that by not having this as an option right now, we don't provide users a way to create their own templates from within the editor (and we definitely want folks to feel like authoring templates is easy/streamlined).

**Comment by karolz-ms** [comment]
> My main concern is that by not having this as an option right now, we don't provide users a way to create their own templates from within the editor (and we definitely want folks to feel like authoring templates is easy/streamlined).

I do not think tweaking the `init` command support in VS Code will be sufficient for this.

What I would explore instead, is to have a heavily commented "template for a template" that would highlight all the common places that developers might want to customize for their type of application. And then we could build an experience in VS Code involving "using" this template (as in, `gh repo create --template azd-starter`), and navigating over it via CodeTour.

**Comment by puicchan** [comment]
A heavily commented "template for a template" could be an option. I will capture that idea in the spec.

**Comment by karolz-ms** [comment]
We are still working on the details azd-enabling any app, and there are plans for changing the command set. Given that, this item (which is really about having a VS Code gesture for azd-enabling an app) is not yet actionable. Closing for now, with the expectation that a new issue will be created for this once the work required in VS Code is clearer.
