### ISSUE TITLE
AzureDeveloperCredential for Python fails if `expiresOn` contains microseconds

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#1333]
Credential works most of the times, but I hit this issue when the `expiresOn` time contains a microseconds information.

![image](https://user-images.githubusercontent.com/24213737/211245268-3f059da5-e469-4b50-ab4e-845689bdca09.png)

Possible solutions:
- Inspect the `expiresOn` value before parsing the date and set the format once we know if it contains a dot `.` after the seconds portion
- Always call `split(value, ".")` to remove the microsecods info from the date and then add the `Z` if it is not at the end.

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-dev/issues/1057#issuecomment-1375122787_

**Comment by ellismg** [comment]
If including the nanonsecond precision makes this harder to consume from other languages, I'm fine for us to just switch to RFC3339.  I'll open a PR.
