### ISSUE TITLE
azdev cannot create roleAssignments

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/azure-dev#134]
Running `azd pipeline config` will create a service principal that has **Contributor** access to the subscription. This role does not grant permission for the service principal to create a role assignment. It will also need "User Access Administrator" role to create the role assignments that are used when granting a managed identity access to another azure resource.

https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal?tabs=current

If you include a role assignment in your `resources.bicep` file then you receive an error that looks like the following:
```
Deployment Error Details:
InvalidTemplateDeployment: Deployment failed with multiple errors: 'Authorization failed for template resource '3333333-1111-3333-4444-22222222222' of type 'Microsoft.Authorization/roleAssignments'. The client '88888888-4444-5555-6666-77777777777' with object id '88888888-4444-5555-6666-77777777777' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/22222222-5555-9999-7777-00000000000/resourceGroups/qa-rg/providers/Microsoft.Authorization/roleAssignments/3333333-1111-3333-4444-22222222222'.:Authorization failed for template resource 'd8c5621e-1787-5c87-b5be-a0e00fbf02bf' of type 'Microsoft.Authorization/roleAssignments'. The client '88888888-4444-5555-6666-77777777777' with object id '88888888-4444-5555-6666-77777777777' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write' at scope '/subscriptions/22222222-5555-9999-7777-00000000000/resourceGroups/qa-rg/providers/Microsoft.Authorization/roleAssignments/d8c5621e-1787-5c87-b5be-a0e00fbf02bf'.'
```

## Known workaround

If you're planning for the resources.bicep file to create role assignments then you should modify the permissions for the service principal that was created by running `azd pipeline config`.

1. Find the service principal by looking in your Azure AD portal or by viewing the detailed logs from `azd pipeline config --debug`
2. Use the azure CLI to grant the User Access Administrator role

```ps
$principalId = {principalId of the service principal created by azd pipeline config}
az login
$subscriptionId=(az account show --query "id")
# list of built-in Azure roles https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles
$userAccessAdministratorRoleId='18d7d88d-d35e-4fb5-a5c3-7773c20a72d9'
az role assignment create --role $userAccessAdministratorRoleId --assignee $principalId --scope /subscriptions/$subscriptionId
```

**Comment by vhvb1989** [comment]
@KSchlobohm have you tried running `azd pipeline config --principal-role Owner` ?

Would the `Owner` role provide both `Contributor` and `User Access Administrator` ?

Let me know if this works for you, or if using `Owner` role is not an option and you need 2 roles instead.

**Comment by KSchlobohm** [comment]
Hi @vhvb1989

I didn't know there were other options to try from the `azd pipeline config` command and have not tried those.

Also, I was under the impression that `Owner` would be too much permission for this principal but perhaps the combination of `User Access Administrator` and `Contributor` has already provided similar permissions.

The idea of assigning `User Access Administrator` was to align with the security principal of trying to give the account the least amount of permission it needed to function.

**Comment by vhvb1989** [comment]
@KSchlobohm , yes, `Owner` might give the wrong idea.

You can use both roles by running:
```sh
# This will create the principal name with `Contributor` role by default
# If git repo is not configured, azd will help you to set it up
azd pipeline config --principal-name pick-some-name

# Running again the command using the same principal-name argument and adding Admin role
# This will update the existing service principal and add the access role
azd pipeline config --principal-name pick-some-name --principal-role "User Access Administrator"

```

The access role is assigned to the entire subscription (scope), so you can see the subscription `Access control (IAM)` from the Azure Portal. The service principal should appear in the `Role Assigments` as `Contributor` and as `User Access Administrator`

Let me know if this works for you.

**Comment by KSchlobohm** [comment]
@vhvb1989 this works great, thanks!
