### ISSUE TITLE
UX learn.microsoft.com vs. CLI help editorial decisions

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#1362]
A couple of points brought up in PR review about editorial/UX decisions we've made in the markdown docs differing from the CLI output should be considered in future UX work. 

* https://github.com/Azure/azure-dev/pull/1353#pullrequestreview-1244245237
* https://github.com/Azure/azure-dev/pull/1353#pullrequestreview-1244247076

**Comment by rajeshkamal5050** [comment]
Anything pending on this?

**Comment by danieljurek** [comment]
This is tracking comments brought up in the course of reviewing some changes made to the help text. I think these should be discussed as part of the UX work that @Austinauth is doing.

**Comment by Austinauth** [comment]
@danieljurek Want to make sure I'm understanding. Are you pointing out that there is some inconsistencies in the language that we're using? If so I feel like a few of us should get together to discuss preferred terminology, and then I can make sure to be consistent based off what we decide.

**Comment by savannahostrowski** [comment]
@Austinauth @danieljurek What was decided here? Anything left?

**Comment by Austinauth** [comment]
@savannahostrowski no updates on my end, I'm not totally sure I understand what the request is.

**Comment by savannahostrowski** [comment]
I think we are good to close for now.
