### ISSUE TITLE
Repeated runs on azd up produce repeated resource lines of output

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-dev#1363]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

```text
azd version 0.4.0-beta.1 (commit 2bf7a529914d86d8e9f5d7b6f95a4f20a2351e01)
```

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 

```json
{
  "azure-cli": "2.42.0",
  "azure-cli-core": "2.42.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.5"
  }
}
```

**Describe the bug**
When running `azd up`, I get a line for each resource repeated for each run of `azd up`:

```text
Created Resource group: rg-adhal-graphql-csharp
Created Azure Cosmos DB: cosmos-74edqzc2mzehi
Created Azure Cosmos DB: cosmos-74edqzc2mzehi
Created Azure Cosmos DB: cosmos-74edqzc2mzehi
Created Azure Cosmos DB: cosmos-74edqzc2mzehi
Created Web App: app-web-74edqzc2mzehi
Created Web App: app-web-74edqzc2mzehi
Created Web App: app-web-74edqzc2mzehi
Created Web App: app-web-74edqzc2mzehi
Created Web App: app-api-74edqzc2mzehi
Created Web App: app-api-74edqzc2mzehi
Created Web App: app-api-74edqzc2mzehi
Created Web App: app-api-74edqzc2mzehi
Created Key vault: kv-74edqzc2mzehi
Created Key vault: kv-74edqzc2mzehi
Created App Service plan: plan-74edqzc2mzehi
Created App Service plan: plan-74edqzc2mzehi
Created Log Analytics workspace: log-74edqzc2mzehi
Created Log Analytics workspace: log-74edqzc2mzehi
Created Log Analytics workspace: log-74edqzc2mzehi
Created Log Analytics workspace: log-74edqzc2mzehi
Created Application Insights: appi-74edqzc2mzehi
Created Application Insights: appi-74edqzc2mzehi
Created Portal dashboard: dash-74edqzc2mzehi
Created Portal dashboard: dash-74edqzc2mzehi
```

**To Reproduce**
Run `azd up` multiple times.

**Expected behavior**
I'd only expect one line per resource to be displayed.

**Environment**
Information on your environment:
    * Template based on `todo-csharp-cosmos-sql` (React/JS frontend, C# ASP.NET Core backend).
    * IDE and version : Visual Studio Code 1.74.3 on Windows 11.

**Comment by rajeshkamal5050** [comment]
@adrianhall can you try with the latest bits. This should be fixed. Let us know.

**Comment by adrianhall** [comment]
Can confirm that this is no longer a problem in 0.5.0-beta.1
