### ISSUE TITLE
[Issue] Login not possible after upgrade to 0.5.0

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-dev#1366]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

azd version 0.5.0-beta.1 (commit 57cba771d598398f30acfef18a272d1906a8e4f1)

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 

{
  "azure-cli": "2.39.0",
  "azure-cli-core": "2.39.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

**Describe the bug**

After the upgrade to 0.5.0-beta.1 I use the new login flow via `azd login`. The login option "Interactive authentication with a browser" is started opening a browser window.

Authentication via username (=email) states that:

```bash
This username may be incorrect. Make sure you typed it correctly. Otherwise, contact your admin.
``` 

A login with this username via `az login` or via Azure Portal is working. 

To work around this issue, I did:

1. `azd config set auth.useAzCliAuth true` 

which forces `azd` to use the login credential saved by Azure CLI (after running `az login`).

**To Reproduce**

- Install/upgrade to latest version of Azure Developer CLI
- Start the command `azd login` to kick off the "Interactive authentication with a browse"
- Enter your username and press "next"

**Expected behavior**

The interactive login via browser and username should be possible

**Environment**

Windows 11
PowerShell 7.3.1

**Additional context**

- Screenshot of error message:

   ![Screenshot 2023-01-12 161502](https://user-images.githubusercontent.com/22294087/212104890-54d81537-b243-425a-a636-bc7bde3cfe68.png)

- The fallback via `azd config set auth.useAzCliAuth true` works

**Comment by weikanglim** [comment]
@ellismg Could this be fixed by the work on tenant IDs? It looks like our auth flow isn't handling personal accounts (outlook address for example).

**Comment by weikanglim** [comment]
To workaround the issue,

1. `azd config set auth.useAzCliAuth true` 
2. Proceed with `azd login`

**Comment by lechnerc77** [comment]
Thanks for the super-quick fix of this issue. Highly appreciated!
