### ISSUE TITLE
Confusion in status in between provisioning and deployment steps

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#1368]
Identified during unmoderated getting started study conducted in Q4 2022.

When resources are provisioned, but an app is not yet deployed, the CLI output is visually fileld withh all-green successful provisioning statuses, and the Portal shows green Successfully Deployed/Running statuses. Customers have confused this to mean 'completely done with everything - creation and deployment' amd are confused when they get 404 errors (because the apps have not deployed).

The "Deploying service api…" at the bottom of the CLI output does not seem to helIn one study, when the next step came up (deploying web…), the customer finally understood what was going on.

![image](https://user-images.githubusercontent.com/8701892/212113016-7f7d266e-0b7f-4b15-a447-5152d0d74ff0.png)

We should make it more visually obvious that provisioning is NOT the end of the process.p, presumably because it is not the most visually impactful thing on the screen.

**Comment by rajeshkamal5050** [comment]
@Austinauth Can you take a look at the messaging?

**Comment by Austinauth** [comment]
The screenshot above appears to be from an older release. 

The latest design should look like this:

![image](https://user-images.githubusercontent.com/6994218/213800020-b4d37fe1-26df-4376-b018-c57015bf3979.png)

We need to confirm that this is still an issue with the new designs (cc: @puicchan), as there were steps taken to make this step more clear.

- Removal of the _Azure resource provisioning completed successfully message_ when running provision as part of `azd up`
- Addition of a header (in bold) when the deployment step starts _Deploying services (azd deploy)_

**Comment by savannahostrowski** [comment]
Closing for now. We can reopen if we retest with the new designs and find issues.
