### ISSUE TITLE
Links are difficult to see in light mode on Linux/Mac

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#1369]
Identified during unmoderated user study conducted in Q4 2022.

Links in the CLI are a very light blue in light mode on Macs, and therefore difficult to read. Suggest choosing a darker blue that passes an accessibility contrast checker (e.g. https://webaim.org/resources/contrastchecker/).

![image](https://user-images.githubusercontent.com/8701892/212114237-f4379efb-f353-4786-a195-3cf4daa5ca93.png)

**Comment by pamelafox** [comment]
See also https://github.com/Azure/azure-dev/issues/1007

Glad you discovered it in your user study as well! Common pain point for me.

**Comment by rajeshkamal5050** [comment]
Closing in favor of #348
