### ISSUE TITLE
Template list is difficult to parse and figure out which one I should choose

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#1370]
Identified during unmoderated getting started with azd study conducted in Q4 2022.

Template list is difficult to parse and figure out which one I should choose. 

Challenges include:
	• "todo" is not descriptive
	• Visually, it is hard to scan quickly (e.g. in VS Code command palette list)
	• Different naming conventions:
		○ Sometimes main compute service is included (e.g. aca, func), sometimes not (e.g. todo-csharp-sql)
		○ Sometimes IaC is included (e.g. terraform) sometimes not
New to azure customers are unlikely to know acronyms (e.g. aca, swa) and therefore not understand that they are choosing a certain compute service. We observed this in a user study where a customer wanted to use the same app service template she used in the CLI, but in VS Code chose the ACA one without realizing it.

![image](https://user-images.githubusercontent.com/8701892/212115231-dd87bb64-d9b9-4077-ab8e-b101c148f1ba.png)

**Comment by rajeshkamal5050** [comment]
Related to #976

**Comment by savannahostrowski** [comment]
We can start with the experiment in #976 and see what, if anything, else we want to do after that.

**Comment by rajeshkamal5050** [comment]
Pulling #976 onto Release 0.7 and moving this to backlog.

**Comment by savannahostrowski** [comment]
As of 0.9.0 (out tomorrow) we have made large updates to this list to reflect the local application stack (as opposed to emphasizing the ToDo app bits or Azure services).

![image](https://github.com/Azure/azure-dev/assets/8949415/68eb6f08-3ca4-48c7-bf76-05acfe597f0a). Going to close this for now as the remaining bits will be addressed by #2158
