### ISSUE TITLE
[Issue] TODO samples are missing apiManagementConfig setting

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#1377]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 0.5.0-beta.1 (commit 57cba771d598398f30acfef18a272d1906a8e4f1)

**Output from `az version`** 

```
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

**Describe the bug**

Currently, if you deploy a TODO app with USE_APIM=true, and then visit that Function App in the Portal and click API Management from the left nav, you'll see this prompt to connect it to APIM:
<img width="1012" alt="Screenshot 2023-01-12 at 4 01 31 PM" src="https://user-images.githubusercontent.com/297042/212206597-85780895-331b-45d8-8cb1-04a08b3c5670.png">

The function app does not realize that it has an associated APIM instance, due to missing configuration.

**To Reproduce**

Open todo-python-mongo-swa-func, set USE_APIM="true" in the .env file, and run `azd up`.

**Expected behavior**

It should embed APIM inside the function app portal. Here's what it looks like for my fastapi-azure-function-apim sample:

<img width="897" alt="Screenshot 2023-01-12 at 4 01 54 PM" src="https://user-images.githubusercontent.com/297042/212208809-c58e6d78-8b2a-4289-8c92-9a95b21fa8f2.png">

Here's the Bicep configuration that links the Function App to the APIM:

https://github.com/pamelafox/fastapi-azure-function-apim/blob/dbf31e0436c441c5ebdd0254224f8467db20d797/infra/resources.bicep#LL140C22-L140C22

**Additional context**

Let me know if you'd like me to send a PR to add that configuration somewhere (either functionapp.bicep or apim.bicep I assume?).

**Comment by jongio** [comment]
PR would be nice!!!

**Comment by pamelafox** [comment]
PR made https://github.com/Azure/azure-dev/pull/1403

**Comment by weikanglim** [comment]
@pamelafox Thanks for submitting the PR, hope it wasn't too much of a hassle!

I've been digging through the APIM docs to learn more about the difference in behavior between how the todo samples are wired up vs. the linking option that you're proposing. My current understanding is that they are different ways of how you could link an Azure resource to an Azure APIM, and it may not be as simple as the resources having a direct link to each other in the Portal.

The ToDo APIs all share a hand-crafted `openapi.yaml` schema that documents the API explicitly. We currently import this specification into APIM, thereby configuring what routes to redirect. I think that this would be the ideal way for developers to develop an API and integrating with APIM (but also slightly more costly). See [importing from OpenAPI configuration](https://learn.microsoft.com/en-us/azure/api-management/import-api-from-oas?tabs=portal).

A different option is to leverage the Azure "Function App/Container App/App Service" knowledge of your service to import the APIM configuration (the linking option that you're looking into). 
- For [Function App](https://learn.microsoft.com/en-us/azure/api-management/import-function-app-as-api), this is relatively straightforward. Functions need to be mapped to HTTP triggers and can be imported as route redirects.
- For [App Service](https://learn.microsoft.com/en-us/azure/api-management/import-app-service-as-api) / [Container App](https://learn.microsoft.com/en-us/azure/api-management/import-container-app-with-oas), this by-default results in wildcard redirects (which is less secure and less precise). A different mode is to also specify a URL to a publicly available `openapi.json` URL specification, which then APIM would import it (as a slightly roundabout mechanism).

Ultimately, the Azure App resource linking is a cheap way to substitute having to develop a OpenAPI specification, but it's something the developer would need to decide upfront which tradeoffs they value more.

**Comment by pamelafox** [comment]
Ah interesting contrast of the approach. 

For the APIM apps that I've been developing in Python, I use the FastAPI framework which creates an OpenAPI specification automatically and the subsequent documentation/parameter validation/etc, so I don't use any of the route-specific mechanisms from APIM. I just use APIM for overall subscription keys, CORS, rate-limiting, etc.  I think that would be a common approach for devs using FastAPI, but maybe some would want to replicate the routes in APIM. They'd probably try to feed the FastAPI-generated OpenAPI spec to APIM in that case.

In terms of apiManagementConfig, I guess I thought that was orthogonal, i.e. in either case it's handy to have an embedding of APIM inside the Portal, but maybe I'm missing something. You think that should only be set if you're hooking the APIM up using the set-backend mechanism?

**Comment by weikanglim** [comment]
@pamelafox When I linked my app service to the APIM, I could see new routes added with wildcards. Did you observe any changes to the routes in your app?

When linking a function app from our ToDo sample, it actually didn't allow me to proceed to do in the portal, as no HTTP trigger functions were detected (IIRC something to do with our samples using packaged defintions).

**Comment by pamelafox** [comment]
Ah, interesting. I assume you linked the App Service to the APIM through the Portal? I'm thinking the Portal tries to be too clever and do additional work that adds the routes. When I link it through the Bicep change proposed in the PR, I do not see any extra routes.

After linking todo-python-mongo through Bicep:

<img width="649" alt="Screenshot 2023-01-23 at 11 08 11 AM" src="https://user-images.githubusercontent.com/297042/214128188-d38c03b6-bd78-4529-bf07-79d7c5cacc22.png">

<img width="678" alt="Screenshot 2023-01-23 at 11 08 13 AM" src="https://user-images.githubusercontent.com/297042/214128179-feb3a4dd-3a82-4ead-b116-de2451f6f7eb.png">

**Comment by weikanglim** [comment]
@pamelafox You might be right that maybe going through bicep-only simply links the app. I did find the docs [here](https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites/config-web?pivots=deployment-language-bicep#siteconfig). I'm going to play around with deploying your changes on all our templates and see if there's any noticeable differences in the APIM config. Stay tuned...

**Comment by pamelafox** [comment]
Okay thanks! If you trigger repoman on my PR, that should deploy the changes on all the templates. It was triggered on an earlier PR draft, but there was a Bicep issue that I've since worked around.
