### ISSUE TITLE
Add a Getting Started page to the Azure Developer CLI extension in VS Code

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1404]
When we detect an `azure.yaml` is present in the root of the current workspace, we should show users who have the azd extension installed a Getting Started walkthrough. This walkthrough should have a big shiny button that tells them that they can provision and deploy in a single step. On clicking said button, we should open the command palette or the `azure.yaml` context menu and show `azd up`.

Pieces of information to figure out:
1. Title and description
2. Steps
	1. Title, description. Description can have up to a single button to run commands, or several that will render as hyperlinks.
	2. Optional media (Markdown, GIF, jpg)
	3. Optional completion criteria (what makes the box checked)
	4. Optional filters for whether or not it should show the step

**Comment by bwateratmsft** [comment]
The documentation for the capabilities is a bit lacking, so I wanted to add a little info.

2.ii. The media is technically "required", but you can give it an empty Markdown file. We did that in the Docker extension.
2.iii. The default is when you access the step it gets marked complete. You can alternatively have it be marked complete when commands are executed, views are viewed, a setting is changed, or on "any context" that can be set by the extension _after it has activated_. For example, we could have a step for getting AZD installed.
2.iv. Filters can be anything in [when clause contexts](https://code.visualstudio.com/api/references/when-clause-contexts)

Experimentation is possible on most of the walkthrough things, but the format of the experimentation variables is very specific, not documented anywhere I'm aware of, and in general pretty confusing.
