### ISSUE TITLE
Upgrade from 0.4.0-beta.1 to 0.5.0-beta.n issues in script

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#1406]
Blog post says: 

> and the output stated that the CLI was updated to the latest version (at that point 0.5.0-beta.1) but it was not. 

https://dev.to/lechnerc77/azure-developer-cli-episode-050-refactoring-ahead-11k6

Investigate. There could be situations where an uninstall is required and those scenarios should be handled or documented.

**Comment by danieljurek** [comment]
@lechnerc77, I'm trying to understand the issue you were seeing with our installer. The upgrade from 0.4.0-beta.1 to MSI installed versions is an expected scenario. Can you tell me more about the state of your machine when upgrading? 

* Have you previously built `azd` from source (or used `go install` to install it)? 
* Was there a previous install of `azd` in directories other than the default installation (i.e. `%LOCALAPPDATA%\Programs\Azure Dev CLI`)?

**Comment by lechnerc77** [comment]
@danieljurek thanks for coming back for this topic:

- I have not installed `azd` from source
- I did not change any defaults. Each installation or upgrade was executed via the Powershell command given in the `azd` README.md
- I am quite sure that I used the "normal" Powershell within Windows Terminal for the installation without admin privileges. Having said that, I am not 100% sure if I used Admin privileges for the very first installation of `azd`. 
When the installation of 0.5.0 failed in the normal Powershell, I indeed tried it also in one with Admin privileges, but that did not change anything. The version output still stated 0.4.0-beta.x

**Comment by heaths** [comment]
If you run `get-command azd`, what path does it return?

**Comment by lechnerc77** [comment]
This is the output: 

```powershell
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     azd.exe                                            0.0.0.0    C:\Users\drchr\AppData\Local\Programs\Azure Dev CLI\azd.exe
```

So path is `C:\Users\drchr\AppData\Local\Programs\Azure Dev CLI\azd.exe`

**Comment by heaths** [comment]
We looked at one user's machine and found the existing _azd.exe_ had a newer last-modified time than the creation-time which, for an unversioned file, means MSI won't overwrite it by default. @danieljurek we should make azd.exe versioned on Windows. There's also a couple things I will do in the MSI, but versioning the file would be the best defense. Then the version always wins.
