### ISSUE TITLE
InvalidAuthenticationTokenTenant

### ISSUE THREAD

**Issue by Jeroen-VdB** [Azure/azure-dev#1409]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here: 
azd version 0.5.0-beta.3 (commit 1c23678aade587d5b9685a256a3c1d2d7f4b42e0)

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 
{
  "azure-cli": "2.44.1",
  "azure-cli-core": "2.44.1",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "datafactory": "0.6.0"
  }
}

**Describe the bug**
```
ERROR: loading environment: initializing environment: prompting for location: listing locations: failed retrieving Azure location for account 'myCustomersSubscriptionId': failed getting next page of locations: GET https://management.azure.com/subscriptions/myCustomersSubscriptionId/locations
--------------------------------------------------------------------------------
RESPONSE 401: 401 Unauthorized
ERROR CODE: InvalidAuthenticationTokenTenant
--------------------------------------------------------------------------------
{
  "error": {
    "code": "InvalidAuthenticationTokenTenant",
    "message": "The access token is from the wrong issuer 'https://sts.windows.net/myCustomersTenantId/'. It must match the tenant 'https://sts.windows.net/myCustomersTenantId/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/myCustomersTenantId' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later."
  }
}
--------------------------------------------------------------------------------
```

**To Reproduce**
Use `azd login` to login with my user account.
Use `azd init` to initialize a new project.
Select an Azure Subscription from my customer's tenant.

**Expected behavior**
Being able to pass a tenant-id with `azd login` to log into my customer's tenant with a user account (and not a service principal).
Just like you can with `az login --tenant`.

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

**Comment by Jeroen-VdB** [comment]
If anyone else is facing the same issue, I use the workaround described in this comment: https://github.com/Azure/azure-dev/issues/1398#issuecomment-1386042866.

**Comment by vhvb1989** [comment]
fixed by https://github.com/Azure/azure-dev/pull/1478

**Comment by rajeshkamal5050** [comment]
@Jeroen-VdB Fix should be part of the next release. 

If you want to try with the daily/bleeding edge builds. Please refer here - https://github.com/Azure/azure-dev/tree/main/cli/installer#download-from-daily-builds Let us know if you run into issues.
