### ISSUE TITLE
As a dev, I can easily diff my local IaC code with remote Azure environment 

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#141]
A developer needs to be able to see what impact their IaC code changes are having with remote azure environment changes.

Includes `what-if` command/pre-flight.

**Comment by ellismg** [comment]
For Terraform this would mean `plan` and for Pulumi it would mean `preview`.

**Comment by savannahostrowski** [comment]
Related to provision caching

**Comment by ellismg** [comment]
We should also think about what this might mean in the case of ADE - will there be some sort of `what-if` mode there, or is this something we won't support in something like ADE.  /cc @wbreza since he's been thinking about ADE stuff.

**Comment by ellismg** [comment]
We'll also need some work from @Austinauth at some point to help us provide a better UX over this experience.  Our current thinking is that we will do some up-front engineering investigation and spike out a very rough UX to understand the problem space, then sync with @Austinauth in Late August/Early September to start designing the right UX.

We can probably put the feature behind a feature flag with the dev UX while we develop it, to let us land changes while we're still exploring the UX.
