### ISSUE TITLE
Investigate GitHub CLI dependency removal

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#1416]
Today GitHub CLI is only required for `azd pipeline config` when using GitHub Actions. 

- Explore any existing Go SDK options for removing GitHub CLI dependency. 
- Analyze existing CLI usage in Azd and map it to the Go SDK features. 
- Come up with rough estimates on the effort required. Based on that we can decide.

Context
- #821

**Comment by vhvb1989** [comment]
Estimation of time for replacing gh-cli with api (REST/GraphQL)

List of the current required operations from github interface:

- secrets api:
  - ListSecrets()
  - SetSecret()
This is REST: https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#list-organization-secrets
This is low cost. A ~2 days

- authentication
  - Login()
  - GetAuthStatus()
Requires implementing device flow: https://docs.github.com/en/developers/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps#identifying-users-on-your-site
This is moderate to high cost. ~5 days

- Repositories
  - ListRepositories()
  - ViewRepository()
  - CreatePrivateRepository()
This is REST: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-organization-repositories
This is low cost. ~2 days

- Actions
  - GitHubActionsExists()
This is REST: https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28
This is low cost. ~1 day

- Others
  - GetGitProtocolType()
This is the protocol selected for talking to GitHub (either HTTPS or SSL).
This information might be discovered from the local files, as it depends on how the repo was cloned
This is low cost. ~1 day

Results:
The overall estimation for switching to GitHub api is ~10 days of work.

Notes:
-  A hybrid approach of consuming REST api + gh-cli for generating auth tokens and managing auth-flow will cost ~5 days. This approach would reduce the manual output parsing from gh-cli result.
- Supporting authentication requires a plan for maintaining a `OAuth application`
