### ISSUE TITLE
[Issue] Standard env var name for flags?

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1419]
Right now we use `USE_APIM` as the env var name to enable APIM in a template.  As we add more features we'll likely add more flags.  To avoid naming conflicts, we should consider prefixing with either AZURE_ or AZD_

**Comment by vhvb1989** [comment]
dup? https://github.com/Azure/azure-dev/issues/589

**Comment by rajeshkamal5050** [comment]
Closing this in favor of above issue #589
