### ISSUE TITLE
[Issue] Unhelpful error message on `azd pipeline config`

### ISSUE THREAD

**Issue by timheuer** [Azure/azure-dev#1420]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 0.5.0-beta.3 (commit 1c23678aade587d5b9685a256a3c1d2d7f4b42e0)

**Output from `az version`** 
{
  "azure-cli": "2.44.1",
  "azure-cli-core": "2.44.1",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "azure-dev": "0.0.1b1539385",
    "containerapp": "0.3.20"
  }
}

**Describe the bug**
When running `azd pipeline config` I get:
```
 timheuer@GRIMSEL2   todo-csharp    azd pipeline config
Using pipeline provider: GitHub

ERROR: pre-config check error from GitHub provider: failed running gh auth status exit code: 1, stdout: , stderr: github.com
  X github.com: the token in GITHUB_TOKEN is missing required scope 'read:org'

: exit status 1
```

**To Reproduce**
1. create a todo-csharp-cosmos-sql
2. azd pipeline config

**Expected behavior**
It helps me create the workflow or tells me how to resolve the error it found.

**Comment by rajeshkamal5050** [comment]
@wbreza can you check if related to tge OIDC and/or authn changes mandating updates to azure-dev.yml?

https://github.com/Azure/azure-dev/releases/tag/azure-dev-cli_0.5.0-beta.1

**Comment by timheuer** [comment]
Ok, I think I may have found the issue but still suggest looking at the e2e and error messages being provided.  On my machine I had an ENV variable for GITHUB_TOKEN that was tied to a appid token.  So azd was using that env variable as the auth and failing.  The error message wasn't clear to me and it looks just to pass along the native error message.  So that's the first thing I noticed.

Second, I did NOT have any `.github` folder in my repo and _assumed_ that `azd pipeline config` would actually help configure a workflow for me.  It does not, it simply configures the required secrets that any potential workflow may use...and assumes that the workflow already existed.  At the end of that command I now have a bunch of repo secrets set (yay!) but no working workflow file.  I had an expectation that 'config' would actually configure a workflow/pipeline for me and it does not.

**Comment by wbreza** [comment]
> Ok, I think I may have found the issue but still suggest looking at the e2e and error messages being provided. On my machine I had an ENV variable for GITHUB_TOKEN that was tied to a appid token. So azd was using that env variable as the auth and failing. The error message wasn't clear to me and it looks just to pass along the native error message. So that's the first thing I noticed.
> 
> Second, I did NOT have any `.github` folder in my repo and _assumed_ that `azd pipeline config` would actually help configure a workflow for me. It does not, it simply configures the required secrets that any potential workflow may use...and assumes that the workflow already existed. At the end of that command I now have a bunch of repo secrets set (yay!) but no working workflow file. I had an expectation that 'config' would actually configure a workflow/pipeline for me and it does not.

Thanks for clarifying.  Today `azd` does not generate a github workflow for you.  You can use one of the workflows from any our [templates examples](https://github.com/Azure-Samples/todo-nodejs-mongo/blob/main/.github/workflows/azure-dev.yml) as a starting point and customize from there.

**Comment by timheuer** [comment]
Thanks @wbreza  -- I would encourage better error messages to indicate the two fail cases I got.
1-auth is invalid -- make it more friendly and guide me to resolution
2-if no workflow is found, let me know that you helped configure the secrets but no workflow was found to execute...and point me to the examples.

**Comment by wbreza** [comment]
Linking #135 since it also discusses adding some boilerplate workflows for az-devify experience.

**Comment by wbreza** [comment]
> Thanks @wbreza -- I would encourage better error messages to indicate the two fail cases I got. 1-auth is invalid -- make it more friendly and guide me to resolution 2-if no workflow is found, let me know that you helped configure the secrets but no workflow was found to execute...and point me to the examples.

The request is totally reasonable.  
**For item 1** - this is more of an edge case scenario since you had a `GITHUB_TOKEN` env var set.  We shell out to the github CLI for authenticating into github to get authentication status.  If you're account was not logged in we would prompt for login at this point.  We can definitely do a better job of giving the user some tips around removing their `GITHUB_TOKEN` if we detect it was previously set.

**For item 2** - Agreed that we should detect that a workflow wasn't found and point the user to some examples.  We have some other items on the backlog including #705 to help fingerprint the application and generate an informed opinion for infrastructure.  The same would also apply to pipeline workflow files for github and/or azdo.

**Comment by timheuer** [comment]
> We shell out to the github CLI for authenticating into github to get authentication status

So interestingly enough, I didn't have the GH CLI even installed ;-) -- so that might be a case to check for as well.  I had a hunch something was missing and when I added that the errors improved.

**Comment by rajeshkamal5050** [comment]
> So interestingly enough, I didn't have the GH CLI even installed ;-) -- so that might be a case to check for as well. I had a hunch something was missing and when I added that the errors improved.

Yes, we have an issue tracking to simplify and validate dependencies. Should be handled as part of that.
- #821

**Comment by wbreza** [comment]
> > We shell out to the github CLI for authenticating into github to get authentication status
> 
> So interestingly enough, I didn't have the GH CLI even installed ;-) -- so that might be a case to check for as well. I had a hunch something was missing and when I added that the errors improved.

@vhvb1989 - Don't we already have a check in pipeline config to validate all required external tools are installed?

**Comment by weikanglim** [comment]
Based on the error message, `gh` should have been installed. We received an exit code of 1 from `gh`, with the standard error messages logged:

` X github.com: the token in GITHUB_TOKEN is missing required scope 'read:org'`

Unfortunately, depending on an external tool means we also miss out on the exact error to propose a different type of improvement. Thus, our hands are tied. I would propose the improvement to make it slightly more user friendly:

from

`ERROR: pre-config check error from GitHub provider: failed running gh auth status exit `

to

```
ERROR: authenticating user against GitHub: failed running 'gh auth status', exit code: 1, stdout: , stderr: github.com
  X github.com: the token in GITHUB_TOKEN is missing required scope 'read:org'

: exit status 1
```

**Comment by wbreza** [comment]
Reassigning to @vhvb1989 who will address the `GITHUB_TOKEN` issues.
