### ISSUE TITLE
Cannot switch Azure tenant through `azd` cli

### ISSUE THREAD

**Issue by kwkraus** [Azure/azure-dev#1430]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 0.5.0-beta.3 (commit 1c23678aade587d5b9685a256a3c1d2d7f4b42e0)

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 
{
  "azure-cli": "2.42.0",
  "azure-cli-core": "2.42.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}

**Describe the bug**
Trying to switch Azure tenants to provision and deploy an application to a new subscription.  When using `azd login` and then running `azd provision`, the list of subscriptions available are shown for the old tenant.  There is no obvious mechanism for switching tenants for the interactive user through the `azd login` command.

When enabling the `az` cli login feature by running `azd config set auth.useAzCliAuth true` command and running the `az login --tenant xxx.onmicrosoft.com` command, the `azd` cli fails to provision due to a conflict with the configured default subscription.

![image](https://user-images.githubusercontent.com/20584716/213788071-66d4b7c4-1963-4b24-91b0-62cfaeedc17b.png)

**To Reproduce**
Login using `azd login` and view your available subscriptions by running `azd init -e environmentname`.   Log out using the `azd logout` command.  There are no switches within the `azd` cli that allow for switching tenants.

To use the `az` CLI for authenticating to Azure, run the following commands:
 - `azd logout`
 - `azd config set auth.useAzCliAuth true`
 - `az login --tenant xxx.onmicrosoft.com`
 - `azd provision`
 
The output below shows the failure/conflict between the new tenant and the default subscription (which doesn't exist in the new tenant)

**Expected behavior**
Some way to successfully switch tenants and select appropriate subscription for provisining and deployment

**Environment**
Information on your environment:
    * PowerShell 7.3.1
    * Windows 11

**Additional context**

**Comment by gkulin** [comment]
current workaround (per @weikanglim) 

1. `azd logout`
2. `azd config set auth.useAzCliAuth true`
3. `az login --tenant <tenant>`
4. `azd config unset defaults.subscription`

**Comment by rajeshkamal5050** [comment]
Should be fixed as part of a common fix which is underway for the following,
- https://github.com/Azure/azure-dev/issues/1409
- https://github.com/Azure/azure-dev/issues/1398

**Comment by vhvb1989** [comment]
fixed by https://github.com/Azure/azure-dev/pull/1478

**Comment by rajeshkamal5050** [comment]
Fix should be part of the next release. 

If you want to try with the daily/bleeding edge builds. Please refer here - https://github.com/Azure/azure-dev/tree/main/cli/installer#download-from-daily-builds Let us know if you run into issues.
