### ISSUE TITLE
[Issue] Error message on Keyvault is not actionable

### ISSUE THREAD

**Issue by paulyuk** [Azure/azure-dev#1431]
**Output from `azd version`**
azd version 0.5.0-beta.3 (commit 1c23678aade587d5b9685a256a3c1d2d7f4b42e0)
in a Codespace

**Describe the bug**
I'm migrating and testing the /infra for aka.ms/dapralbums to the latest modules in /core.  

In my test of an `azd provision` the keyvault creation failed saying it exists but in soft delete state.  This is weird because we generate pseudo unique names like kv-*******.  Anyhow, the error is not actionable to do the next step of look up the resource, because it simply does not tell me the name it tried to create.

What I saw was:
```bash
  (✓) Done: Resource group: rg-dapralbums1
  (✓) Done: Log Analytics workspace: log-u72bywvxdfhdo
  (✓) Done: Application Insights: appi-u72bywvxdfhdo
  (✓) Done: Portal dashboard: dash-u72bywvxdfhdo
  (✓) Done: Container Apps Environment: cae-**u72bywvxdfhdo**

ERROR: deployment failed: error deploying infrastructure: failed deploying: deploying to subscription:

Deployment Error Details:
ConflictError: A vault with the same name already exists in deleted state. You need to either recover or purge existing key vault. Follow this link https://go.microsoft.com/fwlink/?linkid=2149745 for more information on soft delete.
```

What I expected was the kevault name, so I could then do the instructions in that link.  The instructions in that link are also wrong btw, because what you actually need to do is pass in the --keyvault-name from the output of the error

```bash
az keyvault key list-deleted --vault-name **kv-u72bywvxdfhdo**
```

Once I thought about it I was able to reverse engineer the name using the unique string output from the appinsights and dashboard resources created before, but that's not an awesome user experience.

**Comment by rajeshkamal5050** [comment]
@hemarina can we add a minor fix to the error message to also contain the name in conflict?

**Comment by wbreza** [comment]
FYI - The error message that we are displaying is the direct error from the ARM control plane
