### ISSUE TITLE
azd docs command and flag

### ISSUE THREAD

**Issue by Austinauth** [Azure/azure-dev#1433]
Related to #822

## Description
We'd like to propose adding an `azd docs` command and an `azd <command> --docs` flag.

### Behavior
Behavior for this command should be fairly simple. Inputing `azd docs` should open the [azd reference](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/reference) page in a new browser window (see Figure 1.A below).

Inputing `azd <command> --docs` should behave similarly, opening a new browser window to the reference docs section for the specific command entered (see Figure 1.B below).

**Figure 1.A**
![image](https://user-images.githubusercontent.com/6994218/213804854-a2f83ea2-dc8d-4fca-9f67-3e2a6a192aa9.png)

**Figure 1.B**
![image](https://user-images.githubusercontent.com/6994218/213805208-af9c1928-c32a-45f4-b88b-6b5558c51922.png)

**Comment by rajeshkamal5050** [comment]
Moving to Gallium @savannahostrowski

**Comment by savannahostrowski** [comment]
As a start here,  we should support just a top-level docs command.

The flag will require some documentation updates. @gkulin for your consideration!

**Comment by ellismg** [comment]
Do we need a top level `docs` command or could we have `azd --docs` behave as `azd docs` would?

I do think the idea of having some browser based view of our docs is a good idea, I'm less sure we need an entire top level command to do (especially if we are going to support `--docs` on all the sub commands).

**Comment by savannahostrowski** [comment]
Now that you mention it, I'd probably prefer a flag to avoid bloating the top-level commands. 

I don't think we need to worry about more granular docs right now.
