### ISSUE TITLE
azd down UX improvements

### ISSUE THREAD

**Issue by Austinauth** [Azure/azure-dev#1434]
## Description
UX overhaul for `azd down`.  The `azd down` command should be updated to follow the latest design patterns. Includes revamped messaging and error states.

### Behavior
Clickable [prototype here](https://www.figma.com/proto/iIRRiGPuKIfaSFfMJXcYle/azd-resource-provisioning?page-id=1434%3A135002&node-id=1436%3A135020&viewport=5845%2C-785%2C1&scaling=min-zoom&starting-point-node-id=1436%3A135020). Use `<` and `>` keys to navigate.

#### Figure 1.A: Default
![Image](https://user-images.githubusercontent.com/6994218/213807947-9b63ba32-0282-4dc6-a2f6-4f5a826896f5.png)

#### Figure 1.B: Opting not to continue with deletion
![Image](https://user-images.githubusercontent.com/6994218/213808457-87ff3d4b-5801-4ced-91ca-d989b5bcc986.png)

#### Figure 1.C: Opting not to delete Key Vaults
![Image](https://user-images.githubusercontent.com/6994218/213808000-4b6d9a3d-583d-4d64-b829-106a0d0546ac.png)

Tagging @rajeshkamal5050 and @vhvb1989 for prioritization and sizing.

**Comment by Petermarcu** [comment]
There will likely be scenarios where we can't get "down" to be perfect. Should we be adding a disclaimer that its not guaranteed to be perfect and we recommend customer frequently audit their resource usage using the azure portal? There is real money at stake here. :)
