### ISSUE TITLE
Add version property to azd.exe

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#1435]
MSI installation compares file version properties to determine whether it should overwrite (in addition to other strategies). We should version `azd.exe` to have MSI installations succeed properly in more cases.

In the future when we get `azd.exe` versioning properly we can remove `REINSTALLMODE`.

_Originally posted by @danieljurek in https://github.com/Azure/azure-dev/pull/1424#pullrequestreview-1264437252_

**Comment by rajeshkamal5050** [comment]
@danieljurek do we need this to be fixed soon? can you add it to a milestone accordingly?

**Comment by rajeshkamal5050** [comment]
@danieljurek based on the comments from @heaths here https://github.com/Azure/azure-dev/pull/1424#issuecomment-1399758455 adding to a later milestone for us to look at.

**Comment by heaths** [comment]
@rajeshkamal5050 the version change should be done ASAP. We can only remove the REINSTALLMODE property after a few versions of the MSI have been out for a while.
