### ISSUE TITLE
[Issue] Have to run `azd login` multiple times a day in a GH CodeSpace

### ISSUE THREAD

**Issue by paulyuk** [Azure/azure-dev#1443]
I have to run `azd login` multiple times a day in a GH CodeSpace.  This is often times after a CodeSpace logs out, but not always.  I'd be happy to let you look inside my sub to see if there's more info as to why.  

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

**Expected behavior**
Ideally my login would be durable enough to last for days before expiring.  The 2FA steps after this are painful to do multiple times a day.

**Comment by savannahostrowski** [comment]
@weikanglim and I were chatting and it seems like some engineering investigation is needed here. Assigning him as well.

**Comment by rajeshkamal5050** [comment]
We haven't been able to successfully able reproduce this one. Reducing to P1.

@v-xuto can you try reproducing this?

**Comment by v-xuto** [comment]
@rajeshkamal5050  We didn't reproduce the issue, we tried three or four times and it is always logged in.

**Comment by savannahostrowski** [comment]
@paulyuk Can you repro this still?

**Comment by rajeshkamal5050** [comment]
Since, we weren't able to repro this. Moving it to Backlog. 
If we see any repros/updates on this issue. We can pull it back in.

@savannahostrowski @ellismg

**Comment by savannahostrowski** [comment]
I'm actually going to close this for now. If it is reported again, we can reopen.
