### ISSUE TITLE
Refactor `ServiceConfig` and streamline resolution of Framework services & service targets

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#1450]
As we build out more support for additional language/frameworks & service targets we have an opportunity to introduce new components to help instantiate and consume the various services.

- FrameworkServiceManager (Help manage invoking underlying framework services in projects)
- ServiceTargetManager (Help manage the creation and deployment to various azure service targets)

**Comment by weikanglim** [comment]
Should we also have `ProjectManager`?

 Not required for this PR but feels like we need a `ProjectManager` or similar to handle the getting/loading of projects vs this global `GetProject(...)` func with a list of growing dependencies.

_Originally posted by @wbreza in https://github.com/Azure/azure-dev/pull/1478#discussion_r1095170314_

**Comment by rajeshkamal5050** [comment]
Moving to Gallium

**Comment by wbreza** [comment]
Closing since we now have the `ProjectManager` and `ServiceManager` which allows for easier usage and access to framework and service targets.

Resolved with #1754
