### ISSUE TITLE
Document well-known environment variables

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1458]
We should start documenting the list of well-known variables. We might also make different design considerations of breaking down how these configurations are provided. Traditionally, the `environment` has been used a conglomerate source of config which might be an increasingly complex config mechanism.

# Environment Variables

## Input Parameters Substitution

Environment variables can be referenced in IaC provider parameter files (`*.parameters.json` for Bicep, `*.tfvars.json` for Terraform) as part of provisioning. When an environment variable substitution syntax is encountered, azd will automatically substitute the reference with the actual environment variable value set. Substitution also occurs for certain configuration settings in `azure.yaml` (properties documented field 'Supports environment variable substitution'), and in deployment configuration files, such as deployment manifests for `aks`.

## Example: Input Parameters Substitution (Bicep)

Suppose that you have the environment variable `AZURE_LOCATION` set:

Bash: `export AZURE_LOCATION=westus3`
PowerShell: `$env:AZURE_LOCATION='westus3'`

In `main.parameters.json`, you can reference `AZURE_LOCATION` and allow for environment substitution using the following syntax:

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "location": {
      "value": "${AZURE_LOCATION}"
    }
  }
}
```

**Provide default values**

To set `location` to the value `eastus2`  if `AZURE_LOCATION` is not set, the syntax `${AZURE_LOCATION=eastus2}` can be used. For more details on the syntax, see [here](https://github.com/a8m/envsubst#docs).

# Environment-specific `.env` File

Outputs for infrastructure provisioning are automatically stored as environment variables in an `.env` file, located under `.azure/<environment name>/.env`. This allows for a local application, or deployment scripts, to leverage variables stored in the `.env` file to reference Azure-hosted resources if needed. To see these outputs, run `azd env get-values`,  or `azd env get-values --output json` for JSON output.

## azd-provided Environment Variables

These are variables that are automatically provided by azd.

| Name | Description | Examples | When available |
| --- | --- |  --- | --- |
| `AZURE_ENV_NAME` | The name of the environment in-use. | `todo-app-dev` | When an environment is created (i.e. after running `azd init` or `azd env new`). |
| `AZURE_LOCATION` | The location of the environment in-use. | `eastus2` | Right before an environment is provisioned for the first time. |
| `AZURE_PRINCIPAL_ID` | The running user/service principal. | `925cff12-ffff-4e9f-9580-8c06239dcaa4` | Determined automatically during provisioning (ephemeral). |
| `AZURE_SUBSCRIPTION_ID` | The targeted subscription. | `925cff12-ffff-4e9f-9580-8c06239dcaa4` | Right before an environment is provisioned for the first time. |
| `SERVICE_<service>_IMAGE_NAME` | The full name of the container image published to Azure Container Registry for `containerapp` services. | `todoapp/web-dev:azdev-deploy-1664988805` | After a successful publishing of a `containerapp` image |

## User-provided Environment Variables

These are variables that can be declared as an infrastructure output parameter (which is automatically stored in `.env`), or set directly by the user in the environment (`azd env set <key> <value>`). azd will read the values as configuration and perform differently.

| Name | Description | Examples | Effect |
| --- | --- |  --- | --- |
| `AZURE_AKS_CLUSTER_NAME` | The name of the Azure Kubernetes Service cluster to target. | `aks-my-cluster` | Required property for deployment of an `aks` service. |
| `AZURE_RESOURCE_GROUP` | The specific resource group to target. Type `string`. | `rg-todo-dev` | azd will not perform resource group discovery, and instead references this resource group. Note that azd does not control the authored IaC configuration files, thus changes to IaC files may be needed.  |
| `AZURE_CONTAINER_REGISTRY_ENDPOINT` | The Azure Container Registry endpoint to publish docker image. Type `string`. | `myexampleacr.azurecr.io` | Required property for deployment of a `containerapp` or `aks` service. |
| `SERVICE_<service>_ENDPOINTS` | The endpoints for the particular service. Type `array` (bicep) / `list`-equivalent (terraform). | `['endpoint1', 'endpoint2']` | Sets the public endpoints for the particular service will be used by azd for display. By default, azd discovers the automatically assigned hostnames for a given host. i.e. `*.azurewebsites.net` for `appservice`. |

**Comment by weikanglim** [comment]
@ellismg Feel free to use this as a reference and also live-documentation for editing as you're exploring the environment redesign.

**Comment by savannahostrowski** [comment]
Is this ready for docs? We need to get this in before content freeze on 5/15

**Comment by rajeshkamal5050** [comment]
> Is this ready for docs? We need to get this in before content freeze on 5/15

@weikanglim can you see if it looks good for @gkulin to consume?

**Comment by weikanglim** [comment]
@rajeshkamal5050 I'll need to reword the content to describe the `.env` file, and check in with other devs.

**Comment by weikanglim** [comment]
@savannahostrowski @gkulin It's ready for consumption. The final edit is in the initial post.

**Comment by savannahostrowski** [comment]
@gkulin Let's make sure that we try to land this before 5/15.
