### ISSUE TITLE
[Issue] SWA deployment results in resource not found

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#146]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

azd version 0.1.0-beta.2 (commit b6fb9fe470c090ff1eee77c817389d3ab34a3140)

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 

{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.25.0",
    "azure-iot": "0.14.1",
    "containerapp": "0.3.6",
    "storage-preview": "0.8.3"
  }
}

**Describe the bug**

Deployment fails with simple swa repo

**To Reproduce**

`azd up -t jongio/azd-create-react-app-swa`

You'll see this:

```
Error: deploying service: deploying service web package: failed retrieving static web app deployment token: failed getting staticwebapp api key: exit code: 3, stdout: , stderr: ERROR: (ResourceNotFound) The Resource 'Microsoft.Web/staticSites/cra-swa-azd-003web' under resource group 'cra-swa-azd-003-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource 'Microsoft.Web/staticSites/cra-swa-azd-003web' under resource group 'cra-swa-azd-003-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
: exit status 3
```

If you re-run `azd deploy` it will succeed.

**Expected behavior**
resource is deployed

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]
vs code

**Additional context**

**Comment by vhvb1989** [comment]
wasn't able to repro on my end:

![image](https://user-images.githubusercontent.com/24213737/179903009-5fdc79d7-7a7e-414f-ba81-a7c1c29c4018.png)

> If you re-run azd deploy it will succeed.

This makes me think that we need to add some `delay-retry` after provisioning and if deploy fails with resource-not-found. As Azure might have told us that the resource is created and ready, but the Resource Graph make take a few more seconds to be updated and ready to find the new resource.

**Comment by jongio** [comment]
Thanks for trying to repo. 

I suspect it is more than that since it fails looking for Microsoft.Web/staticSites/cra-swa-azd-003web.  It shouldn't be looking for a resource with that name, it should be querying based on the azd-service-name tag.

**Comment by vhvb1989** [comment]
ah, that search happens after looking for the `azd-service-name` tag, in case that returns zero results. 
For example, in the current preview version `0.1.0-beta.2` if you use an environment name with capital letters, searching for the tag name returns zero results and then we would try to look for the resource name directly (supposing that the bicep code is not using the tag-naming and auto-gen naming approach, and instead giving a fixed name)

**Comment by jongio** [comment]
What is interesting is subsequent `azd deploy` calls succeed, so I thought it was a provisioning delay as well, but that error message suggests otherwise.

**Comment by jongio** [comment]
I have tried this again twice and I didn't see the error.  @puicchan Can you please share your results?

**Comment by puicchan** [comment]
Today, I get a diff error. Running `azd deploy` again deployed the app. See below. Started in an empty folder; used "jong" as environment name. I am using `azd version 0.1.0-beta.2`. 

I did not start in an empty folder yesterday and did `azd up` in a directory containing sub folders with azd project folders. The observation: azd up failed; cannot find the resource group. Running `azd deploy` again did not deploy the app. Created a new environment `jong719` and managed to `azd up`.

---

Deploying to environment: default

Deploying project to Azure Static Web Apps...

, stderr: npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
✖
✖ Deployment Failed :(
✖ Deployment Failure Reason: request to https://swalocaldeploy.azureedge.net/downloads/versions.json failed, reason: getaddrinfo ENOTFOUND swalocaldeploy.azureedge.net
✖ For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/azure/static-web-apps/
✖ If you believe this behavior is unexpected, please raise a GitHub issue at:
  https://github.com/Azure/static-web-apps-cli/issues/new/choose
: exit code: 1, stdout:
Welcome to Azure Static Web Apps CLI (1.0.2)

Deploying front-end files from folder:
  D:\codes\jong\src\my-app\build


Deploying to environment: default

Deploying project to Azure Static Web Apps...

, stderr: npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
✖
✖ Deployment Failed :(
✖ Deployment Failure Reason: request to https://swalocaldeploy.azureedge.net/downloads/versions.json failed, reason: getaddrinfo ENOTFOUND swalocaldeploy.azureedge.net
✖ For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/azure/static-web-apps/
✖ If you believe this behavior is unexpected, please raise a GitHub issue at:
  https://github.com/Azure/static-web-apps-cli/issues/new/choose
: exit status 1

**Comment by rajeshkamal5050** [comment]
@v-xuto can you see if this is reproducible?

**Comment by v-xuto** [comment]
@rajeshkamal5050 We have tried, and we can reproduce this issue.

**Comment by rajeshkamal5050** [comment]
Closing this issue as not reproducible.
