### ISSUE TITLE
January Doc Plan

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1462]
We will want to get these squared away before the next major release of the CLI

- [ ] Add azd hooks info to azure.yaml and doc updates @wbreza (in draft PR - https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4109)
- [ ] New distribution channels @danieljurek 
- [x] #124 

In PR:
- [x] Add reference to awesome-azd in https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/azd-templates (replace the reference to browsing GitHub)  - https://github.com/MicrosoftDocs/azure-dev-docs/pull/1045
- [x] https://github.com/Azure/azure-dev/issues/541  - https://github.com/MicrosoftDocs/azure-dev-docs/pull/1047

**Comment by savannahostrowski** [comment]
@danieljurek - will we require doc updates for Cloudshell and/or package managers?
@rajeshkamal5050 Any other updates anticipated?

**Comment by rajeshkamal5050** [comment]
> will we require doc updates for Cloudshell and/or package managers?

@savannahostrowski were you thinking of calling CloudShell support for Feb release excluding,
- All java samples. Since we need a JDK upgrade to be done. Not sure if it will get done for our Feb release @danieljurek Any ETA?
- All ACA samples. Since docker daemon on the host is not supported in Cloud Shell #1206 

> Any other updates anticipated?

@savannahostrowski nothing major, edited the base update to reflect the new distribution channels @danieljurek

**Comment by savannahostrowski** [comment]
Yeah - so I don't want to announce Cloudshell until the JDK version has been updated. Would be good to know if we think that's liable to land before 2/16.

We should add docs for the Docker limitation - I don't view that as blocking on our end though.

**Comment by savannahostrowski** [comment]
@gkulin We should also update:
- https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/make-azd-compatible?pivots=azd-convert
- https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/troubleshoot#solution-5

to add details about running  `sudo apt-get update && sudo apt-get install xdg-utils` or having those installs/updates as part of your devcontainer.json.

We can chat more about specifics.

**Comment by gkulin** [comment]
calling out awesome-azd: https://github.com/MicrosoftDocs/azure-dev-docs/pull/1045

preview install steps: https://github.com/MicrosoftDocs/azure-dev-docs/pull/1047

**Comment by gkulin** [comment]
pr for #124: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4142
