### ISSUE TITLE
Provide support for adding in your own company approved Project template repos for azd init command

### ISSUE THREAD

**Issue by anevjes** [Azure/azure-dev#147]
**Request**
As a large enterprise I would want to be able to lookup my own Company governed azd templates. Please provide support to linking in your own Company approved Project templates to the azd cli. I can see that there is a [repo.yaml](https://github.com/Azure/azure-dev/blob/main/templates/todo/projects/nodejs-mongo-aca/repo.yaml)  file located within the CLI source code - however this isn't editable by the end user within an organisation....

**Expected behavior**

repo.yaml configuration that can be applied to the entire company using azd cli...

When I type azd init - I would want to see a list of Company approved project templates.
<img width="348" alt="image" src="https://user-images.githubusercontent.com/9455286/179897980-48301ca7-118b-45c6-b7b9-d6c5a98c235d.png">

**Comment by vhvb1989** [comment]
Hello @anevjes 
Thank you for using azd :)

While the team talks about your request, I wanted to mention that you can run `azd init -t <owner>/<repository>` to use any template hosted in github (even a private repo, just by setting up git with your personal access token as auth).

both `azd up` and `azd init` supports the template parameter:
```
-t, --template string   Template to use when initializing the project. You can use: 1. Full URI 2. <owner>/<repository> or 3. <repository> - if part of the azure-samples organization
```

**Comment by jongio** [comment]
That's a great request! We'll discuss that. 

In addition to what Victor mentioned, you can also use a complete path to a repo, https://yourdomain/yourorg/yourrepo

Understood your request though, and it is a great one

**Comment by ellismg** [comment]
@wbreza had a draft PR at one point which allowed picking up a list of locally installed templates out of `~/.azd` which could be related.

It would be interesting to think about configuring how the JSON file we interpret is loaded.  Instead of having it compiled in, what if we pulled it from some remote source and that was configurable?  Or perhaps we keep our version compiled in but allow a way to override the location with an external source?

@anevjes How would you imagine delivering the list of curated templates you want from your organization?

**Comment by anevjes** [comment]
> @wbreza had a draft PR at one point which allowed picking up a list of locally installed templates out of `~/.azd` which could be related.
> 
> It would be interesting to think about configuring how the JSON file we interpret is loaded. Instead of having it compiled in, what if we pulled it from some remote source and that was configurable? Or perhaps we keep our version compiled in but allow a way to override the location with an external source?
> 
> @anevjes How would you imagine delivering the list of curated templates you want from your organization?

@ellismg  - I would like to have another command within azd that will allow me to set a remote path to my template repos.

upon first time azd setup - the developer would need to supply this additional command in order to view the approved template project patterns... This can be handled via a simple readme file to get devs up and running...

**Comment by rajeshkamal5050** [comment]
@jongio @savannahostrowski 
Doesn't seem to be a must fix for our next milestone. Moving it to On Deck for now.

**Comment by rajeshkamal5050** [comment]
https://devblogs.microsoft.com/azure-sdk/azure-developer-cli-azd-september-2023-release/#specify-custom-template-sources-for-azd-init
