### ISSUE TITLE
[doc] azd login using device code - devcontainer

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#1477]
Feedback from @aaronpowell when trying eShopOnWeb

Cloned the PR locally under WSL2, opened in VS Code Insiders and launched with the provided devcontainer

Ran azd login to connect to Azure
- Had to provide the --use-device-code flag as it couldn't launch a browser from the devcontainer
- Might be worth having that documented as sometimes it'll launch a browser (I find it inconsistent across projects I've put azd into)

**Comment by vhvb1989** [comment]
@aaronpowell , do you have any logs from any time the browser didn't open?

Did azd give an errror?  or nothing happened?

**Comment by aaronpowell** [comment]
I'll get the exact error message when I next encounter it, but it's generally related to using a Container image that doesn't have `xdg-utils` installed.

**Comment by rajeshkamal5050** [comment]
We have documented this as part of doc updates #1475
