### ISSUE TITLE
Azd pipeline config - github provider - Federated credential - 409 conflict

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#1482]
Azd fails when trying to set up federated credential for a new repository using `main` as federated credential if the credential already exists

vivazqu@ubuntu22:~/workspace/build/pp$ azdd pipeline config --principal-name viva-fooo

Configure your azd pipeline

  (✓) Done: Checking current directory for Git repository
  (✓) Done: Creating or updating service principal viva-fooo

ERROR: failed configuring authentication: failed creating federated credential: POST https://graph.microsoft.com/v1.0/applications/bdec736f-4453-4545-abd9-2a87a8631f0a/federatedIdentityCredentials
--------------------------------------------------------------------------------
RESPONSE 409: 409 Conflict
ERROR CODE: Request_MultipleObjectsWithSameKeyValue
--------------------------------------------------------------------------------
{
  "error": {
    "code": "Request_MultipleObjectsWithSameKeyValue",
    "message": "FederatedIdentityCredential with name main already exists.",
    "innerError": {
      "date": "2023-02-02T21:29:38",
      "request-id": "d60c4453-57cc-4363-b006-d1c69fc1e732",
      "client-request-id": "d60c4453-57cc-4363-b006-d1c69fc1e732"
    }
  }
}
--------------------------------------------------------------------------------

Repro:

```to repro:

azdd pipeline config --principal-name a-name-for-principal

then

azdd pipeline config --principal-name a-name-for-principal --remote-name extraremote

*When azd ask if you want to create a new private repo, select yes
```

**Comment by rajeshkamal5050** [comment]
Had an offline conversation with @wbreza @vhvb1989 

Seems a corner case. Removing blocker and not a must-fix for this 0.6 release.
