### ISSUE TITLE
Dynamic Translation of WebApp Service Types is probably broken?

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#1484]
Something I noticed while I was playing around with some other stuff, and wanted to log an issue on it before I forgot.  In https://github.com/Azure/azure-dev/pull/152, when we added support for logging resources as they were created, we needed a way to map resource IDs to logical types that would be familiar to users (e.g App Service App or Function App).

We built `GetResourceTypeDisplayName` on `AzureResourceManager` which used `GetResource` on the `AzCli` type to fetch information about the resource and then do dynamic logic (such as looking at the `kind` property, for AppServices) to figure out the type that would make sense for humans.

At the time, we were using the `az` CLI to fetch this information and ended up calling `az resource show`.  When we moved off the API, we moved to using `*armresources.Client`'s `GetByID` method.

This call requires an API version (unlike the `az resource show` operation) and [we ended up passing in the empty string](https://github.com/Azure/azure-dev/blob/9cb891aeb1c3724a4b619f42dcbca5bb7add3c51/cli/azd/pkg/tools/azcli/resources.go#L17).  I think in practice this ends up breaking the call, since the REST API returns an error saying that the `apiVersion` parameter is required.

Furthermore, it this API Version is an API Version for the RP that owns the resource, not the general ARM control plane, so there's no fixed value we can put here.

If you look more at `az resource show` you can see there are options to set the API Version to use and if you don't pass one the latest stable version is used.  If you run with `--debug --verbose` you can see it fetching information from the RP to find API versions of sub resources (I assume it does this by having a fixed mapping of "RPs -> Latest API Version to use when listing API versions of sub resources?, but have not dug in) before finally making the logical `GetByID` call using the correct API version.

In practice, all the callers of `AzureResourceManager::GetResourceTypeDisplayName` ignore the error and do a fallback based on static translation.  I suspect the end user visible change is when we deploy a function app template now, the output says App Service instead of Function App, but again, I didn't try this yet.

Assuming this is a problem, we probably want to add a `apiVersion` parameter to the `GetResource` function on the `azCLI` type and then add a version to `AzureResourceManager` that doesn't have a `apiVersion` parameter and instead does something like what the AZ CLI does, figures out the latest stable version to use.

I do think a general "here's an ARM resource ID, give me back the corresponding `GenericResource` object (or a subset that we want to expose) would be useful (in fact, I figured that's what GetResource was going to do for me first, which is why I reached for it and then noticed this issue, since I was unwilling to ignore the error).

**Comment by ellismg** [comment]
I think I will need the ability to go from a resource id (without an API version) to information about the ARM Resource sooner rather than later for some work I am doing, so I'm going to try to pull a fix for this out and land it pre-emptively.

**Comment by weikanglim** [comment]
@ellismg Thanks for finding this. I have mental notes around resource type translations (doing it the right way) in general. I'm still working with a few Azure folks to land this change, but it's likely that we want to fix the dynamic resolution for `Microsoft.web/sites` correctly and keep it.
