### ISSUE TITLE
[Issue] azd init fails; cannot connect to Azure even after successful azd login

### ISSUE THREAD

**Issue by indcoder** [Azure/azure-dev#1498]
- [ x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 0.5.0-beta.3 (commit 1c23678aade587d5b9685a256a3c1d2d7f4b42e0)

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 
azure-cli                         2.44.1

core                              2.44.1
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1

**Describe the bug**
azd init is failing when trying to connect to azure with my subscription

<img width="628" alt="image" src="https://user-images.githubusercontent.com/2099300/216815474-62a2bc49-7c98-4688-a2dd-bb537fa50e5b.png">

I expected the various subscription to show up in the dropdown; but it was empty and I have to chose the manual option. Copy pasting the subscription [I have validated this across different subcriptions], it fails with an unauthorized 401 with the error code InvalidAuthenticationTokenTenant. 

<img width="642" alt="image" src="https://user-images.githubusercontent.com/2099300/216816209-6f174cc0-c5f2-4d6e-8863-d7b86319126a.png">

<img width="955" alt="image" src="https://user-images.githubusercontent.com/2099300/216815590-96f990cf-40e2-445f-b1e4-556663721287.png">

If you see the screenshot that azd login is successful.  And you get a homeaccountid when doing an azure config list

<img width="743" alt="image" src="https://user-images.githubusercontent.com/2099300/216815785-7e858872-b5e5-4076-ab65-1d0bb92eb944.png">

**To Reproduce**
Run  azd init or azd up with any of the templates.

**Expected behavior**
Should have completed the command with azd init, or with azd up provisioned the resources on Azure
**Environment**
Information on your environment:
    * Language name and version: C#
    * IDE and version : [e.g. Visual Studio 16.3] NA

**Additional context**
Perhaps this has something to with the latest merge #1495

**Comment by vhvb1989** [comment]
@indcoder , this is already fixed in `main` branch and it is expected to be part of next week release 0.6.0

Fixed by: https://github.com/Azure/azure-dev/pull/1478

**Comment by vhvb1989** [comment]
A few options, in case you are blocked by this:
- Use the daily-release to start using the patch.
   You can install the daily-release in Lin/max with `curl -fsSL https://aka.ms/install-azd.sh | bash -s -- --version daily --verbose` and for Windows: `powershell -ex AllSigned -c "Invoke-RestMethod 'https://aka.ms/install-azd.ps1' -OutFile 'install-azd.ps1'; ./install-azd.ps1 -Version 'daily'"`

- Switch to `Azure CLI` for auth following the next workaround
     https://github.com/Azure/azure-dev/issues/1398#issuecomment-1386042866

**Comment by rajeshkamal5050** [comment]
Marking this as fixed and should be available in the next release.
