### ISSUE TITLE
Add telemetry for failed-login on multi tenant

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#1501]
details tba

**Comment by savannahostrowski** [comment]
I thought we wanted to capture this regardless of failed/success. Might be good to know the distribution of our users accounts that are multi-tenant/single tenant (as well as success/failures).

**Comment by weikanglim** [comment]
If we're implementing this, it should be tracking the "account.list_subscriptions" operation, with attributes:
1. Number of tenants fetched
2. Number of failed tenants

**Comment by weikanglim** [comment]
Completed with #1507

**Comment by weikanglim** [comment]
@savannahostrowski Do you want to create an issue to track the dashboard?

From dev side, here's what we added in telemetry:
Event name : `account.subscriptions.list`
Fields: `Properties['tenants.found']`, `Properties['tenants.failed']`

For all events, we also have `ad.account.type` <-- we can use this filter out service principals that aren't users, and this might resolve the active user mismatch with other datasets.

**Comment by savannahostrowski** [comment]
Created an issue for it on the query repo.
