### ISSUE TITLE
Credential handlers - Consume from upstream SDK's

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#1505]

**Comment by vhvb1989** [comment]
Python: https://github.com/Azure/azure-dev/pull/1574

**Comment by vhvb1989** [comment]
.NET and JS have not released the preview version yet

**Comment by vhvb1989** [comment]
.Net: https://github.com/Azure/azure-dev/pull/1652

**Comment by vhvb1989** [comment]
JS: https://github.com/Azure/azure-dev/pull/1659

**Comment by vhvb1989** [comment]
Java: https://github.com/Azure/azure-dev/pull/1661

**Comment by vhvb1989** [comment]
Java blocked by: https://github.com/Azure/azure-sdk-for-java/issues/34255

Manage Identity is not working since Identity version 1.8.1, so, when using the beta library with the Azure Developer CLI credential, the api server cannot init on App-service because ManageIdentity is not detected.
