### ISSUE TITLE
Fix spinner rendering, or enforce max length

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1513]
Our spinner rendering ends up breaking whenever the length of message exceeds terminal width. We either need to fix this, or enforce that the application has shorter progress message text.

![image](https://user-images.githubusercontent.com/2322434/217321954-5a8e362d-33c2-4a1f-8833-532a756b982d.png)

**Comment by savannahostrowski** [comment]
Same here, can we figure out what this would take to get in product before GA? This is general UX polish.

**Comment by rajeshkamal5050** [comment]
> Same here, can we figure out what this would take to get in product before GA? This is general UX polish.

@vhvb1989 If a minor UX fix. Please update and pull it into May RC milestone.
