### ISSUE TITLE
[Issue]  Use customizations/vscode/extensions instead

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1518]
Seeing this today:

![image](https://user-images.githubusercontent.com/2163001/217566470-6462d289-6fb8-40a1-be34-f37904508443.png)

Looks like the devcontainer file may have changed schema for extensions.

We should look at updating.

**Comment by rajeshkamal5050** [comment]
@bwateratmsft is this something which needs fix on VSCode or Azd side?

**Comment by bwateratmsft** [comment]
It looks like #1549 fixed this for most of our devcontainer files but there are a couple left to do. I can fix those.
