### ISSUE TITLE
[Issue] `azd env list` w/o .azure folder throws error

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1520]
Create a folder with an azure.yaml file in it.
Run `azd env list`

Expected: return zero env
Actual: Errors that .azure doesn't exist

```
PS D:\temp\yamltest> touch azure.yaml
PS D:\temp\yamltest> azd env list

ERROR: listing environments: listing entries: open D:\temp\yamltest\.azure: The system cannot find the file specified.
```

**Comment by weikanglim** [comment]
This was fixed in #2013

<img width="633" alt="image" src="https://user-images.githubusercontent.com/2322434/236611378-df651f5d-0447-456f-8f60-b7bc9884c3fc.png">
