### ISSUE TITLE
Graphics for Getting Starting page in VS Code

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1524]
Related to #1404

**Comment by savannahostrowski** [comment]
cc: @gkulin let's use this for any asks you might have around graphics in the walkthrough

**Comment by Austinauth** [comment]
Completed first pass at graphics and revised walkthrough.

- [Updated flow UX - Figma (graphics, language, etc.)](https://www.figma.com/file/SBSJcE3lMi9p8S8MiU71Ns/VSCode-azd-Getting-Started?node-id=3%3A1311872&t=c6zgz6vEx4vYrRwx-1)
- [Graphic `.svg` exports (works w/different VSCode themes)](https://microsoft.sharepoint.com/:f:/t/AzureDeveloperExperience-AzureAcceleratorsTeamInternal/EkLKkpQrkQtIsZp3-YRuxo0BffZvOXMES_XLl2jMM0qlRw?e=3y1dN6)

@gkulin @bwateratmsft Let me know if you need anything else!
