### ISSUE TITLE
[Issue] Add zero state (azd init) support to Visual Studio

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1531]
Today, a user has no way to create a project from an azd template from within Visual Studio. They must create the project outside of the IDE and then open it in VS.

We should support a developer in going end-to-end (project initialization to deploy) from within the IDE for C# projects.

A proposal on how to do this that feels familiar for .NET devs: via support through [`dotnet create new`](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new) and [Visual Studio's "New project dialog"](https://learn.microsoft.com/en-us/visualstudio/ide/create-new-project?view=vs-2022)

From Angelos:
> The most straightforward way to achieve that is by following the instructions in these two documents ([summary docs](https://learn.microsoft.com/en-us/dotnet/core/tools/custom-templates), [detailed docs](https://github.com/sayedihashimi/template-sample)).
The result is a .template.config folder with a template.json file in it. Once you have that, you can [publish these to NuGet](https://learn.microsoft.com/en-us/dotnet/core/tools/custom-templates#pack-a-template-into-a-nuget-package-nupkg-file).
That’s it, that’s all it takes! The published [templates will be available via `dotnet create new`](https://github.com/sayedihashimi/template-sample#finding-and-installing-templates) and VS will [show them in the "New project dialog"](https://devblogs.microsoft.com/dotnet/net-cli-templates-in-visual-studio/)

**Comment by savannahostrowski** [comment]
@rajeshkamal5050 @danieljurek  Is this something we can take a look at in the next couple of iterations? Or spike on it to understand what the process would look like?

**Comment by rajeshkamal5050** [comment]
Previous VS integration is not valid anymore and isn't available in the previews. It will be replaced with the new VS/Aspire integration using azd vs-server.

@abpiskunov @bradygaster @kristenwomack @ellismg
