### ISSUE TITLE
[Issue] azd pipeline started failing on Github actions 

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#1532]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
It's whatever version is in the image:
https://github.com/pamelafox/a-msdocs-flask-postgresql-sample-app-azd/actions/runs/4138504086/workflow

**Output from `az version`** 

Ditto

**Describe the bug**

My builds are all failing on the provision stage:

```
Run azd provision --no-prompt
Error: loading environment: reading environment name: no default response for prompt 'Please enter a new environment name:'
Error: Process completed with exit code 1.
```
https://github.com/pamelafox/msdocs-django-postgresql-sample-app-azd/actions/runs/4138539748/jobs/7155065639
https://github.com/pamelafox/a-msdocs-flask-postgresql-sample-app-azd/actions/runs/4138504086/jobs/7154987464
https://github.com/pamelafox/staticmaps-function/actions/runs/4138102973/jobs/7154096637

I've tried reconfiguring but they're still failing. It looks like AZD_ENV_NAME is a secret locally and in Github, so I'm not sure why it can't get it. I wonder if it's a regression bug with latest release, given the timing?

**To Reproduce**

Trigger the build on those repos.

**Comment by vhvb1989** [comment]
can you try updating `AZD_ENV_NAME` to `AZURE_ENV_NAME` ?

**Comment by pamelafox** [comment]
Sorry, I meant AZURE_ENV_NAME, that's what it is now.

![Screenshot 2023-02-09 at 1 56 54 PM](https://user-images.githubusercontent.com/297042/217948523-a6d05a7a-5717-4946-b6a2-506ffa2792ec.png)

**Comment by vhvb1989** [comment]
@pamelafox , can you try this workaround?
https://github.com/pamelafox/staticmaps-function/pull/3

I created a PR for one of the affected repositories.  
I am basically adding `azd init` before `azd provision`.  

This is only to patch a bug on azd version 0.6.0 where it is failing to pull the env name from the secret value (env var)

**Comment by pamelafox** [comment]
Alas, it failed:

https://github.com/pamelafox/staticmaps-function/actions/runs/4139092147/jobs/7156271508

**Comment by vhvb1989** [comment]
yeah, I missed something there :(
https://github.com/pamelafox/staticmaps-function/pull/4

**Comment by vhvb1989** [comment]
Added a PR for the other 2 affected repositories.

Note: This is just a temporary solution.  azd needs to be fixed.  @weikanglim  @wbreza

**Comment by pamelafox** [comment]
Thanks! I have ~12 azd-ified repositories, but I can wait for the proper azd fix for those.

**Comment by weikanglim** [comment]
This should be fixed with #1534 .

@pamelafox , we released a new patch with these changes last Friday. Can you see if version `0.6.0-beta.2` resolves the issue for you?

**Comment by pamelafox** [comment]
Is that version in the image that's used by the standard workflow, or do I need to add a line in the workflow to download it?

**Comment by pamelafox** [comment]
It worked! https://github.com/pamelafox/msdocs-django-postgresql-sample-app-azd/actions/runs/4138539748/jobs/7210339514
(That's on a repo which we didn't patch)

**Comment by weikanglim** [comment]
@pamelafox Thanks for confirming!
