### ISSUE TITLE
[Issue] Documentation contains invalid hook "preinit"

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-dev#1550]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 0.6.0-beta.2 (commit c4a201e55a13eba77f9037b296a90e0f81b00dbe)

**Output from `az version`** 

n/a - not relevant for my scenario

**Describe the bug**

The documentations and the announcement blog post for `azd` version 0.6.0-beta.1 contain a code snippet that contains the hook definition for a `preinit` event ([link](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/azd-extensibility#root-command-registration)).

This event is not foreseen in the JSON schema of the `azure.yaml` as a vlid entry. 

I assume that this event should not be part of the flow. 

**To Reproduce**

Define a azure.yaml and specify a `preinit` hook. 

VSCode will highlight an issue due to validation.
Executing an `azd init` with the file does not show any effect, it does not seem that the hook gets picked up.

**Expected behavior**

Not sure: either the documentation needs to be adjusted or the event is indeed missing in the `azure.yaml` JSON schema as well as in the `azd` implementation.

**Environment**

n/a

**Additional context**

n/a

**Comment by rajeshkamal5050** [comment]
@gkulin @wbreza can we get the docs fixed?

**Comment by gkulin** [comment]
will work on a pr now

**Comment by savannahostrowski** [comment]
Completed!
