### ISSUE TITLE
[Issue] Improvement of documentation - hooks and interactive:false

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-dev#1551]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 0.6.0-beta.2 (commit c4a201e55a13eba77f9037b296a90e0f81b00dbe)

**Output from `az version`** 

n/a - not relevant for my scenario

**Describe the bug**

The current sample for he hook definition in the documentation show simple `echo` commands to display that the hook gets executed.

However due to the missing `interactive: true` configuration in the sample, the output is not shown. 
 
**To Reproduce**

- Copy one of the samples for hook configuration from the documentation
- Adjust if necessary to your OS (exchange `echo` to `Write-Host` for PowerShell)
- Execute `azd` to pick up the hook

**Expected behavior**

I would either add the `interactive: true` to the corresponding sections of the code samples or at least add a remark in the documentation that this is needed to see the output. Although it is described as parameter giving hooks a first try the user will probably not read that. 

**Environment**

n/a

**Additional context**

n/a

**Comment by rajeshkamal5050** [comment]
@gkulin @wbreza can we get the docs fixed?

**Comment by gkulin** [comment]
will work on a pr now

**Comment by savannahostrowski** [comment]
PR was merged!
