### ISSUE TITLE
[ARM64] bicep binary does not run on Apple Silicon macOS

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#1560]
Repro steps (on an Apple Silicon Mac): 

1. Install [signed azd binary](https://artprodcus3.artifacts.visualstudio.com/A0fb41ef4-5012-48a9-bf39-4ee3de03ee35/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2F6dXJlLXNkay9wcm9qZWN0SWQvNTkwY2ZkMmEtNTgxYy00ZGNiLWExMmUtNjU2OGNlNzg2MTc1L2J1aWxkSWQvMjE4NDg2OC9hcnRpZmFjdE5hbWUvc2lnbmVkLW1hYw2/content?format=file&subPath=%2Fazd-darwin-arm64) (authentication required) 
2. Run `azd init` and `azd provision` on a template 
3. Wait for bicep to download

Expected: Bicep compilation succeeds
Actual: Bicep compilation fails with `status: killed` 

Signing the binary on the system with `codesign -s - ~/.azd/bin/bicep` results in bicep compilation succeeding. 

Also note: before signing, running `~/.azd/bin/bicep` also fails.

**Comment by rajeshkamal5050** [comment]
Depends on [Cannot run bicep-osx-arm64 on macOS 12 #6195]( https://github.com/Azure/bicep/issues/6195)
