### ISSUE TITLE
[Issue] Hashed subscription IDs in telemetry

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1586]
We are currently sending all command events with hashed sub IDs

**Comment by savannahostrowski** [comment]
@weikanglim @rajeshkamal5050 This might be point release worthy IMO, given how widespread the impact is. Thoughts?

**Comment by esweet431** [comment]
@weikanglim or @savannahostrowski, which releases were impacted by this?

**Comment by weikanglim** [comment]
Correct.
