### ISSUE TITLE
[Issue] Strange repetition in azd up command in Codespaces

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#1602]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

@pamelafox ➜ /workspaces/fastapi-azure-function-apim (main) $ azd version
azd version 0.6.0-beta.2 (commit c4a201e55a13eba77f9037b296a90e0f81b00dbe)

**Describe the bug**
When I first run azd up inside Github Codespaces, it asks me or an env name twice, and then gives up and tells me to login:

```
@pamelafox ➜ /workspaces/fastapi-azure-function-apim (main) $ azd up
? Please enter a new environment name: fastapi-azf310

Initializing a new project (azd init)

? Please enter a new environment name: fastapi-azf310

ERROR: running init: loading environment: initializing environment: listing accounts: listing subscriptions: not logged in, run `azd login` to login
```

I think it's weird that it asks for the env name twice. I expect it to immediately give up and tell me to login.

**To Reproduce**

Open https://github.com/pamelafox/fastapi-azure-function-apim in Codespaces and run azd up.

**Comment by weikanglim** [comment]
Thanks for reporting this. We did get a duplicate issue logged with #1566, which is being fixed by #1571. Closing this as a result.
