### ISSUE TITLE
[Issue] VSCode refactoring - Azd re-branding/naming

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#1606]
Depends on 
- https://github.com/Azure/azure-dev/issues/1428

**Comment by bwateratmsft** [comment]
A couple of PM questions for @savannahostrowski--

1. Do we want to be backwards compatible--and support `azd` from newer extension versions--or just make a clean break?
1. We can keep the extension ID as `ms-azuretools.azure-dev` right? Changing extension ID would be a _much_ bigger job, but it's not visible in too many places.

**Comment by rajeshkamal5050** [comment]
Moving to Backlog. We are most likely not going to rename for GA. If needed, we can pull it back.
