### ISSUE TITLE
[Issue] Login flow in Devcontainer fails (improve `login` debugging)

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-dev#1609]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 0.6.0-beta.2 (commit c4a201e55a13eba77f9037b296a90e0f81b00dbe)

**Describe the bug**

Using `azd login` in a devcontainer does not seem to work. The login is executed (browser opens, success message is printed), but every `azd` command fails that needs a logged on user.  

**To Reproduce**

- Open a `azd` project in a devcontainer
- Execute azd login
- Execute any `azd` command that needs a login like `azd provision` 

see this screenshot:

![devcontainer-not-loggedin](https://user-images.githubusercontent.com/22294087/221218890-e7a3d982-d2fc-4405-bd91-689ca1b93aed.png)

**Expected behavior**

- The `azd` commands work after login

**Environment**

Windows 11 Version 22H2
VSCode version 1.75.1 with latest etensions
Docker Desktop 4.16.3 (96739) leveraging WSL 2 backend

**Additional context**

Repository used is: <https://github.com/lechnerc77/app-service-javascript-sap-cloud-sdk-quickstart/tree/predeploy-hook> (predeploy branch)

**Comment by vhvb1989** [comment]
hello @lechnerc77 

I wasn't able to reproduce.
I try using 3 different accounts (WorkAccount, Personal Account, ADD account).
For all cases, `azd` is running as expected.

I need your help to better understand what might be happening on your side.
I used the same repo you shared, so I am running the same devcontainer you do.

Can you tell me a little bit more about the account you are using to `log in` ?
- Is it a personal account ( @live @hotmail etc) ?
- Does it need two-form auth ?
- Can you login to Azure Portal and click on the top right (directories + subscriptions button) 
![image](https://user-images.githubusercontent.com/24213737/221279087-012ff6b3-0fea-4a21-8e5d-1d25a0904490.png)
   - Do you see more than one directory listed?

- When the browser is launched for login, are you selecting a picking a credential from: 
![image](https://user-images.githubusercontent.com/24213737/221279604-4e33ef4b-438e-4cdd-b4a9-885d93383bef.png)
  ??

- If you are picking a credential, what's the message below the email?  Is is `Signed in` ? like: 
![image](https://user-images.githubusercontent.com/24213737/221279840-dbd1a8bc-2265-4ae6-bd33-1e63864415e0.png)

- Have you try using the `Use another account` option (
![image](https://user-images.githubusercontent.com/24213737/221279975-d5c4c9af-46f4-432f-9a42-6f153e60b133.png)
) for the login ?


If you can help answering those questions, I am happy to continue the investigation here. Thank you

**Comment by lechnerc77** [comment]
Hi @vhvb1989 

- It is a personal account (login via @outlook.de)
- 2FA is not needed
- In Azure Portal I see two directories: 
   - "Default Directory"  which is flagged as "Current
   - "Microsoft"
- The login flow is as you depicted: 
   - The browser open with the "Pick an account"
   - My @outlook.de user is marked as "Signed in"
   - I pick the @outlook.de user
   - The browser states: "Authentication complete. You can return to the application. Feel free to close this browser tab."

I just retried it today with the same setup and it worked again ??? I am confused now, as the setup did not change compared to yesterday. 

I will keep an eye on that, but I think you can close the issue, as I cannot reproduce it today.

**Comment by lechnerc77** [comment]
@weikanglim here we go: I get the error now on regular Win11 installation as welll as on WSL2. I attached the logs

Win11 (PowerShell): [login_win11.log](https://github.com/Azure/azure-dev/files/10847375/login_win11.log)

WSL2 (Ubuntu 22.04 LTS): [login_wsl2.log](https://github.com/Azure/azure-dev/files/10847378/login_wsl2.log)

**Comment by weikanglim** [comment]
@lechnerc77 Apologies. Can you run `azd init --debug 2>init.log`, given that the new issue is happening on `azd init`?

**Comment by lechnerc77** [comment]
@weikanglim no change in the setup, and today things worked again on Win11 and WSL2. What I recognized was that after `azd login` there was a short message in the console `fetching subscriptions` that I did not see up to now.

No idea what is going on. Could it be that there are changes on Azure side that impact this functionality?

**Comment by weikanglim** [comment]
@lechnerc77 A few things that could be related:

1. Did you happen to upgrade `azd` at all?
2. Is it possible, that you had `auth.useAzCliAuth` set? Does `azd config get auth.useAzCliAuth` return "true"?
3.  Do you have multiple accounts that you're logging in with `azd`? My colleague had seen a similar issue.

I've created #1654 to address this + increase our logging so that we can better troubleshoot issues like this better.

**Comment by lechnerc77** [comment]
@weikanglim  here the answers to your questions

1. Yes, it worked for some time after the upgrade, the "hickup" began some time afterwards. I re-installed it several times (alway clean install, so removed the MSI before). 
2. Yes that was set and then removed
3. No, just that one account. 

Thanks for improving logging on that topic!

**Comment by pamelafox** [comment]
I filed issue related to #3: https://github.com/Azure/azure-dev/issues/1758
