### ISSUE TITLE
[Issue] Improvement of documentation for hook types

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-dev#1612]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 0.6.0-beta.2 (commit c4a201e55a13eba77f9037b296a90e0f81b00dbe)

**Describe the bug**

Not a bug, but a request for improvement of the documentation. The newly release hooks come in two flavors:

- command hooks
- service lifecycle hooks

In both cases the user of `azd` can specify the script to be executed in line or as a file. It should be highlighted in the documentation that `azd` considers the following paths for the execution:

- for command hooks: the root of project is the starting point of the path
- for service lifecycle hooks the path specified in the `project` attribute of the service is the  the starting point of the path

The commands and/or location of the scripts must be available in accordance to this path. This is logical, but not immediately obvious, so some hint in the documentation would be helpful.

**To Reproduce**

- Create a hook directory in the root of your `azd` project
- Add a script file into the directors
- Create a service lifecycle event hook in the `azure.yaml` that references the hook directory, but specify it like `./hook/yourfilename` in the run section of the hook.  

This will lead to a error message here in case of the predeploy hook:

```bash
ERROR: deploying service: failed invoking event handlers for 'predeploy', 'predeploy' hook failed with exit code: '127', Path: '/tmp/azd-predeploy-1465749944.sh'. : exit status 127
```

**Expected behavior**

Improvement of the documentation for the hook implementation that the location of the script file must be defined *relative* to the path defined in the `project` attribute of the `azure.yaml`

**Environment**

n/a

**Additional context**

n/a

**Comment by gkulin** [comment]
pr: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4415 (currently in review)

**Comment by gkulin** [comment]
Oh sorry @lechnerc77 I just realized that PR is in a private repo so you aren't able to see it. But yes, that is a PR with the improvements! I can post another comment here once they are live. They will be on this page: https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/azd-extensibility later today.

**Comment by gkulin** [comment]
@lechnerc77 the changes are now live🙂

**Comment by lechnerc77** [comment]
@gkulin Looks good, thanks for the update and improvements!
