### ISSUE TITLE
AKS app deployment with Helm

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#1618]
[Helm](https://helm.sh) is a package manager for Kubernetes that simplifies deploying and managing applications. It uses charts (packages of pre-configured Kubernetes resources) to streamline the process of defining, installing, and upgrading even complex applications.

Helm charts are useful for installing common components into k8s clusters and are ideal for iterative development based on its usage of robust templating support.

- Ability to reference helm repositories and deploy releases to AKS clusters
- Ability to reference local helm chart for development & deployment

**Comment by crazy4pi314** [comment]
I am working on building a AZD template for BinderHub that uses a helm chart, so I'll give this a +1 :)

**Comment by savannahostrowski** [comment]
Adding some additional rationale for why we need Helm chart support (as derived from a document that @crazy4pi314 wrote and shared with me). These are core data science scenarios we need to enable.

<html>
<body>
<div class="OutlineElement Ltr SCXW239038815 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="Paragraph SCXW239038815 BCX0" paraid="940623628" paraeid="{1cc59c04-6596-4da0-b94e-b3d6a7f9aaee}{91}" style="margin: 0px 0px 0px 48px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow-wrap: break-word; white-space: pre-wrap; font-weight: normal; font-style: normal; vertical-align: baseline; font-kerning: none; background-color: transparent; color: windowtext; text-align: left; text-indent: 0px;"><span class="EOP SCXW239038815 BCX0" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:160,&quot;335559740&quot;:259}" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 11pt; line-height: 19.425px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;"> </span></p></div><div class="OutlineElement Ltr SCXW239038815 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="TableContainer Ltr SCXW239038815 BCX0" style="margin: 2px 0px 2px -5px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; position: relative; display: flex; justify-content: flex-start;"><div id="{7319a32d-1c8e-4ec2-82b3-b4a9692d460e}{66}" class="WACAltTextDescribedBy SCXW239038815 BCX0" aria-hidden="true" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; position: absolute; visibility: hidden; z-index: -100;"></div>

  | Helm Chart | Setup Instructions | Azure deploy docs?
-- | -- | -- | --
[Jupyter Hub](https://jupyterhub.readthedocs.io/en/stable/)  | [Helm chart repository](https://hub.jupyter.org/helm-chart/)  | [Zero to JupyterHub with Kubernetes ](https://z2jh.jupyter.org/en/stable/)  | Yes, quite long and detailed
[Binder Hub](https://binderhub.readthedocs.io/en/latest/)  | [Helm chart repository](https://hub.jupyter.org/helm-chart/)  | [Zero to BinderHub](https://binderhub.readthedocs.io/en/latest/zero-to-binderhub/index.html)  | Yes, depend on Jupyter Hub
[Dask](https://docs.dask.org/en/stable/)  | [Dask Helm charts](https://helm.dask.org/) | [Dask Cloud Provider documentation](https://cloudprovider.dask.org/en/latest/azure.html)  | Yes
[Rstudio](https://posit.co/products/open-source/rstudio/)  | [RStudio Helm charts ](https://helm.rstudio.com/)  |[Posit Documentation](https://docs.posit.co/installation/?h=helm#install-using-helm-charts)  | None
[Kubeflow](https://www.kubeflow.org/)  | No helm | [Kubeflow on Azure](https://www.kubeflow.org/docs/distributions/azure/)   | Lots of confusing paths/options
[Modin](https://modin.readthedocs.io/en/stable/)  | Not needed | [Installation — Modin ](https://modin.readthedocs.io/en/stable/getting_started/installation.html)  | Easy, it’s an add-on to other tools here, uses Dask or Ray
[Ray](https://docs.ray.io/en/latest/)  | [ray-project/kuberay-helm](https://github.com/ray-project/kuberay-helm)  | [Launching Ray Clusters on Azure ](https://docs.ray.io/en/latest/cluster/vms/user-guides/launching-clusters/azure.html?highlight=azure)  | Technically yes, but very scattered

</div></div><div class="OutlineElement Ltr SCXW239038815 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow: visible; cursor: text; clear: both; position: relative; direction: ltr; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web&quot;, Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="Paragraph SCXW239038815 BCX0" paraid="504216420" paraeid="{68c3f8b6-c769-48d9-a871-d4243b0f3f85}{133}" style="margin: 0px 0px 0px 48px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; overflow-wrap: break-word; white-space: pre-wrap; font-weight: normal; font-style: normal; vertical-align: baseline; font-kerning: none; background-color: transparent; color: windowtext; text-align: left; text-indent: 0px;"><span data-contrast="auto" xml:lang="EN-US" lang="EN-US" class="TextRun SCXW239038815 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-variant-ligatures: none !important; font-size: 11pt; line-height: 19.425px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;"><span class="NormalTextRun SCXW239038815 BCX0" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent;"></span></span><span class="EOP SCXW239038815 BCX0" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:720,&quot;335559739&quot;:160,&quot;335559740&quot;:259}" style="margin: 0px; padding: 0px; user-select: text; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; font-size: 11pt; line-height: 19.425px; font-family: Calibri, Calibri_EmbeddedFont, Calibri_MSFontService, sans-serif;"> </span></p></div>
</body>
</html>
