### ISSUE TITLE
Azd Release on Mar/08 - Manual Testing

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#1627]
Starting 3rd March. Based on pending PR's and builds containing all features required for release.

- Regression tests.
- Testing for new features i.e., AKS Template, GH CLI removal, VS Code workspace view etc.

**Comment by v-xuto** [comment]
@rajeshkamal5050 What do `AKS Template` and `VS Code workspace view` refer to?

**Comment by v-xuto** [comment]
@rajeshkamal5050 Finished the _**Azd Release on Mar/08 - Manual Testing**_, we filed three new issues [#1685](https://github.com/Azure/azure-dev/issues/1685),  [#1686](https://github.com/Azure/azure-dev/issues/1686) and [#1687](https://github.com/Azure/azure-dev/issues/1687). Please review.
