### ISSUE TITLE
`azd up` fails to pass env vars to hook scripts

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-dev#1628]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
`azd version 0.6.0-beta.2 (commit c4a201e55a13eba77f9037b296a90e0f81b00dbe)`

**Describe the bug**
I have a powershell script as a postprovision hook. If I run `azd up` the environment variables are empty.
It seems that the .env file is perhaps not being updated until the command completes, or at least in the `up` case the env vars are not being set before calling the hook script.

**To Reproduce**
1. Export a variable called "TEST" with a value of "test1" from main.bicep
2. Add postprovision script to azure.yaml with "write-host "TEST: $env:TEST"
3. run `azd up`
4. notice that "test1" does not appear after "TEST: " in the output
5. run `azd provision`
6. notice that "test1" now appears after "TEST: " in the output

Tested with predeploy too and that failed as well.

**Expected behavior**
When `azd up` is run, I expect the env vars from the bicep files to be available to postprovision, predeploy, postdeploy scripts.

**Environment**
Information on your environment:
    * PowerShell 7.3.1
    * VS Code 1.75.1

**Additional context**

**Comment by wbreza** [comment]
@charris-msft Thanks for reporting.  It looks like the new env vars added from the provision step are not refreshed in the in-memory representation of the environment before passing into the hooks to other downstream hooks.

**Comment by rajeshkamal5050** [comment]
@wbreza  do you want to fix it for the upcoming March release?

**Comment by charris-msft** [comment]
pretty please with sugar on top!

We won't be able to update a very complex public tutorial to use azd until this is fixed.

**Comment by charris-msft** [comment]
FYI - this also blocking a scenario where I need to run a preprovision script to get a value, set an env var, and consume that env var in the main.parameters.bicep file.

**Comment by charris-msft** [comment]
That's great news!!

Another interesting find - not sure if the PR will resolve it.
I have a preprovision script that sets my local IP as an env var:
`azd env set MY_PUBLIC_IP $my_public_ip`

At this point I can see MY_PUBLIC_IP and the correct value in the .env file

Because of this problem in this issue, I'm getting prompted for the IP address when azd starts to provision resources (expected). However, after I provide the IP address manually, azd asks me if I want to keep it. If I say yes (with `y` or `Y`) MY_PUBLIC_IP is removed from the .env file.

This seems a bit weird, so may want to check the PR behavior.
