### ISSUE TITLE
[Issue] Port mismatch between API and Website when launching through VS Code

### ISSUE THREAD

**Issue by Petermarcu** [Azure/azure-dev#1634]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 0.6.0-beta.2

**Describe the bug**
By default, the website doesn't connect to the web api when both are launched from VS Code using the default settings from the template.

**To Reproduce**
initialize the todo-csharp-cosmos-sql@0.0.1-beta template. 
Load the folder in VS Code.
In VS Code, go to the debug command area and select debug api.
In VS Code, go to the debug command area and select web.

Notice the API is launched on port 3100 in my case. The VS Code configuration for the website has localhost:3000 set. Can we set the port that will be used for the web api or detect what port ASP.NET used?

**Expected behavior**

**Environment**
Information on your environment:
VS Code using this template: todo-csharp-cosmos-sql@0.0.1-beta

**Additional context**

**Comment by vhvb1989** [comment]
You can set the `API url` for the `Web` using `REACT_APP_API_BASE_URL` env var.
See: https://github.com/Azure-Samples/todo-csharp-cosmos-sql/tree/main/src/web#setup

This allows the `web` to connect to any `rest api` (either running locally, or running in Azure services).

The local `api api` project uses `3100` .  The `port` is defined by each project-type:
  C# -> dotnet
  python -> flask
  nodejs -> Express 
  java -> boot spring config
 
What we do for the templates local debug experience, is to provide `tasks` you can call to start the applications and have then connected.  In Vscode, run `Crtl+Alt+P` -> type `run task` -> select Start Web and Api.  or Debug

**Comment by rajeshkamal5050** [comment]
@weikanglim Need to investigate for any changes or just doc updates?

**Comment by weikanglim** [comment]
The ToDo templates always specifies:
- API to listen on port `3100`
- Web to listen on port `3000`

The `web` uses `REACT_APP_API_BASE_URL` to identify the API endpoint. By default, this is set to `localhost:3100` in the VSCode tasks [here](https://github.com/Azure-Samples/todo-csharp-cosmos-sql/blob/50465e297f317a5f7c1032ff8b69d36663fca268/.vscode/tasks.json#L74), but is also overridden when `azd` env file is updated through `provision`, to set to the remote Azure URL instead.

@Petermarcu Just to clarify, did the browser simply errored when you did `Debug Web`? I suspect that's because the way the ToDo projects are set up, `Debug Web` doesn't actually start the web server. The user has to first do `Tasks: Run Task -> Start Web` as a separate step to start the web server. Then, `Debug Web` to launch a browser with JS source debugging enabled. It's a pain point captured in #917

**Comment by weikanglim** [comment]
@Petermarcu I understand how that can be really confusing.. Debug web is supposed to connect to the front-end application (which listens on `3000`, and not the API which listens on `3100`)  that has the following UI:
![image](https://user-images.githubusercontent.com/2322434/222516286-61f7bbd4-1683-4920-ad05-9414cbac0794.png)

The front-end web server isn't launched by "Debug web" however. It is launched by the `Tasks: Run Task -> Start Web`

**Comment by Petermarcu** [comment]
Got it, Yes, that did the right thing.

**Comment by Petermarcu** [comment]
Is there any follow up we want to do WRT to this or should we just close it?

**Comment by vhvb1989** [comment]
I would just close this @Petermarcu 
There should be clear docs/instructions within the template Readme.doc about how to run the application locally and how to start debugging. So, we could also use this issue to follow up about linking the root Readme to each src/app -> readme.

For example, there are docs about the web app within the src/web folder: https://github.com/Azure-Samples/todo-csharp-cosmos-sql/tree/main/src/web#getting-started-with-create-react-app-and-fluent-ui, but it looks like the root Readme from the template has not link about it.
Most likely, the link should be part of the Application Code description here: https://github.com/Azure-Samples/todo-csharp-cosmos-sql#application-code.  

@savannahostrowski @puicchan , do you want to use this issue to create relations between root-readme and each service-app readme?  Is that something that you might be already tracking/doing somewhere?

**Comment by rajeshkamal5050** [comment]
@vhvb1989 @gkulin can we close this?
