### ISSUE TITLE
[Issue] Error when Terraform not installed

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1648]
Try running the tf template w/o terraform installed

![image](https://user-images.githubusercontent.com/2163001/222585929-6060d142-bb22-48b9-bc2e-049114f09b2d.png)

**Comment by jongio** [comment]
I'm actually seeing this even though I have terraform installed

**Comment by vhvb1989** [comment]
what do you get if you run `terraform version -json` on your system?

**Comment by jongio** [comment]
![image](https://user-images.githubusercontent.com/2163001/222587519-8b40f9e3-0294-405e-862f-6c7ae5829877.png)

**Comment by jongio** [comment]
Seems the version I have is "pre --json" flag support

**Comment by vhvb1989** [comment]
correct.

you need to update

And we need to make a patch for azd to catch this and tell folks to update

**Comment by jongio** [comment]
Cool. thanks

**Comment by rajeshkamal5050** [comment]
> And we need to make a patch for azd to catch this and tell folks to update

Tried with latest 0.8 bits. Error message seems fine. Might have been handled/fixed.
```
ERROR: creating provisioning manager: required external tools are missing:
 - need at least version 1.1.7 or later of Terraform CLI installed. Download newer version from https://www.terraform.io/downloads Terraform CLI version
```
