### ISSUE TITLE
Template deployment issue

### ISSUE THREAD

**Issue by JohnCarmichael3000** [Azure/azure-dev#165]
**Output from `azd version`**
azd version 0.1.0-beta.2 (commit 13ec2b11aa755b11640fa16b8664cb8741d5d300)

**Output from `az version`** 
"azure-cli": "2.38.0"

**Describe the bug**
Attempting to deploy [https://github.com/Azure-Samples/todo-csharp-cosmos-sql](url) but get the following output/error:

Creating Azure resources (17 of ~17 completed)

Deploying service api

Error: deploying service: deploying service api package: deploying service api: failed running az deployment source config-zip: exit code: 3, stdout: , stderr: WARNING: Getting scm site credentials for zip deployment
ERROR: (ResourceNotFound) The Resource 'Microsoft.Web/sites/jcTest1api' under resource group 'jcTest1-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Code: ResourceNotFound
Message: The Resource 'Microsoft.Web/sites/jcTest1api' under resource group 'jcTest1-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
: exit status 3

**To Reproduce**
azd up --template todo-csharp-cosmos-sql

**Expected behavior**
When azd up is complete it will output the following URLs:
Azure Portal link to view resources
ToDo Web application frontend
ToDo API application

**Environment**
VS Code 16.9.2

**Additional context**
It appears I meet the install requirements stated in the application. Using Azure subscription where I am owner so permissions shouldn't be an issue.
Azure Developer CLI : azd version 0.1.0-beta.2 (commit 13ec2b11aa755b11640fa16b8664cb8741d5d300)
Azure CLI (2.38.0+):  2.38.0
.NET SDK 6.0: 6.0.302
Node.js with npm: node v18.6.0, npm@8.15.0
Git (2.36.1+): git version 2.37.1.windows.1

**Comment by puicchan** [comment]
Thank you very much for reporting this issue. This may be because you used mixed cases in your environment. A bug reported in #115. We will be releasing a fix for this. The workaround for the time being is to use all lowercase for environment name.

**Comment by JohnCarmichael3000** [comment]
That does look to be the issue. I retried the deployment with the same settings except lower case for the environment name and it deployed correctly (technically there was a number character in the name as well). Thank you for the clarification on this issue.

**Comment by puicchan** [comment]
Glad it works. The number should be ok. Just no uppercase.

**Comment by puicchan** [comment]
Closing this since issue resolved. Please reopen if any other issue.
