### ISSUE TITLE
Handle login errors better

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1653]
1. Detect when refresh token is expired, provide a better error message.
2. Always provide human-readable unhandled authentication failures. We need this to be able to quickly debug and solve authentication issues without having roundtrips for obtaining logs when users log issues.
3. Improve access token retrieval log failures (use `azsdk` format)
4. Never present user with `not logged in, run azd login` error message when user is running `azd login`. Instead, ask the user to rerun with `--debug` and log an issue if that fails.

**Comment by rajeshkamal5050** [comment]
Moving this to Gallium. Not a GA blocker.

@savannahostrowski @ellismg

**Comment by weikanglim** [comment]
This has all been completed:

1. User is presented with "login expired"
2. We both format the error message from AAD, and also reformat for specific conditions
3. We always log errors to debug log
4. Should no longer happen based on recent changes.
