### ISSUE TITLE
[Issue] azd init fails after declining to overwrite files from template repo

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1656]
**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 0.6.0-beta.2 (commit c4a201e55a13eba77f9037b296a90e0f81b00dbe)

**Describe the bug**
When I decline to let azd overwrite the `.gitignore`, `LICENSE`, and `README.md` in my current project, it failed to initialize.

![image](https://user-images.githubusercontent.com/8949415/222821986-399ba403-df99-477e-9be2-cc9190a308fd.png)

**To Reproduce**
1. Open an existing project (non-azd compatible)
2. Run `azd init` on the codebase
3. Choose a template from the list
4. Decline letting azd overwrite your files

**Expected behavior**
This should succeed.  I'd expect that the template files are added to my project and the `.gitignore`, `LICENSE` and `README.md` are untouched by azd.

In this case, none of these files are even core to executing the template. They're metadata and configuration.

**Comment by weikanglim** [comment]
The intention was probably to avoid the user from cloning into an existing repository by accident.

It seems that a simple change could be to update the prompt:

- What would you like to do with these files?
o) Overwrite with versions from template
k) Keep current files
c) Cancel

**Comment by savannahostrowski** [comment]
Yeah - that makes sense. I think this would avoid us having a blocking UX. The copy might need some finessing.

cc: @Austinauth for visibility and in case he has anything to add
cc: @ellismg as FYI

**Comment by Austinauth** [comment]
@savannahostrowski @vhvb1989 

Currently investigating more accessible list select patterns, in the interim we can keep the current pattern (selecting with a `>`), unless we feel strongly about using the letters ( o), k), c) ).

![image](https://user-images.githubusercontent.com/6994218/223503363-30dc90d2-bf82-4c37-823c-db79f29e0c5d.png)

**Comment by savannahostrowski** [comment]
I think that looks great tbh. I agree with keeping our styles consistent as you've outline. Super clear.

**Comment by savannahostrowski** [comment]
@weikanglim @rajeshkamal5050 It'd be great if we could prioritize a fix for this. Right now, it sort of hinders me from doing azdev-ifying in demos.

**Comment by weikanglim** [comment]
@Austinauth @savannahostrowski Is `Abort init` maybe slightly better than `Cancel init`? I'm trying to convey the idea that nothing will happen, so that the user isn't left wondering if they're in an intermediate state where `azd` performed something, but not quite all of it.

**Comment by weikanglim** [comment]
Perhaps it's clear from the logging what `azd` did, since any modifications would be logged, and the absence of that suggests the same idea. I'm going to move forward with Cancel, but just curious if you have a quick feeling one way or another.

**Comment by Austinauth** [comment]
I don't have a strong feeling on the wording one way or another, I personally I feel both `abort` and `cancel` convey the same thing.

Super quick sketch, wording probably needs adjustment.In the future we might be able to do something like this to be more clear. We do not currently have a pattern like this implemented. 

![image](https://user-images.githubusercontent.com/6994218/226423918-5f66e453-3006-4308-8848-c4ee60269cf9.png)

**Comment by savannahostrowski** [comment]
Is there any reason that we can't use the same style we use for region or subscription selection here?

**Comment by Austinauth** [comment]
> Is there any reason that we can't use the same style we use for region or subscription selection here?

That's what's proposed above here: https://github.com/Azure/azure-dev/issues/1656#issuecomment-1458633571

Sketch is just to illustrate how we could add additional context if required.

**Comment by weikanglim** [comment]
@Austinauth @savannahostrowski I realized I had made a faulty suggestion by putting "Cancel init" as an option.

The typical way the user would "cancel" out of a CLI is to use "Ctrl + C" on their keyboard. This does work here. I'm worried if we introduce Cancellation as an option, we might be stuck in trying to implement this UI pattern everywhere, so I would maybe suggest to not introduce that options unless we need to?

**Comment by savannahostrowski** [comment]
Yeah - that's true that people can do ctrl/cmd+c to cancel out and a fair concern about how this scales. I agree - we shouldn't introduce a cancel option unless we have supporting data to back doing so. I'd expect that most know that ctrl+c would get them out of the command execution.

**Comment by weikanglim** [comment]
I have a change out to switch the confirmation to a selection.

@Austinauth @savannahostrowski I think we might also need to reword the yellow warning message below, which states "The following files will be overwritten with the versions from the template":

![image](https://user-images.githubusercontent.com/2322434/226489151-d1f8886e-5f90-4a4a-b659-cb27ff48141b.png)

I can't find the words to best express this. My really poor attempt looks like:

> The following files are present both locally and in the template:

**Comment by Austinauth** [comment]
I think both suggestions are fine, I added a few more options.

1. The following files are present both locally and in the template:
2. The template contains files with the same name as files in your application:
3. The template you've selected contains files with the same name as files in your application: 
4. Both the template and your local directory contain the following files:

All are serviceable IMO.

We should probably tweak the prompt choices as well, perhaps:

- Overwrite with versions from the template
- Keep my existing files unchanged
