### ISSUE TITLE
[Issue] Deployment of Azure Container Apps with Terraform as Infrastructure Provider fails

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-dev#1662]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 0.6.0-beta.2 (commit c4a201e55a13eba77f9037b296a90e0f81b00dbe)

**Describe the bug**

Scenario is to `azd up` an Azure Container app using *Terraform* as IaC Provider. The provisioning of the infrastructure via `azd provision` works as expected and all components are set up successfully.

The deployment of the Azure Container App via `azd deploy` fails after the push of the image to the Azure container registry with the error message:

```bash
ERROR: deploying service: deploying service sender package: planning provisioning: planning infrastructure provisioning: creating template: failed to compile bicep template: failed running bicep build: exit code: 1, stdout: , stderr: An error occurred reading file. Could not find file 'C:\Users\drchr\sandbox\tf-aca\infra\sender.bicep'.
 (exit status 1)
```
It seems that the deployment command does not consider the configuration of the infrastructure provider defined in the `azure.yaml`

**To Reproduce**

- Clone the repo <https://github.com/lechnerc77/tf-aca/> 
- Switch to the branch `tf-apps-reduced`
- Create a blob storage for state management as described in the `README.md`
- Execute `azd provision`
- Execute `azd deploy --debug`

**Expected behavior**

The deployment of the Azure Container App when using Terraform as IaC provider should deploy the app. 

**Environment**
Information on your environment:
    * Terraform v1.3.7
    * Docker Desktop 4.16.3 (96739)

**Additional context**

- Log output of `azd deploy --debug`: [error-log-deploy-aca.txt](https://github.com/Azure/azure-dev/files/10889147/error-log-deploy-aca.txt)
- Alternative repo to reproduce (more extensive setup): <https://github.com/KaiWalter/tf-aca/tree/tf-apps> by @KaiWalter
- See discussion <https://github.com/Azure/azure-dev/discussions/1595>

**Comment by wbreza** [comment]
@lechnerc77 - We're in the process of updating our Container Apps deployment implementation to use the Azure SDKs instead of spawning a new partial provisioning.

Please try out the PR build of `azd` from this PR @ https://github.com/Azure/azure-dev/pull/1989

I've also gone ahead and forked the referenced repo to use as a Terraform use case.  The only modifications were to remove the bicep modules you had in there and include the ACA apps as part of the main terraform deployment.

**Comment by lechnerc77** [comment]
That's great news. I will try it out  in the next couple of days

**Comment by lechnerc77** [comment]
Unfortunately I cannot retest it as there seems to be an issue with container apps and pay-as-you.go subscriptions: 

<https://github.com/microsoft/azure-container-apps/issues/729>

Seems to be happening since the last days few days

**Comment by KaiWalter** [comment]
@wbreza I need some guidance; with the adapted version https://github.com/KaiWalter/tf-aca/tree/tf-apps and your **azd** PR version I managed to get **infra create**.
Question: how would I need to shape Terraform files so that **sender** and **receiver** are built with **up**?

**Comment by wbreza** [comment]
@KaiWalter - take a look at my fork @ https://github.com/KaiWalter/tf-aca/blob/tf-apps/infra/main.tf#L77

Here I just make sure that the `sender` & `receiver` modules are also included in `main.tf`. This will ensure that all your infra is created in any `azd provision` or `azd up` call. 

Does this answer your question? Let me know if you meant something different.
