### ISSUE TITLE
The "--output" option isn't supported when building a solution

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/azure-dev#1679]
**Output from `azd version`**
Run `azd version` and copy and paste the output here:
```
azd version 0.6.0-beta.2 (commit c4a201e55a13eba77f9037b296a90e0f81b00dbe)
```

**Describe the bug**
The template `todo-csharp-cosmos-sql` could not be deployed. It fails with error from MSBUILD

```
ERROR: deploying service: packaging service api: dotnet publish on project 'D:\my-folder\src\api' failed: exit code: 1, stdout: MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET
```

**To Reproduce**
1. azd init - choose `Azure-Samples/todo-csharp-cosmos-sql`
2. azd up

**Expected behavior**
1. code is deployed

**Environment**
Information on your environment:
    * PowerShell: 7.3.3

**Comment by KSchlobohm** [comment]
Known workarounds

1. delete or move the solution file from the folder where the csharp service is stored

e.g. in the repro above, i deleted the solution file for Todo.Api.sln

**Comment by rajeshkamal5050** [comment]
Closing this in favor of #1421
