### ISSUE TITLE
[Issue] user study error message guide on deploying service

### ISSUE THREAD

**Issue by hemarina** [Azure/azure-dev#168]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd up`**
Run `azd up` and copy and paste the output here:
C:\Users\participant\FirstAZD>azd up --template todo-nodejs-mongo
Initializing a new project in C:\Users\participant\FirstAZD

? Please enter a new environment name: test

? Please enter a new environment name: test
? Please select an Azure location to use: 40. (US) East US (eastus)
? Please select an Azure Subscription to use:  1. Azure Pass - Sponsorship (xxx)
Provisioning Azure resources can take some time.

You can view detailed progress in the Azure Portal:
https://portal.azure.com/#blade/HubsExtension/DeploymentDetailsBlade/overview/id/%2Fsubscriptions%2Fxxx%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Ftest

Created Azure resources

Deploying service api

Deployed service api
 - Endpoint: [https://app-api-h4p7ot2dd42ri.azurewebsites.net/]

Deploying service web
Error: deploying service: deploying service web package: deploying service web: failed running az deployment source config-zip: exit code: 1, stdout: , stderr: WARNING: Getting scm site credentials for zip deployment
WARNING: Starting zip deployment. This operation can take a while to complete ...
WARNING: Deployment endpoint responded with status code 504
ERROR: An error occured during deployment. Status Code: 504, Details: 504.0 GatewayTimeout: exit status 1

**Describe the bug**
This bug happens during user study. The deployment of api is not working. It works after 30 minutes. 

**To Reproduce**
Run `azd up --template todo-nodejs-mongo` with East US (eastus) location and Azure Pass - Sponsorship Azure Subscription.

**Expected behavior**
Could we map certain error code (with actual root cause) to specific action to resolve the issue? 

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

**Comment by puicchan** [comment]
We suspect this is a transient issue since the app is deployed once the customer reran `azd up`. Ideal solution: let customer know to rerun `azd deploy`. They can rerun `azd up` but that's a longer (unnecessary) wait since provision was fine.

**Comment by rajeshkamal5050** [comment]
@puicchan see if we need to document this. Else, we can close it out.

**Comment by puicchan** [comment]
@rajeshkamal5050, I am not convinced we should solve this by documenting this. A better experience would be to improve the error message and suggest the next step developer can potentially take (i.e., rerun `azd deploy`.)

@Austinauth - can we add to #243

**Comment by Austinauth** [comment]
@puicchan sure, I'll link to this issue from #243!
