### ISSUE TITLE
Break out 'up' telemetry to fire init, provision, and deploy

### ISSUE THREAD

**Issue by esweet431** [Azure/azure-dev#1680]
CC: @savannahostrowski 

**Describe the bug**
Currently, there is one telemetry event that corresponds to an azd `up` invocation. 

**Expected behavior**
It would be better to fire one telemetry event for each underlying command (`init`, `provision`, and `deploy`). We can add a new property to indicate whether the init/provision/deploy command was invoked independently or was called by `up`.

**Additional context**
This will make it easier to understand where customers who invoke `up` are getting stuck.

**Comment by savannahostrowski** [comment]
@weikanglim @ellismg Let's make sure that we factor this into any telemetry update plans required as part of the command exploration.
