### ISSUE TITLE
[Issue] Hooks should state that powershell 7 is required

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1681]
I believe `pwsh` is a PowerShell 7 feature/alias.  On a new machine I didn't have Powershell 7 installed and got a generic pwsh not found error.  Detection would be great.

**Comment by rajeshkamal5050** [comment]
We can document this as a fit-n-finish item. If possible, we can also adjust code for detecting and erring.

This could also be related to the external template dependencies which someone would want to express and get handled cc @Austinauth

**Comment by rajeshkamal5050** [comment]
Can we get the docs enhanced with PowerShell 7 requirement for pwsh scripts?

https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/azd-extensibility
