### ISSUE TITLE
Workspace Resource Explorer Test exception

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#1687]
**Describe the issue:**
On the Azure tab in VSCode, in the second tree view (“Workspace Resources”), no application is shown.

![image](https://user-images.githubusercontent.com/80496810/223634798-3366d319-a3ef-4560-ac59-418d454a154e.png)

**Repro steps:**
1. Run command `azd login`.
2. Install the [Azure Resources extension](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azureresourcegroups)
3. Open a new, empty workspace folder.
4. Use the command `azd init` to choose a template and create a project

**Environment:**
OS: Windows desktop, Codespaces, MacOS desktop, Linux desktop, Devcontainer in VS Code, WSL.
Template: All templates
Azd version: 0.6.0-beta.3-daily.2613549  (commit https://github.com/Azure/azure-dev/commit/2d2f744fe6aba8a26569c6284f73ca3f9434e3b7)

**Expected behavior:**
On the Azure tab in VSCode, in the second tree view (“Workspace Resources”), the application should be shown.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@bwateratmsft is this a dup of #1688?

**Comment by bwateratmsft** [comment]
@rajeshkamal5050 I believe so, yes.
