### ISSUE TITLE
[Issue] azd cannot access ~/.azd/config.json after macOS upgrade

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#1691]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

**Describe the bug**
Breaking this issue out of [another conversation](https://github.com/Azure/azure-dev/issues/1673#issuecomment-1459988539).

**To Reproduce**

1. Install older version of `azd` 
2. Run some `azd` commands which results in a `~/.azd/config.json` file being created
3. Upgrade MacOS from ____ to Ventura 13.2.1
4. Use the uninstall script to uninstall `azd` then run the install script to install `azd@latest` 
5. Run `azd up` in an appropriate situation 

Actual: access denied error to `~/.azd/config.json`

![image](https://user-images.githubusercontent.com/2158838/223841099-4b33a5c4-aed1-4e9c-81eb-b1ec4f85d864.png)

**Expected behavior**

`azd up` works

**Environment**
Information on your environment:
    * Apple M1

**Additional context**

**Comment by rajeshkamal5050** [comment]
@danieljurek able to reproduce? Even if we do, not sure if we can fix anything since this is caused by MacOS upgrade changing some perms. May be we could document on the impact and what needs to be done manually?
