### ISSUE TITLE
`provision` is slow because of `dotnet secrets`

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1695]
I observed that `dotnet user secrets` slowed down the command by 1.5s per invocation. We invoke this per setting, and this adds up to over 10 seconds with less than 10 variables which is unacceptable.

**Comment by jongio** [comment]
For the record... we set .net user secrets so that the user can access the outputs of a provision in their application... if there are performance issues then we should talk to the.net team to see if they have a bulk API or can improve the perf of the existing API's

**Comment by rajeshkamal5050** [comment]
Seems to be an observation. Needs investigation on the alternatives, if any. Moving this to backlog. Not a must-fix for GA.

@savannahostrowski @ellismg
