### ISSUE TITLE
Support pyproject.toml

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1698]
Today, we mainly support requirements.txt. We should also support the increasingly popular pyproject.toml/Poetry for Python projects.

https://python-poetry.org/docs/pyproject/

**Comment by jongio** [comment]
The new OpenAI Plugins sample uses Poetry: https://github.com/openai/chatgpt-retrieval-plugin

**Comment by savannahostrowski** [comment]
@rajeshkamal5050 @ellismg We may need to consider promoting this item from a 1 to a 0 for Gallium to make sure that we can support this AI scenarios
