### ISSUE TITLE
March Docs Plan

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1709]
Joint ownership on this one since @gkulin will be out the last half of the month.

- @gkulin
	- Brainstorm/spec updates to https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/overview
	- Brainstorm/spec updates to "Get started" tab

- @savannahostrowski 
	- Will handle tactical April release-centric doc updates (if needed)

**Comment by rajeshkamal5050** [comment]
FYI @savannahostrowski for docs and blogposts.
Readme updates by @danieljurek for the deb and rpm package installations - https://github.com/Azure/azure-dev/pull/1862
