### ISSUE TITLE
[Bug] [AzureDeveloperCliCredential - azd] Wrong token is returned when multi-tenant.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#1712]
When the `AzureDeveloperCliCredential` invokes `azd` to generate a token, the `tenant-id` and the TenantId is not set.  Azd is returning a token for the home-tenant of the logged in user. 

A use case of this:
  An application using `DefaultAzureCredential()` is not aware of what is the TenantId to be used when invoking `azd`. And `azd` is not aware of what is the default tenant which should be used when `--tenantId` is not set.

The `Azure cli` handles this by using the `az account set`, which sets a default `subscription/tenantId` to be used when the parameter is not set.  But `azd` has no way to set this `default subscripion/tenantId`.  

azd has a concept of `default sub and location` but it is used only for selecting options from a list prompt.  

Azd could use this default sub/location as well for when `azd auth token` is run.  Or another strategy should be designed.

**Comment by ellismg** [comment]
I wonder if we should follow a strategy like this (when tenant-id is not set):

1. Attempt to load the current environment, and if we can, look for `AZURE_SUBSCRIPTION_ID` in it (right now it will always be there, but with my work that invariant will be broken).  If we find it, figure out what tenant that subscription is in and use that when requesting a token.

2. If there is no environment, or the environment does not have a `AZURE_SUBSCRIPTION_ID` property, check if the AccountManager has a default subscription set.  If so, find it's tenant and use that when requesting a token.

3. If there is no default set, the just don't include a specific tenant, and allow the default behavior of requestion a token from the user's home tenant.

I think we'll need something like (1) such that if you use `AzureDeveloperCliCredential` from within an AZD project we use the tenant for your current environment, which may be different from your default tenant.

**Comment by vhvb1989** [comment]
I think it is a good strategy @ellismg .

I would update (2) to first check if `AZURE_SUBSCRIPTION_ID` is set as a system env.  This would allow customers to dynamically change it without changing the defaults on `azd account manager`.
I would never use the defaults from the Account Manager, as those are just for auto-selecting from a list of choices from azd. But they are super fragile and get useless very eaasily. For example, running `azd login` to a tenant where the default sub does not exists.

**Comment by weikanglim** [comment]
@ellismg Does @vhvb1989 proposed makes sense in your mind?

I do feel better with what Victor suggests, to punt it for now. Walking up the chain and having multiple ways of sourcing seems a little scary. The fact that you can have N-subscriptions, and we decided to pick the "default subscription tenant" instead of the "default home tenant" seems maybe more arbitrary.

Users can set `AZURE_SUBSCRIPTION_ID` env var outside of `azd` projects if they do not want to explicitly set `tenantId`.
