### ISSUE TITLE
env variables created in preprovision script are not passed to provision

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-dev#1714]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 0.7.0-beta.1 (commit 9ce71659f7688d0dc3dda8b84e5accedca58cf01)

**Describe the bug**
I am setting an env var in a preprovision script called `MY_PUBLIC_IP`
I am reading that env var in main.parameters.json 
```
    "myPublicIp": {
      "value": "${MY_PUBLIC_IP}"
    },
```

and passing it to main.bicep
```
@description('My public IP address')
param myPublicIp string
```

Then on to a bicep module during provisioning in the `allowedSingleIPs` param:
```
module postgresServer 'core/database/postgresql/flexibleserver.bicep' = {
  name: postgresServerName
  scope: resourceGroup
  params: {
    name: '${prefix}-postgresql'
    location: location
    tags: tags
    sku: {
      name: 'Standard_B1ms'
      tier: 'Burstable'
    }
    storage: {
      storageSizeGB: 32
    }
    version: '14'
    administratorLogin: postgresUser
    administratorLoginPassword: databasePassword
    activeDirectoryAuth: 'Enabled'
    databaseNames: [ postgresDatabaseName ]
    allowAzureIPsFirewall: true
    allowedSingleIPs: [ myPublicIp ]
    aadAdmin: aadAdmin
  }
}

```

However, when I look at the Inputs in the Deployment Center in the Portal, the value is blank:
<img width="364" alt="image" src="https://user-images.githubusercontent.com/74415662/224455795-119c1664-81dc-46db-98ea-b12efa60b395.png">

Other values I am passing from env vars that are created when the azd env is created, are able to be passed through, but new ones I create in a preprovision script are not.

**To Reproduce**
See instructions above

**Expected behavior**
If I create an env var in a pre provision script, I expect to be able to reference it in the main.parameters.json and use it in my provision step.

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Comment by wbreza** [comment]
@charris-msft How are you setting the new env var in your preprovision script?

**Comment by charris-msft** [comment]
I'm setting the env var in the preprovision script like this:
```
$my_public_ip = (Invoke-WebRequest -uri http://ifconfig.me/ip).Content
azd env set MY_PUBLIC_IP $my_public_ip
```

If it helps, when monitoring the .env file, right after the preprovision script runs I can see the new env var in the .env file:
![image](https://user-images.githubusercontent.com/74415662/225128518-2a17c403-df4c-43d9-9726-b9bcf6b355fa.png)

**Comment by pamelafox** [comment]
I believe I would also need this functionality to work in order to azd-ify https://github.com/Azure-Samples/ms-identity-python-webapp/ 
It doesn't seem possible to configure App Registration entirely in Bicep, so I would need a preprovision script to first run the powershell/az, and then pass CLIENT_ID/CLIENT_SECRET to the appSettings of the app service.
