### ISSUE TITLE
`azd env refresh` loses state

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1720]
`azd env refresh` does not pull bicep outputs from container app deployments, which are done outside of `main.bicep`.

**Comment by ellismg** [comment]
I'm not really certain what we should do here.  My current thinking is that we could tag deployments created by `azd`, and then when doing `env refresh`, starting from the subscription level deployment walk all the resource groups and look at all the deployments in each resource group, find the ones created by `azd` and then merge their outputs in with the set from the subscription level deployment.

**Comment by weikanglim** [comment]
Sharing some observations if it helps:

I can see a world where we would start allowing `provision` to be performed in phases, and each `provision` of an infra module is a separate deployment.

In that world:

1. Running `azd provision` will recover the state. And this is also true currently for `azd`.
2. We could make `provision` smarter by simply downloading state instead of triggering the ARM deployment, or a `pull` command that pulls down Azure state from deployments.

Which may suggest that we simply need to ensure that we have a unique reference or strategy to map each infra module to an Azure deployment.

Now, dealing with the current problem where we do have stuff that creates `infra` outside of `provison`. I think long-term should we get avoid this. I think of container app deploys as a code swap + deployment policies that could signal how the swap could occur. All this can live outside of `infra` since we're not actually creating new Azure resources (even though in `ACA` world it is represented as such).

The short-short term is maybe that we recommend users to run `azd up` to recover state. I personally, don't think it's such a bad thing, and it ensures that the `infra` and `code` is in-sync with the local state. The no-opt that Azure performs should also maybe it a lot faster than 7 minutes. I suspect this may take 1-2 minutes.

**Comment by wbreza** [comment]
I've mentioned this before, but I also agree that `provision` is the only time we should be performing any bicep deployments.  Having ACA perform a bicep deploy at `deploy` stage go against any other service target that we support.  Yes, there would be an empty ACA app sitting there without any code but this matches the strategy for app service and all other service targets.

Also, the split between root and service level `provision` calls would also give us an opportunity have a separation of concerns between the root app and the individual services.  In this scenario we would also need to keep track of all the ARM deployments triggered for AZD.

As @ellismg mentioned the short term stop-gap solution would be find all ARM deployments provisioned by AZD and group the outputs to recover env state.

**Comment by rajeshkamal5050** [comment]
Some of the items discussed above seems to be long term items. Currently we don't support phased and/or different levels of provisioning.

Not a must-fix item for GA. Moving it to backlog.

@savannahostrowski @ellismg

**Comment by weikanglim** [comment]
@rajeshkamal5050 To be precise, this is an existing bug with product functionality. Container apps does currently perform bicep deployment, does set important state information, and is not recovered with `azd env refresh`.

**Comment by savannahostrowski** [comment]
I think we want to explore stabilization ahead of Build. Can we make sure we plan for that in the current iteration?

**Comment by rajeshkamal5050** [comment]
> I think we want to explore stabilization ahead of Build. Can we make sure we plan for that in the current iteration?

@v-xuto can we test https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/reference#azd-env-refresh command with some of our templates. Please file issues separately for the same.
