### ISSUE TITLE
User is forced to `azd login` again after `azd config reset`

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1721]
As the title says. if the user runs `azd config reset`, the user is logged out.

1. `azd login` once
1. `azd config reset`
2. `azd init` 

Expected:
`azd init` should succeed.

Actual:
`azd init` reports `Error: not logged in, run `azd login` to login`

**Comment by rajeshkamal5050** [comment]
This should be fixed with the recent changes w.r.t to `azd init` not requiring `azd auth login`

**Comment by vhvb1989** [comment]
We just moved the error to `azd provision` instead of `azd init`.   Which is still a bug.

`azd config reset` should not remove the current `auth` , even if that's part of the user config, it should be considered immune to `azd config reset`.  

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/24213737/231348810-7ec4e550-a1cf-445c-a8ba-ffcb26b0d51e.png">

**Comment by rajeshkamal5050** [comment]
> azd config reset should not remove the current auth

Did not get this one.
What we `azd config list` is what we `azd config reset`? If reset is an issue, then listing them is also an issue?

**Comment by weikanglim** [comment]
@rajeshkamal5050 When a user removes user configuration, they do not expect to be logged out. I don't think there's software that would work this way. For example, re-defaulting my Azure Portal settings shouldn't log me out.

The only reason this happens is that the implementation of `azd auth login` is problematic. It stores auth information in the user configuration file.

**Comment by rajeshkamal5050** [comment]
@weikanglim do we really need the below command to be public? Shouldn't we be okay for the users to knowingly set/unset configs they need?

`azd config reset : Resets configuration to default`

**Comment by rajeshkamal5050** [comment]
Not a must-fix for GA. Moving to Backlog.

@savannahostrowski @ellismg
