### ISSUE TITLE
`azd config reset` does not ask for confirmation

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1722]
It feels like we should have confirmation for a "reset all configuration" action.

**Comment by rajeshkamal5050** [comment]
Not a must-fix for GA. Moving it to Backlog.

@savannahostrowski @ellismg

**Comment by vhvb1989** [comment]
already implemented:

![image](https://github.com/Azure/azure-dev/assets/24213737/83710e1f-963b-40c5-9bdc-b69a46b0b074)
