### ISSUE TITLE
vscode: first install errors

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1728]
Does this occur consistently? Yes
Repro steps:
1. Have a brand new machine without CLI or extension installed
2. Install the extension
3. Install the CLI using the prompt
![image](https://user-images.githubusercontent.com/2322434/225133825-1893efa5-7ac5-429e-87fa-c785f12469d1.png)
5. Click Sign in.
6. **Unexpected behavior**: The tool prompted me to install again, which I clicked yes. It launched a another tab with `azd dev`. See two tabs below:
![image](https://user-images.githubusercontent.com/2322434/225133711-85c2a0b3-7a1c-4bc7-ba05-719853f63614.png)
7. **Unexpected behavior**: I clicked "Sign in" again. This executed a task, but the task failed due to PATH not including `azd`:
![image](https://user-images.githubusercontent.com/2322434/225133921-1bcbb78c-1a4e-4b7a-9ed3-ea3cfefc90e8.png)

Action: azure-dev.commands.cli.login
Error type: number
Error Message: 1

Version: 0.4.1
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.76.1
Language: en

**Comment by weikanglim** [comment]
@bwateratmsft I think you had mentioned some PATH fixes at standup. I couldn't find the issue, so decided to log one in case that helped.

**Comment by bwateratmsft** [comment]
Thanks @weikanglim. I'll take a look. We're working around first-session PATH issues by appending the usual install path to the PATH variable of processes we start. I'll see if there's a bug in this logic...

**Comment by bwateratmsft** [comment]
Ok, the good news is, it looks like sign-in is the only affected command. The bad news is, that's literally the next step on the walkthrough.

**Comment by bwateratmsft** [comment]
I think I know how I missed this. It's either one or both of these things--

1. If you are logged in, then uninstall and reinstall, you're _still_ logged in--it doesn't lose that state
2. I may have tried this by uninstalling and reinstalling _in the same session_, so when VSCode was first started, it had the necessary `PATH` entries--and I didn't restart after uninstalling, so it kept them
