### ISSUE TITLE
[Bug] Setting `Principal ID` on multi-tenant scenario

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#1729]
When azd env is created, azd is setting `AZURE_PRINCIPAL_ID` for the logged in user within the Home Tenant.

If user selects a subcription from a different tenant, the princiapal-id can be a different `id`, as the same use has different principal-id for within each tenant.

Then, any reference to `principal id` within `bicep` will fail, as that principal id does not exists on the tenant where the subscription is.

Provision error:
```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"PrincipalNotFound","message":"Principal XXXXXXXXXXX does not exist in the directory XXXXXXXXXXX . Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.  See [https://aka.ms/docs-principaltype"}]}](https://aka.ms/docs-principaltype%22%7D]%7D)
```

**Comment by vhvb1989** [comment]
Workaround: If the `PrincipalNotFound` error happened, user need to run:

> azd env set AZURE_PRINCIPAL_ID <user-principal-id-within-the-azure-directory>

**Comment by vhvb1989** [comment]
Another workaround:

Run `azd login --tenant-id <azure-directory-id>` , azd will set the principal id correctly then.

**Comment by ellismg** [comment]
This logic is initialized today here:

https://github.com/Azure/azure-dev/blob/26238399cafbd801b9538dbe9ec865434e6691ae/cli/azd/cmd/util.go#L285-L291

Looking at the code that is called by this, it looks like we should just be threading a tenant id along and where we call this in util.go can provide the correct tenant id (i.e. the one tied to the subscription they have selected).

**Comment by vhvb1989** [comment]
> This logic is initialized today here:
> 
> https://github.com/Azure/azure-dev/blob/26238399cafbd801b9538dbe9ec865434e6691ae/cli/azd/cmd/util.go#L285-L291
> 
> Looking at the code that is called by this, it looks like we should just be threading a tenant id along and where we call this in util.go can provide the correct tenant id (i.e. the one tied to the subscription they have selected).

@ellismg , but, what we need is the `object id` of the user within the selected tenant.  We are resolving the tenantId correctly, but we are not resolving what's the user's id within each tenant.
