### ISSUE TITLE
[Issue] Could not install MSI - osVersion 10.0.19044.0

### ISSUE THREAD

**Issue by DaruinHerrera** [Azure/azure-dev#1730]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

**Describe the bug**
Description of issue you're seeing...

**To Reproduce**
Steps to reproduce the behavior...

**Expected behavior**

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

**Comment by DaruinHerrera** [comment]
powershell -ex AllSigned -c "Invoke-RestMethod 'https://aka.ms/install-azd.ps1' | Invoke-Expression"
DETALLADO: Downloading build from https://azure-dev.azureedge.net/azd/standalone/release/latest/azd-windows-amd64.msi
DETALLADO: Decompressing artifacts
DETALLADO: Decompression not required
DETALLADO: Installing MSI
Invoke-RestMethod 'https://aka.ms/install-azd.ps1' | Invoke-Expression : Could not install MSI at C:\Users\IGNIWEB
06\AppData\Local\Temp\0nemuydn.di3\azd-windows-amd64.msi
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException

An error was encountered during install: MsiFailure
Error data collected:

Name                           Value
----                           -----
osVersion                      10.0.19044.0
installVersion                 latest
terminal                       powershell
isWsl                          False
reason                         MsiFailure
executionEnvironment           Desktop
os                             Win32NT



Answering 'yes' below will send data to Microsoft. To learn more about data collection see:
https://go.microsoft.com/fwlink/?LinkId=521839

You can also file an issue at https://github.com/Azure/azure-dev/issues/new?assignees=&labels=&template=issue_report.md&title=%5BIssue%5D

**Comment by rajeshkamal5050** [comment]
@danieljurek can you take a look at this installation failure?

Also, adding @abpiskunov since initial description has Visual Studio 16.3.

**Comment by danieljurek** [comment]
@DaruinHerrera, thanks for reporting! MSI related errors can frequently be associated with machine configuration. 

Please take the following actions and let me know the results: 

1. Download https://azure-dev.azureedge.net/azd/standalone/release/latest/azd-windows-amd64.msi
2. In PowerShell, cd to the location where you downloaded the MSI file and run: 

```pwsh
$installProcess = Start-Process "${env:SystemRoot}\System32\msiexec.exe" -ArgumentList @('/i', 'azd-windows-amd64.msi') -PassThru -Wait
Write-Host "Exit code: $($installProcess.ExitCode)"


```

The exit code can often give us hints about what may need to change without requiring detailed logs.

**Comment by danieljurek** [comment]
@DaruinHerrera, are you still seeing this issue? I've updated our install script so it will show exit codes and help us debug. You can run the install script to try again and it will print more information about the failure to the console: 

```pwsh
powershell -ex AllSigned -c "Invoke-RestMethod 'https://aka.ms/install-azd.ps1' | Invoke-Expression"
```

If I don't hear back from you we'll close this issue out.

**Comment by danieljurek** [comment]
Closing. We don't have enough information to work on a fix. @DaruinHerrera, if you encounter this issue again, please open a new issue or re-open this issue and we can help!
