### ISSUE TITLE
Telemetry: more usage info

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1736]
1. List of hashed flag names that are set (no user-provided value, just flag names).
2. List of hashed Languages in `services`
3. List of hashed Hosts in `service`

@savannahostrowski please help note any additional info you'd like collected. It's fairly trivial for us to instrument any new usage attributes, given we have the proper telemetry framework defined for doing it currently. For example, these changes are ~1 day of dev effort, so please help note anything else and we can do a 1-pass.

**Comment by savannahostrowski** [comment]
This makes sense to me. @esweet431 in case you have other thoughts.

**Comment by savannahostrowski** [comment]
Resource groups map 1:1 with environments. An app could have many environments (and therefore, many RGs).

Also interested in whether they'll be on all events. That's an interesting idea re. env name hashing.

**Comment by weikanglim** [comment]
We can do all events or just "usage events", which are `cmd.*`. Generally, it depends on how useful that attribute is.

@savannahostrowski That is certainly true in how we think users can use it. In reality, they could have the same `env` name mapped to different resources (in azd, this is convention based).

Re: How many "project" azd is creating -- should we just hash the project name?

**Comment by esweet431** [comment]
> Re: How many "project" azd is creating -- should we just hash the project name?

Where is project name defined? Is it the `name` field in azure.yaml? If so, then I don't think that will be helpful since it's not unique across projects.

**Comment by weikanglim** [comment]
@esweet431 Can you clarify what you mean by a project? Users are expected to update the `name` field for their own application. I would not expect users to run with `todo-python-mongo-swa-func` for example. It's simply the default name in the templates.

**Comment by esweet431** [comment]
> @esweet431 Can you clarify what you mean by a project? Users are expected to update the `name` field for their own application. I would not expect users to run with `todo-python-mongo-swa-func` for example. It's simply the default name in the templates.

Apologies for the late response. I agree that customers who are actually using the project will (hopefully) rename it, but I wouldn't be surprised if customers leave the template name as they are exploring - especially since `up` inits/provisions/deploys without asking the user to rename the project.

Does it make sense to hash both env name and project name?
