### ISSUE TITLE
Consistent resource abbreviations across all templates

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#174]
Right now all of our resource name abbreviations are hardcoded in templates and not shared amongst templates.  As we introduce new templates it will be nice to have consistent abbreviations amongst all of them and not depend on template developers copy and pasting the right values..  Bicep allows you to have a json lookup file.  Let's put the values in a shared JSON file and reference those in each template.

**Comment by rajeshkamal5050** [comment]
Done.
