### ISSUE TITLE
"Show resource group" in application tree view is very slow

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1742]
When clicking "show resource group" from the application tree view in the resources siderail, it often takes a very long time to open the correct RG (to the point where I'm not sure that it's working; I counted for one of my projects and it took ~18 seconds).

**Comment by bwateratmsft** [comment]
We need to transfer this to https://github.com/Microsoft/vscode-azureresourcegroups

**Comment by bwateratmsft** [comment]
Closing as external to https://github.com/microsoft/vscode-azureresourcegroups/issues/614
