### ISSUE TITLE
`azd env refresh` should accept positional env name argument like `azd env new`

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1746]
This is what I get when I try to use positional argument.  Looks like -e is required.  Would be good to be consistent with azd env new

![image](https://user-images.githubusercontent.com/2163001/225764866-ca80d7f4-32f4-4e3b-a955-ac8d13cee4f6.png)

**Comment by rajeshkamal5050** [comment]
Not a must-fix for GA. Moving it to Backlog.

@savannahostrowski @ellismg

**Comment by savannahostrowski** [comment]
Is it going to cause us issues if we don't get this in product before GA? Do we know what this would take to fix?

**Comment by rajeshkamal5050** [comment]
@ellismg Please update, if its a minor UX fix and pull it into May RC milestone.

**Comment by jongio** [comment]
I ran into this again today...would be good to squeeze in.

**Comment by savannahostrowski** [comment]
@rajeshkamal5050 Did we investigate this? I agree with Jon here.

**Comment by rajeshkamal5050** [comment]
> @rajeshkamal5050 Did we investigate this? I agree with Jon here.

No we did not. @ellismg can you take a look and see if we are consistent across?
