### ISSUE TITLE
azd login --tenant-id foo.onmicrosoft.com doesn't log you in to that tenant.

### ISSUE THREAD

**Issue by ctolkien** [Azure/azure-dev#1750]
`azd version 0.7.0-beta.1 (commit 9ce71659f7688d0dc3dda8b84e5accedca58cf01)`

**Describe the bug**

I'm specifying another tenant to login with, but it's logging me into my home tenant.

**To Reproduce**
Login with:
`azd login --tenant-id someothertenant.onmicrosoft.com`

**Expected behavior**

Expect to see subscriptions from this tenant. Instead I am seeing subs from my home tenant.

**Comment by weikanglim** [comment]
@ctolkien Thank you for reporting!

One clarification that may be important: when `azd` lists subscriptions, it will list subscriptions across all tenants. Perhaps you saw subscriptions from `someothertenant` as well as your home tenant?

If the claritifcation didn't help, let's troubleshoot.

Can you confirm:
1. When you `azd login --tenant-id <x>`, does the URL in the browser look like `login.microsoftonline.com/<someothertenant tenant ID>`? And when you run `azd login`, does the URL in the browser look different, i.e. `login.microsoftonline.com/<Home tenant ID>`? If so, `azd login` is indeed trying to redirect based on the specified tenant ID, and perhaps something else has gone awry.
