### ISSUE TITLE
Template bicep files don't accept custom resource group names

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#177]
Discovered when automating template testing.

**Comment by jongio** [comment]
Can you please provide more details on your scenario?  Thank you

**Comment by danieljurek** [comment]
Best path for our automated testing scenario: A way to add a tag to the resource group that exists for the lifetime of the resource group. 

In the case of automated testing we need to be able to ensure that resources deployed for testing are properly cleaned up after the tests complete. EngSys automation finds and removes resource groups which have a `DeleteAfter` tag whose value is a timestamp that has passed. 

Today, we're guessing the resource group name (I think inaccurately) in the template test pipeline and then adding the `DeleteAfter` tag in the pipeline. 

It'd be best if the tag were present for the lifetime of the resource group because failures in the pipeline could prevent this tag from being added after tests complete (network failure, VM crash, etc.) and the resource groups would persist until discovered and removed manually. 

Currently, deployments to a resource group overwrite tags so, if we created an RG with an appropriate tag before running `azd deploy` the deployment would overwrite the tag.

**Comment by jongio** [comment]
Okay, you should be able to solve this today by looking at the main.bicep file name to determine what resource group name will be created.  Right now it is {envname}-rg, but that will change to rg-{envname} with PR #140
