### ISSUE TITLE
[Issue] AZD output turns into a scrollie

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#1784]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 0.7.0-beta.1 (commit 9ce71659f7688d0dc3dda8b84e5accedca58cf01)

**Describe the bug**

When I run azd up commands, sometimes the text is too long for the line, and my terminal becomes a scrollie:

<img width="1149" alt="Screenshot 2023-03-23 at 11 39 49 AM" src="https://user-images.githubusercontent.com/297042/227315903-99bd3325-795f-4afe-864c-976cd32cc076.png">

This is totally an aesthetic thing, so not a big deal, and I don't know the magical of terminal output so I don't know how fixable it is. Just wanted to let you know! 

**To Reproduce**

Increase the font size to the point where a line wraps.

**Expected behavior**

No scrollie, progress output stays on one line

**Environment**
Information on your environment: Mac M1 Ventura Terminal app

**Comment by vhvb1989** [comment]
@savannahostrowski @ellismg I can a `truncate-console-logs` feature if you guys agree.

This is basically introducing something like `azd config set console.truncate-len 50` to make azd to add `...` at the end of lines longer than 50.

It would be non-set by default, which means no-truncate. And customers can set the length they want.

Let me know what you think.

**Comment by savannahostrowski** [comment]
@Austinauth for input here. 

I don't know if making it configurable is a must have at this point. I feel like we could truncate to a "reasonable" length and that'd probably suffice.

**Comment by ellismg** [comment]
> I don't know if making it configurable is a must have at this point. I feel like we could truncate to a "reasonable" length and that'd probably suffice.

That's probably the place I would start.  I think it is possible to send some set of terminal escape codes and get back information from the terminal emulator on how wide the terminal window is.  Longer term we could start doing this and have that inform what a "reasonable" length ends up being.

**Comment by vhvb1989** [comment]
> I feel like we could truncate to a "reasonable" length

For anyone having less than that and reporting this issue, will we just say "please use a reasonable length" ? =P   

Also, in case we don't give flexibility for setting the length, then does it really a good idea to truncate?  I think it would be better to stablish a limit for `text in the spinner` and make the spnniner `panic` if it receives a longer msg than the app-standard.  Then developers are forced to add messages with a max-length, instead of having the messages truncated anyway..

**Comment by Austinauth** [comment]
Aesthetically, I generally agree with the suggestion to use truncation here `...`. However, I'm mildly concerned that important information could be cutoff here. I'm also concerned that this might present accessibility issues for someone using a screen reader.

@savannahostrowski @vhvb1989 @ellismg How critical is this information. If we truncate do you foresee it causing confusion for users, particularly during error/failure scenarios?

@vhvb1989 What would happen to the truncation if the user were to adjust their screen size larger? Would it go away?

Including a max character length on sub-steps like may help, but also isn't a guaranteed fix if the user decides to make their text size larger or utilize a really small terminal window.

I'll investigate the accessibility issue tomorrow or early next week.

**Comment by rajeshkamal5050** [comment]
Not a must-fix for GA. Moving it to Backlog.

@savannahostrowski @ellismg

**Comment by savannahostrowski** [comment]
Do we know what it would take to fix this? It looks really rough in more narrow terminal windows (half screen right now).

I'd like to understand if this is a big lift or something we can feasibly polish before GA. I think we could see what the line lengths are for each service name and come up with a reasonable max length to truncate.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 Please update, if its a minor UX fix and pull it into May RC milestone.

**Comment by vhvb1989** [comment]
> @vhvb1989 Can we get this in before the May release? I got feedback around this a couple times at PyCon.

Got you a PR within 9 hours :) .  Let's see if folks like it. https://github.com/Azure/azure-dev/pull/2017
