### ISSUE TITLE
Add version check to VS Code

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1786]
With upcoming changes, we want to make sure that a user is encouraged to move to 0.8 or later.

**Comment by bwateratmsft** [comment]
As discussed offline, we can likely do this on a temporary basis--release a few extension versions with a version check during startup and eventually remove it.

**Comment by rajeshkamal5050** [comment]
Marking this as blocker for 0.8 April 5th release. If you think its not needed, please clarify and remove blocker.

@savannahostrowski @ellismg
