### ISSUE TITLE
az CLI installed in azd container

### ISSUE THREAD

**Issue by spboyer** [Azure/azure-dev#1795]
https://github.com/Azure/azure-dev/blob/7d92d369d1f403fd2fb0f9958a0fb49261cf6fc1/cli/Dockerfile#L18

Is this needed anymore, can it be removed?

**Comment by vhvb1989** [comment]
I is still used un CI for docker templates.

We'll see if we can have it only for those templates and remove it from here

**Comment by rajeshkamal5050** [comment]
@vhvb1989 why do we need Az CLI in docker? Anything else other than Azd uses it?

**Comment by vhvb1989** [comment]
oh, I meant `terraform`.  Not sure why I wrote `docker`. LoL.

The `azure-dev/cli/Dockerfile` is full-features container for azd.
It is used for running `azd` on CI (pipelines).  
So it  contains all the exiting features/dependencies for azd. Like languages (jdk, nodejs, dotnet, python), docker (to support `aca`), the `az` (to support terraform auth), etc.

This container is huge!! and I have been talking to @danieljurek about getting rid of it and to use the same devcontainer from each template for CI, instead of this super all-inclusive container

**Comment by spboyer** [comment]
Consider using `FROM --platform=amd64 mcr.microsoft.com/dotnet/sdk:6.0-cbl-mariner2.0` as the base. It includes  .NET Core SDK, PowerShell and you do not need to do this:
https://github.com/Azure/azure-dev/blob/09db608b8b8562e70608475d954c0c70df5ee88e/cli/Dockerfile#L6

**Comment by spboyer** [comment]
Example of what a smaller mariner image would look like
```docker
#Base image has .NET Core, PowerShell
FROM --platform=amd64 mcr.microsoft.com/dotnet/sdk:6.0-cbl-mariner2.0
WORKDIR /app

# Install Python
RUN tdnf upgrade -y
RUN tdnf install -y python3 python3-pip \
     && echo 'alias python=python3' >> ~/.bashrc \
     && echo 'alias pip=pip3' >> ~/.bashrc 

# Install Java
ARG package="msopenjdk-17"
ARG PKGS="tzdata freetype"

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
ENV JAVA_HOME=/usr/lib/jvm/msopenjdk-17

RUN tdnf install -y ${package} ${PKGS} && \
    tdnf clean all && \
    groupadd --system --gid=101 app && \
    adduser --uid 101 --gid 101 --system app && \
    install -d -m 0755 -o 101 -g 101 "/home/app" && \
    rm -rf /var/cache/tdnf && \
    rm -rf /usr/lib/jvm/${package}/lib/src.zip && \
    echo java -Xshare:dump && \
    java -Xshare:dump     

#Install NodeJS
RUN tdnf install -y nodejs 

#Install Terraform
RUN tdnf install -y wget && tdnf update
RUN tdnf install -y terraform

# Azure Functions Tools (use npm to install, Mariner doesn't have native package)
RUN npm install -g azure-functions-core-tools@4 --unsafe-perm true

# Install Azure CLI - verify if this is needed 900MB install
RUN tdnf install -y azure-cli

# Install Docker
ENV DOCKERVERSION=18.03.1-ce
RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz \
  && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 \
                 -C /usr/local/bin docker/docker \
  && rm docker-${DOCKERVERSION}.tgz

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
     && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
     && rm kubectl  

# azd
COPY cli/bin/azd-linux-amd64 /usr/bin/azd
COPY NOTICE.txt . 
```

**Comment by vhvb1989** [comment]
thank you @spboyer , that definitely looks like a better way to use more layers for the docker file than what we are currently doing.

However, my main concern is that this is not a scalable solution long term. The more languages `azd` support, the more things this container needs to add. And this is an expensive side effect to folks not using everything from the container.

Imagine I want to add ruby support, and my app is only using ruby.  I would need to bring ruby for everyone else, and I would need to use this big container on my CI.

**Comment by rajeshkamal5050** [comment]
Not a GA blocker. Moving this to Gallium. Don't think we will have the dev and test cycles to break the uber container.

@savannahostrowski @ellismg

**Comment by ellismg** [comment]
We've now released our own devcontainer feature, removing the need for this all in one container.

`az` is no longer required by `azd` for any cases, however, `az` the default authentication mode for terraform out of the box, so customers using terraform will need to continue to have `az` around, unless they pick a different authentication method.
