### ISSUE TITLE
Error installing azd via winget

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-dev#1796]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
not installed yet

**Describe the bug**
Brand new machine - installing azd before az cli:

```
> winget install microsoft.azd
Found Azure Developer CLI [Microsoft.Azd] Version 0.7.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/Azure/azure-dev/releases/download/azure-dev-cli_0.7.0-beta.1/azd-windows-amd64.msi
An unexpected error occurred while executing the command:
InternetOpenUrl() failed.
0x80072f05 : unknown error

> winget install microsoft.azd
Found Azure Developer CLI [Microsoft.Azd] Version 0.7.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/Azure/azure-dev/releases/download/azure-dev-cli_0.7.0-beta.1/azd-windows-amd64.msi
An unexpected error occurred while executing the command:
InternetOpenUrl() failed.
0x80072f05 : unknown error
```
Install Azure CLI
```
> winget install microsoft.azurecli
Found Microsoft Azure CLI [Microsoft.AzureCLI] Version 2.46.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://azcliprod.azureedge.net/msi/azure-cli-2.46.0.msi
  ██████████████████████████████  55.2 MB / 55.2 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```
Now install azd
```
> winget install microsoft.azd
Found Azure Developer CLI [Microsoft.Azd] Version 0.7.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/Azure/azure-dev/releases/download/azure-dev-cli_0.7.0-beta.1/azd-windows-amd64.msi
  ██████████████████████████████  12.6 MB / 12.6 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

**To Reproduce**
Brand new machine, before installing Azure CLI
```
winget install microsoft.azd
```

**Expected behavior**
azd installs without error

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

**Comment by weikanglim** [comment]
@charris-msft Thanks for logging this! It does seem that you were able to download it after retrying? I'm not sure if the `azure-cli` install is related, but it could be. I do see that other winget users have raised this in: https://github.com/microsoft/winget-cli/issues/566

I haven't managed to fully track down the error code related to `InternetOpenUrl()` but it seems to suggest some sort of TLS certificate validation error.

winerror.h: WININET_E_SEC_CERT_DATE_INVALID | The date in the certificate is invalid or has expired | winerror.h

**Comment by danieljurek** [comment]
@charris-msft, GitHub (where our releases are hosted) noted [an issue relating to their certificates on March 24th](https://www.githubstatus.com/incidents/x7njwb481j9b) around the time you encountered this error. Since we're not seeing additional errors here, we can close this as a transient issue involving our releases (hosted on GitHub's CDN).
