### ISSUE TITLE
Extra log from `azd deploy` after displaying the success message

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#1806]
The latest `deploy` implementation is sending one last console message update after the command has returned, making the output to show one last line at the end of the output like:

![image](https://user-images.githubusercontent.com/24213737/228130005-dc0c57dd-f061-49c3-a931-f7ac46f768e4.png)

**Comment by weikanglim** [comment]
This may not be isolated to the final deployment message update.

When we run in CI, we also observe out-of-order spinner messages:

![image](https://user-images.githubusercontent.com/2322434/228383586-ef3ee0bd-f204-4a89-8b0f-2a328aae7939.png)

`Deploying service api (Deployment completed)` happened after `Deploying service web`

**Comment by rajeshkamal5050** [comment]
Should be fixed as part of 0.8. Please re-open otherwise.
