### ISSUE TITLE
Terminating errors are sent to both `stdout` and `stderr`

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1823]
When an action (business logic) returns `nil` `action.Result`, and non-nil `err`, i.e. `return nil, fmt.Errorf("an error)`, the message is currently being sent to `stdout` instead of `stderr`. I believe this is a bug.

When a command (cobra layer) returns an error, it instead goes to `stdout`.

**Comment by rajeshkamal5050** [comment]
@weikanglim isn't this addressed?

**Comment by weikanglim** [comment]
No, but I don't think it's worth addressing.
