### ISSUE TITLE
[Issue] azd stuck in "Compiling bicep templates..." (if params are not initialized)

### ISSUE THREAD

**Issue by manekinekko** [Azure/azure-dev#1826]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

`azd version 0.7.0-beta.1 (commit 9ce71659f7688d0dc3dda8b84e5accedca58cf01)`

**Describe the bug**

Running `azd up` will hang in `Compiling Bicep template...` if one of the params is missing in `infra/main.parameters.json`.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/1699357/228846026-030af82c-b851-4991-bdba-f2ecb2d30bba.png)

**To Reproduce**
- create a `main.bicep` file that declares an uninitialized `param`, eg: `param storageAccountName string`
- somewhere in the module, use `storageAccountName` by checkiong if it is not empty
```
params: {
    name: !empty(storageAccountName) ? storageAccountName : '${abbrs.storageStorageAccounts}${resourceToken}'
}
```
- run `azd up`

**Expected behavior**
`azd up` should not hang. I'd expect at least a warning or an error.

**Environment**
N/A

**Additional context**

1. `az bicep compile` does compile and bicep code without errors.
2. In order to fix this issue, either we have to initialize the params in `main.bicep` or provide a value in `main.parameters.json`

**Comment by weikanglim** [comment]
@manekinekko Sorry for being late on this. Does this still reproduce for you on the latest `azd` version? 

On `azd version 0.9.0-beta.2 (commit afa7ac6e839be8304b86b3df6b8525a97e48a532)`, I see that an interactive prompt asks the user to fill the parameter, which is expected:

```bash
$ azd provision

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time

? Please enter a value for the 'storageAccountName' infrastructure parameter:
```
