### ISSUE TITLE
[Issue] Update devcontainers to point to new devcontainer image spec

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1843]
Example here: https://github.com/devcontainers/images/tree/main/src/python

We don't want the /vscode/ in our path anymore.

**Comment by vhvb1989** [comment]
I think this is already implemented @jongio . Unless I am misunderstanding...  Look at the current staging branch from todo-samples: https://github.com/Azure-Samples/todo-java-mongo/blob/staging/.devcontainer/devcontainer.json#L6

I am assuming you are refering to the devcontainers for the template samples, right?

Pamela had all templates updates with: https://github.com/Azure/azure-dev/pull/1463/files

**Comment by jongio** [comment]
Yes, closing...
