### ISSUE TITLE
[Issue] Explorer commands look out of place

### ISSUE THREAD

**Issue by isidorn** [Azure/azure-dev#1848]
Hi VS Code PM here 👋 

1. Install Azure Developer CLI extension
2. Open explorer, have an azure.yaml file
3. Context menu -> notice all the contributed commands

Couple of issues here:
1. Label of commands are not aligning with the rest of the explorer commands. Start of words should be capitalised. 
2. Description of commands should not be rendered in the command title (it looks out of place)
3. This looks like a bunch of commands without any order, grouping or whatsover. Can we shorten the list, or at least add some separators, or sub-menus

Thank you!

![image](https://user-images.githubusercontent.com/1926584/229517093-38e222d2-3d79-4898-834a-5635787d6a03.png)

**Comment by savannahostrowski** [comment]
@gkulin Let's chat about this after Build.

**Comment by charris-msft** [comment]
I was going to report the same feedback. it took me a minute to realize that the large block of commands were for azd.

I was also surprised that there wasn't an `init` command in the list.

**Comment by savannahostrowski** [comment]
Yeah, so the plan here is to rework these items so that each is "<Human-readable title> (`<command>`)" instead. We don't want to hide what command is being fired by `azd` because as we start to leverage more native VS Code UI over the embedded terminal, we want to make sure that folks can build a mental model about what commands are actually being fired.

Re. `init`, the reason you can't see `init` in the list is because you've already initialized and there's an `azure.yaml` in your project. You can run `init` from the command palette but it doesn't make much sense to show it in the context menu as the ability to use the context menu hinges on an initialized project today.

**Comment by bwateratmsft** [comment]
At the same time I'd like to address the sorting and/or grouping of the commands to make it consistent and logical.

**Comment by savannahostrowski** [comment]
Yep - we can map to what we show in `azd -h` or similar.

**Comment by savannahostrowski** [comment]
I think this looks much better tbh. Some nits
- For the "Azure Developer CLI" context menu entry, can it be "Azure Developer CLI (azd)"
- Can we remove the backticks from the commands in parens as they don't render?
- `up` should probably have package, provision, deploy

Otherwise, LGTM

**Comment by bwateratmsft** [comment]
Ok, with feedback from above comment and what we discussed offline, here's a new batch of screenshots:

Command palette:
![image](https://github.com/Azure/azure-dev/assets/36966225/194de544-51c4-46b1-8543-5164691a79d9)

`azure.yaml` context menu:
![image](https://github.com/Azure/azure-dev/assets/36966225/cbdf21a0-0afa-45c5-90ec-d523517a307a)

Application:
![image](https://github.com/Azure/azure-dev/assets/36966225/9e24f138-bf77-4d5c-9685-c40d6584ab5f)

Services:
![image](https://github.com/Azure/azure-dev/assets/36966225/f69707bf-a414-4ac6-b56a-d0e9bb55497b)

Service:
![image](https://github.com/Azure/azure-dev/assets/36966225/95d79e46-ef95-4902-9035-adc99d943502)

Environments:
![image](https://github.com/Azure/azure-dev/assets/36966225/193cff4a-537c-4d94-a0a3-e11e4a635153)

Environment (selected as default):
![image](https://github.com/Azure/azure-dev/assets/36966225/ad4fa1b3-61d7-4086-b6bb-40e6cb73bbf9)

Environment (not selected as default, so Select and Delete commands show):
![image](https://github.com/Azure/azure-dev/assets/36966225/36b8e292-e064-4bc4-8a85-e4a19c4c9f16)

**Comment by savannahostrowski** [comment]
LGTM! Ship it :D

**Comment by isidorn** [comment]
Looks great! Thank you very much 👏
