### ISSUE TITLE
Uninstall text not showing on uninstall for MSI package

### ISSUE THREAD

**Issue by heaths** [Azure/azure-dev#1858]
Despite both the `Installed` and `REMOVE` properties being set correct e.g., `REMOVE=ALL`, the custom uninstall text is not showing in the `ExitDlg` when invoked with `msiexec /x`. If you run `msiexec /i` and run the MSI in maintenance mode, then choose **Uninstall**, it does show as expected. The condition should fire appropriately.

Need to investigate more.

_Originally posted by @heaths in https://github.com/Azure/azure-dev/pull/1834#discussion_r1156474297_

**Comment by heaths** [comment]
"omus" is too strict when we want to allow "channel hopping" of sorts between betas and releases. That said, `REMOVE` is still "ALL" by the end. Maybe I should dump properties right after `CostFinalize` and make sure. Do you know, off hand, if dialog conditions are evaluated early at script time, though? I wouldn't think so, but done much with standard Windows Installer UI beyond simple, static customizations in a _very_ long time since we always ended up using chainers for everything.

It'll be an interesting test, though. I can remove `REINSTALLMODE` and see if that helps, but would likely be just as confusing since the condition still should work. But, hey, if the shoe fits...

**Comment by barnson** [comment]
Sadly, I think you can continue to abuse `REINSTALLMODE`. The only thing that `/x` might do is set `Preselected`, which is a bigger deal on initial dialogs, not the end. I imagine the conditions are evaluated first when the dialog is created. Then there are weird rules for what has to happen to make MSI update the UI (the whole trick about showing a second dialog just to get an update of a control tied to a property).
