### ISSUE TITLE
ParameterOutOfRange: The value of the 'Version' should be in: [] when creating resource DBforPostgreSQL.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-dev#1866]
**Describe the issue:**
When executing the `azd provision` command, and will encounter this error.
<img width="588" alt="image" src="https://user-images.githubusercontent.com/81678720/229760037-4e0dde9d-ae4e-4d35-b7de-1f60524c70b9.png">

**Repro Steps:**
1. azd init -t <template_name>
2. azd package
3. azd provision

**Environment:**
OS: Windows
Templates: 
- Azure-Samples/bindings-dapr-python-cron-postgres  
- Azure-Samples/bindings-dapr-csharp-cron-postgres  
- Azure-Samples/bindings-dapr-nodejs-cron-postgres  
- pamelafox/flask-surveys-container-app 
- pamelafox/django-quiz-app 
- fangjian0423/todo-java-postgresql-aca-terraform 
- fangjian0423/todo-java-postgresql-terraform 

Azd version: azd version 0.7.0-beta.2-pr.2672227 (commit dec4eb2c9f5932d3bd41f7e66b41c775c050ad48)

**Expected behavior:**
Execute the `azd provision` command to successfully create all resources.

@rajeshkamal5050 for notification.

**Comment by vhvb1989** [comment]
Related to: https://github.com/pamelafox/flask-surveys-container-app/issues/19

Please use a different location when using postfreSQL within the playground subscription (or microsoft tenant's subscriptions)
