### ISSUE TITLE
Failed packaging service 'web': failing invoking action 'package'

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-dev#1867]
**Describe the issue:**
When executing the `azd package` command, the path where the `.zip` file is stored after packaging is different from the path system is looking for.
![image](https://user-images.githubusercontent.com/81678720/229769452-5292173a-81aa-4190-a59b-5c0021534ca3.png)

**Repro Steps:**

1. azd init -t <template_name>
2. azd package

**Environment:**
Scene 1: (Windows Desktop)
zul-m/AzureDevCLI, fangjian0423/todo-java-postgresql-terraform, manekinekko/todo-nodejs-mongo-swa, glaucia86/azure-sql-prisma-vue, todo-csharp-cosmos-sql, todo-nodejs-mongo, todo-nodejs-mongo-swa-func, todo-python-mongo, todo-python-mongo-swa-func , todo-csharp-sql, todo-python-mongo-terraform, todo-csharp-sql-swa-func, todo-java-mongo

Scene 2: (Linux Desktop)
todo-nodejs-mongo-swa-func, todo-python-mongo-swa-func, todo-python-mongo-terraform, todo-nodejs-mongo-terraform, todo-csharp-sql-swa-func, todo-java-mongo 

Scene 3: (WSL and CodeSpace)
todo-csharp-cosmos-sql, todo-nodejs-mongo, todo-nodejs-mongo-swa-func, todo-python-mongo, todo-python-mongo-swa-func , todo-csharp-sql, todo-python-mongo-terraform, todo-csharp-sql-swa-func, todo-java-mongo

Azd version: azd version 0.7.0-beta.2-pr.2672227 (commit https://github.com/Azure/azure-dev/commit/dec4eb2c9f5932d3bd41f7e66b41c775c050ad48)

**Expected behavior:**
Execute the `azd package` command can pass.

@rajeshkamal5050 for notification.

**Comment by bwateratmsft** [comment]
@wbreza this is similar to the issue I hit yesterday.

**Comment by rajeshkamal5050** [comment]
@wbreza can you take a look at the package issue? Marked it as a blocker. Please update.

**Comment by wbreza** [comment]
@rajeshkamal5050 @zedy-wj - this is most likely with not running the templates against the `staging` branch.  For 0.8 testing you MUST using the `staging` branch for all template testing.
