### ISSUE TITLE
The subscription does not have QuotaId/Feature required by sku 'S0' from kind 'OpenAI'

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-dev#1868]
**Describe the issue:**
When executing the `azd provision` command, resource `OpenAI` (sku: S0) could not be created under testing subscription.
![image](https://user-images.githubusercontent.com/81678720/229781357-bc13a6bb-f644-4328-9b96-4e56ecc546b8.png)
![image](https://user-images.githubusercontent.com/81678720/229781507-80f80d7c-f618-4f31-9ee3-9a901c8537b0.png)

**Repro Steps:**

1. azd init
2. azd package
3. azd provision

Environment:
OS: Windows
Template: Azure-Samples/azure-search-openai-demo 
Azd version: azd version 0.7.0-beta.2-pr.2672227 (commit dec4eb2c9f5932d3bd41f7e66b41c775c050ad48)

**Expected behavior:**
Please cleanup the resource in testing subscription (Azure SDK Developer Playground).

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 we cannot run the OpenAI sample on the the SDK subs right? Please update.

**Comment by vhvb1989** [comment]
We can run it but only using a location from:
- South Central US
- West Europe
- East US

But, we should create special procedure for this template to re-use an existing instance of openAI instead of create/delete all the times.  There's an instance in the playground expected to be shared between everyone :).  

Please do not run this template as part of the tests until we share the instructions for re-using the resources.

**Comment by datumradix** [comment]
We are facing the same issue if use East US deployed through Codespaces

**Comment by teepipe** [comment]
any solution to this?

**Comment by Cat-Vader** [comment]
Anyone find a solution? I am facing the same challenge through codespaces

**Comment by rajeshkamal5050** [comment]
@vhvb1989 the one reported by @zedy-wj initially was due to the subs limitation. Any other issue we have? Since. I see other folks also facing a similar on their subs?

**Comment by vhvb1989** [comment]
There is a limit to the number of Azure OpenAI instances that can be created within a subscription.

The original error here is about a subscription where the limit is reached. This is not azd-issue.
