### ISSUE TITLE
azd pipeline config  `Azure Dev Provision` fail in pipeline for `todo-nodejs-mongo-aks`

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#1871]
**Describe the issue:**
The template deployment fail , when run `azd pipeline config --provider azdo`.

The error message as follows:
![image](https://user-images.githubusercontent.com/80496810/229798456-87f358b7-77ab-4c23-aabc-9054bb47fb15.png)

**Repro steps:**
1. Run command `azd login`.
2. Run command ` bash ./test-templates.sh -t todo-nodejs-mongo-aks -b staging`
3. Run command `azd pipeline config --provider azdo`

**Environment:**
OS: Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code, WSL.
Template: todo-nodejs-mongo-aks
Azd version: 0.7.0-beta.2-pr.2672227  (commit https://github.com/Azure/azure-dev/commit/dec4eb2c9f5932d3bd41f7e66b41c775c050ad48)

**Expected behavior:**
`azd pipeline config --provider azdo` can pass.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you take a look at the azdo issue? Marked it as a blocker. Please update.

**Comment by wbreza** [comment]
@rajeshkamal5050 @vhvb1989  Looks like a duplicated of closed issue #1686

**Comment by vhvb1989** [comment]
> @rajeshkamal5050 @vhvb1989 Looks like a duplicated of closed issue #1686

Do we need to document within aks-todo templates that running azd pipeline requires to set an special role? Or at least as part of the test-procedures notes.

**Comment by vhvb1989** [comment]
removing blocker...  as this is known configuration issue

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 This issue also occurs in the following cases:

- OS: Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code, WSL.
- Template: todo-nodejs-mongo-aks
- Branch: Staging
- Azd version:  0.7.0-beta.2-daily.2681609  (commit https://github.com/Azure/azure-dev/commit/81b97e0268a78c521ef0017c5c9531c4ba7e0399)

**Comment by rajeshkamal5050** [comment]
@wbreza can we callout the requirements `azd pipeline config --provider github --principal-role owner` in the template's ReadMe?
