### ISSUE TITLE
Don't mandate that repos must have lowercase names

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1874]
See https://github.com/bradygaster/RockPaperOrleans/issues/11 as an example.

We shouldn't be dictating how a user's code is structured or named etc. We need to meet folks where they are at.

**Comment by savannahostrowski** [comment]
@rajeshkamal5050 @ellismg Can we get this prioritized for April? Seems rather invasive to tell users that their repos must be named in a specific way to use azd.

**Comment by bradygaster** [comment]
My 2C: AZD shouldn't care what people name things. At all. Directories, files, yada ^2.

**Comment by rajeshkamal5050** [comment]
@wbreza please take a look a this https://github.com/bradygaster/RockPaperOrleans/issues/11 issue where `azd package` is failing.

**Comment by wbreza** [comment]
This appears to be a requirement of docker, not azd.  But Azd should lowercase the docker repository names automatically.
