### ISSUE TITLE
'azd' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by NorvalH1** [Azure/azure-dev#1879]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-dev.commands.cli.init
Error type: 1
Error Message: Process 'azd template list --output json' exited with code 1
Error: 'azd' is not recognized as an internal or external command,
operable program or batch file.

Version: 0.4.2
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.77.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.js:2:919933
```

</details>

**Comment by bwateratmsft** [comment]
@NorvalH1 do you have the Azure Dev CLI installed?
