### ISSUE TITLE
April/May Docs Plan

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1884]
- [ ] Brainstorm/spec updates to [learn.microsoft.com/en-us/azure/developer/azure-developer-cli/overview](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/overview)
- [ ] Brainstorm/spec updates to "Get started" tab
- [x] Add ASA info to DevHub when merged (if in DevHub) - https://github.com/Azure/azure-dev/pull/1808 @fangjian0423 @vhvb1989 
- [ ] SWA known issue/troubleshoot update https://github.com/Azure/azure-dev/issues/1847 @vhvb1989 
- [x] Pipelines <-> CodeSpaces improvements. Any additions/removals from existing troubleshoot/FAQ's - https://github.com/Azure/azure-dev/issues/1938 @vhvb1989 
- [ ] [azure.yaml.json](https://github.com/Azure/azure-dev/blob/main/schemas/v1.0/azure.yaml.json) publishing recent updates. Is it automatic as part of pipelines? @danieljurek

**Comment by savannahostrowski** [comment]
Add ASA info to DevHub when merged (if in DevHub).

**Comment by savannahostrowski** [comment]
P0 for release on May 9:
- Add ASA info to DevHub when merged (if in DevHub) - https://github.com/Azure/azure-dev/pull/1808 @fangjian0423 @vhvb1989
- https://github.com/Azure/azure-dev/pull/2029

By May 23:
- Getting started revisions
- CSS doc updates
- SWA known issue/troubleshoot update https://github.com/Azure/azure-dev/issues/1847 @vhvb1989
 Pipelines <-> CodeSpaces improvements. Any additions/removals from existing troubleshoot/FAQ's - https://github.com/Azure/azure-dev/issues/1938 @vhvb1989
 [azure.yaml.json](https://github.com/Azure/azure-dev/blob/main/schemas/v1.0/azure.yaml.json?rgh-link-date=2023-04-05T22%3A42%3A27Z) publishing recent updates. Is it automatic as part of pipelines? @danieljurek
- environment updates per @ellismg

**Comment by danieljurek** [comment]
Publishing `azure.yaml.json` docs is not automated today, however our builds always produce the markdown for that. 

To get the markdown: 

1. Open release build
2. Navigate to `Artifacts` 
3. Open the `docs` artifact
4. Download the `azure.yaml.schema.md` file
5. Open PR to update docs using the new `azure.yaml.schema.md` file
