### ISSUE TITLE
Capture azd Commands Telemetry (enable for production)

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#190]
Bootstrap all azd commands (except version, help) should track the command duration/success

**Comment by weikanglim** [comment]
Telemetry has been implemented with recent changes. This work will track enabling it for production use once infrastructure pieces are ready.

These lines of code will be removed: https://github.com/Azure/azure-dev/blob/90bab013dcc90498c47fd87b2dc66e5f78eb979a/cli/azd/internal/telemetry/telemetry.go#L83-L85

We should also remove the `aztempl` user-agent from our Azure service HTTP requests.
