### ISSUE TITLE
[Issue/Question] Unable to edit or replace deployment when trying to run two parallel GitHub Actions pipelines

### ISSUE THREAD

**Issue by sabbour** [Azure/azure-dev#1900]
When running `azd provision` in a GitHub Actions pipeline, it frequently runs into a race condition where if the pipeline was triggered more than once, for example if two changes were pushed, ARM will complain that there's an already existing deployment taking place.

Is there some guidance on what's the best way to approach this? This seems very common.

```
ERROR: deployment failed: error deploying infrastructure: failed deploying: starting deployment to subscription: PUT https://management.azure.com/subscriptions/***/providers/Microsoft.Resources/deployments/***
--------------------------------------------------------------------------------
RESPONSE 409: 409 Conflict
ERROR CODE: DeploymentActive
--------------------------------------------------------------------------------
{
  "error": {
    "code": "DeploymentActive",
    "message": "Unable to edit or replace deployment '***': previous deployment from '4/6/2023 11:54:53 PM' is still active (expiration time is '4/13/2023 11:54:50 PM'). Please see https://aka.ms/arm-deploy-resources for usage details."
  }
}
--------------------------------------------------------------------------------
```

**Comment by rajeshkamal5050** [comment]
This could be due to a upstream GitHub issue discussed here #1767

**Comment by vhvb1989** [comment]
@sabbour , you can try a `queue` strategy like:
https://github.com/marketplace/actions/github-workflows-queue
or
https://github.com/marketplace/actions/workflow-queue

It would make flows to run one after the other instead of on demand. 

@rajeshkamal5050  @ellismg  @savannahostrowski , let me know if you want to update our samples using this strategy.


The other strategy is to make any newest workflow to cancel the previous one

**Comment by sabbour** [comment]
@vhvb1989 not exactly, I think this is more around giving some thought into the assumptions. Particularly:
- Is there an assumption that only one person is working on the project, hence there will not be multiple code commits that are competing to deploy the changes?
- Since azd provision and azd deploy are not doing differential deployments and essentially they're packaging the whole thing, is it really safe to assume that they can be used in a pipeline to deploy the changes to the same environment without running into a race condition?
- Should we revisit the purpose of azd (including in docs and examples) so that this is more of a deploy to a "developer environment" per developer versus being a tool to deploy to production?
- What if we think about azd in deployment pipelines as a way to create pull request specific e2e testing environments? Can we create examples for that?

I'm just thinking out loud :)

**Comment by sabbour** [comment]
> @sabbour , you can try a `queue` strategy like: https://github.com/marketplace/actions/github-workflows-queue or https://github.com/marketplace/actions/workflow-queue
> 
> It would make flows to run one after the other instead of on demand.
> 
> @rajeshkamal5050 @ellismg @savannahostrowski , let me know if you want to update our samples using this strategy.
> 
> The other strategy is to make any newest workflow to cancel the previous one

The queue approach is a good way to start.
