### ISSUE TITLE
[Issue] azd init -t azure-search-openai-demo failes due to GIT

### ISSUE THREAD

**Issue by bryanyip94** [Azure/azure-dev#1902]
**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 0.7.0-beta.1 (commit 9ce71659f7688d0dc3dda8b84e5accedca58cf01)

**Describe the bug**
azd init -t azure-search-openai-demo

ERROR: required external tools are missing:
 - error checking for external tool git CLI: checking git CLI version: exit status 1

**To Reproduce**
run: 
azd init -t azure-search-openai-demo

**Environment**

git --version
git version 2.40.0.windows.1

**Comment by weikanglim** [comment]
@bryanyip94 Can you rerun with `--debug` enabled? i.e. `azd init -t azure-search-openai-demo --debug`

The standard out and error from the `git` command should be available, that will help us troubleshoot.

**Comment by vhvb1989** [comment]
Please also mention what OS you're using (assuming it is Windows, by the git --version output, but is it 10/11?)
What console are you using ? WindowsPowerShell?  PowerShell7?  Cmd?  GitBash?

**Comment by vhvb1989** [comment]
related: https://github.com/Azure-Samples/azure-search-openai-demo/issues/92

**Comment by stuartsands** [comment]
Same problem and output as above. Running Windows 10. 
If I run git --version from the same terminal window, I get:

```
git version 2.39.2.windows.1
```

**Comment by rajeshkamal5050** [comment]
@weikanglim @vhvb1989 any findings on this?

**Comment by weikanglim** [comment]
@bryanyip94 / @stuartsands Are you still hitting this issue?

Unfortunately, it looks like we're not outputting the required info into debug (I have a pending change to fix this).

We'll need to do some ad-hoc debugging in the meantime.

In PowerShell,
```pwsh
git --version
echo $LASTEXITCODE
```

Is `$LASTEXITCODE` 0 here?

If running in cmd prompt, the equivalent steps would be:

```cmd
git --version
echo %ERRORLEVEL%
```

**Comment by vhvb1989** [comment]
@bryanyip94 @stuartsands 

Can you also provide the output from running `Get-Command git` from powershell ?

**Comment by bryanyip94** [comment]
I am still getting the same error after installing the latest version:

```
ERROR: required external tools are missing:
 - error checking for external tool git CLI: checking git CLI version: exit status 1
```

And these are the output of the command you provided:
```
XXXX\repo> git --version
git version 2.40.1.windows.1
XXXX\repo> echo %ERRORLEVEL%
%ERRORLEVEL%
XXXX\repo> Get-Command git

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     git.exe                                            2.40.1.1   C:\Git\cmd\git.exe `
```

**Comment by weikanglim** [comment]
Hi @bryanyip94 , if you want to wait a week and upgrade again, the about-to-be-released version of `azd` will include the error output so we can debug further.

If you do want to investigate it right away, you can install the latest [daily](https://github.com/Azure/azure-dev/blob/main/cli/installer/README.md#download-from-daily-builds) (pre-release) build and rerun the command. We should see what the error message coming from `git` is, and how to proceed from there.

The `daily` build is pretty stable and should be able to at least provide diagnostics, but if it's inconvenient for you, we could just hold off until then.

**Comment by weikanglim** [comment]
@bryanyip94 Can you retry with azd version 0.9.0-beta.3 (commit e564b122af7c1cb92bc54755f32930d661dddda2) and reattach the output of running the command?

**Comment by Lasweiga** [comment]
This is still happening with azd 1.0. Was there any conclusion how to solve the " - error checking for external tool git CLI: checking git CLI version: exit status 1" issue?

**Comment by vhvb1989** [comment]
@Lasweiga , can you run azd using `--debug` and shared the logs please?

**Comment by Lasweiga** [comment]
![image](https://github.com/Azure/azure-dev/assets/1085856/c07e4134-d02d-4857-bfc7-f314ddde9a1b)

**Comment by weikanglim** [comment]
@Lasweiga I'm not sure how this may have happened, but it could be possible that there's two `git` executables located in your `PATH` variable.

Can you try running the following in powershell to see if anything changes:

```pwsh
$gitPath = Split-Path -Parent (get-command git.exe).Path
Write-Host "gitPath: $gitPath"
$env:PATH="$gitPath;$env:PATH"
azd init -t azure-search-openai-demo --debug
```

**Comment by Lasweiga** [comment]
Hi,

Here is the result:
[image: image.png]

I have the same result :(

**Comment by santamariasilvia** [comment]
I'm experiencing the same after a Windows update :( In my case, I was able to run the code one week ago, but now it is not working anymore

**Comment by weikanglim** [comment]
Two things to try:

1. Let's make the PATH even more constrained to see if we can't spot the error. If this does error, it does seem to suggest a problem with the binary:
```pwsh
# Get current git path
$gitPath = Split-Path -Parent (get-command 'git.exe').Path
Write-Host "gitPath: $gitPath"
Get-ChildItem $gitPath

# Get azd path
$azdCmd = (get-command 'azd.exe').Path

# Confirm PATH is taking effect
$env:PATH=""

# Try running azd, this should fail because GIT is not available which is expected
& $azdCmd init -t azure-search-openai-demo

$env:PATH="$gitPath"

# Run azd again with only GIT in PATH
& $azdCmd init -t azure-search-openai-demo --debug
```

1. If you're still seeing the final error from the previous script, can you also try installing a later version of GIT to see if that changes anything? https://git-scm.com/download/win

**Comment by Lasweiga** [comment]
> Two things to try:
> 
> 1. Let's make the PATH even more constrained to see if we can't spot the error. If this does error, it does seem to suggest a problem with the binary:
> 
> ```powershell
> # Get current git path
> $gitPath = Split-Path -Parent (get-command 'git.exe').Path
> Write-Host "gitPath: $gitPath"
> Get-ChildItem $gitPath
> 
> # Get azd path
> $azdCmd = (get-command 'azd.exe').Path
> 
> # Confirm PATH is taking effect
> $env:PATH=""
> 
> # Try running azd, this should fail because GIT is not available which is expected
> & $azdCmd init -t azure-search-openai-demo
> 
> $env:PATH="$gitPath"
> 
> # Run azd again with only GIT in PATH
> & $azdCmd init -t azure-search-openai-demo --debug
> ```
> 
> 1. If you're still seeing the final error from the previous script, can you also try installing a later version of GIT to see if that changes anything? https://git-scm.com/download/win

**This is just running the script without trying to reinstalling the GIT:**

`Directory: C:\Program Files\Git\cmd

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          14/03/2023  7:12 AM         136240 git-gui.exe
-a---          14/03/2023  7:12 AM          45088 git-lfs.exe
-a---          14/03/2023  7:12 AM          45088 git.exe
-a---          14/03/2023  7:12 AM         136240 gitk.exe
-a---          14/03/2023  7:12 AM          45088 scalar.exe
-a---          14/03/2023  7:12 AM           3022 start-ssh-agent.cmd
-a---          14/03/2023  7:12 AM           2723 start-ssh-pageant.cmd

ERROR: required external tools are missing:
 - git CLI is not installed, see https://git-scm.com/downloads to install
2023/06/17 08:39:54 main.go:53: azd version: 1.1.0-beta.1-daily.2836717 (commit c20734243ee94dc4228490089ff36a48f365bc2d)
2023/06/17 08:39:54 main.go:203: using cached latest version: 1.0.2 (expires on: 2023-06-17T06:32:52Z)
2023/06/17 08:39:54 cobra_builder.go:137: Resolved action 'azd-init-action'
2023/06/17 08:39:54 middleware.go:124: running middleware 'debug'
2023/06/17 08:39:54 middleware.go:124: running middleware 'telemetry'
2023/06/17 08:39:54 telemetry.go:45: TraceID: dfcc7a4d6de009cada99acb91307798d
2023/06/17 08:39:54 command_runner.go:132: Run exec: 'git --version' , exit code: 1

ERROR: required external tools are missing:
 - error checking for external tool git CLI: checking git CLI version: exit code: 1, stdout: , stderr:`


**After reinstalling the GIT:**

`gitPath: C:\Program Files\Git\cmd

    Directory: C:\Program Files\Git\cmd

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           1/06/2023  4:34 PM         136200 git-gui.exe
-a---           1/06/2023  4:34 PM          45048 git-lfs.exe
-a---           1/06/2023  4:34 PM          45048 git.exe
-a---           1/06/2023  4:34 PM         136200 gitk.exe
-a---           1/06/2023  4:34 PM          45048 scalar.exe
-a---           1/06/2023  4:34 PM           3022 start-ssh-agent.cmd
-a---           1/06/2023  4:34 PM           2723 start-ssh-pageant.cmd

ERROR: required external tools are missing:
 - git CLI is not installed, see https://git-scm.com/downloads to install
2023/06/17 08:46:01 main.go:53: azd version: 1.1.0-beta.1-daily.2836717 (commit c20734243ee94dc4228490089ff36a48f365bc2d)
2023/06/17 08:46:01 main.go:203: using cached latest version: 1.0.2 (expires on: 2023-06-17T06:32:52Z)
2023/06/17 08:46:01 cobra_builder.go:137: Resolved action 'azd-init-action'
2023/06/17 08:46:01 middleware.go:124: running middleware 'debug'
2023/06/17 08:46:01 middleware.go:124: running middleware 'telemetry'
2023/06/17 08:46:01 telemetry.go:45: TraceID: 6d887a862c7ea81fd870b87aa37cd0cc
2023/06/17 08:46:02 command_runner.go:132: Run exec: 'git --version' , exit code: 1

ERROR: required external tools are missing:
 - error checking for external tool git CLI: checking git CLI version: exit code: 1, stdout: , stderr:


╭╴者 xcadat C:\Projects\bmw
╰─➜ git --version
git version 2.41.0.windows.1`


So, has not changed anything :(

**Comment by weikanglim** [comment]
@Lasweiga Thank you for those logs. That's helpful.

I realized that the invocation is going through the cmd shell. What is the output after running the following commands in powershell?

```pwsh
& "$env:SYSTEMROOT\System32\cmd.exe" '/c' 'git' '--version'
Write-Host $LASTEXITCODE
```

**Comment by Lasweiga** [comment]
azd init -t azure-search-openai-demo --debug & "$env:SYSTEMROOT\System32\cmd.exe" '/c' 'git' '--version'
ParserError:
Line |
   1 |  … openai-demo --debug & "$env:SYSTEMROOT\System32\cmd.exe" '/c' 'git' ' …
     |                                                             ~~~~
     | Unexpected token ''/c'' in expression or statement.


 Write-Host $LASTEXITCODE
1

> @Lasweiga Thank you for those logs. That's helpful.
> 
> I realized that the invocation is going through the cmd shell. What is the output after running the following commands in powershell?
> 
> ```powershell
> & "$env:SYSTEMROOT\System32\cmd.exe" '/c' 'git' '--version'
> Write-Host $LASTEXITCODE
> ```

**Comment by Lasweiga** [comment]
@weikanglim  did you get my latest above? I hope that helps you to identify the issue.

**Comment by weikanglim** [comment]
hi @Lasweiga. Sorry for not getting back to you sooner. Summer vacation has taking up my time in the last week.

From your output, it seems like you ran the following command in a single line:

```pwsh
azd init -t azure-search-openai-demo --debug & "$env:SYSTEMROOT\System32\cmd.exe" '/c' 'git' '--version'
```

Would you be able to run the following commands as-is in your terminal?

```posh
& "$env:SYSTEMROOT\System32\cmd.exe" '/c' 'git' '--version'
Write-Host $LASTEXITCODE
```

**Comment by Lasweiga** [comment]
@weikanglim I copied the code you provided and pasted as is. Here is the result:
![image](https://github.com/Azure/azure-dev/assets/1085856/452604e1-ead8-4e2e-bb93-c6f202c1dab1)
