### ISSUE TITLE
`azd deploy` should not print `azd package` as the first thing it does

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#1904]
Unlike other commands, when `azd deploy` runs, it first prints `Packaging service (azd package)` as the first thing it runs. Without additional context, this may result in confusion on which command the user intended to run. The user may even second-guess that they ran the wrong command, `azd package` instead of `azd deploy`.  Example:

![image](https://user-images.githubusercontent.com/2322434/230658597-5ad7f6fa-14fa-4f21-baa8-2a54f3971bb4.png)

The other pattern we have is in `azd up`, but we've always viewed `azd up` as an orchestration, and it is clear in the docs that `azd up` runs a series of commands to apply all your infrastructure + code changes to Azure in a single command.

The other thing this may hurt is in terms of information progressive disclosure. For a developer that never ends up using a production release mechanism, they may not even need to know that `azd package` is a thing. Packaging really only comes in when users start thinking about a production CI workflow, and isn't really required if the user does not choose to opt-in to that. For example, a developer that works on a team that already has separate teams that take care of releasing the product and may only interact with a dev Azure resource, would maybe simply use `azd deploy` as the primary mechanism to enact their code changes in Azure.

I wrote this issue after discussing with @savannahostrowski. Feel free to add any additional context here.

**Comment by savannahostrowski** [comment]
Yep - 100% agree. This feels jarring because the user didn't invoke `package`, they invoked `deploy`.

I think that it's fine to provide flexibility to users (in that they can now run `package` ahead of `provision`, if desired) but I don't think that they need to see command output for `package` here.

The user should only have to care about `package` if they _need_ to care about `package`.
