### ISSUE TITLE
[onboarding experience improvement] Region capacity check

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#191]
After region is selected check if:

availability - region is too busy to create cosmo db account

**Comment by ellismg** [comment]
I really hope we can leverage ARM primitives here - the problem of "will this deployment succeed or hit capacity issues" is not a problem specific to `azd` - anyone using ARM Deployments can hit this same issue and so I hope we can minimize the amount of `azd` specific work we do here.

Depending on how we solve this - it may have deep implications on Pulumi and Terraform support.

**Comment by puicchan** [comment]
This issue surfaced again for the unmoderated getting started with azd study conducted in Q4 2022. 2 out of 8 customers encountered this issue.  	Quote from user study: "I chose the wrong.. I am having issues with the region. It doesn't give me a lot of detail."

**Comment by puicchan** [comment]
Also, the error message for one of the customers - pretty "messy"
![image](https://user-images.githubusercontent.com/8701892/212113872-5f5a21e8-1682-4f57-bb9b-2a18302693d9.png)

**Comment by savannahostrowski** [comment]
Related to #468

**Comment by savannahostrowski** [comment]
I'm going to close this in favour of #468 since there's considerable overlap.

**Comment by savannahostrowski** [comment]
Important for: https://github.com/Azure-Samples/azure-search-openai-demo/pull/252
