### ISSUE TITLE
Prompt for bicep required param if there but empty

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#1910]
When running `azd provision` we only prompt for required params if the param doesn't exist in bicep params file.  

I would like to be prompted for the value if the param exists in bicep params file, but is empty.

This is going to help because right now we have to ask the user to first create an environment with azd env new, then azd env set for that value.  

With this change we can just ask the user to run `azd provision`

I also think we should persist what they enter into the .env file.

**Comment by vhvb1989** [comment]
> I also think we should persist what they enter into the .env file.

azd ask customer if they want to persist the value for future runs

**Comment by vhvb1989** [comment]
> but is empty.

What if I want to set an empty string?   Or do you mean that the env var is not set/found within system env?

**Comment by jongio** [comment]
Prompt if **required** param isn't provided, not in params file, or empty.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 is this still valid? given we have native prompting support?

**Comment by vhvb1989** [comment]
Fixed it already
