### ISSUE TITLE
Initializing service 'web', could not locate a dotnet project file for service web.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-dev#1911]
**Describe the issue:**
Must specify the language under `service` in `azure.yaml` file when executing `azd deploy`.
<img width="742" alt="image" src="https://user-images.githubusercontent.com/81678720/230867094-66231031-c679-423f-b9f5-2621504119fb.png">

**Repro Steps:**

1. azd init -t <template_name>
2. azd package
3. azd provision
4. azd deploy.

**Environment:**
OS: Windows
Template: savannahostrowski/terminal-personal-site
Azd version: azd version 0.8.0-beta.1-daily.2689578 (commit 3b28fc8f84717d732f646a3e3b9521204f122112)

**Expected behavior:**
Executing `azd deploy` can pass.

**Notes:** this issue not appeared in 0.7 beta version of azd.

@rajeshkamal5050, @savannahostrowski for notification.

**Comment by savannahostrowski** [comment]
Yeah - this is my project and it's sort of a hack right now as we don't support `language: none`. In previous versions, I was able to omit the language property have azd just work when targeting ACA. I'm going to close this in favour of #1645.

I've fixed the template by using another language (another hack).

**Comment by savannahostrowski** [comment]
do
