### ISSUE TITLE
Fail to pacakge service  in Windows

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#1913]
**Describe the issue:**
Fail to pacakge service with `todo-nodejs-mongo-swa-func` and `todo-csharp-sql-swa-func`  in Windows , when run `bash ./test-templates.sh -c false -t template-name -b staging `. But run `azd init -t template-name -b staging` > `azd package` >`azd provision` > `azd deploy` , it can work normally.

The error message as follows:
![image](https://user-images.githubusercontent.com/80496810/230880391-326321bf-2171-4241-b91f-d24d665fff14.png)

**Repro steps:**
1. Run command `azd login`.
2. Run command ` bash ./test-templates.sh -t template-name -b staging`

**Environment:**
OS: Windows desktop.
Template: todo-nodejs-mongo-swa-func, todo-csharp-sql-swa-func
Azd version: 0.7.0-beta.2-daily.2681609  (commit https://github.com/Azure/azure-dev/commit/81b97e0268a78c521ef0017c5c9531c4ba7e0399)

**Expected behavior:**
`bash ./test-templates.sh -t template-name -b staging ` can pass.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@wbreza can you take a look? Is this a blocker for 0.8?

**Comment by wbreza** [comment]
@v-jiaodi can you provide more information on the actual error message? You mentioned this repros for both `node` and `csharp` `swa-func` templates however the API packaging error message would be totally different for each since one runs `node` and the other `csharp`?

**Comment by wbreza** [comment]
Turns out that this was effecting all templates that used Node JS for the backend API server and could be easily reproduced by running `azd package api` and did not only fail during template tests.
