### ISSUE TITLE
Improve error message on `azd up` in empty dir

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#1919]
Running azd up on an empty directory (pre-init) yields this error:
![image](https://user-images.githubusercontent.com/8949415/230998070-436c97d0-3fee-4508-b7a9-d83505f7a5af.png)

We should improve this. The first part of the error message seems good but the second bit about service name is confusing.

Note that this is on 0.8.0 (azd version 0.8.0-beta.1-pr.2687840 (commit a4f6a60a52ac5f8efa6243d2c0527f0dfc9c4a3c))

**Comment by weikanglim** [comment]
@savannahostrowski I think you may have created an `azure.yaml` somewhere in `/c/Users/sostrowski`

Here's what I get with `azd up`:

```pwsh
PS D:\tmp\empty> azd up
Error: no project exists; to create a new project, run `azd init`
PS D:\tmp\empty> azd version
azd version 0.8.0-beta.1 (commit 08209da7c22d28c6a123ef4e88d433132066b800)
```

Here's what I get after running `azd init` inside `d:\tmp`:

```pwsh
PS D:\tmp\lol> azd up

Packaging services (azd package)


ERROR: current working directory is not a project or service directory. Please specify a service name to package a service, or specify --all to package all services
```

**Comment by savannahostrowski** [comment]
Lol, yes...we really need to address #1638 so I stop doing this.

I'll close this :)
