### ISSUE TITLE
[Issue] secretOrRandomPassword generates strings that start with numbers

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#1939]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

azd version 0.8.0-beta.1 (commit 08209da7c22d28c6a123ef4e88d433132066b800)

**Describe the bug**
Description of issue you're seeing...

secretorRandomPassword generated a string with numbers in front, and I was trying to use it for a PostgreSQL admin user name, but that's not allowed:

"InvalidUserName: Admin username cannot start with numbers and must only contain characters and numbers."

So I will either prefix it or not use secretOrRandomPassword.

I think it's fine that secretOrRandomPassword puts numbers in front, but the problematic aspect is that it doesn't *always* do that, as far as I can see, as I've successfully deployed this in the past. That could lead people to think their infra is correct but then be unable to use it sometimes.

**To Reproduce**

This was when 'azd up'ing on https://github.com/pamelafox/django-quiz-app
You'd need to try multiple times since it's random!

**Comment by rajeshkamal5050** [comment]
Update the known issues/FAW to update the workaround using prefix.

**Comment by gkulin** [comment]
documented: https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/faq#what-is-the-behavior-of-the--secretorrandompassword--function
