### ISSUE TITLE
az deploy results in: panic: Task error has already been set! Task cannot have both a result and an error.

### ISSUE THREAD

**Issue by EverybodyKurts** [Azure/azure-dev#1944]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

```bash
% azd version
azd version 0.8.0-beta.1 (commit 08209da7c22d28c6a123ef4e88d433132066b800)
```

**Describe the bug**

Running `azd deploy` results in a panic along with a short stack trace:

```bash
% azd deploy

Deploying services (azd deploy)

  |=====  | Deploying service webApp (Copying deployment package)Executing predeploy hook => /var/folders/c4/kx9yp81s3vb166xy0qy6_hmw0000gq/T/azd-predeploy-237170854.sh
  |===    | Deploying service webApp (Fetching endpoints for static web app)panic: Task error has already been set! Task cannot have both a result and an error.

goroutine 105 [running]:
github.com/azure/azure-dev/cli/azd/pkg/async.(*TaskContext[...]).SetResult(...)
        /Users/runner/work/1/s/cli/azd/pkg/async/task_context.go:36
github.com/azure/azure-dev/cli/azd/pkg/project.(*staticWebAppTarget).Deploy.func1(0xc00031c690)
        /Users/runner/work/1/s/cli/azd/pkg/project/service_target_staticwebapp.go:146 +0x918
github.com/azure/azure-dev/cli/azd/pkg/async.(*TaskWithProgress[...]).Run.func1()
        /Users/runner/work/1/s/cli/azd/pkg/async/task.go:144 +0x11d
created by github.com/azure/azure-dev/cli/azd/pkg/async.(*TaskWithProgress[...]).Run
        /Users/runner/work/1/s/cli/azd/pkg/async/task.go:140 +0x1cf
```

**To Reproduce**

I can successfully run `azd provision` to provision the static web app. My azure yaml is as follows:

```yaml
name: myapp
services:
  webApp:
    project: ./webapp
    language: ts
    host: staticwebapp
    hooks:
      predeploy:
        shell: sh
        run: vite build
pipeline:
  provider: azdo
```

Let me know what else I need to include :)

**Expected behavior**

Either successfully deploy the static web app **or** give a more descriptive error message.

**Comment by vhvb1989** [comment]
@EverybodyKurts, can you try changing the `prebuild` hook to `prepackage` ?

I think you are expecting `vite` to build and produce some output which is then used by the `deploy` operation.  From azd version >= 0.8.0, you would need `prepackage` for that.

anyway, azd needs to improve this error here, and do not panic...  but this updating the hook might help you in case you are blocked
