### ISSUE TITLE
Introduce "dry run" option for provision and deploy commands

### ISSUE THREAD

**Issue by karolz-ms** [Azure/azure-dev#195]
Azure CLI, and many other CLI tools that allow for cloud resource deployments, have "dry run" mode, that validates the deployment, but stops short of creating actual cloud resources. We should introduce a similar mode for AZD. 

In particular, it would be useful for the dry-run mode to expose the final result of Bicep/Terraform build process, including results of parameter substitution and name/unique suffix generation. This will help developers troubleshoot deployment issues.

**Comment by jongio** [comment]
note: ARM has 'what-if' command that could be used for this.

**Comment by savannahostrowski** [comment]
Related to what @vhvb1989 is starting to take a look at with #141
