### ISSUE TITLE
[Issue] Reference is outdated, incompatible with 0.8 changes

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#1955]
**Describe the bug**
Description of issue you're seeing...

https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/reference#synopsis
says

azd up –-template todo-nodejs-mongo

That won't work anymore. There may be other parts of the reference as well that are out of date.

**Comment by gkulin** [comment]
thanks for calling this out @pamelafox !

**Comment by gkulin** [comment]
pr to fix: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4400
