### ISSUE TITLE
[Issue] Latest azd is built with go 1.20.0 from February, instead of latest 1.20.3

### ISSUE THREAD

**Issue by jakebailey** [Azure/azure-dev#1969]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here: azd version 0.8.0-beta.1 (commit 08209da7c22d28c6a123ef4e88d433132066b800)

**Describe the bug**

Running:

```sh
$ go version $(which azd)
/usr/local/bin/azd: go1.20
```

This version of go corresponds to the version of go released a few months ago; the latest is go1.20.3:

```sh
$ go version
go version go1.20.3 linux/amd64
```

**To Reproduce**

Install azd via the install instructions, check the version it's built with.

**Expected behavior**

Building from source, I get:

```sh
$ go version ./azd
./azd: go1.20.3
```

I did a quick scan and found: https://github.com/Azure/azure-dev/blob/main/eng/pipelines/templates/steps/setup-go.yml#L2

I have no idea what "GoTool@0" does, but it's possible it's not smart enough to pull in a new patch version (compared to the GHA `setup-go` which special cases this).

**Comment by ellismg** [comment]
The source for this task lives here: https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/GoToolV0.  Looking at the source, it looks like the default version is set to 1.10.0 and does not automatically role forward across patch versions.  It also appears that it doesn't support something like `1.10.x` (as some of the other tool fetching tasks do), so I guess we'll just have to manually move this along for now by explicitly setting the version property.

Just wondering - was there something specific from 1.10.2 that caused you to open this, or just a hygiene issue you noticed?

**Comment by jakebailey** [comment]
Just something I noticed while testing and I was asked to file it; it's a pretty common issue when publishing Go binaries so I tend to check it.
