### ISSUE TITLE
Unable to select template from vscode

### ISSUE THREAD

**Issue by smas1** [Azure/azure-dev#1979]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-dev.commands.cli.init
Error type: 1
Error Message: Process 'azd template list --output json' exited with code 1
Error: 'azd' is not recognized as an internal or external command,
operable program or batch file.

Version: 0.5.0
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.77.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.js:2:915195
```

</details>

**Comment by bwateratmsft** [comment]
@smas1 do you have the Azure Dev CLI installed?

**Comment by savannahostrowski** [comment]
Closing this as we haven't heard from the author in about two weeks. Please reopen if there are more details you can share!
