### ISSUE TITLE
Installer telemetry

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#1986]
Know installer channel

MSI -- Parameter to MSI that lays on the machine metadata to be included in telemetry (writes in the registry) ... Also, a file could be possible (and fewer code paths)

RPM/DEB -- Write to a file near the executable

Brew -- Write to a file near the executable

Install .sh script -- Write to a file near the executable

File name: `.installed-by.txt` (on Windows: hidden file)

**Comment by savannahostrowski** [comment]
What's left here? Is this required for 5/9 or just GA? I'm going to move it to GA release milestone but chime in if you disagree.

**Comment by danieljurek** [comment]
Instead of putting all changes into a single PR we could just release the MSI changes (already checked in), the winget/choco changes (pretty trivial), and the changes to `azd`. 

This will give us some data right away and smooth the path for the install scripts (on which I'm doing a small refactor that is receiving the bulk of review comments)

**Comment by danieljurek** [comment]
This PR contains that minimal set of changes: https://github.com/Azure/azure-dev/pull/2099
