### ISSUE TITLE
[Issue] New directories/files don't appear after running `azd env new` in VSCode until reloading window

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#199]
I believe this could be an issue with VSCode's file watching?

Right now, if you run `azd env new` you won't see the newly created files/directory for your environment until you reload the window or end the session and reopen VSCode.

**Comment by karolz-ms** [comment]
What files are you expecting to see?

**Comment by savannahostrowski** [comment]
I'd expect that a new subdir is added to my .azure/, reflecting the new environment that was created.


This happens with `azd init` as well.  In the case of `azd init`, I'd expect that I have an new azure.yaml file, .azure directory with a subdir (name reflecting the environment name I entered). 

Right now, I am only seeing those appear after reloading the window.

**Comment by savannahostrowski** [comment]
I can't repro anymore.
