### ISSUE TITLE
Deploying service api failed when using  todo-nodejs-mongo-aks template 

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#1992]
**Describe the issue:**
Failed to deploy service api Whe run ` bash ./test-templates.sh -t todo-nodejs-mongo-aks -b staging`.

The error message as follows:
![image](https://user-images.githubusercontent.com/80496810/233313744-dae8c8c6-4d84-484f-a1b6-6a036b7ed5c4.png)

**Repro steps:**
1. Run command `azd auth login`.
2. Run command ` bash ./test-templates.sh -t todo-nodejs-mongo-aks -b staging`

**Environment:**
OS: MacOS desktop, Linux desktop,  WSL, DevContainer in VS Code,CodeSpace.
Template: todo-nodejs-mongo-aks
Azd version: 0.8.0-beta.2-daily.2713284  (commit https://github.com/Azure/azure-dev/commit/cb28058af1e7139be4381532f6b1167d9cd948fb)

**Expected behavior:**
`bash ./test-templates.sh -t todo-nodejs-mongo-aks -b staging` can pass.

@rajeshkamal5050 for notification.

**Comment by wbreza** [comment]
Not able to reproduce.  The template provisioned & deployed without issue in Windows & WSL.

Note: If running on an MSFT internal azure subscription the tests will fail because of VM based networking restriction put in place.



![Image](https://user-images.githubusercontent.com/6540159/233443423-078f92d7-3a53-46e5-ae57-e2cafeb9bfcb.png)

**Comment by v-jiaodi** [comment]
When not using the MSFTVPN network, the following error occurs：
![image](https://user-images.githubusercontent.com/80496810/233588558-6b9ff296-6441-428b-8907-d162bde96e34.png)

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 This issue also occurs in the following cases:


- OS: WSL, Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code, Codespaces
- Template: todo-nodejs-mongo-aks
- Branch: Staging
- Azd version: 0.8.0-beta.3-daily.2760917  (commit https://github.com/Azure/azure-dev/commit/2201b16963dc43ae045c52374c0dd395152cb309)

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 This issue also occurs in the following cases:


- OS: WSL, Windows desktop, MacOS desktop, Linux desktop, Devcontainer in VS Code, Codespaces
- Template: todo-nodejs-mongo-aks
- Branch: Staging
- Azd version: 0.8.0-beta.3-daily.2763383  (commit https://github.com/Azure/azure-dev/commit/3f484a283b309b3cab6f91386a4a7af7f4a082a2)
