### ISSUE TITLE
Failed to `azd auth login`  on Windows

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#1994]
**Describe the issue:**
Failed to `azd auth login` When using MSFTVPN network  on Windows

The error message as follows:
![image](https://user-images.githubusercontent.com/80496810/233331927-6260d469-9165-4cc0-8595-998820fbf5be.png)

In addition, when not using VPN, it can work normally
**Repro steps:**
1. Run command `azd auth login`.

**Environment:**
OS: Windows
Template: all templates.
Azd version: 0.8.0-beta.2-daily.2713284  (commit https://github.com/Azure/azure-dev/commit/cb28058af1e7139be4381532f6b1167d9cd948fb)

**Expected behavior:**
 `azd auth login ` can pass on Windows.

@rajeshkamal5050 for notification.

**Comment by weikanglim** [comment]
Not a blocker. The DNS lookup for "localhost" when MSFTVPN was enabled. I have not seen this behavior.

@v-jiaodi 

Does it reproduce consistently?

**Comment by v-jiaodi** [comment]
When executing `nslookup localhost` in a cmd shell, get the message as follow:
![image](https://user-images.githubusercontent.com/80496810/233528003-2622837f-f374-4fce-bf96-4a02032b45bc.png)

**Comment by msiemon** [comment]
I have the same issue on Windows 11. I was able to work around it with:
auth login --use-device-code false
