### ISSUE TITLE
[Issue] Change `managedIdentity` field in containersApps template to `managedIdentityEnabled`

### ISSUE THREAD

**Issue by mukundansundar** [Azure/azure-dev#2019]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

**Describe the bug**
Description of issue you're seeing...

**To Reproduce**
Steps to reproduce the behavior...

**Expected behavior**
It is better to have `managedIdentityEnabled` as an input param name for containers-apps core template instead of managedIdentity. Additionally these changes would need to be made in all places where the template is used as well as terraform templates. 

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**
Based off of this comment https://github.com/Azure/azure-dev/pull/1958#discussion_r1171810487

**Comment by rajeshkamal5050** [comment]
@wbreza is this handled as part of your managed-identity aca changes?
