### ISSUE TITLE
Advance Terraform to Beta/Public Preview

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#2035]
azd init on a tf template

i was asked to enable alpha.terraform.

i shouldn't be asked to enable terraform when using a terraform template...or at all.

![image](https://user-images.githubusercontent.com/2163001/234730057-8e68f474-23a8-495c-9f9e-9b3734ec698d.png)

**Comment by savannahostrowski** [comment]
Moving this to Ge based on ADE convos
