### ISSUE TITLE
[Issue] up auth flow issues

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#2037]
When I run azd up, it asks for env name, then fails and says I need to login.

It feels like it is interrupting my flow.

I would rather it tell me I need to login before asking me to do anything else.

I would also like it to auto log me in and make it interactive, so I don't need to run another command to login and then come back and run azd up again.

**Comment by weikanglim** [comment]
The auto login feedback is definitely noted. We've received multiple feedback on that front. It's a feature request tracked in #1391. We'll fix the login check in this issue.
