### ISSUE TITLE
[Issue] Property module is not allowed?

### ISSUE THREAD

**Issue by manekinekko** [Azure/azure-dev#2039]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
`azd version 0.8.0-beta.2 (commit 429b6ccf9a9d1616efa8988f2f8561deeb464c71)`

**Describe the bug**
Property `module` is flagged as invalid by the language server in vscode. However, removing this property and running `azd deploy` throws the following error:

![image](https://user-images.githubusercontent.com/1699357/234982226-ee4cf9b2-6c18-43c0-8edd-55a5c64c4b8d.png)
![image](https://user-images.githubusercontent.com/1699357/234982760-305d8285-5842-4129-8f99-e100c39ec3b4.png)

**To Reproduce**
- create an `azure.yaml` file with a service that uses the `module`  property
- open `azure.yaml` in vscode
- notice validation error
- remove `module` property from `azure.yaml`
- run `azd up`.
- notice error.

**Expected behavior**
Property `module` should not be wrongly flagged as not allowed.

**Additional context**
Adding the `module` property back, and ignoring the language server error, works as expected.

VSCode version:
```
Version: 1.78.0-insider (user setup)
Commit: d6290ef6582acecbf3bca1558111f2ee64375801
Date: 2023-04-27T05:20:48.295Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22624
Sandboxed: Yes
```

**Comment by wbreza** [comment]
This property will be deprecated in a future release.  Resolved with #2047 for now.
