### ISSUE TITLE
`azd pipeline config` support for different branches

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#2040]
As a user, I should be able to run `azd pipeline config` to configure the Azure connection for different branches. The branch-specific behavior may be specific to federated credentials.

I want to be able to do this to configure CD for my mainline branch that is not `main`, or potentially other release servicing branches.

See original comment [here](https://github.com/Azure/azure-dev/pull/2029#discussion_r1178214371)

**Comment by vhvb1989** [comment]
My 2 cents:
   Let `azd` to be an example for how to set up a reference pipeline, but not as the tool you need to use for setting up all your pipelines. 
   In this case, for example, supporting multiple branches would require to create a group of secrets per branch so I could use `azd` for 3 different branches and each pipeline could have its own env values (secrets).  This complicates things IMO.

**Comment by jongio** [comment]
I would like azd to help me create the FIC for the branches I want the action to run on.  It could look at my default gh action, see which branches I have listed there, and then create FICs for each branch.  As it is now, I need to figure out how to create my own FIC.

**Comment by wbreza** [comment]
@weikanglim / @jongio - I believe this PR #2468 should solve the concern issue here.
