### ISSUE TITLE
`azd env refresh` fails to refresh all the environment variables when running in Codespaces

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#2042]
**Repro steps**

- deploy an azd template locally. Push the repo to GitHub.
- in Codespace, run `azd env refresh` by providing the existing environment name, subscription and location.

Expected to see all environment variables restored in .env file of the environment. 

**Actual**: I only get environment name, sub and location. Other environment variables like service end points etc. are all missing. **I can restore all environment variables when running in VS Code (local install)**

**Comment by weikanglim** [comment]
@puicchan Double-checking the expectations here:

Do you mean all variables from deployments (as `azd env refresh` currently advertises)?

Or do you mean all variables, including ones you had set using `azd env set`?

**Comment by puicchan** [comment]
What I need to be able to see the tree view in workspace really. I believe though if you do `azd env set`, it will be added to the .env file.

**Comment by weikanglim** [comment]
Do you believe if `azd env refresh` should then recover the values from `azd env set` on a different machine?

**Comment by puicchan** [comment]
The scenario is to make sure one can go from having the app deployed via CI and then be able to continue development on local dev box. If the value is needed so that it's possible to provision and build the app then yes. Else no. @savannahostrowski, @karolz-ms to chime in.

**Comment by vhvb1989** [comment]
> The scenario is to make sure one can go from having the app deployed via CI and then be able to continue development on local dev box.

I love it!  but we have some challenges to get there.  For example:
- A secret-value from CI can't be retrieved/read outside a CI pipeline (like querying the value from another PC).  The secret can be set again (override) only.  This means, if you set one env var for your CI and you want to restore the azd env with that value, we can't, we need something else to store the value and be able to restore it.

One option could be to make azd to support using an Storage account or Key Vault as the place to save the azd environment (instead of locally).  But this a new feature (and not a simple one)

**Comment by vhvb1989** [comment]
@rajeshkamal5050 , let's talk about this issue, I don't think it is a bug but a feature-request.

The only thing I believe we can do for May is to define the current boundaries from `azd env refresh`, which is:
   To restore azd env variables which were part of a provision output and are saved as tags within the Azure resources

**Comment by puicchan** [comment]
@vhvb1989, the issue is now I can get most if not all env variables when I run `azd env refresh` in VS Code (local install) but when I do that in CodeSpaces, I can't. All I get in .env file is env name, sub and location which are the input parameters. I have updated the issue to make this clear.

**Comment by vhvb1989** [comment]
reviewed it next to @puicchan and the issue is no longer seen
