### ISSUE TITLE
'Show Azure resource ' fail to expand the container app environment and show the container app

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#2043]
**Repro steps**
1. `azd up` any azd template that deploys to ACA
2. In Azure (resource) -> workspace view, right click any service and select "Show Azure resource`

Expected:
- the correct container environment expanded and the corresponding container app is showed 

Actual:
- nothing happens.

**Comment by karolz-ms** [comment]
This is an external issue in the Azure resource group extension; there is nothing to do on the AZD extension side.

**Comment by savannahostrowski** [comment]
@karolz-ms I filed a similar issue awhile back that @bwateratmsft transferred to the Azure resource group extension's repo. Not too sure what happened to it. If you have access to their repo/know what their repo name is (I don't :) ), would you mind linking it here? We can close this out - just want to be able to follow up.

**Comment by savannahostrowski** [comment]
May or may not be related to https://github.com/Azure/azure-dev/issues/1742

**Comment by savannahostrowski** [comment]
I'll close this for now and we can chase this upstream.
