### ISSUE TITLE
`azure.yaml` schema no longer includes `services.properties.modules` 

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2046]
It looks like somewhere along the way, we removed `module` as a valid property for services. This causes users to see a false positive diagnostic in their `azure.yaml` (I'm assuming it's false positive given that the product still works) in VS Code/Codespaces.

![image](https://user-images.githubusercontent.com/8949415/235028618-1cabd557-ed51-4bef-8484-8787234bab72.png)

To repro: 
- Clone any of our templates and open the azure.yaml (make sure you have the YAML Red Hat extension installed; I didn't so I hadn't seen this before).

**Comment by manekinekko** [comment]
Run into the [same issue](https://github.com/Azure/azure-dev/issues/2039) lately. Thanks @wbreza for the quick fix!
