### ISSUE TITLE
`azd config` is hard to use

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2051]
We should probably do an audit of `azd config` UX during Gallium.

Today, it's hard to know what you should pass into `azd config get`. The help text doesn't really give much insight into what the supported values are (e.g. properties in the `config.json` and the error message is too vague/not providing enough guidance.

**Comment by weikanglim** [comment]
There's a lot of things we can do here.

I would love to adopt VSCode's flattened JSON file format so that the user can easily change settings in the filesystem without going through the CLI.

And as you pointed out, there should be a gesture to display the allowed settings with their descriptions.

**Comment by vhvb1989** [comment]
> I would love to adopt VSCode's flattened JSON file format so that the user can easily change settings in the filesystem without going through the CLI.

I don't like when users can have access to application files. That's usually not a good idea.
If we want to go this path, I suggest using user-settings file per project.  Then, the global-azd app config is managed only by azd cli.  If user wants to use a manual file, they could create an azd.config file within a project to override the global settings.

**Comment by weikanglim** [comment]
> I don't like when users can have access to application files. That's usually not a good idea.

It's not the best idea for engineering and app owners, but it's worth it for the user. There's a reason why `git` supports both types of configurations.

> If we want to go this path, I suggest using user-settings file per project

Do you have current examples of why users might want this?

**Comment by savannahostrowski** [comment]
After chatting with @vhvb1989, we are going to:
1. Surface supported values in `azd config -h`
2. When a user passes in an unsupported value, the error will tell them to run help to view permissible options.

**Comment by savannahostrowski** [comment]
Can we add more details here about why this was moved?
