### ISSUE TITLE
`azd up` shows subcriptions when unauthenticated and `config.json` empty

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2054]
I'm testing out/documenting our commands and I got into a weird spot.

1. `azd config reset` 
2. Create a new dir, cd into it, run `azd init`, select template (I chose todo-python-mongo-aca; not that it matters?)
3. Run `azd up`

Notice that azd:
1. Shows you the list of your subscriptions 
2. Then shows an error telling me to authenticate/that it can't retrieve locations

I'm a bit confused because I'd assume that if my config is empty (which it is) and I'm not detected as authenticated that `azd up` should fail earlier and not show me any subs (because it doesn't have access to it?)
![image](https://user-images.githubusercontent.com/8949415/235261277-b3229ce4-2235-47d3-9b16-1e354677a5f3.png)

![image](https://user-images.githubusercontent.com/8949415/235261060-7cf857a4-0df7-4b90-9f3d-536465ac92df.png)

**Comment by vhvb1989** [comment]
Side effect of subscription cache on login + logout after config reset.
We have an issue to avoid logging out when calling azd config reset which should fix this issue as well.

@weikanglim should we delete subscription cache on config reset? It might be a way to re-list subscriptions without logging out. For example, if I am added to a new subscription, I could just reset azd config and the. i would see the new sub, with no extra login

**Comment by weikanglim** [comment]
I was talking to @ellismg and we are in agreement that we should fix #1721 which will fix the logout behavior. He's looking into that as a quick fix.

I also think that if we reversed the `azd up` prompt as suggested in #2037, the correct prompts would have been shown. I'm looking into this pretty immediately.

**Comment by savannahostrowski** [comment]
+1 one on both of these items. Thanks for jumping on this quickly!

**Comment by savannahostrowski** [comment]
@weikanglim Will this be addressed by #2059

**Comment by weikanglim** [comment]
@savannahostrowski I think it fixes the UX in the user flow. The new experience is that you get:

`ERROR: <maybe prefixed>: not logged in, run `azd auth login` initially, before any prompts.

And with #2071 (in-PR), `azd config reset` will no longer log you out.
