### ISSUE TITLE
Show template display names in `azd init` prompt

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#2057]
We'll want to rename the templates currently displayed in the `azd init` prompt to a user-friendly display name now that we have the capabilities to do so.

In the picture below, we want `todo-*` to have a different display name. The display name will still have the template name linked for ease of use when running `azd init --template <name>`

![image](https://user-images.githubusercontent.com/2322434/235265041-fdef1504-1fc1-4012-9955-56d115dfa352.png)

**Comment by weikanglim** [comment]
May be a good question to track here: How should the list be organized with the display names? What ordering should be impose?

**Comment by savannahostrowski** [comment]
I think ideally it's be something like alphabetical by programming language (front end lang first, api second).

Additionally, we should also update `azd template show` descriptions per @gkulin 's proposal (see #2063)

**Comment by savannahostrowski** [comment]
@weikanglim I think this is done now, yeah?

**Comment by weikanglim** [comment]
Yup; Closing
