### ISSUE TITLE
[Issue] Deployment errors - directory casing

### ISSUE THREAD

**Issue by Austinauth** [Azure/azure-dev#206]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
`version 0.1.0-beta.2 (commit 13ec2b11aa755b11640fa16b8664cb8741d5d300)`

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 
```
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

**Describe the bug**
The last few times I have attempted to deploy an app template using `azd up` I run into the error below:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/6994218/181643459-b97cc61d-c238-4dc5-ad7a-bbe966d478c6.png">

I'm not sure if this is due to something on my behalf or a bug with the tool.

**To Reproduce**
1. `azd up --template todo-nodejs-mongo`
2. Environment name: `res-demo`
3. Location: `46. (US) West US (westus)`
4. Subscription: _will share privately if needed_

**Expected behavior**
I expect the app to successfully deploy to azure.

**Environment**
Information on your environment:

<img width="163" alt="image" src="https://user-images.githubusercontent.com/6994218/181643828-36cbc61e-899d-4019-a605-c7c363f70bea.png">

**Comment by Austinauth** [comment]
**Update - 08/01/2022**

After further investigation @karolz-ms helped me determine that this issue is related to directory casing. When the entire directory path is in lowercase the issue goes away. 

In his words: _"Could you add this information to the issue (that it works if the local app folder is all-lowercase, and that it is, most likely, Windows-only issue)?_"

**Source of the problem as been identified, but it still likely need a fix.**

Teams discussion for more context:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/6994218/182252655-ca477d78-9b3f-4588-9453-2664d15bf9f1.png">

**Comment by savannahostrowski** [comment]
@Austinauth Is this still reproduceable?

**Comment by Austinauth** [comment]
@savannahostrowski I'm not sure, this bug is close to 9 months old. I haven't encountered it recently.

**Comment by savannahostrowski** [comment]
I can't repro it so I'll close for now and we can reopen if it pops up again!
