### ISSUE TITLE
Make it more clear what the user needs to pass in for `azd template show`

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2063]
<img width="607" alt="image" src="https://user-images.githubusercontent.com/8949415/235510203-3c71c800-9fd4-4e5e-ac79-2ce7bd892407.png">

Today, it's not really clear what a user needs to pass into `azd template show` (e.g. URL).

We should also revisit making this more valuable to the user (e.g. Update the template descriptions to reflect the local application stack).

**Comment by rajeshkamal5050** [comment]
Investigate on `azd template` commands to see if we need to hide some of them.

**Comment by savannahostrowski** [comment]
I am going to close this for now based on above changes
