### ISSUE TITLE
Make it clear `azd init` downloads codes as part of project initialization 

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#207]
We have added verbiage in Dev Hub to call out code is downloaded as part of `azd init`. 

Developers are still not aware of this.

Today, we say:
$ ~\repos\todo-app> azd init -t todo-nodejs-mongo
Initializing a new project in D:\temp\test2

Let's make it clear:
$ ~\repos\todo-app> azd init -t todo-nodejs-mongo
Initializing a new project and downloading code in D:\temp\test2

@Austinauth

**Comment by Austinauth** [comment]
I assume this message will also appear when running `azd up` during the `init` phase?

I have no issues pushing this verbiage change and seeing if it's enough to raise awareness. I also think we should continue to explore how we can make this clearer in the documentation and if there are any UX tweaks that might help.

**Comment by puicchan** [comment]
Yes, `azd up` includes running `azd init` so will apply to `azd up`.

And yes, we need doc update along with this as well. I just want to keep this to CLI update.

**Comment by Austinauth** [comment]
As part of #255 we are looking at how we can improve the messaging during `azd up`, this includes the `init` step. I will follow up with the outcome of that work once we've had a chance to discuss as a team this afternoon.

**Comment by rajeshkamal5050** [comment]
@puicchan Closing this one since the verbiage is captured as part of UX improvements issue
- #255 and its [figma prototype](https://www.figma.com/proto/iIRRiGPuKIfaSFfMJXcYle/azd-resource-provisioning?page-id=179%3A96561&node-id=207%3A97650&viewport=2107%2C1113%2C0.25&scaling=scale-down&starting-point-node-id=207%3A97650)
