### ISSUE TITLE
Improve the UX of provision/deploy in CI/CD

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2070]
Today, we render the progress spinners in CI/CD, which looks a bit rough. It'd probably even be nicer to just see "starting" "in progress" and "done" markers for each step instead.

![image](https://user-images.githubusercontent.com/8949415/235728797-cbe9e61c-97e4-46b5-89c5-5870c3c9cc66.png)

**Comment by weikanglim** [comment]
@vhvb1989 @ellismg 

1. Should we default `TerminalMode = yacspin.ForceNoTTYMode` (example in our codebase [here](https://github.com/Azure/azure-dev/blob/d8863e44c25bad9e52a5c6a1c0b042a52b81edde/cli/azd/pkg/input/console.go#L194)), if we are able to detect CI, reusing the telemetry detection logic [here](https://github.com/Azure/azure-dev/blob/d8863e44c25bad9e52a5c6a1c0b042a52b81edde/cli/azd/internal/telemetry/resource/exec_environment.go#L77)? This maybe means another env variable to 'unoverride' the behavior (can come later)
2. Or we could also update our default azure-dev.yml to set `AZD_DEBUG_FORCE_NO_TTY` (rename this var to maybe `AZD_FORCE_NO_TTY`)

**Comment by vhvb1989** [comment]
@weikanglim I would use both 1) and 2).
I would move 1) to the `main.go` and use it to set `AZD_RUNNING_ON_CI=true` during the execution of the command
Then we could also update telemetry to use `AZD_RUNNING_ON_CI` instead of doing 1) again.
Then we should update the console to check for AZD_RUNNING_ON_CI or AZD_DEBUG_FORCE_NO_TTY

That's my suggestion

**Comment by ellismg** [comment]
I much prefer just doing (1) right now.  I think it's a good pit of success and most folks won't want to revisit our decision in CI.  If it becomes an issue, we can either expose the knob as a config var or via `~/.azd/config.json`.

**Comment by weikanglim** [comment]
Looks pretty!
![image](https://github.com/Azure/azure-dev/assets/2322434/39695cff-2839-40e1-9d3f-9344f97eb716)

![image](https://github.com/Azure/azure-dev/assets/2322434/7ff20e92-7acb-4402-8cc9-38fb96eea69d)

**Comment by savannahostrowski** [comment]
Heck yes - this looks great!
