### ISSUE TITLE
Remove duplication between `RepositoryPath` and `Name` from `templates.json`

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#2075]
`RepositoryPath` and `Name` are currently duplicated in template metadata, see [here](https://github.com/Azure/azure-dev/blob/d2f4c44553fccfe105c69a7c763af80601c956dc/cli/azd/resources/templates.json#L3). Original comment [here](https://github.com/Azure/azure-dev/pull/2055#discussion_r1182033576).

We should reduce the contract surface area.

## Early Proposal

Remove `RepositoryPath` in favor of `Name`. Templates should have names. We can describe name simply as follows:

A template name is a fully qualified URI to a github repository, "{org}/{repo}" for GitHub repositories, or "{repo}" for GitHub repositories under Azure-Samples (default organization). 

Alternative naming: Use `Id` and `Title` similar to how NuGet [schema](https://learn.microsoft.com/en-us/nuget/api/registration-base-url-resource#catalog-entry). 

## Final Proposal

- Name - Human friendly name
- Path - The path to the template. Can either be a fully qualified URI to a github repository, "{org}/{repo}" for GitHub repositories, or "{repo}" for GitHub repositories under Azure-Samples (default organization). 
- Description (optional) - The long description of the template

**Comment by vhvb1989** [comment]
See this: https://github.com/Azure/azure-dev/pull/90

We used to have an issue some time ago where the `Name` was used to fetch the repo-path (as a result of using the Name for the Selection and loosing the path after selecting from the list).

This issue should be fixed now and Name and Path are still there with the same value,,, but the name can be updated to whatever we want to be the display name without affecting the path.

So, if you want, you can rename `name` to `Display name` to make it a better name :)  

But I don't think we need name and displayName

**Comment by weikanglim** [comment]
Packages, templates, artifacts should have names or IDs. Having "RepositoryPath" being the primary identifier disrupts the mental model for me. Perhaps I'm wrong here.

**Comment by vhvb1989** [comment]
it should not be the primary id.
the id should be the `name` , which can be the displayName as well. Unless there is a requirement for having both.
The way I would have it is:
- Name
- Path
- Description (optional)
- Order (optional)

The name is the key and the path is a required attribute.
Description can be used to created documentation or longer help notes about the template.
Order can be used to promote the template above others easily.  

I would also move the template list outside of the azd binary to be pulled from git repo, so it can be changed on demand

**Comment by weikanglim** [comment]
I do see the similarities between the proposed design and go modules, and it's worked out well there.

> I would also move the template list outside of the azd binary to be pulled from git repo, so it can be changed on demand

This is definitely on our plate, but we probably want to have proper feature design around there. This goes into indexing etc etc.
