### ISSUE TITLE
azd "restore" should unset NODE_ENV for JS projects

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#2076]
When running build-related tasks, NPM will NOT install `devDependencies` when `NODE_ENV=production`. This should only happen in the scope of those tasks. 

Log that we're unsetting `NODE_ENV` if we encounter `NODE_ENV=production` during build steps. 

We encountered this in CloudShell.

**Comment by weikanglim** [comment]
@danieljurek Can you clarify if you're ask is for `azd` to go above and beyond to warn for possible `npm` issues? We don't inject anything in `npm install` when running `azd restore`: [npm.go](https://github.com/Azure/azure-dev/blob/b42c228e28c58c7afa428b893e414cfe002090eb/cli/azd/pkg/tools/npm/npm.go#L73)

**Comment by danieljurek** [comment]
We're exploring whether `NODE_ENV` should be set in user sessions in CloudShell or if it's something we should consider setting during `bulid` ... 

If we did set it in `azd` we'd probably need to alert the user as to this fact as it could potentially change assumptions the user is making about their environment.

**Comment by danieljurek** [comment]
CloudShell is setting `NODE_ENV` in their environment to a value that isn't production. Once the change is rolled out broadly we can verify and close this issue.

**Comment by rajeshkamal5050** [comment]
@danieljurek can this be verified and closed
