### ISSUE TITLE
AZURE_RESOURCE_GROUP should be the first search-criteria during provision

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#2081]
Based on the comments from: https://github.com/Azure/azure-dev/blob/main/cli/azd/pkg/infra/azure_resource_manager.go#L207

when env var AZURE_RESOURCE_GROUP is set, it takes the last place during the resource group searching/resolving.

**Comment by asanjabi** [comment]
I ran into this when I was trying to override the RG for provisioning in a GitHub workflow, it is blocking two scenarios that I am working on:

- It is very common that a developer might have access to a specific RG for the project and the name might not necessarily match the naming pattern that azd uses by default.  
- In some cases such as multiple simultaneous pull requests, it makes sense to deploy the same environment into multiple RGs.

**Comment by weikanglim** [comment]
@asanjabi Do you have a specific error you would be willing to share? The code there is quite complicated, and there's actually another layer on top of it which seems like it would use `resourceGroupName` in `azure.yaml` or `AZURE_RESOURCE_GROUP` as the higher-order referencing. I will agree that all this behavior is quite confusing.

**Comment by asanjabi** [comment]
Hi Wei, you can take a look at the code I am working on here: https://github.com/Azure/reliable-web-app-pattern-dotnet/tree/asanjabi/workflow/.github/workflows.  I was trying to override the RG where the project gets deployed during the deployment pipeline, where .azure directory is not available, but was unable to do that by setting the `AZURE_RESOURCE_GROUP` environment variable unless there was and error.  For example if I have two RGs with the tag, then I am able to use the `AZURE_RESOURCE_GROUP` variable to point to the right RG.  (https://github.com/Azure/reliable-web-app-pattern-dotnet/blob/b3048455fe0e4ac4718c80ef855a62360abf6319/.github/workflows/deploy.yml#L85)

**Comment by ellismg** [comment]
A lot of this code has been refactored and cleaned up since this issue was opened.  I looked over what we have today and everything seems to be in order now.
