### ISSUE TITLE
azd login on github actions stopped working today

### ISSUE THREAD

**Issue by varndellwagglebee** [Azure/azure-dev#2091]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
github actions

**Describe the bug**
github action to login to azd..
Run $info = $Env:AZURE_CREDENTIALS | ConvertFrom-Json -AsHashtable;
  
Not logged in, run `azd auth login` to login to Azure.

**To Reproduce**
create a github action with the following step

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in with Azure (Client Credentials)
        run: |
          $info = $Env:AZURE_CREDENTIALS | ConvertFrom-Json -AsHashtable;
          Write-Host "::add-mask::$($info.clientSecret)"
          azd auth login `
            --client-id "$($info.clientId)" `
            --client-secret "$($info.clientSecret)" `
            --tenant-id "$($info.tenantId)"
        shell: pwsh
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS **}}**

**Expected behavior**
Expected to be login in with azd clie

**Environment**
Github actions

**Additional context**

**Comment by weikanglim** [comment]
@varndellwagglebee Can you post the output logs from the step that failed? Do make sure to sanitize any data that may be sensitive for you.

**Comment by vhvb1989** [comment]
@varndellwagglebee azd supports `Client Credentials` or `Federated Credentials`
Based on the issue description, it looks like you are using `Client Credentials`.

For Client Credentials, the common issues why login would start to fail in pipelines are:
- The ServicePrincipal was deleted from Azure Active Directory.
- The secret for the Service principal was updates/rotated, so the value in GitHub no longer match.
  - This could happen, for example, when using the same Service principal for two repositories.
- The secret for the Service principal had an expiration date and it became expired.

For Federated Credential, the common issues are:
- Changed the repository or branch name (fed credential is configured to match repo and branch name)
- Service principal deleted
- Fed Credential removed

**Comment by varndellwagglebee** [comment]
I ran azd pipeline config and it updated github withe the principle data.  Ran the workflow again and still not logging in..
I checked and the ServicePrinicipal is in AAD.

**Comment by varndellwagglebee** [comment]
I manually replaced all the secrets:  

2s
##[debug]Evaluating: secrets.AZURE_CREDENTIALS
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'AZURE_CREDENTIALS'
##[debug]=> null
##[debug]Result: null
##[debug]Evaluating condition for step: 'Log in with Azure (Client Credentials)'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Log in with Azure (Client Credentials)
##[debug]Loading inputs
##[debug]Loading env
Run $info = $Env:AZURE_CREDENTIALS | ConvertFrom-Json -AsHashtable;
##[debug]pwsh -command ". '/__w/_temp/fd54a3e7-[1](https://github.com/Matri-Design-LLC/Matri.GlyphEditor/actions/runs/4897063448/jobs/8744653304#step:4:1)a05-48f6-a7c0-5396[2](https://github.com/Matri-Design-LLC/Matri.GlyphEditor/actions/runs/4897063448/jobs/8744653304#step:4:2)ad6fdd[3](https://github.com/Matri-Design-LLC/Matri.GlyphEditor/actions/runs/4897063448/jobs/8744653304#step:4:3).ps1'"
Warning: Can't add secret mask for empty string in ##[add-mask] command.
Error: flag needs an argument: --tenant-id
Error: Process completed with exit code 1.
##[debug]Finishing: Log in with Azure (Client Credentials)

**Comment by vhvb1989** [comment]
@varndellwagglebee 

just noticed in the issue description you have

```
env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS **}}**
```

is the `**}}**` a typo for when you created the issue?  or is this also in your code?

**Comment by vhvb1989** [comment]
@varndellwagglebee can you also share how you ran `azd pipeline config` ?  what arguments did you use?

**Comment by varndellwagglebee** [comment]
I ran the config from vs code menu.  the env is just from when the issue was created.  here are my env items

APPLICATIONINSIGHTS_CONNECTION_STRING="InstrumentationKey=5f41d059-2bc7-462e-a9af-fbf701868282;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/"
APPLICATIONINSIGHTS_NAME="appi-3hmn6weg7opbk"
AZD_PIPELINE_PROVIDER="github"
AZURE_CONTAINER_ENVIRONMENT_NAME="cae-3hmn6weg7opbk"
AZURE_CONTAINER_REGISTRY_ENDPOINT="cr3hmn6weg7opbk.azurecr.io"
AZURE_CONTAINER_REGISTRY_NAME="cr3hmn6weg7opbk"
AZURE_DATABASE_NAME="glypheditor"
AZURE_DATABASE_SERVER_HOST="psql-db-3hmn6weg7opbk.postgres.database.azure.com"
AZURE_DATABASE_SERVER_NAME="db-glypheditor"
AZURE_ENV_NAME="staging"
AZURE_KEY_VAULT_NAME="GlyphEditor-Staging"
AZURE_LOCATION="eastus"
AZURE_SUBSCRIPTION_ID="******"
AZURE_TENANT_ID="**********"
REACT_APP_WEB_BASE_URL="https://ca-web-3hmn6weg7opbk.wittystone-5f08ad6e.eastus.azurecontainerapps.io"
SERVICE_API_NAME="app-api-3hmn6weg7opbk"
SERVICE_WEB_NAME="ca-web-3hmn6weg7opbk"

**Comment by vhvb1989** [comment]
@varndellwagglebee , when you run `azd pipeline config` from vscode menu, you mean like:

![image](https://user-images.githubusercontent.com/24213737/236884516-03e2dbfb-7b0f-4313-930d-d8ee9f0e8dd0.png)

In that case `azd pipeline config` is invoked with default values, and the default for authentication is to use federated credential.
This means your pipeline definition should use the fed-credential step for logging.

In your initial logs, you mentioned you are using client-secret auth like

```
Log in with Azure (Client Credentials)
```

Try switching to:

```
      - name: Log in with Azure (Federated Credentials)
        if: ${{ env.AZURE_CLIENT_ID != '' }}
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh
```

**Comment by vhvb1989** [comment]
Can you tell what you mean by `azure developer profile config` ?

The fed-credential is to be used when azd is running within the GitHub action.  It can't be used for running locally.

I was referring to `.github/workflows/azure-dev.yml`  Can you share the content of that file?

**Comment by varndellwagglebee** [comment]
I right-clicked on the azure.yaml file and selected 
![azure](https://user-images.githubusercontent.com/117473104/236893636-ad5263b8-aa9f-4eb9-a738-0091750de30a.png)


here is my azure.yaml file:

# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: azure-remix-stack
services:
  web:
    language: ts
    project: "./src/web/GlyphEditor"
    module: app/web
    host: containerapp
  api:
    Language: csharp
    project: "./src/api/GlyphEditor/src/GlyphEditor"
    module: app/web
    host: appservice

Here is my github workflow file:

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read 

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in with Azure (Federated Credentials)
        if: ${{ env.AZURE_CLIENT_ID != '' }}
        run: |
            azd auth login `
              --client-id "$Env:AZURE_CLIENT_ID" `
              --federated-credential-provider "github" `
              --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Azure Dev Provision
        run: azd provision --no-prompt
        env:
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Dev Deploy
        run: azd deploy --no-prompt
        env:
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

**Comment by vhvb1989** [comment]
thank you @varndellwagglebee 

When you select `pipeline config` from the menu, a new command line is opened in VSCode with the log and progress

something like:
![image](https://user-images.githubusercontent.com/24213737/236952588-3ab21631-95cd-4766-9672-b5824ad1b744.png)


Can you share that log output please?

**Comment by varndellwagglebee** [comment]
Found the problem.  The federated account was pointing to the wrong branch in GitHub.  It seems when you run azd profile config, it assumes you want a branch named main.  We have Master.  Thank you for all your help.

Anyone else having this issue, go into Azure Portal, app registrations, and make sure your service principal for GitHub is pointing to the correct branch.
