### ISSUE TITLE
Cannot get to help topic for `azd init` if I run `azd init help` 

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#210]
azd version 0.1.0-beta.3 (commit 77ab01c3bcf40d12852d543506ecbb935a779f81)

It's standard convention to type `help` after a CLI command to see the help topic. If I type `azd init help`, I get:
 
D:\temp>azd init help
Initializing a new project in D:\temp

? Select a project template  [Use arrows to move, type to filter]
> Empty Template
  Azure-Samples/todo-python-mongo-swa-func
  Azure-Samples/todo-nodejs-mongo
  Azure-Samples/todo-python-mongo
  Azure-Samples/todo-csharp-cosmos-sql
  Azure-Samples/todo-nodejs-mongo-aca
  Azure-Samples/todo-python-mongo-aca

Expected result:
- see the help topic for `azd init`, same output as running `azd init --help`.

**Comment by karolz-ms** [comment]
> It's standard convention to type `help` after a CLI command to see the help topic. If I type `azd init help`, I get:

Hmm, not really. `--help`, yes, `-h` yes, even `-?` is common, but just the word "help" is too ambiguous (is it a file? is it a subcommand?).

For example (Azure CLI):
```shell
> az group help
'help' is misspelled or not recognized by the system.
```

**Comment by puicchan** [comment]
We are very inconsistent. `help` works for the azd and the group commands:
- env 
- infra 
- monitor
- config
- pipeline

**Comment by karolz-ms** [comment]
I see what you mean. What is happening is for commands that require a subcommand, if an invalid subcommand is provided, there is no error. Instead, `azd` just provides usage information. The latter part is not bad, but there should also be an error message telling the user that they provided an invalid subcommand. 

You will get the same effect if you provide any invalid subcommand name, not just `help`, e.g. `azd env whatever`

**Comment by puicchan** [comment]
I understand but we should be consistent.

**Comment by jongio** [comment]
I also see this with `azd deploy help`

```
D:\code\azure-dev>azd deploy help
Error: no project exists; to create a new project, run `azd init`.

D:\code\azure-dev>azd deploy -h
Usage of :
      --debug
      --help
2022/08/01 12:55:09 main.go:232: could not parse flags: pflag: help requested
Deploy the application's code to Azure.

When no `--service` value is specified, all services in the *azure.yaml* file (found in the root of your project) are deployed.

Examples:

        $ azd deploy
        $ azd deploy –-service api
        $ azd deploy –-service web

After the deployment is complete, the endpoint is printed. To start the service, select the endpoint or paste it in a browser. 

Usage:
  azd deploy [flags]

Flags:
  -h, --help             Gets help for deploy.
  -o, --output string    The output format (the supported formats are json, none). (default "none")
      --service string   Deploys a specific service (when the string is unspecified, all services that are listed in the azure.yaml file are deployed).

Global Flags:
  -C, --cwd string           Sets the current working directory.
      --debug                Enables debugging and diagnostics logging.
  -e, --environment string   The name of the environment to use.
      --no-prompt            Accepts the default value instead of prompting, or it fails if there is no default.

Please let us know how we are doing: https://aka.ms/azure-dev/hats
```

**Comment by savannahostrowski** [comment]
`help` no longer exists
![image](https://user-images.githubusercontent.com/8949415/231009205-bb74c1cb-92b6-47a0-8d52-337a15782af3.png)
