### ISSUE TITLE
[Docs] Improve clarity on pipeline config doc

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2106]
https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/configure-devops-pipeline?tabs=GitHub

Add details to pre-amble about what exactly the command does:
- Creates and configures the Service Principal on the Azure subscription
- If there is not a git repository configured, provides the needed mechanics to create/configure your repository as well as commit the code.
- Create a secure connection between Azure and your repository using GitHub secrets.
- Upon checking in the workflow file, runs the action.

A couple things we should make clearer:

That pipeline will not generate a pipeline for you
We currently say that all templates include GHA/AzDO pipeline definitions. That's true for our templates we've authored but won't be true for community authored templates
We should link or include example pipelines for GHA and AzDO inline in the doc. Right now we just link out to the repos we've authored.

**Comment by vhvb1989** [comment]
@savannahostrowski here is a document which might be helpful for this: https://github.com/Azure/azure-dev/blob/main/cli/azd/docs/manual-pipeline-config.md

**Comment by savannahostrowski** [comment]
Needed before content freeze

**Comment by gkulin** [comment]
addressed in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4456
