### ISSUE TITLE
[Docs] Add support page to DevHub

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2107]
Should include:
- Directing users to file issues on GitHub
- Explicitly call out anything is which will not be supported  
- Mention how VS Code extensions etc. are supported 
- Azd minimum version support  
- Azd dependency support

**Comment by alexwolfmsft** [comment]
Hey @savannahostrowski or @gkulin it looks like we already have this support page started that addresses some of these concerns: https://github.com/Azure/azure-dev/blob/main/SUPPORT.md

Can you provide additional information around what you'd like to see for these items:

* **Directing users to file issues on GitHub** - it looks like this one is mostly addressed in the support doc above.
* **Explicitly call out anything is which will not be supported** -  Can you provide clarity here? Listing things that are NOT supported seems very open ended unless you had a few specific items in mind you wanted to call out.
* **Mention how VS Code extensions etc. are supported** - Are you just looking for a link to the VS code extension with some general information?
* **Azd minimum version support** - Is this meant to describe the lowest version of azd that is supported for a given template, or what would you like to see here?
* **Azd dependency support** - Git is our only prerequisite at the moment, so are you looking for a minimum git version? This would probably change over time so we might want to think about how to keep that up to date.

**Comment by savannahostrowski** [comment]
Yeah so I think that CSS is requesting that we also have some version of this live on our official docs site. Looking around at other teams, it seems like they have something like https://learn.microsoft.com/en-us/azure/aks/aks-support-help. This would lead me to lean towards just updating our Troubleshoot doc with something like
![image](https://github.com/Azure/azure-dev/assets/8949415/af3c0971-4f01-4c96-836f-744f2b5bd7b2)

I think the big thing is that they want to see that we are properly directing users so they can ensure they are getting support.

**Comment by alexwolfmsft** [comment]
Thanks @savannahostrowski it looks like I might have been overthinking this - I'll get something like this added to the troubleshooting page. I already have a PR open with some other support related adjustments so I'll just add it to that.

**Comment by gkulin** [comment]
@alexwolfmsft we should also include with this that folks should go to GitHub for issues with the VS Code extension too

**Comment by savannahostrowski** [comment]
Needed before content freeze
