### ISSUE TITLE
[Docs] Add link to support page in other sub pages on DevHub

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2108]
We should link to the page created via #2107 at the bottom of most pages (especially how to guides, troubleshooting and FAQ) so that folks are directed to GitHub

**Comment by rajeshkamal5050** [comment]
@savannahostrowski @ellismg should we also reference this `support page` when there are `azd runtime/execution errors`?

**Comment by savannahostrowski** [comment]
If the user is starting in azd and encounters a runtime/execution error, I'd expect that we should just directly point them to GitHub.

This doc is for folks who might go searching for help on DevHub. We want to route them to GitHub.

**Comment by savannahostrowski** [comment]
Needed before content freeze
