### ISSUE TITLE
az dev deploy reporting misleading errors when I tried to deploy to an environment that has not been provisioned

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#211]
azd version: azd version 0.1.0-beta.3 (commit 77ab01c3bcf40d12852d543506ecbb935a779f81)

Repro steps:

1. install latest version of azd
2. Create 2 environments. env1 - provisioned and deployed. env2 - initialized but not provisioned
3. make sure current working environment is env2
4. azd deploy

Expected:
Hint like "Have you provisioned the resources by running `azd provision`?" is more actionable. 

Actual error returned:
Deploying service api
Error: deploying service: deploying service api package: deploying service api: failed running az deployment source config-zip: exit code: 3, stdout: , stderr: WARNING: Getting scm site credentials for zip deployment
ERROR: (ResourceGroupNotFound) Resource group 'dev-rg' could not be found.
Code: ResourceGroupNotFound
Message: Resource group 'dev-rg' could not be found.

**Comment by puicchan** [comment]
@Austinauth for input.

**Comment by Austinauth** [comment]
@puicchan

@savannahostrowski and I have a general issue created to investigate Error state UX (see: https://github.com/Azure/azure-dev/issues/243). I will add this to the list of examples we've captured in that issue. 

Error and warning states are something we want to start taking a more wholistic approach to. Ideally we can create a few reusable and actionable patterns.  I will be looking at this more in-depth this week and next.

**Comment by savannahostrowski** [comment]
I think that this is resolved now
![image](https://github.com/Azure/azure-dev/assets/8949415/c661b430-d379-4992-b875-314e1b641e41)
