### ISSUE TITLE
[Feature request] Support GitHub container registry as a container target

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#2110]
Currently, the aca build mechanism can push images to Azure Container Registry and then use those images for the Azure Container App image.

It would be great if it could also push images to GitHub Container Registry, which is a more affordable option for low levels of traffic. That would also make azd a more viable option for ACA workshop attendees, since they wouldn't need to worry about accruing ACR costs (as ACA is consumption-based).

cc @asw101 who has also thought about this and may be able to provide more technical details about GHCR usage.

**Comment by savannahostrowski** [comment]
Yeah - this is a great feature request. I'd be nice to give folks the option. I'll move to Gallium for us to investigate what this would take.

**Comment by rajeshkamal5050** [comment]
Moving this to Germanium @savannahostrowski

**Comment by rajeshkamal5050** [comment]
@wbreza has added support for it [Adds support for external container registries #3450](https://github.com/Azure/azure-dev/pull/3450) in the upcoming 1.7.0/March release.
