### ISSUE TITLE
Failed:  Deploying service web

### ISSUE THREAD

**Issue by varndellwagglebee** [Azure/azure-dev#2118]
Bicep version
0.16.2

Describe the bug

Deploying services (azd deploy)

(x) Failed: Deploying service web

I confirmed that Docker does have an 18-bullseye-slim manifest.

ERROR: failed building service 'web': failing invoking action 'build', building container: web at .: building image: exit code: 1, stdout: , stderr: Dockerfile:2
--------------------
   1 |     # base node image
   2 | >>> FROM node:18-bullseye-slim as base
   3 |     
   4 |     # set for base and all layer that inherit from it
--------------------
ERROR: failed to solve: node:18-bullseye-slim: no match for platform in manifest sha256:2ff9841de879f1a2d2d8ef83183c2d93435c451a36d6cfb37b3331d1386c00f8: not found
: exit code: 1, stdout: , stderr: Dockerfile:2
--------------------
   1 |     # base node image
   2 | >>> FROM node:18-bullseye-slim as base
   3 |     
   4 |     # set for base and all layer that inherit from it
--------------------
ERROR: failed to solve: node:18-bullseye-slim: no match for platform in manifest sha256:2ff9841de879f1a2d2d8ef83183c2d93435c451a36d6cfb37b3331d1386c00f8: not found
: exit status 1

To Reproduce

1.  ran provision from VS Code
2.  ran Deploy: received error when selecting Deploy from the Azure.Yaml file

Additional context
Web.bicep

param name string
param location string = resourceGroup().location
param tags object = {}

param applicationInsightsName string
param containerAppsEnvironmentName string
param containerRegistryName string
param imageName string = ''
param serviceName string = 'web'

module app '../core/host/container-app.bicep' = {
  name: '${serviceName}-container-app-module'
  params: {
    name: name
    location: location
    tags: union(tags, { 'azd-service-name': serviceName })
    containerAppsEnvironmentName: containerAppsEnvironmentName
    containerRegistryName: containerRegistryName
    env: [
      {
        name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
        value: applicationInsights.properties.ConnectionString
      }
      {
        name: 'PORT'
        value: '80'
      }
      {
        name: 'NODE_ENV'
        value: 'production'
      }
    ]
    imageName: !empty(imageName) ? imageName : 'nginx:latest'
    targetPort: 80
  }
}

resource applicationInsights 'Microsoft.Insights/components@2020-02-02' existing = {
  name: applicationInsightsName
}

output SERVICE_WEB_IDENTITY_PRINCIPAL_ID string = app.outputs.identityPrincipalId
output SERVICE_WEB_NAME string = app.outputs.name
output SERVICE_WEB_URI string = app.outputs.uri
output SERVICE_WEB_IMAGE_NAME string = app.outputs.imageName
-- web.parameter.json

{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "location": {
      "value": "${AZURE_LOCATION}"
    },
    "name": {
      "value": "${SERVICE_WEB_NAME}"
    },
    "imageName": {
      "value": "${SERVICE_WEB_IMAGE_NAME}"
    },
    "applicationInsightsName": {
      "value": "${APPLICATIONINSIGHTS_NAME}"
    },
    "containerAppsEnvironmentName": {
      "value": "${AZURE_CONTAINER_ENVIRONMENT_NAME}"
    },
    "containerRegistryName": {
      "value": "${AZURE_CONTAINER_REGISTRY_NAME}"
    }
  }
}
AZURE.YAML

# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: azure-remix
services:
  web:
    language: ts
    project: './src/web/GlyphEditor'
    module: app/web
    host: containerapp

DOCKER FILE:
# base node image
FROM node:18-bullseye-slim as base

# set for base and all layer that inherit from it
ENV NODE_ENV production

# Install all node_modules, including dev dependencies
FROM base as deps

WORKDIR /myapp

ADD package.json package-lock.json ./
RUN npm install --production=false

# Setup production node_modules
FROM base as production-deps

WORKDIR /myapp

COPY --from=deps /myapp/node_modules /myapp/node_modules
ADD package.json package-lock.json ./
RUN npm prune --production

# Build the app
FROM base as build

WORKDIR /myapp

COPY --from=deps /myapp/node_modules /myapp/node_modules

ADD . .
RUN npm run build

# Finally, build the production image with minimal footprint
FROM base

WORKDIR /myapp

COPY --from=production-deps /myapp/node_modules /myapp/node_modules

COPY --from=build /myapp/build /myapp/build
COPY --from=build /myapp/public /myapp/public
ADD . .

CMD ["npm", "start"]

**Comment by wbreza** [comment]
Does a standard `docker build` command work to build the container image?  
Do you have a repo you can share to more easily debug?
