### ISSUE TITLE
[Issue] Update azd pipeline config troubleshooting

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#2123]
Would like the doc https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/troubleshoot#azd-pipeline-config-failure-due-to-conditional-access-policy to specify which codespaces host each workaround applies to.  Maybe have a section "codespaces in browser" and another for "codespaces in vscode".

**Comment by rajeshkamal5050** [comment]
@gkulin can you work with @vhvb1989 to get it updated?

**Comment by savannahostrowski** [comment]
Needed before content freeze
