### ISSUE TITLE
[Bug] azd is not using default environment when there are more than one env.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#2127]
There's a bug on azd when it resolves what environment to use if there are more than one environment. (And for some cases, even for just one environment).

Repro:
1) from empty folder, run `azd auth login` and complete login process
2) do `azd init` (complete the process, pick any template)
3) do `azd provision`. This should ask you to pick a subscription and location. Wait until finish
4) Now run `azd auth login` again and use a different user which has no access to previous used subscription.
5) Run `azd env new` and choose some name.
6) Run `azd provision`
  - EXPECTED: azd should ask you to select a sub and location for the just created new environment.
  - ERROR: azd returns an error as it tries to use the previous environment and fails accessing the subscription.

Workaround is to run `azd provision -e env-name` to select the just-created environment. Then azd behaves a expected.

**Comment by vhvb1989** [comment]
Here's another unexpected behavior:

1) delete .azure folder `rm -rf .azure`
2) run `azd env new foo`
3) run `azd env list` and notice the just created env as default
4) run `azd up`, Notice how azd uses a different env name:

![image](https://user-images.githubusercontent.com/24213737/236917397-63b35019-ce1e-4ee9-8415-1e14f0f82fa4.png)

**Comment by ellismg** [comment]
Having trouble reproducing this locally.

What's very confusing to me is that in the example in the second case, you say that you delete all of `.azure`.  This should remove the `config.json` in the root of `.azure` that we use to store what the selected environment is.  And in the screen shot it seems like the new environment you created was set as the default, so I'm very confused where `azd up` was picking that setting up from.

When you are in this state is the name in .azure/config.json for the currently selected environment correct?

**Comment by ellismg** [comment]
@vhvb1989 and I looked at this a little and he was also seeing it behave has expected.  He had, however, recently rebooted his system.

Talking about the issue, I realized that if you explicitly set AZURE_ENV_NAME in your os's environment (say via `export` or `set` in your shell) then we would use this environment name, unless you explicitly pass a value on the command line (recall that when `-e is not set, we the value of AZURE_ENV_NAME instead of the default environment set in `config.json`).  I could set that explicitly and reproduce the above behavior, so I suspect that might what was going on.

**Comment by ellismg** [comment]
We can't seem to reproduce this anymore.  If someone hits this, check to see if `AZURE_ENV_NAME` is set in your os environment (e.g. `echo $AZURE_ENV_NAME` in the shell that you're hitting this in)

**Comment by Justrebl** [comment]
Hello, 
I can reproduce on my environment that do not want to switch environments, whatever command i execute : 
- azd env new demo
- azd env select demo 
- azd provision -e is the only way to select the new environment

Even tried removing the .azure folder : the old environment is still identified as the current one 

Any further analysis on your end?

**Comment by Justrebl** [comment]
Just found out that manually changing $env:AZURE_ENV_NAME helps me switching environments so that AZD accepts working with another environment as current
