### ISSUE TITLE
Unable to run `azd pipeline config`

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#2137]
azd version 0.8.0-beta.3-daily.2756342

Not sure if this is related to starter template. 

Repro steps:
Follow steps in https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/make-azd-compatible?pivots=azd-convert. 
1. Run git clone https://github.com/Azure-Samples/msdocs-python-flask-webapp-quickstart
2. Replace main.bicep with what's in the tutorial 
   - make sure in /core/host, the following files are found: appservice-appsettings.bicep; appservice.bicep and appserviceplan.bicep.
3. run `azd provision`
4. replace azure.yaml with what's in the tutorial
5. run `azd deploy`
6. run `git remote rm origin` 
7. run `azd pipeline config`. Private repo is created but hit the following error message:

```
ERROR: failed to create or update service principal: failed retrieving application list, failed executing request: http call(https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/token)(POST) error: reply status code was 400:
{"error":"invalid_grant","error_description":"AADSTS50158: External security challenge not satisfied. User will be redirected to another page or authentication provider to satisfy additional authentication challenges.\r\nTrace ID: 4b08afbe-880a-42b0-b310-afe60bb59000\r\nCorrelation ID: 17861d31-f579-475c-8cf9-4b817058ec98\r\nTimestamp: 2023-05-09 04:44:17Z","error_codes":[50158],"timestamp":"2023-05-09 04:44:17Z","trace_id":"4b08afbe-880a-42b0-b310-afe60bb59000","correlation_id":"17861d31-f579-475c-8cf9-4b817058ec98","error_uri":"https://login.microsoftonline.com/error?code=50158","suberror":"basic_action"}
```

**Comment by weikanglim** [comment]
I think this is due to the `msgraph` scope needing additional authorization.
