### ISSUE TITLE
Deploying service api failed when run command "bash xxx"

### ISSUE THREAD

**Issue by blow-hey** [Azure/azure-dev#2138]
**Describe the issue:**
Failed to deploy service api when run `bash ./test-templates.sh -t <template-name> -b staging`

The error message as follows:
![image](https://user-images.githubusercontent.com/112381413/237008352-b953c3c8-773b-47dc-9354-f35bc333f234.png)

**Repro steps:**
1. Run `azd auth login`
2. Run `bash ./test-templates.sh -t <template-name> -b staging -c false`.

**Environment:**

- OS: Windows desktop.
- Template: todo-nodejs-mongo, todo-nodejs-mongo-terraform, todo-nodejs-mongo-swa-func
- Branch: staging
- Azd version: 0.8.0-beta.3-daily.2760917 (commit 2201b16963dc43ae045c52374c0dd395152cb309)

**Expected behavior:**
`bash ./test-templates.sh -t <template-name> -b staging -c false` can pass.

@rajeshkamal5050 for notification.

**Comment by wbreza** [comment]
I'm not able to reproduce this issue.  Please ensure you have the correct node version installed on your machine (Node 18.16 LTS).

<img width="863" alt="image" src="https://github.com/Azure/azure-dev/assets/6540159/8c09a814-cead-4b8f-b611-9b1271c79f16">
