### ISSUE TITLE
Start api failed when run vscode tests with todo-nodejs-mongo-aca

### ISSUE THREAD

**Issue by blow-hey** [Azure/azure-dev#2139]
**Describe the issue:**
Run task `Start API and Web`, the API application failed to start.

The error message as follows:
![image](https://user-images.githubusercontent.com/112381413/237010105-c25a7717-bf19-4a58-87da-2e6256ac99dd.png)

**Repro steps:**
1. Run `azd auth login`
2. Run `bash ./test-templates.sh -t todo-nodejs-mongo-aca -b staging -c false`.
3. Open the project in VS Code
4. Hit F1, Run Task, `Start API and Web`

**Environment:** 

- OS: Windows desktop.
- Template: todo-nodejs-mongo-aca
- Branch: staging
- Azd version: 0.8.0-beta.3-daily.2760917 (commit 2201b16963dc43ae045c52374c0dd395152cb309)

**Expected behavior:** 
API application started successfully when run vscode tests with `todo-nodejs-mongo-aca`.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you triage this?
