### ISSUE TITLE
Permission denied when run command "azd up"

### ISSUE THREAD

**Issue by blow-hey** [Azure/azure-dev#2140]
**Describe the issue:**
Permission denied when run `azd up`.

The error message as follows:
![image](https://user-images.githubusercontent.com/112381413/237043993-d91a553a-c7cf-4e8a-bb59-b2598004413f.png)

**Repro steps:**
1. Run `azd auth login`
2. Run `azd up`

**Environment:**
OS: MacOS desktop, Linux desktop, WSL, DevContainer in VS Code, CodeSpace.
Template:  https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application
Azd version: 0.8.0-beta.3-daily.2760917 (commit https://github.com/Azure/azure-dev/commit/2201b16963dc43ae045c52374c0dd395152cb309)

**Expected behavior:**
Run command `azd up` success.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
PR out https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application/pull/4

**Comment by yiliuTo** [comment]
Closing this issue since it has been fixed by https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application/pull/4 and has been validated.
