### ISSUE TITLE
"Azd pipeline config" failed on Codespace

### ISSUE THREAD

**Issue by blow-hey** [Azure/azure-dev#2142]
**Describe the issue:**
Failed configuring authentication when run `azd pipeline config --provider github`

The error message as follows:
![image](https://user-images.githubusercontent.com/112381413/237049087-f2dacd64-642e-4aef-a5e8-3ac4dc221e3f.png)

**Repro steps:**
1. Run `azd auth login`
2. Run `azd up`
3. Run `azd pipeline config --provider github` 

**Environment:**
OS: CodeSpace.
Template: https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application
Azd version: 0.8.0-beta.3-daily.2760917 (commit https://github.com/Azure/azure-dev/commit/2201b16963dc43ae045c52374c0dd395152cb309)

**Expected behavior:**
Run command `azd pipeline config` success on CodeSpace.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@yiliuTo you need to update your ASA template similar to this - https://github.com/Azure/azure-dev/pull/2126

@wbreza @ellismg this breaking change will be widespread in addition to changelog @savannahostrowski do you want to call this out in blog post too?

**Comment by yiliuTo** [comment]
HI @rajeshkamal5050 and @vhvb1989 , after update the template by replacing secerts by vars like [here](https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application/pull/4/commits/6a8ecbbdbe3594ff72d2132520f8a96542c32089), the test team still met the samilar error as below:

![MicrosoftTeams-image](https://github.com/Azure/azure-dev/assets/63028776/cb152d19-1cc2-4000-8fb3-816b23d835a0)

And still I cannot reproduce this issue with my own GitHub account, which maybe due to that I am the admin of the template GitHub repo. Would you like to share any suggestions about this error? Thanks

**Comment by rajeshkamal5050** [comment]
@vhvb1989 @yiliuTo worked offline and has fixed it.
```
Ideally, the repo should be a public template (like the other todo projects)
Right now is a regular github repo.
When the repo is a template, opening codespaces from it does not link a git remote to the repo, 
A folder with a repo files copy is opened in the codespace, so running pipeline config will ask to create a new repo.
But if the repo is a not template and just regular repo, the codespace is opened git origin remote set to the repo. Pipeline config will not ask to creat a new repo and instead it will try to update the original
```
@v-xuto @blow-hey can you test this again?

**Comment by v-xuto** [comment]
@rajeshkamal5050  Got it. We will re-test it.

**Comment by v-xuto** [comment]
@rajeshkamal5050 We retested it in CodeSpace, and the following are the test results:
- If we start from `Code` -> `Create codespace on main`, this issue can still be reproduced. And, this method is what we have been using.
![image](https://github.com/Azure/azure-dev/assets/57166602/6574aef4-aa82-4226-84ea-8949294801c7)

- If we start from the `Use this template` -> `Open in a codespace`, its test result is **PASS**.
![image](https://github.com/Azure/azure-dev/assets/57166602/0948fd76-dd65-41d8-8f3a-5ea83c83da31)
