### ISSUE TITLE
VS Code - `up` command - cli output repeated

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-dev#2150]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 0.8.0-beta.2 

**Describe the bug**
When running `Azure Developer: up` via the azd extension in vs code, the cli output is repeated as the activity indicator moves, but only for the 2nd resource, subsequent resources did not experience the same behavior.

**To Reproduce**
`ctrl+shift+p`
`up`

**Expected behavior**
I expect to see only one instance of the repeated line in the screenshot, rather than one instance for each movement of the activity indicator.

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : VS Code latest
    
**Additional context**
![image](https://github.com/Azure/azure-dev/assets/74415662/bdbfc49f-687c-4191-9dc2-a6de2099bda7)

**Comment by savannahostrowski** [comment]
Yeah - this was a known bug related to your window width.  It was reproduceable in any terminal, not just VS Code.

It will be fixed in the next release of azd, out tomorrow - see https://github.com/Azure/azure-dev/issues/1784
