### ISSUE TITLE
Improve UX of azd down when default env selected has not been provisioned/deployed

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2155]
- `azd up`
- `azd env new <name>`, which will create and switch to the env (not provisioned/deployed)
- `azd down --force --purge --no-prompt`

You will see:
![image](https://github.com/Azure/azure-dev/assets/8949415/5fe5a9c0-5a04-4157-9464-13566abb8817)

The error should tell the user that this environment does not have any deployments/infra to destroy.

**Comment by rajeshkamal5050** [comment]
@v-xuto can you pick error handling/validation and put out a PR?

**Comment by zedy-wj** [comment]
@savannahostrowski - According to your steps: `azd up` -> `azd env new <name>` -> `azd down --force --purge --no-prompt`, we cannot reproduce this issue. The results of the attempt are as follows:
![image](https://github.com/Azure/azure-dev/assets/81678720/23d1b923-b7d6-4c22-a5e9-1fb92feb67f3)
**This seems to be the result you expected.**

Could you try it again? If you still reproduce this problem, please provide your specific version of `azd`, thank you!

**Comment by savannahostrowski** [comment]
Looks like the behaviour was updated!
