### ISSUE TITLE
Update template names in command palette

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2158]
With the naming updates in #2073, we need to update the template names and descriptions in the command palette.

**Comment by bwateratmsft** [comment]
@savannahostrowski I think this Just Works (TM), since the extension picks up the choices programmatically. Can you check with AZD 0.9.0+? 
![image](https://github.com/Azure/azure-dev/assets/36966225/2597c3e9-7530-4fc6-8f34-c312f34ccd18)
