### ISSUE TITLE
[docs] Docs need to identify target OS

### ISSUE THREAD

**Issue by gkulin** [Azure/azure-dev#2160]
audit commands mentioned in the docs & clarify whether they are OS specific 

> For example - [Configure a pipeline and push updates using GitHub Actions or Azure DevOps (preview) | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fdeveloper%2Fazure-developer-cli%2Fconfigure-devops-pipeline%3Ftabs%3Dazdo&data=05%7C01%7Cgrace.kulin%40microsoft.com%7Cc004b61f6de543a661c108db50d08689%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638192628768653996%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EzFM1GzQZvKIqO%2BvWs3ki7jwyJriQA7TxfzYKcCjD8U%3D&reserved=0)
> 
> This is not clear if this command is supposed to be run in Azd or it’s a OS specific command? What about other supported OS if this is a Linux command?
> 
> ![image](https://github.com/Azure/azure-dev/assets/55554236/21b58b29-5e5c-40e6-9cdf-aa1395bbe0d9)
> 

This is intended to be an env variable set in the terminal where the azd command is being run. Update the command type to Bash for clarification.

**Comment by savannahostrowski** [comment]
Needed before content freeze
