### ISSUE TITLE
[docs] Mapping between project / resource via tags

### ISSUE THREAD

**Issue by gkulin** [Azure/azure-dev#2163]
> [Make your project compatible with Azure Developer CLI (preview) | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fdeveloper%2Fazure-developer-cli%2Fmake-azd-compatible%3Fpivots%3Dazd-create&data=05%7C01%7Cgrace.kulin%40microsoft.com%7Cc004b61f6de543a661c108db50d08689%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638192628768653996%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kpBh3yIuXTYTG2Di3vtZL3PpW6T9sHdvmcowbqzC1EM%3D&reserved=0)
> 
> ![thumbnail_image003](https://github.com/Azure/azure-dev/assets/55554236/2ae0ffe2-d05b-4981-9931-5289a8edb372)
> Use of “tags” should be explained more explicitly and provide more clarity,

Add some additional details about how the azure.yaml service names tie to Bicep modules and tags.

**Comment by savannahostrowski** [comment]
Needed before content freeze

**Comment by savannahostrowski** [comment]
Awesome - did you want to add this issue in the PR comment for the docs issue so we know when this issue can be closed?

**Comment by puicchan** [comment]
Done.
