### ISSUE TITLE
[Issue] Don't give 'brazilus' as an option

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#2165]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 0.8.0-beta.2 (commit 429b6ccf9a9d1616efa8988f2f8561deeb464c71)

**Describe the bug**

I selected a region based on the list and randomly selected 'brazilus'. However, I got an error that such a location isn't available:

```
ERROR: deployment failed: error deploying infrastructure: starting deployment to subscription: PUT https://management.azure.com/subscriptions/32ea8a26-5b40-4838-b6cb-be5c89a57c16/providers/Microsoft.Resources/deployments/flask-db-quiz
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: LocationNotAvailableForDeployment
--------------------------------------------------------------------------------
{
  "error": {
    "code": "LocationNotAvailableForDeployment",
    "message": "The provided location 'brazilus' is not available for deployment. List of available regions is 'eastus,eastus2,eastusstg,westcentralus,westus,westus2,westus3,centraluseuap,eastus2euap,canadacentral,canadaeast,centralus,northcentralus,southcentralus,southcentralusstg,eastasia,southeastasia,australiaeast,australiasoutheast,brazilsouth,switzerlandnorth,germanywestcentral,francecentral,uksouth,ukwest,centralindia,southindia,jioindiawest,japaneast,japanwest,koreacentral,northeurope,norwayeast,swedencentral,uaenorth,westeurope,southafricanorth,australiacentral,australiacentral2,westindia,koreasouth,qatarcentral,polandcentral'."
  }
}
--------------------------------------------------------------------------------

```

This page shows only brazilsouth as an option:
https://azure.microsoft.com/en-us/explore/global-infrastructure/geographies/#geographies

This page shows brazilsouth and brazilsoutheast for emergencies, but no brazilus:

https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/?products=app-service

I don't know where brazilus came from, but it doesn't seem like a good option.

I'm double checking with the Brazil advocacy team to see if they know more, will update when I hear back.

**To Reproduce**

Run azd up on new project, select brazilus as option.

**Expected behavior**

I expect only viable locations (at least globally viable).

**Comment by pamelafox** [comment]
Update from Brazilian advocate: "A friend of mine told me that Brazilus is a non-production region. It's a canary region"

**Comment by savannahostrowski** [comment]
Oh this is interesting - @rajeshkamal5050 I'm assuming it'd be easy enough to hide this region from the list. Moving to 5/17 but please let me know if this is more invasive.

**Comment by rajeshkamal5050** [comment]
@wbreza is the location/region dynamic? If dynamic, do we get some metadata on such locations, so we can hide them?
