### ISSUE TITLE
`azd pipeline config`  fail to deploy service api in action logs

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#2171]
**Describe the issue:**
When run `azd pipeline config --principal-role owner`,  get error in action logs as follow:

![image](https://github.com/Azure/azure-dev/assets/80496810/09989a02-2614-437c-88ff-3f6dacfa0659)

Notes: add `--principal-role owner` is because we first encountered old issue: https://github.com/Azure/azure-dev/issues/1686

**Repro Steps:**
1. Run`azd auth login`
2. Run `bash ./test-templates.sh -t todo-python-mongo-aca -b staging -c false`.
3. Run ` azd pipeline config --principal-role owner--provider github` or `azd pipeline config --principal-role owner --provider azdo` or `azd pipeline config --principal-role owner --auth-type client-credentials `

**Environment:**
- OS: Windows desktop, MacOS desktop, Linux desktop,  WSL ,CodeSpace and Devcontainer in VS Code.
- Template: todo-python-mongo-aca
- Branch: staging
- Azd version: 0.8.0-beta.3-daily.2763383  (commit https://github.com/Azure/azure-dev/commit/3f484a283b309b3cab6f91386a4a7af7f4a082a2)

**Expected behavior:**
 Run `azd pipeline config` can pass for todo-python-mongo-aca

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@v-jiaodi does this reproduce consistently or it happens sometimes? Can you try and let us know?

**Comment by vhvb1989** [comment]
Can you confirm azd version?  The issue description says `Azd version: 0.8.0-beta.3-daily.2763383`  , but daily should be `azd version 0.9.0-beta.2-daily`

Are you getting version 0.8.0 inside the pipeline?

The logs from the pipeline are logs from version 0.8.0, which is not compatible with templates on branch staging (those requires 0.9.0)

**Comment by v-jiaodi** [comment]
@rajeshkamal5050, @vhvb1989 Based on the latest version testing of azd `0.9.0-beta.2-daily.2776582`, this issue cannot be reproduced. I will close it.
