### ISSUE TITLE
`azd pipeline config`  fail to deploy service api with todo-nodejs-mongo-aks

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#2172]
**Describe the issue:**
When run `azd pipeline config --principal-role owner`, get error in action logs as follow:

![image](https://github.com/Azure/azure-dev/assets/80496810/90d3a3fa-dede-490b-9c11-0323dd1ac5ff)

**Repro Steps:**

1. Run`azd auth login`
2. Run `bash ./test-templates.sh -t todo-nodejs-mongo-aks -b staging -c false`.
3. Run `azd pipeline config --principal-role owner --provider github` or `azd pipeline config --principal-role owner  --auth-type client-credentials` or `azd pipeline config --principal-role owner --provider azdo`

**Environment:**

- OS: Windows desktop, MacOS desktop, Linux desktop,  WSL ,CodeSpace and Devcontainer in VS Code.
- Template: todo-nodejs-mongo-aks
- Branch: staging
- Azd version: 0.8.0-beta.3-daily.2763383  (commit https://github.com/Azure/azure-dev/commit/3f484a283b309b3cab6f91386a4a7af7f4a082a2)

**Expected behavior:**
 Run `azd pipeline config` can pass for todo-nodejs-mongo-aks

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@v-jiaodi does this reproduce consistently or it happens sometimes? Can you try and let us know?

**Comment by v-jiaodi** [comment]
@rajeshkamal5050  This issue can always reproduce.

**Environment:**

- OS: Windows desktop, MacOS desktop, Linux desktop,  WSL ,CodeSpace and Devcontainer in VS Code.
- Template: todo-nodejs-mongo-aks
- Branch: staging
- Azd version: 0.9.0-beta.2-daily.2772915  (commit https://github.com/Azure/azure-dev/commit/08ff66607eb70b25d189aefce0d21070fe84630d)

**Comment by vhvb1989** [comment]
root cause: https://github.com/Azure/azure-dev/issues/2172
