### ISSUE TITLE
[Hotfix] azd upgrade notice copy changes

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#2176]
New copy: 

```
warning: your version of azd is out of date, you have 1.2.3 and the latest version is 4.5.6

To update to the latest version, <instructions> 
```

We'll use `.installed-by.txt` to determine the installation method. 

`<instructions>` will be: 

* Windows
    * install-azd.ps1 -- `powershell -ex AllSigned -c \"Invoke-RestMethod 'https://aka.ms/install-azd.ps1' | Invoke-Expression\"`
    * winget -- `winget upgrade Microsoft.Azd`
    * choco -- `choco upgrade azd`
    * default -- `visit https://aka.ms/azd/upgrade/windows` 
* Linux
    * install-azd.sh -- `curl -fsSL https://aka.ms/install-azd.sh | bash` 
    * default -- `visit https://aka.ms/azd/upgrade/linux` (useful for `.deb` and `.rpm` in their current state of support)
* MacOS
    * brew -- `brew upgrade azd`
    * install-azd.sh -- `curl -fsSL https://aka.ms/install-azd.sh | bash` 
    * default -- `visit https://aka.ms/azd/upgrade/mac`
* Platform unknown
    * all cases -- `visit https://aka.ms/azd/upgrade` 

Users can install `azd` on Linux and MacOS using our PowerShell installer script, but in that case the PowerShell installer script only bootstraps `install-azd.sh` and the `.installed-by.txt` file will have the value `install-azd.sh` so we don't need to explicitly handle that case.

**Comment by Austinauth** [comment]
Thanks @danieljurek! 

I would just make sure the warning label is in all caps `WARNING:`. Its a little intense, but it will be consistent with our other log messages. I want keep them  consistent until we have a chance to come back and revisit them holistically post-Build.

**Comment by pamelafox** [comment]
FYI https://aka.ms/azd/upgrade/mac doesnt go to Mac instructions for me, it goes to:
https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/install-azd?tabs=localinstall%2Cwindows%2Cbrew%2Cdeb

**Comment by savannahostrowski** [comment]
This is a known issue - docs changes are in PR https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4483 and we will update the URLs when this gets merged.
