### ISSUE TITLE
[Issue] Autogenerated image name is toooo long

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#2178]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

azd version 0.9.0-beta.1 (commit 9e9e9d6e66afd3b417b60cc4d387cee0626a67d7)

**Describe the bug**

I just wanted to try new azd on container apps to see if I need to change something, and a deploy on an existing environment is erroring out due to image name length. I assume the image name is longer in the latest version of azd, as I think this successfully deployed before. Can you truncate on your end? (I'll try a new env for now)

```
simple-flask-api-container % azd up

Packaging services (azd package)

  (✓) Done: Packaging service api
  - Image Hash: sha256:e272932e6220b18bfede045476336fb72c1a199fe0e15f0f5f2752d762c06ad8
  - Image Tag: simple-flask-container-app/api-simple-flask-api-aca:azd-deploy-1683832575

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time

  You can view detailed progress in the Azure Portal:
  https://portal.azure.com/#blade/HubsExtension/DeploymentDetailsBlade/overview/id/%2Fsubscriptions%2F32ea8a26-5b40-4838-b6cb-be5c89a57c16%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Fsimple-flask-api-aca-1683832581

  (✓) Done: Resource group: simple-flask-api-aca-rg
  (✓) Done: Log Analytics workspace: simple-flask-api-aca-yjdgrj55pofd4-loganalytics
  (✓) Done: Key vault: simpleflaskapiaca-vault
  (✓) Done: Container Apps Environment: simple-flask-api-aca-yjdgrj55pofd4-containerapps-env
  (✓) Done: Container Registry: simpleflaskapiacayjdgrj55pofd4registry
  (✓) Done: Container App: simple-flask-api-ac-containerapp


Deploying services (azd deploy)

  (x) Failed: Deploying service api

ERROR: failed deploying service 'api': failing invoking action 'deploy', updating container app service: updating container app revision: begin updating ingress traffic: PATCH https://management.azure.com/subscriptions/32ea8a26-5b40-4838-b6cb-be5c89a57c16/resourceGroups/simple-flask-api-aca-rg/providers/Microsoft.App/containerApps/simple-flask-api-ac-containerapp
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: ContainerAppInvalidRevisionName
--------------------------------------------------------------------------------
{
  "error": {
    "code": "ContainerAppInvalidRevisionName",
    "message": "Revision name has an invalid value 'simple-flask-api-ac-containerapp--azd-deploy-1683832697'. A revision name must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character. The length of the revision name must not be more than a combined 54 characters with the container app name."
  }
}
--------------------------------------------------------------------------------

```

**To Reproduce**

Use name with length of "simple-flask-api-aca" with https://github.com/pamelafox/simple-flask-api-container
and run `azd up`

**Environment**
Mac OS X M1 terminal

**Comment by weikanglim** [comment]
I think this broke when I introduced "projectName" into the default naming convention a few releases ago (it's been months). One thing to note is that the user has full control over the tag generated, by specifying an explicit `services.<service>.docker.tag` in `azure.yaml`.

Looking back at the scenario, I could see us removing "projectName", and keeping to a combination of env + service name for sufficient uniqueness. This is a fine change to make, and I don't think users will notice if we did change the naming convention.

We should also apply truncation of image tags for this scenario, but it'll have to be consistent with valid docker image tag naming rules.

**Comment by wbreza** [comment]
After looking into this issue the issue is with the name of the container app revision, not the name of the image specified associated with the container.  It's a combination of the resource name plus the vision suffix.

ARM Resource Name + azd-deploy-{TIMESTAMP}

This weird linkage means that the suffix possible length is reduced as the container app names grows.
