### ISSUE TITLE
Improve the discoverability of alpha features in docs

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2180]
We probably want to add details about how to enable alpha features here (e.g. azd config set alpha.feature on) etc.

https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/feature-versioning

Not required before content freeze.

cc: @puicchan

**Comment by gkulin** [comment]
closed with https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4458
