### ISSUE TITLE
Improve error when repo name already exists during pipeline config

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2181]
![image](https://github.com/Azure/azure-dev/assets/8949415/1def1094-7663-46a3-a683-5f50a499097e)

This is the error message a user sees if they enter a repo name that already exists on their account (if they choose to create a new private repo) during pipeline config.

There's a lot of info in there that's noise/not useful

The error should read more like:

"ERROR: A repository with this name already exists on this account. Please run `azd pipeline config` again with a different name"

**Comment by vhvb1989** [comment]
@savannahostrowski should we require user to run `azd pipeline again` ?

We can just backtrack to the name-prompt after displaying a non-process-ending error.  This is what we do for Azdo.  azd just tell user `this name is already taken` and ask to use a different name.

**Comment by savannahostrowski** [comment]
Oh! That's even better. Yes, if we can backtrack without having to ask them to reinvoke the command that's best!
