### ISSUE TITLE
[Issue] azd env refresh reports success, but vars not in .env file

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#2191]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
9.2

**Describe the bug**

I run azd env refresh, it says success, but no values in .env file.

**To Reproduce**

One thing to note is the last deployment to this env failed, so that may have something to do with it, but we should report the failure of refresh if no values are added.

Another thing is the bicep is slightly different locally than what is live in azure.

**Expected behavior**
Values in .env

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

.net
vscode

**Additional context**

**Comment by rajeshkamal5050** [comment]
@ellismg can you take a look and pull it into GA if need be.

**Comment by rajeshkamal5050** [comment]
@jongio have not seen this lately, re-open if it happens again.
