### ISSUE TITLE
Have to reset my tty each time I run azd

### ISSUE THREAD

**Issue by duglin** [Azure/azure-dev#2194]
Using version: azd version 0.9.0-beta.2 (commit afa7ac6e839be8304b86b3df6b8525a97e48a532)

I've been playing with azd and been running into issues and it fails for me each time I run it - not an azd issue per se, I assume some setup/config issue. However, after azd runs I can't see my cursor and I have to run "reset" before I can see my cursor again. I'm guessing it's because the fancy cursor movement stuff that azd does might not be resetting things upon exiting in the error case. I could be true for the happy-path case too, I'm not sure since I haven't gotten that far yet.

I'm on a mac - v12.6.5

**Comment by duglin** [comment]
I just set the env var NO_COLOR=1 and this seems to have fixed the issue - if that's a clue.

**Comment by weikanglim** [comment]
@duglin Thanks for reporting this. What's the minimal command that this reproduces with, and what's your terminal setup? 

Another thing to try:

Does `export TERM=dumb` also fix the behavior?

To root cause, we can try something along the lines of this StackOverflow [post](https://unix.stackexchange.com/questions/469770/cursor-disappears-when-running-top-n1-head) to see if there are misbehaving control characters.

**Comment by duglin** [comment]
I just ran `azd up`.
I can reproduce it by hitting ctrl-c as soon as I see:
```
|   ====| Creating a deployment plan
```
basically as soon as the advanced cursor stuff kicks in.
And yes `TERM=dumb` does seem to avoid it

**Comment by weikanglim** [comment]
@duglin Thanks. That seems to narrow it down to the spinner that `azd` uses. However, I'm not seeing any existing issues that captures what you're seeing yet.

I also ran `azd` on macOS 13 on both iterm and Terminal and they both work as expected.

Can you share more about your specific terminal setup?

**Comment by duglin** [comment]
See if this helps, my TERM env vars:
```
TERM_PROGRAM=Apple_Terminal
TERM=xterm-256color
TERM_PROGRAM_VERSION=445
```
and I'm running bash - but I doubt that's related.

**Comment by weikanglim** [comment]
Interesting. It doesn't reproduce for me. I'm slightly ahead (macOS 13.3.1):

```
TERM=xterm-256color
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=447
```

**Comment by savannahostrowski** [comment]
@duglin Does this still repro for you?

**Comment by duglin** [comment]
Yup still seeing it. I make sure that env var `NO_COLOR` is set and then do `azd up`. Then as soon as I see the progress bar I hit ctrl-c. And my cursor vanishes.

**Comment by savannahostrowski** [comment]
@weikanglim Did we fix this?

**Comment by weikanglim** [comment]
@duglin We updated logic to unhide the cursor on graceful termination (success or failure). Feel free to reopen if there are still cases where this isn't working as expected for you.

**Comment by duglin** [comment]
@weikanglim I'm still seeing the issue. I'm on:
azd version 1.5.0 (commit 012ae734904e0c376ce5074605a6d0d3f05789ee)

**Comment by duglin** [comment]
I'm not able to reopen the issue

**Comment by duglin** [comment]
just tried it again with the latest, and it seems to be working. thanks @weikanglim

**Comment by weikanglim** [comment]
@duglin Thanks for confirming!
