### ISSUE TITLE
[Issue] Failure packaging on  todo-nodejs-mongo-swa-func

### ISSUE THREAD

**Issue by ricardocovo** [Azure/azure-dev#2199]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 0.9.0-beta.2 (commit afa7ac6e839be8304b86b3df6b8525a97e48a532)

**Describe the bug**
When executing 'azd up', I get the following errors:
```
Packaging services (azd package)

  (x) Failed: Packaging service api

ERROR: failed packaging service 'api': failing invoking action 'package', failed to run NPM script build, exit status 2
```

**To Reproduce**
Run: azd init --template todo-nodejs-mongo-swa-func
- Environment name: swademo
- Location: eastus2

Run: 'azd up' or 'azd package'

**Expected behavior**
I expected 'azd up' to run 'azd package', 'azd provision' and 'azd deploy', but it is failing in the package step.

**Environment**
Information on your environment:

Running all from console.
Nodejs version : v18.14.1
NPM version: 9.3.1

**Additional context**
I had used this template before without issues. This started happening recently.

**Comment by rajeshkamal5050** [comment]
@ricardocovo tried and couldn't repro it.

Are you running the the new azd bits with an older version of the template? Can you try a fresh download/init of the template and see?

Logs of a successful run.
```
azd version
azd version 0.9.0-beta.2 (commit afa7ac6e839be8304b86b3df6b8525a97e48a532)

azd init

Initializing a new project (azd init)

? Select a project template: React Web App with Node.js API and MongoDB

  (✓) Done: Initialized git repository
  (✓) Done: Downloading template code to: /Users/rajeshkamal/acme-azd

? Please enter a new environment name: acme-azd-dev

SUCCESS: New project initialized!
You can view the template code in your directory: /Users/rajeshkamal/acme-azd
Learn more about running 3rd party code on our DevHub: https://learn.microsoft.com/azure/developer/azure-developer-cli/azd-templates#guidelines-for-using-azd-templates
rajeshkamal@devdiv acme-azd % azd up
? Please select an Azure Subscription to use: 21. acme-sub
? Please select an Azure location to use: 44. acme-location

Packaging services (azd package)

  (✓) Done: Packaging service api
  - Package Output: /var/folders/p2/m3m3zff130z421xnyynky0jw0000gn/T/azddeploy2493098051.zip
  (✓) Done: Packaging service web
  - Package Output: /var/folders/p2/m3m3zff130z421xnyynky0jw0000gn/T/azddeploy3901477753.zip

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time

  (✓) Done: Downloading Bicep
  You can view detailed progress in the Azure Portal:
  https://portal.azure.com/{url}

  (✓) Done: Resource group: rg-acme-azd-dev
  (✓) Done: Key vault: kv-n2bunmzwe3z7y
  (✓) Done: Log Analytics workspace: log-n2bunmzwe3z7y
  (✓) Done: App Service plan: plan-n2bunmzwe3z7y
  (✓) Done: Application Insights: appi-n2bunmzwe3z7y
  (✓) Done: Portal dashboard: dash-n2bunmzwe3z7y
  (✓) Done: Azure Cosmos DB: cosmos-n2bunmzwe3z7y
  (✓) Done: App Service: app-web-n2bunmzwe3z7y
  (✓) Done: App Service: app-api-n2bunmzwe3z7y
```

**Comment by wbreza** [comment]
@ricardocovo ca. You provide us the versions of node and npm that you have installed on your system?

**Comment by ricardocovo** [comment]
@wbreza  here you go:

```
PS C:\Playground\demos\nodejs-mongo-aca> node -v
v18.14.1
PS C:\Playground\demos\nodejs-mongo-aca> npm -v
9.3.1
```

**Comment by wbreza** [comment]
Thanks for the updates!  Unfortunately I wasn't able to reproduce the issue. 

There was some changes to the template over the past couple releases and based on the error message it appears you may have an older version of the template with new CLI which could be causing your issue.

Is this issue still happening for you with the latest version of the template & latest version of azd?

**Other things to try**
1. Manually navigate to `src/web` folder `cd src/web`
1. Delete out any `node_modules` folder from within the `src/web`
1. Run `npm ci` to perform a clean install of all project dependencies
1. Run `npm run build` to manually run the project `build` script

**Comment by wbreza** [comment]
Closing for now.  Please feel free to re-open if you continue to encounter this issue.
