### ISSUE TITLE
[Issue] Output of azd up and azd provision

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-dev#2204]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 0.9.0-beta.2 (commit afa7ac6e839be8304b86b3df6b8525a97e48a532)

**Describe the bug**

It seems that the default output of `azd up` and `azd provision`

Although this is chort and crisp, I would like to see a bit more information like the URL to my app. Switching to debug mode or using `--output json` delivers the information, but the output is not very "nice" esp when doing demos. 

Here the standard output: 

![Screenshot 2023-05-14 092701](https://github.com/Azure/azure-dev/assets/22294087/745c3e15-b313-4d5b-a971-b8e7921b0568)

Here the more verbose output using `--output json`:

![Screenshot 2023-05-14 091800](https://github.com/Azure/azure-dev/assets/22294087/f1fe109b-a8e7-4118-b355-671764f0bba3)

![Screenshot 2023-05-14 091840](https://github.com/Azure/azure-dev/assets/22294087/42eab0cc-1f9d-4831-8cfa-fa3d3e65a256)

![Screenshot 2023-05-14 092000](https://github.com/Azure/azure-dev/assets/22294087/55ecc179-5358-4ff5-be12-2ff41bb52444)

**To Reproduce**

* Clöone the repository <https://github.com/Azure-Samples/app-service-javascript-sap-cloud-sdk-quickstart>
* Execute an `azd provision` and compare to `azd provision --output json` 

**Expected behavior**

I think it would make sense to have at least an option via config to make the default output a bit more chatty i.e. being able to specify:

* If the bicep output params should be printed after successful execution
* if updated resources especially configs should be printed.

The information is available in the JSON output, but seems to be ignored in the regualr output

**Environment**

n/a

**Additional context**

I am quite sure that the output of the endpoints was available in some releases of `azd`, but maybe vanished when the output got refactored.

**Comment by savannahostrowski** [comment]
Thanks for filing this - I'll have to explore how we want to surface this info in our up/provision output.

**Comment by savannahostrowski** [comment]
Thinking about this a bit more, today we have `azd env get-values` which will give you all the outputs for your environment.

I think we are more likely to expose a human-readable command like `azd show` (see https://github.com/Azure/azure-dev/issues/1887). I think that exposing everything in command output from up and provision could be quite noisy (perhaps too noisy for some users).

**Comment by lechnerc77** [comment]
I like the proposal given in `azd show`. That would be a good addition to the `azd` commands imho.

If you want to close this issue in favor of #1887 im perfectly fine with that - up to you
