### ISSUE TITLE
GHA "dubious ownership" git error

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2205]
While trying to customize the base GHA we include with our templates, I ran into 
<img width="686" alt="image" src="https://github.com/Azure/azure-dev/assets/8949415/21143575-2632-4a9f-881a-9a68a6015b64">

I suspect that this is because we use an all in one image as part of the GHA and there are mixed ownership and perms across the image and the repo itself.

**Comment by pamelafox** [comment]
I filed an issue about "dubious ownership" in the VS Code repo:
https://github.com/microsoft/vscode-remote-release/issues/8488#issuecomment-1549107575
Our issues might be completely unrelated, just noting since I was working in an azd-ified repo at the time.
