### ISSUE TITLE
Stop using an all in one image for installing azd in template pipeline definitions

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2206]
Today, we use an all-in-one azd container image in our template GHAs which includes all the possible dependencies needed to run any of our templates. This results in a very slow start time for pipeline runs as the image is very large. The image also includes many dependencies that are irrelevant to a given user's application (e.g. if I'm using a Python and React template, I don't need or care about Java being installed)

Instead, we should move to:
- Installing the deps as steps in the pipeline definition (e.g. setup-python, setup-node). This is more transparent to the user what versions of their dependencies are being used in CI. This would also enable a user to more easily customize the versions of their dependencies needed to package their application for deployment.
- Installing azd via GHA (see #2207)

With these enhancements, I was able to get my pipeline run time from 13mins31secs to 10mins37secs for todo-python-mongo. See  https://github.com/savannahostrowski/build-demo-session/blob/main/.github/workflows/azure-dev.yml as an example.

**Comment by savannahostrowski** [comment]
This would be handled by #2207

**Comment by weikanglim** [comment]
Now that `azd` auto acquires `bicep`, this feels like a really good change.

With `azd` delivered as a task, we also definitively know that we're running in GitHub for example, and can enforce certain CI behaviors at the task level. One thing that comes into mind is to improve our usage telemetry upload behavior in this mode.
