### ISSUE TITLE
deployment failed: failing invoking action 'provision', error deploying infrastructure: starting deployment to subscription: PUT https://management.azure.com/subscriptions/***/providers/Microsoft.Resources/deployments/***-1684161352

### ISSUE THREAD

**Issue by varndellwagglebee** [Azure/azure-dev#2209]
- [X ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

This worked last week and the only thing that changed, was on the federated Creds for GitHub actions from 
Entity Type: Branch
Based on selection: dev-setup

TO

Entity TYpe: Environment
Based on selection: Staging 

I also tried giving the service principle owner access.

**Describe the bug**
Unable to provision from Github workflows using service principle and Federated credentials:

**To Reproduce**
1. setup a service principle
2. give it Cloud Application Administrator
3. Try giving it owner access to subscription

**Expected behavior**
To be able to deploy with Environment setting from github workflow.

**Environment**
GitHub Workflow

**Additional context**

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: starting deployment to subscription: PUT https://management.azure.com/subscriptions/***/providers/Microsoft.Resources/deployments/***-1684161920
--------------------------------------------------------------------------------
RESPONSE 403: 403 Forbidden
ERROR CODE: AuthorizationFailed
--------------------------------------------------------------------------------
{
  "error": {
    "code": "AuthorizationFailed",
    "message": "The client '03fa35e0-e0[59](https://github.com/Matri-Design-LLC/Matri.GlyphEditor/actions/runs/4981274109/jobs/8916491326#step:6:60)-4216-b075-1dae40b24ee0' with object id '03fa35e0-e059-4216-b075-1dae40b24ee0' does not have authorization to perform action 'Microsoft.Resources/deployments/write' over scope '/subscriptions/***/providers/Microsoft.Resources/deployments/***-16841[61](https://github.com/Matri-Design-LLC/Matri.GlyphEditor/actions/runs/4981274109/jobs/8916491326#step:6:62)920' or the scope is invalid. If access was recently granted, please refresh your credentials."
  }
}
--------------------------------------------------------------------------------**

![image](https://github.com/Azure/azure-dev/assets/117473104/58e860c0-ff40-49ac-9a0f-5ec72537c3c2)

**Comment by varndellwagglebee** [comment]
I changed the service principle back to Branch/ develop and now I get this error message:

![image](https://github.com/Azure/azure-dev/assets/117473104/4c006012-3251-4275-be25-9fee0fc488de)

**Comment by varndellwagglebee** [comment]
Any update on this?  I'm still getting the issue.


Run azd provision --no-prompt

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time

Downloading Bicep
Creating a deployment plan
Creating/Updating resources

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: starting deployment to subscription: PUT https://management.azure.com/subscriptions/***/providers/Microsoft.Resources/deployments/***-[1](https://github.com/Matri-Design-LLC/Matri.GlyphEditor/actions/runs/5003709419/jobs/8965282464#step:5:1)684329584
--------------------------------------------------------------------------------
RESPONSE 403: 403 Forbidden
ERROR CODE: AuthorizationFailed
--------------------------------------------------------------------------------
{
  "error": {
    "code": "AuthorizationFailed",
    "message": "The client '03fa35e0-e059-4216-b075-1dae40b24ee0' with object id '03fa35e0-e059-4216-b075-1dae40b24ee0' does not have authorization to perform action 'Microsoft.Resources/deployments/write' over scope '/subscriptions/***/providers/Microsoft.Resources/deployments/***-1684329584' or the scope is invalid. If access was recently granted, please refresh your credentials."
  }
}
--------------------------------------------------------------------------------

TraceID: 59eadcc5dc85[14](https://github.com/Matri-Design-LLC/Matri.GlyphEditor/actions/runs/5003709419/jobs/8965282464#step:5:15)4d0a84[25](https://github.com/Matri-Design-LLC/Matri.GlyphEditor/actions/runs/5003709419/jobs/8965282464#step:5:26)7c43dddb00
Error: Process completed with exit code 1.

**Comment by vhvb1989** [comment]
@ellismg I think @varndellwagglebee is deploying to Azure Container Apps, which we recently updated to require either Admin or Owner role to work.
Before our latest changes, a Contributor was able to run azd pipeline config, create a SP with contributor role and provision+deploy to Container Apps.

This is no longer the case, not only for aca, but for even calling azd pipeline config.

@hemarina is working on this [PR](https://github.com/Azure/azure-dev/pull/2028) which will check if user has enough roles before calling azd pipeline config.

**Comment by ellismg** [comment]
Looks like you can use the `az role assignment list --assignee` CLI to list role assignments, if you pass the app id not the object id for the service principal. 

@vhvb1989 Are you sure about that?  From the log I see a 403 when trying to do a PUT to create the deployment:

```
Run azd provision --no-prompt

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time

Downloading Bicep
Creating a deployment plan
Creating/Updating resources

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: starting deployment to subscription: PUT https://management.azure.com/subscriptions/***/providers/Microsoft.Resources/deployments/***-[1](https://github.com/Matri-Design-LLC/Matri.GlyphEditor/actions/runs/5003709419/jobs/8965282464#step:5:1)684329584
--------------------------------------------------------------------------------
RESPONSE 403: 403 Forbidden
ERROR CODE: AuthorizationFailed
--------------------------------------------------------------------------------
{
  "error": {
    "code": "AuthorizationFailed",
    "message": "The client '03fa35e0-e059-4216-b075-1dae40b24ee0' with object id '03fa35e0-e059-4216-b075-1dae40b24ee0' does not have authorization to perform action 'Microsoft.Resources/deployments/write' over scope '/subscriptions/***/providers/Microsoft.Resources/deployments/***-1684329584' or the scope is invalid. If access was recently granted, please refresh your credentials."
  }
}
--------------------------------------------------------------------------------
```

It feels like we are failing to even start the deployment, not that the deployment is working but the role assignments are failing during deployment because the principal running the deployment did not have permissions to assign roles.  Am I misunderstanding the error?

**Comment by varndellwagglebee** [comment]
Is there any follow up on this?

**Comment by vhvb1989** [comment]
@varndellwagglebee have you changed/updated the azure-dev.yaml to use variables instead of secrets?

**Comment by varndellwagglebee** [comment]
This is my deployment yaml:

name: Staging Provision and Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - develop

#https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Log in with Azure (Federated Credentials)
        run: |
                azd auth login `
                  --client-id "e7fd15fe-fc75-457e-8e03-227ff259a274" `
                  --federated-credential-provider "github" `
                  --tenant-id "ff18155b-8577-4821-9a09-ead38d2eb1d9"
        shell: pwsh

      - name: Azure Dev Provision
        run: azd provision --no-prompt
        env:
          AZURE_ENV_NAME: 'production'
          AZURE_LOCATION: 'eastus'
          AZURE_SUBSCRIPTION_ID: 'e40c39fd-1bd0-4fb7-860f-3c1f79ab48eb'

      - name: Azure Dev Deploy
        run: azd deploy --no-prompt
        env:
           AZURE_ENV_NAME: 'production'
           AZURE_LOCATION: 'eastus'
           AZURE_SUBSCRIPTION_ID: 'e40c39fd-1bd0-4fb7-860f-3c1f79ab48eb'

**Comment by vhvb1989** [comment]
>  I've tried Blueprint contributor and owner of the resources group

That's not enough. You need Admin or Owner for the subscription (not resource group)

**Comment by varndellwagglebee** [comment]
I gave our service principle Owner access and it worked.  Thank you for your assistance.
