### ISSUE TITLE
[Docs] Prune DevHub and update template names

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2211]
![image](https://github.com/Azure/azure-dev/assets/8949415/5c3d63d2-9d5e-4cf8-8d8f-1f887cef1df3)

We need to go through DevHub and make sure that all template names have been updated to reflect https://github.com/Azure/azure-dev/issues/2073

**Comment by gkulin** [comment]
closed by https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4431
