### ISSUE TITLE
Improve UX of hook output

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2213]
![image](https://github.com/Azure/azure-dev/assets/8949415/6ea07a0c-eb77-4864-9148-a86e827fe95b)

**Comment by savannahostrowski** [comment]
@Austinauth Do we think this just needs a newline?

**Comment by Austinauth** [comment]
@savannahostrowski @wbreza @vhvb1989 

Truthfully I'm not 100% sure whats happening here. There's a lot going on that top line. If this is all one step, I believe what should happen is the sub-step copy should truncate to ... when it goes off screen (and not break to a new line). 

The status of the sub-step should never close at `|       |` it should just say `(✓) Done` on one line.

**Comment by wbreza** [comment]
This is related to #1930 and #1948

This occurs because the writing of the hook execution happens in a different component to our standard process and they end up stepping on each other.  

I have a WIP update but it is too large of a change to address before GA.
