### ISSUE TITLE
Improve documentation on pre/post command hooks

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2224]
"Pre/post scripts also cool, but still I'm not entirely clear about the flow of environment variables into them/out of them"

**Comment by savannahostrowski** [comment]
@gkulin What iteration should this be assigned to? August? September?

**Comment by gkulin** [comment]
August will work! @savannahostrowski

**Comment by savannahostrowski** [comment]
Might be good to consider also adding details about how to consume environment variables via hooks here.

**Comment by rajeshkamal5050** [comment]
@gkulin similar issue #2607 and its discussion https://github.com/Azure/azure-dev/discussions/1613#discussioncomment-6661906

Is this incorporated for the upcoming release i.e., Aug 9 1.2.0?

**Comment by gkulin** [comment]
completed via https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4774
