### ISSUE TITLE
todo-java-postgresql-terraform deploy fail in Linux and Mac

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#2233]
**Describe the issue:**
When run `azd up`,  in **linux** get error as follow:

![image](https://github.com/Azure/azure-dev/assets/80496810/3497bfac-085e-455e-a09d-5966b933b07a)

in **Mac** get error as follow:

![image](https://github.com/Azure/azure-dev/assets/80496810/2d3dc66b-2385-4ce6-b51d-682a873bab2f)

**Repro Steps:**
1. Run`azd auth login`
2. Run `azd init -t todo-java-postgresql-terraform -b staging`.
3. Run `azd up`

**Environment:**
- OS: MacOS desktop, Linux desktop.
- Template: todo-java-postgresql-terraform
- Branch: staging
- Azd version: 0.9.0-beta.2-daily.2772915  (commit https://github.com/Azure/azure-dev/commit/08ff66607eb70b25d189aefce0d21070fe84630d)

**Expected behavior:**
 Run `azd up` can pass for `todo-java-postgresql-terraform`

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
Linux issue
- Seems to be captured as part of know issues - https://github.com/Azure-Samples/todo-java-postgresql-terraform/#error-creating-administrator @yiliuTo @fangjian0423 how to fix it?

Mac issue
- Seems a local-exec of script requires psql. Please install psql

**Comment by fangjian0423** [comment]
Linux issue

- This is not template's issue, we have mentioned it in https://github.com/Azure/awesome-azd/issues/76#issuecomment-1447638955. Maybe be we could use KeyVault instead of AAD admin settting on the template. How do you think about it? @rajeshkamal5050 

Mac issue

- Please install psql, the README mentiond it in [**Prerequisites** section](https://github.com/Azure-Samples/todo-java-postgresql-terraform#prerequisites).

**Comment by v-xuto** [comment]
@rajeshkamal5050 This issue can be reproduced when running the command `azd pipeline config --provider azdo`.

**Environment:**
OS: Windows desktop, MacOS desktop, Linux desktop, WSL ,CodeSpace and Devcontainer in VS Code.
Template: todo-java-postgresql-terraform
Branch: staging
Azd version: azd version 0.9.0-beta.2-daily.2786873 (commit https://github.com/Azure/azure-dev/commit/de89effa931a89e8125e520e5bc3ff473f014fb5)

The error message as follows:
![image](https://github.com/Azure/azure-dev/assets/57166602/94af0882-71f8-416f-9eba-8f74d544ed1d)

**Comment by blow-hey** [comment]
@fangjian0423, @rajeshkamal5050 After installing psql, the 2nd part of the mac issue will not reproduce.

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 This issue can be reproduced when running the command `azd pipeline config --provider azdo`.

**Environment:**


- OS: Windows desktop, MacOS desktop, Linux desktop, WSL and Devcontainer in VS Code.
- Template: todo-java-postgresql-terraform
- Branch: staging
- Azd version: azd version 1.1.0-beta.1-daily.2845223 (commit https://github.com/Azure/azure-dev/commit/9e11674b30a1b0c456fbd8a042d6f5af77ec6188)
- 
The error message as follows:
![image](https://github.com/Azure/azure-dev/assets/80496810/146d96f9-2aac-4d6d-9fa8-ebd48339d44c)

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 This issue can be reproduced when running the command `azd pipeline config --provider azdo`.

**Environment:**


- OS: Windows desktop, MacOS desktop, Linux desktop, WSL and Devcontainer in VS Code.
- Template: todo-java-postgresql-terraform
- Branch: staging
- Azd version: azd version 1.0.3-beta.1-daily.2905893 (commit https://github.com/Azure/azure-dev/commit/a7126c9e3b8573d3874c47adf0caad927a551d76)
