### ISSUE TITLE
[Issue] arm64 beta doesnt work in dev container

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#2235]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd-darwin-arm64-beta % ./azd-darwin-arm64 version
azd version 0.9.0-beta.2 (commit afa7ac6e839be8304b86b3df6b8525a97e48a532)

**Describe the bug**

The beta seems to work in my arm64 Terminal, but not in a Dev Container with this Dockerfile:

```
ARG IMAGE=python:3.11
FROM mcr.microsoft.com/devcontainers/${IMAGE}
RUN export DEBIAN_FRONTEND=noninteractive \
     && apt-get update && apt-get install -y xdg-utils \
     && apt-get clean -y && rm -rf /var/lib/apt/lists/*
```

It gives an error:

```
vscode ➜ /workspaces/chatgpt-quickstart (pamelas-fork) $ chmod +x azd-darwin-arm64 
vscode ➜ /workspaces/chatgpt-quickstart (pamelas-fork) $ ./azd-darwin-arm64 
bash: ./azd-darwin-arm64: cannot execute binary file: Exec format error
```

Notably, the Dev Container reports an architecture of "aarch64" while Terminal reports "arm64".

**To Reproduce**

Use Dockerfile to make Dev Container, download zip from releases, extract zip, drag and drop to Dev Container, chmod, run.

**Environment**

Version: 1.79.0-insider (Universal)
Commit: 2c73d2651cc525b27fc697b820743098a204ec01
Date: 2023-05-04T22:14:17.675Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: Yes

**Comment by rajeshkamal5050** [comment]
> Update: I realize I should try the non-darwin arm64 build!

Yes, we have started to publish arm64 bits in preview/beta - https://github.com/Azure/azure-dev/releases/download/azure-dev-cli_0.9.0-beta.2/azd-darwin-arm64-beta.zip

Keep us posted on what you find. @ellismg has also been trying arm64 bits from DevContainer.

**Comment by pamelafox** [comment]
Hm, I don't actually see a non-darwin arm64 option there. (The only Linux option listed is amd64) Which of those should work in a non-platform-emulated Dev Container on M1s?

**Comment by danieljurek** [comment]
@pamelafox -- I added `azd-linux-arm64` to the most recent azd release https://github.com/Azure/azure-dev/releases/download/azure-dev-cli_0.9.0-beta.2/azd-linux-arm64-beta.tar.gz .. It'll be automatically released going forward. 

Also, future releases will contain `azd-linux-arm64-beta` (note the added `-beta` at the end) in the compressed file... so your Dockerfile will need to take that into account from the next release going forward.

**Comment by ellismg** [comment]
@pamelafox - I was able to use the azd-linux-arm-beta bits locally on an ARM container running on my M1 mac.

See: https://github.com/Azure-Samples/azure-search-openai-demo/issues/195#issuecomment-1552219371 for the edits I made to the dev container locally. They are more or less what you would expect.

This worked fine for me and I was able to use `azd` inside the container without issue.

**Comment by pamelafox** [comment]
Thanks for the Dockerfile patch! I didn't know the right incantation to get it installed in the container (might be helpful to link to that for others who want to try it). I'm now using it on the same repo and `azd up` is chugging along.
