### ISSUE TITLE
CloudShell documentation

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#2262]
Document azd on CloudShell limitations 

* `azd auth login` uses CloudShell authentication transparently (no need to log in but can log in with service principal or `--use-device-token` if desired) 
* The `aca` templates will not deploy because [CloudShell does not support building Docker containers in the CloudShell session](https://learn.microsoft.com/en-us/azure/cloud-shell/troubleshooting#you-cant-run-the-docker-daemon). Use a non-ACA image 
* CloudShell [may timeout during long deployments](https://learn.microsoft.com/en-us/azure/cloud-shell/limitations#usage-limits), make sure the session does not become idle (this is a CloudShell limitation) 
* Update SUPPORT.md to direct to GitHub issues

**Comment by gkulin** [comment]
https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4646
