### ISSUE TITLE
[Issue] azd function secretOrRandomPassword brings the error "lookup <key-vault-host>: no such host"

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-dev#2281]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 0.9.0-beta.2 (commit afa7ac6e839be8304b86b3df6b8525a97e48a532)

**Describe the bug**
When using the funtion `secretOrRandomPassword` to store a secret in Key Vault in `main.parameters.json` like below:
```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    ...
    "psqlAdminPassword": {
      "value": "$(secretOrRandomPassword ${AZURE_KEY_VAULT_NAME} psqlAdminPassword)"
    },
    ...
  }
}
```

Then when running the command `azd down`, it will delete the Key Vault but won't delete the associated information in the `.azure` folder, e.g., azd environment var `AZURE_KEY_VAULT_NAME` is still there.
Then when next time I run `azd up`, it will read this `AZURE_KEY_VAULT_NAME` to fetch the secret, but that Key Vault has already been deleted. Then I could get the below error:
```output
ERROR: deployment failed: failing invoking action 'provision', planning deployment: planning infrastructure provisioning: creating parameters file: substituting command output inside parameter file: reading secret 'psqlAdminPassword' from vault 'kv-eioej5up42tow': getting key vault secret: Get "https://kv-eioej5up42tow.vault.azure.net/secrets/psqlAdminPassword/?api-version=7.3": dial tcp: lookup kv-eioej5up42tow.vault.azure.net: no such host
```

**To Reproduce**
Using any AZD template which uses `secretOrRandomPassword`, e.g., https://github.com/Azure-Samples/todo-csharp-sql/
run the below three commands in order:
```shell
azd up
# should input yes when asking whether to delete resources
azd down
azd up
```

**Expected behavior**
In the above scenario, when I run `azd up` for the second time, it should behave the same as the first time. Otherwise, I have to run `azd env new` to create a new env then I could be able to run `azd up`.

**Environment**
Information on your environment:
    * Language name and version: Java 17
    * IDE and version : Intellij Ulimate 2023, windows

**Comment by yiliuTo** [comment]
@weikanglim cool, thanks for the quick response. I believe this could be fixed with the change you mentioned:

> With this change, AZURE_KEY_VAULT_NAME, if it is defined as a bicep deployment output, will be removed after running azd down.

Please let me know when the fix gets released.

**Comment by rajeshkamal5050** [comment]
@yiliuTo fix has been released. Please try the latest bits.

**Comment by yiliuTo** [comment]
Close this issue since it has been fixed.
