### ISSUE TITLE
[Issue] azd auth login does not use BROWSER env

### ISSUE THREAD

**Issue by heaths** [Azure/azure-dev#2291]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here: azd version 0.9.0-beta.3 (commit e564b122af7c1cb92bc54755f32930d661dddda2)

**Describe the bug**
Despite having the `BROWSER` env var defined as "explorer.exe" - a not uncommon practice in WSL2 - I get an error when I try to run `azd auth login`:

```
ERROR: logging in: failed to authenticate: exec: "xdg-open,x-www-browser,www-browser": executable file not found in $PATH
```

I'd prefer not to install any of these as it pulls in a lot of dependencies I don't need for WSL2, where I do most of my non-C# development.

**To Reproduce**
1. Provision a fresh distro in WSL2
2. Install azd
3. (Assuming bash): `export BROWSER="explorer.exe"`
4. `azd auth login`

**Expected behavior**
My default browser should open.

**Environment**
Information on your environment:
    * Language name and version: go version go1.20.1 linux/amd64
    * IDE and version: none (WSL2)

**Comment by weikanglim** [comment]
MSAL library uses [pkg/browser](https://pkg.go.dev/github.com/pkg/browser).

Related issue here: https://github.com/pkg/browser/issues/41

**Comment by ellismg** [comment]
One thing to note is that we use a slightly different package in the implementation of `azd monitor` to open a web-browser, which IIRC is a fork of pkg/browser that the GitHub folks wrote, which also respects BROWSER before falling back to xdg-open.

It would be nice perhaps if the MSAL library allowed us to provide some function with a signature like `OpenBrowser(url string) error` so they didn't have to have policy here, maybe we can open a PR.

@heaths, one thing to note, is that I think with `--no-install-recommends` the footprint of `xdg-utils` should be quite small, since I think it is just shell scripts.  IIRC, `xdg-open` itself respects `BROWSER` when it is set.

You could also consider putting some simple `xdg-open` script on the path that just does `$BROWSER $1` or something.

**Comment by heaths** [comment]
Thanks. I will give that a try. If xdg-open can be installed minimally and I can do without the `BROWSER` env var, even better. Lately (not sure exactly when it started), Windows 11 is opening _explorer.exe_ itself when it didn't before. Wonder if that was a regression (intentional or otherwise) when explorer.exe was refreshed with tabs and more.

**Comment by heaths** [comment]
Update: it was a small install for xdg-utils, yes, but doesn't work. `azd auth open` reports, "xdg-open: no method available for opening ***". Oddly, it opens explorer.exe twice as opposed to other CLIs e.g., `gh`, that open it only once. So xdg-open does use the `BROWSER` env var but not successfully.

Fortunately, I can work around this using `azd auth login --use-device-code` but it'd be nice for users not to have to worry about this. I suspect - I hope, rather - we have a healthy community of devs on Windows using WSL2.

**Comment by heaths** [comment]
Update 2: `sudo apt install --no-install-recommends wslu` - which installs `wslview` - works with and without `BROWSER` being set.

**Comment by enjoysparkling** [comment]
Had the same error this morning on a fresh install of `azd`.  I ran `azd auth login --use-device-code` to get around it.

Note, I did also have to use `sudo hwclock -s` for an `az login` error (because the laptop came back from sleep mode?).

**Comment by ellismg** [comment]
FWIW - I opened https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/422 in MSAL to give us the ability to configure what package is used to open the browser.  With this change, we should be able to provide an implementation that honors BROWSER before falling back to `xdg-open` or the other tools that `pkg/browser` looks for.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you take care of consuming MSAL changes once they are released?

**Comment by vhvb1989** [comment]
See https://github.com/Azure/azure-dev/issues/2446

for wsl with ubuntu 22 on win11, azd requires: `sudo apt update && sudo apt install xdg-utils wslu`

**Comment by weikanglim** [comment]
Full instructions for `wslu` on WSL installation here: https://wslutiliti.es/wslu/install.html

**Comment by heaths** [comment]
This auth flow works in other commands without wslu, though. While that works around the problem, not requiring additional dependencies that similar CLIs e.g., `az` don't need would probably be ideal for user adoption and ease of use.

**Comment by weikanglim** [comment]
I do agree with that. It looks like what `az` relies on as a fallback is using `powershell.exe -C "Start-Process <url>"`. Supposedly, if WSL is set up to allow include the Windows host PATH (default installation option), this would allow Windows to handle opening the URL with the default configured browser.

https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/332
https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/333/files

Something less nice about this is that it takes 4-8 seconds for me:

```
weilim@weilim-z4:~$ time powershell.exe -NoProfile -Command "Start-Process www.bing.com"

real    0m8.062s
user    0m0.000s
sys     0m0.009s
```

**Comment by weikanglim** [comment]
I think we're also supporting `BROWSER` with this change?

**Comment by heaths** [comment]
Odd they choose powershell. It has a slower startup cost. You could instead `cmd.exe /s /c start "%s"`. Much faster.

**Comment by vhvb1989** [comment]
> Odd they choose powershell. It has a slower startup cost. You could instead `cmd.exe /s /c start "%s"`. Much faster.

@heaths @weikanglim , it looks like `cmd` requires a more elaborated set of scape characters.  For example, I had to replace `&` for `^&` (for the query parameters).  Idk if that's the only thing to scape of if there will be more stuff in the future.

I am setting powershell as the fallback when `cmd start` fails: https://github.com/Azure/azure-dev/pull/2576/files#diff-ffdf55a2ce62d4d28c8ba5ef58397ce1fce6d062f4dc19cec32450cc72dbdb65R371

**Comment by weikanglim** [comment]
Using [wikipedia](https://en.wikipedia.org/wiki/Escape_character#Windows_Command_Prompt), with original [source](https://learn.microsoft.com/en-us/previous-versions//cc723564(v=technet.10)?redirectedfrom=MSDN), and [ss64](https://ss64.com/nt/syntax-esc.html) as the base reference then conducting my own testing:

The special characters seems to be: `<`, `>`, `^`, `|` and `&`. I did not observe `(`, `)`, and `\` needing escape:

```golang
package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	res, err := exec.Command("cmd.exe", "/C", "start", "http://localhost:8080/?^<^>^|^^^&a=1^&b=2\\()").CombinedOutput()
	fmt.Println(string(res))

	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
```
