### ISSUE TITLE
Better code coverage insights

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#2295]
As a azd developer, I'd like to see better code coverage insights:
1. As a product owner, I'd like to visualize, analyze code coverage trends over time, identifying areas needing coverage
2. As a code reviewer, I'd like to visualize code coverage diff for any new PR changes to provide data and insights to identify if a change is risky, and how to best mitigate risk.

I'd like to propose usage of [codecov](https://about.codecov.io), which is widely popular amongst open source repositories. It is also already widely used in Azure and Microsoft org repositories (login to codecov to see the list).

To onboard our repository, if we choose to, would require the following steps (these steps are mostly repeated of codecov's instructions when trying to setup a repository):
1. Set `CODECOV_TOKEN` as a secret in our CI provider (Pipelines).
2. Update our workflows to download `codecov` binary and upload coverage to codecov's central servers
3. Authorize the codecov-app to be able to post comments on PRs in azure-dev (can be follow-up)
4. Figure out what may be remaining from 3, due to our unique GitHub + Azure Pipelines setup

We may end up disabling PR comments if it ends up being noisy in the future, but it may make sense for the short-term as we build up muscles.

**Comment by danieljurek** [comment]
@weikanglim -- We've not encountered much value when using code coverage tools that analyze coverage "over time"... There are a couple options today that can help: 

1. Provide a required "floor" for code coverage in pipelines and fail the pipeline if code coverage drops below that floor. We do this today in C++ 
2. We already upload code coverage reports today in every pipeline build (including PR builds) for example: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2880996&view=codecoverage-tab

![image](https://github.com/Azure/azure-dev/assets/2158838/921c46c0-a985-4efb-aaca-1a5895c35534)

The report that we're publishing today already shows areas that require coverage: 

![image](https://github.com/Azure/azure-dev/assets/2158838/c1c09a31-2a17-4f9c-bc86-2643623616cd)

**Comment by weikanglim** [comment]
Since I last chatted with @danieljurek , we're thinking to enable something like codecov, but after getting code coverage generated in GitHub actions.

**Comment by weikanglim** [comment]
Closing this -- not something we plan to do anytime soon.
