### ISSUE TITLE
VSCode issue when running `show` with no init'd project.

### ISSUE THREAD

**Issue by RailokGit** [Azure/azure-dev#2296]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-dev.views.workspace.application.resolve
Error type: 1
Error Message: Process 'azd show --no-prompt --cwd "/workspaces/openai-plu...' exited with code 1
Error: Error: loading environment: reading environment name: no default response for prompt 'Please enter a new environment name:'

Version: 0.6.0
OS: linux
OS Release: 5.4.0-1106-azure
Product: Visual Studio Code
Product Version: 1.78.2
Language: ru

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.
</details>

**Comment by ellismg** [comment]
From the error it sounds like this was happening when an environment had not yet been created for the project (so `azd init` has not yet been run).

I wonder what the behavior of `azd show` should be in this case.  There is some information we can provide (like project structure) but we wouldn't be able to load any information about the resources themselves.

**Comment by bwateratmsft** [comment]
We only run `azd show` if an `azure.yaml` file exists, so the workspace got at least that far. But without an environment I guess `azd show` errors.

I like the idea of having it output as much info as it can; no environment isn't unlike an environment that just hasn't been deployed yet.
