### ISSUE TITLE
[env select] - validate env name exists

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#2306]
When running `azd env select foo` , azd is not validating that `foo` is an existing environment.  Azd is setting the env name to `foo` without creating the environment. This causes that running `azd provision` next would ask if you want to create the `foo` environment.

Example:
![image](https://github.com/Azure/azure-dev/assets/24213737/edd91c3d-7bc9-4777-b236-35b41b3ef4da)

Expected:
Should azd fail if `azd env select` receives one environment name which does not exists?

**Comment by ellismg** [comment]
> Should azd fail if azd env select receives one environment name which does not exists?

Yeah, this feels like a reasonable thing for us to be doing here.
