### ISSUE TITLE
failed running post hooks: 'postprovision' hook failed with exit code: '127'

### ISSUE THREAD

**Issue by raj-microsoft** [Azure/azure-dev#2321]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
failed running post hooks: 'postprovision' hook failed with exit code: '127', Path: 'C:\Users\rajba\AppData\Local\Temp\azd-postprovision-3989770095.sh'. : exit code: 127

**Describe the bug**
unable to restore database from dump files

**To Reproduce**
You see this in the last step of azd provision

**Expected behavior**
restoration of data dump files into the postgres sql

**Environment**
Information on your environment:
    * azd version 1.0.1 (commit e0cd1aca716fa5d08704beade7dcc734fe68f5f1)
    * WSL2 Ubuntu 22.04.2 LTS

**Comment by rajeshkamal5050** [comment]
@raj-microsoft thanks for filing an issue. What was the template/sample application which you were running Azd with? Can you share the repo?
