### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by mokwenak** [Azure/azure-dev#2323]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:1.0.1

**Describe the bug**
Description of issue you're seeing...

**To Reproduce**
Steps to reproduce the behavior...

**Expected behavior**

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

**Comment by rajeshkamal5050** [comment]
@mokwenak not sure if it was accidentally filed. Couldn't find much details on the issue. Can you add more details?

**Comment by ellismg** [comment]
@mokwenak - Feel free to re-open this with more content
