### ISSUE TITLE
July Release - Docs Plan

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#2330]
Changes impacting docs
- CloudShell - @danieljurek 
- GHA, Azd DevContainer feature - @hemarina @ellismg 
- azd docs command - @vhvb1989 @gkulin was this for this iteration?
- RG scoped deployments - @ellismg

**Comment by danieljurek** [comment]
Cloud Shell docs -- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4646

**Comment by savannahostrowski** [comment]
@gkulin Has this been taken care of with Alex?

**Comment by rajeshkamal5050** [comment]
@gkulin closing this one. If anything pending, lets take care of it as part of the August iteration release.
