### ISSUE TITLE
Investigate using the GH CLI auth UX in Codespaces

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2332]
The GH CLI has a slightly nicer auth flow than azd in Codespaces today.

They show a user a code, tell them to copy it and then hit enter to open the browser to paste it in. This is a slightly more streamlined UX, can we adopt it?

**Comment by savannahostrowski** [comment]
@vhvb1989 Have you considered this? Is this possible?

**Comment by savannahostrowski** [comment]
Nah, this is different. We do a _very_ similar flow but require a user to either control click the URL or copy-paste the URL into another browser window.

GH CLI just asks the user to hit enter and brings them to another window. It's a little more streamlined but it'd also be nice to have the authentication flow as them.

**Comment by vhvb1989** [comment]
@savannahostrowski , it was easy to make the change. Made a PR for you.

**Comment by savannahostrowski** [comment]
This is the Victor way! I file an issue and by end of day, there's a PR! Always going above and beyond :D

Thanks for taking a look!
