### ISSUE TITLE
[Feature] Application Scaffolding Wizard

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2342]
# What is the “Application Scaffolding Wizard” as a feature? Why add an “Application Scaffolding Wizard” to the Azure Developer CLI? 

Some developers know what Azure services they’d like to use to get their application up on Azure. The idea with this feature is that the Azure Developer CLI scaffold a skeleton template (read below) for them to work from.  

# High-level UX flow 

At a high level, the experience should be as follows: 

- User runs ‘azd init` in an empty or non-empty directory 

- User selects to onboard using the scaffolding wizard 

- User is presented with a wizard type experience (to be designed) and makes selections from the menus (see selection options below) to scaffold their application 

- User ends up with infra/ and azure.yaml in their current working directory 

- User can now continue to iterate on their application, modify the IaC as they desire and then run azd up whenever they are ready.

Note that this does not cover cases where a user wants to incrementally add infrastructure to their project. That composability will come next semester. This flow is also not as “streamlined” as the flow in https://github.com/Azure/azure-dev/issues/705. This flow supports giving experienced developers a foundation to build upon. It is expected that they will tweak the IaC. We will start with support for Bicep here and expand to Terraform if there’s sufficient demand (we’d need to expand our IaC module library to accommodate).
```[tasklist]
### Tasks
- [ ] Review the existing brief & artifacts, capture intial questions, prep to start in following sprint [Austin Auth] [Jul 12 - 26]
```

**Comment by savannahostrowski** [comment]
Assigning to @Austinauth for design. Once designs are finalized, we will past this on for implementation

**Comment by stliu** [comment]
is there a feature plan that support add azd to an existing project/application?

**Comment by savannahostrowski** [comment]
Hey @stliu check out #705!

**Comment by savannahostrowski** [comment]
Deprioritizing this item for now, given other commitments and potentially refinements to the original intention/spec. Will revisit in the fall

**Comment by savannahostrowski** [comment]
Closing in favour of #2386 as I think this will get handled together
