### ISSUE TITLE
Generate CI/CD pipelines

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2343]
In addition to forming an opinionated infrastructure folder we should also explore generating default github actions / azdo pipeline files to help enable pipeline configuration as mentioned in #1420

_Originally posted by @wbreza in https://github.com/Azure/azure-dev/issues/705#issuecomment-1397729936_

**Comment by timheuer** [comment]
dupe of #2752?

**Comment by rajeshkamal5050** [comment]
Yes @timheuer closing one.
