### ISSUE TITLE
[Issue] azd should use it's own kubeconfig file 

### ISSUE THREAD

**Issue by carmodyquinnms** [Azure/azure-dev#2351]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 1.0.1 (commit e0cd1aca716fa5d08704beade7dcc734fe68f5f1)

**Describe the bug**
If one uses a KUBECONFIG file to access clusters and has it set in the environment where they are running "azd up" then the deployment step will fail and inherits the KUBECONFIG rather than creating one it's own for the new cluster.

**To Reproduce**
Steps to reproduce the behavior...
Perform azd up, and azd down and azd up again with an AKS cluster and a deployment and the deployment will fail because the deleted cluster is still in the kubeconfig file.
OR
export KUBECONFIG=<a valid kube config file to some cluster>
azd up
# the deployment step will fail to go to the new aks cluster in the azd up step

**Expected behavior**
When running azd up and provisioning a new AKS cluster, the deployment step of azd up should deploy to the newly provisioned cluster and not inherit the KUBECONFIG from the parent shell.

**Comment by wbreza** [comment]
Resolved with #2488

@carmodyquinnms Since `azd` now allows users to specify their own `KUBECONFIG` it should now be fully managed by the user and `azd` will just use the config provided instead of creating its own.

Happy to re-open if you still feel there is more work to be done here.
