### ISSUE TITLE
[Issue]: Does not support AKS Clusters with AAD/Azure RBAC (localAccounts disabled)

### ISSUE THREAD

**Issue by carmodyquinnms** [Azure/azure-dev#2359]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 1.0.1 (commit e0cd1aca716fa5d08704beade7dcc734fe68f5f1)

azd deploy will not work without local admin enabled on AKS which is not secure.  Not able to deploy with a cluster that has AAD with Azure RBAC.  

**To Reproduce**
disable local accounts on AKS and attempt to run azd deploy of anything to it.
**Expected behavior**
expect to be able to deploy applications to secure AKS clusters that have AAD/Azure RBAC and have local accounts disabled

Here is a copy of the error:
```
   POST https://management.azure.com/subscriptions/82e70289-bf40-45f9-8476-eab93d2031f4/resourceGroups/cqtst14-rg/providers/Microsoft.ContainerService/managedClusters/aks-cqtst14/listClusterAdminCredential?api-version=2022-09-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armcontainerservice/v2.2.0 (go1.20.3; linux),azdev/1.0.1 (Go go1.20.3; linux/amd64)
   X-Ms-Correlation-Request-Id: 5904cdc2f9fb46e2a4ab5f979dfcaf5c
   --------------------------------------------------------------------------------
   RESPONSE Status: 400 Bad Request
   Cache-Control: no-cache
   Content-Length: 175
   Content-Type: application/json
   Date: Mon, 05 Jun 2023 22:59:00 GMT
   Expires: -1
   Pragma: no-cache
   Server: nginx
   Strict-Transport-Security: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Correlation-Request-Id: 5904cdc2-f9fb-46e2-a4ab-5f979dfcaf5c
   X-Ms-Ratelimit-Remaining-Subscription-Writes: REDACTED
   X-Ms-Request-Id: 2689b34b-7551-413b-80ca-2aa509d926f2
   X-Ms-Routing-Request-Id: REDACTED

2023/06/05 17:58:59 main.go:47: Retry: response 400
2023/06/05 17:58:59 main.go:47: Retry: exit due to non-retriable status code
  (x) Failed: Deploying service api

ERROR: failed deploying service 'api': failing invoking action 'deploy', failed retrieving cluster admin credentials. Ensure your cluster has been configured to support admin credentials, POST https://management.azure.com/subscriptions/82e70289-bf40-45f9-8476-eab93d2031f4/resourceGroups/cqtst14-rg/providers/Microsoft.ContainerService/managedClusters/aks-cqtst14/listClusterAdminCredential
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadRequest
--------------------------------------------------------------------------------
{
  "code": "BadRequest",
  "details": null,
  "message": "Getting static credential is not allowed because this cluster is set to disable local accounts.",
  "subcode": ""
}
--------------------------------------------------------------------------------

TraceID: 5904cdc2f9fb46e2a4ab5f979dfcaf5c
```

**Comment by wbreza** [comment]
### Integration with kubelogin for Azure RBAC support

When Azure RBAC is enabled or local accounts are disabled `azd` needs to leverage `kubelogin` to successfully authenticate into the AKS cluster.

In these scenarios `azd` will call `kubelogin convert-kubeconfig -l azd` and leverage the current logged in principal of `azd` to authenticate into the cluster.

This command will update the `kubeconfig` context with to leverage `kubelogin` to generate access tokens via `azd`.

- Add new `azd` login mode to `kubelogin` CLI
- Integrate with `kubelogin` CLI to automate authentication into Azure RBAC enabled AKS clusters
