### ISSUE TITLE
[Issue]: azd deploy not able to handle properly formatted configmap for AKS

### ISSUE THREAD

**Issue by carmodyquinnms** [Azure/azure-dev#2367]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
```
cquinn@DESKTOP-72A3U61:.../ratings-nodejs-azd-akslza$ azd version
azd version 1.0.1 (commit e0cd1aca716fa5d08704beade7dcc734fe68f5f1)
```

**Describe the bug**
azd deployment fails on mongodb configmap yaml

**To Reproduce**
use the attached mangodb configmap yaml and attempt to deploy with azd deploy and it fails with the following error message:
```
(x) Failed: Deploying service api
ERROR: failed deploying service 'api': failing invoking action 'deploy', failed applying kube manifests: failed process templates, failed applying template 'src/manifests/api/ratings-mongodb-configmap.yaml', failed replacing env vars, missing closing brace
```

**Expected behavior**
azd deploy is expected to either handle the yaml file which is formatted properly

[ratings-mongodb-configmap.yaml.txt](https://github.com/Azure/azure-dev/files/11667498/ratings-mongodb-configmap.yaml.txt)

**Comment by rajeshkamal5050** [comment]
@wbreza can you take a look? Please adjust milestone based on findings.
