### ISSUE TITLE
Give me a way to bring in the "core" bicep files

### ISSUE THREAD

**Issue by bradygaster** [Azure/azure-dev#2368]
I'd love to have a way of doing something like `azd init --core` to lay down all the core infrastructure files when i set up a new AZD template. I typically start with my code, then i `azd init`, then i go pull from other places. it'd be nifty if there was either a switch on `init` or an additional to command to drop in all the core files.

**Comment by savannahostrowski** [comment]
We'd discussed adding core/ to the Bicep starter template. Might be worth doing that while we sort out the whole registry thing @ellismg.

**Comment by jongio** [comment]
As a workaround you can do `azd init -t jongio/azd-starter-bicep-core`, which is updated with latest from azure-dev/main

**Comment by rajeshkamal5050** [comment]
Pulling this into next sprint since @aaronpowell was also requesting core/default ones to be available as part of starters.
