### ISSUE TITLE
Define and implement connection between Azure DevOps and Azure

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#237]
In order to [support](https://github.com/Azure/azure-dev/issues/101) `Azure DevOps` as a repository for a `azd - project` and use its CI pipeline: 

- Azure DevOps requires communicating with Azure in the same way as GitHub can currently perform provisioning and deployment in Azure.

GitHub, uses a secret credential from one Azure's App Registration (with enough security roles assigned) to authenticate to Azure and perform operations.  The [federated identity](https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation-create-trust-github?tabs=azure-portal) for GitHub and Azure is not yet implemented.

Azure DevOps supports multiple [connection types](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#common-service-connection-types).  

I suggest using the [Resource Manager](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#azure-resource-manager-service-connection) type.

It looks like there is not a REST API for DevOps to create the connection.  
Users would need to follow the instructions from DevOps to create the connection to allow pipelines to authenticate and work with Azure.

azd would provide the pipeline and refer customers to how to create the connection.

**Comment by jongio** [comment]
Please see the README in the .azdo folder for the exact steps needed to automate this.  Everything except creating the org is automatable.

**Comment by vhvb1989** [comment]
already implemented
