### ISSUE TITLE
Unable to install azd on WSL Ubuntu

### ISSUE THREAD

**Issue by ruslany** [Azure/azure-dev#2380]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
N/A

**Describe the bug**
Getting this error when trying to install azd on WSL:

$ curl -fsSL https://aka.ms/install-azd.sh | bash
install-azd: ERROR: Symlink folder does not exist: /usr/local/bin. The symlink folder should exist and be in $PATH
install-azd: ERROR: Create the folder (and ensure that it is in your $PATH), specify a different folder using -s or --symlink-folder, or specify an empty value using -s "" or --symlink-folder ""
install-azd: ERROR: An error was encountered during install: SymlinkFolderDoesNotExist
install-azd: ERROR:
install-azd: ERROR: To send an error report to Microsoft, check that AZURE_DEV_COLLECT_TELEMETRY is not set and then run:
install-azd: ERROR: curl -fsSL https://aka.ms/install-azd-report.sh | bash
install-azd: ERROR:
install-azd: ERROR: Running the above script will send data to Microsoft. To learn more about data collection see:
install-azd: ERROR: https://go.microsoft.com/fwlink/?LinkId=521839
install-azd: ERROR:
install-azd: ERROR: You can also file an issue at https://github.com/Azure/azure-dev/issues/new?assignees=&labels=&template=issue_report.md&title=%5BIssue%5D

**To Reproduce**
Create a brand new WSL v2.0 and run the installation script

**Expected behavior**
Installation should succeed

**Environment**
WSL Ubuntu

**Comment by ruslany** [comment]
For some reason the usr/local/bin was missing. I recreated it and the install seemed to complete with this output:

azd-linux-amd64
NOTICE.txt
mkdir: cannot create directory ‘/opt/microsoft’: Permission denied
install-azd: Creating /opt/microsoft/azd requires elevated permission. You may be prompted to enter credentials.
install-azd: Writing to /opt/microsoft/azd/ requires elevated permission. You may be prompted to enter credentials.
install-azd: Writing to /usr/local/bin/ requires elevated permission. You may be prompted to enter credentials.
install-azd: Successfully installed to /opt/microsoft/azd
install-azd: Symlink created at /usr/local/bin/azd and pointing to /opt/microsoft/azd/azd-linux-amd64
install-azd:
install-azd: The Azure Developer CLI collects usage data and sends that usage data to Microsoft in order to help us improve your experience.
install-azd: You can opt-out of telemetry by setting the AZURE_DEV_COLLECT_TELEMETRY environment variable to 'no' in the shell you use.
install-azd:
install-azd: Read more about Azure Developer CLI telemetry: https://github.com/Azure/azure-dev#data-collection

However I still cannot logon - getting this error: https://github.com/Azure/azure-dev/issues/2382

**Comment by ruslany** [comment]
Also when I run the uninstall script it produces bunch of permission denied errors. It seemed to delete the azd but the script should be improved so it does not show permission errors.

rm: cannot remove '/usr/local/bin/azd': Permission denied
Writing to /usr/local/bin/azd requires elevated permission. You may be prompted to enter credentials.
rm: cannot remove '/opt/microsoft/azd/.installed-by.txt': Permission denied
rm: cannot remove '/opt/microsoft/azd/azd-linux-amd64': Permission denied
rm: cannot remove '/opt/microsoft/azd/NOTICE.txt': Permission denied
Writing to /opt/microsoft/azd requires elevated permission. You may be prompted to enter credentials.

azd may have downloaded binaries to ~/.azd/bin and, depending on how azd was used on this machine,
may have downloaded binaries to other users' home directories in their .azd/bin directory.
These binaries will need to be removed manually.
To remove such binaries from your home directory, run 'rm -rf ~/.azd/bin'.

**Comment by vhvb1989** [comment]
@ruslany can you try running `curl -fsSL https://aka.ms/install-azd.sh | sudo bash`

**Comment by vhvb1989** [comment]
Take a look to: https://github.com/Azure/azure-dev/blob/main/cli/Dockerfile#LL7C1-L7C1

You can see the list of all the external dependencies which could be eventually required for `azd`, depending on the project (this is the entire set).  

When working with WSL, you will also want to install the WSL utilities from: https://wslutiliti.es/wslu/install.html#ubuntu
Utilities will help you to open your local browser from WSL, for example.

**Comment by ruslany** [comment]
@vhvb1989 - thanks for quick reply. The aka.ms install link worked better. Maybe the docs should be updated to use that link?

 curl -fsSL https://aka.ms/install-azd.sh | sudo bash
[sudo] password for ruslany:
azd-linux-amd64
NOTICE.txt
install-azd: Successfully installed to /opt/microsoft/azd
install-azd: Symlink created at /usr/local/bin/azd and pointing to /opt/microsoft/azd/azd-linux-amd64
install-azd:
install-azd: The Azure Developer CLI collects usage data and sends that usage data to Microsoft in order to help us improve your experience.
install-azd: You can opt-out of telemetry by setting the AZURE_DEV_COLLECT_TELEMETRY environment variable to 'no' in the shell you use.
install-azd:
install-azd: Read more about Azure Developer CLI telemetry: https://github.com/Azure/azure-dev#data-collection

However the azd auth login still gives me this error:

 azd auth login

ERROR: logging in: failed to authenticate: exec: "xdg-open,x-www-browser,www-browser": executable file not found in $PATH

I already have latest WSL utils:

sudo apt install ubuntu-wsl
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ubuntu-wsl is already the newest version (1.481).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

I am able to login using az cli (az login), which opens a browser window. So this looks like something specific to azd.

**Comment by ruslany** [comment]
@danieljurek - I ran the installation script and then uninstall script. Also tried the deb package instructions and also ran apt remote -y azd. I think at one of those steps the /usr/local/bin was deleted. I manually recreated it and that unblocked the install.  The azd login still does not work though as described here - https://github.com/Azure/azure-dev/issues/2382

BTW - the [update instructions](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/install-azd?tabs=winget-windows%2Cbrew-mac%2Cscript-linux&pivots=os-linux) in the docs seem to be not correct. for the update they still reference curl -fsSL https://aka.ms/uninstall-azd.sh | bash, sam as for uninstall.

**Comment by rajeshkamal5050** [comment]
@danieljurek what are the next steps here? any fix or workaround needed?

**Comment by ellismg** [comment]
FWIW, On the `azd auth login` error failing with `ERROR: logging in: failed to authenticate: exec: "xdg-open,x-www-browser,www-browser": executable file not found in $PATH`, this can happen if either `xdg-open` and friends are not installed.  You might try installing `xdgutils` (which gives you xdg-open) and `wslu` (which gives you the WSL specific command that allows `xdg-open` to pop a browser when using WSL.
