### ISSUE TITLE
Error: no project exists; to create a new project, run `azd init` - when using `azure.yml` instead of `azure.yaml`

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#2381]

**Comment by savannahostrowski** [comment]
@vhvb1989 This is a bug right?

**Comment by vhvb1989** [comment]
@savannahostrowski yes, `.yml` or `.yaml` should be both valid, IMO.
Unless you want to only allow `azure.yaml` by design

**Comment by savannahostrowski** [comment]
Yeah I was asking because we have an issue for adding support for .yml already.

https://github.com/Azure/azure-dev/issues/364

**Comment by rajeshkamal5050** [comment]
@savannahostrowski @vhvb1989 marking this as a duplicate of #364
