### ISSUE TITLE
azd auth login does not work on WSL Ubuntu

### ISSUE THREAD

**Issue by ruslany** [Azure/azure-dev#2382]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.0.1 (commit e0cd1aca716fa5d08704beade7dcc734fe68f5f1)

**Describe the bug**
Getting this error when trying to login:

azd auth login

ERROR: logging in: failed to authenticate: exec: "xdg-open,x-www-browser,www-browser": executable file not found in $PATH

**To Reproduce**
Steps to reproduce the behavior...

Install azd with this script:
curl -fsSL https://aka.ms/install-azd.sh | bash
run 
azd auth login

**Expected behavior**
Login successful

**Environment**
Information on your environment:
WSL Ubuntu

**Additional context**

**Comment by rajeshkamal5050** [comment]
@ruslany thanks for reporting this. There is a similar issue #2291. Marking this as a duplicate.

As a workaround you could do `azd auth login --use-device-code` https://github.com/Azure/azure-dev/issues/2291#issuecomment-1561268901
