### ISSUE TITLE
Update all templates with Azure DevOps pipeline for provision, build and deploy

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#239]
In order to [support](https://github.com/Azure/azure-dev/issues/101) `Azure DevOps` as a repository for a `azd - project` and use its CI pipeline: 

- Templates must provide a `yaml` file to describe an Azure DevOps pipeline to be run on every code push to `main` branch which run provision and deploy.  Similar to how GitHub workflows are currently defined.

**Comment by jongio** [comment]
Just want to make sure you know that templates already have azdo pipeline files in .azdo folder.

**Comment by vhvb1989** [comment]
this is implemented already
