### ISSUE TITLE
Validate container app revision after deployment

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#2398]
`azd deploy` should validate the state of a container app during deployment to ensure it is in a `Provisionsed` state and is considered `Healthy`.

Today after the revision is deployed it is assumed to be health.  Azd should perform the following validations:

1. New revision has transitioned into the `Provisioned` state and `Running`
2. New revision is in a `Healthy` state

**Comment by rajeshkamal5050** [comment]
@wbreza updating to keep it specific to ACA. Since #3260 handled for AppService with its new `Deployment Status API`

**Comment by mip1983** [comment]
I'd like to know how to do this also, both to know that the revision came up successfully, but also to run some post deploy automated tests
