### ISSUE TITLE
Unable to deploy to a container app that uses workload profiles

### ISSUE THREAD

**Issue by ruslany** [Azure/azure-dev#2402]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.0.1 (commit e0cd1aca716fa5d08704beade7dcc734fe68f5f1)

**Describe the bug**
When trying to deploy to a container app that uses workload profiles I get this error:

```bash
ERROR: failed deploying service 'acachat': failing invoking action 'deploy', updating container app service: updating container app revision: begin updating ingress traffic: PATCH https://management.azure.com/subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.App/containerApps/<appname>
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: WorkloadProfilePropertyNotSupportedInApiVersion
--------------------------------------------------------------------------------
{
  "error": {
    "code": "WorkloadProfilePropertyNotSupportedInApiVersion",
    "message": "WorkloadProfiles configuration is not supported in  api version. Use 2022-11-01-preview or above."
  }
}
--------------------------------------------------------------------------------

TraceID: 3cfceb3ea54d1ceb7c9c46876069b8c3
```

**To Reproduce**
Use api version 2022-11-01-preview in the bicep files for creating containerapp environment and apps. Run azd provision. Then run azd deploy

**Expected behavior**
azd deploy should work with workload profiles or there should be a way to specify an API version to use when PATCH a container app.

**Environment**
Information on your environment:
      * Language name and version - py
      * IDE and version : Visual Studio Code

**Comment by rajeshkamal5050** [comment]
@wbreza is this a change in the Bicep which users could modify or something in the core azd bits?

**Comment by wbreza** [comment]
@ruslany Please take a look at the private azd build from PR #2412 and confirm that this addresses your issue.  Thank you for reporting this!

**Comment by savannahostrowski** [comment]
@wbreza Is this okay to close now, given that we have #2413?

**Comment by wbreza** [comment]
> @wbreza Is this okay to close now, given that we have #2413?

@savannahostrowski This one is already closed :)  Let me know if I misunderstood the question.

**Comment by cyptus** [comment]
@ruslany how can i influence the environment type after this patch (from an `azure.yaml`)? i dont find any documentation of how you did this?
