### ISSUE TITLE
how to implent to azure auth login to AzureChinaCloud[Issue]

### ISSUE THREAD

**Issue by huqianghui** [Azure/azure-dev#2411]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.0.1 (commit e0cd1aca716fa5d08704beade7dcc734fe68f5f1)

**Describe the bug**
I set my cloud env to AzureChinaCloud by the command:

az cloud set --name AzureChinaCloud

**To Reproduce**
Steps to reproduce the behavior...

**Expected behavior**
azd auth login command can direct to CN domain.

**Comment by savannahostrowski** [comment]
Hey there! azd does not currently support Azure China Cloud (see #2280). We are investigating adding support for it.

I'll close this issue in favour of that one but please upvote/weigh in!
