### ISSUE TITLE
[Issue] Pipeline status URL is a 404

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#2425]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

chatgpt-quickstart % azd version
azd version 1.0.2 (commit 145e046b1ea9394bd4e1b1d539eb32e860d692fb)

**Describe the bug**

I ran azd pipeline config on https://github.com/pamelafox/chatgpt-quickstart/

and it says:

```
SUCCESS: Your GitHub pipeline has been configured!
Link to view your new repo: https://github.com/pamelafox/chatgpt-quickstart
Link to view your pipeline status: https://github.com/pamelafox/chatgpt-quickstart.git/actions
```

That final URL is a 404 however - it should not have .git in it.
The azd code does seem to have a call to trimSuffix of ".git" but maybe that call is too late?

**To Reproduce**

Git clone, run azd up and pipeline config on the repo linked above.

**Environment**

VS Code details:
Version: 1.79.0-insider (Universal)
Commit: b9a77b3c7b43f229a430b28070250d55e5d14858
Date: 2023-05-31T20:19:54.210Z
Electron: 22.5.4
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

**Comment by vhvb1989** [comment]
I remember some other issue from @jongio about this (I just couldn't find it to link it here).

@pamelafox , this is a known issue when the repo is set up using ssh, as the link has the `.git` at the end.  
azd takes the repo link in a similar way than running `git remote -v` 

Thank you for opening the issue.  I will fix it soon
