### ISSUE TITLE
[Issue] Federated credential is set only on main (not other branches)

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#2428]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 1.0.2 (commit 145e046b1ea9394bd4e1b1d539eb32e860d692fb)

**Describe the bug**

To test my azd workflow, I set the push to include my testing branch (cicd). However, when I do that, I get an error:

AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer: 'https://token.actions.githubusercontent.com/'. Assertion Subject: 'repo:pamelafox/sample-app-aoai-chatGPT:ref:refs/heads/cicd'. Assertion Audience: 'api://AzureADTokenExchange'. [https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation\r\nTrace](https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation/r/nTrace) ID: fcbeda46-d5f3-48c6-9058-84408cf47600\r\nCorrelation ID: 031d62c7-6267-4c89-aa09-64364f3235c8\r\nTimestamp: 2023-06-16 16:38:31Z",

I realized that's because the federated credentials are only set up for the main branch and pull_request, per:

https://github.com/Azure/azure-dev/blob/f84dbd154d5b12ce58ff1d475f29d063d9f6cdb9/cli/azd/pkg/pipeline/github_provider.go#L621

So I adjusted my workflow to include pull_request to get it working.

**To Reproduce**

Change azure-dev.yaml to include a non-main branch, push to that branch, see error.

**Expected behavior**

I was hoping it'd work. Maybe the code could check azure-dev.yaml to decide what to make credentials for? If not, maybe it could let the user know that it'll only work on main/pull_request.

**Environment**

CI/CD server, VS Code

**Comment by rajeshkamal5050** [comment]
@wbreza can we infer other non-main branches and make it work?

**Comment by wbreza** [comment]
> @wbreza can we infer other non-main branches and make it work?

@rajeshkamal5050 
Federated credentials require specifying branch name when creating the credential.  We have a few options:
If new branches are created after running `azd pipeline config` `azd` doesn't know these branches exist

1. Offer new flag on `azd pipeline config` to specify a `branch_name` that can be used
1. Scan for all branches on the repo and create credentials for each
1. User can manually update federated credentials in the Azure portal

Out of the above options I believe option 1 would provide the most value. Otherwise user can workaround this issue with option 3.

**Comment by vhvb1989** [comment]
@wbreza , when creating the ref-cred, azd should use whatever branch is currently the output of `git status`, as that's the branch that is likely to be pushed.
We should not be hardcoding `main`

**Comment by wbreza** [comment]
Agreed we can do better than hardcoding `main`.  I think that part of the issue is knowing that the credentials that are generated at the time of the command are only good on the branch that was initially pushed and that other/new branches will fail.

**Comment by pamelafox** [comment]
Hm, from a user perspective, I think I was hoping I could set it up from my testing branch, and then once it worked, I'd delete testing branch from the workflow file and leave it as main (or whatever is the prod branch name).

**Comment by wbreza** [comment]
> Hm, from a user perspective, I think I was hoping I could set it up from my testing branch, and then once it worked, I'd delete testing branch from the workflow file and leave it as main (or whatever is the prod branch name).

From a usability perspective that request makes total sense.  Based on the [GitHub -> Azure docs](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows#use-the-azure-login-action-with-openid-connect) around federated identity it unfortunately requires specifying an `Entity` to create the subject claim for the underlying OIDC request.

The `Entity` can either be an environment, branch, pull request or tag.  Today we use `main` branch as the default but once we better support GitHub environments (#2373) I could see this becoming easier.  Any branch then targeting the same azd environment name could share the same the same federated identity.

**Comment by jongio** [comment]
Related: https://github.com/Azure/azure-dev/issues/2040
