### ISSUE TITLE
Add a note for `azd env new` for users to know that the new created environment is set as the selected env after it is created

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#2434]
There's no way for customers to know that after running `azd env new`, the new env will be set as the selected env.

Running `azd env help` and/or `azd env new -h` should mention this detail

**Comment by rajeshkamal5050** [comment]
Parking under `august milestone` for the reference doc updates.

cc: @savannahostrowski

**Comment by savannahostrowski** [comment]
I think this is a help text update. Seems pretty minimal.

**Comment by ellismg** [comment]
I updated the help text in #2471, so this was fixed for the 1.1.0 release.
