### ISSUE TITLE
Allow recording/playback for `Test_CLI_Up_Down_ContainerApp`

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#2450]
When trying to record/playback `Test_CLI_Up_Down_ContainerApp`, there are a few issues that needs to be addressed:

1. Tokens, registry passwords as part of ACR token exchange will need to be sanitized before recordings can be checked in.
2. Proxy configuration will not affect `docker` CLI for operations like `push` and `login`, since the client talks to the docker daemon which isn't proxied unless with system configuration. [Docs](https://docs.docker.com/config/daemon/systemd/#httphttps-proxy).

To solve number 2, it seems like we could take the strategy of having a "proxy" for tools that azd integrates with. A minimal implementation for container app is to simply return exit code 0 for `push` and `login`. The way the proxy could be configured in tests is using PATH priority to include a "tools" directory that contains the proxied docker/other tool implementations.

**Comment by ellismg** [comment]
> To solve number 2, it seems like we could take the strategy of having a "proxy" for tools that azd integrates with. A minimal implementation for container app is to simply return exit code 0 for push and login. The way the proxy could be configured in tests is using PATH priority to include a "tools" directory that contains the proxied docker/other tool implementations.

I recall @wbreza wondering if we could do a similar recorder strategy, but at our our command runner level, for external tool.  If we had that, it feels like we could use it here?  That would certainly be more work than these stubs that we put on the $PATH to override the real tools, but might be the right long term move?

**Comment by weikanglim** [comment]
Unsure about my own bandwidth -- moving to backlog for now
