### ISSUE TITLE
Update logProgress for write() to be continuous instead of always using a new line

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#2452]
I would like to keep it as such for this first iteration. (write() === writeLine())
There's a few things to define for moving into the model you proposed. Mostly related to what to do on line's overflow. 
On current behavior, we are truncating the line to the terminal's width.

I will create a new issue to design and plan supporting a pure write() model

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-dev/pull/2364#discussion_r1239086305_

**Comment by ellismg** [comment]
We are just taking care of this as part of the PR, so no need to have this issue hanging around.
