### ISSUE TITLE
[VSCode] [azd init] Error: 'azd' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by nik251** [Azure/azure-dev#2454]
Does this occur consistently? Yes
Repro steps:

1. press select a template and initialize path when scaffolding code
2.

Action: azure-dev.commands.cli.init
Error type: 1
Error Message: Process 'azd template list --output json' exited with code 1
Error: 'azd' is not recognized as an internal or external command,
operable program or batch file.

Version: 0.6.0
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.79.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.js:2:928019
```

</details>

**Comment by ellismg** [comment]
From the error message here, it seems like `azd` is not on the $PATH.  I believe that the extension when it installs `azd` will try to modify the `PATH` of the currently running code instance to save the user from having to restart, but maybe that's not working here.

It's possible that restarting VS Code (so it can pick up the new `PATH` value) will fix this issue for you, @nik251.

**Comment by nik251** [comment]
Thank you!

**Comment by bwateratmsft** [comment]
Agreed, restarting VSCode ought to fix the issue. I'll take a look at the logic and see if something is no longer working. @ellismg did the install path change at all? I know there are multiple ways to install and the VSCode extension only handles the install to `%LOCALAPPDATA%\Programs\Azure Dev CLI`

**Comment by bwateratmsft** [comment]
I am able to reproduce.

**Comment by bwateratmsft** [comment]
**Workaround:** Restart VSCode (maybe completely, i.e. close _all_ windows and reopen)

**Comment by bwateratmsft** [comment]
The fix for this issue has just been released in Azure Developer CLI extension version 0.7.0.
