### ISSUE TITLE
[Issue] todo-python-mongo-aca azd deploy fails with tagging error unable to find 'azd-service-name: api'

### ISSUE THREAD

**Issue by lao8n** [Azure/azure-dev#2456]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 1.0.2 
**Describe the bug**
Description of issue you're seeing...
I get an error that 'unable to find a resource tagged with `'azd-service-name: api'` despite the fact that in the api.bicep i have 
   ` tags: union(tags, { 'azd-service-name': serviceName })` where` param serviceName string = 'api'`
![Screenshot 2023-06-23 203635](https://github.com/Azure/azure-dev/assets/30158430/de55b083-cbf1-48dc-bc6e-306b2e9efc99)
**To Reproduce**

Steps to reproduce the behavior...
1. Git clone https://github.com/azure-samples/todo-python-mongo-aca
2. Follow quick start - it fails on` azd up` in the azd deploy stage
**Expected behavior**
I expected the deployment to complete and the resources in azure portal to be created. This works when I do the same process for the non-containerized version [todo-python-mongo](https://github.com/Azure-Samples/todo-python-mongo)
**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

**Comment by lao8n** [comment]
was able to get it to work by 1. commenting out all the `azd-service-name` tags 2. deploying resources successfully 3. uncommenting tags 4. redeploying again - not sure why this is necessary - perhaps an ordering issue?

**Comment by ellismg** [comment]
> not sure why this is necessary - perhaps an ordering issue?

Yes - that seems strange and is not expected.  I suspect there could be an issue where there an eventual consistency issue where we don't find the container app resource group in the set of resource groups we examine and then assume it is not found.  I am wondering if these changes you made are a red herring.

I just deployed this template with 1.0.2 and was successful, and didn't have to jump through the hoops you outlined here.

Good to hear you are unblocked with a workaround, at least.

**Comment by lao8n** [comment]
yeah my theory was there might be some eventual consistency problem which my workaround deploying the resource so it was there first might be solving - who knows maybe it was unrelated
