### ISSUE TITLE
Short description should be added to Bicep files in /core

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#2466]
`description` should be added at the top to all Bicep files in /core to help folks understand what the module does:
```
metadata description = 'Short description for module...'
```

From 0.18 onwards, Bicep will show description in help text when mouse-over a module you reference: 
![image](https://github.com/Azure/azure-dev/assets/8701892/bb904d52-f957-45d6-a6dc-bd591c640a9d)

**Comment by rajeshkamal5050** [comment]
@v-xuto can you pick this up and put out a PR for review with @jongio @savannahostrowski ?

**Comment by v-xuto** [comment]
> @v-xuto can you pick this up and put out a PR for review with @jongio @savannahostrowski ?

Got it. We will pick up this issue and create PR for it.

**Comment by v-xuto** [comment]
@rajeshkamal5050 PR https://github.com/Azure/azure-dev/pull/2534  is ready, please review.
