### ISSUE TITLE
Install PostgreSQL fail in action logs

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#2478]
**Describe the issue:**
For `todo-java-postgresql-terraform` template , when executing `azd pipeline config`, get error as follow:

- ubuntu-latest
 ![image](https://github.com/Azure/azure-dev/assets/80496810/25805a96-63cc-412b-8149-25e92b779773)
- macos-latest
 ![image](https://github.com/Azure/azure-dev/assets/80496810/62861547-afb0-493a-98ee-8321c7bd5661)
- windows-latest
 ![image](https://github.com/Azure/azure-dev/assets/80496810/a4c5b84e-3ae2-47c2-9e86-d41b33e56f1f)

**Repro Steps:**

1. Run `azd auth login`.
2. Run `azd init -t todo-java-postgresql-terraform -b staging`
3. Open `azure-dev.yml` file in `.github/workflows`. Remove two lines of code on container image. Add GHA code after checkout step(Shown as below).  
![image](https://github.com/Azure/azure-dev/assets/80496810/bb8d99a9-bd97-4d1d-b460-946b2ce12e0a)

4. Run `azd pipeline config` and verify the action pipeline.

5. Change the code to `windows-latest` or `macos-latest` as shown below. ![image](https://github.com/Azure/azure-dev/assets/80496810/d51e3e40-a979-4ed6-b37e-7c6e9beedece)

6. Re-verify the action pipeline.

**Environment:**

- Template: todo-java-postgresql-terraform
- Azd version: 1.0.2 

**Expected behavior:**
 Run `azd pipeline config` can pass.

@hemarina for notification.

**Comment by v-jiaodi** [comment]
@hemarina Retest using the method mentioned above, the `Install PostgreSQL` step can pass, but you will encounter the same issue as https://github.com/Azure/azure-dev/issues/2475. After adding the `Install Java17 SDK` step , the final error encountered is https://github.com/Azure/azure-dev/issues/2232 
![image](https://github.com/Azure/azure-dev/assets/80496810/3073809f-06bc-4e9f-853e-33fbac401ef4)

**Comment by v-jiaodi** [comment]
@hemarina Can you provide the PR link  for adding this command?
Rerun it after changing part of azd provision, you will encounter the same issue as https://github.com/Azure/azure-dev/issues/2477. According to https://github.com/Azure/azure-dev/issues/2477#issuecomment-1631864379 add step for it, the error log is as follows:

![image](https://github.com/Azure/azure-dev/assets/80496810/42d1b2ee-3db2-4e65-bfbd-999008c523ef)

>
> The step of Install Java17 SDK is same code as [#2475 (comment)](https://github.com/Azure/azure-dev/issues/2475#issuecomment-1631714980), right?

Yes

**Comment by rajeshkamal5050** [comment]
@fangjian0423 @yiliuTo can you also look into this as part of the cleanup/refactoring?

**Comment by fangjian0423** [comment]
The PR https://github.com/Azure/azure-dev/pull/2556 use deploymentscript to replace of psql command line tools to run psql commands. When the PR merged, the issue could be closed.
