### ISSUE TITLE
Costing information should be more prominent on templates

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2480]
I have gotten this comment from various developers at conferences and also from developer advocates lately ("I don't feel confident in how much this will cost if I try it")

Some options:
1. Promote the costing calculator to a section instead of a note, which can be easy to miss
2. Adopt a structure similar to https://github.com/pamelafox/flask-surveys-container-app#costs

**Comment by vhvb1989** [comment]
@savannahostrowski , azd can use the cost management sdk (probably as an opt-in feature) to display the cost after `azd provision` (probably cost per day or per hour).

see:
https://learn.microsoft.com/en-us/rest/api/cost-management/
https://github.com/Azure/azure-sdk-for-go/tree/934612c4f2b59cf590e5f041d1aea5381abf70e2/sdk/resourcemanager/costmanagement/armcostmanagement

Additionally, we could introduce some `azd monitor cost` of something to open the Azure portal with the cost manager filtering the resource group for the azd-env

**Comment by savannahostrowski** [comment]
I think ideally we'd want to show this proactively. Folks are getting caught up on cost before they even get started.

**Comment by rajeshkamal5050** [comment]
@gkulin can we close this?

**Comment by pamelafox** [comment]
Speaking as an azd template developer, not all azd templates have cost info yet. I'll try adding to https://github.com/Azure-Samples/azure-search-openai-demo today as I saw a comment that it cost some folks $200 to deploy, and they had to request a refund. (Mostly due to Form recognizer running in the postprovision).
