### ISSUE TITLE
[Issue] azd pipeline credentials do not appear to have permissions to run azd down

### ISSUE THREAD

**Issue by carmodyquinnms** [Azure/azure-dev#2486]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
N/A since this is in github

**Describe the bug**
I am trying to create a github workflow to delete infrastructure (azd down) using azd configured pipeline credentials.  However I get an error that appears as though the credentials do not have the necessary permissions to delete the infrastructure:
```
ERROR: deleting infrastructure: error deleting Azure resources: deleting resource groups: user denied delete confirmation
```
Please see both the job and the log archive attached.

**To Reproduce**
Create azure credentials with the "azd pipeline config" command and then attempt to run "azd down" from a github workflow.

**Expected behavior**
Expect the permissions to allow for deleting the infrastructure that was previously created

**Environment**
Information on your environment:
    * github workflows

**Additional context**
Please see both the job and the log archive attached.
[azd-down.yml.txt](https://github.com/Azure/azure-dev/files/11968474/azd-down.yml.txt)
[logs_131.zip](https://github.com/Azure/azure-dev/files/11968468/logs_131.zip)

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you triage this?

**Comment by vhvb1989** [comment]
@carmodyquinnms , instead of `azd down --no-prompt --debug` , please use:

`azd down --no-prompt --force --purge`

--force will skip asking user to confirm deleting, which has `No` as the default answer (that's why --no-prompt is picking `no` ).

--purge will make sure to purge any soft-deleted resources
