### ISSUE TITLE
URLs printed on pipeline config are invalid

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2512]
Looks like we are using the protocol set for Git here (e.g. I use SSH). However, this makes the links unclickable.

![image](https://github.com/Azure/azure-dev/assets/8949415/c2ef0808-3801-45ef-b504-e0152f48b543)

**Comment by vhvb1989** [comment]
duplicated of: https://github.com/Azure/azure-dev/issues/2425
