### ISSUE TITLE
Feature suggestion: Provide an "assume yes" setting or flag

### ISSUE THREAD

**Issue by tpetchel** [Azure/azure-dev#2513]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

```
azd version 1.0.2 (commit 145e046b1ea9394bd4e1b1d539eb32e860d692fb)
```

**Describe the bug**

To enable unattended scenarios such running `azd` from a Bash script or CI/CD pipeline, it would be convenient to have an "assume yes" mode. This would suppress the "(y/N)" prompts by automatically answering "y"es.

This would be similar to:

* `DEBIAN_FRONTEND=noninteractive` on Debian systems
* `AZURE_CORE_DISABLE_CONFIRM_PROMPT=1` with the Azure CLI
* `--yes` and `--force` flags found with many other CLIs

I can't use `--no-prompt` because this defaults to "no" in commands such as `azd down`.

As a workaround, I was able to write "y" to a file and redirect stdin. It would feel better to use a flag or environment variable. :) 

Apologies if this already exists. I didn't see anything listed [here](https://learn.microsoft.com/azure/developer/azure-developer-cli/manage-environment-variables) or in the sources.

**To Reproduce**

N/A

**Expected behavior**

Here are a few examples that demonstrate the concept. Each would suppress the prompt and proceed with "yes"; it's just a matter of which method folks prefer.

```
# environment variable
AZD_DISABLE_CONFIRM_PROMPT=1 azd down

# environment variable, flavor 2
export AZD_DISABLE_CONFIRM_PROMPT=1
azd down

# --yes
azd down --yes
# --force
azd down --force
```

**Environment**
Information on your environment:

* macOS 13.4.1 (22F82)
* `azd` version 1.0.2

**Additional context**

**Comment by vhvb1989** [comment]
Hello @tpetchel 
Have you tried running `azd down --force --purge`

By using `force` and `purge` you can bypass the `azd down` confirmations:

```
Flags
        --docs                  : Opens the documentation for azd down in your web browser.
    -e, --environment string    : The name of the environment to use.
        --force                 : Does not require confirmation before it deletes resources.
    -h, --help                  : Gets help for down.
        --purge                 : Does not require confirmation before it permanently deletes resources that are soft-deleted by default (for example, key vaults).
```

**Comment by tpetchel** [comment]
Hi @vhvb1989,

Wow, how did I miss that? `azd down --force` was even in one of my examples! I think I was so focused on a global option that I missed the flag on this specific command.

This is great. Sorry for the silly question and thanks for the quick response. :)
