### ISSUE TITLE
Feature suggestion: Make it easy to access deployment details

### ISSUE THREAD

**Issue by tpetchel** [Azure/azure-dev#2514]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

```
azd version 1.0.2 (commit 145e046b1ea9394bd4e1b1d539eb32e860d692fb)
```

**Describe the bug**

Although `azd up` prints details such as the service hostname, it might be convenient to also provide an `azd show` or similar command that provides common details about the deployment. Having a separate command would enable you to: 

* fetch details later, after you've run `azd up`
* store details in a variable for later use
* avoid the need to go to the Azure portal or dig up the appropriate Azure CLI command

Apologies if this functionality already exists. I didn't see anything [here](https://learn.microsoft.com/azure/developer/azure-developer-cli/reference).

**To Reproduce**

N/A

**Expected behavior**

Here's how I might get the service endpoint today by using the Azure CLI:
 
```
$ az webapp list --resource-group default-dev-rg --query "[].defaultHostName" --output tsv
default-dev-ochogy5totpus-app-service.azurewebsites.net
```

Here's a sketch of what `azd show` might look like: 

```
$ azd show --query "[].defaultHostName" --output tsv
default-dev-ochogy5totpus-app-service.azurewebsites.net
```

The two are similar, but the latter saves me from looking up the Azure CLI command and specifying details such as the resource group.

**Environment**

* macOS 13.4.1 (22F82)
* `azd` version 1.0.2

**Additional context**

**Comment by vhvb1989** [comment]
Hello @tpetchel 

After running `azd up`, you can run `azd env get-values` (see [docs](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/reference#azd-env-get-values)), to display all the infra-outputs.

Another util command is `azd show -o json`, which will display info about the services

**Comment by tpetchel** [comment]
Hey @vhvb1989,

`azd show` is exactly what I asked for! I didn't know about this because it's not [documented](https://learn.microsoft.com/azure/developer/azure-developer-cli/reference) and `azd --help` doesn't show it. 

I trust they'll be included in a future update. Thanks for the quick response!
