### ISSUE TITLE
ERROR: getting target resource: expecting only '1' resource tagged with 'azd-service-name: api', but found '2'

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2526]
I keep getting this on fresh deploy (no changes made to template) of https://github.com/Azure-Samples/todo-csharp-cosmos-sql (v1.1.0 of azd)
![image](https://github.com/Azure/azure-dev/assets/8949415/c6de2b2c-b777-4c94-b0d9-e8c7fde5c03b)

**Comment by vhvb1989** [comment]
This usually happen when you deploy the same template in a different location, which would give you an existing resource group, with the same name, on a different location having the same tag and confusing azd :)

**Comment by vhvb1989** [comment]
azd should use the location when looking for the resource group...

**Comment by savannahostrowski** [comment]
Hmmm, I used a new env names both times I tried.

At the very least, we should improve this error message.

**Comment by vhvb1989** [comment]
Haven't seen this in a while

**Comment by soni811** [comment]
@minLength(1)
param environmentName string = ''

param snowAppId string = ''
param appServicePlanName string
param resourceGroupName string
param apiServiceName string
param keyVaultServiceName string
param appServiceSkuName string // Set in main.parameters.json

var abbrs = loadJsonContent('abbreviations.json')
var resourceToken = tolower(uniqueString(subscription().id, environmentName))
var tags = {
  'azd-service-name': 'api'
  'Env': 'Dev'
  'fin_snowappid': snowAppId
}

// Create a resource group
resource resourceGroup 'Microsoft.Resources/resourceGroups@2021-04-01' = {
  name: resourceGroupName
  location: location
  tags: tags
}

// Deploy the chatgum-api
module chatgmapi 'core/host/appservice.bicep' = {
  name: 'web'
  scope: resourceGroup
  params: {
    name: empty(apiServiceName) ? apiServiceName : '${abbrs.websitesAppService}'
    location: location
    tags: tags
    runtimeName: 'python'
    runtimeVersion: '3.12'
    appCommandLine: 'python3 -m gunicorn main:app'
    scmDoBuildDuringDeployment: true
    managedIdentity: true
    use32BitWorkerProcess: appServiceSkuName == 'F1'
    alwaysOn: appServiceSkuName != 'F1'
    appSettings: {
      AZURE_ENV_NAME: environmentName
      AZURE_LOCATION: 'westus'
      AZURE_RESOURCE_GROUP: resourceGroupName
      AZURE_KEY_VAULT_NAME: keyVaultServiceName
      DISABLE_SSL_VERIFY: 'True'
      APP_LOG_LEVEL: 'INFO'
    }
  }
}

// Create an App Service Plan
module appServicePlan 'core/host/appserviceplan.bicep' = {
  name: 'appserviceplan'
  scope: resourceGroup
  params: {
    name: appServicePlanName
    location: location
    sku: {
      name: appServiceSkuName
      capacity: 1
    }
  }
}

using for this  i am face this issue how to best ways to solve this
