### ISSUE TITLE
Wrong README for todo-csharp-cosmos-sql (not Mongo!)

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2527]
https://github.com/Azure-Samples/todo-csharp-cosmos-sql. We reference MongoDB but this should be SQL?

![image](https://github.com/Azure/azure-dev/assets/8949415/ef6e802f-7e9a-4d03-a19b-48da341fa50b)

![image](https://github.com/Azure/azure-dev/assets/8949415/e7ff5142-adca-4aaa-987b-116c786d494a)

See arch diagram and also https://github.com/Azure-Samples/todo-csharp-cosmos-sql/blob/main/infra/main.bicep
![image](https://github.com/Azure/azure-dev/assets/8949415/372003f3-3196-4c53-9b02-ded5a8aa22cd)

**Comment by rajeshkamal5050** [comment]
@jongio @vhvb1989 do you know if this todo-csharp-cosmos-sql does provision Cosmos DB(MongoDB API) similar to todo-java-mongo and todo-nodejs-mongo?

**Comment by vhvb1989** [comment]
@rajeshkamal5050 , yes, it uses `cosmos-sql-db` (see: https://github.com/Azure-Samples/todo-csharp-cosmos-sql/blob/main/infra/app/db.bicep#L26)

The template name is good. The readme needs to be updated
