### ISSUE TITLE
Feature Request: Azure DevOps Pipeline Task for azd

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-dev#2536]
The recent 1.1.0 announcement with a dedicated task for GitHub Actions was awesome.  Can we have the same for Azure DevOps Pipelines please?

**Comment by pamelafox** [comment]
Ah, I realize the TODO samples already demonstrate an ADO pipeline: https://github.com/Azure-Samples/todo-python-mongo/blob/main/.azdo/pipelines/azure-dev.yml
So we'll add that. 
(I realize now that @adrianhall's request is for an ADO task, to streamline that pipeline)

**Comment by rajeshkamal5050** [comment]
@savannahostrowski @ellismg adding it to Backlog.

**Comment by vhvb1989** [comment]
Created a PR to add the DevOps Task: https://github.com/Azure/setup-azd/pull/35

Here are some screenshots of how it looks (tested on windows and linux pipelines)

![image](https://github.com/Azure/azure-dev/assets/24213737/f110c5d4-5026-476d-8dc6-00daa715f783)


![image](https://github.com/Azure/azure-dev/assets/24213737/e28dcee1-cf80-4a3f-8869-e673f8895d99)


I published this task as `private only` and tested it within the azd-devops organization.

The task is ready to be published so it is accessible by everyone.

**Comment by vhvb1989** [comment]
@adrianhall , we now have the Azure DevOps extension: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.azd

You can install it for your Azdo org and start using it
