### ISSUE TITLE
[Issue] Mac - arm64 out of beta

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#2542]

**Comment by danieljurek** [comment]
Things to consider: 

* Costs of releasing with increased manual testing (until we get better automation) 
* Installers (brew and install-azd.sh) 
* Do we need to check dependencies on binaries like bicep and gh when running from the `~/.azd/bin` folder? (e.g. if someone upgraded from x86_64 to ARM64 do we also require ARM64 versions of bicep, gh, etc.?)

**Comment by rajeshkamal5050** [comment]
@danieljurek agreed on the unknown issues and its resulting manual testing required for regression/releases.

In general, feeling confident about the cross compiled bits. Don't think we have any functional aspect in code that is specific to ARM64(except for installers/package management and dependency handling i.e., Bicep, GH CLI) which I think is sort of had been tested manually by folks(within the team @ellismg @weikanglim and also from @pamelafox).

I would feel better off to make the ARM64 bits public/GA and take the additional cost for manual testing/regressions.

**Comment by rajeshkamal5050** [comment]
Out of beta as of https://github.com/Azure/azure-dev/releases/tag/azure-dev-cli_1.4.0
