### ISSUE TITLE
[Request] azd package writes output folder to an env variable

### ISSUE THREAD

**Issue by paulyuk** [Azure/azure-dev#2543]
Azd package is quickly becoming one of my favorite tools to easily and reliably create the app package build before provisioning and deployment.  It's useful for automation and diagnostics.

That said, to better enable pipelines and tools, I request the output path for *this package gets written to an environment variable or something that can be looked up in scripts/code/pipelines.  Another alternative I suppose is a flag that enables reliable output to a known folder.

@jongio @ellismg @savannahostrowski

**Comment by savannahostrowski** [comment]
IMO, this seems like a reasonable ask and could be very useful. @ellismg for his thoughts here but at a glance, I can't see any reason we shouldn't do this.
