### ISSUE TITLE
[Request] azd up/provision console print the Subscription and Region

### ISSUE THREAD

**Issue by paulyuk** [Azure/azure-dev#2544]
Once you've done the azd up or provision once, the subscription and region you chose is stashed away in the environment files.  

At scale, when working with enough environments, it gets painful to know which subscription/region/token you're targeting.

The request is to always print the RG/subscription/region in every provision and up, so you know where you're sending those bits.  This is incredibly useful for diagnostics and communication.  

@jongio @ellismg @savannahostrowski

**Comment by savannahostrowski** [comment]
That's fair - I think it's pretty low touch for us to just have a blurb at the top of provision output (where the grey text lives now)
that says something like:

"Provisioning in *rg* in *region* using *subscription*" (where rg, region, subscription are placeholders)

![image](https://github.com/Azure/azure-dev/assets/8949415/d58b26f1-9bbe-4d7d-adb4-655ac70ca55b)


or similar.

@Austinauth for his thoughts as well.

**Comment by savannahostrowski** [comment]
I guess my follow up would be: does RG need to be in that blurb if it's printed out as the first thing in the provision output?

**Comment by Austinauth** [comment]
If there is valid concern about not knowing which region or subscription you're provisioning and deploying to beyond the initial `azd up`, would it be worth having them confirm the region and subscription before executing the command?

**Comment by rajeshkamal5050** [comment]
@ellismg @savannahostrowski adding it to the Germanium bucket. We can pull it into iterations/sprints as part of planning.

**Comment by john0isaac** [comment]
Hey everyone,
I intend to work on this as a part of Hacktoberfest but I have a question.

Your request is to print the subscription before the resource group when someone runs any of the 2 commands azd up or azd provision.
Am I correct?
