### ISSUE TITLE
[Issue] "azd env refresh" output could be a little nicer

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#2563]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 1.1.0 (commit ea9cb12575734ee6a5f99c4d415c1a51d6f32d3e)

**Describe the bug**

When I run azd env refresh, I see:

```
vscode ➜ /workspaces/azure-search-openai-demo (main) $ azd env refresh
? Enter a new environment name: openai-search
  (✓) Done: Downloading Bicep
? Select an Azure Subscription to use: 86. ca-pamelafox-demo-test (XXX)
  (✓) Done: Retrieving locations...
? Select an Azure location to use: 44. (US) South Central US (southcentralus)
  (✓) Done: Retrieving locations...
  |       | Normalizing output parametersEnvironments setting refresh completed
```

I think it could use a new line between parameters and Environments.

**To Reproduce**

I ran `azd env refresh` on https://github.com/Azure-Samples/azure-search-openai-demo/

**Expected behavior**

I expect the most beautiful CLI output in the world from my beloved azd.

**Comment by wbreza** [comment]
@savannahostrowski UX updates from #2537 should address this.

**Comment by rajeshkamal5050** [comment]
Marking this as completed, since the above PR is merged.
