### ISSUE TITLE
First run telemetry notice

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#2580]
Print telemetry notice on first run. 

Conditions: In Cloud Shell AND have not run previously (no ~/.azd/first-run file present) 
1. Disable telemetry for the command
2. Print telemetry notice
4. Create ~/.azd/first-run file

Will need some help from @weikanglim to ensure that telemetry is properly disabled.

**Comment by weikanglim** [comment]
Straightforward way is to update `initialize` in [telemetry.go](https://github.com/Azure/azure-dev/blob/4a0fd5fb6989405bc810fd7f13762d142f27da4b/cli/azd/internal/telemetry/telemetry.go#L89). If `initialize` returns `nil` for `TelemetrySystem`, telemetry is disabled.

Do you expect the telemetry notice to be printed before, or after the command execution?
