### ISSUE TITLE
[awesome-azd] create filters

### ISSUE THREAD

**Issue by gkulin** [Azure/azure-dev#2589]
create filters from this design: 
![image](https://github.com/Azure/azure-dev/assets/55554236/dbc7a53f-2a30-4b19-ad20-f61f2dd56494)

https://github.com/Azure/awesome-azd/issues/151

**Comment by rajeshkamal5050** [comment]
@gkulin @hemarina moving it to Germanium i.e., delivering for Ignite.

**Comment by savannahostrowski** [comment]
@hemarina is this addressed now?

**Comment by gkulin** [comment]
closed via https://github.com/Azure/awesome-azd/pull/190
