### ISSUE TITLE
[awesome-azd] create filter bar

### ISSUE THREAD

**Issue by gkulin** [Azure/azure-dev#2590]
- [ ] Default
- [ ] Search applied
- [ ] filter applied
- [ ] Search and filter applied

<img width="513" alt="image" src="https://github.com/Azure/awesome-azd/assets/104857065/acd82c5f-c892-49b6-8884-f58833ea37b9">

https://github.com/Azure/awesome-azd/issues/152

**Comment by rajeshkamal5050** [comment]
@gkulin @hemarina moving it to Germanium i.e., delivering for Ignite.

**Comment by savannahostrowski** [comment]
@gkulin Is this complete?
