### ISSUE TITLE
[awesome-azd] create search bar & result pages

### ISSUE THREAD

**Issue by gkulin** [Azure/azure-dev#2591]
- [ ] Search Bar
- [ ] Search Bar with Results
- [ ] Search Bar with no result page

https://github.com/Azure/awesome-azd/issues/153

**Comment by rajeshkamal5050** [comment]
@gkulin @hemarina moving it to Germanium i.e., delivering for Ignite.

**Comment by savannahostrowski** [comment]
@gkulin Is this complete?
