### ISSUE TITLE
Mac1 M1 and other architectures fail -- Deploy failed on javascript/npm specific Dockerfile -- "failed to reserve virtual memory"

### ISSUE THREAD

**Issue by paulyuk** [Azure/azure-dev#260]
I'm deploying the JS equivalent of a working Python dapr quickstart:
https://github.com/paulyuk/quickstarts/tree/azd/pub_sub/javascript/sdk

The `azd deploy` step fails on the Docker build step on the checkout service, and I cannot explain it since the `docker build ..` of the Dockerfil is ok on my local build.  I suspect something environmental.  

Error

> Azure/azure-dev-pr#8 [4/6] RUN npm install --production --silent && mv node_modules ../
> Azure/azure-dev-pr#8 sha256:402a395e4f71daead3ba427a1e06cbde38aa1f0d29ea323a18a21d84e17441dd
> Azure/azure-dev-pr#8 0.745 
> Azure/azure-dev-pr#8 0.745 #
> Azure/azure-dev-pr#8 0.745 # **Fatal process OOM in Failed to reserve virtual memory for CodeRange**
> Azure/azure-dev-pr#8 0.745 #
> Azure/azure-dev-pr#8 0.745 
> Azure/azure-dev-pr#8 0.745 qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
> Azure/azure-dev-pr#8 0.749 Trace/breakpoint trap
> Azure/azure-dev-pr#8 ERROR: executor failed running [/bin/sh -c npm install --production --silent && mv node_modules ../]: exit code: 133
> ------
>  > [4/6] RUN npm install --production --silent && mv node_modules ../:
> ------
> executor failed running [/bin/sh -c npm install --production --silent && mv node_modules ../]: **exit code: 133**
> : exit status 1

**Comment by rajeshkamal5050** [comment]
Closing this in favor of #1314
