### ISSUE TITLE
[CI/CD]  Error: making Read request on Azure KeyVault Secret AZURE-COSMOS-CONNECTION-STRING from template

### ISSUE THREAD

**Issue by thanhrieker** [Azure/azure-dev#2602]
- Already installed lasted version for azd

**Output from `azd version`**
azd version 1.1.0 (commit ea9cb12575734ee6a5f99c4d415c1a51d6f32d3e)

**Describe the bug**
I start adz from template following:

[](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/get-started?tabs=localinstall&pivots=programming-language-nodejs)
[](https://github.com/Azure-Samples/todo-nodejs-mongo-terraform/tree/main)

All working in local but when start "azd pipeline config --principal-name azd-dev-1035" actions from github I got error from github action logs:

`module.keyvault.azurerm_key_vault_secret.secrets[0]: Refreshing state... [id=https://kv-nmjmzgizmjiym.vault.azure.net/secrets/AZURE-COSMOS-CONNECTION-STRING/c2a0607621284aaf99c5f37cf5cd90gr]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply" which may have affected this plan:

  # module.api.azurerm_linux_web_app.web has changed
  ~ resource "azurerm_linux_web_app" "web" {
        id                                = "/subscriptions/as1bvv2f-7461-4dfc-89c4-6b9141de7e65/resourceGroups/rg-todo-action05082023/providers/Microsoft.Web/sites/app-api-nmjmzgizmjiym"
        name                              = "app-api-nmjmzgizmjiym"
        tags                              = {
            "azd-env-name"     = "todo-action05082023"
            "azd-service-name" = "api"
        }
        # (18 unchanged attributes hidden)

      ~ identity {
          + identity_ids = []
            # (3 unchanged attributes hidden)
        }

        # (2 unchanged blocks hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────
╷
│ Error: making Read request on Azure KeyVault Secret AZURE-COSMOS-CONNECTION-STRING: keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=as1bvv2f-bb63-483d-81a1-b16ccbefbce7;oid=as1bvv2f-2ebb-4e4c-b086-81b909046eda;iss=https://sts.windows.net/d05c6e7a-e5d1-4af0-a643-f829e6e08d31/' does not have secrets get permission on key vault 'kv-nmjmzgizmjiym;location=southeastasia'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287" InnerError={"code":"AccessDenied"}
│ 
│   with module.keyvault.azurerm_key_vault_secret.secrets[0],
│   on modules/keyvault/keyvault.tf line 65, in resource "azurerm_key_vault_secret" "secrets":
│   65: resource "azurerm_key_vault_secret" "secrets" {
│ 
╵

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform planned the following actions, but then encountered a problem:

  # module.keyvault.azurerm_key_vault_access_policy.user[0] must be replaced
-/+ resource "azurerm_key_vault_access_policy" "user" {
      - certificate_permissions = [] -> null
      ~ id                      = "/subscriptions/as1bvv2f-7461-4dfc-89c4-6b9141de7e65/resourceGroups/rg-todo-action05082023/providers/Microsoft.KeyVault/vaults/kv-nmjmzgizmjiym/objectId/as1bvv2f-4e37-40b4-8fac-f228fbe70700" -> (known after apply)
      - key_permissions         = [] -> null
      ~ object_id               = (sensitive value) # forces replacement
      - storage_permissions     = [] -> null
        # (3 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

ERROR: deployment failed: failing invoking action 'provision', planning deployment: planning infrastructure provisioning: terraform plan failed: err failed running terraform plan:  (exit code: 1)
TraceID: d6c2a1eea639d56e987a48f149b254e2
Error: Process completed with exit code 1.`

**To Reproduce**
azd up
azd pipeline config --principal-name azd-dev-1035

**Expected behavior**
The actions from github must without error

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : Visual Studio Code 1.81.0

**Additional context**
Only problem on remote github action. Local working good.

Please have a look.

Thanks
Thanh

**Comment by vhvb1989** [comment]
@thanhrieker , when running/provisioning the template locally, your account (the account from `az account show`) is used as the principal-id.  But when running from CI/CD (github), there is a Service-Principal account (not your account).

What this means is that, after an initial local provision, the access roles for Key Vault (for example) are assigned to your account (so you can run the app locally and have access to the Key Vault). Then, later, when trying to provision again from github, terraform is detecting that the access roles will be replaced.  And there's also a Forbidden error when the ServicePrincipal on github is trying to read the KeyVault (b/c it has no access).

There are 2 solutions I can imagine:

  1.  Use the same account locally and on github.  For example, use the same ServicePrincipal locally and from GitHub.
  2. Update your infra files to support one user account (for running locally) and a ServicePrincipal (for github). Make the infra to append roles, instead of replacing.

**Comment by thanhrieker** [comment]
@vhvb1989 thanks you for your solution.

I will try one of them for sure. But I would like to report this issue for Dev team can update example to avoid this error in further.

Get back to you
Thanh

**Comment by rajeshkamal5050** [comment]
@vhvb1989 we don't run into this issue with Bicep? Should we document the above workarounds for TF?

**Comment by thanhrieker** [comment]
@vhvb1989 :

I try with two if your solution and got error:

`uilding AzureRM Client: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
│ 
│ To authenticate to Azure using a Service Principal, you can use the separate 'Authenticate using a Service Principal'
│ auth method - instructions for which can be found here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret
│ 
│ Alternatively you can authenticate using the Azure CLI by using a User Account.
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on provider.tf line 23, in provider "azurerm":
│   23: provider "azurerm" {`

Now I will try with user instance Service Principal.

Get back to you later.

Best regards
Thanh

**Comment by thanhrieker** [comment]
I try to config on other way and it is working well.

Step:

I create new available on variables.tf on main: 

`variable "service_principal_id" {
  description = "The id of service principal to deploy CI/CD"
  type = string
  default = ""
}`

Update main.tf:

`# ----------------------------
# Deploy key vault
# ----------------------------
module "keyvault" {
 source                   = "./modules/keyvault"
 location                 = var.location
 principal_id             = "" //var.principal_id
 rg_name                  = azurerm_resource_group.rg.name
 tags                     = azurerm_resource_group.rg.tags
 resource_token           = local.resource_token
 access_policy_object_ids = [module.api.IDENTITY_PRINCIPAL_ID, var.service_principal_id]
 secrets = [ // this will saved into secrets with connection info
    {
        name = local.cosmos_connection_string_key //name of value
        value = module.cosmos.AZURE_COSMOS_CONNECTION_STRING //keyvault will generate a unikey with version and store value of connection string there
    }
 ]
}`

Thanks you for your help
Thanh
