### ISSUE TITLE
[Issue] Remove the need to press Enter when authenticating using Device Code

### ISSUE THREAD

**Issue by janegilring** [Azure/azure-dev#2605]
**Output from `azd version`**
azd version 1.1.0 (commit ea9cb12575734ee6a5f99c4d415c1a51d6f32d3e)

**Describe the bug**
When running `azd auth login --use-device-code` from within a notebook in VS Code, it would hang at this point due to no support for interactive commands within notebook cells:

>Start by copying the next code: LH8Q8TA52
>Then press enter and continue to log in from your browser...

**To Reproduce**

- Create a [Polyglot Notebook](https://code.visualstudio.com/docs/languages/polyglot)
- Insert a PowerShell code cell with this content:  `azd auth login --use-device-code`
- Run the cell

**Expected behavior**
The device code should be outputted similarly as when using `az login --use-device-code`, without any need to press Enter:

>To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CVEZPMCUW to authenticate.

**Environment**
Information on your environment:
    * IDE and version : VS Code 1.81.0

**Additional context**
Workaround is to hit the stop button in the code cell, this will abort the prompt to hit Enter and continue the authentication flow.

**Comment by vhvb1989** [comment]
thank you @janegilring 

I created a PR for this.  You should be able to run `azd auth login --use-device-code --no-prompt` to skip waiting for Enter.

**Comment by janegilring** [comment]
Great, thanks - it seems to work 👍

```
Start by copying the next code: GDSGDCW76
Then press enter and continue to log in from your browser...
Error launching browser. Manually go to: https://microsoft.com/devicelogin
Waiting for you to complete authentication in the browser...
Device code authentication completed.
Retrieving subscriptions...
Logged in to Azure.
```
