### ISSUE TITLE
[Issue] No validation for set default environment

### ISSUE THREAD

**Issue by Flanker32** [Azure/azure-dev#261]
**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 0.0.1-beta.1689529

**Describe the bug**
- Run `azd env select` with an un-exist environment, could run successfully without warning. 

**To Reproduce**
- Select an un-exist environment with `azd env select`

**Expected behavior**
- Better to show warning/error notification when user select an un-existing environment

**Environment**
Information on your environment:
    * Language name and version Node JS
    * IDE and version : [e.g. Visual Studio 16.3] VSCode 1.68.1

**Additional context**

**Comment by savannahostrowski** [comment]
@ellismg @rajeshkamal5050 This still repro - we should emit some error here.

**Comment by savannahostrowski** [comment]
Closing this in favour of #1160
