### ISSUE TITLE
[fingerprint] - infra generation

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#2616]
Part of #705

## Infra generation

1. Backend that largely leverages text/template to expand templates for the particular app configuration.
2. Frontend that prompts users for inputs/necessary revisions.

Remainder work

- [x] Refactor/cleanup
- [x] Telemetry
- [x] Acceptance tests
- [x] Review & check-in

**Comment by savannahostrowski** [comment]
@weikanglim Is this completed with #2658?
