### ISSUE TITLE
Feature stage updates - August release

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#2619]
https://github.com/Azure/azure-dev/blob/main/cli/azd/docs/feature-stages.md needs updates.
- Add CloudShell -> Beta @savannahostrowski ?
- Update ASA -> Beta

**Comment by savannahostrowski** [comment]
That makes sense to me!

**Comment by rajeshkamal5050** [comment]
https://github.com/Azure/azure-dev/pull/2620
