### ISSUE TITLE
Show message to the user when we are failing to get deployment info for a resource.

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2622]
Today, we will fail silently and continuously retry (visible with --debug) if we fail to get deployment info. To the end user, they might just see the "creating/updating resource" dialog hanging.

We should make it clear when we can't fetch deployment information and potentially encourage them to check the Portal?

cc: @Austinauth as well as their might be UX changes here.

**Comment by vhvb1989** [comment]
related: https://github.com/Azure/azure-dev/issues/1557
