### ISSUE TITLE
[Issue] FYI: App Service references to KeyVault aren't re-fetched after provision/deploys

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#2631]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 1.2.0 (commit 99ea7577f0df0df2ba34b677da189fafba18c0f7

**Describe the bug**

We have a sample that uses KeyVault references in the App Service app settings:

https://github.com/Azure-Samples/azure-django-postgres-flexible-appservice/blob/e492ece2a165e122067ef8e5cf086482b60f9b18/infra/main.bicep#L106

We accidentally used the wrong reference the first time we ran, using the wrong name or something, and we saw that error reported in the portal when we looked at the App settings configuration.

We fixed the reference, and re-ran azd up, but still saw the Key Vault references reported as incorrect. We realized that's because App Services caches Key Vault references for a number of hours. You can bust the cache by changing app configuration in the Portal (arbitrarily, and then changing back).

I've asked the App Service team to consider always busting the cache on a re-provision and/or re-deploy, they say they'll think about it.

I just wanted to post it as an issue here in case other folks run into it.

**To Reproduce**

Introduce a bad reference in the Bicep of https://github.com/Azure-Samples/azure-django-postgres-flexible-appservice/blob/main/infra/main.bicep#L106 (like wrong secret name)
Run azd up, notice error in app settings
Fix reference, run azd up again, notice error doesn't go away

**Comment by weikanglim** [comment]
If using an App Service KeyVault reference, the secret reference is indeed managed by App Service, cached, and is fetched every 24 hours. The docs are [here](https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli#rotation). 

If wanting to tie secret rotation to infrastructure deployments (`azd provision`), one could choose to use bicep `getSecret`[docs](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-resource#getsecret) that will retrieve the KeyVault secret and stamp the configuration with a literal value at provisioning time.

**Comment by pamelafox** [comment]
Hm, yeah, that's a possibility to make sure folks don't run into this issue, but then you have the drawback of a secret being very easily viewable in app settings. The key vault reference thing is nice since it makes it that much harder to accidentally reveal a secret. Good option to know about though.

**Comment by pamelafox** [comment]
(Feel free to close this issue, I just wanted the issue to be findable for others)
