### ISSUE TITLE
ERROR: logging in: failed to authenticate: failed to decrypt data: Key not valid for use in specified state.

### ISSUE THREAD

**Issue by d-paulus** [Azure/azure-dev#2635]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here: azd version 1.2.0 (commit 99ea7577f0df0df2ba34b677da189fafba18c0f7)

**Describe the bug**
Login fails since yesterday. The browser opens, login is successful through the browser, but receiving the below error in Powershell and VS Code.

running: azd auth login --debug
2023/08/16 09:24:48 main.go:53: azd version: 1.2.0 (commit 99ea7577f0df0df2ba34b677da189fafba18c0f7)
2023/08/16 09:24:48 main.go:210: using cached latest version: 1.2.0 (expires on: 2023-08-17T13:15:22Z)
2023/08/16 09:24:48 cobra_builder.go:142: Resolved action 'azd-auth-login-action'
2023/08/16 09:24:48 middleware.go:124: running middleware 'debug'
2023/08/16 09:24:48 middleware.go:124: running middleware 'telemetry'
2023/08/16 09:24:48 telemetry.go:45: TraceID: a879ed2d9f730c7b703914388b9c98de

**ERROR: logging in: failed to authenticate: failed to decrypt data: Key not valid for use in specified state.**

**To Reproduce**
azd auth login

**Expected behavior**
Successful login

**Environment**
Information on your environment:
    * Powershell
    * VS Code

**Additional context**
The issue started abruptly yesterday, after `azd login` and `azd auth login` worked well for months without issues. `az login` still works. Tried uninstalling and installing azd, but still same error. These are the recent Windows updates on the machine:

- 2023-08 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5029263)
- 2023-08 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Windows 11, version 22H2 for x64 (KB5028948)
- NVIDIA - Display - 31.0.15.2908
- Lenovo - System - 23.5.0.38
- Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.395.547.0)
- Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.395.498.0)
- Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.395.420.0)
- Update for Microsoft Defender Antivirus antimalware platform - KB4052623 (Version 4.18.23070.1004)

**Comment by d-paulus** [comment]
Uninstalling azd, deleting .azd directory in user directory, reinstalling azd, fixed it.

**Comment by d-paulus** [comment]
Uninstalling azd, deleting .azd directory in user directory, reinstalling azd, fixed it.

**Comment by rajeshsinghd** [comment]
What solved for me is renaming the msal_token_cache.bin file in C:\Users\XXX\.azure. Close the shell and rerun az login
