### ISSUE TITLE
text color issues with `azd provision --preview`

### ISSUE THREAD

**Issue by gkulin** [Azure/azure-dev#2638]
it seems like sometimes "skip" is yellow / highlighted when it should be grey / not highlighted. It seems like it's consistently the 2nd to last item (for the todo templates: the api), but I haven't done exhaustive testing, so I am not 100% sure if that's always the case. 

a couple examples:
<img width="881" alt="image" src="https://github.com/Azure/azure-dev/assets/55554236/ff08e1c9-8e61-4c47-abae-a89c84933697">
<img width="439" alt="image" src="https://github.com/Azure/azure-dev/assets/55554236/f9407303-8c58-40ce-886e-d96fceea0062">

to repro:
make some changes then run `azd provision --preview`

**Comment by rajeshkamal5050** [comment]
Assuming its a bug(Skip should be grey'ed) and assigning to @vhvb1989 to take a look. @Austinauth please chime-in, if need be.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you check the text coloring issue?

**Comment by vhvb1989** [comment]
Didn't repro.

It might be fixed on the last patch by Matt: https://github.com/Azure/azure-dev/pull/2630
