### ISSUE TITLE
ERROR: failed running post hooks: Error: loading environment:

### ISSUE THREAD

**Issue by rachaelsingleton** [Azure/azure-dev#2639]
**Output from `azd version`**
`azd version 1.2.0`

**Describe the bug**
Azure CLI commands are not working in post script. I get the following error: 

```
ERROR: failed running post hooks: 'postdeploy' hook failed with exit code: '2', Path: './scripts/post.sh'. : exit code: 2, stdout: Loading azd .env file from current environment
, stderr: Error: loading environment: environment demovchat does not exist
./scripts/post.sh: 6: export: Environment 'demochat' does not exist, would you like to create it? (y/N) : bad variable name
```

**To Reproduce**
azure.yaml: 
```
name: demochat
hooks:
  postdeploy:
    run: ./scripts/post.sh
services:
  vchat:
    language: python
    project: ./app
    host: containerapp
    docker:
      path: App.Dockerfile
```

post.sh: 
```
echo "Loading azd .env file from current environment"

# Use the `get-values` azd command to retrieve environment variables from the `.env` file
while IFS='=' read -r key value; do
    value=$(echo "$value" | sed 's/^"//' | sed 's/"$//')
    export "$key=$value"
done <<EOF
$(azd env get-values) 
EOF
```

**Expected behavior**
Environment variables are loaded correctly. No errors.

**Comment by rajeshkamal5050** [comment]
@v-xuto can you try reproducing this?

**Comment by jongio** [comment]
@rachaelsingleton - What os are you running?

**Comment by rachaelsingleton** [comment]
I'm not currently working out of a public repo. It worked before - it recently stopped working. I am running out of a docker container (mcr.microsoft.com/devcontainers/base:bullseye).

**Comment by rachaelsingleton** [comment]
I am on Windows 11, but I am getting this error from inside a devcontainer... 

```FROM mcr.microsoft.com/devcontainers/base:bullseye```
