### ISSUE TITLE
Request: Single-Developer Mode

### ISSUE THREAD

**Issue by StephenCleary** [Azure/azure-dev#2645]
If possible, I'd like to have a single-developer mode that:

- Caches all ARM responses in a machine/user-local file.
- Invalidates cache entries based on changes that are applied (or re-reads those ARM responses after deployment changes).

This would vastly speed up single-developer, single-machine iterative deployments.

**Comment by jongio** [comment]
In the meantime, you could use the --debug flag and pipe to a file.  

What are you wanting to do with the data in the file?  Do you need it structured?

**Comment by StephenCleary** [comment]
Sorry if I wasn't clear.

I have no use for the file. What I want is to be able to change one property on one resource without waiting 10 minutes for my entire infrastructure to be checked for changes.

If there was a "single developer" mode, then azd wouldn't need to check the resources I haven't changed.

**Comment by savannahostrowski** [comment]
#376 Seems like this is relevant here. We've started investigation into supporting provision caching which would avoid that wait you're seeing.

**Comment by StephenCleary** [comment]
> provision caching relied on client-state and assumed that the resource group is only managed through azd via azd provision.

Client-side provision caching is exactly what I was thinking, yes.

**Comment by savannahostrowski** [comment]
Perfect - if it's alright, I will close this issue in favour of that one. We are currently spiking on this and should hopefully have improved UX here soon. 

Please feel free to reopen if need be.
