### ISSUE TITLE
Minor changes for simplified init experience for 9/6

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2671]
Updated by Austin A on 08/31/2023

### 1. "Select a template" misinterpreted 

**Owner:** @gkulin to review prompt and suggest alternative language to help clarify.
**Status:** In review (issue comment below)

#### Problem
"Select a template" misinterpreted by multiple customers as choosing a template that will then be applied to your current app, and refactor your code to fit that template. 

![image](https://github.com/Azure/azure-dev/assets/6994218/588ac173-36a1-4e32-955d-5a6a0716e556)

#### Solution
TBD

<hr>

### 2. Missing "no code detected" error message

**Owner:** @Austinauth 
**Status:** ✅ Design complete / 🚨 Ready for Dev

#### Problem
When a user scans the code in their current directory but no code exists we show them an empty detection summary.

![image](https://github.com/Azure/azure-dev/assets/6994218/b2557306-fd44-4fbd-9de5-43a035904a31)

#### Solution

![image](https://github.com/Azure/azure-dev/assets/6994218/0c82bf9b-a65e-4b41-9904-f97d20bfb7ca)

Add the following error message when a user opts to _Use code in current directory_ but no code is found:

> Error: No files or services detected in the current directory.
> 
> Ensure you’re in the directory where your app code is located and try again. If you do not have code and would like to start with an app template run 'azd init' in an empty directory and select the option to Use a template.
> 
> For more information, refer to the documentation or run 'azd help'.

<hr>

### 3. The word "services" in "add or remove services" is unclear

**Owner:** @weikanglim 
**Status:** ✅ Dev complete

#### Problem

The word "services" in "add or remove a service" is unclear, causing some customers to believe it is talking about modifying Azure services, rather than confirming that the detection worked accurately. 

![image](https://github.com/Azure/azure-dev/assets/6994218/f06583c5-2992-4b51-a130-9f74ea381ed2)

#### Solution

Add the word "detected" to action to draw an even stronger connection to the detection summary. 

> Add or remove a **detected** service 

<hr>

### 4. "Database name" misinterpreted as being any name

**Owner:** @gkulin 
**Status:**  In review (issue comment below)

#### Problem
'database name' misinterpreted as being any name, rather than the database name that the application expects. Multiple customers believed that they can provide any name to the database. Although we have help text, and see the help text pattern working well for environment name, for the database name no customer has used the help pattern for some reason (maybe they have a stronger conviction that they know what 'database name' is?).

![image](https://github.com/Azure/azure-dev/assets/6994218/b8dfc44f-a1d2-4836-a442-056311a9b5d9)

#### Solution
TBD

<hr>

### 5. [Bug] Help text disappears

**Owner:** @Austinauth 
**Status:** ✅ Design complete /  🚨 Ready for Dev

#### Problem
Help text disappears for many users once they've moved on to the next prompt.
![image](https://github.com/Azure/azure-dev/assets/6994218/0a954592-c3a2-4538-aa10-b8e5c93e1c44)

#### Solution
Help text should stay visible once the user has moved to the next prompt. 

![image](https://github.com/Azure/azure-dev/assets/6994218/df655a2e-d9d5-4dbf-a029-ef1c1bbbb8dd)

<hr>

### 6. [Bug] Loading animation breaks at times due to hooks

**Owner:** N/A
**Status:** 🚨 Awaiting dev

#### Problem
Loading animation breaks due to the hooks.
<img width="731" alt="image" src="https://github.com/Azure/azure-dev/assets/6994218/fe7dec2b-0166-48c2-8754-0db364ee76da">

<hr>

### 7. Escape sequence needed during troubleshooting steps

**Owner:** @Austinauth 
**Status:** ✅ Design complete / 🚨 Ready for Dev

#### Problem
User is locked into troubleshooting path.
![image](https://github.com/Azure/azure-dev/assets/6994218/f47d1c72-401f-4635-9ce2-217795696ff9)

#### Solution

Provide option for the user to "cancel" or "go back" if they decide not to continue troubleshooting.

##### Cancel from service add
![image](https://github.com/Azure/azure-dev/assets/6994218/8a329581-c772-4783-844c-a8aeffaad75a)

![image](https://github.com/Azure/azure-dev/assets/6994218/a92617ea-1687-4ab3-8bdc-29d243bee3ba)

![image](https://github.com/Azure/azure-dev/assets/6994218/ef7adcec-8865-4541-b974-f4e6ba5c78e9)

##### Cancel from path input

![image](https://github.com/Azure/azure-dev/assets/6994218/a4c96fb7-598e-467a-aa7b-f019200d2e3a)

![image](https://github.com/Azure/azure-dev/assets/6994218/55eb4d71-4371-4e47-a9e2-b531543facd4)

<hr>

### 8. Make relationship between ‘azd up,’ ‘azd provision,’ and ‘azd deploy’ more clear. 

**Owner:** @gkulin 
**Status:** ✅ Dev complete

#### Problem
The line which talks about the relationship between ‘azd up’ and ‘azd provision’ and ‘azd deploy’ – multiple customers questioned whether ‘up’ included ‘provision’ and ‘deploy’ commands, or if they needed to be run in succession.

<img width="620" alt="image" src="https://github.com/Azure/azure-dev/assets/44615618/284f5a51-b50b-480e-93db-1bc3a0fb3b8b">

### 9. Re-work heading levels to follow a logical "Chapter in a book" model. 

**Owner:** @gkulin 
**Status:** ✅ Dev complete

#### Problem
Per Florian's feedback, Headings should act as chapters in a book where H1 is the title, H2s are chapters (e.g. 1, 2), and H3s are sub-chapters within those (e.g. 1.2, 1.3). Suggestions include: 
Make Troubleshooting, Billing, What was Added their own chapters so they are more easily discoverable, not hidden under details.
Make Next Steps a high level chapter with "define environment variables" and "Provision infrastructure and deploy application code" sub-chapters of that.
Fix Troubleshooting list items - currently all 1s.

<img width="574" alt="image" src="https://github.com/Azure/azure-dev/assets/44615618/175103b7-4059-481b-9bc3-cad28a375392">

### 10. Explain that buildpacks are being used if you don't have a dockerfile

**Owner:** @gkulin 
**Status:** ✅ Dev complete

#### Problem
One customer who understood that her app was being containerized looked for a dockerfile added to her app, but did not find one. Neither the CLI output nor next-steps clearly mentions the use of buildpacks. In the real world, this customer would have no way to understand that we are using buildpacks.

Additionally, in package step, have a message like "no dockerfile found, using buildpacks..." Either explain in line or link out to docs.

**Comment by gkulin** [comment]
I'm giving a couple options for each copy fix so please feel free to voice your opinions!

1 - "Select a template" is misinterpreted 
alternatives: 
- Start with a new template (recommended for empty directory only)
- Create new app, beginning from a template (recommended for empty directory)
- Create new app, with a template

2 - "database name" is misinterpreted
alternatives:
- Input the ([DB Type]) database name used in your app
- Input the name of the database ([DB Type]) as it is used in your app 

I also want to note here that the help text for the database name also might lead users to believe that the database name can be anything
<img width="893" alt="image" src="https://github.com/Azure/azure-dev/assets/55554236/653871dd-cafb-4051-a0c4-6a1a3f9ad82d">

**Comment by savannahostrowski** [comment]
@gkulin Have you considered "Initialize your application from a template" for "select a template"

For 2, I'd probably vote for "Input the name of the database ([DB Type]) as it is used in your app". I recognize that it's longer but I do think it's clearer.

**Comment by Austinauth** [comment]
A few notes:

- I've updated @savannahostrowski's initial message above with the list of remaining items, the solution owner, and the status. Please make an effort to update the list when a solution is decided for a given item (cc: @gkulin)
- Only items missing from the list are things we decided could wait until post release as well as items related to the `next-steps.md` file. @Irina If there's anything for the 9/6 release related to this can you add? I didn't have a chance to capture them during the meeting yesterday.
- @gkulin will provide feedback for you by EoD!

**Comment by gkulin** [comment]
> Have you considered "Initialize your application from a template" for "select a template"

@savannahostrowski I did think about something like that but thought that some people still might think that means the template will be applied to your current app and refactor the code to fit the template

what do you think of "Initialize a new application from a template"?

**Comment by gkulin** [comment]
@Austinauth I like option 2! Is 'documentation' a clickable link?

**Comment by Austinauth** [comment]
> I'm giving a couple options for each copy fix so please feel free to voice your opinions!
> 
> 1 - "Select a template" is misinterpreted alternatives:
> 
> * Start with a new template (recommended for empty directory only)
> * Create new app, beginning from a template (recommended for empty directory)
> * Create new app, with a template
> 
> 2 - "database name" is misinterpreted alternatives:
> 
> * Input the ([DB Type]) database name used in your app
> * Input the name of the database ([DB Type]) as it is used in your app
> 
> I also want to note here that the help text for the database name also might lead users to believe that the database name can be anything <img alt="image" width="893" src="https://user-images.githubusercontent.com/55554236/264188429-653871dd-cafb-4051-a0c4-6a1a3f9ad82d.png">

**Re: #1**

Still not sure I am in love with any of these options. I think the missing element for me is the inference that you will be selecting the template. It's not something that you have to provide.

**Re: #2** 

I like the second option: _Input the name of the database ([DB Type]) as it is used in your app_

**Re: DB Hint**

Agree about the DB name hint text. The first line could probably be revised to be a more detailed version of the prompt. 

Something like:

_Input the name of your database as it is defined in your application files (case sensitive). If you do not input the name of your database exactly as it is defined [x] will happen..._

**Comment by Austinauth** [comment]
> @Austinauth I like option 2! Is 'documentation' a clickable link?

Ideally! We just have to get this issue resolved first for it to work: https://github.com/Azure/azure-dev/issues/2539

**Comment by irinasmoke** [comment]
# next-steps.md changes


## Make relationship between ‘azd up,’ ‘azd provision,’ and ‘azd deploy’ more clear. 
The line which talks about the relationship between ‘azd up’ and ‘azd provision’ and ‘azd deploy’ – multiple customers questioned whether ‘up’ included ‘provision’ and ‘deploy’ commands, or if they needed to be run in succession.

<img width="620" alt="image" src="https://github.com/Azure/azure-dev/assets/44615618/284f5a51-b50b-480e-93db-1bc3a0fb3b8b">

## Re-work heading levels to follow a logical "Chapter in a book" model. 
Per Florian's feedback, Headings should act as chapters in a book where H1 is the title, H2s are chapters (e.g. 1, 2), and H3s are sub-chapters within those (e.g. 1.2, 1.3). Suggestions include: 
Make Troubleshooting, Billing, What was Added their own chapters so they are more easily discoverable, not hidden under details.
Make Next Steps a high level chapter with "define environment variables" and "Provision infrastructure and deploy application code" sub-chapters of that.
Fix Troubleshooting list items - currently all 1s.

<img width="574" alt="image" src="https://github.com/Azure/azure-dev/assets/44615618/175103b7-4059-481b-9bc3-cad28a375392">

## Explain that buildpacks are being used if you don't have a dockerfile
One customer who understood that her app was being containerized looked for a dockerfile added to her app, but did not find one. Neither the CLI output nor next-steps clearly mentions the use of buildpacks. In the real world, this customer would have no way to understand that we are using buildpacks.

Additionally, in package step, have a message like "no dockerfile found, using buildpacks..." Either explain in line or link out to docs.

**Comment by gkulin** [comment]
> # next-steps.md changes

I made these changes here: https://github.com/weikanglim/scaffold-projects/pull/2

**Comment by Austinauth** [comment]
Thank you @gkulin! 

Status of all the items in the initial [issue comment](https://github.com/Azure/azure-dev/issues/2671#issue-1872544939) are now up to date.

**Comment by savannahostrowski** [comment]
I think this can be closed
