### ISSUE TITLE
[Issue] Bicep installer prefers MUSL variant over glibc

### ISSUE THREAD

**Issue by mthebridge** [Azure/azure-dev#2683]
- [ X  ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.2.0 (commit 99ea7577f0df0df2ba34b677da189fafba18c0f7)

**Describe the bug**
When azd installs its bicep provider, it uses the presence of the MUSL linker on the system to determine whether to install a MUSL based bicep.   See this code here: https://github.com/Azure/azure-dev/blob/ba25a8cdd81cf6b81a1f09c575bdd513eda95a98/cli/azd/pkg/tools/bicep/bicep.go#L167 

I believe this is the same issue in the main Azure CLI as https://github.com/Azure/bicep/issues/5040 which was fixed by only installing the musl-based variant if there is no glibc installed. Could the same fix as made under https://github.com/Azure/azure-cli/pull/23040/files be made here in the developer CLI?  Happy to offer a PR if that would be helpful.

**To Reproduce**
* Install the musl libc toolchain.
* Run `azd up` in a Bicep-based deployment.  Bicep installs but fails to run.

**Expected behavior**

Bicep should be installed for the correct system libc.

**Environment**
WSL Ubuntu 20.04 on Windows 11.

**Comment by ellismg** [comment]
Thought that I wrote a response here but looks like I forgot to submit it.  Thanks for opening this @mthebridge.  You are correct that we modeled getting bicep off the logic in the `az` CLI.  When we added it, they had not yet landed that fix, so we didn't pick it up.  I opened a PR that adds this to our heuristic.  Thanks for pointing it out, @mthebridge!

**Comment by ellismg** [comment]
FWIW, as a workaround until the fix lands (or for others who stumble upon this issue later) you can download the glibc bicep yourself from the GitHub releases page and then set the environment variable `AZD_BICEP_TOOL_PATH` to the full path to the bicep you downloaded.  In that case, we will use that version instead of the one that `azd` downloads and manages itself.

**Comment by mthebridge** [comment]
> FWIW, as a workaround until the fix lands (or for others who stumble upon this issue later) you can download the glibc bicep yourself from the GitHub releases page and then set the environment variable `AZD_BICEP_TOOL_PATH` to the full path to the bicep you downloaded. In that case, we will use that version instead of the one that `azd` downloads and manages itself.

Thanks @ellismg - I'd already discovered that workaround and have been using that fine.
