### ISSUE TITLE
Allow for azd auth on clouds other than AzureCloud

### ISSUE THREAD

**Issue by davesee** [Azure/azure-dev#2684]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.2.0 (commit 99ea7577f0df0df2ba34b677da189fafba18c0f7)

**Describe the bug**
I am trying to use the azd cli to deploy to the AzureUSGovernment cloud.

**To Reproduce**
Run the latest installed azd cli with the `azd auth login` to connect to an AzureUSGovernment subscription. This option is not currently available.

**Expected behavior**
As a user of azd I can set the cloud I would like to deploy too.

>**Note:** With az cli, this can be set with `az set cloud --name AzureUSGovernment ` and `export ARM_ENVIRONMENT=usgovernment` needs to be set when executing terraform in this cloud. Not sure if there are Bicep specific needs.

**Environment**
Information on your environment:
- WSL Ubuntu 20
- Win 11 Powershell

**Additional context**
- This will enable usage of azd in clouds other than Azure Commercial, for example AzureUSGovernment.
- Possible to set this via the `azd auth ` command with a new option
- The cloud is currently set here:
  - https://github.com/Azure/azure-dev/blob/main/cli/azd/pkg/azdo/azdo.go#L38

**Comment by savannahostrowski** [comment]
Hey! We're going to spike on this in the next couple months - using this issue to track #2653. Closing in favour of the existing issue.
