### ISSUE TITLE
Failed to `azd package api` for `todo-java-mongo` on Apple Silicon

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#2693]
**Describe the issue:**
Test `todo-java-mongo` template on Apple Silicon. Install azd (`ARM64`), run `azd package api`, get error as follow:

![image](https://github.com/Azure/azure-dev/assets/80496810/c3ff7355-45c8-42d4-97a6-d06263fdff36)

**Repro Steps:**
1. Install azd : `curl -fsSL https://aka.ms/install-azd.sh | bash -s -- --architecture arm64`
1. Run command: `azd init -t todo-java-mongo`
2. Run command: `azd package api` .

**Environment:**
OS: Mac M2 (ARM64)
Template: todo-java-mongo
Azd version:  `(azd-mac-arm64)` 1.2.0

**Expected behavior:**
Run command `azd package api` can pass.

@rajeshkamal5050, @danieljurek  for notification.

**Comment by rajeshkamal5050** [comment]
https://github.com/HubSpot/prettier-maven-plugin/issues/66 seems similar. Can we try upgrading prettier-maven-plugin 0.18 or latest and try it locally?

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 It works after upgrading prettier-maven-plugin 0.18 in locally.

**Comment by rajeshkamal5050** [comment]
> @rajeshkamal5050 It works after upgrading prettier-maven-plugin 0.18 in locally.

Can you do a PR for the same in these places - https://github.com/search?q=repo%3AAzure%2Fazure-dev%20prettier-maven-plugin&type=code ?

cc @weikanglim

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 I have created a PR :  https://github.com/Azure/azure-dev/pull/2709
