### ISSUE TITLE
[Issue] `azd auth login` doesn't work in codespaces

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#2697]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

1.2

**Describe the bug**

Auth doesn't work

**To Reproduce**
1. Create a new repo with GH UI
2. Create a new codespace with GH UI
3. Install azd using `curl -fsSL https://aka.ms/install-azd.sh | bash`
4. Run `azd auth login`

See many prompts about allowing cookies and then it fails due to JS not being enabled.

<img width="448" alt="image" src="https://github.com/Azure/azure-dev/assets/2163001/d5931d80-d13d-4e37-b89e-9cedfbc4268d">

<img width="402" alt="image" src="https://github.com/Azure/azure-dev/assets/2163001/0c3eb831-03a2-45a1-9fdb-784f2a290699">

<img width="573" alt="image" src="https://github.com/Azure/azure-dev/assets/2163001/d70af3a0-bc82-4988-ac25-0957597047d2">

**Expected behavior**
I should be logged in

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

Codespaces in browser Edge
No devcontainer.json file

I created codespace with UI.

**Additional context**

**Comment by ellismg** [comment]
From the screenshots, it really seems like some console based browser was selected to do the interactive flow and that browser can't run JavaScript.

We have code in `azd` to attempt to detect if you are running in a codespace and if so force you to use device code auth, maybe that heuristic is no longer working?

/cc @vhvb1989 who worked through the login flow for codespaces and did a bunch of work to try to make this work the best it could out of the box.

**Comment by jongio** [comment]
`azd auth login` works if I connect to the codespace via local vscode.

**Comment by jongio** [comment]
I also repro'd this in Chrome (latest)
