### ISSUE TITLE
Create experiment + scorecard with metrics for VS Code

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#270]
Follow up from Azure/azure-dev-pr#1221 

We need to:
1. Set up the A/A experiment 
2. Probably clone Docker's scorecard
3. Update to reflect our own events, similar to  https://github.com/Azure/azure-sdk-pr/pull/793

cc: @karolz-ms for awareness and to add any details I'm missing.

**Comment by karolz-ms** [comment]
The scorecard is working and data looks good ☺️
