### ISSUE TITLE
October Release - Doc Updates

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#2712]
- Remote environments support - https://github.com/Azure/azure-dev/pull/2765 @wbreza 
- Provision caching - https://github.com/Azure/azure-dev/pull/2725/ @vhvb1989 
- Mac ARM64 support to GA, update troubleshooting doc for node issue - @danieljurek

**Comment by gkulin** [comment]
completed via https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4962
