### ISSUE TITLE
[Issue] Run cspell in CI for changes that don't impact the CLI

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#272]
In Azure/azure-dev-pr#1318 we made some changes to the README.md's in our templates and doing so introduced a spelling "error" (specifically, our use of "azdo", which cspell rightly said was not a word).

Since we only run cspell today as part of the `cli-ci` leg, which uses path filters to only run when you are touching CLI product code, we didn't see these errors as part of the PR, and instead they cropped up in Azure/azure-dev-pr#1385 because this was the first job after the change landed that saw these errors.

We should break the cspell legs out into their own workflows and figure out better path filtering.  Or perhaps instead we should move the cspell logic for checking the templates and extension into the CI legs for these components, since I think we have the same general problem with the extension as well.

**Comment by vhvb1989** [comment]
This is done
