### ISSUE TITLE
Simplified init flow and buildpacks(alpha -> beta)

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2728]
Follow up to #705 

```[tasklist]
### Tasks
- [ ] Improve manual configuration flows (e.g. database connection string, environment variables, detected ports)
```

**Comment by savannahostrowski** [comment]
@weikanglim @ellismg We will need to remove ExP logic for this and pull the feature out from under the feature flag.

**Comment by rajeshkamal5050** [comment]
@savannahostrowski @weikanglim anything pending? we can close this?
- https://github.com/Azure/azure-dev/pull/2925
- https://github.com/Azure/azure-dev/pull/2904
- https://github.com/Azure/azure-dev/pull/2900
- https://github.com/Azure/azure-dev/pull/2875

**Comment by weikanglim** [comment]
This is done.
