### ISSUE TITLE
azd up should display warning message when downloading a non-Azure-Samples template

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#273]
This helps to warn customers about potentially downloading malicious repo.

**Comment by savannahostrowski** [comment]
After chatting with CELA, we will need to:
- Add a page to our documentation on docs.microsoft.com outlining the risk of running code you didn’t author
	- In azd product, show a blurb with link to notice on docs.microsoft.com on azd init
	- On GitHub, add a notice to the bottom of our GitHub README

**Comment by savannahostrowski** [comment]
I believe this can be closed now via #1348
