### ISSUE TITLE
[UX Improvement] azd template list - filtering 

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-dev#2732]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 1.3.0 (commit 6605c5768cb3ab6d9e0e6c2d892c9e8b49e1f720)

**Describe the request**

This is more a feature request/proposal to improve the usability. With release 1.3.0 the `azd template list` command fetches all templates from the awesome azd gallery. Depending on the project setup I just want to have a sepcific type of template available like only TypeScript templates that refer to Azure Container Apps. This information might be part of the title or text available in the output of `azd template list` but walking through it and finding the right templates might be cumbersome. 

It would be a nice addition to the config option to add some tag filtering infor to the configuration of the source. Currently this is:

```json
{
  "template": {
    "sources": {
      "awesome-azd": {
        "key": "awesome-azd",
        "location": "https://aka.ms/awesome-azd/templates.json",
        "name": "Awesome AZD",
        "type": "awesome-azd"
      }
    }
  }
}
``` 

which could be like

```json
{
  "template": {
    "sources": {
      "awesome-azd": {
        "key": "awesome-azd",
        "location": "https://aka.ms/awesome-azd/templates.json",
        "name": "Awesome AZD",
        "type": "awesome-azd"
        "filterTags": ["typescript", "aca"] 
      }
    }
  }
}
``` 

The logic would probably be additive so filter by tag1 AND tag2 to avoid unncessary complexity. The intention would be to narrow down the list and not represent complex queries. 

This could also benefit in the sceanrio of custom template sources. Thinking about a company that has such an internal list, but all projects in the org unit A want to use web app templates only, this would allow a preconfigured selection for the teams working in the irg unit.

**Additional context**

The information about the tags is available at [https://azure.github.io/awesome-azd/templates.json](https://azure.github.io/awesome-azd/templates.json)

**Comment by vhvb1989** [comment]
@lechnerc77 , you can type the filter when the template-list is displayed. The filter is applied right away.

**Comment by lechnerc77** [comment]
@vhvb1989 yes I saw that his is possible, but as far as I saw this is restricted to the text that is visible and not to any metadata of the projects. 
To give more context: As a company I am offering different templates as blueprints for my projects. In general, the guidance is that development takes place via Typescript or .NET. Team A of that company  decided to go exclusively for TypeScript.  Of course the teams are using `azd` but team A wants to configure that the list provided by `azd init` to the templates that are relevant for them (Typescript based ones) right from the start without any dev needing to manually filter.

**Comment by vhvb1989** [comment]
@lechnerc77 , have you tried running

```
azd template source remove awesome-azd
azd template source add <url>
```

where `<url>` is some json file you have uploaded to some public CDN or FTP server.  In this file, you can create your own list of templates and that's what azd would show.

Your json file should look like: https://github.com/Azure/azure-dev/blob/main/cli/azd/resources/templates.json

Also, as soon as you remove the `awesome-azd`, the default templates (todo-templates) are also removed.

**Comment by lechnerc77** [comment]
@vhvb1989 thanks for pointing this out. I was aware of the option but did not try it out yet. 

So the best practise to realize the intended setup is to create a dedicated configuration as pointed out in the JSON and to wire that up with the azd configuration. That makes sense. I think the procedure you described would be a great  addition to the `azd`documentation as best practice for this functionality. If you anyway have that on your list, we can close this issue.

**Comment by rajeshkamal5050** [comment]
Specify custom template sources for azd init - https://devblogs.microsoft.com/azure-sdk/azure-developer-cli-azd-september-2023-release/#specify-custom-template-sources-for-azd-init
