### ISSUE TITLE
[Issue]ERROR: listing accounts: listing subscriptions: failed to load subscriptions from tenant '默认目录' : reauthentication required, run `azd auth login` to log in

### ISSUE THREAD

**Issue by YouJiYun** [Azure/azure-dev#2738]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)
<img width="547" alt="image" src="https://github.com/Azure/azure-dev/assets/36957239/524138c3-d017-4064-8c55-588f098c07ea">

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
1.3.0
**Describe the bug**
Description of issue you're seeing...
run `azd up` and get a error
**To Reproduce**
Steps to reproduce the behavior...
1. azd auth login
2. select account
3. azd up
**Expected behavior**

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

**Comment by rajeshkamal5050** [comment]
@YouJiYun can you run it with --debug and attach logs? Is the user associated azure china cloud?

cc @ellismg @weikanglim @vhvb1989

**Comment by YouJiYun** [comment]
@rajeshkamal5050  
I have resolved the issue by using `az login` for multiple authentication.
