### ISSUE TITLE
[Issue] azd deploy is not working anymore post upgrade to 1.3.0

### ISSUE THREAD

**Issue by vrajroutu** [Azure/azure-dev#2744]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here: `azd version 1.3.0 (commit 6605c5768cb3ab6d9e0e6c2d892c9e8b49e1f720)`

**Describe the bug**
Description of issue you're seeing...

Running `azd deploy` returns

(base) Browls@Wolf-MacBook-Pro OpenAI % azd deploy

Deploying services (azd deploy)

SUCCESS: Your application was deployed to Azure in less than a second.
You can view the resources created under the resource group a44455-dedvri in Azure Portal:
https://portal.azure.com/#@/resource/subscriptions/8707508803038308333-333/resourceGroups/a44455-dedvr/overview

**To Reproduce**
Steps to reproduce the behavior...
`azd deploy`

**Expected behavior**

**Environment**
Information on your environment:
    * Language name and version 
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

**Comment by weikanglim** [comment]
Hi @vrajroutu, it looks like `azd deploy` didn't find anything to deploy:

1. Are you running in the same directory that contains `azure.yaml`?
2. Does `azure.yaml` contain one or more `services`?

**Comment by jongio** [comment]
Can you please run the command with `--debug` and report what you see?

**Comment by vrajroutu** [comment]
@jongio  @weikanglim closing this issue. It worked as expected.
