### ISSUE TITLE
Discussion: Should azd up include azd init

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#275]
`azd up` is the single command that does init, provision and deploy but bundling "get code" together with "get app running in Azure" is confusing to customers.  Typically, developers get code and then modify and deploy the app.   

Note that, for DevContainer, we need to `azd init` and then `azd up`. 

We should:
1. consider if it makes more sense to consistently recommend a 2-step flow 
2. separating "get code" from `azd init`. Either do git clone in baremetal or add a new command for getting code. Init is for initializing environment.

**Comment by savannahostrowski** [comment]
I'm going to close this in favour of the discussion that was opened. Please let me know if you take issue with this. Trying to keep the convo in a single place.
