### ISSUE TITLE
Spike on how we enable static frontend apps for simplified init

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#2750]
Right now, buildpacks don't support this scenario and there's "magic"/"hacks" to make it work which make it a non-starter for the new init flow.

**Comment by weikanglim** [comment]
Current plan is to enable azd to influence Oryx to install + launch a static content webserver (likely nginx) to serve the static file content on the system.

This will require Oryx (w/ node runtime) to surface configuration options to achieve the target.

**Comment by weikanglim** [comment]
Oryx team will provide nginx capabilities long-term. Short-term, azd will be configuring the runtime image to achieve the hosting requirements
