### ISSUE TITLE
[Issue] Could/should azd add a .gitignore to .azure?

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#2755]
I just learned that subdirectories can have .gitignore's! Apparently lots of tools add .gitignore to their created folders, like venv recently did: 
https://github.com/python/cpython/issues/83417

I wonder if it'd make sense for .azure to have a .gitignore? (Instead of adding itself to the repo's .gitignore?)

Just a thought!

**Comment by jasontaylordev** [comment]
> I wonder if it'd make sense for .azure to have a .gitignore? (Instead of adding itself to the repo's .gitignore?)

Hey @pamelafox - I wonder what would be the point of that? Specifying **.azure** in **.gitignore** at the repo level means that the folder will be ignored by Git.

**Comment by pamelafox** [comment]
The benefit of adding a .gitignore with * in .azure is that azd doesn't need to mess with the root .gitignore. It just seems like it might be a bit cleaner, less brittle. I think sometimes I get double .azure's in my .gitignore due to azd logic in how it adds to it.
Functionally, the result would be same as today. It's just a different approach.

**Comment by jasontaylordev** [comment]
Thanks, I didn't know that. I did a quick test to confirm behaviour and found:

1. **.gitignore \*** includes all files and folders contained within **.azure**
2. **.azure** is not committed because it is an empty folder

I like it, nice and simple.
