### ISSUE TITLE
[Issue] Error when devshell module installed in $profile (Powershell)

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#2758]
azd v.1.3

1. Find shortcut file to "Developer Powershell for VS 2022". Mine was here: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2022\Visual Studio Tools
1. Right click on the shortcut and find the instance id in the "Target" field. Mine was:
    ```
    C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe -noe -c "&{Import-Module """C:\Program Files\Microsoft 
    Visual Studio\2022\Preview\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"""; Enter-VsDevShell c110b361}"
    ```
1. Add the following to $profile
  Run `notepad $profile`

    Add:

    ```
    Import-Module "C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
  
    Enter-VsDevShell c110b361
    ```
   Where c110b361 is the instance id you found in the last step:

1. Start a new Powershell instance.
1. Run `azd up` on any project with a hooks in azure.yaml, like https://github.com/Azure-Samples/demystifying-rag-dotnet

You'll see this output:

```
Error: no project exists; to create a new project, run `azd init`
WARNING: 'postprovision' hook failed with exit code: '1', Path: 'C:\Users\\AppData\Local\Temp\azd-postprovision-2183812410.ps1'. : exit code: 1
Execution will continue since ContinueOnError has been set to true.
```

Something with Developer Powershell is interfering with azd.

**Comment by ellismg** [comment]
I wonder if we are passing `--NoProfile` to pwsh when we are running the script or if we should be.  Loading the user's profile when running hooks is maybe something we don't want to do implicitly (for example, when running in CI there will be no profile to load so if your script relies on it implicitly it will fail).

If you run with `--debug` you should be able to extract the entire command line we are using to run pwsh, wondering if running the script outside of `azd` also fails and if so, if passing `--NoProfile` fixes it.

**Comment by rajeshkamal5050** [comment]
Fixed via PR https://github.com/Azure/azure-dev/pull/3469
