### ISSUE TITLE
[Issue] List of subscriptions is too broad

### ISSUE THREAD

**Issue by diberry** [Azure/azure-dev#2761]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here: azd version 1.3.0 (commit 6605c5768cb3ab6d9e0e6c2d892c9e8b49e1f720)

**Describe the bug**
when I provision, the list of subscriptions is too broad - I should only have 2 subscriptions for my personal email which is also tied to my FTE VS Enterprise subscription. 

**To Reproduce**
1. In CodeSpaces, open [https://github.com/Azure-Samples/contoso-real-estate](https://github.com/Azure-Samples/contoso-real-estate). 
2. `azd auth login`
3. `azd provision` - this shows more than my 2 subscriptions I have using my personal account

```
   1. 1-Pay-As-You-Go (xxx)
   2. AICP-API-QnAMaker-MSFT-Non-Prod (xxx)
   3. Azure VMware Solution Licensing Calculator (xxx)
   4. Microsoft for Startups for tech staff to learn and test (xxx)
   5. Visual Studio Enterprise Subscription (xxx)
```

Number 1 and 5 are what I should see. No idea where 2,3, and 4 came from. This seems like a security issue with how azd is getting the list. 

**Expected behavior**
Only show me 1 and 5. 

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

**Comment by savannahostrowski** [comment]
@rajeshkamal5050 Can we get someone to investigate? Seems like a bug.

**Comment by ellismg** [comment]
> This seems like a security issue with how azd is getting the list.

AZD pulls all the subscriptions from all the tenants the user has access to, not just the user's default tenant.  This behavior is similar to what `az` does.  @diberry wondering if you also see these other subscriptions when you do an `az account list` with the `az` CLI?

**Comment by diberry** [comment]
@ellismg Yes, they all show up. Weird is that 2 weeks ago, only the QnAMaker was the addition to the list. Now there are 2 more. There isn't anyway  my personal account should be seeing this unless somehow access to the VS enterprise sub is giving it to me. I'm using a Google chrome browser logged into with my personal account only. 

If I log into the azure portal with the personal account, I only see the 2 I'm supposed to see. 

![image](https://github.com/Azure/azure-dev/assets/41597107/b6e806db-5ad6-4ad7-b0bb-52055cef34a9)

**Comment by rajeshkamal5050** [comment]
From the `az account list` screenshot above. Looks like these aggregated subs are coming from `two different tenants` which the user is associated with. Doesn't seem to be a security issue. cc @weikanglim

**Comment by weikanglim** [comment]
@diberry In the screenshot, `Subscriptions == global filter` is applied. Does removing the filter change the result?

**Comment by diberry** [comment]
@weikanglim 
![image](https://github.com/Azure/azure-dev/assets/41597107/34b3078f-8107-4a20-916b-3bc2134318e8)

@rajeshkamal5050 Do my personal account is in the corporate tenant somehow. How can I find that and remove it?

**Comment by weikanglim** [comment]
@diberry Let me work with you to see if we can't get it resolved.

**Comment by weikanglim** [comment]
Closing since the original issue has been resolved. `azd` is listing subscriptions across all tenants that the user has access to.
