### ISSUE TITLE
Migrate package hosting CDN

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#2766]
Akamai CDN retires 2023-10-31. Install script needs to download from a new location before that date. 

Migration instructions: https://learn.microsoft.com/en-us/azure/cdn/cdn-change-provider?WT.mc_id=Portal-Microsoft_Azure_Cdn

Steps: 

1. Set up new CDN endpoint (should not require moving storage account) 
2. Validate traffic on new CDN endpoint
3. Update installer scripts to point to new endpoint and release updated installer scripts
4. Update aka.ms links to point to new CDN location 

This should send all traffic to the new CDN. Traffic pointing to the old hostname will stop working after 2023-10-31.

**Comment by rajeshkamal5050** [comment]
@danieljurek Closing it as complete.
