### ISSUE TITLE
On provision, only show progress if not 0

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#277]
I'm seeing this:
![image](https://user-images.githubusercontent.com/2163001/176973167-3aa4fd6a-acab-4b92-9152-f3ae99548ae7.png)

Which makes me think something is wrong.

I'd say we only show the message if the numbers aren't 0

**Comment by savannahostrowski** [comment]
@weikanglim Can this be closed now?

**Comment by weikanglim** [comment]
Yes, closing.
