### ISSUE TITLE
[Feature] Add OIDC support for Azure Pipelines

### ISSUE THREAD

**Issue by geekzter** [Azure/azure-dev#2777]
As per [doc](https://learn.microsoft.com/azure/developer/azure-developer-cli/reference#azd-pipeline-config) `azd pipeline config --auth-type` doesn't support Azure Pipelines. As Azure Pipelines has [announced](https://devblogs.microsoft.com/devops/public-preview-of-workload-identity-federation-for-azure-pipelines/) support for OIDC, please add this capability to Azure Developer CLI.

While the blog post describes usage for pipeline authors and task developers, this [script](https://github.com/geekzter/azure-identity-scripts/blob/main/scripts/azure-devops/create_azurerm_msi_oidc_service_connection.ps1) demonstrates usage of the service endpoint [REST API](https://learn.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints/create?view=azure-devops-rest-7.2&tabs=HTTP) to create an OIDC service connection to Azure.

See similar request for [GitHub actions](https://github.com/Azure/azure-dev/issues/408).

**Comment by ellismg** [comment]
Woohoo!  Glad to see OIDC supported in Azure Pipelines - moving to this should simplify some stuff for us.
