### ISSUE TITLE
Add Private Endpoint as a resource kind for deployment [Issue]

### ISSUE THREAD

**Issue by mattjames1978** [Azure/azure-dev#2809]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

**Describe the bug**
When running a deployment I would like to see private endpoint resource added to the resource list for outputting the progress.

**To Reproduce**
Running a new deployment only displays certain resources and private endpoint is missing. 

**Expected behavior**
See the progress of Private Endpoint Deployment

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

**Comment by vhvb1989** [comment]
related to: https://github.com/Azure-Samples/azure-search-openai-demo/pull/488
