### ISSUE TITLE
Feature Request: Specify resource groups for individual services in azure.yaml

### ISSUE THREAD

**Issue by EverybodyKurts** [Azure/azure-dev#2811]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

```bash
% azd version
azd version 1.3.1
```

**Describe the problem**

The `azure.yml` spec states I can only specify *one* resource group, I'd love to be able specify the resource group under the `services` property. I have a static web app in one resource group and an azure function app in another (another function app already exists in the resource group).

**Solution**
Be able to override the resource group for each service.

**Comment by jongio** [comment]
Thanks @EverybodyKurts, but we have an existing issue here.  Please feel free to add to that conversation.  Thanks! 

https://github.com/Azure/azure-dev/issues/690
