### ISSUE TITLE
Automated cleanup for template tests

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#282]
Live tests of samples provision and deploy in resource groups with a `DeleteAfter` tag. In the case of templates we should add tags to the deployments so those can be cleaned up by automation as well. 

If we don't tag resource groups we will leak resources in certain build failures including agent crashes, network failures, or failures in the test script which halt execution of deprovisioning steps. 

Couple ways to do this: 

* Add a parameter to `azd provision` that is passed through to templates or sets tags directly on the resource group(s)
* Add parameter to `azd provision` that deploys to an existing resource group
* Guess the name of the resource group that will be deployed, create it, then run `azd deploy` as normal
* Tag the created resource group in the script after provisioning (this could encounter problems if there is a crash/network issue in the middle of provisioning)

**Comment by vhvb1989** [comment]
is this fixed by this: https://github.com/Azure/azure-dev/issues/481 ???

**Comment by weikanglim** [comment]
We definitely add tags with `DeleteAfter` as-of today. Closing this.
