### ISSUE TITLE
Readme for ACA template should not `azd up --template ..`

### ISSUE THREAD

**Issue by paulyuk** [Azure/azure-dev#283]
I notice the readme for ACA template recommends a default pull of the template and deploy in a single step: https://github.com/Azure-Samples/todo-python-mongo-aca/blob/main/README.md?plain=1#L45

I do not believe most users will work this way.  I believe devs typically start from a template.  work on it.  and then deploy with `azd up`.  

Even if you want to pull and up right away, I worry about the overwrite behavior.  E.g. I had made simple changes, got that prompt: 
` * tests/playwright.config.ts
 * tests/todo.spec.ts
? Overwrite files with versions from template? (y/N) `

if I say N, it errors out `Error: running init: confirmation declined`

That encourages a user workflow to retry the same thing but this time with y, which blows away the change.  Note in real life I did blow away my changes, which was frustrating. 

Based on this I have two proposals:
1) change the readme for these templates to always deploy via `azd up` and no args
2) in the y/N prompt, and when azure.yaml is present, guide the user to rerun with `azd up` instead of this current behavior with No is a failure and Yes overwrites their work.

**Comment by rajeshkamal5050** [comment]
Updated - https://github.com/Azure-Samples/todo-python-mongo-aca/tree/main?tab=readme-ov-file#quickstart

```
# Log in to azd. Only required once per-install.
azd auth login

# First-time project setup. Initialize a project in the current directory, using this template. 
azd init --template Azure-Samples/todo-python-mongo-aca

# Provision and deploy to Azure
azd up
```
