### ISSUE TITLE
azd reports I need to upgrade, but winget disagrees

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-dev#2832]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)
I can't (see below)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
`azd version 1.3.1 (commit b5030da0f29ffe98664c40450187fd8a4cb0d157)`

**Describe the bug**
When I run an azd command, it tells me I need to upgrade from 1.3.1 to 1.4.0.
But, running `winget upgrade Microsoft.azd` tells me `no available upgrade found`.

![image](https://github.com/Azure/azure-dev/assets/74415662/91d3055c-5824-406c-95c0-be13ca2c2a67)

**Expected behavior**
I expect winget upgrade to upgrade azd.

**Environment**
Information on your environment:
    * Language name and version

**Comment by danieljurek** [comment]
@charris-msft -- there is a small lag between opening a PR to WinGet and the merging of that PR which updates the manifest. That lag has elapsed and `winget upgrade Microsoft.Azd` succeeds now. Thanks for reporting! :)
