### ISSUE TITLE
[Bug] Running `azd up` after running `azd down` doesn't make changes to Azure

### ISSUE THREAD

**Issue by john0isaac** [Azure/azure-dev#2835]
**Output from `azd version`**
azd version 1.4.0 (commit 25dc100fce2d2aa1ad2affd9e3c7b707519b0ee8)

**Describe the bug**
After running the down command that deletes the resources from Azure if you try to recreate the deleted resources using the up command it gives you a message that says "(-) Skipped: Didn't find new changes." and doesn't create anything on Azure.

**To Reproduce**
Run `azd up`
Run `azd down`
Run `azd up`

**Expected behavior**
The deleted resources get created again on Azure.

**Additional context**
![image](https://github.com/Azure/azure-dev/assets/64026625/4bb34238-339d-4a04-8e9b-348d1fedff39)

**Comment by john0isaac** [comment]
@savannahostrowski that is the issue that I told you about I tried multiple times and it's consistent.

**Comment by savannahostrowski** [comment]
Hey @john0isaac! Thanks for following up. 

@rajeshkamal5050 Can we investigate this?

**Comment by rajeshkamal5050** [comment]
@vhvb1989 looks like even though the resources are deleted(`azd down`). The subsequent provisioning(`azd up`) checks against the previous deployment runs and skips/does nothing. Seems to be a bug. Can you take a look?

**Comment by vhvb1989** [comment]
@john0isaac , thank you for reporting this.

I'm working/debugging the issue.  As a workaround, for now, you can call `azd provision --no-state` to re-deploy your infrastructure

**Comment by vhvb1989** [comment]
fix expected as part of 1.4.1 within a few more minutes now.

**Comment by jyrijh** [comment]
I am expriencing this issue with version 1.11.0, and I have seen this previosly also.
Yesterday I did run azd down before quitting for the day, and tomorrow when i run azd up I did get the `Skipped: Didn't find new changes.` message. And there were no resourcegroups in my subscription at all
