### ISSUE TITLE
Per RP progress for azd provision/azd up output

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#284]
Now we see (7 of ~8 completed), I still do not know what is created and how long it takes to create the resource. 

**Now**
Creating Azure resource \
->
Creating Azure resources ( 2 of ~3 completed)

**Desired outcome:**
Creating Azure resources ( 2 of ~3 completed)
- Resource group: xxxx-rg created [timestamp]
- App service plan: plan-xxxx created [timestamp]

**Comment by weikanglim** [comment]
Fixed by #152
