### ISSUE TITLE
Add examples section to --help 

### ISSUE THREAD

**Issue by spboyer** [Azure/azure-dev#288]
Azure CLI does a good job of showing example commands which ensure some success, easy edit to guide users to success.

i.e. `az webapp up --help` 

```
Examples
    View the details of the app that will be created, without actually running the operation
        az webapp up --dryrun

    Create a web app with a specified name and a Java 11 runtime using '|' delimiter (not
    recommended for powershell; use the ":" delimiter instead)
        az webapp up -n MyUniqueAppName --runtime "java|11|Java SE|11"
```

We should consider using this pattern for `init` , `up` initially; but also for other commands to create put of success.

**Comment by puicchan** [comment]
@Austinauth, assigning this to you since you are working on UX for --help.

**Comment by savannahostrowski** [comment]
I think we are going to take a more minimalist approach here for the first rev.

**Comment by Austinauth** [comment]
I've actually been including something similar in my most recent mockups. I'll need some help getting the examples right, but definitely something we can discuss together. Doesn't have to be for the first rev if we want to take more time to think through it.

**Example Mockup**

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/6994218/210610280-19afc206-313b-4f60-a773-b3ad9743baaf.png">

**Comment by savannahostrowski** [comment]
Closing this out given the upcoming updates to `help` :tada:  - #822
