### ISSUE TITLE
Doc Updates - November Release

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#2885]
Features and its doc updates. @gkulin please work with respective folks.
- Simplified Init, Buildpacks, Simplify configuring variables/app settings etc @weikanglim 
- ADE docs @wbreza 
- azd show @vhvb1989 
- .NET 8 updates @ellismg 

Misc
- [Resource Group Scoped Deployments [Alpha]](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/resource-group-scoped-deployments) currently, we don't callout any pre-requisites i.e., required roles, permissions. Will be good for us to update the doc to include them @weikanglim can you help @gkulin on that?

**Comment by weikanglim** [comment]
Submitted https://github.com/MicrosoftDocs/azure-dev-docs/pull/1283 as a suggested improvement we could make
