### ISSUE TITLE
[Issue] Update docs on dev containers to mention feature

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#2892]
https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/make-azd-compatible?pivots=azd-create#make-your-template-dev-container-and-codespaces-compatible

should just recommend using the feature!

**Comment by gkulin** [comment]
closed via https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/5118
