### ISSUE TITLE
[Question] When will the Terraform support feature go live?

### ISSUE THREAD

**Issue by cryanskl** [Azure/azure-dev#2894]
Hi Team,

Good day!

I want to use Terraform with Azure Developer CLI tools to deploy my Web App. I am also aware that Terraform features are in the beta version. However, I would like to inquire, when will the Terraform support feature go live?

[Terraform features are in the beta version](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/use-terraform-for-azd#:~:text=Terraform%20is%20still%20in%20beta.%20Read%20more%20about%20alpha%20and%20beta%20feature%20support%20on%20the%20feature%20versioning%20and%20release%20strategy%20page)

Thanks in advance!

**Comment by savannahostrowski** [comment]
Terraform support is live in product today. We don't have a definite timeline for advancing it to stable or GA. Advancement depends on usage and feedback.

**Comment by jongio** [comment]
@cryanskl - Have you tried the Terraform implementation yet?  We'd be curious to get some feedback from you and see if there's anything about it that needs to be improved.  Thanks
