### ISSUE TITLE
[Issue] azure-sdk bot bot miss registration to winget-pkg repository

### ISSUE THREAD

**Issue by kkamegawa** [Azure/azure-dev#2908]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Describe the bug**
Developer tool can't upgrade with `winget upgrade microsoft.azd` .

https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/Azd/1.4.400/Microsoft.Azd.installer.yaml

azure-sdk bot miss registration to winget-pkg manifest. Every version exists same miss.

miss(current)
```
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Azure/azure-dev/releases/download/azure-dev-cli_1.4.*3*/azd-windows-amd64.msi
```

correct
```
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Azure/azure-dev/releases/download/azure-dev-cli_1.4.*4*/azd-windows-amd64.msi
```
winget's `installurl` must match about PackageVersion's release artifact. 

**Expected behavior**
`InstallerUrl`'s binary must match `PackageVersion` release.

**Comment by danieljurek** [comment]
Hey @kkamegawa, thanks for opening an issue! This is by-design as MSI's versioning behaviors predate SemVer and MSI does not support SemVer. The result is an algorithm for finding the "patch" or "revision" number of the MSI based on a given SemVer. If MSI supported SemVer this would not be necessary.

The algorithm for determining the MSI version given the SemVer version of the tool is expressed here: https://github.com/Azure/azure-dev/blob/main/eng/scripts/Get-MsiVersion.ps1#L48-L53

An example execution shows that `1.4.3` maps to `1.4.400` 

```powershell
.\Get-MsiVersion.ps1 -CliVersion 1.4.3
1.4.400
```

This enables us to release SemVer versions like `1.4.3-beta.1` and get MSI versions which will correctly upgrade over older versions (e.g. `1.4.2`) and be superseded by newer versions (e.g. `1.4.3`): 

```powershell
.\Get-MsiVersion.ps1 -CliVersion 1.4.2
1.4.300

# Installs over 1.4.2
.\Get-MsiVersion.ps1 -CliVersion 1.4.3-beta.1
1.4.301

# Installs over 1.4.3-beta.1
.\Get-MsiVersion.ps1 -CliVersion 1.4.3
1.4.400
```

Thanks again for reporting! I'm going to close this issue for now but please re-open if you have more questions.
