### ISSUE TITLE
playwright test fail in todo-nodejs-mongo

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-dev#291]
**Describe the issue:**
playwright test fail when delete a item.

**Repro steps:**

1. Run command `azd up`
2. Run command `cd tests`
3. Run command `npm i && npx playwright install`
4. Run command `npx playwright test`

![image](https://user-images.githubusercontent.com/76771069/174277224-5d8e4e76-1ff9-48f7-8062-3e1bd5d3836c.png)

**Environment:**
OS : Linux(Ubuntu 20.04), DevContainer, Codespace
Template: 
https://github.com/Azure-Samples/todo-nodejs-mongo
https://github.com/azure-samples/todo-csharp-cosmos-sql
https://github.com/azure-samples/todo-nodejs-mongo
https://github.com/azure-samples/todo-nodejs-mongo-aca
https://github.com/azure-samples/todo-python-mongo
https://github.com/azure-samples/todo-python-mongo-aca

**Expected behavior:**
playwright test can success.

@jongio for notification.

**Comment by v-jiaodi** [comment]
@hemarina,   I re-run the test . This issue can no longer be reproduced on Linux(Ubuntu 20.04) ，Codespace and DevContainer.
