### ISSUE TITLE
[Issue] WinGet upgrade fails

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#2929]
The winget upgrade command fails with the error message:

`The install technology of the newer version specified is different from the current version installed. Please uninstall the package and install the newer version`

### Steps to reproduce
On the command line:
```
winget install Microsoft.Azd --version 1.4.300
winget upgrade Microsoft.Azd --version 1.4.400 
```

**Comment by rajeshkamal5050** [comment]
@danieljurek @heaths depends on the `winget-cli` issue - https://github.com/microsoft/winget-cli/issues/3825

**Comment by heaths** [comment]
Some other person reverted the files and removed them in https://github.com/microsoft/winget-pkgs/pull/123748. I'm restoring them now...

**Comment by danieljurek** [comment]
Mitigation: https://github.com/Azure/azure-dev/pull/3013

**Comment by danieljurek** [comment]
Mitigation merged

**Comment by rajeshkamal5050** [comment]
Closing this one since we the mitigation(reverting customization) place. Will be added back #3012 once winget issue https://github.com/microsoft/winget-cli/issues/3825 is addressed.
