### ISSUE TITLE
Changing Azure location and re-deploying results in deployment name conflict

### ISSUE THREAD

**Issue by karolz-ms** [Azure/azure-dev#293]
### Repro steps
1. Initialize the repository via `azd init`
2. `azd provision`
3. Open the .env file and change AZURE_LOCATION (e.g. from westus to eastus or similar).
4. Do `azd provision ` again.

### Expected
Provisioning should succeed

### Actual
Provisioning fails with deployment name conflict (a screenshot from Tim, who brought this scenario to my attention):

![MicrosoftTeams-image](https://user-images.githubusercontent.com/15271049/173890790-3dc6e732-0b64-4af9-87c7-bd7a6cac8598.png)

**Comment by puicchan** [comment]
I re-produced this. The error included in original issue is misleading. Tim selected a region that was too busy to create the Cosmo DB account.

Pick a region that is ok. e.g., centralus, and the error message is:

...
Created Key vault: keyvaultrsiqo7swfrhqi
Created Azure Cosmos DB: cosmos-rsiqo7swfrhqi
Error: deployment failed: failed deploying: failed running az deployment sub create:

Deployment Error Details:
InvalidDeploymentLocation: Invalid deployment location 'centralus'. The deployment 'node810' already exists in location 'westus'.

Potential suggestion: Run `azd down` to delete all the existing infrastructure before re-deploying.

**Comment by puicchan** [comment]
After talking through this, we should make sure we use unique deployment names to prevent this from happening.

**Comment by jongio** [comment]
I believe this is related to us using the environment name as the deployment name.  We may need to randomize the deployment name or include the location in the name.

**Comment by xaviermignot** [comment]
Hello, I'm facing the same issue. It would be great if we had a way to specify the deployment name. 
Currently if I have several projects using `azd` in the same subscription, if I use the same location my deployments at the sub level are being overwritten. If I change the location, I get the error mentionned here.
