### ISSUE TITLE
[Issue] dubious ownership issue with "azd pipeline config" in Codespaces

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#2934]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

Latest from azd feature

**Describe the bug**

Please see issue from QA team here:
https://github.com/Azure-Samples/azure-django-postgres-flexible-aca/issues/72

Jay replicated as well.

We found some suggested workarounds with marking directories as safe but want to confirm that's to be expected.

**Comment by rajeshkamal5050** [comment]
@pamelafox based on comment here https://github.com/Azure-Samples/azure-django-postgres-flexible-aca/issues/72#issuecomment-1813177036 and the codespaces workaround is already captured here https://github.com/Azure-Samples/azure-django-postgres-flexible-aca/issues/72#issuecomment-1813177036 closing this issue for now.
