### ISSUE TITLE
[Issue] Failed downloading bicep with "Azd up" in M1 Dev Container

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#2939]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

```
vscode ➜ /workspaces/azure-search-openai-demo (bicep-updates) $ azd version
azd version 1.4.3 (commit d165bd2de96dae75de57604c0d8a5553ae214618)
```

**Describe the bug**

Trying to run `azd up` in dev container for https://github.com/Azure-Samples/azure-search-openai-demo but getting this error:

```
vscode ➜ /workspaces/azure-search-openai-demo (bicep-updates) $ azd up
  (x) Failed: Downloading Bicep

ERROR: initializing infrastructure provider: failed resolving IaC provider 'bicep': downloading bicep: Get "https://downloads.bicep.azure.com/v0.21.1/bicep-linux-arm64": EOF
```

That URL does seem to exist in my browser, but not sure if its corrupt or something?

**Environment**

VS Code
Version: 1.83.1 (Universal)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:46:55.789Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

**Comment by weikanglim** [comment]
@pamelafox Does it reproduce consistently? From the error, it's possible that there was server hiccup.

**Comment by pamelafox** [comment]
No, I restarted my computer and it's fine now. I suspect the dev container was partially set up / in a weird state, as other funky things were happening.
