### ISSUE TITLE
Func apps are being reset after re-provision

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#294]
1. Run `azd up` on project with function
2. Test that the function is working
3. Run `azd provision`
4. Try to hit the function
5. It won't be available, because the "re-provision" after a deploy removes the code from the function.

Could be related to this: https://stackoverflow.com/questions/59740162/azure-function-code-deleted-after-a-new-arm-deployment-from-azure-devops

**Comment by rajeshkamal5050** [comment]
@vhvb1989 @jongio  given we have added `azd provision` to skip if no deltas are found. Function app shouldn't get reset.

But with a forced provisioning using `azd provision --no-state` I am able to see the web and the service accessible. Tried with `azd init -t todo-python-mongo-swa-func`. Please reopen if you find issues.
