### ISSUE TITLE
[Issue] AZD fails on bicep download in GitHub Codespaces

### ISSUE THREAD

**Issue by diberry** [Azure/azure-dev#2942]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here: azd version 1.4.3 (commit d165bd2de96dae75de57604c0d8a5553ae214618)
Bicep CLI version 0.23.1 (b02de2da48)

**Describe the bug**
Azd up was working on this [AOAO JS sample repo](https://github.com/azure-samples/azure-search-openai-javascript) 2 days ago and isn't today. 

**To Reproduce**
1. Fork repo
2. Open in Codespace
3. check versions of azd and bicep
4. `azd auth login`
5. `azd up`

```
? Enter a new environment name: diberry-js-aoai-110803
  (x) Failed: Downloading Bicep

ERROR: initializing infrastructure provider: failed resolving IaC provider 'bicep': downloading bicep: Get "https://downloads.bicep.azure.com/v0.21.1/bicep-linux-x64": read tcp 172.16.5.4:46544->13.107.213.70:443: read: connection reset by peer
```

**Expected behavior**
Bicep is already on the container - why is it downloading bicep? 

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

![image](https://github.com/Azure/azure-dev/assets/41597107/554ae288-bd70-4aba-bd60-99f46aecf0f7)

**Comment by vhvb1989** [comment]
> Bicep is already on the container - why is it downloading bicep?

if the bicep cli version on the container is < 0.21.1, azd pulls its own version, instead of using the one from the system.

**Comment by diberry** [comment]
@vhvb1989 The devcontainer feature for azd says latest. Shouldn't that be in sync with the latest azd?

**Comment by jongio** [comment]
@pamelafox saw this yesterday too.

**Comment by vhvb1989** [comment]
Reviewed this directly with the team and suggested them to move from using Alpina to Debian, for the devcontainer.

This is not related to azd.
