### ISSUE TITLE
Support azd logout

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#295]
If we support `azd login`, we should also probably support `azd logout`.

I can imagine a use case where a developer would want to switch Azure accounts (e.g. from personal to work or vice versa) where this would be helpful.

As it stands right now, I don't think there's anyway to logout via `azd` or `az`?

**Comment by savannahostrowski** [comment]
@wbreza I assume this is relevant to your work to remove the az dependency + as you think about auth on the azd side. Does this make sense to assign to you?

**Comment by savannahostrowski** [comment]
@rajeshkamal5050 Let's make sure that this is considered as we work through auth

**Comment by ellismg** [comment]
We now have `azd logout` - it was added with our auth support
