### ISSUE TITLE
Login error 

### ISSUE THREAD

**Issue by bnodir** [Azure/azure-dev#2950]
Does this occur consistently? Yes

Repro steps:
1.  Type "azd auth login" or "azd auth login --use-device-code" in terminal.
2. The following error is displayed.
＊＊＊
ERROR: logging in: failed to authenticate: unable to resolve an endpoint: server response error:
 Get "https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration": EOF
＊＊＊

Action: azure-dev.views.workspace.environment.resolve
Error type: Error
Error Message: Timed out waiting for a task to complete.

Version: 0.7.0
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.84.2
Language: en

<details>
<summary>Call Stack</summary>

```
Timeout._onTimeout extension.js:2:938994
```

</details>

**Comment by jongio** [comment]
This may have been transient.  Are you still seeing this issue?

**Comment by bnodir** [comment]
Thank you for your response. No, I don't have this issue anymore, so we  can close it now.

**Comment by bnodir** [comment]
@jongio, Thank you for your response. No, I don't have this issue anymore, so it is closed now.
