### ISSUE TITLE
Consider adding wait spinner when running `azd down`

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#297]
When running `azd down`, it takes from 10 to 30 seconds for the first output to show up:

> This will delete 8 resources, are you sure you want to continue?

Consider adding a quick message after running `azd down` like: `Getting resource list from your project...`  .  So the user knows that `azd` is doing something and that it's not frozen.

**Comment by rajeshkamal5050** [comment]
Should be covered as part of the azd down UX improvements https://github.com/Azure/azure-dev/issues/1434
