### ISSUE TITLE
[Issue] add new command - `azd auth account`

### ISSUE THREAD

**Issue by dfberry** [Azure/azure-dev#2976]
Related to #2975 

After failing the postprovision because az didn't think it was authenticated from azd, it would be nice to run `azd auth account` to see what/who azd thinks just ran the `azd provision` command.

**Comment by wbreza** [comment]
Thanks for the suggestion. This is a duplicate to #986 which we will continue to use to track this issue.

**Comment by wbreza** [comment]
Thanks for the suggestion. This is a duplicate to https://github.com/Azure/azure-dev/issues/986 which we will continue to use to track this issue.
