### ISSUE TITLE
[Issue] Inconsistent login behavior in Codespaces

### ISSUE THREAD

**Issue by sinedied** [Azure/azure-dev#2979]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here: 1.4.3

**Describe the bug**
We encountered this issue when doing a workshop with 25p last week (1.4.3 was the latest at that time).

When opening this template https://github.com/Azure-Samples/azure-openai-rag-workshop-template in Codespaces and running `azd auth login`, the behavior was different for about half the audience:

- For about half (like me), it automatically falls back to using device code and works properly
- For the other half, it runs the standard interactive login that cannot be completed due to the callback URL not working. They had to manually add `--use-device-code` flag to properly log in.

**To Reproduce**
Try running `azd auth login` on different Codespaces.

**Expected behavior**
Login experience should be consistent.

**Environment**
Codespaces, see https://github.com/Azure-Samples/azure-openai-rag-workshop-template/blob/main/.devcontainer/devcontainer.json

**Comment by vhvb1989** [comment]
@sinedied do you have more information about the scenarios where azd did not launch device-code?

For example, what browser they were using, and if they create a new codespace or if they were using some existing one?

**Comment by sinedied** [comment]
@vhvb1989 They all created new codespaces, starting from the same template they just forked. From top of mind, more of them used either Chrome or Firefox.
Besides that, I don't have any more details and I could never replicate it on my side, but I've seen in person 2 different perso starting a new Codespaces from scratch on a latest Chrome browser and having this issue, with many others of attending the workshop experiencing the same.

We had other inconsistent behavior with Codespaces like the Docker daemon not being available, but other issues could always be solved by just reloading the Codespaces. We tried multiple times with this one, and when one person had this problem it could be replicated all the time, even after reloading.

**Comment by sinedied** [comment]
Issue is still valid, and we have upcoming workshops sessions so this still matters.

**Comment by sinedied** [comment]
Is there any more feedback you need from my side?

**Comment by vhvb1989** [comment]
@sinedied, it looks like a codespaces issue to me.  Something is happening during the container creation.

If you see this issue again, try not only to reload the codespace, but to full-rebuild:

![image](https://github.com/Azure/azure-dev/assets/24213737/340b22b5-8558-4624-8094-5e1f6c98212d)


Another things to consider:

- Your devcontainer is using `javascript-node:18-bullseye` image and it is also using the `features/node`. This is redundant, as the image has node18 already installed. Consider removing the feature: https://github.com/Azure-Samples/azure-openai-rag-workshop-template/blob/main/.devcontainer/devcontainer.json#L11
- Consider upgrading the `docker-in-docker` feature to latest version 2. https://github.com/Azure-Samples/azure-openai-rag-workshop-template/blob/main/.devcontainer/devcontainer.json#L14C37-L14C55. Like:
```
"ghcr.io/devcontainers/features/docker-in-docker:2": {
        },
```
 - Consider removing `npm install ...` from `post create script`.  Ask customer to manually run this command instead so they can see if there are install issues or security warnings.
