### ISSUE TITLE
Weird winget installer message on updating to latest 1.5.0 version

### ISSUE THREAD

**Issue by timheuer** [Azure/azure-dev#2986]
**Describe the bug**
When running `winget install Microsoft.Azd` I get an odd message saying that the installer tech has changed and I need to uninstall/install rather than just update

**To Reproduce**

1. `winget install Microsoft.Azd -v 1.4.600`
2. `winget install Microsoft.Azd`

**Expected behavior**
Updates fine with no need to uninstall first.

![image](https://github.com/Azure/azure-dev/assets/4821/cb9fa940-58e5-4a09-8b7c-94e281eb0531)

**Workaround**
Easy to workaround:
1. `winget uninstall Microsoft.Azd`
2. `winget install Microsoft.Azd`

**Comment by danieljurek** [comment]
@timheuer -- Thanks for reporting. We're aware of this issue (https://github.com/Azure/azure-dev/issues/2929) and looking into it with the WinGet team (https://github.com/microsoft/winget-cli/issues/3825) 

The workaround you propose does work properly. 

I'll close this issue as a duplicate at this time.
