### ISSUE TITLE
Failed AZD Up locks docker engine

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#2994]
Created issue from user's feedback:

https://teams.microsoft.com/l/message/19:ug5DKpbpRJbBtgoSQAXdynHgthpALgePNJ8wb5AI8HM1@thread.tacv2/1698779928463?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=c99e8504-1250-4d95-a824-9778e0e626c7&parentMessageId=1698779928463&teamName=Azure%20Developer%20CLI%20(azd)%20Partners&channelName=General&createdTime=1698779928463

Description:

I am deploying my container to an Container App and it failed. When it failed it also locked the docker engine to where any command to unlock failed. If you run any docker command you get an error asking if the Docker Daemon is running. The only way I've been able to proceed has been to reboot my computer. I am using WSL 2 Ubuntu 20.04 with the lastest AZD version. How can I resolve this in case of future build errors

**Comment by rajeshkamal5050** [comment]
@vhvb1989 ran into this issue lately?

**Comment by vhvb1989** [comment]
Didn't hear about this again
