### ISSUE TITLE
Promote Resource group scoped deployments from alpha to beta

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#2995]
Creating issue from:

https://teams.microsoft.com/l/message/19:ug5DKpbpRJbBtgoSQAXdynHgthpALgePNJ8wb5AI8HM1@thread.tacv2/1696542177446?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=c99e8504-1250-4d95-a824-9778e0e626c7&parentMessageId=1696542177446&teamName=Azure%20Developer%20CLI%20(azd)%20Partners&channelName=General&createdTime=1696542177446

@savannahostrowski @ellismg , let's use this issue to plan for a date to graduate this alpha feature.  What do you think? 

I think we have some evidence to meet: https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/feature-versioning#advancement-criteria-how-to-reach-beta

```
Advancement criteria (how to reach beta)
The feature has been properly spec’d and approved by the product team.
The product team has formally signed off on advancing the feature to next phase.
The feature is documented and help text is available in the product.
Confirmation that the UX is successful via sufficient user feedback.
```

**Comment by ellismg** [comment]
One thing we should think about as we do this promotion - we don't have a satisfying answer for `azd down` in this world.  What we do today is "delete the resource group" that you targeted.  That may be reasonable for flows where `azd` creates a new resource group (an option you have when doing your first provision) but likely doesn't make sense for the case where you select an existing resource group (and could lead to you deleting more than you expected!)

Part of me wonders if we should use resource group scoped deployments as a way to explore also using [Azure Deployment Stacks](https://techcommunity.microsoft.com/t5/azure-governance-and-management/arm-deployment-stacks-now-public-preview/ba-p/3871180) (now in Public Preview).  In this world, `down` would have clearer semantics (delete the stack, and allow it to decide if it wants to delete or detatch resources).  It would also give users a more "Terraform/Pulumi" like experience where removing a resource from the IaC would cause it to be removed from the set of deployed infrastructure (or detached, depending on configuration).

**Comment by ulkeba** [comment]
I agree with @ellismg. 

In my setup, I have RGs created upfront, with restricted RBAC role assignments. The current behavior of `azd down`, i.e., deleting the RG, is challenging here since it will lock users out of their defined scope. My expectation would be that with resource group deployment, azd will only manage the lifecycle of the contained resources -- not the RG itself.

**Comment by rajeshkamal5050** [comment]
- https://github.com/Azure/azure-dev/pull/4285
