### ISSUE TITLE
Authentication for sources in azd template source

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-dev#2996]
### Discussed in https://github.com/Azure/azure-dev/discussions/2960

<div type='discussions-op-text'>

<sup>Originally posted by **lechnerc77** November 12, 2023</sup>
We can change the list of available template sources via `azd template source add`. Assuming I want to add my custom source I can define a JSON and reference it via e.g.:

```
azd template source add my-source --type url --location https://raw.githubusercontent.com/lechnerc77/azd-festive-tech-calendar-2023/main/custom_template/dapr_template.json
```
How can I use this command and access private GitHub repositories that require authentication?
</div>

Following up this discussion and the answer by @wbreza I open this issue as a *feature* request for enhancing azd template sources for defining the sources behind endpoints that need authentication like private GitHub repositories

Scenario: company maintains their own curated list of sources for azd. The list of the sources as well as the sources are available in private repositories only.

**Comment by vhvb1989** [comment]
@TWolversonReply , I created https://github.com/Azure/azure-dev/pull/4203 for this.  It will allow you to use private GitHub repositories as template source for azd.
