### ISSUE TITLE
[Issue] Add PubSub to infra core templates

### ISSUE THREAD

**Issue by diberry** [Azure/azure-dev#3000]
Something like: 

```
@description('Specifies a project name that is used to generate the Event Grid name.')
param name string
param location string = resourceGroup().location
param storageAccountId string
param endpoint string
param tags object = {}
param eventSubName string

resource systemTopic 'Microsoft.EventGrid/systemTopics@2021-10-15-preview' = {
  name: name
  location: location
  tags: tags
  identity: {
    type: 'None'
  }
  properties: {
    source: storageAccountId
    topicType: 'Microsoft.Storage.StorageAccounts'
  }
}

resource eventSubscription 'Microsoft.EventGrid/systemTopics/eventSubscriptions@2022-06-15' = if (endpoint != '') {
  parent: systemTopic
  name: eventSubName
  properties: {
    destination: {
      properties: {
        endpointUrl: endpoint
        maxEventsPerBatch: 1
        preferredBatchSizeInKilobytes: 64
      }
      endpointType: 'WebHook'
    }
    filter: {
      advancedFilters: []
      includedEventTypes: [
        'Microsoft.Storage.BlobCreated'
        'Microsoft.Storage.BlobDeleted'
      ]
      enableAdvancedFilteringOnArrays: true
    }
  }
}
```

**Comment by vhvb1989** [comment]
Hello @diberry, my understanding is that we are not adding new/more bicep modules to azd-core-templates.
This is b/c we would be migrating at some point to use AVM (Azure Verified Modules) https://azure.github.io/Azure-Verified-Modules/

You can take a look to see if there is already one AVM you can reference from your bicep module for PubSub, or you can contribute directly with a new one.

**Comment by jongio** [comment]
> Hello @diberry, my understanding is that we are not adding new/more bicep modules to azd-core-templates.
> This is b/c we would be migrating at some point to use AVM (Azure Verified Modules) https://azure.github.io/Azure-Verified-Modules/

We will continue adding modules to core as needed.  AVM is a ways a way.

**Comment by jongio** [comment]
@diberry - I suggest doing a PR to infra/core
