### ISSUE TITLE
Improve `container.v0` support for Aspire Apps

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#3007]
As we were bringing up support for Aspire apps in `azd`, one of the samples we were using, for a period of time had a container resource.  We added some basic support for supporting `container.v0` resources, but the sample stopped using the container and I suspect the support bit rotted somewhat.

We'd like to add real support to `azd` to deploy these resources.  We should be able to just include them as container apps in our generated `resources.bicep` file.

**Comment by mitchdenny** [comment]
Related: https://github.com/dotnet/aspire/issues/1088

**Comment by rajeshkamal5050** [comment]
Moving this to Jan release. Not a blocker for December.

**Comment by rajeshkamal5050** [comment]
Fixed as part of PR's #3131 #3095
