### ISSUE TITLE
Composite Actions do not check for all required tools up-front.

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#301]
In Azure/azure-dev-pr#1217 we improved the tool checking experience to try to check for all the tools "up front" and print all missing tools once before the command starts.

This works well for our individual commands, but doesn't work for composite actions like `up`.  Instead of taking the union of the tools required across each step, and checking once before starting any steps, we just check for per step requirements.

Imagine a case where you do `azd up --template todo-nodejs-mongo` but do not have node installed.  Logically this is the same as doing:

```
$ azd init --template todo-nodejs-mongo
$ azd infra create
$ azd deploy
```

If you are missing `node` then `azd up` will fail after the `azd infra create` and `azd deploy` actions complete saying you need node.  It would be ideal if we did this checking at the start of the `azd up` gesture.

@vhvb1989 I could imagine a possible solution here could look like some sort of `RequiredTools` function on Action interface that returns a slice of `tools.ExternalTools` that are needed, which would allow the compositeAction type to implement it by doing a union, but I am not wed to that, just feels like it would fit given the current design.  As your thinking about how you want to improve how we capture common logic in our commands could you think about this?

Talking with PC, we're fine with delaying this work for GA (which will let us do it just once, the right way, when you figure out what it is we should do here)

**Comment by rajeshkamal5050** [comment]
> Depending on: #84 as pre-work. Once that one is merged, I would implement the logic to cover this issue on top of that one. Otherwise they would conflict on same files

In addition to an aggregated erroring and failing for the composite up command

> ```diff
> # azd up -t todo-csharp-cosmos-sql
> - ERROR: required external tools are missing:
> -  - error checking for external tool npm CLI: checking npm CLI version: exec: "node": executable file not found in $PATH
> -  - .NET CLI is not installed, please see https://dotnet.microsoft.com/download to install

For the primitive commands, can we warn and proceed

> ```diff
> # azd init -t todo-csharp-cosmos-sql
> ! WARN: required external tools are missing:
> !  - error checking for external tool npm CLI: checking npm CLI version: exec: "node": executable file not found in $PATH
> !  - .NET CLI is not installed, please see https://dotnet.microsoft.com/download to install
> # Initializing a new project (azd init)
> + (✓) Done: Downloading template code to: /Users/acme/azd-demo

@ellismg @savannahostrowski @vhvb1989 thoughts?

**Comment by savannahostrowski** [comment]
IMO, I don't know that we should warn on something like `init`. The behaviour of this command right now is that it really just pulls template code down for you and initializes some environment metadata. This could give users the wrong impression about the behaviour of a command like `init` as I think many (myself included) only see information about language runtimes, tools etc. when the code is being executed or when we build the project.

**Comment by rajeshkamal5050** [comment]
With all of the validations added for checking required tools. Things should be in a good state with 0.8. If any new issues, please open a new one.
