### ISSUE TITLE
[Issue] Existing bicep files are not respected

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-dev#3015]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install) 👉 I've got the nightly build version

**Output from `azd version`**

```bash
azd version 1.6.0-beta.1-daily.3273852 (commit f00f37d70ae38a8b53d28650b0398ea4d097ec7d)
```

**Describe the bug**

👉 **It's related to Aspire.** 👈
I've got an existing Azure Bicep file, `aoai.bicep`, under the `infra` directory, which provisions Azure OpenAI instances. When I ran `azd up` under this condition, it threw an error like the screenshot below.

![image](https://github.com/Azure/azure-dev/assets/1538528/ec49f3fe-2d85-4752-ac6f-c7b8c4975ff9)

If I remove the `infra` directory, `azd up` works just fine.

**To Reproduce**

1. Create an Aspire starter project
2. Create any Bicep file under the `infra` directory and give it a name other than `main.bicep`
3. Run `azd up`
4. See the error like above.

**Expected behavior**

`azd up` should work fine.

**Environment**
Information on your environment:
    * Language name and version: .NET 8
    * IDE and version : Visual Studio 2022 17.9

**Additional context**

- Haven't tried yet. But my gut feeling says, even if I only have the `infra` directory with nothing in it, it might be throwing the same error.

**Comment by vhvb1989** [comment]
@justinyoo , as of today, azd does not support `Aspire-Auto-infra-generation + infra-folder`

As soon as you create the `infra folder` , azd will switch to use the content of that folder as the source of true for the infrastructure.  Then, azd will find for the `main.bicep` file by default. If you want to use a different name, you need to define the name in `azure.yaml` like:

``` yaml
# define `foo` as the default bicep file, instead of `main`
infra:
  module: foo
```

This will tell azd to take `foo.bicep` as the iac.

You might want to consider running command `azd infra synth` . This command would take all the infrastructure required by the Aspire project and put within the infra folder.  Then you can add more resources there.  Just remember that, if you make changes to the Aspire host (like adding more projects or components there), you need to run `azd infra synth` again.

**Comment by justinyoo** [comment]
@vhvb1989 Thanks for the reply!

Yeah, that's what I'm talking about. I think more proper logic, in order to respect existing bicep files under the `infra` directory, could be:

- Check whether the `infra` directory exists or not
  - If `infra` doesn't exist, provision resources generated by Aspire
  - If it exists, look for `main.bicep` as defined in `azure.yaml`
    - If `main.bicep` doesn't exist, provision resources generated by Aspire
    - If it exists, throw an error or prompt asking like "`main.bicep` will be overwritten. Want to continue?"

The main point of my question is that, regardless `main.bicep` exists or not, `azd up` throws an error, as long as the `infra` directory exists. I don't think it's a proper behaviour because there are chances provisioning other resources not associated with Aspire like Azure OpenAI, Azure Functions, Azure Event Grid, etc.

**Comment by rajeshkamal5050** [comment]
Seems to be a bigger feature under discussion here to make azd work in hybrid/mixed mode i.e., Aspire's in-memory IaC + non-Aspire projects IaC.

@vhvb1989 is planning to have a temporary fix in place to make them work independently.

**Comment by rajeshkamal5050** [comment]
Not a blocker for the December release. Moving to January release.
