### ISSUE TITLE
Add support for missing resource types

### ISSUE THREAD

**Issue by davidfowl** [Azure/azure-dev#3020]
https://learn.microsoft.com/en-us/dotnet/aspire/deployment/manifest-format#built-in-resources
- [x] #3065
- [x] #3060
- [x] #3062

https://learn.microsoft.com/en-us/dotnet/aspire/deployment/manifest-format#azure-specific-resource-types

- [x] #3061
- [x] #3063
- [x] #3064
- [x] #3066

**Comment by stuartpa** [comment]
+1 on getting the SqlServer resource type supported.  Currently hitting:

```
azd init
.
.
Generating files to run your app on Azure:

ERROR: unsupported resource type: sqlserver.server.v1
```

**Comment by stuartpa** [comment]
Is implementing the container resources for items not supported by "az appcontainer add-on create" going to be hard?   For example, will azd wait until "az appcontainer add-on sqlserver" support is added before trying to implement sqlserver.server.v1 support.

My understanding is, without appcontainer add-on support for sqlserver, azd will need to do the work to config Ingress, setup a container secret, and also pass the required environment variables (e.g. ACCEPT_EULA and MSSQL_SA_PASSWORD).

While sqlserver is not supported by "appcontainer add-ons", will azd still move forward in supporting sqlserver.server.v1, or will azd wait until "az appcontianer add-on" support is added for "sqlserver"?

**Comment by vhvb1989** [comment]
@stuartpa , `azd` does not depend on `az` to provide functionality.

azd interacts with appcontainer service directly, using the sdk clients.  

So, no, what `az` supports or not does not affect `azd`.

**Comment by stuartpa** [comment]
Okay, same question rephrased:

While sqlserver is not supported by "appcontainer add-ons", will azd still move forward in supporting sqlserver.server.v1 (and do all the wiring up (Ingress/Secret/EnvVars) required in azd), or will azd wait until "az appcontianer add-on" support is added for "sqlserver"?

**Comment by mitchdenny** [comment]
We are working through these details at the moment. Our goal is to have it so that when azd sees a sqlserver resource that it will deploy an Azure SQL Database instance.

**Comment by davidfowl** [comment]
@eerhardt we need to add kafka to this list

**Comment by eerhardt** [comment]
> @eerhardt we need to add kafka to this list. ACA's kafka support https://learn.microsoft.com/en-us/azure/container-apps/tutorial-dev-services-kafka?tabs=bash

Note I can't edit the top list, as I'm not a contributor in this repo.

I noticed a couple more missing as well. I've opened the following issues, if you want to add them to this list @ellismg:

* https://github.com/Azure/azure-dev/issues/3219
* https://github.com/Azure/azure-dev/issues/3220
* https://github.com/Azure/azure-dev/issues/3221

**Comment by javiergardella** [comment]
@mitchdenny --> Instead of creating an 'Azure SQL Database instance,' could you set up an entire AKS with two PODs—one for SQL Server and another for the web? 

I have already accomplished this, and I can provide the YAML files if needed.

**Comment by davidfowl** [comment]
SQL Server will work in the next preview.

**Comment by rajeshkamal5050** [comment]
We will not add hand-crafted, template-based Bicep deployment support in azd. Instead, we will be moving towards using bicep resource type and CDK effort.
- https://github.com/dotnet/aspire/issues/1941
- https://github.com/Azure/azure-dev/issues/3279
