### ISSUE TITLE
[Issue] How to add CICD deployment for AZD to an existing (mature) repository?

### ISSUE THREAD

**Issue by diberry** [Azure/azure-dev#3023]
This is related to Issue #2851 - I need to set up the auth to allow AZD to package, provision, and deploy a repository. I only see steps for a new repo. How do I successfully set this up for an existing repository? 

1) Assume I have azd packaging, provisioning, and deploying successfully from my local environment and now I want to move to the next step of having azd do this from a GitHub action.
2) What are the minimal steps in Azure and in GitHub to accomplish this?

**Comment by weikanglim** [comment]
1. Create a workflow definition for the CI provider (GitHub or Azure DevOps). If looking for inspiration, see the workflow definitions under the `.azdo` or `.github` directory in our [minimal starter (bicep)](https://github.com/Azure-Samples/azd-starter-bicep/tree/main). The workflow simply does:
    - Install azd 
       ```
       - name: Install azd
          uses: Azure/setup-azd@v0.1.0
       ```

    - Login (`azd auth login`) with a service principal
    - Then run `azd provision`, `azd deploy` as normal.
3. Run `azd pipeline config` to set up the auth. See [Configure a pipeline and push updates](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/configure-devops-pipeline?tabs=GitHub).

**Comment by vhvb1989** [comment]
You can also see more github workflow definitions here: https://github.com/Azure/azure-dev/tree/main/templates/common/.github/workflows

**Comment by timheuer** [comment]
Also kinda feature tracked here: https://github.com/Azure/azure-dev/issues/2752

**Comment by dfberry** [comment]
Works for me. #please-close
