### ISSUE TITLE
[Issue] `azd provision` fails in CI for .NET Aspire

### ISSUE THREAD

**Issue by timheuer** [Azure/azure-dev#3027]
**Output from `azd version`**
azd version 1.5.0 (commit 012ae734904e0c376ce5074605a6d0d3f05789ee)

**Describe the bug**
When using `azd provision` in a .NET Aspire app (after a successful `init` and `pipeline config`) it fails to provision with:

```
ERROR: failed registering service hooks, failed getting services: importing services: generating app host manifest: selecting public services: no default response for prompt 'Select which services to expose to the Internet'
```

This is a result of a prompt input for determining which of the configured services are exposed to the internet in the ACA environment.

This information is saved in a config.json but by default that config.json is excluded in the default .gitignore pattern (which ignores .azure where this file is nested)

**To Reproduce**
See: https://github.com/timheuer/new-aspire-starter/actions/runs/7012943567/job/19078302319 for a sample run/repo

**Expected behavior**
Be able to set the prompt, move the config to a diff way, env vars, something that accepts the answer

**Comment by vhvb1989** [comment]
I'll work on this.
The multi-select component is missing default selections. 
Defaults should be set as env-variables on github (probably serializing the exported services, or the entire config json).

**Comment by timheuer** [comment]
Thanks @vhvb1989 if you have any PR builds you want me to help with validation ping me for sure. I was thinking the env vars might be exposed similar to the `SERVICE_X_ENDPOINTS` array idea.

I do wonder @mitchdenny if something in the Aspire appmodel could encode this even so the manifest already describes this and doesn't even have the need to have user input at this stage 🤔

**Comment by ellismg** [comment]
> I do wonder @mitchdenny if something in the Aspire appmodel could encode this even so the manifest already describes this and doesn't even have the need to have user input at this stage 🤔

When we originally designed the feature, there was an ask from the Aspire team to have the tool deploying the aspire app make this assignment.  At the time @davidfowl and @mitchdenny wanted this because I think it made manifest generation much easier and faster on their end and also simplified their app model.

I'm not wed to the current design, if this could be exposed in the manifest itself, I'd love to consume it from there, but I think the Aspire team had good reasons for pushing towards this split.

**Comment by mitchdenny** [comment]
I would have thought the selection of what endpoints to expose would be a per environment setting (potentially) or a global setting which could be checked into the repo.

@vhvb1989  ... what was the resolution to this issue on the AZD side?

**Comment by timheuer** [comment]
> @vhvb1989 ... what was the resolution to this issue on the AZD side?

Now when you run `azd pipeline config` in indeed does set those settings in the repo in an `AZD_INITIAL_ENVIRONMENT_CONFIG` secret
