### ISSUE TITLE
[Issue] Running `azd pipeline config` on Aspire apphost project fails to recognize repo root

### ISSUE THREAD

**Issue by timheuer** [Azure/azure-dev#3034]
**Output from `azd version`**
azd version 1.5.0 (commit 012ae734904e0c376ce5074605a6d0d3f05789ee)

**Describe the bug**
When running `azd pipeline config` in the aspire apphost project directory it fails with:

```
Error: no CI/CD provider configuration found. Expecting either github and/or azdo folder in the project root directory.
```

The project however is in a git repository and there is a `.github\workflows\build.yaml` file present.  `azd` seems to look at project root versus repo root

**To Reproduce**

1. `dotnet new aspire-starter`
2. (add to a github repo)
3. `azd init` for Aspire
4. add a workflow file at the repo root (.github\workflows\foo.yaml)
5. run `azd pipeline config`

**Expected behavior**
I expect the pipeline config to work.  It does not :-).

**Comment by Petermarcu** [comment]
Yeah, I think the whole convention is that it looks in the project root. @ellismg should we consider probing or is the guidance here to specify the relative path in azure.yaml?

**Comment by spboyer** [comment]
Need to consider GHA modifications for Aspire applications and `azd synth`

**Comment by vhvb1989** [comment]
> azd seems to look at project root versus repo root

Yes, that's per design. You can have multiple azd projects within one only repo (for example, one repo full of azd samples).

In the future, once we implement https://github.com/Azure/azure-dev/issues/2752, azd won't require to have `.github/workflows` or `.azdo` folders next to the `azure.yaml`. But that is still TBD.
