### ISSUE TITLE
[Issue] allow azd (via azure.yaml) to add `—target` to docker build

### ISSUE THREAD

**Issue by splusq** [Azure/azure-dev#3050]
**Describe the bug**
Currently `azure.yaml` does not provide a mechanism to add a `--target` parameter to `docker build`. This is necessary for multi-stage docker build where there are multiple layers and at build time one decides which layer to target. 

**To Reproduce**
Run `azd package` on a multi-stage docker file there are no options to pass the `--target` argument. 

**Expected behavior**
If one were to build the docker file here's how one would pass the argument:

```
docker build --target foo -t docker.io/bar/baz -f foo/dockerfile .
```

**Environment**
Does not matter.

**Comment by rajeshkamal5050** [comment]
Does this already existing feature https://github.com/Azure/azure-dev/pull/2266 help achieve that? cc @vhvb1989  @wbreza

**Comment by Petermarcu** [comment]
--target is a different argument than what goes in buildargs. 

I started a PR here that might be enough to unblock. I don't think its complete but could be a starting point. 
https://github.com/Azure/azure-dev/pull/3052
