### ISSUE TITLE
Aspire: Support rabbitmq.connection.v0, rabbitmq.server.v0

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#3060]
We need to come up with a design for how we want to run this on Azure - It's not 100% clear what we want to do here - we need some production ready managed service at some point, but we might be able to get a way with "run an open source version as a container" as we do for our dev redis service with ACA.

**Comment by rajeshkamal5050** [comment]
Moving this to the Germanium semester bucket. We can pull it into appropriate milestones as we move along. Currently for Aspire Preview 3 we are targeting to add support for `sql/sqlserver` and `cosmos`

@davidfowl @mitchdenny @ellismg @spboyer @gkulin

**Comment by rajeshkamal5050** [comment]
We will not add hand-crafted, template-based Bicep deployment support in azd. Instead, we will be moving towards using bicep resource type and CDK effort.
- https://github.com/dotnet/aspire/issues/1941
- https://github.com/Azure/azure-dev/issues/3279
