### ISSUE TITLE
Aspire: Support azure.redis.v0

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#3061]
We should use: https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-overview.

**Comment by rajeshkamal5050** [comment]
Moving this to the Germanium semester bucket. We can pull it into appropriate milestones as we move along. Currently for Aspire Preview 3 we are targeting to add support for `sql/sqlserver` and `cosmos`

@davidfowl @mitchdenny @ellismg @spboyer @gkulin

**Comment by rajeshkamal5050** [comment]
We will not add hand-crafted, template-based Bicep deployment support in azd. Instead, we will be moving towards using bicep resource type and CDK effort.
- https://github.com/dotnet/aspire/issues/1941
- https://github.com/Azure/azure-dev/issues/3279
