### ISSUE TITLE
Aspire: Support dockerfile.v0 resource

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#3062]
We need to support the `dockerfile.v0` resource type, to allow Aspire applications to build and deploy containers from dockerfiles.  This is how they support non dotnet languages.  See https://github.com/dotnet/aspire/pull/1059 for the support in Aspire.

**Comment by rajeshkamal5050** [comment]
Added support in Azd as part of PR https://github.com/Azure/azure-dev/pull/3075

cc: @mitchdenny @davidfowl @bradygaster

**Comment by mitchdenny** [comment]
Thanks!
