### ISSUE TITLE
Aspire: Support azure.cosmosdb.account.v0, azure.cosmosdb.connection.v0

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#3066]
There is some existing code in the Aspire provisioning package for spinning these types up, we can use that as the basis for the bicep in our implementation.

**Comment by vhvb1989** [comment]
`azure.cosmosdb.connection.v0` seems to be already implemented

**Comment by vhvb1989** [comment]
For `azure.cosmosdb.account.v0`,

Expecting Net Aspire code: `builder.AddAzureCosmosDB("cosmo");`
With Manifest:

```json
    "cosmo": {
      "type": "azure.cosmosdb.account.v0"
    }
```
and ref:
```json
"ConnectionStrings__cosmo": "{cosmo.connectionString}",
```
