### ISSUE TITLE
Support .NET 8 dockerless build

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#3067]
Currently, `azd` supports dockerless builds using Oryx buildpacks for languages. `azd` uses builder image `mcr.microsoft.com/oryx/builder:debian-buster-20231004.1` for dotnet. This does not support .NET 8 yet.

Loosely, we have a few options:

### Option 1 (`buildpacks` support):

Wait for `mcr.microsoft.com/oryx/builder:debian-bookworm-20231004.1` to support all versions of .NET

### Option 2 (`buildpacks` + `azd` support)

Implement .NET version detection logic, to be able to switch builder images

### Option 3 (`azd` support + .NET container build)

Implement .NET version detection logic, for versions of .NET (maybe just 8.+) that support container support, use `dotnet publish` by default.

**Comment by spboyer** [comment]
If we go with Option 3, it would have to be for .NET 8+ only. In .NET 7, there is a nuget package required to support SDK Container builds. Need to consider local architecture target versus host target. Making sure there is a way to define `PLATFORM` for image. Cannot assume local=target host

**Comment by weikanglim** [comment]
We ended up on Option 1 with #3112

It will still be interesting to see how we want start slowly moving .NET8+ users onto .NET native publishing with #2632
