### ISSUE TITLE
Web page exception after running `azd up` on US Gov Cloud

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#3079]
**Describe the issue:**
Test `todo-java-mongo` template on US Gov Cloud. After running `azd up`, there are no errors in the output log, but when clicking on the web link to view it, it cannot be loaded properly, we see the following errors：

![image](https://github.com/Azure/azure-dev/assets/80496810/b5cd5b5f-989c-4d2e-9ee7-e01df207c023)

**Repro Steps:**

1. Login in with command: `azd auth login`.
2. Execute command: `azd init -t todo-java-mongo`.
3. Execute command: `azd up` and click web link.

**Environment:**

- Cloud: US Gov.
- Template: todo-java-mongo.
- Azd version : 1.6.0-beta.1  (commit https://github.com/Azure/azure-dev/commit/04fedb57ba251d0c7cfdc8e3612cdf35ee6c04f8)

**Expected behavior:**
The web can load normally after running `azd up`.

@danieljurek   for notification.

**Comment by danieljurek** [comment]
This issue doesn't reproduce. Java apps do take a while to launch so waiting a little longer would probably result in success.
