### ISSUE TITLE
API application error after running `azd up` on US Gov Cloud

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#3081]
**Describe the issue:**
Test `todo-python-mongo` template on US Gov Cloud. After running `azd up`, there are no errors in the output log, but when clicking on the API link to view it, get application errors：

![image](https://github.com/Azure/azure-dev/assets/80496810/4f005718-10ab-429a-913c-90879c3a66a4)

**Repro Steps:**

1. Login in with command: `azd auth login`.
2. Execute command: `azd init -t todo-python-mongo`.
3. Execute command: `azd up` and click api link.

**Environment:**

- Cloud: US Gov.
- Template: todo-python-mongo.
- Azd version : 1.6.0-beta.1  (commit https://github.com/Azure/azure-dev/commit/04fedb57ba251d0c7cfdc8e3612cdf35ee6c04f8)

**Expected behavior:**
The api application can start normally after running `azd up`.

@danieljurek   for notification.

**Comment by danieljurek** [comment]
This does not reproduce in my latest build: 

![image](https://github.com/Azure/azure-dev/assets/2158838/c42f896b-5cd0-4abb-b019-f6c1ca5e7469)
