### ISSUE TITLE
Aca templates failed to execute `azd up` on US Gov Cloud

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#3082]
**Describe the issue:**
Test `todo-java-mongo-aca` template on US Gov Cloud. Run `azd up`, get error as follow：

![image](https://github.com/Azure/azure-dev/assets/80496810/db427e26-99fa-4b2b-acf6-7808ec418377)

**Repro Steps:**

1. Login in with command: `azd auth login`.
2. Execute command: `azd init -t todo-java-mongo-aca`.
3. Run `azd up`.

**Environment:**

- Cloud: US Gov.
- Template: todo-java-mongo-aca, todo-python-mongo-aca, todo-nodejs-mongo-aca.
- Azd version : 1.6.0-beta.1  (commit https://github.com/Azure/azure-dev/commit/04fedb57ba251d0c7cfdc8e3612cdf35ee6c04f8)

**Expected behavior:**
Run `azd up` can pass.

@danieljurek   for notification.

**Comment by danieljurek** [comment]
The API is available but not at the requested version. Can we use a common non-preview version of the API?

**Comment by v-jiaodi** [comment]
@danieljurek When use the API version: `2023-05-01`, `2023-05-02-preview`, `2023-08-01-preview`, get error as follow:

![image](https://github.com/Azure/azure-dev/assets/80496810/a246d71e-5895-4596-beb8-94fbd6e1ebf4)
![image](https://github.com/Azure/azure-dev/assets/80496810/795c926f-21df-43e1-a8e5-53a5b55ba8b4)

**Comment by danieljurek** [comment]
I'm not certain that ACA is supported in gov clouds (though some of the endpoints do exist). I'll need to check this more thoroughly. 

https://azure.status.microsoft/en-us/status

Select "Azure Government" at the top
![image](https://github.com/Azure/azure-dev/assets/2158838/f724d88d-d274-4e8c-9491-8aeb170410e3)


![image](https://github.com/Azure/azure-dev/assets/2158838/4bad588f-2881-4f9a-9221-2e287cbed04b)

**Comment by v-jiaodi** [comment]
@danieljurek According to `AzdManualTestSovereignClouds.docx` retest, the same issue still exists for aca templates.

**Comment by danieljurek** [comment]
Let's close this. ACA isn't available for sovereign clouds. I've updated the testing doc.
