### ISSUE TITLE
Function templates failed to execute `azd up` on US Gov Cloud

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#3084]
**Describe the issue:**
Test `todo-csharp-sql-swa-func` template on US Gov Cloud. Run `azd up`, get error as follow：

![image](https://github.com/Azure/azure-dev/assets/80496810/fc7182ca-437b-4d6e-85fb-81f49ef8ff55)

**Repro Steps:**

1. Login in with command: `azd auth login`.
2. Execute command: `azd init -t todo-csharp-sql-swa-func`.
3. Run `azd up`.

**Environment:**

- Cloud: US Gov.
- Template: todo-csharp-sql-swa-func, todo-nodejs-mongo-swa-func, todo-python-mongo-swa-func.
- Azd version : 1.6.0-beta.1  (commit https://github.com/Azure/azure-dev/commit/04fedb57ba251d0c7cfdc8e3612cdf35ee6c04f8)

**Expected behavior:**
Run `azd up` can pass.

@danieljurek   for notification.

**Comment by danieljurek** [comment]
Static web apps are not supported in gov cloud at this time. This template is not supported in gov cloud.

**Comment by dotnet-7** [comment]
@danieljurek The following environment also have the same issue on China Cloud:

- azd version: 1.6.0-beta.1-pr.3436205 (commit 79ee6dfcae682672d0808d2590b93d298fcba844)
- Templates: `todo-csharp-sql-swa-func` ,`todo-nodejs-mongo-swa-func`, `todo-python-mongo-swa-func`.
- Branch: [pr2897](https://github.com/Azure/azure-dev/pull/2897).
- Cloud: China.

**Comment by danieljurek** [comment]
Static web apps not available in China Cloud. Thanks!
