### ISSUE TITLE
Fail to run "azd restore" for PR3017

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-dev#3087]
**Describe the issue:**
Based on [PR3017](https://github.com/Azure/azure-dev/pull/3017), running the `azd restore` command failed, the error is as follows:
![image](https://github.com/Azure/azure-dev/assets/111940661/b8f73dcd-117b-4280-b41b-d88523fa3629)

Besides, use the **latest release azd version** to test the **main** branch, also has the same issue.

**Repro steps:**
1. Run command `azd auth login`.
2. Run command `azd init -t Azure-Samples/todo-csharp-sql-swa-func -b pr/3017`.
3. Run command `azd up`.
4. Run command `azd restore`.

**Environment:**

1.
- azd version: `azd version 1.6.0-beta.1-pr.3312226 (commit 422b1d81a9f2d5bde45278b955ea5d168f1ef6a0)` .
- Templates: `https://github.com/Azure-Samples/todo-csharp-sql-swa-func.git`.
- Branch: pr/3017.
- OS : windows desktop.

2.
- azd version: `azd version 1.5.0 (commit 012ae734904e0c376ce5074605a6d0d3f05789ee)`.
- Templates: `https://github.com/Azure-Samples/todo-csharp-sql-swa-func.git`.
- Branch: main.
- OS: windows desktop.

**Expected behavior:**
The `azd restore` command can be run successfully.

@rajeshkamal5050, @jongio and @isaacrlevin for notification.

**Comment by vhvb1989** [comment]
This is not related to updating to NET8

I can reproduce this issue for `azd restore` using `1.5.0` version.

**Comment by vhvb1989** [comment]
Simple repro:

> dotnet new console
> azd init
> azd restore

**Comment by Menghua1** [comment]
@vhvb1989 Based on the azd version of [pr3106](https://github.com/Azure/azure-dev/pull/3106), this issue has been fixed.
However, based on the azd version of [pr3017](https://github.com/Azure/azure-dev/pull/3017), this issue still exists and has not been fixed.

**Comment by v-xuto** [comment]
@vhvb1989 Based on the latest azd version of [PR3017](https://github.com/Azure/azure-dev/pull/3017), this issue has been fixed.
