### ISSUE TITLE
Azure DevOps pipeline manual setup documentation contradicts examples

### ISSUE THREAD

**Issue by TWolversonReply** [Azure/azure-dev#3088]
https://github.com/Azure/azure-dev/blob/main/templates/common/.azdo/pipelines/bicep/azure-dev.yml fails in my environment - it looks as though `$Env:AZURE_CREDENTIALS` isn't set, which I would expect. [This documentation](https://github.com/Azure/azure-dev/blob/main/cli/azd/docs/manual-pipeline-config.md) says:
> The Azure DevOps pipelines from the azd samples depend on the task AzureCLI@2 which uses the Azure CLI to provide authentication.

The samples don't mention this, that I can see. This is how I think it should work; I do have a service connection and that's what I want to use; it looks as though the azdo example has been overwritten with how GitHub would do it, where that is not idiomatic in Azure DevOps. This definitely won't work with [Federated Credentials](https://techcommunity.microsoft.com/t5/azure-devops-blog/introduction-to-azure-devops-workload-identity-federation-oidc/ba-p/3908687) style service connections, because it expects a client secret and with federated managed identity _there isn't one._

Additionally, it is not well explained what `azd pipeline config` is doing, I haven't run it because since I don't have that explanation, I can't trust that it won't do something I don't want in my ADO tenant - which is what it looks like it means to do, probably by setting a variable with the AZURE_CREDENTIALS. I don't want that, I want to use the normal way - which is a service connection.

**Comment by vhvb1989** [comment]
Hello @TWolversonReply 

We recently updated ADO default pipelines for samples [here](https://github.com/Azure/azure-dev/pull/2701/files#diff-ee20f4a73f08c798def8b8469b0de5ba16f74797f9ae3ce588432f7c95d19edeL24).

We have missed updating the documentation you linked.

This change was to remove the dependency on `az` and on the universal-img (mcr.microsoft.com/azure-dev-cli-apps:latest) which is huge and more than folks might need for CI.

When you run `azd pipeline config --provider azdo`:
  - Federated credential is not supported. azd automatically changes to secret-client and displays a warning about it.
  - azd creates the ADO pipeline definition and a `service connection` with the name `azconnection`.  If the `service connection` with such name already exists, it is updated based on the SP used.

So, even we updated the pipeline definition to use an ADO pipeline step to install azd + a `ubuntu-latest` as the base image, you can still move back your definition to use `az + azconnection service connection` and it would work for you.
If you have an existing service connection, you can just update your pipeline definition and set that name.

Here is more information/docs about `pipeline config`: https://github.com/Azure/azure-dev/blob/main/cli/azd/docs/manual-pipeline-config.md

Next steps for this issue:
- Update official docs based on this information. We need to tell customers how they can use an existing service connection, or create a new one.
- Update the default pipeline definition for ADO with a note about this and a link to the docs. This should help users moving to use the definition they want.
- Design and create a new ADO step for `azd` that uses a service-connection, similar to `AzureCLI@2`.  It could be just a login step for azd, or a general step which would allow running any azd command with specific login credentials.

**Comment by vhvb1989** [comment]
@TWolversonReply 

> Could I clarify whether it is just avoiding the messy dependency that is the motivation here, and there is no reliability/supportability reason I shouldn't do this?

The change was just to avoid the dependency on `AzureCLI@2`.  
I have created a PR which moves us back to use it until azd has its own task which supports using a service-connection.
no reliability/supportability reason.
