### ISSUE TITLE
Request - Improve `azd auth login --use-device-code` for Jupyter notebook use in Codespaces

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-dev#3091]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 1.5.0 (commit 012ae734904e0c376ce5074605a6d0d3f05789ee)

**Describe the bug**
I'm working on using azd in a Jupyter/Polyglot notebook in Codespaces.

While I can run `azd auth login --use-device-code` in a cell, the output of the cell is non-interactive so I can't press enter to cause the login web page to open.

My workaround is to tell the user to copy the command and paste it in the VS Code terminal.

**To Reproduce**
Steps to reproduce the behavior...
1. In a Jupyter notebook running in Codespaces, create a code cell with `!azd auth login --use-device-code`
2. Execute the cell
3. See that the cell just hangs waiting for input from the user

**Expected behavior**
When the cell is executed, I expect the URL to be shown at the same time as the code.
My suggestion is to add a `--no-wait` or similar parameter.

I would be happy to talk this over with the team to show the full scenario and find a great user experience.

**Environment**
Information on your environment:
    * Jupyter and/or Polyglot Notebook

**Additional context**

**Comment by rajeshkamal5050** [comment]
@charris-msft does this help `azd auth login --use-device-code --no-prompt` ref: https://github.com/Azure/azure-dev/issues/2605#issuecomment-1668346781

cc: @vhvb1989 added this a while back.

**Comment by charris-msft** [comment]
> @charris-msft does this help `azd auth login --use-device-code --no-prompt` ref: [#2605 (comment)](https://github.com/Azure/azure-dev/issues/2605#issuecomment-1668346781)
> 
> cc: @vhvb1989 added this a while back.

Unfortunately, no. 

When I use that in a Jupyter notebook in Codespaces, the cell hangs, there is no output text so I can't copy the code, and there is no browser window that opens.

The experience for `az` is probably closer to the ideal at this point:
![image](https://github.com/Azure/azure-dev/assets/74415662/2fecb5db-9b68-4012-8d6d-99b787cce66b)
It shows the URL and the Code in the output, so I can copy the code and click the URL link.

**Comment by vhvb1989** [comment]
@charris-msft , can you try `azd auth login --use-device-code --no-prompt --debug 2>&1` and share a screenshot of what you get?

My guess is that Jupyter is not showing the output until the command is not completed or that azd is sending output to stderr and output is not visible.  By running command, I am hoping that `2>&1` at the end will redirect stderr to stdout and see everything on the Jupy output.

**Comment by charris-msft** [comment]
That partially worked. 

I got output, which you can see below.
And another browser tab opened for the deviceauth page.

However, it happened so fast there was no time to copy the device code before the tab opened. And for a user unfamiliar with the process they wouldn't know to go back to the Notebook tab and copy the code.

Full text:
```
2023/12/08 20:34:13 main.go:54: azd version: 1.5.0 (commit 012ae734904e0c376ce5074605a6d0d3f05789ee)
2023/12/08 20:34:13 user_config_manager.go:39: creating empty config since '/home/vscode/.azd/config.json' did not exist.
2023/12/08 20:34:13 main.go:211: ignoring cached latest version, it is out of date
2023/12/08 20:34:13 main.go:233: fetching latest version information for update check
2023/12/08 20:34:13 cobra_builder.go:141: Resolved action 'azd-auth-login-action'
2023/12/08 20:34:13 middleware.go:124: running middleware 'debug'
2023/12/08 20:34:13 middleware.go:124: running middleware 'experimentation'
2023/12/08 20:34:13 assignment.go:87: could not read assignment from cache: cache expired
2023/12/08 20:34:13 main.go:48: Retry: =====> Try=1
2023/12/08 20:34:13 main.go:48: Request: ==> OUTGOING REQUEST (Try=1)
   GET https://default.exp-tas.com/exptas49/b80dfe81-554e-48ec-a7bc-1dd773cd6a54-azdexpws/api/v1/tas
   Accept: application/json
   User-Agent: azsdk-go-variantassignment/0.0.1 (go1.21.0 X:loopvar; linux)
   X-ExP-Parameters: REDACTED
   X-Exp-Sdk-Version: REDACTED

2023/12/08 20:34:13 main.go:48: Response: ==> REQUEST/RESPONSE (Try=1/38.580658ms, OpTime=38.6139ms) -- RESPONSE RECEIVED
   GET https://default.exp-tas.com/exptas49/b80dfe81-554e-48ec-a7bc-1dd773cd6a54-azdexpws/api/v1/tas
   Accept: application/json
   User-Agent: azsdk-go-variantassignment/0.0.1 (go1.21.0 X:loopvar; linux)
   X-ExP-Parameters: REDACTED
   X-Exp-Sdk-Version: REDACTED
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Content-Length: 369
   Content-Type: application/json; charset=utf-8
   Date: Fri, 08 Dec 2023 20:34:13 GMT
   Etag: -1240097783_602342615
   X-Cache: REDACTED
   X-Content-Type-Options: REDACTED
   X-Exp-Trackingid: REDACTED
   X-Msedge-Ref: REDACTED

2023/12/08 20:34:13 main.go:48: Retry: response 200
2023/12/08 20:34:13 main.go:48: Retry: exit due to non-retriable status code
2023/12/08 20:34:13 experimentation.go:42: assignment context: initflow_c:78272;0g5ad841:76970;
2023/12/08 20:34:13 middleware.go:124: running middleware 'telemetry'
2023/12/08 20:34:13 telemetry.go:50: TraceID: 021c96462df2a7d2038a07243ff504f1
Start by copying the next code: B545NZ6QB
Then press enter and continue to log in from your browser...
2023/12/08 20:34:14 command_runner.go:307: Run exec: '/vscode/bin/linux-x64/af28b32d7e553898b2a91af498b1fb666fdebe0c/bin/helpers/browser.sh https://microsoft.com/devicelogin' , exit code: 0
Waiting for you to complete authentication in the browser...
2023/12/08 20:34:14 main.go:290: updated cache file to version 1.5.0 (expires on: 2023-12-09T20:34:14Z)
```
Screenshot:
![image](https://github.com/Azure/azure-dev/assets/74415662/11994f26-e85d-4eee-b2cc-9076261e4c5e)
