### ISSUE TITLE
Fail to "Start API" for PR3017 of "todo-csharp-sql-swa-func"

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-dev#3109]
**Describe the issue:**
Executed  the `Start API` task failed, the error is as follows:
<img width="686" alt="image" src="https://github.com/Azure/azure-dev/assets/111940661/d875b69b-b554-445f-ab17-724be1ff5078">
**Repro steps:**
1. Open a codesapces on pr/3017 of `todo-csharp-sql-swa-func`.
2. Install azd `curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3017/install-azd.sh | bash -s -- --base-url https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3017 --version '' --verbose --skip-verify`.
3. Run command `azd auth login`.
4. Run command `azd up`.
5. Hit F1 -> Run Task -> Start API.

**Environment:**

- azd version: `azd version 1.6.0-beta.1-pr.3330875 (commit 0995c4269de837e45038f8efac2c78633ad3a0d6)`.
- Templates: `https://github.com/Azure-Samples/todo-csharp-sql-swa-func.git`.
- Branch: pr/3017.
- OS: codespaces.

**Expected behavior:**
`Start API` task can be run successfully.

@rajeshkamal5050, @vhvb1989, @jongio and @isaacrlevin for notification.

**Comment by Menghua1** [comment]
After running `npm i -g azure-functions-core-tools@4 --unsafe-perm true` in `codespace`, the `Start API` task can be executed successfully.

**Comment by vhvb1989** [comment]
fixed using postCreateCommand on devcontainer
