### ISSUE TITLE
Ability to add custom CLI commands

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#311]
Imagine a scenario where an app dev team has standardized on use the Azure Dev CLI for all of their development.  It is great that we give them commands like `monitor` that will launch our default dashboard.  

How can we help take the dev team to the next level?

## Initial use case

I'm an app dev @ Contoso.  We use azure dev CLI for all our green field development.  We would like at extend the commands offered in the CLI to include our own custom command called `rollback`. (this can be whatever they want)

## How to support this

Add special CLI configuration file in the `.azure` folder.  The file contains configuration values for command/subcommands/scripts to include in the CLI. 

The CLI will check for the existence of this file at runtime and give you proper intelligence help, etc.

Users can author custom scripts as bash or powershell scripts.  Scripts would be invoked with current environment variables as well as any custom command parameters available.

**Comment by rajeshkamal5050** [comment]
@wbreza feels like the will get accomplished via #3565
