### ISSUE TITLE
Any planned support for Go?

### ISSUE THREAD

**Issue by seesharprun** [Azure/azure-dev#3111]
I noticed that Go wasn't in the list of supported languages: https://learn.microsoft.com/azure/developer/azure-developer-cli/supported-languages-environments

I searched the issues but couldn't find any related discussions around planned support for Go. I also could be bad at GitHub search and not found it for that reason 😅.

Is support for Go as a programming language being considered for the future? My use case is to host a Go application in a Dockerfile and run it on Azure Container Apps.

**Comment by vhvb1989** [comment]
Hello @seesharprun, there's not an official plan for go.

Can you describe what would it be your user case?  Are you looking for hosting a backend service?  or are you using some go-eco-system like [buffalo](https://gobuffalo.io/) for your entire app?

As an alternative, you can use Azure Container Apps to host a go service and have azd to do the deployment end2end.
Here's a repo with an example: https://github.com/vhvb1989/goaca

Basically, when working with `Azure Container Apps`, it doesn't really matter what's the language you set for `azd` on azure.yaml, you can control how to build your container from your Dockerfile and your sourcecode. So, this is an alternative which you can use to support any language, running your service in a container.

Would Container apps work for your scenario?  or are you looking for Azure WebApps to host your service?

We have this 2 related issues:
  https://github.com/Azure/azure-dev/issues/2935
  https://github.com/Azure/azure-dev/issues/1891

There's already some interest from folks to break the dependency on a laguage when containerapp is set as a host.

**Comment by seesharprun** [comment]
ACA is my preferred solution and it's good to see that there are other related issues to allow ACA without a language specified. That's enough for me to close this issue.

Thanks!
