### ISSUE TITLE
Aspire manifest resource types to Azure resource type mappings.

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-dev#3121]
This is a meta issue to track proposed mappings from Aspire manifest resource types to concrete Azure managed resource types. We would prefer to provision managed services where possible because they are going to be better from an operability point of view for production deployments. Here are the initial mappings.

| Manifest resource type                  | Proposed Azure managed resource                                                                                                                                                               |
| --------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| postgres.server.v0                      | [Azure Postgres Flexible Server](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/overview "https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/overview")   |
| mongodb.server.v0                       | [Azure Cosmos for Mongo DB](https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/introduction "https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/introduction")?                 |
| mysql.server.v0                         | [Azure Database for MySQL](https://learn.microsoft.com/en-us/azure/mysql/flexible-server/overview#overview "https://learn.microsoft.com/en-us/azure/mysql/flexible-server/overview#overview") |
| rabbitmq.server.v0                      | ???? There seems to be some way to bridge rabbitmq to Service Bus, but a container might be the best option here. Much harder to get this right from a production operability perspective.    |
| redis.v0<br>azure.redis.v0                | [Azure Cache for Redis](https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-overview "https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-overview")          |
| sqlserver.server.v0<br>azuresql.server.v0 | [Azure SQL Database](https://azure.microsoft.com/en-au/products/azure-sql/database/ "https://azure.microsoft.com/en-au/products/azure-sql/database/")                                         |
| azure.storage.v0                        | Self explanitory                                                                                                                                                                              
| azure.appconfiguration.v0               | Self explanitory                                                                                                                                                                              
| azure.cosmosdb.v0                       | Self explanitory                                                                                                                                                                              
| azure.servicebus.v0                     | Self explanitory                                                                                                                                                                              
| oracle.server.v0                        | Apparently there is a new managed service Oracle Database@Azure that we could look at here.                                                  
| kafka.server.v0                         | Azure event hubs? I think there is some Kafka support

**Comment by ellismg** [comment]
> ???? There seems to be some way to bridge rabbitmq to Service Bus, but a container might be the best option here. Much harder to get this right from a production operability perspective.

From my (admittedly brief) amount of reading - it seems like there are bridges that allow you to push data from RabbitMQ to ServiceBus, but I didn't see anything that would allow you to connect to a service bus from an existing RabbitMQ client.

This might be a place where we can come up with a "reasonable story" for development (containers with perhaps a volume mount for durability) but for folks that want to do something "production ready" we provide a way for them to bring their own implementation (i.e. if you could give `azd` a template-spec and some properties, we could just deploy whatever bicep you needed to get RabbitMQ stood up and then publish an output like `connectionString` and `azd` can wire everything up...

**Comment by vhvb1989** [comment]
Closing this in favor of the `bicep.v0` support on preview.4
