### ISSUE TITLE
`azd` should not create multiple containers when two `postgres.database.v0` Aspire resources share the same parent.

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-dev#3134]
Currently when `azd` encounters an AppHost with multiple `postgres.database.v0` resources it will create a container for each database. This is not desirable. Instead `azd` should create a single database server, and then inject variations of the connection string for each database that would be hosted on that server.

Developers also need to get a connection string to the database server (whether it is a container or hosted on a managed service). 

Workaround:
As a temporary work around developers can pass a reference to the database and then create a new connection after trimming off the database specific entry. We should aim to fix this up for preview 3 so this isn't necessary.

**Comment by ellismg** [comment]
I wonder - are we going to have to do anything special to ensure these databases are created when using the ACA postgres service?  I know when using something like the postgres container you can set an environment variable for the initial database that is created, but I am wondering if you need to run `CREATE DATABASE` calls for the other databases - or is that something the Aspire component will do as part of booting up?

When we map this to something like Postgres Flexible Server, it seems there's a bicep resource that models the database separate from the account, so the mapping in that world is clear: https://learn.microsoft.com/en-us/azure/templates/microsoft.dbforpostgresql/flexibleservers/databases?pivots=deployment-language-bicep

**Comment by weikanglim** [comment]
Like @ellismg mentions, this is definitely straightforward when it's a managed resource (prod). For container app add-ons (dev), there isn't a straightforward option without extra weight on `azd` or additional support from ACA.

`azd` currently uses the ACA provided `postgres` container image / add-on service, which is built upon the official postgres image. The ACA add-on service does additional things like automatically configure `pg-password` as a Container App secret, and assumes single DB setup. Thus, we could make an ask here to support multiple database setups if we were to stick to the ACA provided `postgres` add-on service.

If we or ACA were wanting to configure this using the official [postgres image](https://hub.docker.com/_/postgres/), we'd need configure a mounted initialization script with the docker image to create multiple DBs. The easiest way is probably to simply create a derived docker image with something similar looking to [this](https://github.com/mrts/docker-postgresql-multiple-databases).
