### ISSUE TITLE
`azd` should support `mysql.server.v0` and `mysql.database.v0` Aspire resource types

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-dev#3135]
Currently the only way to trigger deployment of MySql is via `AddMySqlContainer(...)` which will not enable managed resource deployments. When we add support for managed resources we'll want to be able to deploy MySql to this resource type:

https://learn.microsoft.com/en-us/azure/mysql/flexible-server/overview

Currently deployments fail with:

```
ERROR: generating bicep from manifest: unsupported resource type: mysql.server.v0
```

and

```
ERROR: generating bicep from manifest: unsupported resource type: mysql.database.v0
```

**Comment by rajeshkamal5050** [comment]
We will not add hand-crafted, template-based Bicep deployment support in azd. Instead, we will be moving towards using bicep resource type and CDK effort.
- https://github.com/dotnet/aspire/issues/1941
- https://github.com/Azure/azure-dev/issues/3279
