### ISSUE TITLE
Add C#, Azure SQL, SWA, Func App Todo App Template

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#315]

**Comment by rajeshkamal5050** [comment]
@wbreza do you think this is a duplicate of https://github.com/Azure/azure-dev/issues/450 which @karolz-ms is looking into for the current milestone?

**Comment by wbreza** [comment]
@rajeshkamal5050  - Not a duplicate, just a variation of the template with SWA & function app support.

**Comment by jongio** [comment]
We are going with #316 for this template.

**Comment by savannahostrowski** [comment]
Do we have a link to this repo yet?
