### ISSUE TITLE
[Issue] configuring ingress for project silo: the transport property of all bindings should match

### ISSUE THREAD

**Issue by KSemenenko** [Azure/azure-dev#3153]
azd 1.5.1

aspire code
``` cs
var silo = builder.AddProject<Projects.Silo>("silo")
     .WithServiceBinding(8080, "http")
     .WithServiceBinding(11111, "tcp")
     .WithServiceBinding(30000, "tcp");
```
And I get an error:

`ERROR: generating infra/ folder: configuring ingress for project silo: the transport property of all bindings should match`

I think this is wrong, in case of I need http and tcp endpoints.

**Comment by rajeshkamal5050** [comment]
Thanks for reporting @KSemenenko 

FYI, we have an ongoing discussion here on this - https://github.com/Azure/azure-dev/issues/3123#issuecomment-1861882895

**Comment by rajeshkamal5050** [comment]
Duplicate of #3267
