### ISSUE TITLE
[WebToolsE2E][Aspire] Deploying aspire starter app using 'azd up', the status of container app shows failed: ContainerCrashing

### ISSUE THREAD

**Issue by v-cazhang** [Azure/azure-dev#3158]
**REGRESSION INFO**: Works fine on Aspire.ProjectTemplates.8.0.0-preview.2.23619.3 + azd 1.5.1

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install 8.0 SDK: 8.0.200-preview.23613.10
3. Install Aspire Preview 2 latest build 8.0.0-preview.3.23619.4
4. Apply NuGet Feeds
5. Install azd 1.5.1

**REPRO STEPS**

1. Open CMD, creating and running an Aspire Starter App using following commands:
        `dotnet new aspire-starter -o aspire1`
2. Open Powershell window and go to the aspire1 folder, type '`azd init`' then select 'Use code in the current directory' > Confirm and continue initializing my app, type a new environment name, press enter.
3. Then type '`azd up`' to deploy it.
4. Open the resource group, click the 'webfrontend' container app.

**Notes**:

1. This issue also repro on Aspire Starter Application with redis checked.
2. This issue also repro on the web project with aspire checked.
3. This issue doesn't repro on web project without aspire.

**ACTUAL**
The status shows failed:  Failed:webapplication2ContainerCrashing
![image](https://github.com/Azure/azure-dev/assets/82028229/2f8a4159-396c-47e8-9e0c-fecd48cf1e3a)

**EXPECTED**
![image](https://github.com/Azure/azure-dev/assets/82028229/2aecfa9a-e533-487b-ba1b-7d4d8425608d)

**Comment by rajeshkamal5050** [comment]
@v-cazhang still able to reproduce this with the latest aspire bits and [latest azd bits](https://github.com/Azure/azure-dev/tree/main/cli/installer#download-from-daily-builds)

@hemarina @vhvb1989 can you also try reproducing it?

**Comment by v-cazhang** [comment]
Hi @rajeshkamal5050, I verified on Aspire.ProjectTemplates.8.0.0-preview.3.24055.2 + azd version 1.6.0-beta.1-daily.3380999 today, this issue still repro.

**Comment by rajeshkamal5050** [comment]
@v-cazhang can you share more details on the error, also capture the relevant container app logs to take a look?

**Comment by v-cazhang** [comment]
Hi @rajeshkamal5050 , click 'View details' next to the 'failed', it shows this:
![image](https://github.com/Azure/azure-dev/assets/82028229/92cb6c70-de5f-44e0-9b17-8308ef0244f2)

the logs of container shows like below:
![image](https://github.com/Azure/azure-dev/assets/82028229/fdd8f9b4-5b41-47a3-acc0-814ac898a331)

**Comment by v-cazhang** [comment]
Running '`dotnet workload list`', '`Installation Source`' shows as below:
![image](https://github.com/Azure/azure-dev/assets/82028229/c6798ffa-b730-4e03-9ff3-bc9fd19323a3)

**Comment by rajeshkamal5050** [comment]
@v-cazhang seems related to a regression in 8.0.2xx on the dotnet sdk. Seems to have been merged and fixed https://github.com/dotnet/sdk/pull/37996

Please validate with the latest 8.0.2xx which has the above fix.

**Comment by v-cazhang** [comment]
Verified with SDK 8.0.200 + Aspire.ProjectTemplates.8.0.0-preview.3.24073.5 + azd 1.6.0 daily build, this issue doesn't reproduce.
