### ISSUE TITLE
[Issue] Does todo-nodejs-mongo-aca use SWA? 

### ISSUE THREAD

**Issue by dfberry** [Azure/azure-dev#3165]
**Describe the bug**
The sample copies the SWA config file into the build directory as part of the [postbuild step](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/blob/main/src/web/package.json#L20). I've only seen this [todo-nodejs-mongo-aca sample](https://github.com/Azure-Samples/todo-nodejs-mongo-aca) deployed to Azure Container apps (for both api and front-end). 

```
"postbuild": "shx cp ./entrypoint.sh ./build && shx cp staticwebapp.config.json ./build || echo 'post-build completed'",
```

Should this part of the postbuild script for the web app be removed? Or is there a way to deploy this app as a SWA service inside ACA?

**Comment by wbreza** [comment]
No, the `todo-nodejs-mongo-aca` sample does not use SWA.  The reference to `staticwebapp.config.json` is an artifact of us sharing the same frontend code across many of our todo samples.  It could be removed without any harm.

I am not aware of a way to deploy SWA within containerapp.  You could run the backend API as a container app and the frontend as a SWA if desired.  You can use the relevant IaC templates from the [ACA sample](https://github.com/azure-samples/todo-nodejs-mongo-aca) and the [SWA sample](https://github.com/azure-samples/todo-nodejs-mongo-swa-func).

**Comment by weikanglim** [comment]
The `postbuild` task has been removed since a previous change to uptake Vite.
