### ISSUE TITLE
[Issue] Azure MySQL for Databases not Shown in deployment output

### ISSUE THREAD

**Issue by john0isaac** [Azure/azure-dev#3167]
**Output from `azd version`**
`azd version 1.5.1`

**Describe the bug**
I'm using bicep to create an Azure Database for MySQL the bicep is implemented on Azure using azd as you can see below but the output during the deployment process doesn't show anything related to the creation of the database.

Using this template [john0isaac/flask-webapp-mysql-db](https://github.com/john0isaac/flask-webapp-mysql-db).
You can try it out in codespaces I had configured it for the main branch.

![image](https://github.com/Azure/azure-dev/assets/64026625/acd4ad3c-15b4-4bd4-a1b4-72b77ff176d5)

Resources created sucessfully on Azure
![image](https://github.com/Azure/azure-dev/assets/64026625/7a06c7b5-791a-4a58-8fb0-453c9c40db94)

**To Reproduce**
- Run `azd up` or `azd provision`.

**Expected behavior**
Showing Azure Databases for MySQL Flexible server like it shows for Postgresql Database.

**Comment by ellismg** [comment]
We have a hard-coded mapping of resource type to what we display in [azure_resource_types.go](https://github.com/Azure/azure-dev/blob/a0bf60d9bc53aa11b08c9bfd2adf9f3dddd5c70e/cli/azd/pkg/infra/azure_resource_types.go).  https://github.com/Azure/azure-dev/pull/2952 is an example where we updated this previously.

@weikanglim was looking into if we could somehow generate this from the same source of truth that the portal uses, but no luck there yet.

Care to open a PR, @john0isaac?

**Comment by john0isaac** [comment]
@ellismg of course!!
Thanks for the clarification, it's really helpful!

**Comment by john0isaac** [comment]
I thought of something
What if instead of returning nothing if the name doesn't exist
https://github.com/Azure/azure-dev/blob/278a2525d03400e2f8c196148911c42d3a5392ba/cli/azd/pkg/infra/azure_resource_types.go#L116
We strip the name of the resource type from "Microsoft.Storage/storageAccounts@2827373" we take the "storageAccounts" and return it as the default for the switch case.

It's not going to be aesthetic but it's better than nothing.

Also, this will only be displayed for the names of the services we haven't hard-coded in the file.

**Comment by ellismg** [comment]
One of the reasons we were doing this translation (in addition to providing nicer names that what the resource providers gave us) was that we also used it to filter out "uninteresting" resources, like role assignments.

It might, however, be nice to group the operations that this filter elides today into a single item, especially when these are the only operations "in flight" to make it a little clearer that something is going on behind the scenes.

**Comment by john0isaac** [comment]
What you are saying means that even if somehow we managed to pull the names from Azure, we will still need these checks for the "uninteresting" resources.

I'm wondering now which is less? the resources we haven't hard-coded or the resources we have? because if the "uninteresting" resources for example are 10 then I think that we should opt into hard-coding them and returning an empty string if they are being created.
For the rest of the resources if they are not hard-coded and it's a major resource like a database (Azure MySQL DB takes at least 5 mins to be created) then it's better if we show something in the terminal rather than just "creating, updating resources".

TBH, I don't think it's a major issue, it's more of an improvement. LMK what you decide.
