### ISSUE TITLE
[WebToolsE2E][Aspire] Running 'azd init' for aspire project fails with error: "failed to generate manifest from app host project."

### ISSUE THREAD

**Issue by v-sherryfan** [Azure/azure-dev#3174]
**REGRESSION INFO:** Works fine on Aspire.ProjectTemplates.8.0.0-preview.3.24053.2 + azd 1.5.1 / Aspire.ProjectTemplates.8.0.0-preview.2.23619.3 + azd 1.5.1

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install 17.9 Preview3
3. Install Aspire Preview 3 latest build 8.0.0-preview.3.24054.3
4. Apply NuGet Feeds
5. Install azd 1.5.1

**REPRO STEPS**

1. In the VS, create a new project > ASP.NET Core Web API> .NET 8.0 > check 'Enlist in Aspire Orchestration' > Create
2. Right-click solution > Open folder in file explorer > open in terminal
3. Type 'azd init' then select 'Use code in the current directory'

Notes: 

1. This issue cannot be reproduced without the aspire project.

**ACTUAL**
failed to generate manifest from app host project: generating app host manifest: dotnet run --publisher manifest on project ''xxx.AppHost\xxx.AppHost.csproj failed.
![image](https://github.com/Azure/azure-dev/assets/71361488/64ef1303-cb24-4e30-a2a2-642f93071b65)

**EXPECTED**
![image](https://github.com/Azure/azure-dev/assets/71361488/0ca9b517-c7a0-4046-b0bd-bfbd03a025f8)

**Comment by rajeshkamal5050** [comment]
Doesn't seem to be related to Azd. Stack trace points to a failure during Aspire's manifest generation.

> Dashboard is disabled for the 'manifest' publisher, so skipping construction and hosting - seems like an info message. Not sure if any implications. 

Has anything changed on Aspire during manifest generation which Azd should account for?

cc @davidfowl @mitchdenny @ellismg

**Comment by davidfowl** [comment]
This is the latest nightly builds, not anything we shipped. We can close this one. Fixed here https://github.com/dotnet/aspire/commit/3158bb1e893f9180babe2302468a29a83fca6582

**Comment by v-cazhang** [comment]
Verified on Aspire.ProjectTemplates.8.0.0-preview.3.24055.2 + azd 1.5.1, this issue has been fixed.
