### ISSUE TITLE
Add support for azure.cosmos.database.v0 resource type

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-dev#3181]
[This PR in the Aspire repo](https://github.com/dotnet/aspire/pull/1583) is adding a new resource type for Aspire called `azure.cosmosdb.database.v0`.

We need this for Cosmos because the access token that the client code gets in an Aspire application is not scoped for database creation. You need to get a service management token to do that and use the `Azure.ResourceManager` APIs to create the database. For other resource types such as SQL Server and Postgres we are going to be creating the database instances as well so this just aligns the capabilities.

**Comment by mitchdenny** [comment]
@vhvb1989 we just merged database resource types in the Aspire manifest. It would be great if we can get it in azd now so we can try and get a seamless end to end.

**Comment by rajeshkamal5050** [comment]
Addressed part of #3213
