### ISSUE TITLE
Doc Updates - Feb Release

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#3187]
**_Planned release date Feb/13_**

**_Doc/Blogpost updates,_**

_Blogpost_
- Helm, Kustomize, RBAC support @wbreza 
   https://github.com/Azure/azure-dev/pull/3196
   https://github.com/Azure/azure-dev/pull/3211
- Aspire enhancements i.e., Storage Tables, Queues, Dockerfile, Dapr, Cosmosdb, Azure SQL @vhvb1989 @hemarina @weikanglim 
- VS Publish/Deploy(Aspire projects) to ACA using Azd @ellismg
   https://github.com/Azure/azure-dev/issues/2763
- Customizable azd up workflow @wbreza
   https://github.com/Azure/azure-dev/pull/3173
- azd extension in VS Code leverages Azure Tools extension pack credentials/token. Alpha feature @ellismg @bwateratmsft
   https://github.com/Azure/azure-dev/issues/1741
- Sovereign cloud support @danieljurek 

_Docs_
- "Does not have secrets get permission on key vault" after azd in GHA. Updates to troubleshooting guide @weikanglim 
   https://github.com/Azure/azure-dev/issues/2742
- Update docs on dev containers to mention feature @hemarina 
   https://github.com/Azure/azure-dev/issues/2892

cc @ellismg @spboyer

**Comment by gkulin** [comment]
@rajeshkamal5050 I'll look through the issues & PRs to see if there's anything needed here but is there anything you are aware of that definitely requires doc updates?

**Comment by gkulin** [comment]
closed via https://github.com/Azure/azure-sdk-blog/pull/467
