### ISSUE TITLE
Add support to AZD for `secrets.store.v0` and `secrets.secret.v0` resources

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-dev#3189]
We need these in for preview 3 of Aspire as they unlock a lot of external dependency scenarios. Here is the PR where this feature was merged in Aspire and the PR description includes lots of examples:

https://github.com/dotnet/aspire/pull/1487

**Comment by ellismg** [comment]
@mitchdenny I forget where we are with the whole secrets store, are we still trying to do something here for Preview 3 or are we pushing this out to Preview 4?  I can't recall if we walk away from our design meeting yesterday feeling good about this yet or not...

**Comment by mitchdenny** [comment]
Pushing to preview 4. Well rip out secrets as it exists today. I'd recommend keeping the input prompting mechanism we'll be reusing that.
