### ISSUE TITLE
ENOENT

### ISSUE THREAD

**Issue by ApplogistTeam** [Azure/azure-dev#3198]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-dev.views.workspace.environment.resolve
Error type: ENOENT
Error Message: spawn /bin/sh ENOENT

Version: 0.8.0
OS: darwin
OS Release: 23.2.0
Product: Visual Studio Code
Product Version: 1.85.1
Language: en

**Comment by rajeshkamal5050** [comment]
@ApplogistTeam could you add more details?
