### ISSUE TITLE
Failed to deploy api at the first time running `azd up` on US Gov Cloud

### ISSUE THREAD

**Issue by dotnet-7** [Azure/azure-dev#3207]
**Describe the issue:**
Test `todo-csharp-sql`/`todo-csharp-cosmos-sql` templates on US Gov Cloud. Run `azd up`. There is no error in command line , but api deployment failed as follow：

![image](https://github.com/Azure/azure-dev/assets/57525824/7136e540-dca3-4f18-92aa-2dd5d77080f5)

![image](https://github.com/Azure/azure-dev/assets/57525824/c27d975d-3b36-4f0f-aaae-7092b53cc141)
> Central Directory corrupt.

However, rerun `azd up` or `azd deploy`, the log will display **success** and the api can be deployed correctly.

**Repro Steps:**

1. Login in with command: `azd auth login`.
2. Execute command: `azd init -t todo-csharp-sql --branch pr/2897`.
3. Run `azd up`.

**Environment:**

- Cloud: US Gov.
- Template: todo-csharp-sql, todo-csharp-cosmos-sql.
- Azd version : 1.6.0-beta.1-pr.3419072 (commit 9a2e1c913995ed0f7b885f562794165079fa878f)

**Expected behavior:**
Run `azd up` can deploy api service successfully.

@danieljurek  for notification.

**Comment by dotnet-7** [comment]
@danieljurek The following environment also have the same issue on China Cloud:

- azd version: 1.6.0-beta.1-pr.3436205 (commit 79ee6dfcae682672d0808d2590b93d298fcba844)
- Template: `todo-csharp-cosmos-sql`
- Branch: [pr2897](https://github.com/Azure/azure-dev/pull/2897).
- Cloud: China.

**Comment by rajeshkamal5050** [comment]
https://github.com/Azure/azure-dev/pull/3481
