### ISSUE TITLE
Failed to deploy apim resource through `azd up` command on US Gov Cloud

### ISSUE THREAD

**Issue by dotnet-7** [Azure/azure-dev#3208]
**Describe the issue:**
Test `todo-java-mongo`/`todo-python-mongo` templates on US Gov Cloud. Run `azd up`, get error as follow：

![image](https://github.com/Azure/azure-dev/assets/57525824/39ef7d26-4277-43b0-8a97-958663079248)

**Repro Steps:**

1. Login in with command: `azd auth login`.
2. Execute command: `azd init -t todo-java-mongo --branch pr/2897`.
3. Run `azd env set USE_APIM true`.
4. Run `azd up`.

**Environment:**

- Cloud: US Gov.
- Template: todo-python-mongo,todo-java-mongo.
- Azd version : 1.6.0-beta.1-pr.3419072 (commit 9a2e1c913995ed0f7b885f562794165079fa878f)

**Expected behavior:**
Run `azd up` can pass.

@danieljurek  for notification.

**Comment by danieljurek** [comment]
Support request sent.

**Comment by danieljurek** [comment]
Deployment does succeed if deploying to a `Developer` SKU instead of default `Consumption` SKU

**Comment by danieljurek** [comment]
API Management's `Consumption` SKU is not supported in US Government or China Cloud -- https://learn.microsoft.com/en-us/azure/api-management/api-management-features

**Comment by v-jiaodi** [comment]
> Deployment does succeed if deploying to a `Developer` SKU instead of default `Consumption` SKU

@danieljurek Retest according to your comment, it works.

**Comment by danieljurek** [comment]
Changes pushed up to the samples in the `pr/2897` branch

```
azd init -t todo-java-mongo --branch pr/2897
azd env set USE_APIM true
azd env set APIM_SKU Developer
azd up 
```

**Comment by rajeshkamal5050** [comment]
https://github.com/Azure/azure-dev/pull/3481
