### ISSUE TITLE
Aspire: Support kafka.server.v0

### ISSUE THREAD

**Issue by eerhardt** [Azure/azure-dev#3219]
https://github.com/dotnet/aspire/pull/951 added support for Kafka. We should support this in `azd`.

https://learn.microsoft.com/en-us/azure/container-apps/tutorial-dev-services-kafka?tabs=bash

**Comment by rajeshkamal5050** [comment]
We will not add hand-crafted, template-based Bicep deployment support in azd. Instead, we will be moving towards using bicep resource type and CDK effort.
- https://github.com/dotnet/aspire/issues/1941
- https://github.com/Azure/azure-dev/issues/3279
