### ISSUE TITLE
Aspire: Support mongodb.server.v0, mongodb.database.v0

### ISSUE THREAD

**Issue by eerhardt** [Azure/azure-dev#3220]
https://github.com/dotnet/aspire/pull/986 added support for MongoDB in .NET Aspire. We should support these resources in `azd`.

**Comment by rajeshkamal5050** [comment]
We will not add hand-crafted, template-based Bicep deployment support in azd. Instead, we will be moving towards using bicep resource type and CDK effort.
- https://github.com/dotnet/aspire/issues/1941
- https://github.com/Azure/azure-dev/issues/3279
