### ISSUE TITLE
[Issue] azd provision requires elevated permissions in pipeline context

### ISSUE THREAD

**Issue by jsacapdev** [Azure/azure-dev#3224]
**Output from `azd version`**
azd version 1.5.1 (commit 3856d1e98281683b8d112e222c0a7c7b3e148e96)

**Describe the bug**

When attempting to configure a deployment pipeline using azd in GitHub, a service principal was created manually and provided the following permissions at a resource group level:

- User Access Administrator
- Contributor

The deployment reported the following error back:

```
ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: starting deployment to subscription: PUT https://management.azure.com/subscriptions/***/providers/Microsoft.Resources/deployments/dev-1705593296
--------------------------------------------------------------------------------
RESPONSE 403: 403 Forbidden
ERROR CODE: AuthorizationFailed
--------------------------------------------------------------------------------
{
  "error": {
    "code": "AuthorizationFailed",
    "message": "The client '???' with object id '???' does not have authorization to perform action 'Microsoft.Resources/deployments/write' over scope '/subscriptions/***/providers/Microsoft.Resources/deployments/dev-1705593296' or the scope is invalid. If access was recently granted, please refresh your credentials."
  }
}
```

To investigate a sample was created that does successfully deploy. The sample used the command `azd pipeline config -e dev --provider github`. That showed that the service principal that was created has contributor and user access administrator rights at a subscription level.

Does this mean that permissions allocated at a resource group for a service principal level are not sufficient? Setting permissions at a subscription level is a limitation for most organisations who will not be comfortable setting subscription level permissions as it increases the attack surface for a targeted resource deployment.

**Comment by weikanglim** [comment]
@jsacapdev Have you tried [resource group deployments](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/resource-group-scoped-deployments) -- it will require some work updating bicep to target an RG but should be straightforward (docs explain this)? By default, azd uses subscription-level deployments and requires subscription-level scope, which enables multi-RG scenarios with ease. We understand that for enterprise environments, this is not ideal. RG-level deployments are our current solution.

**Comment by jsacapdev** [comment]
@weikanglim the guidence above met the requirement to deploy to a resource group only. Many thanks for your support.
