### ISSUE TITLE
Failed to push to the output registry: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing

### ISSUE THREAD

**Issue by BartNetJS** [Azure/azure-dev#3225]
**Output from `azd version`**
Run `azd version` and copy and paste the output here: azd version 1.5.1 (commit 3856d1e98281683b8d112e222c0a7c7b3e148e96)

**Describe the bug**
On azd up i got above timeout on pushing the image ta acr

**To Reproduce**
Create a default aspire app
run:
azd init
azd auth login
azd up

the same happens when running directly azd deploy

**Expected behavior**
to image to be uploaded to acr

**Environment**
Information on your environment:
    * Visual Studio 17.9.0 Preview 3.0

Here a detailed stack trace:

ERROR: failed deploying service 'apiservice': failing invoking action 'deploy', publishing container: dotnet publish on project 'C:\Users\BARTVA~1\sources\TEST.Aspire\TEST.DataEyesWH\TEST.DataEyesWH.ApiService\TEST.DataEyesWH.ApiService.csproj' failed: exit code: 1, stdout: MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  Restored C:\Users\BartVanderAuweraert\sources\TEST.Aspire\TEST.DataEyesWH\TEST.DataEyesWH.ServiceDefaults\TEST.DataEyesWH.ServiceDefaults.csproj (in 314 ms).
  Restored C:\Users\BartVanderAuweraert\sources\TEST.Aspire\TEST.DataEyesWH\TEST.DataEyesWH.ApiService\TEST.DataEyesWH.ApiService.csproj (in 314 ms).
  TEST.DataEyesWH.ServiceDefaults -> C:\Users\BartVanderAuweraert\sources\TEST.Aspire\TEST.DataEyesWH\TEST.DataEyesWH.ServiceDefaults\bin\Debug\net8.0\TEST.DataEyesWH.ServiceDefaults.dll
  TEST.DataEyesWH.ApiService -> C:\Users\BartVanderAuweraert\sources\TEST.Aspire\TEST.DataEyesWH\TEST.DataEyesWH.ApiService\bin\Debug\net8.0\linux-x64\TEST.DataEyesWH.ApiService.dll
  TEST.DataEyesWH.ApiService -> C:\Users\BartVanderAuweraert\sources\TEST.Aspire\TEST.DataEyesWH\TEST.DataEyesWH.ApiService\bin\Debug\net8.0\linux-x64\publish\
C:\Program Files\dotnet\sdk\8.0.101\Containers\build\Microsoft.NET.Build.Containers.targets(73,5): warning CONTAINER003: The property 'ContainerImageName' was set but is obsolete - please use 'ContainerRepository' instead. [C:\Users\BartVanderAuweraert\sources\TEST.Aspire\TEST.DataEyesWH\TEST.DataEyesWH.ApiService\TEST.DataEyesWH.ApiService.csproj]
  Building image 'azd-deploy-apiservice-1706114439' with tags 'latest' on top of base image 'mcr.microsoft.com/dotnet/aspnet:8.0'.
  Uploading layer 'sha256:2f44b7a888fa005d07c031d3cfad2a1c0344207def2ab9dbb97712425ff812c1' to 'acr2ozlnkdmkzq4m.azurecr.io'.
  Uploading layer 'sha256:9615f6c2b3e3bc65daa95f5223cf017d1e8df1e084eae28bad25a2ca13b00fcb' to 'acr2ozlnkdmkzq4m.azurecr.io'.
  Uploading layer 'sha256:0c33680d721622a0b1f6e975cb815688641a80a99ad6f1585b8390ef1d6691be' to 'acr2ozlnkdmkzq4m.azurecr.io'.
  Uploading layer 'sha256:5f37777da376fa2b289508612cd07adf2f850246df62cfd525ace87d7efb69b5' to 'acr2ozlnkdmkzq4m.azurecr.io'.
  Uploading layer 'sha256:8d53130e324d8a024561a286efaea33d947360d2beeeae59e33b469bc2df191a' to 'acr2ozlnkdmkzq4m.azurecr.io'.
  Uploading layer 'sha256:b7611c826debba743ac3bd762e17f12658d285d9495fa7c9457daa71e74cef19' to 'acr2ozlnkdmkzq4m.azurecr.io'.
  Uploading layer 'sha256:1cecf4652df252c18cbdd71af077047f8c1ceeb5bddeba2da03a814d5eb484ee' to 'acr2ozlnkdmkzq4m.azurecr.io'.
  Finished uploading layer 'sha256:0c33680d721622a0b1f6e975cb815688641a80a99ad6f1585b8390ef1d6691be' to 'acr2ozlnkdmkzq4m.azurecr.io'.
  Finished uploading layer 'sha256:8d53130e324d8a024561a286efaea33d947360d2beeeae59e33b469bc2df191a' to 'acr2ozlnkdmkzq4m.azurecr.io'.
  Finished uploading layer 'sha256:1cecf4652df252c18cbdd71af077047f8c1ceeb5bddeba2da03a814d5eb484ee' to 'acr2ozlnkdmkzq4m.azurecr.io'.
C:\Program Files\dotnet\sdk\8.0.101\Containers\build\Microsoft.NET.Build.Containers.targets(202,5): error CONTAINER1013: Failed to push to the output registry: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing. [C:\Users\BartVanderAuweraert\sources\TEST.Aspire\TEST.DataEyesWH\TEST.DataEyesWH.ApiService\TEST.DataEyesWH.ApiService.csproj]
, stderr:

**Comment by vhvb1989** [comment]
related: https://github.com/Azure/azure-dev/discussions/3212

**Comment by vhvb1989** [comment]
For the logs, I assume this is an Aspire project?

**Comment by BartNetJS** [comment]
Yes indeed, it is an aspire project

**Comment by vhvb1989** [comment]
Aspire team is asking for a fix here: https://github.com/dotnet/sdk-container-builds/issues/543

suggested workaround: https://github.com/Azure/azure-dev/discussions/3212#discussion-6097445

**Comment by ellismg** [comment]
> In the interim as a workaround I'd suggest pushing to a local docker daemon and then using docker push to have Docker push the image to your destination registry.

Sadly, this workaround is hard to do with our Aspire support today because `azd` is the one calling `dotnet publish`.

I'm hopeful that the .NET Team can fix this before Aspire GA - If they can't we'll need to make changes in `azd` to support this workaround - and that will also mean we require the docker daemon again even for Aspire apps, which would be sort of unfortunate (or we have `azd` push the OCI image to the registry, but I don't think I want to end up there unless we really have to).

**Comment by indcoder** [comment]
Same issue for me too.  Till the fix comes in, we should not list AZD as a deployment option for Aspire projects. Or have a block quote mentioning this at the top regarding web projects. It will save folks from wasting their time unnecessarily.
![image](https://github.com/Azure/azure-dev/assets/2099300/d27ffc7e-9f65-42f9-8869-0d9ef5d6248c)

**Comment by efonsecab** [comment]
I am also getting this same error when trying to deploy a .NET Aspire solution.

**Comment by rajeshkamal5050** [comment]
Depends on upstream fixes https://github.com/Azure/azure-dev/issues/3225#issuecomment-1910566180 because https://github.com/Azure/azure-dev/issues/3225#issuecomment-1911652306

**Comment by tarisaig-motion84** [comment]
Has there been any movement on this please? azd up is timing out.

**Comment by vhvb1989** [comment]
@baronfel , wondering if you know anything about this (https://github.com/dotnet/sdk-container-builds/issues/543)

**Comment by baronfel** [comment]
This should have shipped in more recent SDKs at this point - @tarisaig-motion84 what version of the .NET SDK are you using?

**Comment by tarisaig-motion84** [comment]
Thanks @baronfel . I was using .NET 8.0 SDK. I've now upgraded to 8.0.3 and azd up no longer times out. Thank you.
