### ISSUE TITLE
Sql templates with deployment scripts failed to execute `azd up` on China Cloud

### ISSUE THREAD

**Issue by dotnet-7** [Azure/azure-dev#3227]
**Describe the issue:**
Test `todo-csharp-sql`/`todo-csharp-sql-swa-func` templates on China Cloud. Run `azd up`, get error as follow：
![image](https://github.com/Azure/azure-dev/assets/57525824/33a2e996-4125-4d35-b5fb-39f3365442b2)

**Repro Steps:**

1. Run `azd config set cloud.name AzureChinaCloud`
2. Login in with command: `azd auth login`.
3. Execute command: `azd init -t todo-csharp-sql --branch pr/2897`.
4. Run `azd up`.

**Environment:**

- Cloud: China.
- Template: `todo-csharp-sql`, `todo-csharp-sql-swa-func`.
- Azd version : 1.6.0-beta.1-pr.3436205 (commit 79ee6dfcae682672d0808d2590b93d298fcba844)

**Expected behavior:**
Run `azd up` can pass.

@danieljurek for notification.

**Comment by danieljurek** [comment]
This appears to be a quota-related issue, as well.

**Comment by v-xuto** [comment]
Same issue about template `todo-csharp-sql` in **china** cloud.

**Comment by rajeshkamal5050** [comment]
https://github.com/Azure/azure-dev/pull/3481

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 Retest with https://github.com/Azure/azure-dev/pull/3481, this issue still exsits.
