### ISSUE TITLE
Aca templates failed to execute `azd up` on China Cloud

### ISSUE THREAD

**Issue by dotnet-7** [Azure/azure-dev#3229]
**Describe the issue:**
Test `todo-java-mongo-aca`, `todo-python-mongo-aca`, `todo-nodejs-mongo-aca` templates on China Cloud. Run `azd up`, get error as follow：
![image](https://github.com/Azure/azure-dev/assets/57525824/403bc916-2ed8-4910-86fc-44e5ddd4769e)

**Repro Steps:**

1. Run `azd config set cloud.name AzureChinaCloud`
2. Login in with command: `azd auth login`.
3. Execute command: `azd init -t todo-java-mongo-aca --branch pr/2897`.
4. Run `azd up`.

**Environment:**

- Cloud: China.
- Template: `todo-java-mongo-aca`, `todo-python-mongo-aca`, `todo-nodejs-mongo-aca`.
- Azd version : 1.6.0-beta.1-pr.3436205 (commit 79ee6dfcae682672d0808d2590b93d298fcba844)

**Expected behavior:**
Run `azd up` can pass.

@danieljurek for notification.

**Comment by danieljurek** [comment]
Enusre we use China North 3

**Comment by v-jiaodi** [comment]
@danieljurek After adding `Owner` permissions, retest with region `China North 3`, get error as follow:

![image](https://github.com/Azure/azure-dev/assets/80496810/cc918c9b-51c9-4d3e-b8ea-c9ffa0254901)

**Comment by danieljurek** [comment]
I'm seeing a similar failure. The logs are unclear at this time. I'm checking with support.

**Comment by danieljurek** [comment]
Updating the template to use an environment-supplied container registry suffix worked: 

1. Run `azd config set cloud.name AzureChinaCloud`
2. Login in with command: `azd auth login`.
3. Execute command: `azd init -t todo-java-mongo-aca --branch pr/2897`.
4. **NEW STEP** Set environment variable `CONTAINER_REGISTRY_HOST_SUFFIX` to `azurecr.cn` (e.g. `$env:CONTAINER_REGISTRY_HOST_SUFFIX='azurecr.cn'`)
5. Run `azd up`.

This will need to be run with bits from https://github.com/Azure/azure-dev/pull/3452/files ... but not yet. The CI system is encountering issues.

**Comment by rajeshkamal5050** [comment]
https://github.com/Azure/azure-dev/pull/3481
