### ISSUE TITLE
Add support to reference AKS cluster in `azure.yaml`

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#3237]
Today the AKS cluster name must always be set in an environment variable `AZURE_AKS_CLUSTER_NAME`.  This should also be settable via the `resourceName` property of the service configuration in `azure.yaml`.

This will be common in scenarios where AKS clusters may not be provisioned by the current azd project but be provided by the developers organization.

**Comment by ellismg** [comment]
Let's also support SERVICE_<SERVICE_NAME>_AKS_CLUSTER_NAME as well as a way to override AZURE_AKS_CLUSTER_NAME on a service by service basis.

**Comment by wbreza** [comment]
> Let's also support SERVICE_<SERVICE_NAME>_AKS_CLUSTER_NAME as well as a way to override AZURE_AKS_CLUSTER_NAME on a service by service basis.

by supporting `resourceName` which is an `ExpndableString` we basically get this and they can reference whatever env var they would like to use.
