### ISSUE TITLE
Support aspire apps with multiple exposed ports.

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#3267]
ACA now has preview support for a container app exposing multiple ports (with some caveats): https://learn.microsoft.com/en-us/azure/container-apps/ingress-overview#additional-tcp-ports.

We need to leverage this feature to support containers with manifests like the following:

```
    "EventBus": {
      "type": "container.v0",
      "image": "rabbitmq:3-management",
      "env": {
        "RABBITMQ_DEFAULT_USER": "guest",
        "RABBITMQ_DEFAULT_PASS": "{EventBus.inputs.password}"
      },
      "bindings": {
        "tcp": {
          "scheme": "tcp",
          "protocol": "tcp",
          "transport": "tcp",
          "containerPort": 5672
        },
        "management": {
          "scheme": "http",
          "protocol": "tcp",
          "transport": "http",
          "containerPort": 15672
        }
      },
      "connectionString": "amqp://guest:{EventBus.inputs.password}@{EventBus.bindings.tcp.host}:{EventBus.bindings.tcp.port}",
      "inputs": {
        "password": {
          "type": "string",
          "secret": true,
          "default": {
            "generate": {
              "minLength": 10
            }
          }
        }
      }
    },
```

This should expose both 5672 and 15672.

**Comment by ellismg** [comment]
One thing that wasn't clear to me was if it was possible in the above to only expose these two ports, or if ACA was going to force us to have a listener on 443/80 that had to go somewhere (in this case, I guess that would be the management binding, since its transport is http?)

**Comment by weikanglim** [comment]
> or if ACA was going to force us to have a listener on 443/80 that had to go somewhere

Meaning like a load balancer inside the container? 

My read is that internal multiple ports will work as expected since no fancy CORS/session affinity is needed. External multiple ports will be a lot trickier due to caveats such as:

- Any externally exposed additional TCP ports must be unique across the entire Container Apps environment. This includes all external additional TCP ports, external main TCP ports, and 80/443 ports used by built-in HTTP ingress.
-  Only the main ingress port supports built-in HTTP features such as CORS and session affinity. When running HTTP on top of the additional TCP ports, these built-in features aren't supported.

**Comment by rajeshkamal5050** [comment]
Saw an update that this ACA feature is GA'ed - https://azure.microsoft.com/en-us/updates/generally-available-azure-container-apps-supports-additional-tcp-ports/

**Comment by vhvb1989** [comment]
Added a comment here about what azd requires from the Aspire Manifest to support this feature: https://github.com/Azure/azure-dev/issues/3123#issuecomment-1935297266

@mitchdenny , moving the conversation here.

**Comment by rajeshkamal5050** [comment]
- Depends on Aspire issue [Add ability to express exposed services in app host #2099](https://github.com/dotnet/aspire/issues/2099)
- Not a must-fix for Aspire Preview 4. Moving it to next milestone.

@ellismg @vhvb1989 @davidfowl @mitchdenny

**Comment by davidfowl** [comment]
Agreed!

**Comment by davidfowl** [comment]
@rajeshkamal5050 can we put this in P5 as well?

**Comment by rajeshkamal5050** [comment]
Yes, David. Depends on these,
- Core Aspire modeling support issues https://github.com/dotnet/aspire/issues/2658 and https://github.com/dotnet/aspire/issues/2099
- Also, remember some ACA preview features as well.

@vhvb1989 lets see if we can get this in for Preview 5 i.e., Apr 09 azd release

**Comment by davidfowl** [comment]
> Core Aspire modeling support issues https://github.com/dotnet/aspire/issues/2658 

We're punting this one

> https://github.com/dotnet/aspire/issues/2099

But we're doing this one.

I will talk to @vhvb1989 and sure up the rules for how we map to ingress rules

**Comment by davidfowl** [comment]
After some discussions, I wrote a prototype and asked copilot to explain the code:

https://github.com/dotnet/aspire/blob/14a264779d767cece5390367508ecc5206567c59/src/Aspire.Hosting.Azure/Provisioning/Provisioners/AzureContainerAppsInfastructure.cs#L345-L457

The explanation 😄 

The WriteIngress method takes in a resource and a collection of endpoint annotations as parameters. It generates an ingress configuration string based on the provided endpoints. The method performs the following steps:
1.	It checks if there are any endpoints. If there are none, it returns an empty string.
2.	It validates that the endpoints only support the "http", "https", or "tcp" URI schemes. If any other scheme is found, it throws a NotSupportedException.
3.	It groups the endpoints by container port, creating logical bindings or destinations.
4.	It performs several failure case checks:
•	It throws a NotSupportedException if there are multiple external endpoints.
•	It throws a NotSupportedException if there are external non-HTTP(s) endpoints.
5.	It filters and retrieves the HTTP-only endpoint groups.
6.	If there is only one HTTP-only endpoint group, it assigns it as the HTTP ingress.
7.	If there is no HTTP ingress, it tries to find an external HTTP-only endpoint. If there is exactly one, it assigns it as the HTTP ingress. If there are multiple HTTP-only endpoints or no HTTP-only endpoints, it throws a NotSupportedException.
8.	If an HTTP ingress is found, it removes it from the list of endpoint groups.
9.	It checks if the number of remaining endpoint groups exceeds 5. If it does, it throws a NotSupportedException.
10.	It generates the ingress configuration string by mapping the remaining endpoints:
•	If there is an HTTP ingress, it includes the external flag, target port, and transport information.
•	If there is no HTTP ingress, it uses the first remaining endpoint group's port as the target port and sets the transport to "tcp".
•	It also includes additional port mappings for any remaining endpoint groups.

**Comment by rajeshkamal5050** [comment]
Enabling multiple endpoints/ports is not working on all scenarios. Some more additional fixes are needed. Let's target for Preview.6(Apr/23).

@davidfowl @ellismg @vhvb1989 please add more details on the gaps.

**Comment by rajeshkamal5050** [comment]
https://github.com/Azure/azure-dev/pull/3735
