### ISSUE TITLE
[Issue] Quickstart on template reops READMEs is confusing.  should just be azd init (without template name)

### ISSUE THREAD

**Issue by colbylwilliams** [Azure/azure-dev#327]
The readme [Quickstart](https://github.com/Azure-Samples/todo-python-mongo#quickstart) instructions are a little confusing when starting from a template repo vs starting directly with az dev.  

For example, if I find one of the todo templates in the Azure-Samples org, create my own repo from the template, then read the instructions on how to start.  I end up trying to run `azd init -t todo-template-name` which tries to overwrite all of the files in my repo.  Whereas I should just run `azd init` and be on my merry way.

I get that these are being copied from this repo to the Azure-Sample repos, but that seems like an implementation detail that's hurting the UX.  Seems like a the Azure-Sample template repos are likely starting/discoverability points vs this repo.  Its also likely that organizations will use the todo templates as starting points for their own templates, which is another case where it'd be nice if the readme instructions were already accurate (i.e. just `azd init`).

I also understand that it says to go to an empty folder, but it seems more likely to me that they'd want to start in a github repo anyway, and adding the folder to a repo after the fact adds additional confusion.

**Comment by rajeshkamal5050** [comment]
We have made lots of UX improvements and doc updates simplifying the flow. Not sure if this is applicable anymore. Please try with our latest bits and reopen if need be.
