### ISSUE TITLE
Enable simplified-init in VSCode Azd Extension

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#3280]
Simplified-init is not enabled as part of VSCode Azd Extension. We need to enable simplified-init for the Aspire integration.

@davidfowl @ellismg @spboyer @bradygaster

**Comment by weikanglim** [comment]
Not knowing what this entails yet, simplified init presents an interactive wizard in the CLI. Are we thinking to leverage any of #2763 or continue the current VS Code integration pattern?

**Comment by weikanglim** [comment]
@bwateratmsft Suppose we were able to get past the "current directory" prompt, what would VSCode show for "confirming the detected services"?

![image](https://github.com/Azure/azure-dev/assets/2322434/efb4038c-2e0d-458f-bc07-f1b459769c8b)

**Comment by rajeshkamal5050** [comment]
> Also need provision/deploy to change UX flow to accept 'select services to expose'

With [Add ability to express exposed services in app host #2099](https://github.com/dotnet/aspire/issues/2099) being handled in the app-model/manifest itself for Preview 5. Hoping that we don't have to special handle it in Azd, VSCode and also VS.

@davidfowl @ellismg @bwateratmsft @brennanconroy

**Comment by rajeshkamal5050** [comment]
Re-opening this one from VSCode perspective.

**Comment by bwateratmsft** [comment]
What's left to do is to check in and ship some of the changes I have that make `init` more programmatically accessible, as well as add an API for `getAzdLoginStatus()`.
