### ISSUE TITLE
Implement `DeleteEnvironmentAsync` RPC for Aspire Server

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#3285]
We don't implement this today because even the `azd` CLI doesn't have a `azd env rm` command.  That work is tracked by #937.  We need to decide if `DeleteEnvironmentAsync` is the same as `azd env rm` (whatever that ends up meaning) or if this does something different.

For example, you could image that `azd env rm` is a lightweight operation that is just about deleting stuff in the `.azure` folder while this RPC may also want to do something like an `azd down` first.

We need to discuss with the VS team what semantics make sense here for their users and how they plan to surface this in their UI.

@vhvb1989 raised some other good points to think about in the PR: https://github.com/Azure/azure-dev/pull/3190#discussion_r1476595251

> There's many questions we don't have an answer for when it comes to deleting environment.... like
> 
> - Should we call azd down or just leak resources?
> - Should we allow restore and just mark environment as deleted? (best practice)
> - Can we delete the current default environment? should we jump to the next available env as new default? or ask the user?
> - What if I delete env foo and then create env foo again? (what happen on Azure?)
>
> .. etc etc..

**Comment by rajeshkamal5050** [comment]
@ellismg @weikanglim Not in scope for `VS 17.10 Preview 2`. Moving it to March iteration. Feel free to pull it in, if need be.

**Comment by rajeshkamal5050** [comment]
@abpiskunov @anvillan is this required for `VS 17.10 Preview 3`?

**Comment by abpiskunov** [comment]
I believe yes, it will be already 3rd preview and we need to wrap up all known feature gaps and leave only bug fixes for final previews before build.

**Comment by abpiskunov** [comment]
I believe yes, it will be already 3rd preview and we need to wrap up all known feature gaps and leave only bug fixes for final previews before build.

**Comment by abpiskunov** [comment]
This one should be pretty easy - another trigger that invalidates the cache on azd side.

**Comment by weikanglim** [comment]
Related to #937
