### ISSUE TITLE
Allow specifying container image name in `azure.yaml`

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#329]
In https://github.com/Azure/azure-dev/pull/1009#discussion_r876369787 we were discussing what the right default here is (what we have seems sufficient for now) and also what overriding this would look like.

**Comment by rajeshkamal5050** [comment]
Seems like this has been addressed - https://github.com/Azure/azure-dev/blame/main/schemas/v1.0/azure.yaml.json

```
"image": {
"type": "string",
"title": "Optional. The name that will be applied to the built container image.",
"description": "If omitted, will default to the '{appName}/{serviceName}-{environmentName}'. Supports environment variable substitution."
}
```
