### ISSUE TITLE
Ubuntu agents in Azure DevOps fail to run hooks from .sh script file even with chmod

### ISSUE THREAD

**Issue by TWolversonReply** [Azure/azure-dev#3293]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.5.1 (commit 3856d1e98281683b8d112e222c0a7c7b3e148e96)

**Describe the bug**
/bin/sh: 1: ./hooks/RunDbMigrations.sh: Permission denied

ERROR: failed running post hooks: 'postprovision' hook failed with exit code: '126', Path: './hooks/RunDbMigrations.sh'. : exit code: 126, stdout: , stderr: /bin/sh: 1: ./hooks/RunDbMigrations.sh: Permission denied

**To Reproduce**
Write any hook as a .sh script file and include it with its relative path in azure.yaml, and run azd (command) from an Azure DevOps pipeline.
I have included chmod u+r+x '$(System.DefaultWorkingDirectory)\hooks\RunDbMigrations.sh' as the preceding command and this makes no difference. The same command runs fine on a Windows-2022 agent. Full step syntax:

- task: AzureCLI@2
  displayName: Azure CI Provision
  inputs:
    azureSubscription: $(AZURE_RESOURCE_MANAGER_CONNECTION)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      chmod u+r+x '$(System.DefaultWorkingDirectory)\hooks\RunDbMigrations.sh'
      chmod +x '$(System.DefaultWorkingDirectory)\migrations\efbundle.exe'
      azd provision --no-prompt --debug

(the hook runs the compiled result of EF core bundling to update a remote database, but removing it makes no difference)

**Expected behavior**
I expect that this is nothing specific to Azd and I'm just not understanding some aspect of the Linux permissions model as it pertains to pipelines, but I don't have anywhere else to ask. I expect the hook to just run, as it does locally on a Windows development environment.

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

**Comment by rajeshkamal5050** [comment]
@danieljurek can you triage this?

**Comment by danieljurek** [comment]
@TWolversonReply -- Is the `$(System.DefaultWorkingDirectory)\migrations\efbundle.exe` file a Windows-only executable? 

Is there a reason `AzureCLI@2` is being used to run this instead of `script`?

**Comment by danieljurek** [comment]
After some looking, using `azd config set auth.useAzCliAuth "true"`, `AzureCLI@2`, and a service connection simplifies authentication and `AzureCLI@2`'s script invocation isn't doing anything unexpected. It's fine to keep using it. 

If you're still seeing failures with hooks when there's a Linux binary in place, let me know and we can continue investigating. 

You mentioned that the build is done on Windows and provision is done on Linux. During the Windows build can you run the `dotnet ef migrations bundle` step with a `--runtime` parameter to produce a Linux binary? 

https://learn.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-migrations-bundle

Runtime identifiers: https://learn.microsoft.com/en-us/dotnet/core/rid-catalog

**Comment by danieljurek** [comment]
@TWolversonReply -- Were you able to resolve the issue?
