### ISSUE TITLE
Extra `dotnet publish` call for Aspire containerized projects

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#3300]
In logs for `azd deploy <service>` within an AppHost project, we see duplicated `dotnet publish` calls, essentially building the service twice

First call:

```
2024/02/06 15:08:16 command_runner.go:307: Run exec: 'dotnet publish C:\Users\weilim\source\repos\AspireTest\AspireTest\AspireTest.csproj -c Release --output d:\tmp\azd3305704657' , exit code: 0
```

Followed by
```
2024/02/06 15:08:36 command_runner.go:307: Run exec: 'dotnet publish C:\Users\weilim\source\repos\AspireTest\AspireTest\AspireTest.csproj -r linux-x64 -c Debug -p:PublishProfile=DefaultContainer -p:ContainerImageName=azd-deploy-aspiretest-1707260897 -p:ContainerRegistry=<redacted>' , exit code: 0
```

We should eliminate the first call

**Comment by rajeshkamal5050** [comment]
@weikanglim do you think we can get this fixed for upcoming release?

**Comment by weikanglim** [comment]
@rajeshkamal5050 Yes, there should be a simple one-liner patch for this to skip the extra publishing.

If I were to stack unwind a few frames, I do think the existence of the bug is an indicator of the complexity in `azd` splitting "framework service" and "service target" and requiring composition of the lifecycle.
