### ISSUE TITLE
[AspireDeployment] azd server API should be tracing back all possible information in case of errors or exceptions

### ISSUE THREAD

**Issue by abpiskunov** [Azure/azure-dev#3310]
Currently if azd crashes we can only see RemoteConnection close exception. It needs to be improved and API should catch exceptions and send them to VS. Each API should receive an observer parameter that we already have in DeployAsync and print that exception information (or explanation if that is some known case) so user could either do something different in UX or send us that output for diagnostics.

**Comment by weikanglim** [comment]
Let's discuss this on #3312!
