### ISSUE TITLE
[AspireDeployment] azd vs-server can become unresponsive (or crash) after JSON RPC error

### ISSUE THREAD

**Issue by anvillan** [Azure/azure-dev#3312]
The azd vs-server can become unresponsive or crash after a JSON RPC failed invocation.

We've noticed that, while we were working out our way to support Aspire Deployment, sometimes doing a JSON RPC invocation that failed, provoked the azd.exe process to either crash down or become totally unresponsive. 

From VS IDE side, we just print out the JSON RPC error (stack trace), though this won't be enough/helpful for a final user.

azd vs- server should:

- Try to avoid a failed invocation disrupts the azd.exe process
- If a failure actually occurs, send back as much information as possible back to the vs-server client

NOTE: if signatures or return type/data is changed, VS IDE should be informed to adjust current API contact

**Comment by weikanglim** [comment]
The crashes we're seeing will likely be ironed out as we stabilize the server. In general, crashes are a result of unrecoverable panics (something really bad happened), and in these preliminary cases -- unrecoverable program defects that may not be in the normal execution flow.

The panic information will automatically be collected and presented in the `stderr` of the program exit. 

@anvillan @abpiskunov, is it possible that the thread that launches and monitors the vs-server, would write out this information to a user-visible place, or a place for debug collection if the process exits? This would help cover all cases, including corner cases such as problems with the server-client connection itself.

**Comment by abpiskunov** [comment]
There are 2 things here: one is to show all possible data for last resort diagnostics, b. if help user resolve it or work around. If its exception you never expected , sure what else can we do? However when there are scenarios that you could validate and some data missing or state is known to be invalid , we need to communicate that to user so we could know when we should show it right where they are in the UX, instead of silently printing stack traces in teh output (which could be closed or other pane is active in the output window).

**Comment by weikanglim** [comment]
@abpiskunov For general handled errors, they should come through as an error in RPC with an error message. From a test client project we wrote, it looks like:

Unhandled exception. StreamJsonRpc.RemoteInvocationException: *no app host projects found under /home/weilim/repos/main/cli/azd/internal/tracing/azure.yaml*
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject), similar to the one in #3316

**Comment by abpiskunov** [comment]
yes, this one has a nice message, which we could show in UX, however there are other ones like when host project cannot be built and has build errors - that message is huge and i am not sure if we can show it in UX directly, however we cannot leave user without any suggestion and empty page. The reason of this and another bug we opened related to this is to iterate over different errors known there and have better messages like this one above for all known cases (with inner exception maybe having whole output); or introduce formal "Result" object that might have "error message" field if it is for user to see in UX, while exception is still printed in the output.

**Comment by rajeshkamal5050** [comment]
@anvillan @abpiskunov seems lately vs-server has been stable. Can we close this one in favor of #3316 and any specific ones which comes up?

**Comment by anvillan** [comment]
@rajeshkamal5050  

It is OK for me. We can open new bug(s) if we see a specific failures.
