### ISSUE TITLE
[AspireDeployment] EnvironmentSevice.DeployAsync() ProgressMessage should correctly set MessageKind property

### ISSUE THREAD

**Issue by anvillan** [Azure/azure-dev#3313]
The `ProgressMessage` sent back from `EnvironmentService.DeployAsync()` should correctly set the `Kind(MessageKind)` property,

From VS IDE, the `Kind` property of the `ProgressMessage` is used to handle the message according to the value (`Logging (0)` or `Important (1)`). 

This is, if the message is `Important`, the information would be shown _prominently_, other than just print it out in the azd `Output` window.

**Comment by weikanglim** [comment]
@anvillan Thanks for the info. For my own understanding. do you have any suggestions on what messages could be considered *prominent* vs. info?

Related: what would the experience be? I tried on my local debug build but didn't spot a difference in behavior (it was outputting to terminal the same).

**Comment by anvillan** [comment]
@weikanglim 

The change is for VS IDE rather than CLI invocation: in VS, the new (work-in-progress) deployment experience, we start a new deployment, and we show 2 UI elements to let the user know what is going on: 
 1. A _State banner_ where we should _important_ messages of the Environment being acted upon. We only show _Deploying..._ for now.  **<--- This is where we want to show the _important_ messages**.

 2. An output panel: we capture `STDOUT` and `STDERR` from `azd.exe` process

![image](https://github.com/Azure/azure-dev/assets/51379759/13159294-da99-4c2c-8ad6-3d99e90672b7)

Our intention is to show a _subset_ (the important) messages in the _State_ banner (as well as in the Output panel).

What messages are important? For now, we could start with the initial message (and end message?) of an operation. I.e.

`...`
`2/13/2024 1:13:47 PM: Info Deploying services (azd deploy)`  **<--- THIS ONE**
`2/13/2024 1:13:47 PM: Info`
`2/13/2024 1:13:47 PM: Info Deploying service apiservice`  **<--- THIS ONE**
`2/13/2024 1:13:47 PM: Info Deploying service apiservice (Logging in to registry)`
`2/13/2024 1:13:48 PM: Info Deploying service apiservice (Pushing container image)`
`2/13/2024 1:13:58 PM: Info Deploying service apiservice (Updating container app)`
`2/13/2024 1:14:08 PM: Info Deploying service apiservice (Fetching endpoints for container app service)`
`2/13/2024 1:14:08 PM: Info   (✓) Done: Deploying service apiservice`
`2/13/2024 1:14:08 PM: Info   - Endpoint: https://apiservice.yellowwave-ec84e8a0.eastus.azurecontainerapps.io/`
`2/13/2024 1:14:08 PM: Info` 
`2/13/2024 1:14:08 PM: Info Deploying service webfrontend`  **<--- THIS ONE**
`2/13/2024 1:14:08 PM: Info Deploying service webfrontend (Logging in to registry)`
`2/13/2024 1:14:09 PM: Info Deploying service webfrontend (Pushing container image)`
`...`

We can certainly discuss about the criteria we want to use.

**Comment by bradygaster** [comment]
i'd error on the side of dumping more info rather than less; i'd prefer to know the details of each step of the process. From the block above, i'd argue i'd prefer to see all of those lines _except_ for these:

```
2/13/2024 1:13:47 PM: Info
2/13/2024 1:13:47 PM: Info
```

**Comment by anvillan** [comment]
@bradygaster Let's talk about how/what we want to show in VS IDE before `azd` implements further changes. 

My example above is only a small extract of all the logging done during a Deployment. For that, your initial suggestion may work. However, if you see the image in my previous post, there are lines with URLs, or with a key-value-pair (e.g. `Location: East US`) that if shown in the `State` banner as-it-is, by themselves, won't make much sense (at least to me).

My first suggestion was to show the _inital_ (and _finish_?) message of the multiple operations performed. 

Showing the links, etc., would be nice, too, but the message would only appear an instant in the banner -showing a link that disappears immediately won't be useful.

**Comment by anvillan** [comment]
@weikanglim 

We've discussed it, and we decided to set `ProgressMessage.Kind = MessageKind.Important` on the _initial_ messages of an operation (what I describe in my previous post framing this bug).

Please let us know any other question you may have and if it is required to make code modification(s) on our side.

CC: @bradygaster @abpiskunov

**Comment by rajeshkamal5050** [comment]
Tirage update: Not a `must-fix` for `VS 17.10 Preview 2`. Moving to next milestone.

@anvillan @weikanglim @abpiskunov @ellismg
