### ISSUE TITLE
[AspireDeployment] Add version to `vs-server`

### ISSUE THREAD

**Issue by anvillan** [Azure/azure-dev#3314]
VS IDE parses out the `azd version` output to determine the support for `vs-server` exists.

From the most recen version, VS IDE expects an output like this:
`{
 "azd": {
   "version": "1.5.0",
   "commit": "012ae734904e0c376ce5074605a6d0d3f05789ee"
 }
}`

`azd` should ensure this format is honored so VS IDE can rely on it to verify the `vs-server` support

**Comment by weikanglim** [comment]
@anvillan Hey! I'm assuming this is a question and not an ask, but yes `azd version --output json` format is stable. `version >= 1.6.0` is certainly possible.

A different alternative that I have slight preference is to perform `azd vs-server --help` which returns exit code of 0 when `vs-server` is supported.

**Comment by anvillan** [comment]
@weikanglim 

Good. We just want to make sure the JSON output for the `--version` is stable. If, as you said, this format will not change for next releases, and you have a way to _guarantee_ it (e.g., a test), this bug may be dismissed.

We could use `azd vs-server --help` to know whether `vs-server` is supported, though, for all purposes, it should be always better to know the exact version of the `vs-server` running -it can be useful for the user to know it, our telemetry, etc.

Then, before dismissing this bug, it occurred to me, **if `azd vs-server` output could include the `version`?**. 

When the `azd vs-server` runs (successfully), we receive a JSON output as:
`{
  "port": <port>
  "pid":  <pid>
}`

What if it returns:
`{
  "port": <port>,
  "pid": <pid>,
  "version": <version>
}`

This information, we use it to _configure_ the `server` instance running in VS IDE.

Let me know what you think.

**Comment by weikanglim** [comment]
@anvillan Including `version` seems completely reasonable. Let's keep this open and I'll make a change targeting this issue.

**Comment by weikanglim** [comment]
@anvillan I'm thinking it may be useful for diagnostics to include the commit number as well.

```json
{
  "port": "<port>",
  "pid":  "<pid>",
  "azd": {
    "version": "1.5.1",
    "commit": "3856d1e98281683b8d112e222c0a7c7b3e148e96"
  }
}
```

Does this sound reasonable on your end?

**Comment by anvillan** [comment]
Yes! Good thinking.

That way we _separate_ the `process` information from the `azd vs-server` information.
