### ISSUE TITLE
[Docs] out of date info about bicep in troubleshooting

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#3319]
See: https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/troubleshoot?tabs=Browser#azure-bicep-cli-requirement

azd is no longer using `az bicep` .  We must update this note to:

```
azd uses a specific version of bicep cli. If you want to use a different version, you can set the environment variable: `AZD_BICEP_TOOL_PATH` to point to the location of the version you need.
```

**Comment by gkulin** [comment]
https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/troubleshoot?tabs=Browser#azure-bicep-cli-requirement
