### ISSUE TITLE
Sort todo items by updated date not name in template apps

### ISSUE THREAD

**Issue by colbylwilliams** [Azure/azure-dev#332]
[Azure-Samples/todo-python-mongo](https://github.com/Azure-Samples/todo-python-mongo) (and maybe other samples) sort the todo items by name alphabetically.  It's an odd UX.  Seems like they should be sorted by update date/created date.

cc: @jongio @markweitzel

**Comment by rajeshkamal5050** [comment]
With the latest UX changes. This should have been addressed.
