### ISSUE TITLE
WSL - need to run gh auth login if not logged in

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#333]
Follow the steps here https://github.com/Azure/azure-dev/wiki/How-to-run-Azure-Developer-CLI-using-Windows-Subsystem-for-Linux-on-Windows-11.

azd version 0.0.1-beta.1545568 (commit 133bb1eb479f5f4f9b2406d3b684e0d7c91cc62c)

$ azd init -t todo-nodejs-mongo
- cursor spins endlessly. Nothing cloned.

**Comment by rajeshkamal5050** [comment]
With templates being public. Shouldn't be an issue anymore.
