### ISSUE TITLE
 azurerm_cosmosdb_mongo_collection list and Item not accepting unique Key on Azure-Samples / todo-nodejs-mongo-terraform

### ISSUE THREAD

**Issue by aminniktash2010** [Azure/azure-dev#3333]
**Describe the bug**
Code="BadRequest" Message="The field 'unique' is not valid for _id index specification
with module.cosmos.azurerm_cosmosdb_mongo_collection.list,
│   on modules/cosmos/cosmos.tf line 61, in resource "azurerm_cosmosdb_mongo_collection" "list":
│   61: resource "azurerm_cosmosdb_mongo_collection" "list" {

**To Reproduce**
1. Go to 'AZD up'

**Expected behavior**
Terraform apply getting failed on provisioning azurerm_cosmosdb_mongo_collection" "list and Item

I just update the code as below and all working now:

 resource "azurerm_cosmosdb_mongo_collection" "list" {
  name                = "TodoList"
  resource_group_name = azurerm_cosmosdb_account.db.resource_group_name
  account_name        = azurerm_cosmosdb_account.db.name
  database_name       = azurerm_cosmosdb_mongo_database.mongodb.name
  shard_key           = "_id"

  index {
    keys   = ["_id"]
    **unique = false**
  }
}

**Comment by rajeshkamal5050** [comment]
@aminniktash2010 should be fixed with the 1.6.0 release. Please re-open if you see it again.

https://github.com/Azure/azure-dev/pull/3338
