### ISSUE TITLE
azd command go to the interactive mode when something is missing or wrong

### ISSUE THREAD

**Issue by abpiskunov** [Azure/azure-dev#334]
This issue is about integration between azd and tools and avoiding interactive mode when VS or VSCode called azd:
- If --no-prompt is not passed azd always try to go to interactive mode when some parameter is missing or anything else is wrong. This blocks VS since we don't know that tool is in interactive mode and can not enter any parameters that way.
- If --no-prompt is specified, tool defaults to best known parameter like any location or any (first) subscription etc... When from the tool we usually do pass all parameters needed for a particular sub command and need azd just fail and print correct error without defaulting to some unexpected stuff. In case of corrupted state it should suggest something like "init environment or something else how to fix it"

Example: i had old .env file with LOCATION parameter, which was renamed to AZURE_LOCATION, when i ran azd env refresh with --no-prompt , it did fail and assumed some location which I never choose. I should have printed a message that location is missing run "azd init" etc.

**Comment by karolz-ms** [comment]
Need to verify if this still reproduces

**Comment by karolz-ms** [comment]
I believe this has been fixed. I tried deleting various pieces of environment data and could not get the CLI to show a prompt if `--no-prompt` flag has been set.
