### ISSUE TITLE
 [AspireDeployment] Environment.LastDeployment data incorrectly cached (only first data obtained returned)

### ISSUE THREAD

**Issue by anvillan** [Azure/azure-dev#3358]
The `Environment.LastDeployment` data, apparently, is incorrectly cached as consecutive invocations to `EnvironmentService.RefreshEnvironment()` returns the 1st set of data obtained.

I verified with 3 environments: 2 with successful deployments (then with non-null `LastDeployment` data) and 1 with no deployments attempts. Then, after obtaining the `LastDeployment` data of the first environment, performing a `RefreshEnvironment()` for the other 2 environments returns the `LastDeployment` data first obtained.

![image](https://github.com/Azure/azure-dev/assets/51379759/ba21c7b1-1d0e-4604-a419-b382c316beb3)
Fig 1: the `DeploymentId` is for `avc0213Environment` but the `Environment` retrieved (`Name`) is `avcDeployEnv`

**Comment by weikanglim** [comment]
I think this may be a similar story of #3297 . FYI @ellismg

**Comment by weikanglim** [comment]
Closing this as dup of #3297
