### ISSUE TITLE
The in-memory provisioning for .NET Aspire apps does not properly enable ingress settings on the web front end

### ISSUE THREAD

**Issue by alexwolfmsft** [Azure/azure-dev#3360]
**Output from `azd version`**
azd version 1.5.1

**Describe the bug**
The "Use code in the current directory" flow for .NET Aspire apps completes successfully, but does not enable the ingress setting for public access on the front end, resulting in 403 forbidden.  This requires the user to have to manually enable this setting in the Azure portal - many users may not understand how to do this and will assume the deployment did not work correctly.

**To Reproduce**
Run the azd pipeline config flow with a .NET Aspire app or another container app-based project

**Expected behavior**
The front end should be accessible by the user/public at the end of the deployment.

**Environment**
Information on your environment:
    * .NET
    * Terminal

**Comment by rajeshkamal5050** [comment]
@alexwolfmsft Din't you see a prompt to select the services which needs public exposure? something like below?

```
azd will generate the files necessary to host your app on Azure using Azure Container Apps.

? Select an option Confirm and continue initializing my app
By default, a service can only be reached from inside the Azure Container Apps environment it is running in. Selecting a service here will also allow it to be reached from the Internet.
? Select which services to expose to the Internet  [Use arrows to move, space to select, <right> to all, <left> to none, type to filter]
> [ ]  basketcache
  [ ]  basketservice
  [ ]  catalog
  [ ]  catalogdbmanager
  [ ]  catalogservice
  [ ]  frontend
```

**Comment by alexwolfmsft** [comment]
Yes, I selected the webfrontend and it added this configuration, which I think is correct:

<img width="281" alt="image" src="https://github.com/Azure/azure-dev/assets/93200798/886c993b-6c15-4933-aede-e3dbeeb22845">

**Comment by rajeshkamal5050** [comment]
Even in 1.5.1 it was working. Can you try with 1.6.0 and see if it reproduces? cc @vhvb1989

**Comment by rajeshkamal5050** [comment]
@alexwolfmsft can you try with the latest daily bits https://github.com/Azure/azure-dev/tree/main/cli/installer#download-from-daily-builds. We were not able to reproduce. Feel free to re-open.
