### ISSUE TITLE
Need a flag for `azd init` that will use the current directory instead of selecting a template

### ISSUE THREAD

**Issue by bwateratmsft** [Azure/azure-dev#3361]
The new `azd init` with the functionality to use the source in the current directory does not seem to have a flag that can be passed to cause it to take that behavior. I don't think `--no-prompt` will work as that would suppress other prompts that the CLI needs to make.

**Comment by bwateratmsft** [comment]
Blocks #3280

**Comment by rajeshkamal5050** [comment]
@weikanglim is this something we can be add for @bwateratmsft ?

**Comment by weikanglim** [comment]
`azd init .` would be nice if we allow `azd init <args>` where `args` == `[template | . ]` with perhaps argument modifiers in the future if something needs to be treated separately.

Without changing too much, I'm thinking to start with a flag. My uncreative mind stumbled on `--from-code`. But I'd love to hear any suggestions!

cc: @ellismg @kristenwomack
