### ISSUE TITLE
Add ability to specify an existing Resource Group and deploy to RG scope

### ISSUE THREAD

**Issue by colbylwilliams** [Azure/azure-dev#337]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/How-to-install-the-new-Azure-Dev-CLI)

**Output from `az dev version`**
Run `azd version` and copy and paste the output here: azd version 0.0.1-beta.1530657 (commit bc9c19d56f2c3829d7ace2fbed54604cf64bad52)

**Describe the bug**
Currently all templates are deployed at the subscription scope because they create a resource group on behalf of the user.  Is there a plan to be able to pass in an existing resource group and have the template's bicep templates deploy directly to that resource group?

Often in the enterprise (where `az dev` could be extremely valuable) the user won't have contributor access to an entire subscription.  Instead they will be given a resource group in a subscription managed by the central IT team.

If this is not already on the roadmap, please consider adding the concept of **`scope`** that would allow me to indicate that my template is either subscription scoped or resource group scoped.

If the template is resource group scoped, I would choose an existing resource group, which would be used during provisioning/deployment.

This could potentially be inferred from bicep template as it has the `targetScope` property, but I think it makes more sense to be in the `azure.yaml`.

**Comment by jongio** [comment]
@colbylwilliams and @danieljurek 

Today, azd doesn't support the resourceGroup scope, but in the mean-time, can you see if this will work for you?


Have a look at the commit here: https://github.com/jongio/azdexistingresourcegroup/commit/753441812489713f4741bdb0115d92e4d0937be4

It still does a sub level deployment, but it allows you to use an existing resource group.

@rajeshkamal5050  and @savannahostrowski - Let's keep this item open to track supporting deploying to resourceGroup scope level.  My comment above is a workaround.

**Comment by ellismg** [comment]
@mattchenderson As a note, in #2083 I am exploring what it would mean for `azd` to target deploying to a resource group directly (i.e. the root bicep you deploy would be targeting subscription scope).  This might be interesting to you.

**Comment by OrionSehn** [comment]
Just wanted to bump this, and make it known that, at least I, and I'm sure others would very much appreciate this feature. I may try and give it an effort myself in the next month or two if nobody can get to it before me.

**Comment by savannahostrowski** [comment]
We recently added resource group scoped deployments! Will be announced on Wednesday with our monthly release. 

You can give it a shot by running to enable it as an alpha feature.

```
azd config set alpha.resourceGroupDeployments on
```

When running `azd provision` or `azd up` on a repository with resource group scope infrastructure as code, you'll now be prompted to create a new resource group or select an existing resource group by name to provision to.

**Comment by rajeshkamal5050** [comment]
Marking this as complete. Should be part of 7/12 release.
