### ISSUE TITLE
[Issue] azd pipeline config errors when trying to set empty strings

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#3371]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
1.6.0

**Describe the bug**

I just merged https://github.com/Azure-Samples/azure-search-openai-demo/pull/1083 and tried it out. In my .env file, I had a few variables set to empty strings.

When I ran azd pipeline config, it error'd on each var with an empty string:

```
ERROR: failed setting OPENAI_ORGANIZATION secret: failed running gh variable set: exit code: 1, stdout: , stderr: 1 error occurred:
	* failed to set variable "OPENAI_ORGANIZATION": HTTP 422: Invalid request. (https://api.github.com/repos/pamelafox/azure-search-openai-demo/actions/variables)

Invalid input: object is missing required key: value.
```

**Comment by pamelafox** [comment]
@vhvb1989

**Comment by vhvb1989** [comment]
@pamelafox is there a difference between not having the env var and having it with empty string?
Does it impact the bicep inptus? 

Thinking if we want to ignore empty values or set them as variables with empty strings

**Comment by pamelafox** [comment]
I think there might be, as I've now got an error in the provision stage I need to look into. Will update soon.

**Comment by pamelafox** [comment]
Successful azd up once I removed the previously set environment variable:
https://github.com/pamelafox/azure-search-openai-demo/actions/runs/7918060139/job/21622001579

I would hope/presume it would also be successful if the un-needed environment variables were empty strings.

**Comment by vhvb1989** [comment]
> So I think azd should ideally set them as empty strings, to make sure a setup with a new environment overrides previously set non-empty strings.

I see.  makes total sense. 
I think azd should `deleteIfExist` all the secrets/variables with empty string or not found in .env.
It would also reproduce if you run `azd env unset foo` and foo is not removed from the pipeline :)
