### ISSUE TITLE
Add documentation for configurable AZD template sources

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#3377]
Today there isn't any public documentation for AZD template sources.
- Adds docs for the expected template source schema
- Add examples for adding/removing template sources
- Add special notes about the automatic `devcenter` template source when devcenter mode is enabled.

Template sourcess can be managed via the `azd template source` command group

**Comment by alexwolfmsft** [comment]
@wbreza  or @gkulin  do you have more information on these features somewhere? The only information I have is documented on the reference page  https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/reference#azd-template

For example, I'm not sure what these mentioned features are:

Adds docs for the expected template source schema
Add special notes about the automatic devcenter template source when devcenter mode is enabled.

**Comment by wbreza** [comment]
@alexwolfmsft - here is PR for the template sources feature.  Happy to sync up if you need more information.

**Template Sources**
https://github.com/Azure/azure-dev/pull/2573

**Dev Center Features**
https://github.com/Azure/azure-dev/pull/2767

**Comment by alexwolfmsft** [comment]
@wbreza thanks for that information. We do have this current doc that goes into dev center support:
https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/ade-integration

I think we should add a new doc that talks about the template source feature more generally, and then expanding that ADE integration doc with anything that's missing for that specific feature set - does that work for you?

**Comment by gkulin** [comment]
completed here: https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/configure-template-sources
