### ISSUE TITLE
[Issue] Trailing comma in GH Action output creates invalid URL

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#3388]
When azd deploy is run in a GH action the endpoint is outputted.  But it includes a trailing comma that GH treats as part of the URL and renders it invalid.

I recommend putting a space between the end of the URL and the comma.  Or remove the comma.

See comma after .43 here:
![image](https://github.com/Azure/azure-dev/assets/2163001/bd9db743-e748-4911-9f7a-28a3604b21da)

**Comment by rajeshkamal5050** [comment]
@hemarina if this is a minor cosmetic fix. Can we get it fixed for Apr/9 release?
