### ISSUE TITLE
[AspireDeployment] warmup aspire host early to reduce user wait time when environment is created

### ISSUE THREAD

**Issue by abpiskunov** [Azure/azure-dev#3389]
Here is the branch with new WarmupAsync API: 

https://devdiv.visualstudio.com/DevDiv/_git/WebTools?version=GBdev/ap/WarmupAzd&path=/src/ConnectedServices/ConnectedServices.Package2/Azure/AzDev/Rpc/Contracts/IAspireService.cs 

we call it early and forget. The goal for it to trigger a task that would initialize/refresh aspire host models on azd side (this would likely include dotnet build for aspire host). Later when user reaches the 3 step in the wizard we would call GetAspireHostAsync, which should either get model just prepared by WarmupAsync or wait for pending work there which would be much less than waiting for whole refresh started from scratch.

**Comment by weikanglim** [comment]
We spoke on Teams on this, using GetAspireHostAsync to retrieve the results early works for now.
