### ISSUE TITLE
Deploying javascript app with Aspire results in error during deploy step

### ISSUE THREAD

**Issue by timheuer** [Azure/azure-dev#3391]
**Output from `azd version`**
azd version 1.6.0 (commit f90c77f78899db817f56cde9eab4b9421ec15535)

**Describe the bug**
While deploying to azure with azd and Aspire Preview 3:
```
ERROR: failed packaging service 'angular': failing invoking action 'package', parsing source container image: empty image URL provided
```
**To Reproduce**
repo: https://github.com/timheuer/js-aspire
run `azd init` && `azd up`

**Expected behavior**
All services deploy

**Comment by robertjf** [comment]
I have the same problem. It was working on the previous version of azd this morning, and after upgrading via brew (MacOS) I now get the error described here when attempting to deply a nodejs container.

**Comment by rajeshkamal5050** [comment]
@wbreza suspecting the recent changes [Adds support to reference external or prebuilt image references #3269](https://github.com/Azure/azure-dev/pull/3269) might have caused this. Can you check with @ellismg ?

**Comment by sethwenzel** [comment]
I see that a fix has been merged -- any word on when the fix will get released?

**Comment by rajeshkamal5050** [comment]
> I see that a fix has been merged -- any word on when the fix will get released?

We have a release planned next week. If you want to try earlier, you can [use the daily bits](https://github.com/Azure/azure-dev/tree/main/cli/installer#download-from-daily-builds)
