### ISSUE TITLE
[Issue] azd cli github action for aks cluster: kubelogin not found in path

### ISSUE THREAD

**Issue by carmodyquinnms** [Azure/azure-dev#3394]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
image: mcr.microsoft.com/azure-dev-cli-apps:latest

**Describe the bug**
Running azd in a github action with the latest version.  After provisioning the aks cluster, it fails with the error message:
  ```
(✓) Done: AKS Managed Cluster: aks-azdaks01
ERROR: deployment failed: failed invoking event handlers for 'postprovision', converting kubeconfig: exec: "kubelogin": executable file not found in $PATH,converting kubeconfig: exec: "kubelogin": executable file not found in $PATH
Error: Process completed with exit code 1.
```

**To Reproduce**
Run AZD Up on the cqgh branch of 
https://github.com/Azure-Samples/ratings-nodejs-azd-akslza

**Expected behavior**
Expect for kubelogin to be available in the path on the azd image.

**Comment by carmodyquinnms** [comment]
@wbreza This should be assigned to you, however I do not have permissions to assign this.

**Comment by wbreza** [comment]
Thanks for reporting this.  As a workaround for the time being you should be able to manually install `kubelogin` within your pipeline.  
> [!NOTE]
> We're still waiting on the `kubelogin` team to push a new release with the `azd` login type.  We expect it this week.
