### ISSUE TITLE
[Issue] Receiving error when azd provision converts kubeconfig with kubelogin for AKS API login

### ISSUE THREAD

**Issue by carmodyquinnms** [Azure/azure-dev#3398]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
image: mcr.microsoft.com/azure-dev-cli-apps:latest

**Describe the bug**
Here is the pipeline run
https://github.com/Azure-Samples/ratings-nodejs-azd-akslza/actions/runs/7960418372/job/21729357494
Running azd in a github action with the latest version.  After provisioning the aks cluster, it fails with the error message:
  ```
2024/02/19 13:37:11 main.go:48: Retry: exit due to non-retriable status code
2024/02/19 13:37:11 command_runner.go:307: Run exec: 'kubelogin convert-kubeconfig --login azd --kubeconfig /github/home/.kube/aks-azdaks01' , exit code: 1
-------------------------------------stderr-------------------------------------------
Error: 'azd' is not a supported login method. Supported method is one of devicecode, interactive, spn, ropc, msi, azurecli, workloadidentity
2024/02/19 13:37:11 user_config_manager.go:39: creating empty config since '/github/home/.azd/config.json' did not exist.
2024/02/19 13:37:11 main.go:48: Retry: =====> Try=1
```

**To Reproduce**
Run AZD Up on the cqgh branch of 
https://github.com/Azure-Samples/ratings-nodejs-azd-akslza

**Expected behavior**
Expect for kubelogin to be able to convert the kubeconfig

**Comment by carmodyquinnms** [comment]
@wbreza I believe this should be assigned to you, however I do not have the authority.

**Comment by wbreza** [comment]
We are still waiting on the `kubelogin` team to publish a new release with the new `azd` login mode.  We expect it this week.

**Comment by wbreza** [comment]
@carmodyquinnms a new version of `kubelogin` has been released that include the new `azd` login method.
