### ISSUE TITLE
[Issue] Aspire resource azure.cosmosdb.connection.v0 is no longer working

### ISSUE THREAD

**Issue by christiannagel** [Azure/azure-dev#3400]
With a previous version I could successfully use an existing Cosmos DB resource with a connection configured, and use this API 

```csharp
    string cosmosConnectionString = builder.Configuration["CosmosConnectionString"] ?? throw new InvalidOperationException("Could not find CosmosConnectionString");

    var cosmos = builder.AddAzureCosmosDB("GamesCosmosConnection", cosmosConnectionString);
```

to use `azd init` and `azd up`. 

Using .NET Aspire Preview 3 and azd 1.6.1, I get this error:

```
ERROR: unsupported resource type: azure.cosmosdb.connection.v0
```

Now I can use this setup (the name needs to be lowercase)

```csharp
    var cosmos = builder.AddAzureCosmosDB("codebreaker")
       .AddDatabase("codebreaker");
```

Which successfully creates the Azure Cosmos DB with `azd up`.

I think both options should succeed.

**Comment by christiannagel** [comment]
@davidfowl - thanks! Will this be back together with the added managed identities in preview4?

**Comment by davidfowl** [comment]
I think it depends on what you are trying to accomplish:

If you want to connect to an existing resource and the connection information isn't secret then just use `WithEnvironment` with the right format ("ConnectionStrings__name").

This assumes you have configured the resource to enable connecting to it from your local machine (including role assignments for the right user). There's nothing built in that will just do the role assignments for the resource that already exists, this is something we do not do out of the box.

With preview4 we can represent a few things (including the above):

1. The ability to reference a connection string or value that changes between development time and publish time. For e.g. you can connect to an existing sql database locally (like local db) and then swap that value during publish time (azd will prompt and ask for the value).
2. The ability to write a bicep file and wire it into the app host (and also the manifest). This will enable you to define anything that can be written with bicep.

Using number 1 would be the ideal way to do what you are attempting to do.

> together with the added managed identities in preview4?

This would require you to write some bicep that grabs information from the existing resource and then does role assignments with the right user information (which we can provide).

Hopefully that makes some sense.

**Comment by christiannagel** [comment]
@davidfowl, yes, this is great! 

With preview2 I used the same existing Azure Cosmos database at development time and when the solution was published to Azure. With preview3 I can now deploy the Cosmos database to Azure with `azd up`. I expected to use the emulator locally, but there seems to be an issue with the emulator certificate when using EF Core: https://github.com/dotnet/aspire/issues/2322.

**Comment by vhvb1989** [comment]
expected breaking change from Aspire preview2 -> preview3.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 @davidfowl are we expecting any fixes/doc updates here? or can we close it?

**Comment by davidfowl** [comment]
I think there's nothing to do here for p4, we can close.
