### ISSUE TITLE
azd infra synth should put yaml files for container apps under infra folder

### ISSUE THREAD

**Issue by davidfowl** [Azure/azure-dev#3409]
All of the infrastructure should go into a single root folder instead of each project folder. Make it easier to look at and delete.

**Comment by ellismg** [comment]
I think that if we model the AppHost as the thing that provides the infrastructure (in a more first class way than we do today, where the `ImportManager` basically removes the app host from the project graph and replaces it with the individual services and the `infra` folder this will more or less all fall out.

**Comment by davidfowl** [comment]
Agreed, that would be ideal. Are there any side effects of doing that? We still want to deploy individual services.

**Comment by rajeshkamal5050** [comment]
> I think that if we model the AppHost as the thing that provides the infrastructure (in a more first class way than we do today, where the `ImportManager` basically removes the app host from the project graph and replaces it with the individual services and the `infra` folder this will more or less all fall out.

@davidfowl @vhvb1989 @mitchdenny @ellismg moving it as a fit-n-finish item post Preview 5. Please let me know if you think otherwise.

**Comment by davidfowl** [comment]
Can we get ths for P5?

**Comment by rajeshkamal5050** [comment]
@ellismg can we get this in for Preview 5 i.e., Apr 09 azd release?

**Comment by rajeshkamal5050** [comment]
Not a blocker for Preview 5 moving to next milestones.

**Comment by weikanglim** [comment]
Added with #3800, closing out.
