### ISSUE TITLE
CLI should provide full deployment data (--output json mode)

### ISSUE THREAD

**Issue by karolz-ms** [Azure/azure-dev#341]
Today the CLI provides only partial deployment data, esp. if the deployment fails. Instead, we should gather all the data, so the user has a complete picture of what went wrong. Specifically

1. We should gather data for all deployments that are related to CLI invocation (and not just the subscription-level "root" deployment).
2. Deployment data should include all affected resources and all deployment operations. 
3. For failed deployment operations we should include all available error information.

**Comment by rajeshkamal5050** [comment]
@karolz-ms I believe this is not specific to VS? Do you think this should also be factored as part of the error handling exploration which @Austinauth is looking into?

**Comment by karolz-ms** [comment]
@rajeshkamal5050 correct, this will benefit all tooling, not just VS. That said, we expect that `--output json` will be primarily used by tools, and not humans (the default output format should serve humans better).

**Comment by rajeshkamal5050** [comment]
Closing this since we have added internal support only for VS to consume provision, refresh and show commands with JSON outputs.
