### ISSUE TITLE
Allow configuration of the image tag name for container apps

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#342]
Today, when pushing an image to a container registry, we use the name `latest` when we tag the docker image.  We should allow this to be overridden (possibly in the `azure.yaml` file?) and should consider if "latest" is the correct default here.  It might be better to include some sort of distinguisher in the name.

**Comment by rajeshkamal5050** [comment]
Addressed as part of AKS to  - https://github.com/Azure/azure-dev/pull/1629

https://github.com/Azure/azure-dev/blob/main/schemas/v1.0/azure.yaml.json

```
"tag": {
"type": "string",
"title": "The tag that will be applied to the built container image.",
"description": "If omitted, will default to 'azd-deploy-{unix time (seconds)}'. Supports environment variable substitution. For example, to generate unique tags for a given release: myapp/myimage:${DOCKER_IMAGE_TAG}"
}
```
