### ISSUE TITLE
 Applications with external TCP ingress can only be deployed to Container App Environments that have a custom VNET

### ISSUE THREAD

**Issue by mrpmorris** [Azure/azure-dev#3428]
Adding a `playground` to the latest dotnet/aspire repo.

**Output from `azd version`**
azd version 1.6.1 (commit eba2c978b5443fdb002c95add4011d9e63c2e76f)

**Describe the bug**
When executing `azd up` I see the following:

```
ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
ContainerAppTcpRequiresVnet: Applications with external TCP ingress can only be deployed to Container App Environments that have a custom VNET. Set ingress traffic to 'Limited to Container Apps Environment' if you want to deploy to a Container App Environment without a custom VNET. For more information on custom VNETs, please visit https://go.microsoft.com/fwlink/?linkid=2238174

TraceID: 4609a9421a8a0e834db222a6ce227d87

ERROR: error executing step command 'provision': deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
ContainerAppTcpRequiresVnet: Applications with external TCP ingress can only be deployed to Container App Environments that have a custom VNET. Set ingress traffic to 'Limited to Container Apps Environment' if you want to deploy to a Container App Environment without a custom VNET. For more information on custom VNETs, please visit https://go.microsoft.com/fwlink/?linkid=2238174

TraceID: 4609a9421a8a0e834db222a6ce227d87
```

**To Reproduce**
1. Find an existing playground app.
2. Change the code to 
```c#
var builder = DistributedApplication.CreateBuilder(args);
builder.AddRedis("redis1").PublishAsContainer();
builder.Build().Run();
```
3. `az init`
4. `az up`

**Environment**
Information on your environment:
dotnet --version
8.0.201

**Additional context**
dotnet --info
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.ccaef9c0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

.NET workloads installed:
 Workload version: 8.0.100-manifests.ccaef9c0
 [maui-windows]
   Installation Source: VS 17.8.34525.116, VS 17.9.34526.213
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.8.34525.116, VS 17.9.34526.213
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8004\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.8.34525.116, VS 17.9.34526.213
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8004\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.8.34525.116, VS 17.9.34526.213
   Manifest Version:    34.0.52/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.52\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools-net6]
   Installation Source: VS 17.8.34525.116, VS 17.9.34526.213
   Manifest Version:    8.0.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.net6\8.0.2\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools-net7]
   Installation Source: VS 17.8.34525.116, VS 17.9.34526.213
   Manifest Version:    8.0.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.net7\8.0.2\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools]
   Installation Source: VS 17.8.34525.116, VS 17.9.34526.213
   Manifest Version:    8.0.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.current\8.0.2\WorkloadManifest.json
   Install Type:              Msi

 [aspire]
   Installation Source: VS 17.9.34526.213
   Manifest Version:    8.0.0-preview.1.23557.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0-preview.1.23557.2\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  5.0.408 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  8.0.101 [C:\Program Files\dotnet\sdk]
  8.0.200-preview.23624.5 [C:\Program Files\dotnet\sdk]
  8.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\temp\aspire\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by davidfowl** [comment]
Could this be policy driven by the azure subscription that you're using?

**Comment by mrpmorris** [comment]
@davidfowl It's just a standard Azure subscription. I've not added any policies or anything.

**Comment by davidfowl** [comment]
Oh wait, are you exposing the redis service to the internet?

**Comment by mrpmorris** [comment]
Yes.

It's actually a NATS server which has it's own Auth, but I used Redis to show it wasn't a problem with the Aspire implementation of NATS.

I don't think there is a way of adding a vnet in Aspire, is there?

**Comment by davidfowl** [comment]
No there's no support for adding a vnet to the azure container app. I don't recommend exposing anything beyond your own containers from an ACA app. At least not at the moment.

If you want to mess around with this, you can always use **azd infra synth** and tweak the bicep files.

**Comment by mrpmorris** [comment]
Does this mean I am premature in expecting to be able to define my infrastructure with Aspire, run it locally, and then have it deploy to Azure?

**Comment by davidfowl** [comment]
Oh for sure, Aspire isn't mature enough to model everything that you might need. We're still building out the infrastructure required to let people model more things, the compute environment isn't something we handle today, so you have to drop down to bicep and tweak to enable what you want.

Aside: I have no idea why you're exposing redis or nats ourside of our ACA cluster. Why is that?

**Comment by mrpmorris** [comment]
I was testing the Aspire integration of NATS.

I only used Redis to demonstrate the error wasn't NATS specific.

However, it is logical to expose NATS as it is designed to be connected to by many IoT devices for message exchanges, and had it's own authentication/authorization built in for that purpose.

**Comment by rajeshkamal5050** [comment]
For Preview 4, we are [hiding container.v0 resources to be configured as external services](https://github.com/Azure/azure-dev/pull/3444) due to [limitations in ACA supporting it](https://github.com/Azure/azure-dev/issues/3441#issuecomment-1965422357)

Track these issues for updates on how/when things will eventually land,
- Aspire - https://github.com/dotnet/aspire/issues/2099
- Azd - https://github.com/Azure/azure-dev/issues/3267

cc @ellismg  @vhvb1989 @davidfowl @mitchdenny
