### ISSUE TITLE
set-cli-version-cd.yml should support GA versions in addition to prerelease

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#344]
Currently only supports easily adding to the end of prerelease versions. In the case of a GA version it should append `-beta.` to the end of the version number before adding the `.$(Build.BuildId)` value.

**Comment by danieljurek** [comment]
In different build scenarios we'll need to set the CLI version to differ from what's specified in `version.txt`. In these cases, we'll append information to the version so it's not mistaken for an official release. 

Some examples use a contrived build ID `123`

The `daily` release could happen multiple times a day as relevant files are updated in the `main` branch. It might make more sense to use other terms like `unstable` instead of `daily`. 

| version.txt | PR | CI/CD (merge to `main`) | Release (unchanged from version.txt) | 
| ----------- | --- | --------------------------- | -------- |
| `0.1.0-beta.1` | `0.1.0-beta.1-pr.123` | `0.1.0-beta.1-daily.123` | `0.1.0-beta.1` | 
| `1.0.0` | `1.0.0-pr.123` | `1.0.0-daily.123` | `1.0.0` |

@jongio, @weikanglim, @ellismg -- Would these proposed prerelease qualifiers make sense to customers or are there more clear terms we can use here?

**Comment by rajeshkamal5050** [comment]
I am assuming we have already sorted the versioning out.
