### ISSUE TITLE
[Aspire] azd up sometimes fails because of not reaching ACR

### ISSUE THREAD

**Issue by christiannagel** [Azure/azure-dev#3440]
When creating new Azure resources and publishing the app, `azd up` sometimes fails because it cannot access the ACR. Repeating it, everything succeeds. 
For a better user experience, I think it would be useful to check for the ACR to be available and repeat the check before failing the deployment.

I had this issue when deploying to East US 2 from within Europe. This time creating the Container Apps Environment was a lot faster than previous experiences. It looks like that's why this failed.

Versions:
azd version 1.6.1 (commit eba2c978b5443fdb002c95add4011d9e63c2e76f)
aspire 8.0.0-preview.3.24105.21/8.0.100

```
Packaging services (azd package)

SUCCESS: Your application was packaged for Azure in 5 seconds.

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

Subscription: <redacted>
Location: East US 2

  You can view detailed progress in the Azure Portal:
  https://portal.azure.com/#view/HubsExtension/DeploymentDetailsBlade/~/<redacted>

  (✓) Done: Resource group: rg-codebreaker-packt12us
  (✓) Done: Log Analytics workspace: law-okccxl67xgpc6
  (✓) Done: Container Registry: acrokccxl67xgpc6
  (✓) Done: Container Apps Environment: cae-okccxl67xgpc6
  (✓) Done: Container App: redis
  (✓) Done: Azure Cosmos DB: codebreakercosmosokccxl67xgpc6

SUCCESS: Your application was provisioned in Azure in 3 minutes 16 seconds.
You can view the resources created under the resource group rg-codebreaker-packt12us in Azure Portal:
https://portal.azure.com/#@/resource/subscriptions/<redacted>

Deploying services (azd deploy)

  (x) Failed: Deploying service blazor

ERROR: failed deploying service 'blazor': failing invoking action 'deploy', logging in to registry: failed logging into container registry, token: failed getting ACR token: POST https://acrokccxl67xgpc6.azurecr.io/oauth2/exchange
--------------------------------------------------------------------------------
RESPONSE 404: 404 Not Found
ERROR CODE UNAVAILABLE
--------------------------------------------------------------------------------
Response contained no body
--------------------------------------------------------------------------------
, admin: cannot find registry with name 'acrokccxl67xgpc6' and subscriptionId '<redacted'

ERROR: error executing step command 'deploy --all': failed deploying service 'blazor': failing invoking action 'deploy', logging in to registry: failed logging into container registry, token: failed getting ACR token: POST https://acrokccxl67xgpc6.azurecr.io/oauth2/exchange
--------------------------------------------------------------------------------
RESPONSE 404: 404 Not Found
ERROR CODE UNAVAILABLE
--------------------------------------------------------------------------------
Response contained no body
--------------------------------------------------------------------------------
, admin: cannot find registry with name 'acrokccxl67xgpc6' and <redacted>
```

After starting the deployment again, everything succeeded.

**Comment by weikanglim** [comment]
Hey @christiannagel , @vhvb1989 and I were reviewing this issue again, we noticed that you mentioned that the issue occurs when deploying to East US 2 from within Europe. Have you noticed it when deploying to the same geolocation? We are suspecting that geo-replication is the primary factor behind the propagation delay.

The slightly uneasy part of making an improvement here is that `azd` today doesn't quite know whether the ACR was recently created (this is a bicep output). The service is simply responding with 404 that "the ACR doesn't exist". If `azd` waits and retries, it may end up waiting longer in cases where truly, the ACR doesn't exist.

**Comment by christiannagel** [comment]
Hi @weikanglim , @vhvb1989 - I'm deploying from my local system in Austria. I didn't see this issue when deploying to West Europe, only to East US 2. However, in West Europe resource provisioning took 7+ minutes, in East US 2 the provisioning was ready after 3 minutes and 16 seconds.

**Comment by christiannagel** [comment]
Hi @weikanglim, @vhvb1989 - currently I'm seeing a timing issue more often using `azd up`, also when deploying from within Austria to West Europe. It's also a lot faster now (probably because of Easter). This error was curious:

```
? Select an Azure Subscription to use:  3. <redacted>
? Select an Azure location to use: 34. (Europe) West Europe (westeurope)

Packaging services (azd package)


SUCCESS: Your application was packaged for Azure in less than a second.

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

Subscription: <redacted>
Location: West Europe

  You can view detailed progress in the Azure Portal:
  https://portal.azure.com/#view/HubsExtension/DeploymentDetailsBlade/~/overview/id/<redacted>providers%2FMicrosoft.Resources%2Fdeployments%2Fcodebreaker-08-dev-1711806663

  (✓) Done: Resource group: rg-codebreaker-08-dev
  (✓) Done: Log Analytics workspace: law-ssengodjcf2mu
  (✓) Done: Container Registry: acrssengodjcf2mu
  (✓) Done: Container Apps Environment: cae-ssengodjcf2mu

SUCCESS: Your application was provisioned in Azure in less than a second.
You can view the resources created under the resource group rg-codebreaker-08-dev in Azure Portal:
https://portal.azure.com/#@/resource/subscriptions/<redacted>/resourceGroups/rg-codebreaker-08-dev/overview

Deploying services (azd deploy)

  (✓) Done: Deploying service bot
  - Endpoint: https://bot.yellowground-22274287.westeurope.azurecontainerapps.io/

  (x) Failed: Deploying service gameapis

ERROR: failed deploying service 'gameapis': failing invoking action 'deploy', updating container app service: applying manifest: PUT https://management.azure.com/subscriptions/7221029f-b7dc-4ab8-b117-111900d0d73c/resourceGroups/rg-codebreaker-08-dev/providers/Microsoft.App/containerApps/gameapis
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: InvalidParameterValueInContainerTemplate
--------------------------------------------------------------------------------
{
  "error": {
    "code": "InvalidParameterValueInContainerTemplate",
    "message": "The following field(s) are either invalid or missing. Field 'template.containers.gameapis.image' is invalid with details: 'Invalid value: \"acrssengodjcf2mu.azurecr.io/azd-deploy-gameapis-1711806831\": Get \"https://acrssengodjcf2mu.azurecr.io/v2/\": dial tcp: lookup acrssengodjcf2mu.azurecr.io on 100.100.224.10:53: no such host';."
  }
}
--------------------------------------------------------------------------------

TraceID: 3c2685661739cea960ad29545807b2a6

ERROR: error executing step command 'deploy --all': failed deploying service 'gameapis': failing invoking action 'deploy', updating container app service: applying manifest: PUT https://management.azure.com/subscriptions/7221029f-b7dc-4ab8-b117-111900d0d73c/resourceGroups/rg-codebreaker-08-dev/providers/Microsoft.App/containerApps/gameapis
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: InvalidParameterValueInContainerTemplate
--------------------------------------------------------------------------------
{
  "error": {
    "code": "InvalidParameterValueInContainerTemplate",
    "message": "The following field(s) are either invalid or missing. Field 'template.containers.gameapis.image' is invalid with details: 'Invalid value: \"acrssengodjcf2mu.azurecr.io/azd-deploy-gameapis-1711806831\": Get \"https://acrssengodjcf2mu.azurecr.io/v2/\": dial tcp: lookup acrssengodjcf2mu.azurecr.io on 100.100.224.10:53: no such host';."
  }
}
--------------------------------------------------------------------------------

TraceID: 3c2685661739cea960ad29545807b2a6
```

The provisioning part was successful. With the deployment stage, the bot service was successfully deployed - thus the ACR could be reached here. When deploying the games API, the ACR could not be reached: "no such host". Probably the deployment to the games API was started earlier?
With the output it was showing *Your application was provisioned in Azure in less than a second.*, but this of course was not correct. Deployments within the Azure portal show 41,71 seconds for resources, and 48,51 seconds for the app configuration.

Running azd up again, everything succeeded.

I had similar timing issues running this from a GitHub Actions workflow using azd deploy.

Versions currently used:
azd version 1.7.0 (commit 49d6adc2efb178083f61822e6b4715258560803d)
aspire 8.0.0-preview.6.24177.4/8.0.100  SDK 8.0.200

**Comment by vhvb1989** [comment]
@christiannagel , for the versions you mentioned, seems like you are trying the last azd release 1.7.0 with a daily aspire version (preview-6) ?
We don't cover such combination.

There are currently breaking changes for the upcoming aspire P5. The fixes for azd are in this PR: https://github.com/Azure/azure-dev/pull/3612  .  If you are trying daily aspire builds, please install azd from that PR or wait until it is merged to take azd's daily version.

**Comment by christiannagel** [comment]
@vhvb1989 - thanks for this information! I switched to the Aspire daily builds as there's functionality I need with my upcoming book. I'll now use azd from PR #3612. 
What's the best way to find a matching azd version for the Aspire daily builds?

**Comment by vhvb1989** [comment]
> What's the best way to find a matching azd version for the Aspire daily builds?

We've been trying to sync merging features in dotnet/aspire which requires changes to azd until the azd change is ready. By doing this, we are keeping azd-daily build compatible with aspire-daily build.
However, sometime dotnet/aspire is ready and azd needs some more extra time, so the change in Aspire is merged and the azd-daily becomes incompatible with aspire-daily for a few days.  That's the current case, but it is not too often.

Once Aspire GA, this should stop happening, as there should not be breaking changes on top of GA.

**Comment by rajeshkamal5050** [comment]
Depends on https://github.com/microsoft/azure-container-apps/issues/1061

**Comment by vhvb1989** [comment]
Update from ACA team:

Looking through the deployment issue maybe this helps:  
We use Azure DNS Zones to generate the ACR's DNS and according to their documentation there's an up to 60 seconds propagation delay time. If the endpoint ain't working just after creation but works soon after. Using a delay might fix your issues. Here's Doc on the subject:
[https://techcommunity.microsoft.com/t5/azure-database-support-blog/add-wait-operation-to-arm-template-deployment/ba-p/2915342](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftechcommunity.microsoft.com%2Ft5%2Fazure-database-support-blog%2Fadd-wait-operation-to-arm-template-deployment%2Fba-p%2F2915342&data=05%7C02%7CVictor.Vazquez%40microsoft.com%7C8552f2060dd84bda7ab808dc6adbb25f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638502739036416636%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=PYtBts1eHRv3EalGKFVh%2BRMJ4VP5q78v6idsCb%2Ff210%3D&reserved=0)
[https://learn.microsoft.com/en-us/azure/dns/dns-faq](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fdns%2Fdns-faq&data=05%7C02%7CVictor.Vazquez%40microsoft.com%7C8552f2060dd84bda7ab808dc6adbb25f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638502739036427408%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=WANRSpgUNOzmy0hLammDJS6a1Fz%2FnYY%2F3WuApuOylIE%3D&reserved=0)

**Comment by KSemenenko** [comment]
I have new amazing issue 

```
RESPONSE 200: 200 OK
ERROR CODE: ContainerAppOperationError
--------------------------------------------------------------------------------
{
  "id": "/subscriptions/4019bbed-0152-43aa-b7f4-a57b85f6dd22/providers/Microsoft.App/locations/francecentral/containerappOperationStatuses/24fabfa5-24a3-4575-ba70-ca6ab5a45ec3",
  "name": "24fabfa5-24a3-4575-ba70-ca6ab5a45ec3",
  "status": "Failed",
  "error": {
    "code": "ContainerAppOperationError",
    "message": "Failed to provision revision for container app 'api'. Error details: The following field(s) are either invalid or missing. Field 'template.containers.api.image' is invalid with details: 'Invalid value: \"acronzlpwbmtd5fw.azurecr.io/s/api-devops4:azd-deploy-1740587720\": GET https:: MANIFEST_UNKNOWN: manifest tagged by \"azd-deploy-1740587720\" is not found; map[Tag:azd-deploy-1740587720]';.."
  },
  "startTime": "2025-02-26T16:35:55.9727926"
}
--------------------------------------------------------------------------------

  (x) Failed: Deploying service api

ERROR: error executing step command 'deploy --all': failed deploying service 'api': updating container app service: polling for container app update completion: GET https://management.azure.com/subscriptions/11111111-0152-43aa-b7f4-a57b85f6dd22/providers/Microsoft.App/locations/francecentral/containerappOperationStatuses/24fabfa5-24a3-4575-ba70-ca6ab5a45ec3

```
but in the same time i see my image in acr

**Comment by vhvb1989** [comment]
@KSemenenko I've seen that issue one or two times. It usually goes away after a retry.  I think it is ACA internal issue (ContainerAppOperationError) . Can you repro all the time?

**Comment by KSemenenko** [comment]
@vhvb1989 i have it two days in a row. Yesterday and today. West Europe and Central France region. On aspire 9 and 9.1

**Comment by KSemenenko** [comment]
We found the issue, I just will keep you here https://github.com/dotnet/aspire/issues/7797#issuecomment-2687379003
