### ISSUE TITLE
[WebToolsE2E][Aspire] Create a Aspire Starter App with redis, running 'azd up' fails with error: "deployment failed: failing invoking action 'provision'".

### ISSUE THREAD

**Issue by v-reinawang** [Azure/azure-dev#3441]
**REGRESSION INFO**: Worked on Aspire 8.0.0-preview.3.24105.21

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS Code[1.86.2] and C# Dev Kit[1.3.10]
3. Install SDK 8.0.202
4. Install Aspire 8.0 P4 workload version 8.0.0-preview.4.24125.2
5. Apply NuGet Feeds
6. Install Docker Desktop for Windows
7. Install azd [1.7.0-beta.1-daily.3527315]

**REPRO STEPS**
1. Open CMD, creating an Aspire Starter App using following commands:
     `dotnet new aspire-starter --use-redis-cache -o aspirestarter`
2. Run 'cd aspirestarter'
3. Runing 'azd init', select 'Use code in the current directory' > Confirm and continue initializing my app > select frontend as deployment service > type a new environment name, press enter
4. Running 'azd up'

**ACTUAL:**
  (x) Failed: Container App: cache

ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
ContainerAppTcpRequiresVnet: Applications with external TCP ingress can only be deployed to Container App Environments that have a custom VNET. Set ingress traffic to 'Limited to Container Apps Environment' if you want to deploy to a Container App Environment without a custom VNET. For more information on custom VNETs, please visit https://go.microsoft.com/fwlink/?linkid=2238174

TraceID: b2f3f1b41a0265aa38cec062962e01b2

ERROR: error executing step command 'provision': deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
ContainerAppTcpRequiresVnet: Applications with external TCP ingress can only be deployed to Container App Environments that have a custom VNET. Set ingress traffic to 'Limited to Container Apps Environment' if you want to deploy to a Container App Environment without a custom VNET. For more information on custom VNETs, please visit https://go.microsoft.com/fwlink/?linkid=2238174

TraceID: b2f3f1b41a0265aa38cec062962e01b2
![image](https://github.com/Azure/azure-dev/assets/109339894/1a6f504f-7bab-43fd-a576-ff709110705e)

**EXPECTED**
Running 'azd up' successfully.

**Comment by rajeshkamal5050** [comment]
@davidfowl @mitchdenny @vhvb1989 aware of anything broken with latest changes?

**Comment by mitchdenny** [comment]
When deploying the app did they opt to make `cache` external? If so that is probably what is going on here.

**Comment by mitchdenny** [comment]
With the removal of the `redis.v0` resource type from the manifest, AZD is now relying on the `container.v0` resource type that we emit. But because it is a `container.v0` resource it shows up in the list of resources to potentially be exposed publicly.

But there is a limitation in ACA around exposing arbitrary TCP endpoints by the looks of it unless you have your own vnet.
