### ISSUE TITLE
Build requires to have Powershell installed

### ISSUE THREAD

**Issue by jdubois** [Azure/azure-dev#346]
I'm running the project tests using `mage azd:test` and they are failing as Powershell isn't installed on my machine:

```
Error Trace:	executil_test.go:77
        	Error:      	Not equal:
        	            	expected: "signal: killed"
        	            	actual  : "exec: \"pwsh\": executable file not found in $PATH
```

Unit tests shouldn't depend on an external tool being installed on the computer.

**Comment by weikanglim** [comment]
These are integration tests, but `golang` doesn't offer any out-of-the-box ability to separate out integration vs unit tests. Not worth fixing at the moment. Developer can easily ignore the error, and they will be run correctly on CI. We can revisit this later if needed.
