### ISSUE TITLE
[Issue] Support more "inputs" generation strategies in Aspire manifest

### ISSUE THREAD

**Issue by eerhardt** [Azure/azure-dev#3462]
Today in Aspire, we can say:

```json
      "inputs": {
        "password": {
          "type": "string",
          "secret": true,
          "default": {
            "generate": {
              "minLength": 10
            }
          }
        }
      }
```

This allows us to generate a value during `azd up`. However, this always returns values that have lower, upper, and numbers in it. This becomes a problem when we want to use this functionality to generate things that aren't passwords - like user names for PostgreSQL Flexible Server. If we use numbers in those values, the admin name can't start with a number.

We should add the ability to specify more information about the type of string being generated. Following the options from https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password that would be useful, we should add the following to `inputs:<name>:default:generate`:

* Add support for the following bools
    * `lower` - default `true`
    * `upper` - default `true`
    * `numeric` - default `true`
    * `special` - default `true`
* Add support for the following numbers
    * `minLower` - default `0`
    * `minUpper` - default `0`
    * `minNumeric` - default `0`
    * `minSpecial` - default `0`

Optionally, we can also have an `overrideSpecial` value, but I don't think it is strictly necessary. And we can add it in the future, if we find the need.

@vhvb1989 @ellismg @davidfowl

**Comment by vhvb1989** [comment]
An alternative which does not requires changes to the current Aspire manifest is to use the `secure` field to switch between using `LowerCaseLetters` and `LettersAndDigits`

If the input is set as `secret:true` in the manifest, azd would use `LettersAndDigits`
But if `secrets:false`, azd would use `LowerCaseLetters`

This would work only if Aspire will never need something like generating a LettersAndDigits non-secure input for something else (which I think it is currently the case)

**Comment by eerhardt** [comment]
> If the input is set as secret:true in the manifest, azd would use LettersAndDigits
But if secrets:false, azd would use LowerCaseLetters

My concern would be if that is flexible enough to support all cases. We may want non-secret generated values to have upper case letters. Or we may want secret values to also contain "special characters" as well as letters and numbers.

**Comment by ellismg** [comment]
I wonder if there would be some way to have the manifest provide a template or schema for the password, which the tool would then use to generate.  You could image some regex like syntax with ranges and groups: `[a-zA-Z0-9]{20}` for a 20 character alphanumeric string and `[a-zA-Z][a-zA-Z0-9]{19}` for another 20 character alphanumeric password (except that the first character can't be a number).

Another option would be to take inspiration from how the `random_password` element works is Terraform - since this sort of models that https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password.

**Comment by eerhardt** [comment]
> Another option would be to take inspiration from how the random_password element works is Terraform

I like this approach better than creating a new regex-like syntax. The regex-like syntax seems like it could be misused since it is so unbounded. It would also be hard to document and probably implement as well.

The random_password behavior (from my quick skimming of the docs) seems like it would support all the scenarios I had in mind.

**Comment by eerhardt** [comment]
> Another option would be to take inspiration from how the random_password element works is Terraform

I've updated the top comment with a concrete proposal inspired by this suggestion. Please take a look and let me know what you think.

**Comment by rajeshkamal5050** [comment]
Requires changes to the Aspire Manifest. Adding to the March milestone i.e., Aspire Preview 5.

@eerhardt do you also want to add another issue on Aspire core?

**Comment by ellismg** [comment]
> The random_password behavior (from my quick skimming of the docs) seems like it would support all the scenarios I had in mind.

My one concern here is that it will be hard to express something like: "alphanumeric but the first character can't be a number" which actually seems to be fairly common in practice.

Now you could fix this by generating two strings, one of which is just a one character random alphabetical string and then concat it to a 19 character alphanumeric password (and I think the manifest would allow that using a combination of `input.v0` resource and `value.v0` resources?) but it feels like it may be more frustrating in practice.

**Comment by eerhardt** [comment]
> do you also want to add another issue on Aspire core?

https://github.com/dotnet/aspire/issues/2633

> it will be hard to express something like: "alphanumeric but the first character can't be a number" which actually seems to be fairly common in practice.

Is it common to _require_ alphanumeric in those situations? I get that there are scenarios where numeric characters are allowed, but can't be first. But are there scenarios where the value _must_ contain a number?
