### ISSUE TITLE
[Feature] Add ability to set default Service Principal properties for all SP's created by AZD

### ISSUE THREAD

**Issue by tonybaloney** [Azure/azure-dev#3473]
AZD creates AAD applications in the subscription for certain commands, like configuring the GitHub Action for an AZD template.

I'd like the ability to set some default properties of those applications because the auto-generated name isn't much to go off.

- serviceManagementReference should be set to a user-configured GUID
- description should be set to an auto-generated string of which template it was created by

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you help?

**Comment by vhvb1989** [comment]
@tonybaloney you can control the name of the app by setting `--principal-name the-name-you-want` when running `azd pipeline config`

The description is currently set by default to `"Autogenerated from Azure Developer CLI"` 

We are not using/setting `serviceManagementReference`, is this something you would want to set as part of the command?  like:

> azd pipeline config --serviceManagementRef GUID-you-set

Or are you saying azd should use something like the principal-id from the user running azd and set it as the value for `serviceManagementReference` ?

**Comment by tonybaloney** [comment]
I'd like to be able to set `serviceManagementReference` to a system-wide value for all principals without having to specify it on the command line. This feature would be used by all _internal_ users at Microsoft because that value should be the service-tree reference ID. We're having to retroactively apply these using a script right now

**Comment by vhvb1989** [comment]
Bringing this to current iteration as it is affecting more internal customers now.
Talked to @ellismg and defined a strategy by setting `azd config set pipeline.config.smf id` for azd to use the id in all projects.

As a plus, we could add the `--smf` flag to `pipeline config` command and support setting the config key per environment
