### ISSUE TITLE
[Issue] Remove input "type" in Aspire Manifest

### ISSUE THREAD

**Issue by eerhardt** [Azure/azure-dev#3487]
Today in Aspire, we say:

```json
      "inputs": {
        "password": {
          "type": "string",
          "secret": true,
          "default": {
            "generate": {
              "minLength": 10
            }
          }
        }
      }
```

The `"type": "string"` portion is unnecessary. We only support string inputs.

When trying to remove this property, and use `azd init`, I got an error:

```
ERROR: unsupported input type:
```

Can we remove this property from the manifest?

cc @ellismg @vhvb1989 @mitchdenny @davidfowl

**Comment by rajeshkamal5050** [comment]
Adding it to Preview 5.
