### ISSUE TITLE
[Feature] Az Dev should rollback on resource creation failure

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-dev#350]
**Describe the bug**
When I ran `azd up` I hit a permanent error: "we are currently experiencing high demand in ...". This means it is extremely unlikely that I could run the command a second time and have it succeed.

![image](https://user-images.githubusercontent.com/74415662/160452735-d962b62e-6adc-4ff8-a5fd-651db58233b8.png)

Unfortunately, the error dumped me back to the command prompt, but also left in place the resource group and the other resources that had already been created. These are now useless to me because if I want to get my app deployed I need to try a different region.

**To Reproduce**
`azd up --template todo-nodejs-mongo`
Select region 'west us 2'

**Expected behavior**
In the short term, I would like `azd up` to ask me if I would like to "Try again, Delete the already created resources, or Quit"

In the long term, I would like `azd up` to interpret the error and be smart about whether it is a permanent or transient error and provide options accordingly.

**Comment by savannahostrowski** [comment]
Closing this in favour of https://github.com/Azure/azure-dev/issues/463
