### ISSUE TITLE
Fail to run `azd up` with `ASA-Samples-Event-Driven-Application`

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#3500]
**Describe the issue:**
Test `ASA-Samples-Event-Driven-Application` template on DevContainer. Run `azd up`, get error as follow：
![image](https://github.com/Azure/azure-dev/assets/80496810/64f2a616-ab73-495a-a5e8-4e1de14cda9a)

Run `azd pipeline config` get same error:
![image](https://github.com/Azure/azure-dev/assets/80496810/14f599fa-d97e-4d76-81e7-52ac6e5ed6e8)

**Repro Steps:**

1. Login in with command: `azd auth login`.
2. Execute command: `azd init -t ASA-Samples-Event-Driven-Application`.
3. Run `azd up`.
4. Run `azd pipeline config`.

**Environment:**
- Template: ASA-Samples-Event-Driven-Application.
- Azd version : 1.7.0-beta.1-daily  (commit https://github.com/Azure/azure-dev/commit/81f3efd1049889762d01ca46a35630005b45f0b5)

**Expected behavior:**
Run `azd up` and `azd pipeline config` can pass.

@rajeshkamal5050  for notification.

**Comment by rajeshkamal5050** [comment]
@weikanglim can you triage to see if core asa azd deploy or template specific issue?

cc @yiliuTo @saragluna from ASA team to also take a look.

**Comment by weikanglim** [comment]
At a glance, this is happening since the container app is being deployed into what seems like a separate Spring APps managed resource group.

After provisioning, I have:
- rg-weilim-asa-eda-<random> -- The resource group that hosts all the resources
- env-<random>_SpringApps_<random guid> -- This resource group hosts only the container app instance

**Comment by rajeshkamal5050** [comment]
Thanks @weikanglim 

From the docs, https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application?tab=readme-ov-file#quickstart after setting the plan to `azd env set PLAN standard` seems to be deploying fine.

But, the default `Standard consumption and dedicated plan(preview)` seems to be broken.

@yiliuTo can you help triaging? seems related - https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application/pull/12

**Comment by yiliuTo** [comment]
Thanks @rajeshkamal5050 @weikanglim @v-jiaodi , @fangjian0423 will look into this issue.

**Comment by fangjian0423** [comment]
The root case of this issue is Azure Spring Apps consumption plan tier will create 2 resource groups with same tags, but AZD expect to get only 1 resource group with those tags.

We will output resource group name in out ASA template bicep to resolve it.

**Comment by rajeshkamal5050** [comment]
Thanks @fangjian0423

This also needs the same fix https://github.com/Azure-Samples/ASA-Samples-Web-Application/ ?

**Comment by fangjian0423** [comment]
> Thanks @fangjian0423
> 
> This also needs the same fix https://github.com/Azure-Samples/ASA-Samples-Web-Application/ ?

Correct, maybe all ASA templates need to update, we will handle it.

**Comment by rajeshkamal5050** [comment]
@fangjian0423 @yiliuTo can we get the remaining PR's merged.
- https://github.com/Azure-Samples/ASA-Samples-Event-Driven-Application/pull/27
- https://github.com/spring-guides/gs-spring-boot-for-azure/pull/29
- https://github.com/Azure-Samples/spring-chatgpt-sample/pull/11
