### ISSUE TITLE
[Issue] Issue with new docker output

### ISSUE THREAD

**Issue by rudiv** [Azure/azure-dev#3503]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here: azd version 1.6.1 (commit eba2c978b5443fdb002c95add4011d9e63c2e76f)

**Describe the bug**
Docker output freezes and `azd up` never completes.

The last time I used `azd up` this "Docker output" wasn't present and this issue never presented itself. What's weird is that the output seems to freeze at different points, I've left this running for over an hour and nothing happens.

In contrast, building the docker file (a simple `docker build . -f ./Dockerfile`) completes the build in 2 minutes.

Example freeze point:

```
  ────────────────────────────────── Docker Output ─────────────────────────────────

  #9 10.67 Progress: resolved 217, reused 0, downloaded 198, added 0
  #9 11.67 Progress: resolved 264, reused 0, downloaded 234, added 0
  #9 12.67 Progress: resolved 330, reused 0, downloaded 289, added 0
  #9 13.67 Progress: resolved 356, reused 0, downloaded 306, added 0
  #9 14.67 Progress: resolved 384, reused 0, downloaded 324, added 0
  #9 15.67 Progress: resolved 428, reused 0, downloaded 347, added 0
  #9 16.67 Progress: resolved 511, reused 0, downloaded 402, added 0
  #9 17.64 Progress: resolved 565, reused 0, downloaded 450, added 0

  ─────────────────────────────────
```

and another:
```
  ────────────────────────────────── Docker Output ──────────────────


  #5 [builder 2/7] WORKDIR /app
  #5 CACHED

  #6 [internal] load build context
  #6 transferring context: 238.03MB 4.2s
  #6 transferring context: 369.02MB 5.3s done
  #6 DONE 5.4s

  ────────────────────
```

I've attempted to clear builder cache, a system prune, everything at the docker side that could be causing the issues. They're simply not present when using docker directly.

**To Reproduce**
`azd up`

Obviously it's hard to give reproduction steps, just that this is a long running nodejs docker build (in comparison to say, a .NET container).

**Expected behavior**
It doesn't freeze and actually builds / deploys the image.

**Environment**
This is a NodeJS 20 docker file building on OSX (M1 Ultra).

**Additional context**

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you triage this?

**Comment by rudiv** [comment]
I'm closing this off, things are working now so appeared to (somehow) be an environment issue.
