### ISSUE TITLE
Add support for mapping container volumes in Aspire manifest to Azure Files-backed storage mounts in ACA

### ISSUE THREAD

**Issue by DamianEdwards** [Azure/azure-dev#3515]
Aspire issue dotnet/aspire#1676 is adding support for emitting container volume information to the publishing manifest, e.g.:

```json
{
  "resources": {
    "postgres": {
      "type": "container.v0",
      "connectionString": "Host={postgres.bindings.tcp.host};Port={postgres.bindings.tcp.port};Username=postgres;Password={postgres.inputs.password}",
      "image": "postgres:16.2",
      "volumes": [
        {
          "name": "postgresblah",
          "target": "/blah",
          "readOnly": false
        },
        {
          "target": "/foo",
          "readOnly": false
        }
      ],
   ...
```

These should be mapped to [storage mounts backed by Azure Files shares](https://learn.microsoft.com/azure/container-apps/storage-mounts?pivots=azure-cli#azure-files) when deployed to ACA. For now, each volume should be considered dedicated to that specific container. In the future we might introduce the ability to model volumes as resources themselves in which case they could be shared between different containers.

While both named and anonymous volumes will be emitted to the manifest, I think it only makes sense to support mapping named volumes to Azure Files shares for now, and have AZD log a message or fail with an error if an anonymous volume is detected.

Seems simplest approach to start with would be to create an Azure Storage account resource for the ACA environment (similar to how we create LAWS and ACR resources today) if there are any volumes specified on any containers, and then create an Azure Files share and ACA storage definition for each volume (essentially what [this guide](https://learn.microsoft.com/azure/container-apps/storage-mounts-azure-files) does).

**Comment by mitchdenny** [comment]
What defines the location of the sub path on the file share which maps to the target. Would we have \\fileshare\postgresblah mapping to /blah (in the container) (note I'm using UNC naming here just for disambiguation).

**Comment by DamianEdwards** [comment]
It's always mounted to the root of the file share AFAICT so we'd need a file share per volume.

**Comment by mitchdenny** [comment]
That means you'd need a storage account per volume. That seems extreme.

**Comment by DamianEdwards** [comment]
No, one storage account with multiple Azure Files shares in it. Is that not possible?

**Comment by DamianEdwards** [comment]
From [docs](https://learn.microsoft.com/en-us/azure/storage/files/storage-how-to-use-files-portal?tabs=azure-portal#create-a-storage-account):

> A storage account is a shared pool of storage in which you can deploy an Azure file share or other storage resources, such as blobs or queues. **A storage account can contain an unlimited number of shares**. A share can store an unlimited number of files, up to the capacity limits of the storage account.

**Comment by DamianEdwards** [comment]
We just merged a change to [emit the bind mounts too](dotnet/aspire#2761). Might be interesting to think about an approach we might take to support mapping bind mounts to ACA somehow too (TBC that's lower priority than volume support).
