### ISSUE TITLE
AzureCLI issue remote connection

### ISSUE THREAD

**Issue by JoseIvanHernandez** [Azure/azure-dev#3532]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-dev.commands.cli.provision
Error type: Error
Error Message: ENOPRO: No file system provider found for resource 'vscode-redacted:url

Version: 0.8.1
OS: win32
OS Release: 10.0.26080
Product: Visual Studio Code
Product Version: 1.87.2
Language: en

<details>
<summary>Call Stack</summary>

```
n.j workbench.desktop.main.js:653:14743
async n.exists workbench.desktop.main.js:653:16950
async vscode-file:/workbench.desktop.main.js:1864:2800
```

</details>

**Comment by ellismg** [comment]
@bwateratmsft I'm not really sure what this error is trying to tell us - but it seems to happen on the VS Code side of the house, so maybe your eyes have a better idea as to what is going on here?

**Comment by JoseIvanHernandez** [comment]
It's a learning curve. But I'm slowly getting the hang of this.

**Comment by JoseIvanHernandez** [comment]
Hey there. You are the first person I respond to. Tbh I didn't think anyone on here was real. Anyways. So the reason I was getting that error was because two versions are installed, one older and one new one. Slowly I am getting the hang of these errors. At the moment I am configuring seamless passwords between gCloud's.

**Comment by jongio** [comment]
Okay, thanks.  I'll close this for now.
