### ISSUE TITLE
CLI prints prompts twice

### ISSUE THREAD

**Issue by aarthiem** [Azure/azure-dev#354]
**Describe the bug**
NodeJsMongo template prompted to enter location region to store deployment metadata
"Please enter an Azure region to use to store deployment metadata"

**To Reproduce**
1. Open a terminal and create new directory named "testnodemg"
2. run the command az dev up --template todo-nodejs-mongo
3. enter environment name as tempnodetest, azureregion as eastus, select a subscription, **enter azure region to store metadata** as eastus

**Expected behavior**
Expected cli to prompt user to enter only 3 information Environment Name, Azure Location, Azure Subscription

**Environment**
Information on your environment:
    * Nodejs v16.14.0
    * azd version 0.0.1-beta.368 (commit 18e5243e994490b797c8e9b29aecbdf9c8a8c98a)
    * IDE and version : VS Code
![azdevcli_nodejsmongo_deployerror](https://user-images.githubusercontent.com/61921020/159309290-63a651a8-6044-4d44-9293-ae51467d41b3.jpg)

**Additional context**

**Comment by rajeshkamal5050** [comment]
With all the recent UX changes. I believe the above issues are fixed. cc: @vhvb1989 @Austinauth 

Please re-open if you think otherwise.
