### ISSUE TITLE
[AspireDeployment] azd vs-server crashes after obtaining access token from VS IDE

### ISSUE THREAD

**Issue by anvillan** [Azure/azure-dev#3541]
After implementing VS IDE changes to respond to access token requests from `azd vs-server`, the `azd.exe` process crashes down as soon as any response is sent back. I tried using azd [1.7.0-pr.3589009 (commit 6cbc841e67b18efe7122907fd8a4b50be67989f9)](https://github.com/Azure/azure-dev/pull/3523) build.

Example of response:
`{
  "token": "<access_token_value>",
  "expiresOn": "2024-03-14T22:27:44.528Z",
  "result": "success"
}`

The error shown is an `invalid memory address or nil pointer dereference`:

---
C:\Users\anvillan\source\repos\AspireApp>azd vs-server --cwd . --debug
2024/03/15 08:14:18 main.go:59: azd version: 1.7.0-pr.3589009 (commit 6cbc841e67b18efe7122907fd8a4b50be67989f9)
2024/03/15 08:14:18 main.go:229: using cached latest version: 1.7.0 (expires on: 2024-03-16T14:53:00Z)
2024/03/15 08:14:18 project.go:120: Reading project from file 'C:\Users\anvillan\source\repos\AspireApp\azure.yaml'
2024/03/15 08:14:18 middleware.go:106: running middleware 'debug'
2024/03/15 08:14:18 middleware.go:106: running middleware 'experimentation'
2024/03/15 08:14:18 experimentation.go:42: assignment context: 0g5ad841:76970;
2024/03/15 08:14:18 middleware.go:106: running middleware 'telemetry'
2024/03/15 08:14:18 telemetry.go:38: TraceID: 306c633bbc8d83ff858f82b34205d09f
{"port":51528,"pid":1996,"azd":{"version":"1.7.0-pr.3589009","commit":"6cbc841e67b18efe7122907fd8a4b50be67989f9"}}
2024/03/15 08:20:24 server.go:107: handling rpc InitializeAsync
2024/03/15 08:20:24 server.go:206: handled rpc InitializeAsync in 0s
2024/03/15 08:20:29 telemetry.go:107: Telemetry transmitted in 139.194ms, statusCode: 400
2024/03/15 08:20:29 telemetry.go:107: Items accepted/received: 0/1
2024/03/15 08:20:29 telemetry.go:107: Errors:
2024/03/15 08:20:29 uploader.go:223: failed to transmit item C:\Users\anvillan\.azd\telemetry\20240315T152024_0_3347564897.trn with non-retriable status code 400
2024/03/15 08:21:42 server.go:107: handling rpc GetEnvironmentsAsync
2024/03/15 08:21:42 project.go:120: Reading project from file 'C:\Users\anvillan\source\repos\AspireApp\azure.yaml'
2024/03/15 08:21:42 server.go:206: handled rpc GetEnvironmentsAsync in 16.6457ms
2024/03/15 08:21:42 server.go:107: handling rpc OpenEnvironmentAsync
2024/03/15 08:21:42 project.go:120: Reading project from file 'C:\Users\anvillan\source\repos\AspireApp\azure.yaml'
2024/03/15 08:21:42 container.go:172: 'azd vs-server'command asked for envFlag, but envFlag was not included in cmd.Flags().
2024/03/15 08:21:42 server.go:206: handled rpc OpenEnvironmentAsync in 11.8728ms
2024/03/15 08:21:44 server.go:107: handling rpc LoadEnvironmentAsync
2024/03/15 08:21:44 project.go:120: Reading project from file 'C:\Users\anvillan\source\repos\AspireApp\azure.yaml'
2024/03/15 08:21:44 container.go:172: 'azd vs-server'command asked for envFlag, but envFlag was not included in cmd.Flags().
2024/03/15 08:21:44 server.go:107: handling rpc GetEnvironmentsAsync
2024/03/15 08:21:44 project.go:120: Reading project from file 'C:\Users\anvillan\source\repos\AspireApp\azure.yaml'
2024/03/15 08:21:44 server.go:206: handled rpc GetEnvironmentsAsync in 2.5742ms
2024/03/15 08:21:46 command_runner.go:307: Run exec: 'dotnet msbuild C:\Users\anvillan\source\repos\AspireApp\AspireApp.AppHost\AspireApp.AppHost.csproj --getProperty:IsAspireHost' , exit code: 0
2024/03/15 08:21:46 server_service.go:95: [vWabD4wI/38= spinner] Analyzing Aspire Application (this might take a moment...)
[vWabD4wI/38= spinner] Analyzing Aspire Application (this might take a moment...)
2024/03/15 08:21:48 telemetry.go:107: Telemetry transmitted in 21.4165ms, statusCode: 400
2024/03/15 08:21:48 telemetry.go:107: Items accepted/received: 0/3
2024/03/15 08:21:48 telemetry.go:107: Errors:
2024/03/15 08:21:48 uploader.go:223: failed to transmit item C:\Users\anvillan\.azd\telemetry\20240315T152144_0_1625535420.trn with non-retriable status code 400
2024/03/15 08:21:54 command_runner.go:307: Run exec: 'dotnet run --project AspireApp.AppHost.csproj --publisher manifest --output-path C:\Users\anvillan\AppData\Local\Temp\azd-provision450454868\apphost-manifest.json' , exit code: 0
2024/03/15 08:21:54 server.go:206: handled rpc LoadEnvironmentAsync in 10.3516191s
2024/03/15 08:21:54 server.go:107: handling rpc RefreshEnvironmentAsync
2024/03/15 08:21:54 project.go:120: Reading project from file 'C:\Users\anvillan\source\repos\AspireApp\azure.yaml'
2024/03/15 08:21:54 container.go:172: 'azd vs-server'command asked for envFlag, but envFlag was not included in cmd.Flags().
2024/03/15 08:21:55 command_runner.go:307: Run exec: 'dotnet msbuild C:\Users\anvillan\source\repos\AspireApp\AspireApp.AppHost\AspireApp.AppHost.csproj --getProperty:IsAspireHost' , exit code: 0
2024/03/15 08:21:55 server_service.go:95: [vWabD4wI/38= spinner] Analyzing Aspire Application (this might take a moment...)
[vWabD4wI/38= spinner] Analyzing Aspire Application (this might take a moment...)
2024/03/15 08:21:58 command_runner.go:307: Run exec: 'dotnet run --project AspireApp.AppHost.csproj --publisher manifest --output-path C:\Users\anvillan\AppData\Local\Temp\azd-provision1365460796\apphost-manifest.json' , exit code: 0
2024/03/15 08:21:58 command_runner.go:307: Run exec: 'C:\Users\anvillan\.azd\bin\bicep.exe --version' , exit code: 0
2024/03/15 08:21:58 bicep.go:97: bicep version: 0.25.3
2024/03/15 08:21:58 bicep.go:111: using local bicep: C:\Users\anvillan\.azd\bin\bicep.exe
2024/03/15 08:21:58 telemetry.go:107: Telemetry transmitted in 20.6612ms, statusCode: 400
2024/03/15 08:21:58 telemetry.go:107: Items accepted/received: 0/1
2024/03/15 08:21:58 telemetry.go:107: Errors:
2024/03/15 08:21:58 uploader.go:223: failed to transmit item C:\Users\anvillan\.azd\telemetry\20240315T152154_0_1012758286.trn with non-retriable status code 400
2024/03/15 08:21:59 command_runner.go:307: Run exec: 'dotnet msbuild C:\Users\anvillan\source\repos\AspireApp\AspireApp.AppHost\AspireApp.AppHost.csproj --getProperty:IsAspireHost' , exit code: 0
2024/03/15 08:21:59 manager.go:201: delegating auth to external process
2024/03/15 08:21:59 command_runner.go:307: Run exec: 'dotnet --version' , exit code: 0
2024/03/15 08:21:59 dotnet.go:70: dotnet version: 8.0.300-preview.24122.6
2024/03/15 08:21:59 server_service.go:95: [vWabD4wI/38= spinner] Initialize bicep provider
[vWabD4wI/38= spinner] Initialize bicep provider
2024/03/15 08:22:01 command_runner.go:307: Run exec: 'C:\Users\anvillan\.azd\bin\bicep.exe build C:\Users\anvillan\AppData\Local\Temp\azd-infra1624117193\main.bicep --stdout' , exit code: 0
2024/03/15 08:22:01 manager.go:201: delegating auth to external process
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x929155]

goroutine 255 [running]:
github.com/azure/azure-dev/cli/azd/pkg/auth.(*RemoteCredential).GetToken(0xc00079a640, {0x13560c8, 0xc00017e410}, {{0x0, 0x0}, 0x0, {0xc000041fb0, 0x1, 0x1}, {0x0, ...}})
        github.com/azure/azure-dev/cli/azd/pkg/auth/remote_credential.go:91 +0x775
github.com/azure/azure-dev/cli/azd/pkg/auth.EnsureLoggedInCredential({0x13560c8, 0xc00017e410}, {0x134ab40, 0xc00079a640}, 0xc0003024b0)
        github.com/azure/azure-dev/cli/azd/pkg/auth/manager.go:178 +0x15b
github.com/azure/azure-dev/cli/azd/pkg/auth.(*multiTenantCredentialProvider).GetTokenCredential(0xc00030ade0, {0x13560c8, 0xc00017e410}, {0xc0007e0150, 0x24})
        github.com/azure/azure-dev/cli/azd/pkg/auth/credential_providers.go:49 +0x105
github.com/azure/azure-dev/cli/azd/pkg/tools/azcli.(*UserProfileService).createGraphClient(0xc00031b1e0, {0x13560c8?, 0xc00017e410?}, {0xc0007e0150?, 0xc0007ad180?})
        github.com/azure/azure-dev/cli/azd/pkg/tools/azcli/user_profile.go:41 +0x36
github.com/azure/azure-dev/cli/azd/pkg/tools/azcli.(*UserProfileService).GetSignedInUserId(0x24?, {0x13560c8, 0xc00017e410}, {0xc0007e0150?, 0x24?})
        github.com/azure/azure-dev/cli/azd/pkg/tools/azcli/user_profile.go:55 +0x26
github.com/azure/azure-dev/cli/azd/pkg/azureutil.GetCurrentPrincipalId({0x13560c8, 0xc00017e410}, 0xc00017e410?, {0xc0007e0150, 0x24})
        github.com/azure/azure-dev/cli/azd/pkg/azureutil/principal.go:20 +0x3f
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning.(*principalIDProvider).CurrentPrincipalId(0xc00031b220, {0x13560c8, 0xc00017e410})
        github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/current_principal_id_provider.go:43 +0x192
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).loadParameters(0xc00037f7a0, {0x13560c8, 0xc00017e410})
        github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:1644 +0x222
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).ensureParameters(0xc00037f7a0, {0x13560c8, 0xc00017e410}, {{0xc000617320, 0x5b}, {0xc00000bc67, 0x7}, 0xc000796ab0, 0xc000796b40, 0x0})
        github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:1939 +0xba
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).EnsureEnv(0xc00037f7a0, {0x13560c8, 0xc00017e410})
        github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:168 +0x290
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).Initialize(0xc00037f7a0, {0x13560c8, 0xc00017e410}, {0xc00034e540?, 0xc000273670?}, {{0x11807b9, 0x5}, {0xc0006205c0, 0x38}, {0x117fd1c, ...}, ...})
        github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:118 +0x199
github.com/azure/azure-dev/cli/azd/internal/vsrpc.(*environmentService).refreshEnvironmentAsync(0xc00017e320?, {0x13560c8, 0xc00017e410}, 0xc000514ba0, {0xc0005400a0, 0xa}, {0x4, {0x1358f68, 0xc00009abe0}})
        github.com/azure/azure-dev/cli/azd/internal/vsrpc/environment_service_refresh.go:86 +0x2d8
github.com/azure/azure-dev/cli/azd/internal/vsrpc.(*environmentService).RefreshEnvironmentAsync(0xc00048c9c0, {0x13560c8, 0xc00017e410}, {{0xc000540070?, 0x10?}}, {0xc0005400a0, 0xa}, {0x4, {0x1358f68, 0xc00009abe0}})
        github.com/azure/azure-dev/cli/azd/internal/vsrpc/environment_service_refresh.go:41 +0x97
github.com/azure/azure-dev/cli/azd/internal/vsrpc.(*environmentService).ServeHTTP.HandlerFunc3[...].func7({0x1358f68, 0xc00009abe0}, 0xc00032d158, {0x13566c8, 0xc000122880})
        github.com/azure/azure-dev/cli/azd/internal/vsrpc/handler.go:186 +0x164
github.com/azure/azure-dev/cli/azd/internal/vsrpc.serveRpc.func1.1()
        github.com/azure/azure-dev/cli/azd/internal/vsrpc/server.go:187 +0x673
created by github.com/azure/azure-dev/cli/azd/internal/vsrpc.serveRpc.func1 in goroutine 254
        github.com/azure/azure-dev/cli/azd/internal/vsrpc/server.go:146 +0x48a

---

**Comment by ellismg** [comment]
> Example of response:
> { "token": "<access_token_value>", "expiresOn": "2024-03-14T22:27:44.528Z", "result": "success" }

There was a mismatch between the documentation in external-authentication.md and what the CLI (and VS Code, which also uses this protocol) did.  In the implementation we used the word `status` instead of `result`, but when I wrote the documentation after the fact, I accidently used `result` instead of `status`.

I updated the documentation as part of #3523 and also hardened the way we handle responses so if this field is not set we don't panic and instead return a better error about a malformed response.
