### ISSUE TITLE
[AspireDeployment] Aspire Console C# project fails to deploy

### ISSUE THREAD

**Issue by anvillan** [Azure/azure-dev#3574]
From [[AzureTools][Aspire] Fail to publish Console C# project to Azure Container Apps for .NET Aspire with an error](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1999603/?view=edit):

OS Version: Win11 23H2
Dev17 Build: 17.10 preview 3 main-[34718.169](https://vsdrop.microsoft.com/file/v1/Products/DevDiv/VS/adfab3baccf0ac743a6063f990e7c143e00a79eb/ee0d4794-db06-15d9-5c9e-a5e47fdfb61b%3bbootstrappers/Enterprise/vs_Enterprise.exe) | Enterprise
.NET Aspire: 8.0.0-preview.5.24168.3
Integrated 8.0 SDK: 8.0.300-preview.24122.6
Workload:  ASP.NET and web development/Azure development 
Apply Feed: [dotnet-](https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json)[toolsfeed](https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json) & [dotnet8feed](https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json)
azd Version: 1.8.0-beta.1-daily.3604026

**Repro Steps:**
1. Create a new 8.0 Console C# project.
2. Right click on the project -> Add -> .NET Aspire orchestrator support.
3. Right click on AppHost project -> Publish -> Azure Container Apps for .NET Aspire -> Select a location and type a valid environment name -> Next -> Select service -> Finish -> Close.
4. Publish.
5. Check whether publish successfully.

**Expect:**
Publish successfully.

**Actual:** 
Fail to publish with an error.
![image](https://github.com/Azure/azure-dev/assets/51379759/6356dc4f-a7b3-4925-a147-b7c830290271)

**Comment by rajeshkamal5050** [comment]
@anvillan can you run and share the generated manifest too? `dotnet run --project AspireApp.AppHost\AspireApp.AppHost.csproj --publisher manifest --output-path manifest.json`

**Comment by anvillan** [comment]
@rajeshkamal5050 

Here is the manifest for the C# Console App with Aspire Support:
`{
  "resources": {
    "consoleappaspire": {
      "type": "project.v0",
      "path": "../ConsoleAppAspire/ConsoleAppAspire.csproj",
      "env": {
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES": "true",
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES": "true"
      }
    }
  }
}`

And here is the `debug` output for the deploy attempt:

Build started at 7:39 AM...
========== Build: 0 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========
========== Build completed at 7:39 AM and took 00.493 seconds ==========
3/22/2024 7:39:24 AM: Info 
3/22/2024 7:39:24 AM: Info Provisioning Azure resources (azd provision)
3/22/2024 7:39:24 AM: Info Provisioning Azure resources can take some time.
3/22/2024 7:39:24 AM: Info 
3/22/2024 7:39:24 AM: Info Analyzing Aspire Application (this might take a moment...)
3/22/2024 7:39:28 AM: Info Initialize bicep provider
3/22/2024 7:39:30 AM: Info Reading subscription and location from environment...
3/22/2024 7:39:33 AM: Info Subscription: Name (subscription_Id)
3/22/2024 7:39:33 AM: Info Location: East US
3/22/2024 7:39:33 AM: Info 
3/22/2024 7:39:33 AM: Info Creating a deployment plan
3/22/2024 7:39:33 AM: Info Comparing deployment state
3/22/2024 7:39:45 AM: Info Creating/Updating resources
3/22/2024 7:39:48 AM: Info   You can view detailed progress in the Azure Portal:
3/22/2024 7:39:48 AM: Info   https://portal.azure.com/#view/HubsExtension/DeploymentDetailsBlade/~/overview/id/%2Fsubscriptions%subscription_Id%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2FavcEnvConsole-1711118373
3/22/2024 7:39:48 AM: Info 
3/22/2024 7:39:48 AM: Info   (✓) Done: Resource group: rgGroup
3/22/2024 7:39:59 AM: Info   (✓) Done: Container Registry: acrrob6q2qrxymgm
3/22/2024 7:40:10 AM: Info   (✓) Done: Log Analytics workspace: law-rob6q2qrxymgm
3/22/2024 7:41:04 AM: Info   (✓) Done: Container Apps Environment: cae-rob6q2qrxymgm
3/22/2024 7:41:18 AM: Info 
3/22/2024 7:41:18 AM: Info Deploying services (azd deploy)
3/22/2024 7:41:18 AM: Info 
3/22/2024 7:41:18 AM: Info Deploying service consoleappaspire
3/22/2024 7:41:18 AM: Info Deploying service consoleappaspire (Logging in to registry)
3/22/2024 7:41:18 AM: Info Deploying service consoleappaspire (Pushing container image)
3/22/2024 7:41:22 AM: Info Deploying service consoleappaspire (Updating container app)
3/22/2024 7:41:25 AM: Info   (x) Failed: Deploying service consoleappaspire
3/22/2024 7:41:25 AM: Error failed deploying service 'consoleappaspire': failing invoking action 'deploy', updating container app service: applying manifest: PUT https://management.azure.com/subscriptions/<subscription_Id>/resourceGroups/<rgGroup>/providers/Microsoft.App/containerApps/consoleappaspire

RESPONSE 400: 400 Bad Request
ERROR CODE: InvalidParameterValueInContainerTemplate
{
  "error": {
    "code": "InvalidParameterValueInContainerTemplate",
    "message": "The following field(s) are either invalid or missing. Field 'template.containers.consoleappaspire.image' is invalid with details: 'Invalid value: \"acrrob6q2qrxymgm.azurecr.io/azd-deploy-consoleappaspire-1711118478\": GET https:: MANIFEST_UNKNOWN: manifest tagged by \"latest\" is not found; map[Tag:latest]';."
  }
}

**Comment by rajeshkamal5050** [comment]
@ellismg @weikanglim @vhvb1989 

Is this a good enough manifest for azd to start provisioning resources and deploy apps? If not, can we fail fast with validations prior to provisioning, deployment?

```
{
  "resources": {
    "consoleappaspire": {
      "type": "project.v0",
      "path": "../ConsoleAppAspire/ConsoleAppAspire.csproj",
      "env": {
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES": "true",
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES": "true"
      }
    }
  }
}
```

cc @mitchdenny @davidfowl

**Comment by vhvb1989** [comment]
looks like a valid manifest to me. It is failing to pull the container from the registry...  not sure why.

**Comment by vhvb1989** [comment]
I'm guessing this might be b/c a console application uses `<OutputType>Exe</OutputType>` to describe the project, which might be used by `dotnet publish` to create an exe file, instead of a docker image. Or something related to that.

The only project with `<OutputType>Exe</OutputType>` is the appHost.

This might be not azd related, but Aspire+Docker scenario.

@baronfel

**Comment by baronfel** [comment]
I'd want to see more details about the ACR here - the error message is complaining about pulling the `latest` tag of a specific container image, does that tag actually exist?

**Comment by rajeshkamal5050** [comment]
@vhvb1989 @baronfel 

`dotnet publish` doesn't seem to build/publish container image. Is it because of `console` being an exe as @vhvb1989 was suspecting? or publish command wrong? 

Tried the below to repro.
```
dotnet new console
dotnet publish console.csproj -r linux-x64 -c Release /t:PublishContainer -p ContainerArchiveOutputPath=foo**
MSBuild version 17.9.4+90725d08d for .NET
  Determining projects to restore...
  Restored /Users/rajeshkamal/projects/console/console.csproj (in 169 ms).
  console -> /Users/rajeshkamal/projects/console/bin/Release/net8.0/linux-x64/console.dll
  console -> /Users/rajeshkamal/projects/console/bin/Release/net8.0/linux-x64/publish/
```
```
dotnet new web
dotnet publish web.csproj -r linux-x64 -c Release /t:PublishContainer -p ContainerArchiveOutputPath=foo
MSBuild version 17.9.4+90725d08d for .NET
  Determining projects to restore...
  Restored /Users/rajeshkamal/projects/web/web.csproj (in 206 ms).
  web -> /Users/rajeshkamal/projects/web/bin/Release/net8.0/linux-x64/web.dll
  web -> /Users/rajeshkamal/projects/web/bin/Release/net8.0/linux-x64/publish/
  Building image 'web' with tags 'latest' on top of base image 'mcr.microsoft.com/dotnet/aspnet:8.0'.
  Pushed image 'web:latest' to local archive at '/Users/rajeshkamal/projects/web/foo'.
```

**Comment by baronfel** [comment]
`console` apps need the `EnableSdkContainerSupport` property set to `true` in their project files (or any other valid MSBuild property-setting mechanism) if they aren't using the NuGet package that enables SDK Containers support. We have some docs explaining this [here](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container?pivots=dotnet-7-0#add-nuget-package), but I found a bug in the docs that don't show this section for the .NET 8 version of the docs, so I'll work on that.

**Comment by rajeshkamal5050** [comment]
> console apps need the EnableSdkContainerSupport property set to true in their project files (or any other valid MSBuild property-setting mechanism) if they aren't using the NuGet package that enables SDK Containers support.

Default `dotnet new console` don't have the above property enabled by default. Please do as recommended above.
