### ISSUE TITLE
[Issue] GitHub action warning message setup-azd v0.1.0 is using deprecated Node.js 16

### ISSUE THREAD

**Issue by christiannagel** [Azure/azure-dev#3578]
Using setup-azd@v0.1.0 I get this warning message:

**Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: Azure/setup-azd@v0.1.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.**

May 13th, 2024, Node 20 will be enforced: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/ 

According to this information, node20 is already used (but the warning tells otherwise):
https://github.com/marketplace/actions/setup-azd#usage

I've seen a pull request was already done to update to Node 20:
https://github.com/Azure/setup-azd/pull/87

But the latest release was from an earlier date:
https://github.com/Azure/setup-azd/releases

**Comment by rajeshkamal5050** [comment]
@hemarina should we do another release of setup-azd? Please feel free to pull this into milestones cc @vhvb1989

**Comment by vhvb1989** [comment]
node16 to node20 is a breaking change, see: https://github.com/microsoft/setup-msbuild/issues/125

We need to release a major version
