### ISSUE TITLE
[AspireDeployment] azd vs-server fails to send prompt requests to clients

### ISSUE THREAD

**Issue by anvillan** [Azure/azure-dev#3591]
For an `Environment` that contains an Azure resource that requires user to enter secrets (i.e., Application Insights), calling `IEnvironmentService.RefreshEnvironment()` fails with `Error panic: don't know how to prompt for type *survey.Password`.

Error output:
--
3/25/2024 1:52:14 PM: Error panic: don't know how to prompt for type *survey.Password
goroutine 708 [running]:
github.com/azure/azure-dev/cli/azd/internal/vsrpc.capturePanic(0xc000371b98)
	github.com/azure/azure-dev/cli/azd/internal/vsrpc/handler.go:382 +0x65
panic({0xf35000?, 0xc0000510c0?})
	runtime/panic.go:914 +0x21f
github.com/azure/azure-dev/cli/azd/pkg/input.askOneNoPrompt({0x1367b10?, 0xc0004fc960?}, {0xee2f20?, 0xc000051070?})
	github.com/azure/azure-dev/cli/azd/pkg/input/asker.go:72 +0x3e5
github.com/azure/azure-dev/cli/azd/pkg/input.(*AskerConsole).Prompt.func1(0xc0000003c0)
	github.com/azure/azure-dev/cli/azd/pkg/input/console.go:500 +0x74
github.com/azure/azure-dev/cli/azd/pkg/input.(*AskerConsole).doInteraction(0xc0000003c0, 0xc000370b88)
	github.com/azure/azure-dev/cli/azd/pkg/input/console.go:784 +0x1b0
github.com/azure/azure-dev/cli/azd/pkg/input.(*AskerConsole).Prompt(0xc0000003c0, {0x1191931?, 0x3?}, {{0xc00011cd40, 0x3f}, {0x0, 0x0}, {0x0, 0x0, 0x0}, ...})
	github.com/azure/azure-dev/cli/azd/pkg/input/console.go:499 +0xaa
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.promptWithValidation[...]({0x136adb8?, 0xc000447090}, {0x13757b8, 0xc0000003c0}, {{0xc00011cd40, 0x3f}, {0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep/prompt.go:140 +0x119
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).promptForParameter(0xc0004525a0, {0x136adb8, 0xc000447090}, {0xc000a06750, 0x5}, {{0xc000a06740, 0xc}, {0x0, 0x0}, 0x0, ...})
	github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep/prompt.go:93 +0xbad
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).ensureParameters(0xc0004525a0, {0x136adb8, 0xc000447090}, {{0xc0005fc8a0, 0x5b}, {0xc000a066c8, 0x7}, 0xc000350750, 0xc0003507e0, 0x0})
	github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:2021 +0x876
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).EnsureEnv(0xc0004525a0, {0x136adb8, 0xc000447090})
	github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:168 +0x290
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).Initialize(0xc0004525a0, {0x136adb8, 0xc000447090}, {0xc0006b47e0?, 0xc00060f5d0?}, {{0x1192e38, 0x5}, {0xc0006a5200, 0x38}, {0x119239c, ...}, ...})
	github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:118 +0x199
github.com/azure/azure-dev/cli/azd/internal/vsrpc.(*environmentService).refreshEnvironmentAsync(0xc0001076d0?, {0x136adb8, 0xc000447090}, 0xc000285e00, {0xc00069f8a8, 0x11}, {0xf, {0x136db30, 0xc0001060f0}})
	github.com/azure/azure-dev/cli/azd/internal/vsrpc/environment_service_refresh.go:86 +0x2d8
github.com/azure/azure-dev/cli/azd/internal/vsrpc.(*environmentService).RefreshEnvironmentAsync(0xc0001188d8, {0x136adb8, 0xc000447090}, {{0xc0003e3830?, 0xc00068d910?}}, {0xc00069f8a8, 0x11}, {0xf, {0x136db30, 0xc0001060f0}})
	github.com/azure/azure-dev/cli/azd/internal/vsrpc/environment_service_refresh.go:41 +0x97
github.com/azure/azure-dev/cli/azd/internal/vsrpc.(*environmentService).ServeHTTP.HandlerFunc3[...].func7.1({0x136adb8?, 0xc000447090?}, {{0xc0003e3830?, 0xc00060fc30?}}, {0xc00069f8a8?, 0x10?}, {0xf, {0x136db30, 0xc0001060f0}}, 0x914a7c35c72711d?)
	github.com/azure/azure-dev/cli/azd/internal/vsrpc/handler.go:267 +0xb0
github.com/azure/azure-dev/cli/azd/internal/vsrpc.(*environmentService).ServeHTTP.HandlerFunc3[...].func7({0x136db30, 0xc0001060f0}, 0xc00026eb10, {0x136b3c8, 0xc000396140})
	github.com/azure/azure-dev/cli/azd/internal/vsrpc/handler.go:269 +0x1b3
github.com/azure/azure-dev/cli/azd/internal/vsrpc.serveRpc.func1.1()
	github.com/azure/azure-dev/cli/azd/internal/vsrpc/server.go:187 +0x673
created by github.com/azure/azure-dev/cli/azd/internal/vsrpc.serveRpc.func1 in goroutine 489
	github.com/azure/azure-dev/cli/azd/internal/vsrpc/server.go:146 +0x48a
3/25/2024 1:53:09 PM: Error panic: don't know how to prompt for type *survey.Password
goroutine 844 [running]:
github.com/azure/azure-dev/cli/azd/internal/vsrpc.capturePanic(0xc000307b98)
	github.com/azure/azure-dev/cli/azd/internal/vsrpc/handler.go:382 +0x65
panic({0xf35000?, 0xc000051c50?})
	runtime/panic.go:914 +0x21f
github.com/azure/azure-dev/cli/azd/pkg/input.askOneNoPrompt({0x1367b10?, 0xc000571040?}, {0xee2f20?, 0xc000051c10?})
	github.com/azure/azure-dev/cli/azd/pkg/input/asker.go:72 +0x3e5
github.com/azure/azure-dev/cli/azd/pkg/input.(*AskerConsole).Prompt.func1(0xc000208000)
	github.com/azure/azure-dev/cli/azd/pkg/input/console.go:500 +0x74
github.com/azure/azure-dev/cli/azd/pkg/input.(*AskerConsole).doInteraction(0xc000208000, 0xc000306b88)
	github.com/azure/azure-dev/cli/azd/pkg/input/console.go:784 +0x1b0
github.com/azure/azure-dev/cli/azd/pkg/input.(*AskerConsole).Prompt(0xc000208000, {0x1191931?, 0x3?}, {{0xc0006d6e40, 0x3f}, {0x0, 0x0}, {0x0, 0x0, 0x0}, ...})
	github.com/azure/azure-dev/cli/azd/pkg/input/console.go:499 +0xaa
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.promptWithValidation[...]({0x136adb8?, 0xc000372230}, {0x13757b8, 0xc000208000}, {{0xc0006d6e40, 0x3f}, {0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep/prompt.go:140 +0x119
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).promptForParameter(0xc000453560, {0x136adb8, 0xc000372230}, {0xc00080e2c0, 0x5}, {{0xc00080e2b0, 0xc}, {0x0, 0x0}, 0x0, ...})
	github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep/prompt.go:93 +0xbad
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).ensureParameters(0xc000453560, {0x136adb8, 0xc000372230}, {{0xc0005fc0c0, 0x5b}, {0xc00080e238, 0x7}, 0xc0006183c0, 0xc000618450, 0x0})
	github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:2021 +0x876
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).EnsureEnv(0xc000453560, {0x136adb8, 0xc000372230})
	github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:168 +0x290
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).Initialize(0xc000453560, {0x136adb8, 0xc000372230}, {0xc0005723c0?, 0xc00036d5d0?}, {{0x1192e38, 0x5}, {0xc0006d61c0, 0x38}, {0x119239c, ...}, ...})
	github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:118 +0x199
github.com/azure/azure-dev/cli/azd/internal/vsrpc.(*environmentService).refreshEnvironmentAsync(0xc0001076d0?, {0x136adb8, 0xc000372230}, 0xc00068e5a0, {0xc000016450, 0x11}, {0x14, {0x136db30, 0xc0001060f0}})
	github.com/azure/azure-dev/cli/azd/internal/vsrpc/environment_service_refresh.go:86 +0x2d8
github.com/azure/azure-dev/cli/azd/internal/vsrpc.(*environmentService).RefreshEnvironmentAsync(0xc0001188d8, {0x136adb8, 0xc000372230}, {{0xc0002b8460?, 0xc000294400?}}, {0xc000016450, 0x11}, {0x14, {0x136db30, 0xc0001060f0}})
	github.com/azure/azure-dev/cli/azd/internal/vsrpc/environment_service_refresh.go:41 +0x97
github.com/azure/azure-dev/cli/azd/internal/vsrpc.(*environmentService).ServeHTTP.HandlerFunc3[...].func7.1({0x136adb8?, 0xc000372230?}, {{0xc0002b8460?, 0xc00036dc30?}}, {0xc000016450?, 0x10?}, {0x14, {0x136db30, 0xc0001060f0}}, 0xf00a5632b8060c63?)
	github.com/azure/azure-dev/cli/azd/internal/vsrpc/handler.go:267 +0xb0
github.com/azure/azure-dev/cli/azd/internal/vsrpc.(*environmentService).ServeHTTP.HandlerFunc3[...].func7({0x136db30, 0xc0001060f0}, 0xc000296468, {0x136b3c8, 0xc000690040})
	github.com/azure/azure-dev/cli/azd/internal/vsrpc/handler.go:269 +0x1b3
github.com/azure/azure-dev/cli/azd/internal/vsrpc.serveRpc.func1.1()
	github.com/azure/azure-dev/cli/azd/internal/vsrpc/server.go:187 +0x673
created by github.com/azure/azure-dev/cli/azd/internal/vsrpc.serveRpc.func1 in goroutine 489
	github.com/azure/azure-dev/cli/azd/internal/vsrpc/server.go:146 +0x48a

From VS IDE, the support to respond to HTTP request on `<host>/prompt` was introduced with [External prompting support](https://devdiv.visualstudio.com/DevDiv/_git/WebTools/pullrequest/538123). 

Please note:
 - VS IDE is not receiving any requests at `<host>/prompt`
 - When `azd vs-server` is started, it is initialized with `IServerService.InitializeAsync(string, InitializeOptions, CancellationToken)`, where the `InitializeOptions` parameter only specifies the `AuthenticationEndpoint` and `AuthenticationKey` parameters.
 - No `Environment` variable regarding `prompt` configuration is set when azd vs-server process starts
 - VS IDE expects the `prompt` requests to be done on the same `port` and with the same `auth_key` as with `Auth` requests

I tried using `azd version 1.8.0-beta.1-daily.3630034 (commit cac9e7641f89023a3953057e5a314e62e553dc73)` .

**Comment by rajeshkamal5050** [comment]
Feature supporting this hasn't been merged yet - https://github.com/Azure/azure-dev/pull/3364

**Comment by ellismg** [comment]
I'll make sure we have a test case that has a secret here so we can validate the end to end.
