### ISSUE TITLE
Implement CodeTour for templates

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-dev#362]
Leverage the [VS Code - CodeTour](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour) to orient developers to the template when they are using VS Code.

**Comment by savannahostrowski** [comment]
I was exploring CodeTours on a template and have a prototype here: https://github.com/savannahostrowski/todo-python-mongo-test. I will demo in the next biweekly.

**Comment by savannahostrowski** [comment]
After considering this more deeply, the experience isn't quite right for templates. Closing for now.
