### ISSUE TITLE
[WebToolsE2E][Aspire] For Aspire Starter App projects with redis checked, an error occurs when running ‘azd init’.

### ISSUE THREAD

**Issue by v-reinawang** [Azure/azure-dev#3624]
**REGRESSION INFO**: Not repro on Aspire 8.0 preview 4

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.203
3. Install Aspire 8.0 Preview 5 [8.0.0-preview.5.24179.3]
4. Apply NuGet Feeds.
5. Install azd

**REPRO STEPS**

1. Open Command Prompt, run the following commands to create and build an Aspire application
```
dotnet new aspire-starter --use-redis-cache -o aspirestarter
cd aspirestarter
dotnet build
```
2. Runing 'azd init', select 'Use code in the current directory' > Confirm and continue initializing my app > select 'apiservice' and 'webfrontend', type a new environment name, press enter

**ACTUAL**
ERROR: configuring ingress for resource cache: binding for does not specify a container port, ensure WithServiceBinding for this resource specifies a hostPort value
![image](https://github.com/Azure/azure-dev/assets/109339894/b3098c9b-db19-4786-9faf-17aaf5143313)

**EXPECTED**
'azd init' can be run successfully.
![image](https://github.com/Azure/azure-dev/assets/109339894/e7900855-98cb-42af-a113-19e9c2160249)

**Comment by v-polly** [comment]
This issue also reproduce on Mac arm64 with .NET 8.0.204 April Servicing SDK + Aspire 8.0 Preview 5 [8.0.0-preview.5.24179.3] installed.
![image](https://github.com/Azure/azure-dev/assets/88425944/f579c19e-8f85-49de-b543-4bb8506adad6)

**Comment by balachir** [comment]
@rajeshkamal5050 can we have someone investigate, please?

**Comment by rajeshkamal5050** [comment]
@vhvb1989 this should be addressed by https://github.com/Azure/azure-dev/pull/3612 ?

**Comment by vhvb1989** [comment]
Yes, @rajeshkamal5050  #3612 has the fix for the breaking change

**Comment by balachir** [comment]
@rajeshkamal5050 @vhvb1989 I tried using [this script](https://github.com/Azure/azure-dev/blob/main/cli/installer/README.md#download-from-daily-builds) to get the latest azd to verify this fix. The script is installing version 1.8.0-beta.1-daily.3649348, which was the same version of azd when we opened this issue. Is there a newer version of azd available and how can I get it? Thanks!

**Comment by vhvb1989** [comment]
@balachir , azd's daily has an issue.  We're working on it. The daily version you are getting is old.

**Comment by vhvb1989** [comment]
@balachir , azd daily build is ready now.  You can run the script the get the latest and test.

**Comment by v-reinawang** [comment]
Verify that this issue has been fixed in the latest build.
