### ISSUE TITLE
`azd up` does not accept flags for subscription and location

### ISSUE THREAD

**Issue by bwateratmsft** [Azure/azure-dev#3626]
`azd up` will prompt for subscription and location, but does not have flags for passing them in to avoid CLI prompts

**Comment by jongio** [comment]
I'll take this.

**Comment by bwateratmsft** [comment]
TIL that `init` has subscription and location args (even though it doesn't normally ask those questions). I _think_ this should be sufficient for now, I'll keep investigating and reopen this if we still need something.
