### ISSUE TITLE
Consider adding a note about troubleshooting for the blog

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#3635]
This idea came during morning stand up. @kristenwomack suggested to have some notes for forks about how `auth logout` and `auth login` unblocks users after a recent change to subscription roles (like the one that happened to the Playground subscription not so long ago).

We have a troubleshoot section on azd's official docs: https://learn.microsoft.com/azure/developer/azure-developer-cli/troubleshoot

Should we add the note in the troubleshoot and then either keep a constant footer at the end of each release blog post about this troubleshoot page?, or at least mention it from time to time when there might be new entries in the troubleshoot docs?

**Comment by rajeshkamal5050** [comment]
We already had this section - https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/troubleshoot?tabs=Browser#updated-azure-account-permissions-do-not-refresh-in-azd

**Comment by kristenwomack** [comment]
@gkulin added a link at the end of the blog post. Marking this complete.
