### ISSUE TITLE
todo-nodejs-mongo-aks - page loading error - ensure environment variable

### ISSUE THREAD

**Issue by zhangjiale-64** [Azure/azure-dev#3643]
**Describe the issue:**
Test `todo` templates. Run `azd up`, get error as follow:
![image](https://github.com/Azure/azure-dev/assets/141405558/0ffc3357-e72d-488d-b3d4-351719a1af13)

**Repro Step:**
1. Login in with command: `azd auth login`.
2. Execute command: `azd init todo-java-mongo-aca --branch staging` .
4. Run `azd up` .
5. Click the web service endpoint after the deployment completed. And you will see this error.

**Environment:**

- Template: `todo-java-mongo-aca` `todo-nodejs-mongo-aca` ` todo-python-mongo-terraform` 
- OS: Windows
- Azd version: azd version 1.8.0-beta.1-daily.3649348 (commit 85f86be69c647f62cab6f5e42988d19df8bff03f)

**Expected behavior:**
Run `azd up`, click the web service endpoint after the deployment, and the web page can be opened successfully. 

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you take a look?

**Comment by vhvb1989** [comment]
Unable to reproduce.
See `todo-java-mongo-aca` deployed with `azd up` from staging branch:  https://ca-web-c6wtjxjsxo4qw.mangosand-f0fe86a6.eastus2.azurecontainerapps.io/

@zhangjiale-64 can you try again and provide more details?

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 @danieljurek This issue also occurs in Azd Sovereign Cloud Manual Test:


- OS:  Windows desktop
- Template: `todo-nodejs-mongo-aks`
- Branch: `staging`
- Azd version: 1.9.0-beta.1-daily.3739055  (commit https://github.com/Azure/azure-dev/commit/36bf68c04125bfd9d91e097fbabad9602ff113f6)

**Comment by zedy-wj** [comment]
Repro in aks related template.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 any fixes needed for `todo-nodejs-mongo-aks` template? similar to https://github.com/Azure/azure-dev/pull/3671 and https://github.com/Azure/azure-dev/pull/3171

@zedy-wj @v-jiaodi doesn't happen on other clouds?

**Comment by v-jiaodi** [comment]
@rajeshkamal5050 This issue also occurs on other clouds.
> @rajeshkamal5050 @danieljurek This issue also occurs in Azd Sovereign Cloud Manual Test:
> 
> * Template: `todo-nodejs-mongo-aks`
> * Branch: `staging`
> * Azd version: 1.9.0-beta.1-daily.3739055  (commit [36bf68c](https://github.com/Azure/azure-dev/commit/36bf68c04125bfd9d91e097fbabad9602ff113f6))

**Comment by v-xuto** [comment]
@rajeshkamal5050 In the latest round of azd manual testing (1.9.2), this issue still exists.

**Comment by Menghua1** [comment]
@rajeshkamal5050 @danieljurek This issue also occurs in azd manual testing, this issue still exists:

- OS: Windows, DevContainer
- Template: todo-nodejs-mongo-aks
- Branch: staging
- Azd version: `azd version 1.10.0-beta.1-daily.4086794 (commit 9445b193c91acfa2d4bcae129cb7471ecc101e11)`
