### ISSUE TITLE
Web app cannot load properly after running `azd up`

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#3644]
**Describe the issue:**
Test `todo-csharp-cosmos-sql` and `todo-nodejs-mongo` template on  Azure China and US Gov Cloud. Run `azd up`, click the web link, get error as follow：
![image](https://github.com/Azure/azure-dev/assets/80496810/a6c30b36-edcd-43ad-8041-fbefef5d4014)

**Repro Steps:**

1. Login in with command: `azd auth login`.
2. Execute command: `azd init -t todo-nodejs-mongo -b staging`.
3. Run `azd up`.
4. Click web link.

**Environment:**

- Cloud: Azure China and US Gov Cloud.
- Template: `todo-nodejs-mongo` and `todo-csharp-cosmos-sql`.
- Azd version : 1.8.0-beta.1-daily.3661089  (commit https://github.com/Azure/azure-dev/commit/d078aeb7cf1497aa7c8d629d2f6d434554e0cd9a)

**Expected behavior:**
Run `azd up` and the app can load properly.

@danieljurek   for notification.

**Comment by rajeshkamal5050** [comment]
@danieljurek can you take a look?

**Comment by vhvb1989** [comment]
same as: https://github.com/Azure/azure-dev/issues/3646
