### ISSUE TITLE
Fail to start api 

### ISSUE THREAD

**Issue by NanaXiong00** [Azure/azure-dev#3647]
**Describe the issue:**
When `start api and web`, start api have an error occurs, get error as follow：
![image](https://github.com/Azure/azure-dev/assets/138103031/0a0d4f14-a285-4154-b39d-f6636f65b794)

**Repro Steps:**
1. Login in with command: `azd auth login`
2. Execute command: `azd init -t <template> -b staging`
3. Run `azd up`
4. Run task: `start api and web`

**Environment:**
- Template: todo-python-mongo-aca, todo-python-mongo
- OS: Codespace, Linux
- Azd version: 1.8.0-beta.1-daily.3661089 (commit d078aeb7cf1497aa7c8d629d2f6d434554e0cd9a)

**Expected behavior:**
Start api and web can pass.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you take a look?

**Comment by rajeshkamal5050** [comment]
@NanaXiong00 there were fixes made around starting api and web. Can you test and see if this still reproduces?

**Comment by NanaXiong00** [comment]
> @NanaXiong00 there were fixes made around starting api and web. Can you test and see if this still reproduces?

Based on testing with the latest code, the issue no longer exists and has been closed.

**Comment by zedy-wj** [comment]
Reproducing in `Linux`.
Does not reproduce in `codespace`.

template: todo-python-mongo
azd version 1.9.0-beta.1-daily.3717409 (commit aae980c37780689be67b10e472f496d432e5f5a5)

**Comment by NanaXiong00** [comment]
The above problems still exist in the latest test, and the following errors appear when opening the web page:
![image](https://github.com/user-attachments/assets/0142bba6-3421-4925-8144-44e455f4f7ce)
**Environment:**
- Template: todo-python-mongo
- Branch: staging
- OS: Codespace
- Azd version: azd version 1.10.0-beta.1-daily.4028971 (commit b801642c3deafeda7866c1159bcd4a6ae2539556)

**Comment by Menghua1** [comment]
This issue cannot be reproduced in the tests in the past few months. I will close this issue.
