### ISSUE TITLE
Regression for dockerfile.v0 - ingress - targetPort

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#3649]
After https://github.com/Azure/azure-dev/pull/3484, azd is using `0` as the `targetPort` for containerApps coming from dockerfile.v0.

**Comment by rajeshkamal5050** [comment]
Should address these issues reported by manual testing team right?
- https://github.com/dotnet/aspire-samples/issues/178
- https://github.com/dotnet/aspire-samples/issues/179
