### ISSUE TITLE
Incorporate language frameworks into azd

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-dev#365]
JavaScript, Python, and static web apps, have many popular frameworks, e.g. Express, FastAPI, Hugo, that help developers get started building applications. Each of the frameworks has their own distinct way of configuring, building, and deploying their solutions. In many scenarios, these frameworks are the starting point for developers. We will need to determine a subset of language frameworks to "devify" as way to simplify deploying these solutions on Azure. 

For Phase 1, we'll need to select one or two language frameworks for each language. Within these, we will look at the popular example applications and select one or two of these examples. In addition, we'll also do the same with static web apps, e.g. Gatsby, Hugo. Although these are JavaScript, they are not the same kind of thing as an Express or FastAPI app. 

## Phase 1 
Fork & devify existing language framework solution
Azure/azure-dev-pr#505,  Azure/azure-dev-pr#506, & Azure/azure-dev-pr#508 

## Phase 2 
Track & manage changed to the community framework solutions
(link to epic)

## Phase 3
Automatically "devify" a solution based on a supported template
(link to epic)

**Comment by savannahostrowski** [comment]
I'm going to close this for now in favour of having individual items as demand arises.
