### ISSUE TITLE
Deploying function code after a provision requires a delay/recheck

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-dev#366]
Comment from @ellismg.

When I was writing the automated tests for the function deployment I noticed there was a delay between the provision and being able to deploy to the function.

This isn't _great_ (the check code itself and the need for the check) so we should take a look and see if we can improve this. 

If anything it'd be nice to use an API to do the check, rather than just continually launching and failing in the CLI since we don't differentiate failures there so we could be retrying on something _very_ silly.

_Originally posted by @ellismg in https://github.com/Azure/azure-dev/pull/460#r795976155_

**Comment by rajeshkamal5050** [comment]
We haven't recently seen this lately. Please re-open if it happens again.
