### ISSUE TITLE
[Issue] Helm deployments

### ISSUE THREAD

**Issue by pauldotyu** [Azure/azure-dev#3668]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here: 

```
azd version 1.7.0 (commit 49d6adc2efb178083f61822e6b4715258560803d)
```

**Describe the bug**
When deploying an app to AKS hosts via the new Helm Chart repo/release support in AZD, I feel that the deployment process should not attempt to deploy vanilla K8s manifests unless explicitly configured to do so.  

**To Reproduce**
- Configure a `service` with `host` set to **aks** and add a valid helm repository and release.
- Add a manifests folder in the root of repo and add any valid or invalid k8s manifest
- AZD will run the helm install command then attempt to run manifests in the `manifests` directory 

**Expected behavior**
If a user configures the service to deploy via helm repo, that should be it. Once the [`helmDeployed` variable has been set to true](https://github.com/Azure/azure-dev/blob/bafa6c446ad9b07e391ccbef2ff2f29c8c03cc73/cli/azd/pkg/project/service_target_aks.go#L236), no other deployments should occur IMO unless explicitly set to deploy from kustomize or manifests.

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

**Comment by wbreza** [comment]
@pauldotyu  Thanks for the feedback.  Can you expand more on your use case where you have both helm charts and vanilla k8s manifests but you don't want the vanilla manifests actually deployed?

**Comment by wbreza** [comment]
Deploying vanilla manifests in addition to helm charts is a feature of `azd`.  For example, if you are developing your own application you may want to take dependencies on helm charts to spin up resources from 3rd party registries.  At the same time you may then want to deploy your own custom application outside of helm for your custom resources and depend on those 3rd party components.

Right now, the recommendation would be to move your manifests outside of the default `manifests` folder or considering create different repos/branches to showcase the different variations/configurations of your application.
