### ISSUE TITLE
Support local development using services behind firewall 

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-dev#367]
Some services (like Azure SQL) are not exposed to the internet by default. When developing an application that uses Azure SQL a firewall rule needs to be manually added to allow remote access. 

It would be nice if azd was able to simplify this scenario somehow. One way might be to have a well-known parameter name `DEV_EXTERNAL_IP` and use it to conditionally populate the firewall rules in local dev scenarios.

**Comment by rajeshkamal5050** [comment]
Closing this in favor of #1142
