### ISSUE TITLE
Use Oryx rather than local builds for Node.js and Python apps

### ISSUE THREAD

**Issue by fiveisprime** [Azure/azure-dev#368]
I've noticed that I can run the CLI on WSL, so I setup my Windows side to support everything and I immediately noticed two things:

* My API build failed because of CRLF
* The build and deploy took a while compared to running the build in Oryx

This appears to be a conscious decision since `SCM_DO_BUILD_DURING_DEPLOY` is disabled. We've spent a lot of effort optimizing Oryx for node/python builds and that should be taken advantage of here as well.

**Comment by weikanglim** [comment]
Revisiting this stale issue... I'm not sure about the historical context here, but the current state is that:

For python:
1. azd creates its own dictated python venv
1. azd installs requirements.txt
2. azd does a zipDeploy with the zipped source dir (excluding venv and __pycache__), with `SCM_DO_BUILD_DURING_DEPLOY=true` for Oryx to build

For node:
1. azd runs `npm install`
2. azd runs `npm run build`
3. azd does a zipDeploy with the `dist` dir, with `SCM_DO_BUILD_DURING_DEPLOY=true`, but artifacts are already built locally.

I believe that some of this were to enable local dev scenarios. But there is opportunity to speed up deploy times for node/python - appservice if we were interested about those efforts (at the cost of less local dev validation).

**Comment by rajeshkamal5050** [comment]
@weikanglim @fiveisprime closing based on above comment. Feel free to reopen if anything specific is pending here.
