### ISSUE TITLE
[WebToolsE2E][Aspire] Running "azd init" to initialize Metrics solution fails with error: "unsupported resource type: executable.v0".

### ISSUE THREAD

**Issue by v-sherryfan** [Azure/azure-dev#3686]
**REGRESSION INFO:** Worked on Aspire 8.0.0-preview.4.24156.9

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 3 [ Includes Aspire 8.0.0-preview.5.24201.12 and SDK 8.0.300-preview.24203.14 ]
3. Install Docker Desktop for Windows
4. Install latest azd [1.9.0-beta.1-daily]

**REPRO STEPS**

1. Clone aspire-samples repo
2. Update sdk version to 8.0.300-preview.24203.14 in global.json
3. Open samples\Metrics.sln
4. Build
5. Deploy using azd
    - Open the solution folder in a Command Prompt
    - Runing 'azd init', select 'Use code in the current directory' > Confirm and continue initializing my app, type a new environment name, press enter

**ACTUAL**
ERROR: unsupported resource type: executable.v0
![image](https://github.com/Azure/azure-dev/assets/71361488/c87abf78-e97f-4ada-9bce-eab0b1d22f45)

**EXPECTED**
![image](https://github.com/dotnet/eShop/assets/71361488/c5ea6756-d7be-425d-9b7d-655aa8d6dd70)

**Comment by davidfowl** [comment]
This isn't an azd issue.
