### ISSUE TITLE
[Issue] azd putting wrong port in connection string

### ISSUE THREAD

**Issue by eerhardt** [Azure/azure-dev#3690]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

```
❯ azd version
azd version 1.9.0-beta.1-daily.3686742 (commit 2c8ee2a5ba0591dcdf6b54e4566e6795b3d795d3)
```

**Describe the bug**
When using the Qdrant component in .NET Aspire with azd, other services aren't getting the correct endpoint to talk to a qdrant container. The problem is that the connection string contains the "target" port

![image](https://github.com/Azure/azure-dev/assets/8291187/2e0b757c-9e6e-4ffd-b5cc-17b86a711afd)

however, the `qdrant` service is exposing port `80` and `443` for its primary endpoint. So to make this work, I need to remove the port from this connection string in order to make the app work.

**To Reproduce**
Steps to reproduce the behavior...

1. `azd init; azd up` this app: https://github.com/dotnet/aspire/tree/main/playground/Qdrant
    - add `.WithExternalHttpEndpoints()` to the apiservice so it can be hit extenrally.
3. After it is deployed, hit the `/create` and `/search` endpoints on the resulting apiservice app. 

**Expected behavior**
You should see 3 movies be returned from the search. The app should be working.

cc @ellismg 

**Aspire manifest**

The current manifest is:

```json
{
  "resources": {
    "qdrant": {
      "type": "container.v0",
      "connectionString": "Endpoint={qdrant.bindings.grpc.scheme}://{qdrant.bindings.grpc.host}:{qdrant.bindings.grpc.port};Key={qdrant-Key.value}",
      "image": "docker.io/qdrant/qdrant:v1.8.3",
      "volumes": [
        {
          "name": "qdrant-data",
          "target": "/qdrant/storage",
          "readOnly": false
        }
      ],
      "env": {
        "QDRANT__SERVICE__API_KEY": "{qdrant-Key.value}",
        "QDRANT__SERVICE__ENABLE_STATIC_CONTENT": "0"
      },
      "bindings": {
        "grpc": {
          "scheme": "http",
          "protocol": "tcp",
          "transport": "http",
          "targetPort": 6334
        },
        "http": {
          "scheme": "http",
          "protocol": "tcp",
          "transport": "http",
          "targetPort": 6333
        }
      }
    },
    "apiservice": {
      "type": "project.v0",
      "path": "../Qdrant.ApiService/Qdrant.ApiService.csproj",
      "env": {
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES": "true",
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES": "true",
        "OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY": "in_memory",
        "ASPNETCORE_FORWARDEDHEADERS_ENABLED": "true",
        "ConnectionStrings__qdrant": "Endpoint={qdrant.bindings.grpc.scheme}://{qdrant.bindings.grpc.host}:{qdrant.bindings.grpc.port};Key={qdrant-Key.value}",
        "ConnectionStrings__qdrant_http": "Endpoint={qdrant.bindings.http.scheme}://{qdrant.bindings.http.host}:{qdrant.bindings.http.port};Key={qdrant-Key.value}",
        "services__qdrant__http__0": "{qdrant.bindings.http.url}"
      },
      "bindings": {
        "http": {
          "scheme": "http",
          "protocol": "tcp",
          "transport": "http",
          "external": true
        },
        "https": {
          "scheme": "https",
          "protocol": "tcp",
          "transport": "http",
          "external": true
        }
      }
    },
    "qdrant-Key": {
      "type": "parameter.v0",
      "value": "{qdrant-Key.inputs.value}",
      "inputs": {
        "value": {
          "type": "string",
          "secret": true,
          "default": {
            "generate": {
              "minLength": 22,
              "special": false
            }
          }
        }
      }
    }
  }
}
```

However, I plan on making 2 changes to the Aspire side:

1. Change the binding to be `Endpoint={qdrant.bindings.grpc.url};Key={qdrant-Key.value}`
1. Change the 'grpc' transport to 'http2'.

**Comment by ellismg** [comment]
In our expression evaluator when pulling properties for a binding we say that `.port` and `.targetPort` mean the same thing.  I suspect that we want `port` to mean the external port and `targetPort` is the port exposed on the container.

We should have `.url` use the external port, not the internal port.

**Comment by eerhardt** [comment]
> and targetPort is the port exposed on the container.

I believe "targetPort" is the term Aspire uses for the internal port.

> `/// <param name="targetPort">This is the port the resource is listening on. If the endpoint is used for the container, it is the container port.</param>`

https://github.com/dotnet/aspire/blob/58ceb834c15595e20083f327a1791e9997e3be1c/src/Aspire.Hosting/ResourceBuilderExtensions.cs#L445

cc @davidfowl @karolz-ms @reubenbond

**Comment by ellismg** [comment]
> I believe "targetPort" is the term Aspire uses for the internal port.

Right - and from the linked documentation it seems like `port` if it is in the manifest should be the external port (i.e. the port other services use when talking to this service).  The logic in `azd` seems wrong here since are using `port` in a binding expression to mean the same thing as `targetPort` which is not true in general.

**Comment by davidfowl** [comment]
To be clear on the things that need to be fixed:
1. When you reference additional a binding mapped to any TCP ports in ACA ingress, it must not use the FQDN in the host. So in the above example, {qdrant.bindings.grpc.host} should resolve to qdrant.{FQDN}, while {qdrant.bindings.http.host} should resolve to qdrant. This is because the first http binding gets mapped to ingress and the second gets mapped to an additional port.
2. The other issue is that when a binding has been mapped to http ingress, the port should be 80 and https 443. The target port should be whatever was specified or inferred by azd.

**Comment by vhvb1989** [comment]
fixed with https://github.com/Azure/azure-dev/pull/3735
