### ISSUE TITLE
[Issue] azd not installed correctly on mac m1 dev container for 

### ISSUE THREAD

**Issue by dfberry** [Azure/azure-dev#3707]
Azd doesn't work in dev container - this worked a week or two ago. It works if I run in on mac without dev container. 

```
azd: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by azd)
```

- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

**Describe the bug**

```
node ➜ /workspaces/cloud-infra (main) $ git log
commit 866a837edc72bb90c1c050317ebb424f027f1dc0 (HEAD -> main, origin/main, origin/HEAD)
Author: azure-sdk <azuresdk@microsoft.com>
Date:   Tue Apr 9 16:30:11 2024 +0000

    Synchronize repo from Repoman

commit 4aff7739b2e5bd1bfdcf495af1d58b32315a8e8d
Author: azure-sdk <azuresdk@microsoft.com>
Date:   Tue Mar 12 18:42:55 2024 +0000

node ➜ /workspaces/cloud-infra (main) $ azd auth login
azd: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by azd)
azd: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by azd)
```

**To Reproduce**

1. Clone to local mac m1 14.3.1 (23D60)
2. Open in vscode and then open dev container
3. azd commands return error

**Expected behavior**

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**
![image](https://github.com/Azure/azure-dev/assets/1517008/7f068f08-455d-4c39-95cf-d2e9e8f50ed7)

**Comment by pamelafox** [comment]
I'm seeing this as well after a fresh rebuild without cache.

**Comment by rajeshkamal5050** [comment]
@danieljurek can you take a look?

**Comment by danieljurek** [comment]
What is the `image` of the devcontainer?

**Comment by dfberry** [comment]
```
{
    "name": "Azure Developer CLI",
    "image": "mcr.microsoft.com/devcontainers/javascript-node:20-bullseye",
    "features": {
        "ghcr.io/devcontainers/features/docker-in-docker:2": {
        },
        "ghcr.io/azure/azure-dev/azd:latest": {}
    },
    "customizations": {
        "vscode": {
            "extensions": [
                "dbaeumer.vscode-eslint",
                "esbenp.prettier-vscode",
                "GitHub.vscode-github-actions",
                "ms-azuretools.azure-dev",
                "ms-azuretools.vscode-azurefunctions",
                "ms-azuretools.vscode-bicep",
                "ms-azuretools.vscode-docker",
                "ms-vscode.js-debug",
                "ms-vscode.vscode-node-azure-pack"
            ]
        }
    },
    "forwardPorts": [
        3000,
        3100
    ],
    "postCreateCommand": "",
    "remoteUser": "node",
    "hostRequirements": {
        "memory": "8gb"
    }
}
```

**Comment by danieljurek** [comment]
I was able to reproduce the issue on an Apple Silicon mac. Previous releases *did* run successfully in this container but the current version is failing. I expect it to run properly. 

Also, the current version does successfully run in other aarch64 containers (e.g. `ubuntu:latest`).

I suspect that this kind of error is related to a `CGO` compiler configuration and it's possible that this error is coming from a regression in the compile configs for ARM64 Linux owing to a recent migration of our engsys.

**Comment by danieljurek** [comment]
@dfberry -- I have a PR with a fix... You can try running this locally as well. 

I just verified that `azd version` works as expected using this build from the `mcr.microsoft.com/devcontainers/javascript-node:20-bullseye` container on an apple silicon mac. 

```bash
curl -fsSL https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3748/install-azd.sh | bash -s -- --base-url https://azuresdkreleasepreview.blob.core.windows.net/azd/standalone/pr/3748 --version '' --verbose --skip-verify
```

**Comment by dfberry** [comment]
@danieljurek Works for me. Thank you for the quick fix. 

![image](https://github.com/Azure/azure-dev/assets/1517008/64a41e72-8b46-4ff5-8cdf-a30aa032cf9f)

**Comment by dfberry** [comment]
@danieljurek This is appearing again. 

1) New clone of https://github.com/Azure-Samples/todo-nodejs-mongo-aca 
2) Azd auth login fails

![image](https://github.com/Azure/azure-dev/assets/1517008/cf13f419-4dfa-4237-9c8b-f9c62947918f)

**Comment by danieljurek** [comment]
Reopening. This seems like a caching issue as installing azd directly int the devcontainer succeeds. I'm able to reproduce locally.

**Comment by dfberry** [comment]
Ok - an easy fix while waiting is to just install azd yourself. 

```bash
curl -fsSL https://aka.ms/install-azd.sh | bash
```

**Comment by rajeshkamal5050** [comment]
Implemented via PR,
- https://github.com/Azure/azure-dev/pull/3748 - CGO disabled for Linux builds eliminates GLIBC compatibility issues.

Closing, please feel free to reopen if the issue persists.
