### ISSUE TITLE
[Issue] Need support for OneDeploy for azd deploy of Python functions

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#3708]
I am trying to port our functions azd templates to use user-assigned managed identity instead of keys to access the storage account. Unfortunately, it is a current limitation that linux-based functions cannot use managedidentity when deployed via the zipdeploy that azd uses. That limitation is fixed in the Flex consumption plan (currently in preview), in the "OneDeploy" system.

Please add support for OneDeploy to azd so that we can port our Python functions templates to use managed identity instead of keys.

Thanks!

**Comment by pamelafox** [comment]
Note: It's possible to script the deployment step if absolutely necessary:
https://github.com/mcollier/function-app-python-event-hub-managed-identity-sample/blob/azdify/azd-publish.sh#L28

That would be a lot of complexity to add to our many simple Python azd templates, however, so I would like to avoid going down that route if possible.

**Comment by paulyuk** [comment]
Note, if anyone is reading this and needs a solution *today, please see the work Michael did here to script the combination of `azd provision` plus additional az commands to do an upload of the zip package, with runfrompackage=url (effectively sidestepping zip deploy): https://github.com/mcollier/function-app-python-event-hub-managed-identity-sample/tree/azdify

**Comment by pamelafox** [comment]
Lol, jinx! Thanks @paulyuk

**Comment by pamelafox** [comment]
Ah yes, I think I searched for OneDeploy when filing the issue and didn't see that. Feel free to merge this one as dupe.
