### ISSUE TITLE
[azd] Separate template fetch from init into its own command: generate (proposal)

### ISSUE THREAD

**Issue by robconery** [Azure/azure-dev#371]
Currently the `init` command does two things: creates the `azure` directory with default settings as well as handling the template logic, which includes:

 - evaluating the passed in name
 - directory check (if empty)
 - fetching and unzipping

I propose we reduce the complexity of `init` and move the template logic to a new command: `generate`. This follows what other frameworks do (namely Rails and Express among others). With a dedicated `generate` command, we could build something more interactive and friendly, including showing the end user what's available for each language/template.

**Comment by rajeshkamal5050** [comment]
@weikanglim is looking into https://github.com/Azure/azure-dev/issues/135 and https://github.com/Azure/azure-dev/issues/705. These will cover the above ask of generating/creating template skeletons.
