### ISSUE TITLE
[Issue] Incorrect line number reported from failed bicep deployment

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/azure-dev#3716]
**Output from `azd version`**
Run `azd version` and copy and paste the output here:
`azd version 1.8.0 (commit 8246323c2472148288be4b3cbc3c424bd046b985)`

**Describe the bug**
The error message `InvalidTemplate: Deployment template validation failed: 'The template resource '[format('{0}/{1}', parameters('resourceNames').sqlServer, 'mydatabase')]' at line '1' and column '648' is not valid:` does not report the correct line number.

**To Reproduce**
Sample code shown in PR to highlight difference between bicep starter template and the changes made to reproduce the issue https://github.com/KSchlobohm/azd-bug-repros/pull/1/files

1. git clone https://github.com/KSchlobohm/azd-bug-repros.git
2. cd azd-bug-repros
3. git checkout kschlobohm/azd-error-line-1
4. `azd env new`
5. `azd provision`

**Expected behavior**
The expected line number in the error message should be relative to the bicep file. In this scenario the error is from file `application-resources.bicep` line 14.

**Environment**
Used the dev container located in the repository to run from VS Code

**Additional context**
Encountered the error across multiple versions of AZD including version 1.3.0 for this specific repro.

**Comment by KSchlobohm** [comment]
Was also able to reproduce this issue by submitting a bad deployment to azure.

1. azd init the bicep starter template
2. copy+paste the resourcegroup in the main.bicep file adding
```bicep
resource rgHub 'Microsoft.Resources/resourceGroups@2021-04-01' = {
  name: !empty(resourceGroupName) ? resourceGroupName : '${abbrs.resourcesResourceGroups}${environmentName}'
  location: location
  tags: tags
}
```

observe the error is reported as:
```
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: InvalidTemplate
--------------------------------------------------------------------------------
{
  "error": {
    "code": "InvalidTemplate",
    "message": "Deployment template validation failed: 'The resource 'Microsoft.Resources/resourceGroups/rg-bugtest240417v3' at line '1' and column '5586' is defined multiple times in a template. Please see https://aka.ms/arm-syntax-resources for usage details.'.",
    "additionalInfo": [
      {
        "type": "TemplateViolation",
        "info": {
          "lineNumber": 1,
          "linePosition": 5586,
          "path": "properties.template.resources[0]"
        }
      }
    ]
  }
}
```

**Comment by weikanglim** [comment]
@KSchlobohm I think this may be a result of the server reporting the line number in the compiled ARM template JSON, and not the Bicep file...

**Comment by weikanglim** [comment]
Did some digging -- this is being tracked by the Bicep team as https://github.com/Azure/bicep/issues/855
