### ISSUE TITLE
[Issue] bicep version packaged with azd is outdated

### ISSUE THREAD

**Issue by nianton** [Azure/azure-dev#3759]
**Output from `azd version`**
Run `azd version` and copy and paste the output here: azd version 1.8.0 (commit 8246323c2472148288be4b3cbc3c424bd046b985)

**Describe the bug**
I am using in my infra deployment some of the newer features of bicep (e.g. user defined functions which are no longer an experimental feature), my bicep CLI and az CLI are both upgraded to the current latest (0.26.170), but my ``azd up`` or ``azd provision`` commands fail to compile my template, even though I can do so without any errors via az CLI or bicep CLI.

**Expected behavior**
The deployment should proceed without errors -use the packaged bicep executable only as a fallback when the necessary toolset is not installed on the host environment.

**Environment**
Information on your environment:
- az CLI v2.59.0
- bicep CLI v0.26.170

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can we bump the bicep cli version?
