### ISSUE TITLE
Azd assumes that projects can only be used once 

### ISSUE THREAD

**Issue by davidfowl** [Azure/azure-dev#3761]
There are scenarios where the same projec can be used as a template for multiple resources. Running azd infra synth produces a single manifest for the project instead of one per resource:

```c#
var builder = DistributedApplication.CreateBuilder(args);

var pg = builder.AddPostgres("pg");
var db = pg.AddDatabase("db");

var api0 = builder.AddProject<Projects.WebApplication1>("api0", launchProfileName: null)
   .WithHttpEndpoint(name:"http");

builder.AddProject<Projects.WebApplication1>("api")
     .WithEnvironment(context =>
     {
         context.EnvironmentVariables["PG_TP"] = pg.Resource.PrimaryEndpoint.Property(EndpointProperty.TargetPort);
         context.EnvironmentVariables["API0_TP"] = api0.GetEndpoint("http").Property(EndpointProperty.TargetPort);
     });

builder.Build().Run();
```

This should generate 3 container apps but it generates 2 manifests.

**Comment by rajeshkamal5050** [comment]
@ellismg Not sure if this will be fixed as part of the container resources refactoring from Bicep to YAML. 

Marking it as a post 8.0/GA follow-up item @davidfowl

**Comment by ellismg** [comment]
Should be fixed by https://github.com/Azure/azure-dev/pull/3800 which writes manifests in a centralized folder (under the app host) named by their aspire resource name.
