### ISSUE TITLE
When “start api and web”, the web page console reports an error

### ISSUE THREAD

**Issue by jerryshia** [Azure/azure-dev#3764]
**Describe the issue:**
When `start api and web`, after clicking the web url, an error occurs in the page console. The error is as follows:
![image](https://github.com/Azure/azure-dev/assets/139106314/8868ae8f-9690-4fc1-88fa-8d80d38ae175)

**Repro Steps:**

1. Login in with command: `azd auth login`
2. Execute command: `azd init -t <template> -b staging`
3. Run `azd up`
4. Run task: `start api and web`
5. Click the web url to enter the page
6. Open the web page console

**Environment:**

- Template: todo-python-mongo-terraform / todo-csharp-sql-swa-func / todo-nodejs-mongo-aca / todo-nodejs-mongo-swa-func / todo-python-mongo-aca /  todo-java-mongo
- OS: Windows Linux CodeSpace
- Azd version: azd version 1.9.0-beta.1-daily.3717409 (commit aae980c37780689be67b10e472f496d432e5f5a5)

**Expected behavior:**
When start api and web, the web page runs successfully.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you take a look?

**Comment by v-xuto** [comment]
@rajeshkamal5050 In the latest round of azd manual testing (1.9.2), this issue still exists.

- Templates+OS: todo-nodejs-mongo-aca, todo-csharp-sql-swa-func
- OS: Linux
- Branch: staging
- Azd version: azd version 1.10.0-beta.1-daily.3792048 (commit 13a7dd52710daa4ac5f0c17be6a77244005ac76e)

**Comment by vhvb1989** [comment]
Tried to repro with `todo-nodejs-mongo-aca` but couldn't repro. It worked as expected

![image](https://github.com/Azure/azure-dev/assets/24213737/3e70b88c-dcff-489e-b9e4-c9ce888aadd3)

**Comment by Menghua1** [comment]
@rajeshkamal5050 In the latest round of azd manual testing, this issue still exists.

- Templates+OS: todo-nodejs-mongo-aca, todo-csharp-sql-swa-func
- OS: Linux
- Branch: staging
- Azd version: `azd version 1.10.0-beta.1-daily.4086794 (commit 9445b193c91acfa2d4bcae129cb7471ecc101e11)`
