### ISSUE TITLE
Terraform templates failed to execute `azd up`

### ISSUE THREAD

**Issue by zhangjiale-64** [Azure/azure-dev#3765]
**Describe the issue:**
Test `todo-nodejs-mongo-terraform` and `todo-python-mongo-terraform` templates on Azure China and US Gov Cloud. Run `azd up`, get error as follow :
![image](https://github.com/Azure/azure-dev/assets/141405558/f9fc3e21-891d-4ac0-8d9f-115a8ab48331)

**Repro Steps:**

1. Login in with command: `azd auth login`.
2. Execute command: `azd init --template <repositoryPath> --branch staging`.
3. Run `azd up`.

**Environment:**

- Cloud: Azure China and US Gov Cloud.
- Template: `todo-nodejs-mongo-terraform` and `todo-python-mongo-terraform`.
- Azd version : 1.9.0-beta.1-daily.3717409 (commit aae980c37780689be67b10e472f496d432e5f5a5)

**Expected behavior:**
Run `azd up` can pass.

@danieljurek for notification.

**Comment by danieljurek** [comment]
These issues are related to the templates. Terraform attempts to register all supported providers on execution. I suspect that new resource providers have been added to `azurerm` as terraform appears to hang as it attempts to register providers and eventually fails. The provider name can be different in each error message depending on what is registered.


https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_provider_registration -- 

> The Azure Provider will automatically register all of the Resource Providers which it supports on launch (unless opted-out using the skip_provider_registration field within the provider block).

To fix this, one can set `skip_provider_registration = "true"` in `infra/provider.tf` and provisioning will succeed. 

```terraform
provider "azurerm" {
  skip_provider_registration = "true"
  features {
    ...
```

**Comment by zhangjiale-64** [comment]
> These issues are related to the templates. Terraform attempts to register all supported providers on execution. I suspect that new resource providers have been added to `azurerm` as terraform appears to hang as it attempts to register providers and eventually fails. The provider name can be different in each error message depending on what is registered.
> 
> https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_provider_registration --
> 
> > The Azure Provider will automatically register all of the Resource Providers which it supports on launch (unless opted-out using the skip_provider_registration field within the provider block).
> 
> To fix this, one can set `skip_provider_registration = "true"` in `infra/provider.tf` and provisioning will succeed.
> 
> ```terraform
> provider "azurerm" {
>   skip_provider_registration = "true"
>   features {
>     ...
> ```
@rajeshkamal5050  According to this comment. This issue will no longer be reproduced and we will close this issue.

**Comment by danieljurek** [comment]
This change should be put into our terraform templates.
