### ISSUE TITLE
 When `start api and web`, an error occurred in the console

### ISSUE THREAD

**Issue by zhangjiale-64** [Azure/azure-dev#3766]
**Describe the issue:**
When `start api and web`,  get error as follow：
![image](https://github.com/Azure/azure-dev/assets/141405558/11d7be22-d14a-43b5-9dd9-f3de7b688783)

**Repro Steps:**

1. Login in with command:` azd auth login`
2. Execute command: `azd init -t <template> -b staging`
3. Run `azd up`
4. Run task: `start api and web`

**Environment:**

- Template: `todo-python-mongo-terraform`, `todo-python-mongo-swa-func`
- OS: Windows, Mac
- Azd version: 1.9.0-beta.1-daily.3717409 (commit aae980c37780689be67b10e472f496d432e5f5a5)

**Expected behavior:**
Start api and web can pass.

@rajeshkamal5050 for notification.

**Comment by v-xuto** [comment]
@rajeshkamal5050 In the latest round of azd manual testing (1.9.2),  this issue still exists.

- Template: todo-python-mongo-terraform
- Branch: staging
- Azd version: azd version 1.10.0-beta.1-daily.3792048 (commit 13a7dd52710daa4ac5f0c17be6a77244005ac76e)

**Comment by Menghua1** [comment]
This issue cannot be reproduced in the tests in the past few months. I will close this issue.
