### ISSUE TITLE
Unable to use "DB for PostgreSQL flexible server" service connector with azd-provisioned container application

### ISSUE THREAD

**Issue by godefroi** [Azure/azure-dev#3772]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
```
azd version 1.8.0 (commit 8246323c2472148288be4b3cbc3c424bd046b985)
```

**Describe the bug**
Deploying an application through `azd publish` seems to wipe out the `AZURE_POSTGRESQL_CONNECTIONSTRING` environment variable which is created by the "DB for PostgreSQL flexible server" service connector. Further (though likely unrelated to this project), re-running the `az containerapp connection create` command (which creates the service connector) wipes out some of the tags on the `azd`-managed resource group; specifically, the `azd-env-name` and `azd-service-name` tags, which are needed for `azd publish` to work without re-provisioning.

**Environment**
Information on your environment:
    * `azd` command-line interface, `azd-init@1.8.0` template
    * Single server ("api") using the `containerapp` host, `dotnet` language, and building using a "standard" two-stage `Dockerfile` (Oryx fails to build the project).

**Additional context**

**Comment by weikanglim** [comment]
@godefroi Thanks for taking the time to log the feedback! I believe you may be running into [IaC limitations with Service Connector](https://learn.microsoft.com/en-us/azure/service-connector/known-limitations#limitations-to-infrastructure-as-code-iac). 

A brief explanation: Service connector is modifying the resources outside of the Bicep infrastructure-as-code files. When `azd provision` runs, it would update the resources to match the declaration in the Bicep files, which would not have the service connector modifications captured. Likewise, it's possible that using the service connector to create the connection string updates the existing resources and drops the tags like you mentioned.

To connect your app to Postgres, you may need to update the Bicep files to pass along the database connection information. There are different ways to do this, and it also depends whether you're using managed identities or not. I'm happy to provide more information here.

**Comment by godefroi** [comment]
> To connect your app to Postgres, you may need to update the Bicep files to pass along the database connection information.

@weikanglim That's what I ended up doing. It would be nice if this functionality played nicely together, through I believe it seems to be more an issue with the Service Connector than with `azd`, as you noted. I think this issue can be closed.
