### ISSUE TITLE
Scenario: As a developer, I want to ensure that all deployed resources conform with my organization's policy

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-dev#378]
Create a base policy set that defines the best practices for a given resource type, e.g. encryption at rest. Apply these when the resources are deployed. 

> Use Azure Policy to ensure deployments comply with company standards
> Overview of Azure Policy - Azure Policy | Microsoft Docs
> https://docs.microsoft.com/en-us/azure/governance/policy/overview
> - Prevent deploying resources that do not comply with company security policy (e.g. VMs with RDP or SSH enabled ports)
> - prevent deploying resources in 1 resource group to multiple regions or to business approved regions (e.g. Azure Gov)

**Comment by savannahostrowski** [comment]
I think some of this will become relevant with ADE work in Gallium

**Comment by savannahostrowski** [comment]
Closing this in favour of #1113
