### ISSUE TITLE
Hooks don't run when deploying from package

### ISSUE THREAD

**Issue by TWolversonReply** [Azure/azure-dev#3784]
**Output from `azd version`**

azd version 1.8.0 (commit 8246323c2472148288be4b3cbc3c424bd046b985)

**Describe the bug**

`azd deploy (service name) --from-package (package name)` doesn't run the predeploy/postdeploy hooks related to that service. I can't see any reason why it shouldn't, and this is a problem for a scenario of ours.

**Comment by rajeshkamal5050** [comment]
@wbreza can you take a look?

**Comment by wbreza** [comment]
@TWolversonReply I am not able to reproduce this error.  Can you provide more details of your configuration of your `azure.yaml` file?

- Which host are you deploying to? App Service, Container App, etc?
- Sounds like you are configuring your hooks to run just for a service, can you show your config?

In my test I used a container app and verified that any pre/post deploy hooks are running as expected.
