### ISSUE TITLE
AZD Env Refresh Error: Bicep File Not Found Despite Previous Successful Cross-Repo Provisioning

### ISSUE THREAD

**Issue by maacaro** [Azure/azure-dev#3787]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.8.1 (commit 88369c36ce2a0d60794389aad9b10de938f587e1)

**Describe the bug**
 the error during the environment refresh process in Azure DevOps (AZD) and the specific problem with the Bicep file not being found, which contrasts with previous behavior when cross-repository infrastructure definitions were successfully handled

**To Reproduce**
Clone the main repository that contains the infrastructure and initial configuration
Authenticate with Azure:
`az login`
Deploy the infrastructure and services as defined in the repository:
`azd up`
Clone the Child Repository
git clone https://github.com/Azure/gpt-rag-ingestion
go to the gpt-rag-ingestion root folder
cd gpt-rag-ingestion
Authenticate and Refresh Environment
`az login`
`azd env refresh`

**Expected behavior**
it run without error as previously does 

**Current behavior**
it get this error:
``` batch

Refreshing environment develop-clew (azd env refresh)


ERROR: initializing provisioning manager: failed to compile bicep template: failed running bicep build: exit code: 1, stdout: , stderr: An error occurred reading file. Could not find file 'patht-to-my-local/gpt-rag-ingestion/infra/main.bicep'.
```

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**

**Comment by weikanglim** [comment]
@maacaro Thanks for reporting this. This likely regressed in the latest build 1.8.1, I'd recommend staying and documenting to users to stay on 1.8.0 in the meantine. We'll get this fixed shortly.
