### ISSUE TITLE
[Issue] azd provision successfully fails, unable to deploy

### ISSUE THREAD

**Issue by ebaker-sogeti** [Azure/azure-dev#3826]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
PS C:\Users\ebaker\source\repos\policyapi60> azd version
azd version 1.8.2 (commit 14600c7a54edac4f54397413f8638431f5c16327)

**Describe the bug**
`azd provision` fails after creating infra as outlined with the message: "ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: failed getting environment outputs: failed getting latest deployment: failed to find latest deployment"

The infra has been provisioned and appears in Azure Portal. AZD CLI also reports 
  (✓) Done: Deploying dev center environment
before showing the ERROR above.

PS C:\Users\ebaker\source\repos\policyapi60> azd deploy

ERROR: infrastructure has not been provisioned. Run `azd provision`

Running a second time appears to work.

**To Reproduce**
Set up to use a devcenter
I could provide the environment template as a zip if necessary
`azd init`
`azd provision`

**Expected behavior**
I am able to `azd deploy` after I provision and provision does not return an error message

**Environment**
AZD CLI, Visual Studio 2022 Preview

**Additional context**
This was working perfectly last week without issue, seems to have started yesterday, or possible mid-last week.

**Comment by ebaker-sogeti** [comment]
Additionally, I uninstalled 1.8.2 and reinstalled 1.8.0 and the same process works this time.

All resources provision per the portal, and `azd deploy` works right after - steps after uninstalling 1.8.2:

PS C:\Users\ebaker\source\repos> powershell -ex AllSigned -c "Invoke-RestMethod 'https://aka.ms/install-azd.ps1' -OutFile 'install-azd.ps1'; ./install-azd.ps1 -Version '1.8.0'"
PS C:\Users\ebaker\source\repos> azd auth login
Logged in to Azure.
PS C:\Users\ebaker\source\repos> azd config set platform.type devcenter
PS C:\Users\ebaker\source\repos> mkdir policyapi61
PS C:\Users\ebaker\source\repos> cd policyapi61
PS C:\Users\ebaker\source\repos\policyapi61> azd init

Initializing an app to run on Azure (azd init)

? How do you want to initialize your app? Select a template
? Select a project template: WebAPI
  (<<redacted>>)


  (✓) Done: Initialized git repository
  (✓) Done: Downloading template code to: C:\Users\ebaker\source\repos\policyapi61

? Enter a new environment name: [? for help] 61-dev

? Enter a new environment name: 61-dev
? Select a project: PolicyAPI

SUCCESS: New project initialized!
PS C:\Users\ebaker\source\repos\policyapi61> azd provision

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

? Select an environment type: Dev
? Enter a value for Location eastus2
  (✓) Done: Creating devcenter environment 61-dev

  You can view detailed progress in the Azure Portal: <<redacted>>

  (✓) Done: App Service plan: plan-<<redacted>>
  (✓) Done: Log Analytics workspace: log-<<redacted>>
  (✓) Done: Key Vault: kv-<<redacted>>
  (✓) Done: Application Insights: appi-<<redacted>>
  (✓) Done: Portal dashboard: dash-<<redacted>>
  (✓) Done: App Service: app-api-<<redacted>>
  (✓) Done: Deploying dev center environment

SUCCESS: Your application was provisioned in Azure in 5 minutes 9 seconds.
You can view the resources created under the resource group policyapi-61-dev in Azure Portal:<<redacted>>

**Comment by rajeshkamal5050** [comment]
@wbreza can you take a look?
