### ISSUE TITLE
[Issue] azd provision is provisioning two connections that point to same AOAI resource causing issues

### ISSUE THREAD

**Issue by lebaro-msft** [Azure/azure-dev#3831]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
daily - this is the aistudio integration work that was recently merged.

**Describe the bug**
azd provision is provisioning two connections that point to same AOAI resource causing issues.
it should NOT be provisioning the Default_AzureOpenAI connection at all.

**To Reproduce**
azd provision or azd up the starter template for aistudio

**Expected behavior**
A single aoai-connection should be created as part of provisioning.

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**
**This is a //build requirement.**

**Comment by wbreza** [comment]
Resolved in AI Studio starter template
