### ISSUE TITLE
vs-code: Consider reworking initial prompt for From Code vs From Template

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#3844]
Today when you run the `azd init` flow via the VS Code extension, the prompt we give includes options for both starting from existing code, starting from a third party template and then a list of all the templates from Awesome AZD.

In practice, the "Start from existing code" can get lost among a sea of options (since we have so many templates) causing folks to think they are in the wrong place.

It might be better to present two options first:

1. Start from a code
2. Start from a template

And then if you pick (2) we show the template list (and the option to use an external one).

**Comment by rajeshkamal5050** [comment]
@bwateratmsft do you think we can make this enhancement for Build?

@kristenwomack

**Comment by bwateratmsft** [comment]
@rajeshkamal5050 yes, we can do that. I'll get to work on it. Do we want to release it for //Build or is it enough to just get it checked in?

**Comment by rajeshkamal5050** [comment]
> @rajeshkamal5050 yes, we can do that. I'll get to work on it. Do we want to release it for //Build or is it enough to just get it checked in?

Thanks @bwateratmsft for the quick fix. Feedback came as part of the build demo (aspire, C# Dev Kit, VSCode Azd extension) discussion. Will be good to release it.

We can do a `VSCode extension release` along with `azd 1.9.0`(May/7) or the next one `azd 1.9.1`(May/14).
