### ISSUE TITLE
[Issue] `package` hooks order

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-dev#3855]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

```bash
pwsh> azd version                                                                                                                                                                       
azd version 1.8.2 (commit 14600c7a54edac4f54397413f8638431f5c16327)
```

**Describe the bug**

Currently, both `prepackage` and `postpackage` hooks are run after the `up` hook and before the provisioning step.

Can we run both `package` hooks after the `postprovision` hook and before the `predeploy` hook so that we can apply results to the deployment step, which are taken from the provisioning?

Here's an example:

I'd like to get a URL of a provisioned resource and update a `config.json` of a frontend app to be deployed to Static Web App. It's not possible to update `config.json` because the `prepackage` hook occurs before the provisioning step.

As a workaround, I have to run the `predeploy` hook script to update the `config.json` file.

As long as it's a plain JSON file, it's OK. However, if we need to compile binaries, the package hooks should be run in between provisioning and deployment instead of before provisioning, which makes more sense to me.

**To Reproduce**

N/A

**Expected behavior**

I was expecting that the package step would occur after the provisioning. However, it actually occurred before the provisioning.

**Environment**

Information on your environment:
- OS: Windows 11

**Comment by justinyoo** [comment]
The `prepackage` hook doesn't even get invoked if I run `azd provision`.

**Comment by rajeshkamal5050** [comment]
@justinyoo have you take a look at [customizable azd up workflow](https://devblogs.microsoft.com/azure-sdk/azure-developer-cli-azd-february-2024-release/#customizable-azd-up-workflow).

**Comment by justinyoo** [comment]
@rajeshkamal5050 Thanks for the link! I found it a few days back and applied it to mine.
