### ISSUE TITLE
Azd duplicates location parameter

### ISSUE THREAD

**Issue by davidfowl** [Azure/azure-dev#3857]
Creating any azure resource and setting the location results in duplicate location parameters.

AppHost

```C#
using Aspire.Hosting.Azure;

var builder = DistributedApplication.CreateBuilder(args);

builder.AddAzureStorage("storage")
    .WithParameter(AzureBicepResource.KnownParameters.Location, "westus2")
    .AddBlobs("blob");

builder.Build().Run();
```

Bicep

```bicep
module storage 'storage/storage.module.bicep' = {
  name: 'storage'
  scope: rg
  params: {
    location: location
    location: 'westus2'
    principalId: resources.outputs.MANAGED_IDENTITY_PRINCIPAL_ID
    principalType: 'ServicePrincipal'
  }
}
```

We should override the default, not duplicate the parameter. This goes for any known parameter that azd understands.

**Comment by vhvb1989** [comment]
> This goes for any known parameter that azd understands.

For azd, the list of known parameters are:

```
	knownParameterKeyVault      string = "keyVaultName"
	knownParameterPrincipalId   string = "principalId"
	knownParameterPrincipalType string = "principalType"
	knownParameterPrincipalName string = "principalName"
	knownParameterLogAnalytics  string = "logAnalyticsWorkspaceId"
```

`location` was considered a hardcoded parameter.  I will fix azd to check if the AppHost is setting a value for. It is currently the only affected 


Note: setting the location directly will produce a warning:

![image](https://github.com/Azure/azure-dev/assets/24213737/1c728e10-023a-4d98-9e19-a9302af681ad)

@davidfowl , ideally, we should be adding a bicep param with default value and assigning it to the bicep param:

like:
![image](https://github.com/Azure/azure-dev/assets/24213737/10f04667-6951-4543-9881-06e9893b0169)

I was trying to do something like:
```csharp
var pp = new ParameterResource("storageLocation", r => "eastus" );

builder.AddAzureStorage("storage")
    .WithParameter(AzureBicepResource.KnownParameters.Location, pp)
    .AddBlobs("blob");

```

But I didn't find a way to actually set a default value for the parameter.  Is there an API for that?

**Comment by davidfowl** [comment]
We don't have a way to set the default value for a parameter yet. But in playing around with this I found another related bug:

```C#
using Aspire.Hosting.Azure;

var builder = DistributedApplication.CreateBuilder(args);

var location = builder.AddParameter("location");

builder.AddAzureStorage("storage")
    .WithParameter(AzureBicepResource.KnownParameters.Location, location);

builder.Build().Run();
```

Since we already have an implicit parameter named location this tries to override it and conflicts in multiple places.

cc @mitchdenny
