### ISSUE TITLE
ToDo React App Takes a Long Time to Load Locally

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#388]
Right now when you run the app locally, it takes a very long time to spin up.

1. What is causing that?
1. Can we trim number of packages?
1. Should we move away from fluent?

**Comment by savannahostrowski** [comment]
@jongio  Is this still true?

cc: @rajeshkamal5050

**Comment by jongio** [comment]
@v-xuto - Can you measure the time it takes to run the react app locally?

**Comment by v-xuto** [comment]
> @v-xuto - Can you measure the time it takes to run the react app locally?

@jongio We tested several templates, and it takes about 50~60s to start the web app locally.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



Templates | Start web app (second)
-- | --
Todo-python-mongo | 50~60s
Todo-java-mongo-aca | 90~100s
Todo-csharp-sql | 50~60s
Todo-nodejs-mongo-swa-func | 50~60s



</div>


</body>

</html>

**Comment by jongio** [comment]
Thank you, that seems acceptable and much better.
