### ISSUE TITLE
[Issue] error 404 when using winget to install this package

### ISSUE THREAD

**Issue by Robertblazor** [Azure/azure-dev#3883]
When type in the following command

'''winget install Microsoft.Azd '''

It shows the error of the following

<img width="407" alt="image" src="https://github.com/Azure/azure-dev/assets/96743273/7473ecc8-a941-4fa7-9dd6-21f4e9f02c6f">

**Comment by albx** [comment]
I've got the same error.
I tried both update Microsoft.Azd via winget and uninstall and then trying to re-install but the command fails with 404 response

**Comment by danieljurek** [comment]
Thanks for reporting @Robertblazor and @albx ... I see this happening locally. Checking now .

**Comment by albx** [comment]
> ## Workaround
> To work around for now, you can run the PowerShell install script:
> 
> ```powershell
> powershell -nop -c "Invoke-RestMethod 'https://aka.ms/install-azd.ps1' | Invoke-Expression"
> ```

Just tried out the workaround. It works! :)

**Comment by Robertblazor** [comment]
It is working around, but I would recommend the winget to be back on.

**Comment by danieljurek** [comment]
WinGet has fixed the issue in the short term: https://github.com/microsoft/winget-pkgs/pull/152946 so `winget install Microsoft.Azd` now works again.
