### ISSUE TITLE
[AzureTools][Aspire] No error message when executing "azd init" for an Aspire starter project with an existing profile

### ISSUE THREAD

**Issue by v-mengwe** [Azure/azure-dev#3884]
**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** 17.10.0 Preview 8.0 [34908.200.d17.10]
**Aspire Version:** 8.0.0
Apply NuGet Feeds
**azd Version:** 1.10.0-beta.1-daily.3772744

**REPRO STEPS:**
1. Create an Aspire starter project -> Publish -> Azure Container Apps for .Net Aspire -> Create a new profile.
2. Right-click solution > Open folder in file explorer -> In the opened folder, right-click any place > open in terminal -> Runing 'azd init'.

**Expect:**
Output an error message “ERROR: environment already initialized to #profilename”.
![image](https://github.com/Azure/azure-dev/assets/62053665/0295261a-e2c5-4b8c-b1e9-7b4b4ec3e776)

**Actual:**
No error message.
![image](https://github.com/Azure/azure-dev/assets/62053665/dd1c6667-3ca8-428a-aedc-8a8c6d5cdbc4)

**More Info:**
1. This issue also **reproduces** for azd 1.9.0.
2. This issue **doesn't reproduce** for azd 1.7.0-beta.1-daily. 3519922.

**Comment by weikanglim** [comment]
@v-mengwe This is expected behavioral change. VS now initializes the `azd` project inside the AppHost directory.

The validation step should be changed to:
1.  Right-click solution > Open folder in file explorer -> **Change directory to app host directory** -> In the opened folder, right-click any place > open in terminal -> Runing 'azd init'.

Which you should get an error.

**Comment by v-mengwe** [comment]
Make sense, the error message pops up when running 'azd init' on app host directory. Thanks for the guidance.
