### ISSUE TITLE
[docs] Improve documentation about pipeline config

### ISSUE THREAD

**Issue by gkulin** [Azure/azure-dev#3887]
[Configure a pipeline and push updates](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/configure-devops-pipeline?tabs=GitHub) should be clearer that you have to create the azure-dev.yaml yourself if it doesn't already exist. It should also mention the new features with pipeline variables.

We can also improve the [Configure a CI/CD pipeline for your template](https://learn.microsoft.com/en-us/training/modules/deploy-configure-azure-developer-cli-template/5-configure-pipeline?source=recommendations) unit in azd's training module

**Comment by jongio** [comment]
@gkulin With #4030 we now ask the user to add the default azure-dev.yml file if they don't already have it.    should we close this issue?

**Comment by pamelafox** [comment]
Can you adjust that error message to also look for .yaml? It error'ed on me, presumably because I use .yaml, but apparently .yaml is the preferred extension from the YAML creator, so that's what I've been using.

Alternatively, I change all my repos to yml.

**Comment by gkulin** [comment]
closed via https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/5814 

will open another issue for the error message
