### ISSUE TITLE
[WebToolsE2E] After successfully deploying a webapp project using azd, I get an error when opening any container app: "No registered resource provider found for location 'eastus2' and API version '2024-02-02-preview' for type 'managedEnvironments/dotNetComponents'."

### ISSUE THREAD

**Issue by v-sherryfan** [Azure/azure-dev#3892]
**REGRESSION INFO:** Also repro on azd 1.8.2 and 1.9.0

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.300
3. Install Docker Desktop for Windows
4. Install azd version [1.10.0-beta.1-daily.3772744]

**REPRO STEPS**

1. Open CMD, create and deploy a mvc project using following code 
    ```
    dotnet new mvc -o mvc
    cd mvc
    azd init
    azd up
    ```
2. After deployment successful, open the resource group in Azure Portal and then go to any Container App
![image](https://github.com/Azure/azure-dev/assets/71361488/5fe9f133-b1c3-4677-a8cb-8f2a4a1cd681)

**ACTUAL**

No registered resource provider found for location 'eastus2' and API version '2024-02-02-preview' for type 'managedEnvironments/dotNetComponents'. The supported api-versions are '2023-11-02-preview, 2024-02-02-preview'. The supported locations are 'northcentralusstage, westus2, southeastasia, swedencentral, canadacentral, westeurope, northeurope, eastus, eastus2, eastasia, australiaeast, germanywestcentral, japaneast, uksouth, westus, centralus, northcentralus, southcentralus, koreacentral, brazilsouth, westus3, francecentral, southafricanorth, norwayeast, switzerlandnorth, uaenorth, canadaeast, westcentralus, ukwest, centralindia, italynorth, polandcentral, centraluseuap, eastus2euap'.
![image](https://github.com/Azure/azure-dev/assets/71361488/f8f40d26-9e71-4315-8498-c4b03ed824f9)

**EXPECTED**

No errors when opening any container app

**Comment by rajeshkamal5050** [comment]
> This error message does not have any function impact, and we have fixed it, let us know if anyone still see the issue.

This isn't an azd issue. Something on ACA service which seems to have been fixed. Also, the flow isn't Aspire its azd's simplified/easy init detecting .NET services/projects.

**Comment by Rita003** [comment]
Not repro on azd version 1.10.0-beta.1-daily.3787247 + 17.10 GA (include aspire 8.0.0)
