### ISSUE TITLE
Fail to run `azd up` with `todo-python-mongo-terraform`

### ISSUE THREAD

**Issue by zhangjiale-64** [Azure/azure-dev#3893]
**Describe the issue:**
Test `todo-python-mongo-terraform` template on DevContainer. Run `azd up`, get error as follow:
![image](https://github.com/Azure/azure-dev/assets/141405558/69cb44f1-5a32-4a07-8443-21efa842bc3b)

**Repro Steps:**
1. Login in with command: `azd auth login`, `az login`
2. Execute command: `azd init -t todo-python-mongo-terraform -b staging`
3. Run `azd up`

**Environment:**

1. Template: `todo-python-mongo-terraform`
2. OS: DevContainer
3. Azd version : azd version 1.10.0-beta.1-daily.3777186 (commit e4a70d0e5141de8c2823ae88bc053a311ef3d7c1)

**Expected behavior:**
Run `azd up` can pass.

@rajeshkamal5050 for notification.

**Comment by wbreza** [comment]
The default SKU for the app service plan is running on a `B1`.  This is the lowest and is having a hard time starting up in a decent amount of time.  I would recommend that we upgrade the SKU to at least `B2` for all Python based templates.

**Comment by zhangjiale-64** [comment]
> The default SKU for the app service plan is running on a `B1`. This is the lowest and is having a hard time starting up in a decent amount of time. I would recommend that we upgrade the SKU to at least `B2` for all Python based templates.

@rajeshkamal5050 According to this comment. This issue will no longer be reproduced.
