### ISSUE TITLE
Failed to deploy services when running `azd up` on Azure China

### ISSUE THREAD

**Issue by zhangjiale-64** [Azure/azure-dev#3899]
**Describe the issue:**
Test `todo-csharp-cosmos-sql` and `todo-java-mongo` templates on Azure China. Run `azd up` , get error as follow:
![image](https://github.com/Azure/azure-dev/assets/141405558/0759b66c-d72b-4d9b-bd56-728494a84fea)
The api and web have actually been deployed successfully. But this error appears on the terminal unexpectedly.
![image](https://github.com/Azure/azure-dev/assets/141405558/69e25631-a4c7-49e3-bb27-4e9b49fd7586)

**Repro Step:**

1. Login in with command: `azd auth login`.
2. Execute command: `azd init --template <repositoryPath> --branch staging`.
3. Run `azd up`.

**Environment:**

1. Cloud: Azure China.
2. Template: `todo-csharp-cosmos-sql` and `todo-java-mongo`.
3. Azd version : azd version 1.10.0-beta.1-daily.3780018 (commit bb526cbd20cfbd9d2ebadc2e34f1058e8595ff4f) 

**Expected behavior:**
Run `azd up` can pass.

@rajeshkamal5050, @danieljurek  for notification.

**Comment by rajeshkamal5050** [comment]
@danieljurek can you triage it?

**Comment by danieljurek** [comment]
I'm also seeing this behavior in previously released versions of the tool (e.g. `1.7.0`) there may be a service issue here.

**Comment by danieljurek** [comment]
Most recent [error message](https://github.com/Azure/azure-dev/issues/3935) was escalated to the ARM team and deployments are now succeeding. This can be closed.
