### ISSUE TITLE
Failed to deploy services when running `azd up` on US Gov Cloud

### ISSUE THREAD

**Issue by zhangjiale-64** [Azure/azure-dev#3900]
**Describe the issue:**
Test `todo-csharp-cosmos-sql` and `todo-java-mongo` templates on US Gov Cloud. Run `azd up` , get error as follow:
![image](https://github.com/Azure/azure-dev/assets/141405558/33bdc668-5f70-40a3-bc27-e3853cfba5b5)
The api and web have actually been deployed successfully. But this error appears on the terminal unexpectedly.
![image](https://github.com/Azure/azure-dev/assets/141405558/0390f6a2-10d9-42db-912e-c274e44bbb00)
The subscription exists.
![image](https://github.com/Azure/azure-dev/assets/141405558/28245af9-f64e-4150-ad5f-89f697c35b5b)

**Repro Step:**

1. Login in with command: `azd auth login`.
2. Execute command: `azd init --template <repositoryPath> --branch staging`.
3. Run `azd up`.

**Environment:**

1. Cloud: US Gov Cloud.
2. Template: `todo-csharp-cosmos-sql` and `todo-java-mongo`.
3. Azd version : azd version 1.10.0-beta.1-daily.3780018 (commit bb526cbd20cfbd9d2ebadc2e34f1058e8595ff4f) 

**Expected behavior:**
Run `azd up` can pass.

@rajeshkamal5050, @danieljurek  for notification.

**Comment by rajeshkamal5050** [comment]
@danieljurek can you triage it?

**Comment by v-xuto** [comment]
@rajeshkamal5050 In the latest round of azd manual testing (1.9.2),  this issue still exists.

- Templates: todo-csharp-cosmos-sql, todo-csharp-sql, todo-nodejs-mongo, todo-java-mongo, todo-nodejs-mongo-terraform, todo-python-mongo, todo-python-mongo-terraform
- Cloud: Usgov
- Branch: staging
- Azd version: azd version 1.10.0-beta.1-daily.3792048 (commit 13a7dd52710daa4ac5f0c17be6a77244005ac76e)

**Comment by danieljurek** [comment]
I'm also seeing this behavior in previously released versions of the tool (e.g. `1.7.0`) there may be a service issue here.

**Comment by danieljurek** [comment]
This error is not reproducing. I suspect this was related to other issues affecting ARM in sovereign clouds ([example](https://github.com/Azure/azure-dev/issues/3935)). Deployments are succeeding now. This can be closed.
