### ISSUE TITLE
Using the new azd version, a App Service deployment fails when querying the deployment status

### ISSUE THREAD

**Issue by mindit-mio** [Azure/azure-dev#3914]
azd version 1.9.1 (commit aadbc26943c2e3e5437a6ffa528fe5264887a10c)

azd deploy --debug

// 20240515181254
// https://management.azure.com/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxx/providers/Microsoft.Web/sites/xxxxxxxxxxxxxxxxxxxx/deploymentStatus/xxxxxxxxxxxxxxxxxxxxx

{
  "error": {
    "code": "MissingApiVersionParameter",
    "message": "The api-version query parameter (?api-version=) is required for all requests."
  }
}

**Comment by pamelafox** [comment]
We also just got this here:
https://github.com/Azure-Samples/azure-search-openai-demo/actions/runs/9099040349/job/25010663219

**Comment by mindit-mio** [comment]
Problem solved. Seems to have been solved in
azd version 1.9.2 (commit c58b02f71710960aba28f81f3698e64cfdda9f96)
