### ISSUE TITLE
[Issue] Test if docker is running before calling docker commands

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#393]
`azd up`

Got this:

```
Error: Command Failed: deploying service jongtodo100api: packaging service jongtodo100api: building container image: jongtodo100api at src/api: building container image: exit status 1 : exit code: 1, stdout: , stderr: error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&platform=amd64&rm=1&shmsize=0&t=jongtodo100api&target=&ulimits=null&version=1": open //./pipe/docker_engine: The system cannot find the file specified.
```

Turns out docker wasn't running

I would like azd to tell me it isn't running before it tries to execute the command.

**Comment by savannahostrowski** [comment]
This came up a bunch in our UXR for simplified init. We should investigate this as polish during Germanium

**Comment by isaacrlevin** [comment]
I am learning Go and wanted to take a look at a fully fledged app, so I came across this help-wanted issue. Looking at this it seems like the `EnsureInstalled()` function needs to be updated. The function checks to see if a tool is installed, and if it is, it passes the check. This won't work for Docker as it can be installed but not running. Here is the line in question that needs to be updated.

[for _, tool := range tools {](https://github.com/Azure/azure-dev/blob/7990e2111872c524d12f3445a65ff83107fa259a/cli/azd/pkg/tools/ensure.go#L44-L49)
```go
for _, tool := range tools {
    _, ok := confirmedTools[tool.Name()]
    if ok {
	log.Printf("Skipping install check for '%s'. It was previously confirmed.", tool.Name())
	continue
}
```

Ideally there needs to be a check in this area to check if docker is running (maybe docker info). One thing that should be added to the `ExternalTool` interface to flag tools that need to be checked and that calls an alternate workflow (possibly an `EnsureRunning()` function)

**Comment by isaacrlevin** [comment]
@jongio what sample did you get this error with? I am not able to replicate using Dev Containers. Not sure if that is expected however

**Comment by rajeshkamal5050** [comment]
@v-xuto can you see if this is reproducible?

**Comment by v-weiyding** [comment]
@rajeshkamal5050, We can reproduce this issue, the specific error message is as follows:
![Image](https://github.com/user-attachments/assets/af25f29b-7d0b-4b91-9e38-3558cce4d389)

**Environment:**

1. azd version 1.10.4 (commit 5e0b2d56a99bae47a607fa08506da31180bdf540)
2. OS: Windows
3. Templates:
- https://github.com/azure-samples/todo-python-mongo-aca
- https://github.com/Azure-Samples/todo-nodejs-mongo-aca
- https://github.com/Azure-Samples/todo-java-mongo-aca

**Comment by jongio** [comment]
> [@jongio](https://github.com/jongio) what sample did you get this error with? I am not able to replicate using Dev Containers. Not sure if that is expected however

Docker is always running if you are in a devcontainer already

**Comment by v-xuto** [comment]
@rajeshkamal5050 PR https://github.com/Azure/azure-dev/pull/4567 is ready, please help review.
