### ISSUE TITLE
[Issue] `azd up` & `azd provision` with bicep parameters?

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-dev#3930]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

```bash
azd version 1.9.2 (commit c58b02f71710960aba28f81f3698e64cfdda9f96)
```

**Describe the bug**

It's not a bug but a feature request. `azd provision` relies on the bicep template. When I run the bicep template using the `az` CLI command, it should look like:

```bash
az deployment sub create \
    -n <NAME> \
    -l <LOCATION> \
    --template-file ./infra/main.bicep \
    --parameters environmentName=$AZURE_ENV_NAME \
    --parameters location=<LOCATION> \
    --parameters <PARAMETER_KEY_1>=<PARAMETER_VALUE_1> \
    ...
```

However, there's no way to provide parameters while running either `azd up` or `azd provision` command. So, if I run either `azd up` or `azd provision`, can we add the `--parameters` option so that the parameter input prompt won't appear?

**Comment by wbreza** [comment]
@justinyoo  - `azd` supports setting Bicep parameters in the following ways:

1. Interactive mode via a prompt from `azd` when a required parameter is missing a value
2. By configuring [`main.parameters.json`](https://github.com/Azure-Samples/todo-nodejs-mongo-aca/blob/main/infra/main.parameters.json) that supports environment variable substitutions along with default values.
3. By configuring [`main.bicepparam`](https://github.com/Azure-Samples/azd-aistudio-starter/blob/main/infra/main.bicepparam) (See [Azure docs](https://learn.microsoft.com/azure/azure-resource-manager/bicep/parameter-files?tabs=Bicep) for more info)

By using either option 2 or 3 you could then dynamically set any referenced variables and avoid any interactive prompts.

**Comment by justinyoo** [comment]
@wbreza Thanks for getting back to me!

I know all the options, but any of them goes slightly off.

- I want to avoid the interactive mode
- I want to provide some parameter values dynamically generated from somewhere

My current solution is either option 2 or 3, but I think my feature request is also a nice-to-have-feature to provide devs with better flexibility.

**Comment by LunkwillAndFook** [comment]
It would certainly make `azd` easier to use in an Azure Release pipeline if this were implemented. Because this simple feature is missing I have to do a bunch of voodoo to swap out parameter files.
