### ISSUE TITLE
Failed to deploy services when running `azd up` on Azure China and USGovernment

### ISSUE THREAD

**Issue by dotnet-7** [Azure/azure-dev#3935]
#### Describe the issue:
Test `todo-csharp-cosmos-sql` and `todo-java-mongo` templates on Azure China and Azure USGovernment. Run `azd up`, get error as follow:
![image](https://github.com/Azure/azure-dev/assets/57525824/50aedb2b-330c-4560-b5b3-ecc71a68cc7d)
All resources have been successfully provisioned, but during the `azd deploy` process, an error indicates that `api` and `web` resources with tags added cannot be found. However, the services have already been created correctly on the portal.

#### Repro Step:
1. Login in with command: `azd auth login`.
2. Execute command: `azd init --template <repositoryPath> --branch staging`.
3. Run `azd up`.

#### Environment:

- Cloud: Azure China and Azure USGovernment.
- Template: `todo-csharp-cosmos-sql` and `todo-java-mongo`.
- Azd version : 1.10.0-beta.1-daily.3800821 (commit c119c9684cfacaf06ce2ef153b57c0aa14b6f4f0)

#### Expected behavior:
Run `azd up` can pass.

@rajeshkamal5050, @danieljurek for notification.

**Comment by danieljurek** [comment]
Issue was filed with the service team and deployments in sovereign clouds are now succeeding. This can be closed.
