### ISSUE TITLE
[Issue] azd pipeline config, missing a OIDC Environment entry on Azure Entra

### ISSUE THREAD

**Issue by pinakighatak** [Azure/azure-dev#3937]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
`azd version 1.9.2 (commit c58b02f71710960aba28f81f3698e64cfdda9f96)`

**Describe the bug**
When runing `azd pipeline config --principal-name "Yourspecifiedname"` the entries created are missing the Entity type Environment entry credential.

**To Reproduce**
Steps to reproduce the behavior...
1. Run the `azd pipeline config --principal-name "Yourspecifiedname"` from your local machine. 
2. Go to azure portal and then Microsoft Entra ID. Go to **App registration.**
3. Select **All applications** tab and click on the **App Registration** created.
4. Go to **Certificates and Secrets**
5. You will see 2 entries created, but a 3rd entry missing.

**Expected behavior**
There should **at least one additional (3rd) entry** for the `repo:Yourreponame:environment:YourEnvname`

**Environment**
Information on your environment:
    * C#.NET
    * VSCode 1.89.1

**Additional context**
None

**Comment by vhvb1989** [comment]
Hi @pinakighatak , the `environment` you are referring to is the GitHub Actions Environment, right?

AZD does not support GitHub actions environments yet.  `azd pipeline config` assumes you are not using CI/CD environments.  You need to manually update the OIDC credentials if you are working with environments.  And you will also need to manually update the environments' variables, as azd set the env vars at the Repo level

**Comment by pinakighatak** [comment]
Hello @vhvb1989.
Thank you for answering and clarifying. I actually am not in favor of this. If azd is meant to be a consistent tool for deployments, it should not be limited to using this from local environment only. This pipeline should work seamlessly whether I'm doing it locally, or a CI CD pipeline.
Also for future purposes, if all OIDC connections are made on Azure, why are we skipping that one property, that is a best practices for DevvSecOps?
