### ISSUE TITLE
[Issue] azd monitor doesn't work in devcontainer

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#394]
Call azd monitor from devcontainer and get:

```
warning: failed to open default browser: could not open resource: exec: "xdg-open": executable file not found in $PATH
```

I tried "github.com/pkg/browser" OpenURL and got this:

```
warning: failed to open default browser: exec: "xdg-open,x-www-browser,www-browser": executable file not found in $PATH
```

`az login` and `gh auth login` work so there has to be a way.

**Comment by savannahostrowski** [comment]
@puicchan I think this was done as well, right?

**Comment by puicchan** [comment]
Yup. In https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/troubleshoot#azd-monitor-for-development-container. Not FAQ.
