### ISSUE TITLE
Test the Llama Index partner app

### ISSUE THREAD

**Issue by kristenwomack** [Azure/azure-dev#3972]
- [x] Learn about how the Llama Index app works
- [x] azd-ify this project so the template can be submitted to the gallery
    - [x] add `azure.yaml`
    - [x] add infra folder (`main.bicep`, `app/`, `shared/`, `modules/`, `abbreviations.json`, `main.parameters.json`)
    - [x] add instructions for deploying with GitHub actions and running `azd pipeline config`
- [x] Send instructions to Laurie on how to submit the template to the `azd` gallery
- [x] Ask Natalia to also try the app

**Comment by anfibiacreativa** [comment]
adding @manekinekko, too.

**Comment by manekinekko** [comment]
Good news everyone! I managed to deploy one of the LlamaIndex samples (the Nextjs one) to Azure Container Apps, with AOAI, using azd, bicep, and managed ID!

To make AOAI work with LlamaIndex using Managed Identity, I had to patch the LlamaIndex.ts implementation. I opened an [issue](https://github.com/run-llama/LlamaIndexTS/pull/921) on LlamaIndex.ts's repo to discuss it, and prepared a [draft PR](https://github.com/run-llama/LlamaIndexTS/issues/921) as well.

![image](https://github.com/Azure/azure-dev/assets/1699357/662bfcd9-f4cd-4383-8252-11d8f9a9f5a1)

**Comment by kristenwomack** [comment]
Closing this issue. 

Next steps: (thank you @manekinekko) 
- [add MI support](https://github.com/run-llama/LlamaIndexTS/pull/922)
- `azd` [gallery sample](https://github.com/Azure-Samples/llama-index-javascript)
- [feature request](https://github.com/run-llama/llama_index/issues/13918) on the LlamaIndex (Python) repo to add support for Azure Managed Identities, and then plan a python version of the sample on the `azd` gallery.
