### ISSUE TITLE
Add support for container.v1

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#3980]
from: https://github.com/dotnet/aspire/pull/4312

**Comment by mitchdenny** [comment]
@ellismg also noted that the `container.v0` support has a gap right now ... it doesn't support the `args` field (but its in the schema). Would be good to get this fixed up as well.

**Comment by mitchdenny** [comment]
@vhvb1989 @ellismg this is ready to get moving. We've validated things on the Aspire/DCP side (just waiting on a DCP bug fix ... but the fix we are planning worked).
