### ISSUE TITLE
azd-aistudio-stater azd up failure in eastus

### ISSUE THREAD

**Issue by LianwMS** [Azure/azure-dev#3991]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.9.3 (commit e1624330dcc7dde440ecc1eda06aac40e68aa0a3)

**Describe the bug**
https://github.com/Azure-Samples/azd-aistudio-starter 
fork and "azd up":

Creating a deployment plan
Comparing deployment state
Creating/Updating resources
  You can view detailed progress in the Azure Portal:
  *************************************************

  (âœ“) Done: Resource group: rg-lianw0606
  (âœ“) Done: Log Analytics workspace: log-bvs6ljoya3f4a
  (âœ“) Done: Storage account: stbvs6ljoya3f4a
  (âœ“) Done: Key Vault: kv-bvs6ljoya3f4a
  (âœ“) Done: Search service: srch-bvs6ljoya3f4a
  (âœ“) Done: Container Registry: crbvs6ljoya3f4a
  (âœ“) Done: Application Insights: appi-bvs6ljoya3f4a
  (âœ“) Done: Cognitive Service: aoai-bvs6ljoya3f4a

ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
ValidationError: Endpoint resources are no longer supported, and have been migrated to connections. Please delete this resource and re-create it as a connection.

TraceID: bf4aa48b7b279c7205d6c5912f7cceb6

It seems that ai related service contains issue during provision: 

**To Reproduce**
Fork the repo https://github.com/Azure-Samples/azd-aistudio-starter 
Azd up

**Expected behavior**
Successfully

**Comment by wbreza** [comment]
@LianwMS What Azure location are you using?  I ran this template this morning on `eastus2` without issue.

<img width="733" alt="image" src="https://github.com/Azure/azure-dev/assets/6540159/2689cb60-f3ec-4195-a291-819146892255">

**Comment by LianwMS** [comment]
@wbreza  you are correct. eastus2 is ok. Failed in eastus. Any root cause?

**Comment by LianwMS** [comment]
@wbreza  I have the same error in eastus2 now. Could you double check?

**Comment by wbreza** [comment]
@LianwMS - this should be resolved now after the referenced PR was merged.
