### ISSUE TITLE
[Issue] azd up for azd-aistudio-starter have different result in github workflow

### ISSUE THREAD

**Issue by LianwMS** [Azure/azure-dev#3992]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
In local machine: azd version 1.9.3 (commit e1624330dcc7dde440ecc1eda06aac40e68aa0a3)
In github workflow: azd version 1.9.3 (commit e1624330dcc7dde440ecc1eda06aac40e68aa0a3)

**Describe the bug**
For azd-aistudio-starter, azd up
Run on github workflow, more error will be throw:

UnmatchedPrincipalType: The PrincipalId '7bf330256f49491c855f7845a32b7065' has type 'ServicePrincipal' , which is different from specified PrinciaplType 'User'.
UnmatchedPrincipalType: The PrincipalId '7bf330256f49491c855f7845a32b7065' has type 'ServicePrincipal' , which is different from specified PrinciaplType 'User'.
UnmatchedPrincipalType: The PrincipalId '7bf330256f49491c855f7845a32b7065' has type 'ServicePrincipal' , which is different from specified PrinciaplType 'User'.
UnmatchedPrincipalType: The PrincipalId '7bf330256f49491c855f7845a32b7065' has type 'ServicePrincipal' , which is different from specified PrinciaplType 'User'.

**To Reproduce**
Fork azd-aistudio-starter, I create a ci pipeline for azd up. But it return above error on github workflow.  but not show in local.
I can provide the repo /workflow if needed. 

The following is the ci.yaml

name: AI Gallery Template CI Validation
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      - name: Install AZD
        uses: Azure/setup-azd@v1.0.0

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Log in with Azure (Federated Credentials)
        if: ${{ env.AZURE_CLIENT_ID != '' }}
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Run validation
        run: |
          python .github/validator/validator.py . --azdup az--output .github/validator/output.log --debug

validator.py contains the azd up logic. use `azd up --no-prompt`

**Expected behavior**
Success azd up

**Comment by weikanglim** [comment]
Possibly related to #3834

**Comment by rajeshkamal5050** [comment]
Waiting on AVM related changes.
