### ISSUE TITLE
Subsequent deployments reset the Session Affinity flag

### ISSUE THREAD

**Issue by efonsecab** [Azure/azure-dev#3993]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
![image](https://github.com/Azure/azure-dev/assets/3481899/676beb79-f93d-4c54-be82-b2bf1bb41203)

**Describe the bug**
I currently have a platform developed using .NET Aspire. It deploys successfully, however, since I have to manually enable the "Session Affinity" flag after deployment, when I do updates to the code and re-deploy, the "Session Affinity" flag gets reset.

**To Reproduce**
* Publish a .NET Aspire App using azd deploy
* Enable "Session Affinity" in the deployed container app
* Do a small change to your code.
* Re-Publish the app using azd deploy.

**Expected behavior**
The Session Affinity flag value persisted in the portal.

**Environment**
Information on your environment:
    * C#, .NET 9
    * IDE and version: Visual Studio 17.11.0 Preview 1

**Additional context**

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you triage this?

**Comment by vhvb1989** [comment]
@efonsecab, this is working as expected per design.  When you are working with Aspire, all the infrastructure properties are expected to be set from the appHost.  Any manual change is overridden the next time you run a deployment.

However, Aspire does not (yet) support setting up the Azure Container App from the AppHost directly (that's is work in progress).

What you can currently do is to run `azd infra synth` and apply the session affinity to the yaml file generated by azd which defines the Azure Container App.  The downside of this is that after running `azd infra synth`, you would stop using the AppHost to generate the infrastructure, so if you make changes to your AppHost, you need to run `azd infra synth` again and re-apply the session affinity changes.

**Comment by Steinblock** [comment]
@vhvb1989 

> this is working as expected per design. When you are working with Aspire, all the infrastructure properties are expected to be set from the appHost. Any manual change is overridden the next time you run a deployment.

Except for custom domains which can be prevented from overriding with `azd config set alpha.aca.persistDomains on` https://github.com/Azure/azure-dev/pull/3955 

On the long run an option to set from the appHost might be the best option 

```
var frontend = builder.AddProject<Projects.Frontent>("frontend")
    .WithExternalHttpEndpoints(options => o.SessionAffinity = true)
```

but currently deploying a blazor app with aspire requires you to setup signalr service which feels a bit of an overkill for smaller apps. So maybe a opt in `azd config set alpha.aca.ingressSessionAffinity on` might be a good workaround.

/unresolve

**Comment by vhvb1989** [comment]
I will create `azd config set alpha.aca.persistIngressSessionAffinity on` to help here

**Comment by vhvb1989** [comment]
Should be ready in (daily-build)[https://github.com/Azure/azure-dev/blob/main/cli/installer/README.md#download-from-daily-builds] in a few hours.

**Comment by Steinblock** [comment]
Doesn't seem to be published yet.

I just installed the daily build

```
powershell -ex AllSigned -c "Invoke-RestMethod 'https://aka.ms/install-azd.ps1' -OutFile 'install-azd.ps1'; ./install-azd.ps1 -Version 'daily'"
```

and `azd` updated to this version

```
> azd version
azd version 1.10.0-beta.1-daily.3955673 (commit f210eb9547d79ed5c640906a6128909a0a4860f5)
```

which seems to be the commit directly before your PR

![image](https://github.com/user-attachments/assets/c733a8dc-552d-4144-a789-e8adf89e48da)

Not sure what triggers the daily build but it seems to be broken atm.

**Comment by vhvb1989** [comment]
@Steinblock , I see some issues on the CI/CD for building the daily release. I'm looking into it now.

**Comment by vhvb1989** [comment]
@Steinblock , you can install daily now and find the alpha feature when running `azd config list-alpha`

**Comment by Steinblock** [comment]
@vhvb1989 Awesome. Just checked it and it works. 

Thank you.
