### ISSUE TITLE
[Issue] Pre-reqs optimization

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#401]
Right now the pre-req list can be intimidating, esp when we look at containerapps.

1. Can we clarify what is needed for which action?
2. Can we help them install the pre-reqs?
3. Can one extension depend on another?
4. Which pre-reqs do we expect people to already have?

**Comment by savannahostrowski** [comment]
Is this still a relevant issue? Can we close out in favour of #821?

**Comment by savannahostrowski** [comment]
Closing in favour of #821
