### ISSUE TITLE
azd.exe process hanging around after VS exit

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-dev#4033]
This may be a solar flare but I was cleaning up some code on my cloud hosted DevBox and I noticed that `azd.exe` was running and had a handle open on my source folder:

![image](https://github.com/Azure/azure-dev/assets/513398/79cf71c4-8ffc-4e57-8333-c5d563cbfac9)

I suspect this process was launched by VS, but VS wasn't running so perhaps it didn't clean itself up. I can't remember interacting with the VS publish features on this devbox though so I'm not entirely sure where it came from.

Filing an issue just in case others have seen it.

**Comment by mitchdenny** [comment]
![image](https://github.com/Azure/azure-dev/assets/513398/06a6d14d-e792-4d32-801e-2dd05c21f537)

Was definitely launched by VS.

**Comment by rajeshkamal5050** [comment]
@anvillan @abpiskunov can you triage this for anything on VS side? cc @ellismg @weikanglim

**Comment by anvillan** [comment]
@rajeshkamal5050 @mitchdenny 

I gave it a try but could not repro: the `azd.exe` process is always terminated along with VS. 

Remember that VS starts the `azd vs-server` as soon as it detects the current project is an Aspire project. Thus, even if you do not perform and 'Deploy' related tasks, the `azd.exe` process should be started already.

I tried...
 1. Create Aspire project, add new Environment, Publish
 2. Running the project, stopping it
 3. Intentionally terminating the `azd.exe` process while VS is running, so we _recover_ it
 4. Closing VS while we are in the middle of a (long running) `RefreshEnvironment` operation
 5. Terminating (kill process) VS IDE in the middle of a `RefreshEnvironment` and/or running the project

If you could find a way to repro it consistently, that would help to see if there is any issue

**Comment by mitchdenny** [comment]
Let's pencil it in as a solar flare for now.
