### ISSUE TITLE
azd deploy "docker build" command error with container apps project [Issue]

### ISSUE THREAD

**Issue by dkirby-ms** [Azure/azure-dev#4038]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
dakir@WIN-6FJOGCB45OV:~/health_ai$ azd version
azd version 1.9.3 (commit e1624330dcc7dde440ecc1eda06aac40e68aa0a3)

**Describe the bug**
azd deploy fails with an error during docker build due to a missing path in /tmp

dakir@WIN-6FJOGCB45OV:~/health_ai$ azd deploy

Deploying services (azd deploy)

  (x) Failed: Deploying service api

ERROR: failed building service 'api': building container: api at .: building image: exit code: 1, stdout: , stderr: 0 building with "default" instance using docker driver

1 [internal] load .dockerignore
1 transferring context: 2B done
1 DONE 0.0s

....

10 exporting to image
10 exporting layers done
10 writing image sha256:53c907054d95fe74b2d9c8a5e519228210c3ad5691ab5d56a3b64ef12f3e5223 done
10 naming to docker.io/library/todo-python-mongo-aca-api done
10 DONE 0.0s
ERROR: writing image ID file: open /tmp/azd-docker-build3555712615/imgId: no such file or directory

**To Reproduce**
Create a project from todo-python-mongo-aca template and try to build it. 

**Expected behavior**
azd deploy works and docker build command completes without error. 

**Environment**
Information on your environment:
    * docker, ACA
    * WSL2/Ubuntu dev box

**Additional context**

The specific problem is that the --iidfile parameter passed to docker build is pointing to a randomly assigned /tmp/azd folder that doesnt actually exist. Docker build command fails because the folder doesnt exist.

**Comment by vhvb1989** [comment]
@dkirby-ms , the temp folder is created just to write the `imageId` and it is deleted after that. It is expected that you don't see that folder after the error.

I have tried on my side and I was not able to reproduce. Can you share more details about your environment set up?
- Are you using a command line (cmd) in Windows 11 to connect to WSL Ubuntu (do you know what Ubuntu version you are using?  20? 22? ).  Or are you using VSCode to connect to the WSL?
- What do you mean by `dev box` ?  Did you create a [Microsoft dev box](https://devbox.microsoft.com/) and you are running all from there? 

Can you run `azd deploy --debug > fullLog.txt 2>&1` and share `fullLog.txt` ?

**Comment by dkirby-ms** [comment]
I am using VSCode with WSL. I meant my local environment, sorry for the confusion. Log attached.

[log.txt](https://github.com/user-attachments/files/16042173/log.txt)

**Comment by pukichu** [comment]
I got exactly the same issue. (trying to deploy the .net Aspire react example app). No success so far.e

```
ERROR: writing image ID file: open /tmp/azd-docker-build1551254957/imgId: no such file or directory
```
