### ISSUE TITLE
[Issue] deployment metrics missings

### ISSUE THREAD

**Issue by kristenwomack** [Azure/azure-dev#4057]
**Describe the bug**
The `serverless-chat-langchainjs` template is not showing up in the `azd` deployment metrics. The `azure.yaml` is not missing the template name in the metadata and the services are defined. Possibly this is a bug or there is something in the scripts that is causing this.

https://github.com/Azure-Samples/serverless-chat-langchainjs/tree/main

cc: @gkulin

**Comment by weikanglim** [comment]
This is now fixed. The awesome-azd entry had a trailing slash for it's URL, and the ingestion pipeline wasn't handling that.

Trailing slash has been [removed](https://github.com/Azure/awesome-azd/pull/411)

Also, ingestion pipeline has been updated to handle trailing slashes.

The template is now showing up in the dashboard (just confirmed it today).

**Comment by kristenwomack** [comment]
Awesome! Thank you, @weikanglim
