### ISSUE TITLE
Local deploy has stopped working in 1.9.4

### ISSUE THREAD

**Issue by TWolversonReply** [Azure/azure-dev#4072]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
1.9.4

**Describe the bug**
Deploying a local repo fails with

```
ERROR: failed deploying service 'ramps': GET https://management.azure.com/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Web/serverfarms/<redacted>
--------------------------------------------------------------------------------
RESPONSE 404: 404 Not Found
ERROR CODE: ResourceNotFound
--------------------------------------------------------------------------------
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'https://management.azure.com/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Web/serverfarms/<redacted>` was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
  }
}
```

The resource group specified is wrong, and the message is correct that such a resource doesn't exist under it, but this didn't happen in 1.9.3. I can't see what this is trying to do and why it is looking in the wrong place, and --debug didn't provide any more information. 

**To Reproduce**

Deploy locally using version 1.9.4

**Expected behavior**

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : [e.g. Visual Studio 16.3]

**Additional context**
This is not the same issue as #4071

**Comment by rajeshkamal5050** [comment]
@hemarina can you look into this? cc @weikanglim @vhvb1989

**Comment by vhvb1989** [comment]
@TWolversonReply can you mention what azd template you are using?  Or share the bicep/terraform files please?

**Comment by weikanglim** [comment]
Thanks for reporting the issue!

From the error and the description of when this issue occurred, I'm guessing that the service plan is located in a different RG than the function app resource, which our new deployment logic to handle special flex-consumption plans of function apps may not be handling correctly. I submitted #4074 as a fix.
