### ISSUE TITLE
Pipeline: Add OIDC support

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#408]
The command will be something like:

`azd pipeline config --auth-type oidc`

Please see this implementation to see everything we need to script to get OIDC setup:
https://github.com/jongio/github-azure-oidc/blob/main/oidc.sh

We'll want to include a `fics.json` file to help the devs understand what they are doing and is a good way to visualize what the FICs look like in JSON format.
https://github.com/jongio/github-azure-oidc/blob/main/fics.json

Here's a video that walks through all the concepts involved with OIDC: https://youtu.be/r5QdsjjdRDs

We have a dependency on the Related: https://github.com/Azure/azure-cli/issues/20582

But we can call the graph REST API directly as I do in the above script until that is implemented.

We will use the `azure/login` action to support this, so the workflow included with the template will need to be updated to support OIDC or AZURE_CREDENTIALS.  We might need to have different workflow files based on the authtype.

**Comment by ellismg** [comment]
This probably impacts the work we want to do for `azd login`, since `azd login` will likely have to do something different when using OIDC to authenticate.  We'll need to look at how `az` handles this today.

**Comment by jongio** [comment]
I investigated the azure/draft OIDC setup-gh command and it is doing the same thing that my oidc.sh script does.

It heavily uses `az ad` and other `az` commands.

To implement OIDC in azd we'll need to:

Implement the flow found in my oidc.sh script but using the Azure AD REST APIs directly.

We may also add these features to the Azure ID libs:
https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity
https://github.com/AzureAD/microsoft-authentication-library-for-go
