### ISSUE TITLE
[Issue] AZD deploy does not support App Service plan in different resource group

### ISSUE THREAD

**Issue by markwragg** [Azure/azure-dev#4088]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**

azd version 1.9.4 (commit 60d7a770c73289e303a539babf5965e638843227)

**Describe the bug**

We have a Logic App (Standard) App Service in a resource group that uses an App Service Plan from another resource group. When attempting to Azd Deploy it returns a ResourceNotFound error because it expects the App Service Plan to be in the same resource group. I've had to redact out the names below, but in the error returned the resource name for the app service plan was correct (as it appears in the other resource group), but within the resource path the resource group used for it was incorrect, hence the ResourceNotFound:

```
Deploying services (azd deploy)

 (x) Failed: Deploying service logicApp
 
ERROR: failed deploying service 'logicApp': GET https://management.azure.com/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Web/serverfarms/<plan resource redacted>
--------------------------------------------------------------------------------
RESPONSE 404: 404 Not Found
ERROR CODE: ResourceNotFound
--------------------------------------------------------------------------------
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.Web/serverFarms/<plan resource redacted>' under resource group '<redacted>' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
  }
}
--------------------------------------------------------------------------------
```

**To Reproduce**

Deploy a Logic App (Standard) resource in a resource group that uses an App Service plan from another resource group. Attempt to do Azd deploy.

**Expected behavior**

It should not be inferring the resource group for the Plan, it should just get its full resource ID from the app service.

**Environment**

VSCode

**Additional context**

None

**Comment by weikanglim** [comment]
@markwragg This was indeed an oversight and will be fixed in the next release (change #4074 was merged). In the meantime, version 1.9.3 should work for this scenario.

Being slightly curious your setup for Logic App (Standard) deployments.. What is the value you're providing for `host` for `logicApp` in `azure.yaml`?

**Comment by markwragg** [comment]
The value we're using is `function`. I'll downgrade to 1.9.3 and see if that works, thanks!

**Comment by markwragg** [comment]
For some reason when I asked chocolatey to install 1.9.3 I got 1.9.2 instead, but its working fine under that version so closing this issue. Thanks again.
