### ISSUE TITLE
`todo-nodejs-mongo-aks` app not reachable - due to ingress networking security policy in microsoft tenants

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-dev#4108]
**Describe the issue:**
After running the `azd up` command, click the api and web links output in the logs, and the pages fails to load as follows:
- API error: 
![image](https://github.com/Azure/azure-dev/assets/111940661/7f951f82-5131-49ad-a290-1f022e6de9c0)
- Web error:
![image](https://github.com/Azure/azure-dev/assets/111940661/17bc1257-aeca-46f4-b116-f2df249a31c0)

**Repro Steps:**
1. Login in with command: `azd auth login`.
2. Execute command: `azd init -t todo-nodejs-mongo-aks -b staging`.
3. Run `azd up`.
4. Click web and api links.

**Environment:**

- Template: `todo-nodejs-mongo-aks`.
- Branch: `pr/3976` and `staging`.
- OS: Windows, Codespaces, Devcontainer, Linux, Mac.
- Azd version: `azd version 1.10.0-beta.1-daily.3947259 (commit 5bf8568b1566723be8bc2259c578df4f931cf430)`

**Expected behavior:**
Web and api page can be loaded successful.

@jongio for notification.

**Comment by jongio** [comment]
Are these related? https://github.com/Azure/azure-dev/issues/4109

**Comment by jongio** [comment]
This may have been transient.  Please re-test

**Comment by v-xuto** [comment]
> Are these related? #4109

This issue should be unrelated to #4109. When we discovered this issue, `azd up` was successfully executed in the terminal. There were only errors when opening web and api links. At that time, we had not encountered issue #4109, and application insights could be created normally.

**Comment by jongio** [comment]
@rajeshkamal5050 or @weikanglim @vhvb1989 Can you follow up?

**Comment by vhvb1989** [comment]
This is expected for `todo-nodejs-mongo-aks`, IIRC.

@wbreza knows the instructions for testing the ask template. There was something related to using a DevBox with access to CorpNet (when using playground sub)

**Comment by jongio** [comment]
I see this error too:
![image](https://github.com/user-attachments/assets/337eada9-1b97-4741-88e6-f0760385d955)


Which is why I think it's related to the other issue

**Comment by jongio** [comment]
I didn't run into that DevBox/CorpNet issue with the hello-ai aks project. So, I think the restriction Wallace was dealing was could have been resolved.  This works: 
https://github.com/jongio/hello-ai/

**Comment by vhvb1989** [comment]
> I see this error too: ![image](https://private-user-images.githubusercontent.com/2163001/348383974-337eada9-1b97-4741-88e6-f0760385d955.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MTUyNTQsIm5iZiI6MTcyMDgxNDk1NCwicGF0aCI6Ii8yMTYzMDAxLzM0ODM4Mzk3NC0zMzdlYWRhOS0xYjk3LTQ3NDEtODhlNi1mMDc2MDM4NWQ5NTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMjAwOTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWY2NTQ3OTY4MGYyOGZkMmI2MjA2Zjk3M2Q5M2IzMjU4ZTE1YTAwNGQ0NGZjZjE5YzNjNzJhZGU0MGIwNzVjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R9kAsdKnHeMXfle0CaluLG0OwW1iFxsqNrx8wyS4hPc)
> 
> Which is why I think it's related to the other issue

oh!   I will take a look to that!

**Comment by vhvb1989** [comment]
> I didn't run into that DevBox/CorpNet issue with the hello-ai aks project. So, I think the restriction Wallace was dealing was could have been resolved. This works: https://github.com/jongio/hello-ai/

Did you set the `azd env set WORKSPACE azure` ?

**Comment by vhvb1989** [comment]
Here's an example,  

After deploying aks template:

```bash
Deploying services (azd deploy)

  (✓) Done: Deploying service api
  - http://10.0.255.78:80 (Service: todo-api, Type: ClusterIP)
  - http://4.153.60.214/api (Ingress, Type: LoadBalancer)

  (✓) Done: Deploying service web
  - http://10.0.33.13:80 (Service: todo-web, Type: ClusterIP)
  - http://4.153.60.214 (Ingress, Type: LoadBalancer)
```
The ingress `4.153.60.214` is only accesible within the CorpNet.  I can access it from my devBox:

![image](https://github.com/user-attachments/assets/957e8bdb-0987-4948-bc76-37d6a96c1205)

But not from my host PC at home:

![image](https://github.com/user-attachments/assets/5b507eb3-231b-4114-a0c3-c1c1e7db50c2)

**Comment by vhvb1989** [comment]
> I didn't run into that DevBox/CorpNet issue with the hello-ai aks project. So, I think the restriction Wallace was dealing was could have been resolved. This works: https://github.com/jongio/hello-ai/

Fix for this: https://github.com/Azure/azure-dev/pull/4117

**Comment by vhvb1989** [comment]
> I see this error too: ![image](https://private-user-images.githubusercontent.com/2163001/348383974-337eada9-1b97-4741-88e6-f0760385d955.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MTgwOTYsIm5iZiI6MTcyMDgxNzc5NiwicGF0aCI6Ii8yMTYzMDAxLzM0ODM4Mzk3NC0zMzdlYWRhOS0xYjk3LTQ3NDEtODhlNi1mMDc2MDM4NWQ5NTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMjA1NjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjUwNDQxYjBhZDdkMjRhOThhNDMzZDk1NjZkYmUzMjRmNmVkMzU5MjZmNzA5MTQ2NDdiM2QzZTMwNGMyMjFhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.H4Y0mSP8TZrR65sNlVTiZsRCJsjKK5p0q2-m8JQVXJ8)
> 
> Which is why I think it's related to the other issue

fix for this: https://github.com/Azure/azure-dev/pull/4117

**Comment by jongio** [comment]
1. Let's see is this is expected behavior from @wbreza 
2. Let's see if there's something that can be added to the readme and test plan updated for MS subs.

**Comment by wbreza** [comment]
@jongio This is an ingress networking security policy automatically configured against all Microsoft tenant subscriptions which block all inbound traffic to any VM backed resources.

Deploying this template to subscriptions outside of the Microsoft tenant will work as expected unless the subscription has similar policies in place.

**Comment by jongio** [comment]
Do we have anything documented for this in the README?  What should we tell the end user?  

If you are running on an internal sub, then you need to test this from a devbox.  Here's the error you'll receive if you attempt to run outside of a devbox:

**Comment by jongio** [comment]
@Menghua1 - can you do a pr into azure-dev repo to add a note to the readme about this issue?

**Comment by Menghua1** [comment]
> @Menghua1 - can you do a pr into azure-dev repo to add a note to the readme about this issue?

@jongio I created a pr here: https://github.com/Azure/azure-dev/pull/4235, please review.

**Comment by Menghua1** [comment]
> Okay, let's close this now that we have something in the readme and please update the test cases to reflect this.

@jongio Got it, I closed this issue. Could you please clarify what you mean by "the test cases"? 

Additionally, in the latest test, when testing `todo-nodejs-mongo-aks` under on an internal sub and outside of the devbox, we do not encounter the error described in [PR4235](https://github.com/Azure/azure-dev/pull/4235).
