### ISSUE TITLE
Fail to run command `azd up`

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-dev#4109]
**Describe the issue:**
For all todo templates, running the command `azd up` failed with the following error message today:
`Notes: There was no such issue two days ago.`
![image](https://github.com/Azure/azure-dev/assets/111940661/d30fb1a7-2db3-4f87-8238-f9f4abb18d6a)

**Repro Steps:**
1. Login in with command: `azd auth login`.
2. Run command: `azd init -t todo-nodejs-mongo-aks -b staging`.
3. Run command `azd up`.

**Environment:**
- Template: all todo templates (under azure-dev).
- Branch: `pr/3976` and `staging`.
- OS: Windows, Codespaces, Devcontainer, Linux, Mac.
- Azd version: `azd version 1.10.0-beta.1-daily.3947259 (commit 5bf8568b1566723be8bc2259c578df4f931cf430)`.

**Expected behavior:**
The command `azd up` can be run successfully.

@jongio for notification.

**Comment by jongio** [comment]
Does this happen with 1.9.4?

**Comment by jongio** [comment]
This may have been transient.  Please re-test

**Comment by Menghua1** [comment]
Based on the azd 1.9.4 version test, this issue still exists.

**Comment by v-xuto** [comment]
> This may have been transient. Please re-test

We retested today and still have this issue. Application insights cannot be created normally.

**Comment by Menghua1** [comment]
This issue still exists in `eastus`. After changing a location (such as `westus`), this issue no longer exists.

**Comment by jongio** [comment]
@rajeshkamal5050 or @weikanglim @vhvb1989 What do you think we should do here?

**Comment by weikanglim** [comment]
@Menghua1 Can you try retesting it again to see if anything changes? I'm wondering if this was a blip in the service, since iur CI runners are running `azd up` successfully in `eastus2`. I just tried this morning and it worked fine as well:
![image](https://github.com/user-attachments/assets/5914cbf0-1f51-4faf-812f-08bc624a6e34)

It seems that the ARM deployment worker -> app insight request is failing, so it shouldn't be anything that azd has control over on the client-side.

**Comment by vhvb1989** [comment]
> CI runners are running

@weikanglim , IIRC, we don't run aks template in CI.  Did we change that?

**Comment by vhvb1989** [comment]
nvm @weikanglim , I just noticed I am mixing this issue and https://github.com/Azure/azure-dev/issues/4108#issuecomment-2226283947 , LOL.  (b/c this issue is mentioning aks on the description).

But you are right, this looks like a `blip in the service`

**Comment by Menghua1** [comment]
@weikanglim We retested it, this issue did not reoccur in `eastus2`.
