### ISSUE TITLE
[Spike] [Aspire] [Feature] Azure Functions on ACA

### ISSUE THREAD

**Issue by v-mengwe** [Azure/azure-dev#4112]
**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS 17.11.0 Preview 4.0 [35111.106.d17.11]
**Aspire Version:** 8.0.0
Apply NuGet Feeds

**REPRO STEPS:**

1. Create a new 8.0 Azure Function project with HTTP Trigger -> Add -> .NET Aspire orchestrator support.
2. Open Command Prompt and navigate to the solution path of this project.
3. Run 'azd init', select 'Use code in the current directory' -> Confirm and continue initializing my app, type a new environment, press enter
4. Run 'azd up', and select Subscription to Azure Tools Manual Testing 1 and select Location to East US, press enter.
5. **The "No endpoints were found" shows under the service of Azure Function project** -> Open the URL of Aspire Dashboard.
6. Check whether there is an endpoint of the Azure Function project.

**Expect:**
There is no endpoint of the Azure Function project.

**Actual:**
There is an endpoint of the Azure Function project. (I am confused by the results below the service of Azure Function project and on the dashboard.)
![image](https://github.com/user-attachments/assets/63f885dd-7d4c-4765-8d5c-ee302f5b8b0b)

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you take a look?

**Comment by vhvb1989** [comment]
I think this is expected.
The application's endpoint is not exposed and azd would only show the endpoint when it is public.

When you use the aspire-dashboard, you are basically inside the Azure Container Environment, from where the endpoint is valid.

@davidfowl @mitchdenny should the aspire-dashboard mention if the endpoint is public or internal ?  what do you think?

**Comment by mitchdenny** [comment]
We don't yet have Azure function support for .NET Aspire, this is something we are working on for .NET Aspire 9.0. /cc @captainsafia

**Comment by captainsafia** [comment]
@vhvb1989 Yep -- I don't expect this scenario to work end-to-end at the moment. It looks like the repro steps are using the Aspire orchestration integration for Azure Functions in Visual Studio to bootstrap the project. This only configures an Azure Functions project (with only HTTP triggers) to support limited launching/debugging capabilities in VS. The deployment story via `azd` isn't in any public builds yet.

We can follow-up on this scenario once https://github.com/dotnet/aspire/issues/920 is done.

cc: @ellismg

**Comment by rajeshkamal5050** [comment]
@ellismg @vhvb1989 marking this as complete on azd side. Since there isn't anything specific, we do on azd.
