### ISSUE TITLE
Project dependencies

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#412]
Identify how to handle dependencies between projects.

Standard use case
- Solution with 2 apps, frontend + backend.  
- Need to deploy backend changes before frontend, etc.

**Comment by savannahostrowski** [comment]
@wbreza Gentle ping 😸. Is this still needed?

**Comment by rajeshkamal5050** [comment]
@wbreza @savannahostrowski Closing this as a duplicate of this
- https://github.com/Azure/azure-dev/issues/121
