### ISSUE TITLE
[Issue] Reopen: Deployed Aspire Dashboard forces logging in using a school or work account

### ISSUE THREAD

**Issue by Kumima** [Azure/azure-dev#4121]
Reopen issue: #4010
I can't reopen the issue that has been closed by inner developer.
Creating new Aspire Starter Project -> `azd init` -> `azd up`, and nothing else. My azd version is 1.9.5. Still shows "Please use a school or work account.".

I've also asked one of my co-workers to test, same behavior. So, I can confirm it was not caused by my azure subscription.
And please do test before you close the issue, please. This problem has been more than a month.

**Comment by rajeshkamal5050** [comment]
Closing based on comment - https://github.com/Azure/azure-dev/issues/4010#issuecomment-2232086740

**Comment by SlobodanVucetic** [comment]
The same is happening to me. I cannot access the Aspire dashboard from a deployed ACA. It was working few weeks ago... It requires work or school account even when I'm logged in to the Azure portal using my personal account (@gmail).
