### ISSUE TITLE
Deployment status API not reliable for App Service

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#4126]
We are seeing more and more instability in our template tests that deploy to app service.

> ERROR: deployment failed: error deploying infrastructure: deploying to subscription:
> Deployment Error Details:
InternalServerError: There was an unexpected InternalServerError.  Please try again later.  x-ms-correlation-request-id: <redacted>

Repro steps:
1. azd init -t todo-nodejs-mongo
2. azd up

Wait for deployment to complete.  Users experience random `InternalServerError` failures.

**Comment by rajeshkamal5050** [comment]
@hemarina can you triage this?

**Comment by rajeshkamal5050** [comment]
Duplicate of #4093
