### ISSUE TITLE
Making private ai-apps site visible for partners/external users

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#4143]

**Comment by kristenwomack** [comment]
@rajeshkamal5050 - we only want internal microsoft access for testing before go-live

**Comment by vhvb1989** [comment]
If partners or external users are invited/added to the Microsoft directory, they can access the ai-mirror web.

**Comment by vhvb1989** [comment]
Now, @rajeshkamal5050 , if you want to give access to unique specific email accounts (outside of Microsoft Directory), I can set up a second web mirror within our Azure - Dev directory (where we have control over the EntraId directory and where we can invite any external account.  Lmk if you need this

**Comment by kristenwomack** [comment]
This is great! Thank you @vhvb1989. @rajeshkamal5050 - I validated this mirror link and everything works.

**Comment by kristenwomack** [comment]
LGTM

**Comment by kristenwomack** [comment]
I've been using this every day and it's such a time saver -- thank you @vhvb1989!
