### ISSUE TITLE
[Issue] Default Aspire-used Container Registries to Managed Identity

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-dev#4147]
With [[Issue] Container Registry auth error while deploying apps through `azd up`](https://github.com/Azure/azure-dev/issues/2980) the default Aspire generated Container Registry is created with admin account enabled and does authentication via the admin account.

Unfortunately, this results in a failure with S360 as the requirement is that Managed Identity is to be used for authentication and admin users should be disabled.

The result of this is that every time I deploy an Aspire app I get a security warning from our compliance team.

In an effort to adopt best security practices, we should use MI by default, provide guidance (as outlined in #2980) for users that hit that problem and need to "fix" their account, and only lastly provide a workaround to introduce a less-secure auth approach for ACR.

**Comment by mitchdenny** [comment]
Presumably this means we'll have to do `az acr login` for local deployments?

**Comment by aaronpowell** [comment]
Do you mean before running an `azd deploy` command?

I'd expect a workflow that exists virtually the same as the one we currently have in place, where you do `azd up` and it creates the ACR, configures an identity for it (or uses the identity that azd is deploying as) to then authenticate with ACR and publish images.

**Comment by rajeshkamal5050** [comment]
@ellismg @vhvb1989 given that we have to be secure by default. Can we revert this https://github.com/Azure/azure-dev/pull/3069 and document [this guidance to fix their accounts](https://github.com/Azure/azure-dev/issues/2980#issuecomment-1843495071)?
