### ISSUE TITLE
[Feature] Add Java support to CLI

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#416]
We have a Java API working in Azure/azure-dev-pr#459 and need to update the azdev CLI to support packaging and deployment.

We have references here: 
https://github.com/microsoft/nubesgen-actions/blob/main/gitops-build-java-maven/action.yml
https://github.com/microsoft/nubesgen-actions/blob/main/gitops-deploy-to-app-service-java/action.yml

And @jdubois Can help with any questions.

**Comment by weikanglim** [comment]
@jdubois Do you know if the Maven plugin vs Gradle is more popular amongst Java developers for package/deploy? We'll might end up supporting both if the userbase is big enough, but I think we'll start with one for early iterations.

**Comment by rajeshkamal5050** [comment]
> @jdubois Do you know if the Maven plugin vs Gradle is more popular amongst Java developers for package/deploy? We'll might end up supporting both if the userbase is big enough, but I think we'll start with one for early iterations.

@weikanglim it will be Maven to start with based on the data collected by @savannahostrowski

**Comment by jdubois** [comment]
Yes Maven is much more popular than Maven for building/packaging a Java application. Then for deploying, our data shows that most people are using the CLI, the VS Code plugin or a tool like Terraform, than the Maven plugin.

**Comment by stliu** [comment]
> > @jdubois Do you know if the Maven plugin vs Gradle is more popular amongst Java developers for package/deploy? We'll might end up supporting both if the userbase is big enough, but I think we'll start with one for early iterations.
> 
> @weikanglim it will be `Maven` to start with based on the data collected by @savannahostrowski

FYI, Gradle is the default one now on https://start.spring.io , so I'd suggest we add gradle support as well

**Comment by weikanglim** [comment]
@stliu Created #2705. Let's discuss and upvote there!
