### ISSUE TITLE
[AzureTools][Aspire] Fail to publish the project using azd with the location "East US STG (eastusstg)" or "South Central US STG (southcentralusstg)"

### ISSUE THREAD

**Issue by v-mengwe** [Azure/azure-dev#4184]
**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS 17.12.0 Preview 2.0 [35205.153.main]
**Aspire Version:** 8.1.1-preview.1.24405.5
**azd Version:** 1.9.5
Apply NuGet Feeds

**REPRO STEPS:**
1. Create an Aspire starter project
2. Open Command Prompt and navigate to the solution path of this project.
3. Run 'azd init', select 'Use code in the current directory' -> Confirm and continue initializing my app, type a new environment, press enter
4. Run 'azd up', and select Subscription to Azure Tools Manual Testing 1/WTE and select Location to "**East US STG (eastusstg)**", press enter.
5. Check whether succeeds to publish the project.

**Expect:**
1. Succeed to publish the project without any error.
2. It would be better to hide or remove unsupported locations if these locations are not supported

**Actual:**
Fail to publish the project with an error.
![image](https://github.com/user-attachments/assets/52b29365-5395-442b-8e57-dd50504f203b)

**More Info:**
1. This issue also reproduces for the location "South Central US STG (southcentralusstg)".
2. No location "East US STG (eastusstg)" or "South Central US STG (southcentralusstg)" in the dropdown list when publish the project using VS.

**Comment by v-mengwe** [comment]
From the bug [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2183586](url)

**Comment by rajeshkamal5050** [comment]
@vhvb1989 @ellismg can we hide these staging locations which are not valid for deployment?

**Comment by v-mengwe** [comment]
Verified on the azd version 1.10.0-beta.1-pr.4097989, no "East US STG (eastusstg)" or "South Central US STG (southcentralusstg)" location shows for now.
![image](https://github.com/user-attachments/assets/9e967173-0252-4e29-9216-b0b4dc3ff383)

**Comment by v-mengwe** [comment]
Got it, thanks for the update.

**Comment by rajeshkamal5050** [comment]
> Chatted with @ellismg and confirmed that we don't own the change/code in VS. Will create this issue on VS side.

@anvillan @abpiskunov can you create an issue on VS side for this?

**Comment by anvillan** [comment]
@rajeshkamal5050 

We already have bug `2183586` in area path `DevDiv\Web Tools\Web\Aspire`
