### ISSUE TITLE
[Issue] Persist current custom domain fails

### ISSUE THREAD

**Issue by ryanheath** [Azure/azure-dev#4204]
**Describe the bug**
Our custom domain keeps being removed when deploying a new version.
We use #3955 'azd config set alpha.aca.persistDomains on' now, but now deployment fails.
It fails for a container that does not use any custom domain.
Our deployment deploys several containers at once.

![image](https://github.com/user-attachments/assets/1825d787-ca3b-4404-8c36-4c331f7f431d)

**Expected behavior**
Deployment should not fail and custom domain for certain container should be preserved.

**Comment by rajeshkamal5050** [comment]
> It fails for a container that does not use any custom domain.
Our deployment deploys several containers at once.

@vhvb1989 can you see if there is any regression when enabling `alpha.aca.persistDomains`?

**Comment by ryanheath** [comment]
@vhvb1989 Any info about this issue?

// Ryan

**Comment by vhvb1989** [comment]
@ryanheath , have you tried using daily build?  https://github.com/Azure/azure-dev/blob/main/cli/installer/README.md#download-from-daily-builds

Are you getting this issue with version 1.9.6 ?

**Comment by ryanheath** [comment]
@vhvb1989 
We are using the current releases in our pipeline.
It now works! :)
Thanks
