### ISSUE TITLE
[Issue] Can't run azd down on RG with OpenAI instance

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#4210]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.10.0-beta.1-pr.4028794 (commit 1388546c9db82c93a53b8ba8335962b2b68fd408)

**Describe the bug**

I do not think this is an issue with azd itself, but y'all might know where to reroute or have workarounds.

When running "azd down" on https://github.com/Azure-Samples/openai-chat-vision-quickstart/, I get this error:

```
--------------------------------------------------------------------------------
RESPONSE 409: 409 Conflict
ERROR CODE: ResourceGroupDeletionBlocked
--------------------------------------------------------------------------------
{
  "error": {
    "code": "ResourceGroupDeletionBlocked",
    "message": "Deletion of resource group 'chatvision-rg' failed as resources with identifiers 'Microsoft.CognitiveServices/accounts/edmqlohrlcibo-cog' could not be deleted. The provisioning state of the resource group will be rolled back. The tracking Id is '50cc42c7afb813d4bff8d3974397e4d9'. Please check audit logs for more details.",
    "details": [
      {
        "target": "/subscriptions/32ea8a26-5b40-4838-b6cb-be5c89a57c16/resourceGroups/chatvision-rg/providers/Microsoft.CognitiveServices/accounts/edmqlohrlcibo-cog",
        "message": "{\"error\":{\"code\":\"CannotDeleteAccountWithDeployments\",\"message\":\"Could not delete account since it contains 1 deployment(s). Please delete deployments first and try again.\"}}"
      }
    ]
  }
}
```

I see a similar warning in the Portal:

<img width="1293" alt="Screenshot 2024-08-13 at 5 31 24 AM" src="https://github.com/user-attachments/assets/bb3e8f83-8343-4da6-8868-26fc636ec306">

I'm not sure if this is only happening because the deployment uses a Global SKU or if its now happening for all OpenAI accounts. I've only had it reported for this repo so far, but perhaps its a recent change.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 @hemarina do we handle deleting deployments for other resources as part of `azd down`?

**Comment by vhvb1989** [comment]
> @vhvb1989 @hemarina do we handle deleting deployments for other resources as part of `azd down`?

No.  Azd deletes resource groups directly w/o looking what's in them. 
I've started a conversation with @achand to follow

**Comment by wbreza** [comment]
@rajeshkamal5050 - this may be handled by deployment stacks when the deployment is created as part of the deployment stack.  I will test on our feature branch and report back.

If the deployments are created outside of `azd` it isn't a cut & dry and whether or not `azd` should delete deployments on behalf of user or not.

**Comment by rajeshkamal5050** [comment]
@pamelafox starting [azd 1.10.0](https://github.com/Azure/azure-dev/releases/tag/azure-dev-cli_1.10.0) we have added support for deployment stacks(alpha feature `azd config set alpha.deployment.stacks on`) which should handle it without need for the hooks https://github.com/Azure-Samples/openai-chat-vision-quickstart/pull/10

Can you give it a try and let us know if it works? cc: @wbreza

**Comment by pamelafox** [comment]
@rajeshkamal5050 At what point will it not require the alpha flag?
