### ISSUE TITLE
[Issue] SWA app no longer building successfully in GitHub actions

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#4218]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version: 1.9.6 (commit 0b1a8ad350177078312141f4465ad72205d7c077)

**Describe the bug**

My azd up in a GitHub action is now failing:
https://github.com/pamelafox/pamelafox-site/actions/runs/10394704696/job/28785086518

It succeeded the last time I updated the site, with azd version 1.9.3:
https://github.com/pamelafox/pamelafox-site/actions/runs/9748077672/job/26902258183

The diff in the log seems to be that it can't find the swa cli config? These lines are new:

```
2024/08/14 20:41:54 service_manager.go:573: Using swa-cli for build and deploy because swa-cli.config.json was found in the service path
2024/08/14 20:41:54 service_manager.go:573: Using swa-cli for build and deploy because swa-cli.config.json was found in the service path
2024/08/14 20:41:54 ensure.go:47: Skipping install check for 'SWA CLI'. It was previously confirmed.
2024/08/14 20:41:54 service_manager.go:573: Using swa-cli for build and deploy because swa-cli.config.json was found in the service path
2024/08/14 20:41:54 service_manager.go:573: Using swa-cli for build and deploy because swa-cli.config.json was found in the service path
```

But those could be red herrings?

It should be running the prepackage hook to install the Python requirements, but there's no evidence of it running.

**Comment by rajeshkamal5050** [comment]
@weikanglim can you triage this? suspecting it should have been falling since 1.9.4 i.e., ([swa: ability to use swa-cli.config.json #3553](https://github.com/Azure/azure-dev/pull/3553)) got added cc: @vhvb1989 @hemarina

**Comment by vhvb1989** [comment]
This is b/c hooks are not registered

> 2024/08/14 20:41:54 hooks.go:78: azd project is not available or does not contain any command hooks, skipping command hook registrations.


https://github.com/pamelafox/pamelafox-site/actions/runs/10394704696/job/28785086518#step:7:26

This is a current known bug with the order of creation. By the time the hooks registration runs (from midleware) the env is not yet created and the hooks are ignored.

You can currently workaround this by adding one step before the provision to init the env. 

Or you can also move from using azd hook prepackage to use the swa-cli, like

```
"appBuildCommand": "./deploy.sh && python3 freeze.py",
```

**Comment by weikanglim** [comment]
Regarding the `prepackage` *service* hook not running before executing `swa-cli-build`:

Since this repository had `swa-cli-config.json` present, the repository automatically opted-in to the new flow that delegates to `swa-cli` as described in #3553, which executes during the build and not package phase.  Changing the `prepackage` hook to `prebuild` hook would allow you have a hook execute as before.

But as @vhvb1989 pointed out, with `swa-cli-config.json` present, it may be best to delegate the build to `swa-cli` by modifying `swa-cli-config.json` directly. Based on the setup, I would recommend renaming `deploy.sh` -> `build.sh` and set `appBuildCommand: "./build.sh"` in `swa-cli-config.json`.

**Comment by pamelafox** [comment]
That fix didn't fully work yet, it's error'ing at the end with ", stderr: ✖ The folder "/home/runner/work/pamelafox-site/pamelafox-site/src/build" is not found. Exit."

That might be a simple file path issue on my end. It's been a long while since I've dealt with SWAs so I'll debug it later unless y'all know what's up.

**Comment by weikanglim** [comment]
I wonder if `"outputLocation": "flaskapp/build",` may fix it. I ran `package` and that succeeded but I haven't tried running `deploy` (which I think is when that is used).

**Comment by pamelafox** [comment]
Yayy that did it! I assume you can close this as "user did something weird that no longer works"
