### ISSUE TITLE
[Issue] azd up stuck on aspire dashboard

### ISSUE THREAD

**Issue by hjblourenco** [Azure/azure-dev#4221]
While I'm on azd up azure stuck here.
![image](https://github.com/user-attachments/assets/54b48ae5-a165-4eff-954d-b2564f6864eb)

I'm using Visual Studio command line.

All the other resources seems to start:
![image](https://github.com/user-attachments/assets/5928a901-ae90-4c02-9423-b447fc0c66f9)

What can I do?

debug from command line:
The debug message (repeats on loop):
2024/08/16 14:08:12 main.go:50: Retry: response 200
2024/08/16 14:08:12 main.go:50: Retry: exit due to non-retriable status code
2024/08/16 14:08:12 main.go:50: LongRunningOperation: State Running
2024/08/16 14:08:12 main.go:50: LongRunningOperation: delay for 30s
2024/08/16 14:08:12 main.go:50: Retry: =====> Try=1
2024/08/16 14:08:12 main.go:50: Request: ==> OUTGOING REQUEST (Try=1)
   GET https://management.azure.com/subscriptions/XXXXXXXX/providers/Microsoft.Resources/deployments/tests1-1723816787/operations?api-version=2021-04-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armresources.DeploymentOperationsClient/v1.1.1 (go1.21.0 X:loopvar; Windows_NT),azdev/1.9.6 (Go go1.21.0 X:loopvar; windows/amd64)
   X-Ms-Correlation-Request-Id: cd0ba9875117a7e0907489e3f7e3f9c6

  | ======| Creating/Updating resources2024/08/16 14:08:13 main.go:50: Response: ==> REQUEST/RESPONSE (Try=1/437.964ms, OpTime=437.964ms) -- RESPONSE RECEIVED
   GET https://management.azure.com/subscriptions/XXXXXX/providers/Microsoft.Resources/deployments/tests1-1723816787/operations?api-version=2021-04-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armresources.DeploymentOperationsClient/v1.1.1 (go1.21.0 X:loopvar; Windows_NT),azdev/1.9.6 (Go go1.21.0 X:loopvar; windows/amd64)
   X-Ms-Correlation-Request-Id: cd0ba9875117a7e0907489e3f7e3f9c6
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Cache-Control: no-cache
   Content-Length: 1236
   Content-Type: application/json; charset=utf-8
   Date: Fri, 16 Aug 2024 14:08:12 GMT
   Expires: -1
   Pragma: no-cache
   Strict-Transport-Security: REDACTED
   X-Cache: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Correlation-Request-Id: cd0ba9875117a7e0907489e3f7e3f9c6
   X-Ms-Ratelimit-Remaining-Subscription-Global-Reads: REDACTED
   X-Ms-Ratelimit-Remaining-Subscription-Reads: REDACTED
   X-Ms-Request-Id: ebc1f983-6301-4873-9022-24a234f3b68a
   X-Ms-Routing-Request-Id: REDACTED
   X-Msedge-Ref: REDACTED

2024/08/16 14:08:13 main.go:50: Retry: response 200
2024/08/16 14:08:13 main.go:50: Retry: exit due to non-retriable status code
2024/08/16 14:08:13 main.go:50: Retry: =====> Try=1
2024/08/16 14:08:13 main.go:50: Request: ==> OUTGOING REQUEST (Try=1)
   GET https://management.azure.com/subscriptions/XXXXXXXX/resourcegroups/rg-tests1/deployments/resources/operations?api-version=2021-04-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armresources.DeploymentOperationsClient/v1.1.1 (go1.21.0 X:loopvar; Windows_NT),azdev/1.9.6 (Go go1.21.0 X:loopvar; windows/amd64)
   X-Ms-Correlation-Request-Id: cd0ba9875117a7e0907489e3f7e3f9c6

  |     ==| Creating/Updating resources2024/08/16 14:08:14 main.go:50: Response: ==> REQUEST/RESPONSE (Try=1/759.3783ms, OpTime=759.3783ms) -- RESPONSE RECEIVED
   GET https://management.azure.com/subscriptions/XXXXXXXXXXXX/resourcegroups/rg-tests1/deployments/resources/operations?api-version=2021-04-01
   Accept: application/json
   Authorization: REDACTED
   User-Agent: azsdk-go-armresources.DeploymentOperationsClient/v1.1.1 (go1.21.0 X:loopvar; Windows_NT),azdev/1.9.6 (Go go1.21.0 X:loopvar; windows/amd64)
   X-Ms-Correlation-Request-Id: cd0ba9875117a7e0907489e3f7e3f9c6
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Cache-Control: no-cache
   Content-Length: 11551
   Content-Type: application/json; charset=utf-8
   Date: Fri, 16 Aug 2024 14:08:13 GMT
   Expires: -1
   Pragma: no-cache
   Strict-Transport-Security: REDACTED
   X-Cache: REDACTED
   X-Content-Type-Options: REDACTED
   X-Ms-Correlation-Request-Id: cd0ba9875117a7e0907489e3f7e3f9c6
   X-Ms-Ratelimit-Remaining-Subscription-Global-Reads: REDACTED
   X-Ms-Ratelimit-Remaining-Subscription-Reads: REDACTED
   X-Ms-Request-Id: eb299070-064a-4984-b5ff-850bfe62b1e7
   X-Ms-Routing-Request-Id: REDACTED
   X-Msedge-Ref: REDACTED

2024/08/16 14:08:14 main.go:50: Retry: response 200
2024/08/16 14:08:14 main.go:50: Retry: exit due to non-retriable status code

Thanks

**Comment by snehapar9** [comment]
Thanks for reporting this @hjblourenco! This could be a transient issue. Are you still encountering this?
Can you please confirm if you can access the Aspire dashboard now?

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you take a look?

**Comment by hjblourenco** [comment]
Testing again today and the same issue.

After a long time:
```
ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
DotNetComponentOperationError: Failed to provision component 'aspire-dashboard'. Error details: DotNetComponent 'aspire-dashboard deletion timeout.'.

TraceID: 
```

**Comment by hjblourenco** [comment]
Now I'm getting this error:
(How do I manage to fix the possible error if I cant find the place)

```
2024/08/19 14:30:52 main.go:50: Retry: response 200
2024/08/19 14:30:52 main.go:50: Retry: exit due to non-retriable status code
  |==     | Deploying service xinio-api-management (Pushing container image)2024/08/19 14:31:07 command_runner.go:307: Run exec: 'dotnet publish C:\Users\ \source\repos\ \ \.csproj -r linux-x64 -c Release /t:PublishContainer -p:ContainerRepository=.apphost/ -tests4 -p:ContainerImageTag=azd-deploy-1724077852 -p:ContainerRegistry=<redacted> --getProperty:GeneratedContainerConfiguration' , exit code: 1
Additional env:
   SDK_CONTAINER_REGISTRY_UNAME=<redacted>
   SDK_CONTAINER_REGISTRY_PWORD=<redacted>
-------------------------------------stderr-------------------------------------------
MSBUILD : error MSB4166: Child node "4" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\ \AppData\Local\Temp\MSBuildTemp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
MSBUILD : error MSB4166: C:\Users\ \AppData\Local\Temp\MSBuildTemp\MSBuild_pid-16668_21c9ebe9eb16475e9a85c09e4bbe7ef7.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 16668:
MSBUILD : error MSB4166: ====================<redacted>
MSBUILD : error MSB4166: 19/08/2024 14:31:07
MSBUILD : error MSB4166: System.ArgumentNullException: Value cannot be null. (Parameter 'value')
MSBUILD : error MSB4166:    at System.ArgumentNullException.Throw(String paramName)
MSBUILD : error MSB4166:    at System.IO.BinaryWriter.Write(String value)
MSBUILD : error MSB4166:    at Microsoft.Build.Framework.TelemetryEventArgs.WriteToStream(BinaryWriter writer)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ==================<redacted>
MSBUILD : error MSB4166:
MSBUILD : error MSB4166:
Build failed. Properties, Items, and Target results cannot be obtained. See details in stderr above.
  (x) Failed: Deploying service
```

**Comment by snehapar9** [comment]
@hjblourenco thanks for the update! The provisioning status for `dotnet component` was not being updated properly. We have rolled a fix out. It will be deployed to all regions by EOW.

**Comment by rajeshkamal5050** [comment]
Fix has been rolled out - https://github.com/Azure/azure-dev/issues/4216#issuecomment-2302930986

**Comment by vitaliestirbuEvo** [comment]
I am also getting an error when running azd deploy:
`MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 38760:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 9/27/2024 11:56:54 AM
MSBUILD : error MSB4166: System.ArgumentNullException: Value cannot be null. (Parameter 'value')
MSBUILD : error MSB4166:    at System.ArgumentNullException.Throw(String paramName)
MSBUILD : error MSB4166:    at System.IO.BinaryWriter.Write(String value)
MSBUILD : error MSB4166:    at Microsoft.Build.Framework.TelemetryEventArgs.WriteToStream(BinaryWriter writer)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ===================
MSBUILD : error MSB4166:
MSBUILD : error MSB4166:
Build failed. Properties, Items, and Target results cannot be obtained. See details in stderr above.`
