### ISSUE TITLE
Composability design - UX

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#4228]

**Comment by SophCarp** [comment]
10/31 Weekly Review
Brainstormed azd add summary table: 
![Image](https://github.com/user-attachments/assets/8ca631a8-90f6-4804-88cd-0f6c7d4dbbc1)
- Discussed priority, decided sku wasn't helpful at this point in the experience. "uses" is muh more important. 

Brainstormed azd provision --preview table: 
![Image](https://github.com/user-attachments/assets/b159442a-6fca-417d-afa0-eec46df018d6)
- Shows what items are created during provision
- Separates out the "key resources" and the "supporting resources" (wording TBD). In the "Supporting Resources" added which key resources it supports. 
- The goal is to give the user a clear understanding of why this resource was created.

**Comment by SophCarp** [comment]
Design Mockup for full Add flow: 
![Image](https://github.com/user-attachments/assets/115d724d-9f62-47df-a62f-cb4094333813)

**Comment by SophCarp** [comment]
11/7/24 Update:
- brainstormed best paths for provisioning
- Updated azure.yaml preview (not captured in this screen but Okayed by all parties!
- Composability desing (for alpha/ignite) is complete. 

![Image](https://github.com/user-attachments/assets/0cdf68c0-6f55-45b5-a239-d14898c23ceb)
