### ISSUE TITLE
September Blogpost

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#4229]
- https://github.com/Azure/azure-dev/issues/509 @ellismg 
- https://github.com/Azure/azure-dev/issues/2632 @ellismg 
- https://github.com/Azure/azure-dev/issues/4144 @wbreza 
- https://github.com/Azure/azure-dev/issues/2995 @wbreza @ellismg 

@weikanglim @vhvb1989 @hemarina @kristenwomack add if anything additional needs callout in blogpost.

**Comment by gkulin** [comment]
https://github.com/Azure/azure-sdk-blog/pull/509
