### ISSUE TITLE
Fail to run `azd pipeline config --provider azdo`

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-dev#4273]
**Describe the issue:**
When running the command `azd pipeline config --provider azdo`, it fails with the following error:
![image](https://github.com/user-attachments/assets/2475ba1b-0579-47a2-9c3f-ec743065f3a1)

**Repro Steps:**

1. Run `azd init -t todo-python-mongo-terraform -b staging`.
2. Run `azd auth login`.
3. Run `azd pipeline config --provider azdo`
4. Enter the `Personal Access Token (PAT)`.

**Environment:**

- Template: `todo-python-mongo-terraform`, `todo-nodejs-mongo-terraform`, `todo-java-postgresql-terraform`.
- Azd version: `azd version 1.10.0-beta.1-daily.4086794 (commit 9445b193c91acfa2d4bcae129cb7471ecc101e11)`.
- OS: Windows, Mac, DevContainer.
- Branch: Staging.

**Expected behavior:**
`azd pipeline config --provider azdo` command can be run successfully.

@rajeshkamal5050 for notification.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you help triage this one?
