### ISSUE TITLE
Fail to run `azd pipeline config` on Codespaces

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-dev#4275]
**Describe the issue:**
When running the command `azd pipeline config`, it fails with the following error:
![image](https://github.com/user-attachments/assets/6022f512-dfe2-44ef-a09d-199212ea1edf)
According to the error prompt, run the command `gh auth login`, and encounter the following error:
![image](https://github.com/user-attachments/assets/1a11a787-3081-4f2c-9f72-89852f8bea69)

**Repro Steps:**

1. Open the Codespaces environment of the `todo-java-mongo` staging branch.
2. Install the daily version of azd.
3. Run `azd auth login`.
4. Run `azd pipeline conifg`.

**Environment:**

- Template: `todo-python-mongo-aca`, `todo-nodejs-mongo-swa-func`, `todo-java-mongo`.
- Azd version: `azd version 1.10.0-beta.1-daily.4086794 (commit 9445b193c91acfa2d4bcae129cb7471ecc101e11)`.
- OS: Codespaces.
- Branch: Staging.

**Expected behavior:**
`azd pipeline config` command can run successfully.

@rajeshkamal5050 for notification.

**Comment by jongio** [comment]
Was GH removed from the template devcontainer?

**Comment by rajeshkamal5050** [comment]
@vhvb1989 can you help triage this one?

**Comment by vhvb1989** [comment]
@jongio , azd handles/manages `gh-cli`, It is automatically installed and used by azd.

This looks like a breaking change in the `not logged in` message on the gh-cli.  We recently updated the version azd uses, which could introduce this different error and broke azd :).  I'll take a look

**Comment by vhvb1989** [comment]
Fix created
