### ISSUE TITLE
Design a template index system

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#428]
A user can scaffold out an application via templates.

Right now that list is hard-coded.

We need to be able to query and API to get the index of templates.

Cache that locally.  

i.e.  user executes

`az dev init -t foo -l csharp`

That code will try to find that template.

1. search local cache if it exists
2. query an API to try to find it
3. if not found, let them know.

We also need to inform them when a template has a new version and allow them to update the template index.  

`az dev templates update` - to update the index
`az dev templates list` - to show all the templates available

I don't want to standup a service to host this list, so I would like to keep this index on GitHub.

**Comment by savannahostrowski** [comment]
@rajeshkamal5050 @wbreza Not sure that this is needed any more with the new pluggable template sources.

**Comment by jongio** [comment]
Closing as this has been implemented with pluggable template sources
