### ISSUE TITLE
AZD cannot install bicep in Azure DevOps pipeline

### ISSUE THREAD

**Issue by mip1983** [Azure/azure-dev#4284]
**Output from `azd version`**
azd version 1.9.6 (commit 0b1a8ad350177078312141f4465ad72205d7c077)

**Describe the bug**
It seems today azd can no longer download bicep on my Azure Devops pipeline, it tries for about 6-7 minutes before throwing an error like:

"ERROR: initializing provisioning manager: initializing infrastructure provider: failed resolving IaC provider 'bicep': downloading bicep: stream error: stream ID 1; INTERNAL_ERROR; received from peer"

**To Reproduce**
Run azd provision in an Azure DevOps pipeline.

**Expected behavior**
Normal operation of azd provision without error

**Additional context**
Started 02 Sept 2024

**Comment by rajeshkamal5050** [comment]
@v-xuto can you try reproducing this? cc @vhvb1989

**Comment by vhvb1989** [comment]
just tried to repro but it did work on my side:

![image](https://github.com/user-attachments/assets/2f8144b7-b03b-4b90-87e9-b1df62248b6a)

Can you check if you are still seeing this @mip1983 ?  (in case it was sporadic) .  If you keep seeing this, I wonder if there might be some proxy-access rules applied to your Azdo org/project?

**Comment by faynef** [comment]
@rajeshkamal5050 Unable to reproduce the issue, download bicep on Azure Devops pipeline successful.
![image](https://github.com/user-attachments/assets/807a672b-9fc0-438f-a9eb-b6eb6eec77e1)
