### ISSUE TITLE
[WebToolsE2E][Aspire] When using VS and azd v1.10.0 to publish an Aspire project, it displays 'Failed to refresh environment'.

### ISSUE THREAD

**Issue by v-reinawang** [Azure/azure-dev#4296]
**REPRO STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.11.2 (Include Aspire 8.1.0) and azd [1.9.6]
3. New project > .NET Aspire Starter App > .NET 8.0 (Long Term Support) > Create
4. Right click the AppHost project > Publish the project to ACA, this project can be successfully published
5. Now update azd version from 1.9.6 to 1.10.0, and repeat steps 3 and 4

**ACTUAL**
Failed to refresh environment.
Error container: cannot make azureResourceManager field
![image](https://github.com/user-attachments/assets/d7170c1b-ede5-407e-a4c7-fa9dc9d8f2b2)

**Expected behavior**
The environment can be refreshed successfully without any errors.
![image](https://github.com/user-attachments/assets/45db0e35-9272-438a-8353-2d01e746017d)

**Comment by v-elenafeng** [comment]
Hi @rajeshkamal5050, could you please take a look at this issue? It reproes with the latest released azd 1.10.0 and blocks Aspire publish from VS.

**Comment by v-reinawang** [comment]
This issue has been fixed in the latest released azd 1.10.1.
