### ISSUE TITLE
[Issue] azd commands fail when default output from Azure CLI is not json

### ISSUE THREAD

**Issue by crvillanueva** [Azure/azure-dev#432]
When running any command (ex.: `azd init`) it gives an error if the default output from Azure CLI is not JSON:

```
  Error: required external tools are missing:
 - error checking for external tool Azure CLI: checking Azure CLI version:  invalid character 'A' looking for beginning of value
```
I had to set `az config set core.output=json` for the commands to work. It would be nice if in the app used `az version --output=json` instead of the azure cli user default.

**Comment by savannahostrowski** [comment]
@rajeshkamal5050	are you able to reproduce this?

**Comment by rajeshkamal5050** [comment]
Azd no more depends on Az CLI.
