### ISSUE TITLE
bicep/terraform starters containing `azure-dev.yml` workflow files

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#4344]
With #4013 landed, should we remove workflows from the starters (i.e. bicep starter, terraform starter) that don't have application code in them? They should look exactly the same as what `azd pipeline config` would generate when it runs (we should verify if it doesn't match).

The template repositories:
- [Bicep starter](https://github.com/Azure-Samples/azd-starter-bicep)
- [Terrraform starter](https://github.com/Azure-Samples/azd-starter-terraform)

There are four files under the [templates/common](https://github.com/Azure/azure-dev/blob/d91c73968473a807d992560ab6db5b6a192a1447/templates/common) directory I believe that could be removed with this change.

**Comment by weikanglim** [comment]
@jongio if this makes sense to you.

**Comment by v-xuto** [comment]
@rajeshkamal5050 Regarding Wei's [comment](https://github.com/Azure/azure-dev/issues/4344#issuecomment-2359589241) above, should we wait for Jongio's feedback, or should we directly submit a PR for this issue?

**Comment by rajeshkamal5050** [comment]
@jongio can remove the static workflow files gives its part of azd pipeline?

**Comment by rajeshkamal5050** [comment]
@v-xuto can you put out a PR for this?

**Comment by v-xuto** [comment]
> @v-xuto can you put out a PR for this?

@rajeshkamal5050 PR is ready, please review.

- PR link: https://github.com/Azure/azure-dev/pull/4412
