### ISSUE TITLE
engsys: notice generation failing in CI

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#4345]
The build that generates NOTICE.txt is failing in CI. Here's an example [failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4148787&view=logs&j=51fca66c-d965-54db-3c7b-c40df3b9bc52&t=de8f58a9-f606-5bcb-6460-6c94eb67ad3a&l=12)

**Comment by danieljurek** [comment]
Configuration error. Fixed in DevOps. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4157656&view=results
