### ISSUE TITLE
Adding alpha feature for Aspire to persist CORS

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#4395]

**Comment by rajeshkamal5050** [comment]
@vhvb1989 won't this be taken care of with the Aspire 9.0 container app customization?

**Comment by vhvb1989** [comment]
@rajeshkamal5050 , yes, but not until Aspire 9 is released.

And we need to decide if we will remove the alpha features we have for persisting settings and ask folks to move to use Aspire to customize or if we want to keep it for some time as deprecated

**Comment by rajeshkamal5050** [comment]
@vhvb1989 @ellismg Can we deprecate the features which are now handled as part of Aspire App Model/Host itself?

> ex: WARNING: `feature` is deprecated, instead use `ContainerResource` application model.

**Comment by vhvb1989** [comment]
Closing this as not needed anymore. The path to customizing ACA is set for Aspire9 by using the AppHost + Azure Provisioning libraries
