### ISSUE TITLE
Errors during the `azd init` - an issue with az installation

### ISSUE THREAD

**Issue by karolz-ms** [Azure/azure-dev#441]
### Discussed in https://github.com/Azure/azure-dev/discussions/439

<div type='discussions-op-text'>

<sup>Originally posted by **NikiforovAll** August  7, 2022</sup>
Hi,

I encountered the issue with `azd` usage. It looks like I'm lacking `az` installed, but I have it installed on my machine. Any ideas on how to fix it?

![image](https://user-images.githubusercontent.com/8037439/183285032-90ed6a2a-5f73-4897-a9a9-898920185d5b.png)

### Environment:

Windows Terminal + GitBash

```bash
/d/dev/azd-cosmos-todo
$ where azd
C:\Users\Oleksii_Nikiforov\AppData\Local\Programs\Azure Dev CLI\azd.exe
/d/dev/azd-cosmos-todo
$ where az
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd
/d/dev/azd-cosmos-todo
$ az version
Azure-cli    Azure-cli-core    Azure-cli-telemetry
-----------  ----------------  ---------------------
2.39.0       2.39.0            1.0.6
/d/dev/azd-cosmos-todo
$ azd version
azd version 0.1.0-beta.3 (commit 77ab01c3bcf40d12852d543506ecbb935a779f81)
/d/dev/azd-cosmos-todo
$ echo $SHELL
/usr/bin/bash
```</div>

**Comment by karolz-ms** [comment]
Thank you, Oleksii, for reporting this issue and helping us make Azure Dev CLI better. 

I think we have a bug in the tool. Specifically, when we query for Azure CLI version, we do not enforce JSON output: https://github.com/Azure/azure-dev/blob/main/cli/azd/pkg/tools/azcli.go#L354

**Comment by tonybaloney** [comment]
Workaround:

Run az configure and set the default output as json:

```console
> az configure
```
