### ISSUE TITLE
Does AZD lifecycle support multiple subscriptions

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-dev#4428]
## Question
When I use azd to provision resources, I need to provision some azure resources `subscription-A` and some other resources in subscription-B,
but it seems when I try to run command `azd down`, azd can't find all the resources in both `subscription-A`  and `subscription-B`

Below is the sample `infra/main.bicep`

```
targetScope = 'subscription'

param location string

@minLength(1)
@maxLength(64)
@description('Name of the the environment which is used to generate a short unique hash used in all resources.')
param environmentName string

// tags that should be applied to all resources.
var tags = {
  // Tag all resources with the environment name.
  'azd-env-name': environmentName
}

module resourceInSubA './rg-module-1.bicep' = {
  name: 'deployToSubA'
  scope: subscription('subscription-id')
  params: {
    location: location
    rg: 'rgFor1021-SubA'
    tags: tags
  }
}

module resourceInSubB './rg-module-2.bicep' = {
  name: 'deployToSubB'
  scope: subscription('subscription-id')
  params: {
    location: location
    rg: 'rgFor1021-SubB'
    tags: tags
  }
}

```

**Comment by rajeshkamal5050** [comment]
@backwind1233 does provision and deploy works fine? only azd down fails? cc @ellismg @wbreza

**Comment by backwind1233** [comment]
Hello @rajeshkamal5050 
Yes, azd provsion works, I didn't test azd deploy, but azd down failed.

**Comment by backwind1233** [comment]
You need to use an account with multiple subscriptions to test this case.

**Comment by wbreza** [comment]
Hi @backwind1233  - we recently released an alpha feature that leverages [Azure Deployment Stacks](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deployment-stacks?tabs=azure-powershell) which solves some ARM deployments that use more complex configurations.

To opt-in for deployment stacks you can run the following command:
```bash
azd config set alpha.deployment.stacks on
```

Then just run `azd provision` which will move associate your resources with a deployment stack which makes cleanup (`azd down`) more predictable.

You can also read more about it from in a recent [blog post](https://devblogs.microsoft.com/azure-sdk/azure-developer-cli-azd-september-2024/#alpha-feature:-deployment-stacks-support).

Please try this out with your use case and let us know if this resolves your issue.

**Comment by backwind1233** [comment]
![Image](https://github.com/user-attachments/assets/6874121d-b0c2-4902-9f86-4251812291cd)

It seems work, thank you @wbreza
