### ISSUE TITLE
[Issue] WinGet upgrade does not have 1.10.2

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#4429]
Issue caused by publishing issues with WinGet: https://github.com/microsoft/winget-pkgs/issues/180404

Running `winget upgraded Microsoft.Azd` fails with the error message: 

```pwsh
> winget upgrade Microsoft.Azd
No available upgrade found.
No newer package versions are available from the configured sources.
```

## Workaround

Upgrade azd directly using the PowerShell script: 

```pwsh 
powershell -ex AllSigned -c "Invoke-RestMethod 'https://aka.ms/install-azd.ps1' | Invoke-Expression"
```

Future upgrade notices may recommend using the `install-azd.ps1` script but these can be ignored once WinGet publishing issues are resolved.

## More issue details

Running `winget show Microsoft.Azd` also shows that only 1.10.1 is available and not the recently released 1.10.2.  

```pwsh
> winget show Microsoft.Azd
Found Azure Developer CLI [Microsoft.Azd]
Version: 1.10.200
Publisher: Microsoft Corporation
Publisher Url: https://github.com/Azure/azure-dev/
Publisher Support Url: https://github.com/Azure/azure-dev/issues
Moniker: azd
Description: A developer CLI that accelerates the time it takes for you to get started on Azure. The Azure Developer CLI (azd) provides a set of developer-friendly commands that map to key stages in your workflow - code, build, deploy, monitor, repeat.
Homepage: https://github.com/Azure/azure-dev/releases/tag/azure-dev-cli_0.6.0-beta.2
License: MIT License
License Url: https://github.com/Azure/azure-dev/blob/main/LICENSE
Privacy Url: https://go.microsoft.com/fwlink/?LinkId=521839
Copyright: Copyright 2022 (c) Microsoft Corporation.
Release Notes Url: https://github.com/Azure/azure-dev/releases/tag/azure-dev-cli_1.10.1
Documentation:
  Wiki: https://github.com/Azure/azure-dev/wiki
Tags:
  azure
  hacktoberfest
  microsoft
Installer:
  Installer Type: wix
  Installer Locale: en-US
  Installer Url: https://github.com/Azure/azure-dev/releases/download/azure-dev-cli_1.10.1/azd-windows-amd64.msi
  Installer SHA256: 769e44e7cbef172079685a71f18c5f9dc800338f1b1c26117b4eeae5aa35fc18
  Release Date: 2024-09-06
  Offline Distribution Supported: true
```

**Comment by brandonh-msft** [comment]
> Same here, I downloaded and installed the latest release from [releases](https://github.com/Azure/azure-dev/releases/tag/azure-dev-cli_1.10.2)
> 
> ```
> PS C:\> azd version
> azd version 1.10.1 (commit 31409a33266fb4a5fdbb644bc83988e725d6c7c9)
> WARNING: your version of azd is out of date, you have 1.10.1 and the latest version is 1.10.2
> 
> To update to the latest version, run:
> winget upgrade Microsoft.Azd
> PS C:\> winget upgrade microsoft.azd
> No available upgrade found.
> No newer package versions are available from the configured sources.
> ```

ha - was coming to post this exact same output lol

**Comment by danieljurek** [comment]
WinGet is addressed and closed. WinGet now properly upgrades azd to 1.10.2. Closing this issue.
