### ISSUE TITLE
easy-init: azd should auto detect port from Dockerfile

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#4443]
After discussion with @puicchan:

1. Look in Dockerfile
2. If EXPOSE with single port is found, use it and don't ask
3. If EXPOSE is not found, ask the customer.
4. If more than one port is exposed, prompt for a selection (`console.Select`) with the multiple ports available, and an "Other" selection to provide the port number.
   
Multiple ports example:
```bash
Select a port number:
- 5050 
- 8080
- Other
```

**Comment by rujche** [comment]
FYI: 

1. PR is coming soon, and the PR is targeting to main branch. 
2. Reference PR: https://github.com/saragluna/azure-dev/pull/10/files
