### ISSUE TITLE
Azd deploy fails to access container registry in private network

### ISSUE THREAD

**Issue by shankersumit** [Azure/azure-dev#4453]
i am unable to deploy the microservice in container apps as "azd deploy" fails to access container registry in private network.
Our infra is hosted in secure landing zone and mms standards doesnt allow us to keep the acr resource in public network.

ERROR: failed deploying service 'TradeService': remote build failed: 2024/10/17 11:46:31 Downloading source code...
2024/10/17 11:46:32 Finished downloading source code
2024/10/17 11:46:32 Using acb_vol_21368d0d-ab76-426f-8525-fc8abc186630 as the home volume
2024/10/17 11:46:32 Setting up Docker configuration...
2024/10/17 11:46:33 Successfully set up Docker configuration
2024/10/17 11:46:33 Logging in to registry: dmpdevwecontainerregistry.azurecr.io
failed to login, ran out of retries: failed to set docker credentials: Error response from daemon: Get "[https://dmpdevwecontainerregistry.azurecr.io/v2/"](https://***.azurecr.io/v2/%22): denied: client with IP '13.69.110.34' is not allowed access. Refer https://aka.ms/acr/firewall to grant access.
: exit status 1
Run ID: cb9 failed after 7s. Error: failed during run, err: exit status 1

client with IP '13.69.110.34' seems to be from microsoft backbone network.

**Comment by vhvb1989** [comment]
It looks like you are trying to use `remote build`.  Have you tried local build?   IIRC, local build would use docker authentication to log in to the ACR, so as long as you can login docker to it, then azd should be able to.

@ellismg , is there anything we can do for remote build here?  Would a proxy work?

**Comment by shankersumit** [comment]
Hi @vhvb1989 

My acr is in private network and I am using private endpoint to access the acr from my ado agent. 

I have even tried removing the remote build,  and tried accessing the acr via private endpoint and managed identity with acrPull role.

But no luck so far. It only works when acr is in public network.

For production grade application  , specially in secure landing zone , we would like to access our acr using private endpoint only.

Please let me know if there is any environment variable which can help or any steps that you recommend ?

**Comment by vhvb1989** [comment]
Have you tried using [Azure Bastion](https://learn.microsoft.com/azure/bastion/bastion-overview) ?

In summary, you would create a VM inside your private network and then set up bastion as the way to connect to that VM.
From that VM you would be able to run azd and access the ACR, as it would be inside the same private network.

Now, for running from Azure DevOps, you might need to use self-host to tell Azure DevOps to run pipelines in the VM which has access to the private network.  I've never done this, but looks like some folks have [tried it](https://stackoverflow.com/questions/66033403/how-to-access-azure-vm-from-azuredevops-pipelines)

**Comment by shankersumit** [comment]
Hi @vhvb1989 

Both Ado agent subnet and Acr private endpoint is part of the same vnet .
So I don't think azure bastion is required in my case.

I just needed to know whether azd supports the connection to acr via private endpoint using manages identity ? 

The ip mentioned above is part of microsoft service tag for ACR.

**Comment by shankersumit** [comment]
Hi @ellismg  @vhvb1989 

I have tried to set the remotebuild: false in azure . yaml after which i am able to build and push the image to acr using azd cli but i am getting below error when it is trying to deploy to container apps


![Image](https://github.com/user-attachments/assets/c908cd97-b7aa-4dd7-9bad-ccb0c4a70686)

![Image](https://github.com/user-attachments/assets/0b1e4122-f827-4319-93fb-ea2a4325fa25)

![Image](https://github.com/user-attachments/assets/47a5c0ee-cd6a-494a-8631-ca212b28e3c6)

**Comment by shankersumit** [comment]
Hi @ellismg  @vhvb1989 

I am able to deploy the container apps now.

But the only issue that i see is daprd containers are not starting. 
Could you please guide me on this where i should check and update daprd configurations
 
![Image](https://github.com/user-attachments/assets/2a9f111a-2d6c-45e5-a971-7a17f70edb56)

**Comment by vhvb1989** [comment]
Is your project using .NET Aspire?  or how are you defining your DAPR containers?  directly in bicep?

I am not sure if azd supports DAPR containers for non-Aspire projects. @wbreza , do you know?

**Comment by shankersumit** [comment]
Yes my project is dotnet aspire. I am able to fix the above issue from my end .

Thank you.
