### ISSUE TITLE
[Issue] azd 1.10.3 for arm64 reported as a virus by defender

### ISSUE THREAD

**Issue by oising** [Azure/azure-dev#4463]
Downloading https://github.com/Azure/azure-dev/releases/download/azure-dev-cli_1.10.3/azd-windows-arm64-alpha.zip results in a (false positive, I'd hope) for a virus:

![Image](https://github.com/user-attachments/assets/c8f05794-8c9f-4628-a245-2c16a131d0d9)

I'm on an SL7 ARM64.

**Comment by danieljurek** [comment]
Thanks for reporting, @oising. The Windows Defender team has investigated the issue and determined that the detection is a false-positive. They've updated definitions on their side. 

To clean your cache and ensure you have the latest definitions follow these instructions to trigger an update here: [https://www.microsoft.com/en-us/wdsi/definitions](https://www.microsoft.com/en-us/wdsi/defenderupdates).

Closing the issue.
