### ISSUE TITLE
azd MSI

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#447]
* [x] Do we want per-user or per-machine install? 
* [x] License dialog
* [ ] Custom install location? (we allow this today in our install scripts, I'm assuming we should allow this in the MSI as well) 

GitHub CLI is an example here.

**Comment by karolz-ms** [comment]
Per-user please ☺️

**Comment by savannahostrowski** [comment]
@rajeshkamal5050 @danieljurek This isn't assigned to any milestone etc. but I assume that this is good to release in January (putting together the blog post)?

**Comment by danieljurek** [comment]
This is good to release in January

**Comment by jongio** [comment]
Nice!!!

**Comment by rajeshkamal5050** [comment]
MSI installer is released as part of 0.5.0-Beta. Marking it as complete
