### ISSUE TITLE
Audit previous alpha features that were released without official docs support

### ISSUE THREAD

**Issue by gkulin** [Azure/azure-dev#4476]

**Comment by gkulin** [comment]
### Alpha features mentioned in 2024 blog posts:
- Support for Helm and Kustomize for AKS service target [(azure-dev#3196)](https://github.com/Azure/azure-dev/pull/3196)
- Alpha support for Windows Arm64 [(azure-dev#3968)](https://github.com/Azure/azure-dev/issues/3968)
- Alpha support for persistent session affinity and domains for Azure Container Apps (ACA) [(azure-dev#3955)](https://github.com/Azure/azure-dev/pull/3955) 
- Alpha feature: Deployment stacks [(azure-dev#4144)](https://github.com/Azure/azure-dev/issues/4144)

**Comment by kristenwomack** [comment]
Audit is complete, opened an issue to document persistent session affinity alpha support [here](https://dev.azure.com/msft-skilling/Content/_workitems/edit/356389).
