### ISSUE TITLE
[Issue] Install AZD pipeline task depends on a version of node that is end of life

### ISSUE THREAD

**Issue by markwragg** [Azure/azure-dev#4492]
The setup-azd@0 task now causes this warning to appear in Azure DevOps pipelines, advising that it relies a version of Node that is end of life:

##[warning]Task 'Setup Azure Developer CLI' version 0 (setup-azd@0) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

Can the task please be updated.

**Comment by vhvb1989** [comment]
@markwragg , I have released version 0.14 https://marketplace.visualstudio.com/items?itemName=ms-azuretools.azd
Can you please check if the Warning is gone?  (It might take a little longer for me to run a e2e test and validate)
