### ISSUE TITLE
Github Enterprise Managed user can't see the public issues while trying to login using the Github Enterprise account.

### ISSUE THREAD

**Issue by swissrerakeshv** [Azure/azure-dev#4510]
A GitHub Enterprise Managed User (GHEM) is experiencing difficulties accessing public issues on GitHub Community repositories. Despite attempting to view these issues, the user is unable to do so. Additionally, the user logs into their GitHub Enterprise account using Single Sign-On (SSO). We need assistance in resolving this issue to allow the user to access public issues on GitHub.

**Comment by rajeshkamal5050** [comment]
@swissrerakeshv this doesn't seem to be related to AZD. Seems to be a GitHub issue. Please file it here - https://support.github.com/ ref: https://docs.github.com/en/enterprise-cloud@latest/support/contacting-github-support/creating-a-support-ticket
