### ISSUE TITLE
CI/CD test fail - TestDefaultDockerOptions

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#453]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1771695&view=logs&j=dc5bf7c0-035c-5026-d13f-d96165097be5&t=9a1bed46-3cbe-5923-1ee5-60ccc8ec613f&l=172

=== RUN   TestDefaultDockerOptions
2022/08/10 17:13:16 Parsing file contents, 
name: test-proj
metadata:
  template: test-proj-template
resourceGroup: rg-test
services:
  web:
    project: src/web
    language: js
    host: containerapp

2022/08/10 17:13:26 Expecting only '1' resource match to override resource name but found '0'
2022/08/10 17:13:26 building image for service web, cwd: src/web, path: ./Dockerfile, context: .)
2022/08/10 17:13:26 built image imageId for web
    framework_service_docker_test.go:74: 
        	Error Trace:	framework_service_docker_test.go:74
        	Error:      	"[]" should have 1 item(s), but has 0
        	Test:       	TestDefaultDockerOptions
--- FAIL: TestDefaultDockerOptions (10.01s)

**Comment by weikanglim** [comment]
Fixed by #223. I don't see any new failures in the last 14 days: https://dev.azure.com/azure-sdk/internal/_test/analytics?definitionId=4643&contextType=build
