### ISSUE TITLE
[CI/CD test fail] - Test_CLI_ResourceGroupNameWithMultipleMatches

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#454]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1771695&view=logs&j=3eb4d8a5-5d97-562b-c71d-6ac568d84486&t=02dec852-6265-5e32-1c63-ad2bb341bf1e&l=906

=== RUN   Test_CLI_ResourceGroupNameWithMultipleMatches
    cli_test.go:170: DIR: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Test_CLI_ResourceGroupNameWithMultipleMatches2108747844/001
    cli_test.go:173: AZURE_ENV_NAME: azdtest-0bbd886
    cli.go:67: [out] Please enter a new environment name: Please select an Azure location to use (or hit enter to use the default 42. (US) East US 2 (eastus2)): Please select an Azure Subscription to use (or hit enter to use the default  3. Azure SDK Test Resources (***)): 
    cli.go:96: [heartbeat] command azd infra create in /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Test_CLI_ResourceGroupNameWithMultipleMatches2108747844/001 is still running after 10.000965202s
    cli.go:96: [heartbeat] command azd infra create in /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Test_CLI_ResourceGroupNameWithMultipleMatches2108747844/001 is still running after 20.00949782s
    cli.go:96: [heartbeat] command azd infra create in /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Test_CLI_ResourceGroupNameWithMultipleMatches2108747844/001 is still running after 30.01311819s
    cli.go:96: [heartbeat] command azd infra create in /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Test_CLI_ResourceGroupNameWithMultipleMatches2108747844/001 is still running after 40.12246275s
    cli.go:96: [heartbeat] command azd infra create in /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Test_CLI_ResourceGroupNameWithMultipleMatches2108747844/001 is still running after 50.157953448s
    cli.go:96: [heartbeat] command azd infra create in /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Test_CLI_ResourceGroupNameWithMultipleMatches2108747844/001 is still running after 1m0.169777401s
    cli.go:67: [out] Provisioning Azure resources can take some time.
    cli.go:67: [out] 
    cli.go:67: [out] You can view detailed progress in the Azure Portal:
    cli.go:67: [out] https://portal.azure.com/#blade/HubsExtension/DeploymentDetailsBlade/overview/id/%2Fsubscriptions%2F***%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Fazdtest-0bbd886
    cli.go:67: [out] 
    cli.go:67: [out] Creating Azure resources |
    cli.go:67: [out] Creating Azure resources /
    cli.go:67: [out] Creating Azure resources -
    cli.go:67: [out] Creating Azure resources \
    cli.go:67: [out] Created Azure resources
    cli.go:67: [out] 
2022/08/10 17:19:31 RunWithResult exec: 'az account get-access-token --output json'
2022/08/10 17:19:37 RunWithResult exec: 'az account get-access-token --output json'
2022/08/10 17:19:43 RunWithResult exec: 'az account get-access-token --output json'
    cli_test.go:213: 
        	Error Trace:	cli_test.go:213
        	            				cli_test.go:138
        	Error:      	An error is expected but got nil.
        	Test:       	Test_CLI_ResourceGroupNameWithMultipleMatches
--- FAIL: Test_CLI_ResourceGroupNameWithMultipleMatches (82.40s)

**Comment by vhvb1989** [comment]
happened again here:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1814385&view=logs&j=3eb4d8a5-5d97-562b-c71d-6ac568d84486&t=194ce494-74fe-505f-c2a4-2f5966806cf4&l=70

**Comment by weikanglim** [comment]
This class of issues should be fixed with recent changes. Unfortunately, we don't have clear data showing this: https://dev.azure.com/azure-sdk/internal/_test/analytics?definitionId=4643&contextType=build given a separate issue we found with TempDir.Remove failing. This was also fixed recently.
