### ISSUE TITLE
An unhandled error has occurred after building project

### ISSUE THREAD

**Issue by LucaOtto** [Azure/azure-dev#4571]
I keep getting this error, tried on two different computers and installed dependencies from scratch. 

See screenshots below:

![Image](https://github.com/user-attachments/assets/b0739892-faaa-44a2-a222-28ca11a8714f)

In VSCode I'm seeing these errors

![Image](https://github.com/user-attachments/assets/c5bd8b05-6e23-42c6-9ea4-53f58a3420b4)
![Image](https://github.com/user-attachments/assets/9d49abbe-085e-4081-b819-bc722e7898cc)
![Image](https://github.com/user-attachments/assets/e32e30a9-a737-4526-90c6-aa196bebcb5d)

**Comment by rajeshkamal5050** [comment]
Looks like an aspire dashboard issue when using locally doubt there isn't anything related to azd here.

Can you report the issue under Aspire - https://github.com/dotnet/aspire

@vhvb1989 @karolz-ms

**Comment by vhvb1989** [comment]
You need to make your OS to trust the dotnet certificates. See: https://learn.microsoft.com/dotnet/core/tools/dotnet-dev-certs?form=MG0AV3

You might just need to run `dotnet dev-certs https` and `dotnet dev-certs https --trust`. 

The Dashboard runs on HTTPS using local signed certificates from dotnet. Your OS is currently rejecting them.
