### ISSUE TITLE
[Issue] Azure Container Apps for .NET apps should have the default targetPort of 8080, instead of 80

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-dev#4583]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

`azd version 1.11.0 (commit 5b92e0687e1fa96dfc8292f4b900c0c58610b6a5)`

**Describe the bug**
Description of issue you're seeing...

- When I run `azd init` for a .NET app, it automatically generates Bicep files.
- The auto-generated bicep file, `resources.bicep` has invalid target port number of `80`.
  👉 .NET apps should have the target port of `8080`. ([Reference](https://learn.microsoft.com/dotnet/core/compatibility/containers/8.0/aspnet-port))

    ```bicep
    module eshopliteStore 'br/public:avm/res/app/container-app:0.8.0' = {
      name: 'xxxxx'
      params: {
        name: 'xxxxx'
        ingressTargetPort: 80
        ...
        containers: [
          {
            ...
            env: union([
              ...
              {
                name: 'PORT'
                value: '80'
              }
            ],
    ...
    ```

- It's because the following code sets the default port number to `80` except for Java apps.

  https://github.com/Azure/azure-dev/blob/67098119bba70c83485134773ec2c68b53abd568/cli/azd/internal/cmd/add/add_configure_host.go#L238-L244

  It should also be applied to .NET apps like:

    ```go
    if ( svc.Language == project.ServiceLanguageJava || svc.Language == project.ServiceLanguageDotNet ) {
        props.Port = 8080 
    } 
    ```

**To Reproduce**
Steps to reproduce the behavior...

1. Create an ASP.NET app or Blazor app
2. Run `azd init`
3. Check the auto-generated bicep file, `resources.bicep` whether the `ingressTargetPort` value is `80` or not
4. Check the auto-generated bicep file, `resources.bicep` whether the `env.PORT` value is `80` or not

**Expected behavior**

Both `ingressTargetPort` and `env.PORT` values should be `8080`.

**Environment**
Information on your environment:
    * Language name and version: .NET 9
    * IDE and version : VS Code (Dev Container)

**Comment by weikanglim** [comment]
@justinyoo Just wondering... did the container app fail to run?

The default port of `80` is coming from the azd builder for Dockerless build -- feel free to modify it to suit your needs.

```
		// Always default to port 80 for consistency across languages
		environ = append(environ, "ORYX_RUNTIME_PORT=80")
 ```

That being said, we have #4573 to switch over to native dotnet builds, which this feedback is very much applicable -- we'll make the change as part of this.

**Comment by justinyoo** [comment]
@ellismg That's good to know. Thanks!
