### ISSUE TITLE
azd provision in Azure Pipeline not detecting existing service

### ISSUE THREAD

**Issue by johnnyreilly** [Azure/azure-dev#4593]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
1.11.0

**Describe the bug**

I'm not sure if this is a regression, or if this never actually worked and I deceived myself that it did.

Upon reflection, our usage of a default value for `SERVICE_WEB_RESOURCE_EXISTS` has perhaps served us poorly - it means we're not aware if behaviour changes.

```bicep
// azd will provide the following parameters
param containerAppExists = bool(readEnvironmentVariable('SERVICE_WEB_RESOURCE_EXISTS', 'false'))
```

In this blog post I explain how to use AZD to speed up incremental deployments of container apps in Azure Pipelines: https://johnnyreilly.com/using-azd-for-faster-incremental-azure-container-app-deployments-in-azure-devops

However, part of the mechanism describes the "magic" environment variables provided by `azd provision`. These are variables like `SERVICE_WEB_RESOURCE_EXISTS` and the mechanism for providing them can be found here:

https://github.com/Azure/azure-dev/blob/837d4e8592c53375c7d9aa6df8b134c23cdeb487/cli/azd/pkg/project/service_target_containerapp.go#L174-L190

However, regardless of the existence of a container app, AZD is reliably providing `false` where it should be providing `true` when a service exists 

**To Reproduce**

Follow the steps in this blog post: https://johnnyreilly.com/using-azd-for-faster-incremental-azure-container-app-deployments-in-azure-devops

After the initial deployment, log into the portal to look at the root deployment created by azd. Look at the inputs and you should see a `SERVICE_WEB_RESOURCE_EXISTS` that is reliably `false`

**Expected behavior**

After the initial deployment, log into the portal to look at the root deployment created by azd. Look at the inputs and you should see a `SERVICE_WEB_RESOURCE_EXISTS` that is reliably `true` once the service exists.

**Environment**
Azure Pipelines 

**Additional context**
The blog post linked covers a good amount of this context

It's possible to work around this issue by creating the variable by hand - here's an example:

```bash
- task: AzureCLI@2
  displayName: Check container app exists # see https://github.com/Azure/azure-dev/issues/4593 for context on why this exists
  inputs:
      azureSubscription: ${{ variables.serviceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
          if az containerapp show --name "$(zgptZebraGptContainerApps)" --resource-group "$(resourceGroupName)" > /dev/null 2>&1; then
              echo "SERVICE_APP_RESOURCE_EXISTS: true"
              echo "##vso[task.setvariable variable=SERVICE_APP_RESOURCE_EXISTS]true"
          else
              echo "SERVICE_APP_RESOURCE_EXISTS: false"
              echo "##vso[task.setvariable variable=SERVICE_APP_RESOURCE_EXISTS]false"
          fi

- task: AzureCLI@2
  displayName: Provision Infra
  inputs:
      azureSubscription: ${{ variables.serviceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      ${{ if eq(parameters.forceDeployInfra, true) }}:
          inlineScript: azd provision --no-prompt --no-state
      ${{ else }}:
          inlineScript: azd provision --no-prompt
  env:
# ....
    SERVICE_APP_RESOURCE_EXISTS: $(SERVICE_APP_RESOURCE_EXISTS)

```

It feels wrong that we should be doing this though.

**Comment by v-xuto** [comment]
We are following up on this issue. cc @rajeshkamal5050

**Comment by johnnyreilly** [comment]
Possibly linked to https://github.com/Azure/azure-dev/issues/4402 ?

**Comment by Menghua1** [comment]
@johnnyreilly Yes, this is the same issue as https://github.com/Azure/azure-dev/issues/4402, so we will close this issue and we can discuss it in https://github.com/Azure/azure-dev/issues/4402.
