### ISSUE TITLE
[Issue] `azd init` hangs inside WSL

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#460]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 0.1.0-beta.3 (commit 77ab01c3bcf40d12852d543506ecbb935a779f81)

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

**Describe the bug**
When the user isn't logged into azure CLI, running `azd init` hangs on `az login`.

**To Reproduce**
1. In WSL, run `az logout`
2. Run `azd init` in an empty folder
3. Specify a template (if needed) and an environment name
4. `azd` hangs forever

**Expected behavior**
`azd` should print out the device code since there isn't autolaunch browser support in WSL.

**Environment**
Information on your environment:
    * WSL Ubuntu 22.04

**Additional context**

**Comment by savannahostrowski** [comment]
I can't repro this anymore. Does this still persist for you @weikanglim?

**Comment by vhvb1989** [comment]
IIRC, we are not failling if we run any command (like init or up) and we did not log in first.

**Comment by weikanglim** [comment]
This is mostly fixed with the `azd login` changes to not depend on `az`
