### ISSUE TITLE
[Issue] If the AZ cli is configured for non-json output, commands may fail

### ISSUE THREAD

**Issue by Petermarcu** [Azure/azure-dev#462]
We should make sure we are explicitly asking for json output on all our az calls. We should run all our tests with the CLI configured with a different default to find other cases like in issue #441

**Comment by ellismg** [comment]
Let's also consider modifying `runAzCommand` so that it forces json output (instead of requiring us to pass `--output json` for each command.  For the few cases where we run `az` and need non json output, `runAzCommandWithArgs` exists and we can ensure via inspection that `--output` is passed.
