### ISSUE TITLE
azd does not support azure government

### ISSUE THREAD

**Issue by KevinDMack** [Azure/azure-dev#4637]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 1.11.0 (commit 5b92e0687e1fa96dfc8292f4b900c0c58610b6a5)

**Describe the bug**
In azure cli, I can run the command az cloud set --name AzureUSGovernment, but there does not seem to be an equivalent for azd.  

**To Reproduce**
Steps to reproduce the behavior...
If I try to run azd up, it tries to hit commercial.  There are no flags that I can find that point to azure government.  

**Expected behavior**
I would expect there to be an option.  

**Environment**
Information on your environment:
    * Language name and version
    * IDE and version : vscode

**Additional context**
N/A

**Comment by rajeshkamal5050** [comment]
@KevinDMack thanks for reporting cc @danieljurek 

Did you try this?

> azd config set cloud.name AzureUSGovernment
> azd auth login

Ref: https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/sovereign-clouds

**Comment by KevinDMack** [comment]
Yep that absolutely worked thank so much.
