### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by AlHasSaN0ALi** [Azure/azure-dev#4648]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azure-dev.commands.cli.provision
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'configurationFile')

Version: 0.8.4
OS: win32
OS Release: 10.0.26100
Product: Visual Studio Code
Product Version: 1.96.2
Language: en

<details>
<summary>Call Stack</summary>

```
provision extension.js:2:896098
extension.js:2:896767extension.js:2:896767
extension.js:2:58762extension.js:2:58762
extension.js:2:10404extension.js:2:10404
extension.js:2:9229extension.js:2:9229
_ extension.js:2:8915
callWithTelemetryAndErrorHandling extension.js:2:10311
extension.js:2:58480extension.js:2:58480
extension.js:2:58015extension.js:2:58015
_ extension.js:2:57701
extension.js:2:58291extension.js:2:58291
cw.h extensionHostProcess.js:115:32833
cw.g extensionHostProcess.js:115:31910
cw.executeCommand extensionHostProcess.js:115:31817
Object.executeCommand extensionHostProcess.js:157:37484
extension.bundle.js:2:1769624extension.bundle.js:2:1769624
fulfilled extension.bundle.js:2:1768341
```

</details>

**Comment by NanaXiong00** [comment]
@AlHasSaN0ALi Could you please provide more specific information, such as the complete project code and detailed reproduction steps, so that we can reproduce this issue?

**Comment by vhvb1989** [comment]
Seems like an auto-created issue with not enough data. I am closing this. Please re-open with more information if this was a real issue
