### ISSUE TITLE
As a developer, I can use azd in Cloud Shell

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#472]
I should be able to run azd in cloud shell.

**Comment by jongio** [comment]
@danieljurek  - Can you investigate what it would take for us to get azd in cloud shell?

Repo: https://github.com/Azure/CloudShell
Example: https://github.com/Azure/CloudShell/pull/197

**Comment by danieljurek** [comment]
Addressed in https://github.com/Azure/CloudShell/pull/248

**Comment by danieljurek** [comment]
Running in the context of CloudShell we may not have all tools installed for all possible deployments. Tools will need to be installed before running `azd up` etc. 

Missing tools: 
* SWA CLI 
* JDK 

## todo-java-mongo

Error: todo-java-mongo

```
$ azd up 

ERROR: required external tools are missing:
 - need at least version 17.0.0 or later of Java JDK installed. Visit the website for your installed JDK to upgrade Java JDK version
```

**Comment by danieljurek** [comment]
Issues discovered from testing: 

* JDK version -- https://github.com/Azure/azure-dev/issues/1207
* Can't start docker service -- https://github.com/Azure/azure-dev/issues/1206
* Unable to test user interactive login -- https://github.com/Azure/azure-dev/issues/1029 -- this can be solved by supplying `--subscription <subscription>` to the `azd up` command

**Comment by savannahostrowski** [comment]
Ah I see. 

Okay, so I'd say re. JDK, we should try to see if the Cloudshell team can bump to 17. For the other issue, re. #1206, let me ping the Cosmos team and figure out what scenarios are most compelling to them.

**Comment by danieljurek** [comment]
Update. We tested a "workaround" for the JDK upgrade in a local CloudShell container image and the test succeeded.
