### ISSUE TITLE
[CI/CD Issues] Time out after 30 minutes trying to provision

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#487]
Test name:

Test_CLI_InfraCreateAndDeleteFuncApp

Logs:

Created Storage account: stw6aon7tnoby6c
2022/08/17 22:25:54 2022-08-17 22:25:42 - Created Storage account: stw6aon7tnoby6c
Creating Azure resources (1 of ~2 completed) |
2022/08/17 22:25:54 RunWithResult exec: 'az resource show --ids /subscriptions/***/resourceGroups/rg-azdtest-f4ecff5/providers/Microsoft.Web/sites/func-w6aon7tnoby6c --output json'
Created Function App: func-w6aon7tnoby6c
2022/08/17 22:25:56 2022-08-17 22:25:45 - Created Function App: func-w6aon7tnoby6c
Creating Azure resources (4 of ~4 completed) |
2022/08/17 22:26:06 RunWithResult exec: 'az deployment operation sub list --subscription *** --name azdtest-f4ecff5 --output json'
2022/08/17 22:26:08 RunWithResult exec: 'az deployment operation group list --subscription *** --resource-group rg-azdtest-f4ecff5 --name resources --output json'
Creating Azure resources (4 of ~4 completed) /
coverage: [no statements]
panic: test timed out after 30m0s

goroutine 521 [running]:
testing.(*M).startAlarm.func1()
	/Users/runner/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:2029 +0x8e
created by time.goFunc
	/Users/runner/hostedtoolcache/go/1.18.0/x64/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 3 minutes]:
testing.(*T).Run(0xc000240000, {0x151f435?, 0x4ebbf6cce7?}, 0x1559528)
	/Users/runner/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1487 +0x37a
testing.runTests.func1(0xc00019ebd0?)
	/Users/runner/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1839 +0x6e
testing.tRunner(0xc000240000, 0xc00021fca0)
	/Users/runner/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1439 +0x102
testing.runTests(0xc0001df860?, {0x1896460, 0x12, 0x12}, {0x1989a68?, 0x40?, 0x189d180?})
	/Users/runner/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1837 +0x457
testing.(*M).Run(0xc0001df860)
	/Users/runner/hostedtoolcache/go/1.18.0/x64/src/testing/testing.go:1719 +0x5d9
main.main()
	_testmain.go:123 +0x255

Link:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1788367&view=logs&jobId=3eb4d8a5-5d97-562b-c71d-6ac568d84486&j=3eb4d8a5-5d97-562b-c71d-6ac568d84486&t=02dec852-6265-5e32-1c63-ad2bb341bf1e

**Comment by weikanglim** [comment]
Closing this since we haven't seen similar failures recently after various fixes
