### ISSUE TITLE
An error occurred setting up the container in todo-python-mongo, todo-python-mongo-aca and todo-python-mongo-swa-func

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-dev#497]
**Describe the issue:**
These three templates could not be opened in container. We have tried to open them in container with three device, but all failed.

**Notes:** We can't open them under the main branch either.

**Repro Steps:**
1. Click **Reopen in container** with vscode.
![image](https://user-images.githubusercontent.com/81678720/185593277-80e3373c-032a-4e69-9ba1-95678148014f.png)

**Error Message:**
![image](https://user-images.githubusercontent.com/81678720/185591952-45fc716d-e7a8-444d-b583-afd41ed56c47.png)

**Environment:**
devcontainer

Templates: 
- https://github.com/azure-samples/todo-python-mongo 
- https://github.com/azure-samples/todo-python-mongo-aca  
- https://github.com/azure-samples/todo-python-mongo-swa-func 

Based on : https://github.com/Azure/azure-dev/pull/471

**Expected behavior:**
Open these templates in container with vscode can success.

@jongio , @savannahostrowski for notification.

**Comment by jongio** [comment]
I was able to confirm with @chuxel that this is due to a devcontainer/features issue.  He will report back with more info.

**Comment by Chuxel** [comment]
Root bug: https://github.com/devcontainers/cli/issues/131

**Comment by Chuxel** [comment]
This should be resolved in the Remote - Containers release that went out this morning.

**Comment by zedy-wj** [comment]
@jongio, @Chuxel - This issue has been solved, we also verified locally, and the result passed. We will close it, thanks! :)
