### ISSUE TITLE
[Issue] deployed service api link not working for `todo-csharp-cosmos-sql`

### ISSUE THREAD

**Issue by hemarina** [Azure/azure-dev#50]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `todo-csharp-cosmos-sql`**
Run `todo-csharp-cosmos-sql` and copy and paste the output here:
![image](https://user-images.githubusercontent.com/104857065/178346739-a6de2c64-82a7-42df-8d35-ad87ef45600f.png)

**Describe the bug**
deployed service api link (e.g https://app-api-4ncptg7bwnti2.azurewebsites.net/) is 404 (page not found).

**To Reproduce**
Run `azd up --template todo-csharp-cosmos-sql`

**Expected behavior**
Add a handler for the root path to the C# version of the API

**Environment**
Information on your environment:
Windows, AzCli 2.38.0

**Comment by ellismg** [comment]
I think we will want to use [Swashbuckle.AspNetCore.SwaggerUI](https://www.nuget.org/packages/Swashbuckle.AspNetCore.SwaggerUi/) in the C# application to serve the swagger UI from the root of the API endpoint, as we do for the other TODO applications.
