### ISSUE TITLE
Unable to deploy todo-csharp-cosmos-sql

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#503]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 0.1.0-beta.4 (commit fd96b3e9b283598bc4dc736e893f1b47080fbf7d)

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 
{
  "azure-cli": "2.39.0",
  "azure-cli-core": "2.39.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "containerapp": "0.1.0"
  }
}

**Describe the bug**
Not able to azd up azure-samples/todo-csharp-cosmos-sql

Error: deployment failed: failed deploying: failed running az deployment sub create:

[91mDeployment Error Details:[0m
[31mInvalidTemplateDeployment: The template deployment 'pcctodo' is not valid according to the validation procedure. The tracking id is '313bab1f-37ac-48ca-b47f-a5f7f0813994'. See inner errors for details.[0m

**To Reproduce**
1. azd up
2. select todo-csharp-cosmos-sql from list

**Expected behavior**
Successfully deploy and run todo-csharp-cosmos-sql

**Comment by rajeshkamal5050** [comment]
@puicchan just tried the same template. Did not see any issues though. Can you retry again?

azd version
`azd version 0.1.0-beta.4 (commit fd96b3e9b283598bc4dc736e893f1b47080fbf7d)`
azd up --template todo-csharp-cosmos-sql

**Comment by puicchan** [comment]
Closing as transient issue.
