### ISSUE TITLE
Document all of the env vars that azd creates/uses/modifies

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#507]
Let's document all of the env vars azd creates/uses/modifies and how a dev would take advantage of them.

**Comment by savannahostrowski** [comment]
@rajeshkamal5050  Do we have a list of these + info about their use anywhere? I believe CSS had this same feedback.

**Comment by rajeshkamal5050** [comment]
> @rajeshkamal5050 Do we have a list of these + info about their use anywhere? I believe CSS had this same feedback.

https://github.com/Azure/azure-dev/issues/1458 was something @weikanglim was consolidating. Can we use that and close this one?

**Comment by savannahostrowski** [comment]
Yep! Perfect.
