### ISSUE TITLE
[Issue] outputs from main.bicep added to .azure/.env occasionally include a casing error

### ISSUE THREAD

**Issue by greenie-msft** [Azure/azure-dev#512]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:
azd version 0.1.0-beta.4 (commit fd96b3e9b283598bc4dc736e893f1b47080fbf7d)

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 
azd version 0.1.0-beta.4 (commit fd96b3e9b283598bc4dc736e893f1b47080fbf7d)

**Describe the bug**
Description of issue you're seeing...
Occasionally (not always) outputs from main.bicep are exported to .env with casing errors:

output POSTGRES_USER string = binding.outputs.POSTGRES_USER

results in:  
pOSTGRES_USER=XXXXXXX

**To Reproduce**
Output variables from main.bicep 

**Expected behavior**
Environment variables should respect casing when added to .env file.

**Comment by jongio** [comment]
Related? https://github.com/Azure/azure-dev/issues/289

**Comment by ellismg** [comment]
This is somewhat surprising as we do explicit work to try to prevent this from happening.  ARM does not retain the case of output property names (this is a known issue) in the deployment object and so we use ARM Template to discover the canonical case of the outputs and then use that when updating the environment.

That logic lives here: https://github.com/Azure/azure-dev/blob/eff5410e6e0d1cac190823ee0ab5dfa06f43c1c4/cli/azd/pkg/iac/bicep/compile.go#L41-L59

It's possible that we aren't running it in some cases?

@greenie-msft You mentioned this is intermittent - I'm wondering what `azd` command you're running when you trigger this?  The intermittentness concerns me.

Also - when this happens is the original (correctly cased) `POSTGRESS_USER` removed from the environment or is it still around as well as the bad cased version?

**Comment by greenie-msft** [comment]
> 

@ellismg, I just reviewed my shell history and the command I used (every time) was : `azd env set POSTGRES_USER XXXX`

When behavior occurs, it does not remove the correct environment variable from previous attempts. I had the below in my .env file:

 POSTGRES_USER=XXXX
pOSTGRES_USER=XXXX

**Comment by weikanglim** [comment]
I'm pretty consistently running into this on a MacBook. Will investigate further, but at a glance:

- The casing in `.env` file is correct
- When running `bicep build` of the `.bicep` file, the outputs have correct casing
- But in the deployment, I can see the casing is messed up:
<img width="473" alt="image" src="https://user-images.githubusercontent.com/2322434/235014902-9d3fd43d-bcea-4bf2-8fbc-f21484716190.png">

Suspicious that ARM may be involved here.

**Comment by weikanglim** [comment]
This has been lingering for a while -- but the underlying issue was in the ARM deployment outputs. To handle this, azd normalizes all casing outputs -- please reopen if there are further issue around this.

**Comment by sin-rha** [comment]
@weikanglim 

I am seeing the same (or at least similar) issue when using the `az` command with the following run:

```yaml
      - name: Deploy Infrastructure
        id: deploy-infra
        run: |
          ENV_NAME="${{ github.event.inputs.environment || 'dev' }}"
          DEPLOYMENT_OUTPUT=$(az deployment group create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file PathToInfra/main.bicep \
            --parameters @PathToInfra/parameters/${ENV_NAME}.parameters.json \
            --query 'properties.outputs' \
            --output json)

          echo "Deployment output: ${DEPLOYMENT_OUTPUT}"
```

Can see in the action logs that the output has strange casing, seems like it lowercases all characters until the character before the first underscore:

Deployment output (removed the actual values): 
```json
{
  "azurE_CONTAINER_APP_ENVIRONMENT_ID": {
    "type": "String",
    "value": "***"
  },
  "azurE_CONTAINER_REGISTRY_LOGIN_SERVER": {
    "type": "String",
    "value": "***"
  },
  "azurE_CONTAINER_REGISTRY_NAME": {
    "type": "String",
    "value": "***"
  },
  "azurE_LOCATION": {
    "type": "String",
    "value": "***"
  },
  "azurE_RESOURCE_GROUP": {
    "type": "String",
    "value": "***"
  },
  "azurE_STORAGE_ACCOUNT_ID": {
    "type": "String",
    "value": "***"
  },
  "azurE_SUBSCRIPTION_ID": {
    "type": "String",
    "value": "***"
  },
  "azurE_TENANT_ID": {
    "type": "String",
    "value": "***"
  }
}
```

These are uppercased outputs in the bicep file and it is expected that the casing is honoured.

The Azure CLI Version:
```text
Run az --version
azure-cli                         2.81.0

core                              2.81.0
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.2

Dependencies:
msal                            1.34.0b1
azure-mgmt-resource               23.3.0

Python location '/opt/az/bin/python3'
Config directory '/home/runner/.azure'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.13.9 (main, Nov 26 2025, 00:44:06) [GCC 13.3.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
````
