### ISSUE TITLE
[Issue] dev-ify doc needs resourceGroup naming updates

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#519]
What
- https://docs.microsoft.com/en-us/azure/developer/azure-developer-cli/make-azd-compatible
- Make your project compatible with Azure Developer CLI (azd) Preview document requires update to resource group name references. Currently it has names with `-rg` suffix. It should be `rg-` prefix
- Seeing couple of occurrences under section `Add Bicep files`

Why
- Recently we made a change to consolidate names under one file and address naming issues with PR - https://github.com/Azure/azure-dev/pull/140

**Comment by puicchan** [comment]
Updated: https://docs.microsoft.com/en-us/azure/developer/azure-developer-cli/make-azd-compatible?pivots=azd-create
