### ISSUE TITLE
[Issue] Make default view for `azd monitor` the dashboard and not live metrics

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#522]
Right now, `azd monitor` opens Live Metrics. Let's change this to the Dashboard view instead (we have a known issue around Live Metrics and Python that we are working to resolve).

**Comment by savannahostrowski** [comment]
Note that in VSCode we already default to opening the dashboard view.

**Comment by savannahostrowski** [comment]
@rajeshkamal5050 Can we get this prioritized to go in before 9/29? Right now, the experience is broken from the standalone CLI.

**Comment by vhvb1989** [comment]
@savannahostrowski I can take a look
