### ISSUE TITLE
Repoman - ReWrite Rule and Path Normalization

### ISSUE THREAD

**Issue by hattan** [Azure/azure-dev#524]
- Repoman should have a ReWrite Rules section to allow for an explicit definition of path rewrite rules in repo.yaml instead of relying on asset rules mapping directly to source and target paths.
- Repoman path normalization should retain ./ in local relative paths. For some tooling, this is required to indicate a local path source.

**Comment by rajeshkamal5050** [comment]
@hattan I believe this is complete. Please reopen if need be.
