### ISSUE TITLE
[Issue] Being asked for AZURE_LOCATION after running AZD Down

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/azure-dev#528]
**Output from `azd version`**
`azd version 0.1.0-beta.5 (commit 7bd25dd6f1b1899abf63b5f6f36d268a465183e4)`

**Output from `az version`** 
```
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "containerapp": "0.3.5",
    "log-analytics": "0.2.2",
    "rdbms-connect": "1.0.2"
  }
}
```

**Describe the bug**
Being prompted to choose a location after running `azd down --purge --force --no-prompt` because the value is being removed from the `.env` file when the command is run.

**To Reproduce**
1. `azd init`
2. choose a template (i chose the first option `Azure-Samples/todo-python-mongo-aca`)
3. `azd provision`
4. `azd down --purge --force --no-prompt`
5. Now try another command `azd env get-values` and see the select location prompt 

**Expected behavior**
Did not expect the down command to modify my `.env`

**Environment**
Information on your environment:
    * Command line experience
    * Happens from PowerShell and Bash
    
**Additional context**
Noted that other `.env` values are not modified, but I'm prompted for location and subscription.

**Comment by rajeshkamal5050** [comment]
@danieljurek can you work with @ellismg on this.

**Comment by vhvb1989** [comment]
The original issue reported here is no longer happening (running `azd env get-values` for env with only the env-name in it does not ask for location)

I think the current behavior for `azd down` is per design. The values in .env should be no longer valid after `azd down`.  The environment comes back to its `initiated env`, where sub and location are yet to be selected.
