### ISSUE TITLE
Feature Request - Support for a post provision script. 

### ISSUE THREAD

**Issue by greenie-msft** [Azure/azure-dev#534]
It would be beneficial for azd to support a post provision script. 

For example - 

In my Bicep, I define a resource for an Azure Postgres DB and my application once deployed assumes that the table for that DB already exists. I cannot create the table in the Bicep due to the RP not supporting the capability.  So I need to run a custom command to create the script in between an azd provision and an azd deployment. 

It would be great if `azd up` could be aware of the post provision script as well so I can provision/deploy in a single command and everything is operational.

**Comment by jongio** [comment]
That is possible...but ...

ARM deployment scripts require

1. storage account
2. user defined managed identity

**Comment by karolz-ms** [comment]
Storage account is not required; the script can be provided inline in Bicep via `scriptContent` property

Some identity/credentials are required depending what resources the script is supposed to manipulate. For Azure resources, it can use a user-defined managed identity via `identity` property, but one can also pass credentials to the script and have it log in via Azure CLI. The latter may be handy if the deployment is already creating some identities for the application access.

That said, database initialization is a very common requirement, and the script can use whatever authN method the database supports; it does not have to be user-defined managed identity.

**Comment by rajeshkamal5050** [comment]
@greenie-msft as of February azd release, we have the hooks capability. Please try it and let us know for any feedback - https://devblogs.microsoft.com/azure-sdk/azure-developer-cli-azd-february-2023-release/#support-for-command-and-service-hooks

**Comment by savannahostrowski** [comment]
This exists now - closing
