### ISSUE TITLE
Update VS instructions to include preview install steps

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#541]
Let's add steps on how to get the right VS preview version installed
https://docs.microsoft.com/en-us/azure/developer/azure-developer-cli/debug?tabs=windows&pivots=ide-vs#enable-the-preview-feature

**Comment by rajeshkamal5050** [comment]
@jongio since it is a P2. Moving it to backlog. Please pull it in if you think otherwise.

**Comment by jongio** [comment]
I was thinking this would be @puicchan as she is doing doc updates.

**Comment by jongio** [comment]
Isn't it "install vs preview from here" https://visualstudio.microsoft.com/vs/preview/

**Comment by savannahostrowski** [comment]
Yep - @jongio is correct.

**Comment by gkulin** [comment]
pr to add the preview install step: https://github.com/MicrosoftDocs/azure-dev-docs/pull/1047
