### ISSUE TITLE
[CI/CD Issues] - Test_CLI_InfraCreateAndDelete

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#545]
Failed trying to find rg

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1814588&view=logs&j=dc5bf7c0-035c-5026-d13f-d96165097be5&t=d11c4f3e-0cc9-5499-b8f1-7a8b494955f4&l=71

    cli.go:67: [out] Provisioning Azure resources |
    cli.go:67: [out] Provisioning Azure resources (0 of ~1 completed)... /
    cli.go:67: [out] Provisioning Azure resources (0 of ~1 completed)... -
    cli.go:67: [out] Created Storage account: stxnn62ms4xvijw
    cli.go:67: [out] Provisioning Azure resources (1 of ~1 completed)... |
    cli.go:67: [out] Provisioning Azure resources (1 of ~1 completed)... /
    cli.go:67: [out] Provisioning Azure resources (1 of ~1 completed)... -
    cli.go:67: [out] Provisioning Azure resources (1 of ~1 completed)... \
    cli.go:67: [out] 
    cli.go:67: [out] Azure resource provisioning completed successfully
    cli.go:67: [out] 
2022/08/29 17:36:22 RunWithResult exec: 'az account get-access-token --output json'
2022/08/29 17:36:23 RunWithResult exec: 'az account get-access-token --output json'
    cli_test.go:283: 
        	Error Trace:	cli_test.go:283
        	Error:      	Received unexpected error:
        	            	resource not found: azure graph query returned 0 results for resource groups with azd-env-name with value: 'azdtest-lin-dc0'
        	Test:       	Test_CLI_InfraCreateAndDelete

DONE 252 tests, 1 failure in 488.428s

**Comment by jongio** [comment]
I likely related to #540

**Comment by weikanglim** [comment]
This is likely fixed. Will reopen if we see more occurrences.
