### ISSUE TITLE
Deployment is not valid according to the validation procedure in todo-nodejs-mongo-swa-func.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-dev#552]
**Describe the issue:**
Deploy failed when we try to run the file: "test-templates".

**Repro Steps:**

1. Click `Create codespace on main`.

2. After `az login --use-device-code`, run `bash ./test-templates.sh -t todo-csharp-cosmos-sql -c false`.

**Error Message:**
![image](https://user-images.githubusercontent.com/81678720/187405890-676fd494-368c-4adc-968c-e903484d8283.png)

**Environment:**
codespace
Template: https://github.com/azure-samples/todo-csharp-cosmos-sql

**Expected behavior:**
Create resource with the command: `bash ./test-templates.sh -t todo-csharp-cosmos-sql -c false` can success.

@jongio for notification.

**Comment by jongio** [comment]
This was fixed here: https://github.com/Azure/azure-dev/pull/521  which hasn't been merged to main yet.  Can you please retry using that pr?

**Comment by zedy-wj** [comment]
@jongio - Okay, we have tested it based on PR #521, there is no problem.
