### ISSUE TITLE
Implement UX improvements

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#557]
Spike to investigate on Austin's UX improvements proposal and prototype - [Investigate UX improvements to the azd up provisioning flow · Issue #255 · Azure/azure-dev (github.com)](https://github.com/Azure/azure-dev/issues/255)
- P0 - Currently it has mocks only for azd up i.e., azd init, provision, and deploy
- P1 - To follow the same layout and styling across all commands in Azd.

@savannahostrowski @Austinauth

**Comment by Austinauth** [comment]
@rajeshkamal5050 I will be investigating the remaining commands at the end of October / November (what you have captured under P1). This should not prevent us from delivering the initial mocks in P0 (up, init, provision, etc.).

Here is the issue: https://github.com/Azure/azure-dev/issues/663

**Comment by vhvb1989** [comment]
Ux changes:
- azd init: https://github.com/Azure/azure-dev/pull/965
- azd provision: https://github.com/Azure/azure-dev/pull/1133
- azd deploy: https://github.com/Azure/azure-dev/pull/1269

**Comment by rajeshkamal5050** [comment]
Pipeline config UX improvements are complete. Marking it as complete.
