### ISSUE TITLE
Make deployment discovery more robust

### ISSUE THREAD

**Issue by karolz-ms** [Azure/azure-dev#559]
We have logic in Bicep provider to re-try the deployment query: https://github.com/Azure/azure-dev/blob/main/cli/azd/pkg/infra/provisioning/bicep_provider.go#L559 This is because it happens that the deployment is not "visible" via the API even though the call to create it has succeeded shortly before.

This logic affects just one codebase though. We have seen cases (e.g. while running tests) where deployment created by one `azd` invocation is not visible to another `azd` invocation that comes shortly after. To increase `azd` robustness we should make the retry logic for deployment queries universal, that is, all invocations of `azcli.GetResourceGroupDeployment()` and `azcli.GetSubscriptionDeployment()` should use the same retry policy.

This is related to https://github.com/Azure/azure-dev/issues/540

**Comment by weikanglim** [comment]
There was built-in retry for discovering the deployment. However, I believe the error detection was broken: https://github.com/Azure/azure-dev/blob/c414fc573d4785e6f9d875e3529ceb5ad0a2f974/cli/azd/pkg/tools/azcli/azcli.go#L1038
