### ISSUE TITLE
VSCode correlation

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#600]
Currently, we do not have a reliable way to detect whether `azd` is invoked directly from Visual Studio or VSCode for telemetry purposes. This issue tracks the enabling of such a detection mechanism.

Likely, we'll need to add special flags to VSCode or Visual Studio invocation to add identification support.

**Comment by karolz-ms** [comment]
@weikanglim we do for VS Code, see https://github.com/Azure/azure-dev/blob/main/ext/vscode/src/utils/azureDevCli.ts#L66 and https://github.com/Azure/azure-dev/blob/9ecd9bcd9153ee02b64a5a400545a7fe1289a522/ext/vscode/src/extension.ts#L43 and https://github.com/Azure/azure-dev/blob/9ecd9bcd9153ee02b64a5a400545a7fe1289a522/ext/vscode/src/ext.ts#L11

**Comment by weikanglim** [comment]
Thanks for sharing that @karolz-ms. That is indeed a reliable way to detect whether we're invoked by VSCode. Do we think of the `AZURE_DEV_USER_AGENT` as a generic "user agent" variable that is not tied to HTTP? If so, then I agree with the mechanism.

Also, do we guarantee that we would override the environment variable even if one was set by the user, and set `AZURE_DEV_USER_AGENT` to exactly the contents outlined above? I believe so based on how the env var merging is done, but just want to confirm.

**Comment by karolz-ms** [comment]
@weikanglim correct, the `AZURE_DEV_USER_AGENT` is not tied to HTTP in any way, and it should override whatever is set in the ambient environment when VS Code invokes the AZD CLI (if it does not, it is a bug).
