### ISSUE TITLE
[Issue] Deployment of Function - Targeting Function App

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-dev#635]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 0.1.0-beta.5 (commit 7bd25dd6f1b1899abf63b5f6f36d268a465183e4)

**Output from `az version`** 
{
  "azure-cli": "2.39.0",
  "azure-cli-core": "2.39.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

**Describe the bug**
The scenario is a simple deployment of an Azure Function in a Functions App. The setup of the environment is structured in accordance with the ToDo templates i.e., the name of the Function App is defined by:

```bicep
resource functionApp 'Microsoft.Web/sites@2022-03-01' = {
  name: '${abbrs.webSitesFunctions}api-${resourceToken}'
```

Executing an `azd provision` this leads to a Function App name like "func-api-vwqrio2hyvrds".

The source of the Azure Function is located in a dedicated `src` directory. It contains the vanilla Azure Functions structure. 

The `azure.yaml` file has the following structure:

```yaml
name: azure-functions-blob
metadata:
  template: azure-functions-blob@0.0.1-beta
services:
  api:
    project: src
    language: ts
    host: function
```

The environment is defined as `test-app-migration`. Executing an `azd deploy` leads to the following error:

```shell
{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Web/sites/test-app-migrationapi' under resource group 'rg-test-app-migration' was not found. For more details, please go to https://aka.ms/ARMResourceNotFoundFix"}}
```
Taking a look into the yaml schema this error makes sense as it is stated here that the optional resource name if not specified "will be constructed from current environment name concatenated with service name (<environment-name><resource-name>, for example 'prodapi')." This causes the error. 

Putting the Function App name explicitly into the `azure.yaml` file as `resourceName` resolves the situation, but I do not think that is is a good approach.
The question for me is: Is there a best practise how to deal with that. Maybe a default way to reference the resource from the information available via the `.azure` directory? 

**To Reproduce**

- Clone the repo <https://github.com/lechnerc77/azd-compatibility-azure-function>
- Execute `azd init`
- Execute `azd provision`
- Execute `azd deploy --debug`

**Expected behavior**

Some way to dynamically influence the `resourceName` based on the environment information and a documentation of the best practises (maybe in the troubleshooting section of the documentation)

**Environment**
Information on your environment:
    * TypeScript; Node.js 16.16.0
    * Visual Studio Code 1.71.0

**Comment by ellismg** [comment]
Hi @lechnerc77,

Thanks for sharing the sample repository.

> Putting the Function App name explicitly into the azure.yaml file as resourceName resolves the situation, but I do not think that is is a good approach.

Your intuition is right here.  If `resourceName` is not set, `azd` will try to discover the correct resource to target. It does this by looking at all the resource groups for your application and then for a resource tagged with `azd-service-name` with a value that matches the key for the service in `azure.yaml` (in your sample app, this is `api`).

Looking at your sample repository, it looks like the the function app resource is instead tagged with `azd-function-name`, which `azd` doesn't consider.

I forked the sample repository (thanks a ton for providing it!) and made the following changes (one to change the tag name and then one to remove the explicit resource name from `azure.yaml`)

```diff
diff --git a/azure.yaml b/azure.yaml
index 6233732..9e9cb84 100644
--- a/azure.yaml
+++ b/azure.yaml
@@ -5,7 +5,6 @@ metadata:
   template: azure-functions-blob@0.0.1-beta
 services:
   api:
-    resourceName: func-api-vwqrio2hyvrds
     project: src
     language: ts
     host: function
diff --git a/infra/resources.bicep b/infra/resources.bicep
index d7e9d52..085f96f 100644
--- a/infra/resources.bicep
+++ b/infra/resources.bicep
@@ -71,7 +71,7 @@ resource appServicePlan 'Microsoft.Web/serverfarms@2022-03-01' = {
 resource functionApp 'Microsoft.Web/sites@2022-03-01' = {
   name: '${abbrs.webSitesFunctions}api-${resourceToken}'
   location: location
-  tags: union(tags, { 'azd-function-name': 'function 1' })
+  tags: union(tags, { 'azd-service-name': 'api' })
   kind: 'functionapp,linux'
   properties: {
     serverFarmId: appServicePlan.id
```

With these changes, I was able to deploy the application.

Using the tag here is the current recommended best practice.

**Comment by lechnerc77** [comment]
Hi @ellismg,

thanks a ton for the explanation. That clarifies the setup. 
Did I miss that logic to determine the target resource I the documentation. If not I think this would be a great addition to the FAQ area.

**Comment by ellismg** [comment]
> Did I miss that logic to determine the target resource I the documentation. If not I think this would be a great addition to the FAQ area.

We do have some documentation on "AZD"-ify'ing your application, which does point this out (but it is somewhat buried in the prose):

https://docs.microsoft.com/en-us/azure/developer/azure-developer-cli/make-azd-compatible

I'll try to get something added to the FAQ (https://docs.microsoft.com/en-us/azure/developer/azure-developer-cli/faq) as well.

Thanks again for the feedback and for playing around with AZD

**Comment by lechnerc77** [comment]
Thanks again and I will continue playing around 😃

**Comment by ellismg** [comment]
I opened a PR to our FAQ that will add the following questions and answer:

> How does deploy find the Azure resource to deploy my code to?
>
> During deploy, azd looks for a resource tagged with azd-service-name with a value that matches the name of your service from azure.yaml. It searches all resource groups tagged with azd-env-name with a value that matches your environment name.
> 
> While we recommend using tags on resources, you can also use the resourceName property in azure.yaml to provide an explicit resource name. In that case, the above logic is not run.
