### ISSUE TITLE
Graphics for azd storytelling + communications

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#639]
**Outcome:** strengthen azd brand, product positioning.
**Target audience:** LT, partners, open-source community

- [x] azd workflow 
- [ ] condensing developer questions to commands 
- [ ] @savannahostrowski's complex app -> azd simplicity ✨ narrative + deck
- [ ] deck template? (probably relevant for above)

**Comment by Austinauth** [comment]
**Update 09/22/2022**

Diagram for `azd` workflow completed

#### Light Mode
![Image](https://user-images.githubusercontent.com/6994218/191849786-2acb2f6f-dafd-46d8-b9e4-5fc14ec5a74b.png)

#### Dark Mode
![Image](https://user-images.githubusercontent.com/6994218/191849858-7f67c119-38ed-4633-8df9-3abddbbf07ef.png)

**Comment by savannahostrowski** [comment]
Closing for now.
