### ISSUE TITLE
todo-python-mongo-terraform: Cosmos DB is recreated each time.

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#645]
When provisioning the template with terraform, the cosmos DB is destroyed and re-created on each run.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/6540159/189753263-cc06bb6d-6658-44ec-bf12-4bb02c7e42f9.png">

**Comment by rajeshkamal5050** [comment]
Triage Update: @HadwaAbdelhalem to take look at update on the next steps.
