### ISSUE TITLE
deployment not found for azd monitor

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#652]
Used build from https://github.com/Azure/azure-dev/pull/650.

`azd init -t Azure-Samples/todo-python-mongo-terraform -b pr/650
`
>azd monitor
Error: discovering resource groups from deployment: fetching current deployment: deployment not found

**Comment by rajeshkamal5050** [comment]
@puicchan Does `azd monitor` work for Bicep templates?

**Comment by rajeshkamal5050** [comment]
Closing this one in favor of #657
