### ISSUE TITLE
The password does not meet policy requirements because it is not complex enouth.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-dev#655]
**Describe the issue:**
Failed to execute `azd pipeline config` command.

**Repro Steps:**
1. Run command: `azd pipeline config`.
2. Navigate to your new repo and click `Actions` module.

**Error Message:**
![image](https://user-images.githubusercontent.com/81678720/189909212-1da39d8d-d4fe-4ac5-ac60-40d5d9dfdb37.png)

For more details, click [here](https://github.com/zedy-wj/zedytest14-todo-csharp-sql-15875/actions/runs/3045093236/jobs/4906226161).

**Environment:**
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

Windows desktop | Linux desktop | MacOS desktop | WSL | DevContainer in VS Code | Codespaces
-- | -- | -- | -- | -- | --

</div>

</body>

</html>

Template: https://github.com/Azure-Samples/todo-csharp-sql
Branch: staging

**Expected behavior:**
Run the command: `azd pipeline config` can success.

@jongio for notification.

**Comment by karolz-ms** [comment]
The problems is the version of `azd` used by the pipeline is old, so the password generation for the SQL database did not happen. 

The azd image used by the pipeline needs to be updated to the 0.2 version of azd. Then the error should disappear.

**Comment by karolz-ms** [comment]
I am going to close this because there is nothing do do on our side. 

@zedy-wj would appreciate verifying that after changing to a recent `azd` image in pipeline definition e.g. `azdevcliextacr.azurecr.io/azure-dev:pr-660` the problem no longer repros. If it does, please re-open.
