### ISSUE TITLE
Categorize command-terminating errors in telemetry

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#681]
Currently, all errors when executing a command in `azd` is classified as an `UnknownError`. We should improve on this categorization to allow differentiating between types of errors.

We probably want to draw inspiration from HTTP error codes to create a hierarchical error type. The high-level error categorization should allow us to classify user vs. server errors.

**Comment by savannahostrowski** [comment]
@weikanglim Is this the same and/or related to https://github.com/Azure/azure-dev/issues/2101

**Comment by weikanglim** [comment]
Closing since #2101 is done
