### ISSUE TITLE
[Issue] `azd up` error on WSL - "Could not find a part of the path..."

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-dev#686]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
`azd version 0.2.0-beta.1 (commit 817a81ab44ac788ec2d3050e94ba0138c3a80ac3)`

**Output from `az version`** 
```
{
  "azure-cli": "2.40.0",
  "azure-cli-core": "2.40.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "azure-dev": "0.0.1b456",
    "connectedk8s": "1.3.3",
    "connectedmachine": "0.5.1",
    "containerapp": "0.3.11",
    "containerapp-compose": "0.2.2",
    "customlocation": "0.1.3",
    "k8s-extension": "1.3.3",
    "rdbms-connect": "1.0.3",
    "webapp": "0.4.0"
  }
}
```

**Describe the bug**
When running `azd up --template https://github.com/tonybaloney/django-on-azure` I get the following error:
```
Error: planning deployment: planning infrastructure provisioning: creating template: failed to compile bicep template: failed running az bicep build: exit code: 1, 
stdout: , 
stderr: ERROR: An error occurred reading file. Could not find a part of the path 'D:\mnt\d\git\WebApp_DB\azdev_2\infra\main.bicep'.
 (exit status 1)
```

The issue appears to be that azd is prepending "D:" in front of the path.

**To Reproduce**
1. Run `azd up --template https://github.com/tonybaloney/django-on-azure`
2. answer the prompts
3. see the error

**Expected behavior**
I expect `azd up` to create the resources and deploy the application under WSL like it does in a Windows PowerShell prompot

**Environment**
Information on your environment:
    * Windows 11 2022 H2 (occurred on previous version as well)
    * WSL 2
    * No IDE 

**Additional context**

**Comment by vhvb1989** [comment]
@charris-msft can you mention what version of WSL/distro are you using?  (is it Ubuntu-22.04 ??)

Also, what terminal are you using to connect to WSL?  (powershell / cmd / ? )

I'm having some trouble trying to replicate :),  so, hopefully it might be some specific-version that Iam missing

**Comment by charris-msft** [comment]
Hey @vhvb1989 - I'm using Ubuntu 20.04.4 LTS

**Comment by vhvb1989** [comment]
thank you @charris-msft 

Also, what terminal are you using to connect to WSL? (powershell / cmd / ? )

**Comment by charris-msft** [comment]
Windows Terminal > Ubuntu
and
PowerShell > wsl

**Comment by vhvb1989** [comment]
I was able to run `azd up` from Ubuntu 22.04:
deployed app:
https://app-hhpzayqgotauy.azurewebsites.net/


Trying on Ubuntu 20.04 next

**Comment by charris-msft** [comment]
one thing that I should perhaps mention is in Windows my source folder is a junction from d:\git to c:\git. However, under WSL it is located under /mnt/d/git/ as you would expect.

**Comment by vhvb1989** [comment]
thank you @charris-msft 

This might be a wsl issue resolving the paths.

Are you creating a sym-link from your c:\git to d:\git ??  

In order to have the same set up, please describe how you are setting up your folders.

Also, please note that when using `wsl`, it is recommended to use the folders/drive from wsl directly, instead of mounting folders from windows host. You would see a big performance increase.

VSCode, for example, would give you the next message when mounting local folders on wsl
![image](https://user-images.githubusercontent.com/24213737/191328726-284eaf41-d21e-4143-b246-1583b749bcd9.png)

See more: https://learn.microsoft.com/en-us/windows/wsl/setup/environment#file-storage

May I ask,,  is there a reason why you want to use the host folders for running `azd` from wsl?   (instead of, for example, running `azd` directly from Windows host?)

**Comment by charris-msft** [comment]
Here is the command I'm using to link from c:\git to d:\git (the goal is to have a c:\git folder, with the storage being on a separate physical disk)
`mklink /j c:\git d:\git`

This is a good question: "May I ask, is there a reason why you want to use the host folders for running azd from wsl?"

WSL is not my preferred way of working, but there is another issue regarding line endings when using `azd` from PowerShell:  #563. I was hoping to see if switching to wsl would be a reasonable workaround for that issue.

**Comment by vhvb1989** [comment]
I would totally recomend using `WSL`, but working directly from the `~/` directory (your home folder).
Using `/mnt` would give you a poor experience.

Everything should work fine for you if you run this (from WSL)
``` bash
# go to home folder
cd
# create some work folder and run azd from there
mkdir azdtest
cd azdtest
azd up --template https://github.com/tonybaloney/django-on-azure
```

**Comment by vhvb1989** [comment]
Also, have you considered mounting `d:` to `WSL` and directly using `d:\git` from wsl. Instead of using `c:` as router?

**Comment by rajeshkamal5050** [comment]
Hi @charris-msft any updates on the recommendation from @vhvb1989
