### ISSUE TITLE
Nightly Template Test Job failing for CSharp/SQL Templates due to KeyVault Issues

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#697]
Our nightly job which runs `test-templates.sh` is failing for the C# legs which use SQL:

Log: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1857691&view=logs&j=255759e9-95fd-5b22-cada-8803e798a082&t=e39b3856-d7f9-53f8-aecf-19f4626fff0c

The "test" part of the test actually passes (we correctly deployed the app and ran the playwrite tests against it) but we blow up when we try to deprovision:

From the error log:

```
  1 passed (26s)
Deprovisioning infrastructure for azd-template-test-todo-csharp-sql-1857691...
Planning infrastructure provisioning |
Generating Bicep parameters file... /
Error: planning destroy: planning infrastructure provisioning: creating parameters file: substituting command output inside parameter file: reading secret 'sqlAdminPassword' from vault 'keyvault': failed running az keyvault secret show: exit code: 1, stdout: , stderr: ERROR: The user, group or application 'appid=***;oid=***;iss=https://sts.windows.net/***/' does not have secrets get permission on key vault 'keyvault;location=EastUS'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287
: exit status 1
```

It's somewhat surprising that we hit this error during deprovision (I would not have expected us to have to generate a parameters file here, but it's possible this is a side effect of the common interface we have now with TF support), but from the error it seems like just running `azd provision` would have failed.

Karol did work when adding support for C# to read secrets from keyvault (and if they were not present, generate a secret value) and the secret should be added to KeyVault as part of the initial provision.  Seems like we are not ACLing this correctly or there are weird principal errors.

**Comment by weikanglim** [comment]
The issue has to do with the `AZURE_KEY_VAULT_NAME`. It seems to be set to `keyvault` -- which is probably not a keyvault we own (KeyVault names have to be globally unique)

In the error:

> Error: planning destroy: planning infrastructure provisioning: creating parameters file: substituting command output inside parameter file: reading secret 'sqlAdminPassword' from vault '**keyvault**'
