### ISSUE TITLE
Azdo Pipeline Provider - prompt user for PAT 

### ISSUE THREAD

**Issue by hattan** [Azure/azure-dev#699]
Prompt user for PAT if not found in the AZURE_DEVOPS_EXT_PAT environment variable. This is to improve the AzDo pipeline config experience by asking the user for a PAT and linking to documentation on how to create a PAT.

This should also provide instructions on how the user can set a PAT via environment variables so the user is not prompted repeatedly for a PAT.

**Comment by savannahostrowski** [comment]
I think that this was completed via #743
