### ISSUE TITLE
Deprecate AZ CLI usage within AZD

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#709]
The goal is to reduce upfront dependencies for new users of the `azd cli`.  The `az cli` has a large footprint and must be installed first today before `azd` can function

- #712
- #710
- #711
- #720 
- #721
- #854 **_(Note: implementation adjustments/refactoring. not a must-fix for us to deprecate Az CLI)_**
- #871
- #955
- #1023

**Comment by rajeshkamal5050** [comment]
Though we have a couple of items above. We can track those as individually. Marking this complete.
