### ISSUE TITLE
Integrate telemetry useragent tracing into golang modules

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#720]
Since we will be migrating from `az cli` commands to use golang SDK modules we need to ensure that the same level of telemetry data can be captured easily and consistently across `azd` modules.

**Comment by wbreza** [comment]
@weikanglim - we already include our user agent string in all calls through the Go SDK modules and MS graph.  Is there anything else that we need here?

**Comment by weikanglim** [comment]
@wbreza No, that should be all. Created #992 to investigate correlation IDs separately.
