### ISSUE TITLE
Update telemetry dashboards to pull data from any new telemetry stores

### ISSUE THREAD

**Issue by wbreza** [Azure/azure-dev#721]
Update internal telemetry dashboards to pull telemetry data from any new data stores based on changes to the azd module telemetry collection

**Comment by weikanglim** [comment]
@savannahostrowski Do we depend on `AzureCli` Kusto database? I searched for `AzureCli` references in our  "Azure Developer CLI" telemetry dashboard and did not find any

@wbreza Are there other dashboards than "Azure Developer CLI" that you were thinking of?

**Comment by savannahostrowski** [comment]
Nope - we shouldn't!
