### ISSUE TITLE
Pipeline Config - Switch default branch to main.

### ISSUE THREAD

**Issue by hattan** [Azure/azure-dev#725]
The azd pipeline config command currently configures the local repo with master a default branch if a git repository is not initialized. This behavior happens for both GitHub and the new Azure DevOps provider.

This should be changed to main as that is the new industry standard for git default branches.

**Comment by jongio** [comment]
It should use the default on the machine.  I don't think we specify it directly.

**Comment by vhvb1989** [comment]
> I don't think we specify it directly.

After cloning a template, there's not git-repo settings.  azd would ask customers if they want to init a git repo when running `azd pipeline config`

When saying yes, we can set the initial branch name to `main`.   (azd is currently just calling `git init`)
Depending on git version, we can either use the `--initial-branch` argument (from git >= 2.28) or call `git checkout origin` after calling init (for older git versions)

**Comment by jongio** [comment]
Okay, yeah, should default to main.
