### ISSUE TITLE
Architecture diagrams for Java support - App Service & ACA

### ISSUE THREAD

**Issue by rajeshkamal5050** [Azure/azure-dev#733]
For todo-java-mongo-aca & todo-java-mongo.

We need Java versions of the architecture diagram on:
1. https://github.com/azure-samples/todo-nodejs-mongo. 
2. https://github.com/azure-samples/todo-nodejs-mongo-aca 

Replace nodejs with the Java Duke icon https://developer.microsoft.com/en-us/Java.

**Comment by Austinauth** [comment]
### Java Mongo
![image](https://user-images.githubusercontent.com/6994218/191853739-52d07641-d6e6-49d2-9491-e7c4921325c7.png)

### Java Mongo ACA
![image](https://user-images.githubusercontent.com/6994218/191854051-5a2e28b1-5961-4d8b-82a8-a29939fe9f04.png)

I think these should be good, but @rajeshkamal5050 @puicchan take a moment to make sure they're okay next chance you get.
