### ISSUE TITLE
Consider stripping symbols from release bits

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-dev#739]
We should investigate building the bits we ship with `-ldflags '-s -w'` or something similar to remove debug symbols.  We should see how much worse this makes the `panic()` experience as well as the output when running with `--debug`, but it could be a good size win for us.

Possible that we could end up in a place where we have released bits which are stripped and then unstripped versions which we also put on our HTTP service (and perhaps could be installed with a special flag to the install scripts?) for folks that are running into crashes and want the debug versions.

**Comment by weikanglim** [comment]
This has been added a few months back in [ci-build.ps1](https://github.com/Azure/azure-dev/blob/d07ef0c756317ae0d429183b599c6f76668d62be/cli/azd/ci-build.ps1#L74)
