### ISSUE TITLE
Chocolatey package support

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#744]
### Discussed in https://github.com/Azure/azure-dev/discussions/682

<div type='discussions-op-text'>

<sup>Originally posted by **flcdrg** September 14, 2022</sup>
I've created a Chocolatey package to facilitate installing/upgrading the Azure Developer CLI

https://community.chocolatey.org/packages/azure-developer-cli</div>

**Comment by jongio** [comment]
@flcdrg and @danieljurek - Can you investigate what it would take to integrate the publishing to choco from azure/azure-dev repo?

**Comment by flcdrg** [comment]
The source files for the current package are in https://github.com/flcdrg/au-packages/tree/master/azure-developer-cli

You'll need to create a Chocolatey account. Let me know what the account name is and I can add you as a co-maintainer on Chocolatey.org.

You'll need to obtain your API key (similar to nuget.org) and store that somewhere (eg. GH Actions secret). You pass that through to the Chocolatey CLI when pushing a new version `choco push package.nupkg --apikey YOURAPIKEY`

The current Chocolatey package downloads the exe. The other option would be to bundle the exe inside the package (this would require a few other changes to the install script and adding some other license and doc files, but is generally a nicer end-user experience).

Once you folks have this hooked into your CI/CD workflow then I'll hand it all over to you and stop publishing updated from my repo.

**Comment by danieljurek** [comment]
I've done a little reading on the docs. Here's what I see... 

## Installer logic

### Script (using tools we have today)

@flcdrg would there be any major drawbacks to wrapping our existing install script? 

I recommend we use `install-azd.ps1` and set options like `-Version`, `-InstallFolder`, and `-NoPath` to install to the configured locations in https://github.com/flcdrg/au-packages/blob/master/azure-developer-cli/tools/chocolateyinstall.ps1. This will reduce the number of things we have to update if the installer's internal logic changes in the future. 

Also, we've noticed at least one drawback with downloading assets from GitHub releases: in CI scenarios where agents have a shared pool of IP addresses (Azure DevOps hosted agents, GitHub hosted runners), we see 429 responses on occasion. To that end, downloading the releases from a CDN has so far not resulted in those types of failures. This is less likely to be a problem in desktop scenarios compared to CI scenarios. 

From my reading of choco docs, it looks like the main use case for running choco is to run as admin (if memory serves, I have also done it this way in the past)... in which case I think installing to the tools directory is reasonable and requires fewer changes to the system (i.e. no updating `PATH`) 

### Bundling 

Is the main advantage of this approach that we reduce the number of network round trips required to install the package?

We might have to do some duplication of the installer logic which could result in editing installation logic in two places if the installation logic changes in the future. 

## Engineering System (i.e. release automation) 
 
Add jobs to: 
  * Build and validate package install
  * Push updated assets to choco on release

## TODO

* Set up choco account for pushing updates to `azure-developer-cli` 
* Determine best way to go forward

**Comment by flcdrg** [comment]
The potential problem with using the install script is that Chocolatey has restrictions on how files can be downloaded - they must use one of the [Chocolatey functions](https://docs.chocolatey.org/en-us/create/functions/). You also need to ensure that the checksums included in chocolateyInstall.ps1 are correct for each version.

If you know the CDN URLs then those would be preferable to use as download URLs.

Yes, bundling removes the download step.

**Comment by danieljurek** [comment]
Thanks @flcdrg, that clarifies. I'll need to do some prototyping on my side to learn more about the capabilities here.

**Comment by savannahostrowski** [comment]
Done! cc: @danieljurek 🎉
