### ISSUE TITLE
[Issue] Remove node install as a prereq from our docs?

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#753]
I'm not clear on why we need users to install node/npm to use the CLI - 
https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/get-started?tabs=bare-metal%2Cwindows&pivots=programming-language-nodejs#prerequisites

![image](https://user-images.githubusercontent.com/8949415/192600462-5a84bc62-1174-45e0-80dc-1c81297e8370.png)

It makes sense if you are using a JS template but do we need this for the core CLI to run? If not, let's remove this from the docs.

**Comment by puicchan** [comment]
You don't need node. Pls refer to new staged link for the new install page. Content will be live tomorrow.

**Comment by rajeshkamal5050** [comment]
<img width="524" alt="Azd-Prerequisites" src="https://user-images.githubusercontent.com/11532743/193748644-7c76968a-d9be-4835-a79b-bf9b433c67f3.png">

Not seeing node as a pre-requisite.
