### ISSUE TITLE
azdo - "Argument args.Project can not be nil or empty" error if I run azd pipeline config in a new environment

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#759]
PR 743 build -
azd version 0.2.0-beta.3-pr.1877365 (commit https://github.com/Azure/azure-dev/commit/33710f9beab18fc32168ae2e02768f2697bdc164)

Argument args.Project can not be nil or empty
azd init -t Azure-Samples/todo-nodejs-mongo -b pr/743
azd pipeline config --provider azdo
azd env new
azd pipeline config --provider azdo

**Scopes of PAT**
Agent Pools (read, manage)
Build (read and execute)
Code (full)
Project and team (read, write and manage)
Release (read, write, execute and manage)
Service Endpoints (read, query and manage)

-----------------

D:\codes\test\node927>azd pipeline config --provider azdo
Using pipeline provider: Azure DevOps
You need an Azure DevOps Personal Access Token (PAT). Please create a PAT by following the instructions here https://aka.ms/azure-dev/azdo-pat
? Personal Access Token (PAT):  xxx

? Personal Access Token (PAT): xxx
? Save the PAT to the node927b environment file (.env)? Yes
? Please enter an Azure DevOps Organization Name: puichan0401

? Please enter an Azure DevOps Organization Name: puichan0401
Creating or updating service principal az-dev-09-27-2022-22-33-11.

Error: creating service connection: looking for existing connection: Argument args.Project can not be nil or empty

**Comment by vhvb1989** [comment]
When a new environment is created, the persisted configuration about the azdo repo is lost and it is expected to be present in the environment.

I created a PR to restore the settings by parsing the remote url and then querying azdo for the ids
