### ISSUE TITLE
Device is required to be managed to access this resource

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-dev#768]
**Describe the issue:**
Failed when we try to run the command `bash ./test-templates.sh -c false -t todo-python-mongo-terraform -b pr/743`

**Repro Steps:**

1. Run `azd login`
2. Run `bash ./test-templates.sh -c false -t todo-python-mongo-terraform -b pr/743`

**Error Message:**

![image](https://user-images.githubusercontent.com/80307197/192753627-77307978-68dd-4c76-8f2b-6ce06d5270e3.png)

**Environment:**
OS: Linux desktop , WSL
Template: https://github.com/Azure-Samples/todo-python-mongo-terraform

**Expected behavior:**
Run command: `bash ./test-templates.sh -c false -t todo-python-mongo-terraform -b pr/743` can success

@rajeshkamal5050  for notification.

**Comment by HadwaAbdelhalem** [comment]
@AFengKK the failure is regarding the az login with --device code on wsl , details https://github.com/Azure/azure-cli/issues/17273 . Can you please run az login using a service principal or user and rerun the commands.

**Comment by rajeshkamal5050** [comment]
@AFengKK is this similar to the other todo-python-mongo-terraform issue #767?

**Comment by AFengKK** [comment]
@rajeshkamal5050 It may be similar to the https://github.com/Azure/azure-dev/issues/767 issue. We followed what you said in issue https://github.com/Azure/azure-dev/issues/767#issuecomment-1263790268 and configured the ARM variables to deploy resources. This issue is not reproduced, but it had a new issue of failed to install provider. Any ideas?

**Error Message:**

![image](https://user-images.githubusercontent.com/80307197/194808661-aa1c7b79-afaa-4ee9-94eb-ba095f65885a.png)
