### ISSUE TITLE
[Issue] Console output duplicated if wrapped

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#79]
Command output that wraps is duplicated 

Zoom in so the font is larger, or resize your console to cause the text to wrap and you'll see something like this after running `azd restore`

![image](https://user-images.githubusercontent.com/2163001/178545017-82231884-d290-4b75-8687-3ee933aaf344.png)

**Comment by savannahostrowski** [comment]
@vhvb1989 I think that this will be resolved with the PR that resolved #1784, right?

Seems like the UX before the released tomorrow looks like now:
![image](https://github.com/Azure/azure-dev/assets/8949415/9e38a6b7-98df-418c-a4af-51e2ea5ee069)

**Comment by vhvb1989** [comment]
> I think that this will be resolved with the PR that resolved https://github.com/Azure/azure-dev/issues/1784, right?

Yes
