### ISSUE TITLE
Allow infra files location override

### ISSUE THREAD

**Issue by jongio** [Azure/azure-dev#8]
Right now we default to infra files being located in the /infra folder.  Let's allow developers to override that location.

Potential places to allow override.
1. In azure.yaml
2. In root .env
3. In env .env

**Comment by rajeshkamal5050** [comment]
@jongio @ellismg 

Is this a must-fix for the upcoming milestone (Release 0.2 - Sep 7)? 
- If yes, please add it to Aug iteration.
- If not, please move it to On Deck (has to be addressed post Release 0.2) or Backlog.

**Comment by wbreza** [comment]
This was completed during the provider implementation #227
