### ISSUE TITLE
New architecture diagram for C# Azure SQL Functions template

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#800]
Related to PR #551 
We need the architecture diagram edited for the new csharp Azure sql functions template.

**Comment by Austinauth** [comment]
@puicchan Will try to have this done for you by end-of-week or sooner. Can you please provide more specifics on the request in this issue?

**Comment by Austinauth** [comment]
### Updated Diagram

![Image](https://user-images.githubusercontent.com/6994218/195178654-d045f184-640e-4f80-b02c-fbfd429f0093.png)


### Sharepoint Link to Img File
https://microsoft.sharepoint.com/:i:/t/AzureDeveloperExperience-AzureAcceleratorsTeamInternal/EYDI14KlMPVOk-GzWDWr1p4BpFGGw_0MRAayB1j1s1AvbQ?e=BzPmfF


@puicchan feel free to close this issue if thats all you need!

**Comment by madebygps** [comment]
Thank you! I've added it to my template readme.
