### ISSUE TITLE
[Issue] .bicep file for Storage Accounts

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-dev#809]
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azure-dev-cli_0.3.0-beta.1

**Output from `az version`** 
n.a.

**Describe the bug**

This is less a bug than a feature request. With the new setup of infrastructure files in release 0.2.0-beta2 there are several pre-defined `.bicep` files in the `core` folder. Most of them have a useful parameterization. However when it comes to the storage account (`storage-account.bicep`) this is more or less hard coded:

```bicep
var resourceToken = toLower(uniqueString(subscription().id, environmentName, location))

resource storage 'Microsoft.Storage/storageAccounts@2021-09-01' = {
  name: '${abbrs.storageStorageAccounts}${resourceToken}'
```

Of course one could create an own template, but I think this enhancement should be part of the `core`

**To Reproduce**
Try to create an azd compatible project with two storage accounts where you want to influence the names of the storage account using the template from the `core` folder

**Expected behavior**
The naming of the Azure Storage account resource should be possible using the template form the `core` folder

**Environment**
Information on your environment:
    * Node.js 16
    * Visual Studio Code 1.71.2

**Additional context**
You can take a look at my sample project where I created a `.bicep` file for storage which is copy&paste of the core file and allowing a bit more flexibility when it comes to the name: <https://github.com/lechnerc77/azd-compatibility-azure-function/blob/main/infra/corelocal/storage/enhanced-storage-account.bicep>

**Comment by jongio** [comment]
Resolved with #996
