### ISSUE TITLE
[Issue] azd up should create a new directory for better dx

### ISSUE THREAD

**Issue by piizei** [Azure/azure-dev#811]
**Describe the bug**

Like every other common developer cli-tool (like git), azd should create the directory when azd up is ran.

**Expected behavior**

Create a directory with the name of the template

**Environment**
Information on your environment:
azd version 0.3.0-beta.1

**Comment by jongio** [comment]
We'll want to consider side effects of doing this, like `azd up` runs multiple commands assuming current directory, if azd init puts in a subfolder, then we'll need to execute sub commands in the context of that new subfolder.

This should be achievable now that we have --cwd option.

**Comment by rajeshkamal5050** [comment]
Needs investigation and discussion on what other CLI's/tools do.

**Comment by savannahostrowski** [comment]
Closing in favour of https://github.com/Azure/azure-dev/issues/181
