### ISSUE TITLE
`azd help` improvements

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#822]
![image](https://user-images.githubusercontent.com/8949415/194172371-8ecac848-8aa2-42a4-a62d-4f99458242ba.png)

Should we group the commands by task?

**Comment by jongio** [comment]
Yes!

**Comment by Austinauth** [comment]
@savannahostrowski As we discussed earlier, let's make the #663 issue an Epic and this issue a task within the epic (I'm not sure how to do that myself).

**Comment by savannahostrowski** [comment]
Moving this to November (later half of the month)

**Comment by Austinauth** [comment]
**Update 10/25/2022**
- Begin work on this week of 11/14

**Comment by puicchan** [comment]
New command `azd config` is available since release azure-dev-cli_0.4.0-beta.1. Please make sure you include `azd config` in your exploration. 

![Image](https://user-images.githubusercontent.com/8701892/199055265-f12b566d-653f-4bfd-8af5-d48ff05249e4.png)

**Comment by Austinauth** [comment]
Proposed `--help` templates I shared today on the demo.

### General Help (azd --help)

![image](https://user-images.githubusercontent.com/6994218/211672561-d4b0ecc8-b310-4a23-82cc-641890e274cf.png)

### Command Help (azd [command] --help)

![image](https://user-images.githubusercontent.com/6994218/211672593-0f5a0329-d268-4c09-bea0-5976a50a3a7c.png)

**Comment by Austinauth** [comment]
## Update 01/16/2022

- Finalized designs for 12 different azd help experiences
- Presented to team on azd Demo playback
- Detailed feedback provided by @savannahostrowski, @gkulin, @ellismg and Crystal Barragan
- Ready for implementation discussions (cc: @rajeshkamal5050 , @savannahostrowski)

### Overview of new designs

Prototype featuring the proposed `azd help` and `azd <command> --help` designs can be [found here](https://www.figma.com/proto/iIRRiGPuKIfaSFfMJXcYle/azd-resource-provisioning?page-id=1257%3A148505&node-id=1301%3A142321&viewport=773%2C-475%2C0.25&scaling=min-zoom&starting-point-node-id=1301%3A142321). Use `<` and `>` arrows to toggle through pages. 

#### Summary of changes and features
- Overhauled the layout, hierarchy and visual design of both general and command specific help to be more scannable, and to align with the design language we are establishing for the rest of the CLI (consistency).
- Commands regrouped to more accurately reflect the jobs a user can complete using the CLI.
- Reworked individual descriptions for commands, flags and global flags to be more clear.
- Reworked intro descriptions to be more succinct (introduced bullet point format).
- Introduced an examples section for most commands to aid in understanding.
- Introduced new convenience commands/flags: `docs`, `--docs`, `upgrade`. **Needs team approval.**

#### Links to individual help experiences:
- [azd help](https://www.figma.com/proto/iIRRiGPuKIfaSFfMJXcYle/azd-resource-provisioning?page-id=1257%3A148505&node-id=1301%3A142321&viewport=433%2C-1438%2C0.5&scaling=min-zoom&starting-point-node-id=1301%3A142321)
- [azd up --help](https://www.figma.com/proto/iIRRiGPuKIfaSFfMJXcYle/azd-resource-provisioning?page-id=1257%3A148505&node-id=1301%3A142935&viewport=433%2C-1438%2C0.5&scaling=min-zoom&starting-point-node-id=1301%3A142321)
- [azd down --help](https://www.figma.com/proto/iIRRiGPuKIfaSFfMJXcYle/azd-resource-provisioning?page-id=1257%3A148505&node-id=1301%3A143543&viewport=433%2C-1438%2C0.5&scaling=min-zoom&starting-point-node-id=1301%3A142321)
- [azd init --help](https://www.figma.com/proto/iIRRiGPuKIfaSFfMJXcYle/azd-resource-provisioning?page-id=1257%3A148505&node-id=1301%3A143847&viewport=433%2C-1438%2C0.5&scaling=min-zoom&starting-point-node-id=1301%3A142321)
- [azd provision --help](https://www.figma.com/proto/iIRRiGPuKIfaSFfMJXcYle/azd-resource-provisioning?page-id=1257%3A148505&node-id=1301%3A144151&viewport=433%2C-1438%2C0.5&scaling=min-zoom&starting-point-node-id=1301%3A142321)
- [azd deploy --help](https://www.figma.com/proto/iIRRiGPuKIfaSFfMJXcYle/azd-resource-provisioning?page-id=1257%3A148505&node-id=1301%3A144455&viewport=433%2C-1438%2C0.5&scaling=min-zoom&starting-point-node-id=1301%3A142321)
- [azd env --help](https://www.figma.com/proto/iIRRiGPuKIfaSFfMJXcYle/azd-resource-provisioning?page-id=1257%3A148505&node-id=1301%3A144759&viewport=433%2C-1438%2C0.5&scaling=min-zoom&starting-point-node-id=1301%3A142321)
- [azd config --help](https://www.figma.com/proto/iIRRiGPuKIfaSFfMJXcYle/azd-resource-provisioning?page-id=1257%3A148505&node-id=1301%3A145366&viewport=433%2C-1438%2C0.5&scaling=min-zoom&starting-point-node-id=1301%3A142321)
- [azd restore --help](https://www.figma.com/proto/iIRRiGPuKIfaSFfMJXcYle/azd-resource-provisioning?page-id=1257%3A148505&node-id=1301%3A145670&viewport=433%2C-1438%2C0.5&scaling=min-zoom&starting-point-node-id=1301%3A142321)
- [azd pipeline --help](https://www.figma.com/proto/iIRRiGPuKIfaSFfMJXcYle/azd-resource-provisioning?page-id=1257%3A148505&node-id=1301%3A145974&viewport=433%2C-1438%2C0.5&scaling=min-zoom&starting-point-node-id=1301%3A142321)
- [azd monitor --help](https://www.figma.com/proto/iIRRiGPuKIfaSFfMJXcYle/azd-resource-provisioning?page-id=1257%3A148505&node-id=1301%3A146278&viewport=433%2C-1438%2C0.5&scaling=min-zoom&starting-point-node-id=1301%3A142321)
- [azd template --help](https://www.figma.com/proto/iIRRiGPuKIfaSFfMJXcYle/azd-resource-provisioning?page-id=1257%3A148505&node-id=1368%3A149213&viewport=433%2C-1438%2C0.5&scaling=min-zoom&starting-point-node-id=1301%3A142321)

<hr>

Any feedback on the design is still gladly accepted!

**Comment by savannahostrowski** [comment]
@rajeshkamal5050 This is ready for implementation in 0.7. Please let @Austinauth Austin know if anything else is needed!

**Comment by rajeshkamal5050** [comment]
@savannahostrowski @Austinauth 
 
Some comments
	•	Grouping description changes
	•	Moved deploy into the 2nd bucket
	•	Put monitor, test and release together
	•	Moved login/logout onto the first bucket. For downloading/initializing and developing apps localy. We need authentication.

- Setup, configure and develop your app
-- config
-- init
-- restore
-- template
-- login
-- logout
 
- Manage azure resources and app deployments
-- deploy
-- down
-- env
-- infra
-- up
 
- Monitor, test and release your app
-- monitor
-- pipeline
 
- About, help and upgrade
-- docs
-- help
-- upgrade
-- version

**Comment by Austinauth** [comment]
@savannahostrowski are you good with Rajesh proposed tweaks? I don't have any issues.

**Comment by Austinauth** [comment]
@rajeshkamal5050 I spoke with @savannahostrowski regarding the suggested changes. 

We're mostly good on them except:

> Setup, configure and develop your app
Setup and configure are a little redundant, will just use configure for now if that's okay?

I should have the prototype updated by the time you read this message.

**Comment by rajeshkamal5050** [comment]
@Austinauth sounds good.
