### ISSUE TITLE
[azdev-ify] Module discovery and usage for /core

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#831]
It's not easy to figure out what are the modules I should be using - especially for hosts.

e.g., In /host
- we have 11 biceps for appservice
- 4 for ACA (container-app.bicep vs. container-apps.bicep - what's the diff?) 
- 3 for functions - more straightforward - a base and 2 lang-specific.
- 1 for staticwebapp

Consider:
**Scenario 1 - I just want to use what's in /core**
All I need is to know is what parameters to pass to the modules, I may not need to know what's in the modules but I need to know what each module is for and what is the contract.

**Scenario 2 - I want to modify what's in /core and create my own private collection**
For this scenario, developers do need to understand what's in the modules figure out how to customize/add own logics/conventions.

**Comment by jongio** [comment]
We could have files in root of /host be ones we intend people to use directly - but it gets iffy b/c they could use them directly in certain situations.
