### ISSUE TITLE
[Issue] Managed SWA APIs are not deployed to SWA 

### ISSUE THREAD

**Issue by manekinekko** [Azure/azure-dev#837]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here: 

`azd version 0.0.0-dev.0 (commit 0000000000000000000000000000000000000000)` (commit 9f61f14ea0023852b2ca16b690c9fa67f01aedf7)

Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 

`azure-cli": "2.40.0"`

**Describe the bug**
APIs part of SWA (managed API) are not being deployed by azd.

The reason is that the SWA CLI flags [that are being used to deploy an SWA app are missing the --api-location](https://github.com/Azure/azure-dev/blob/main/cli/azd/pkg/tools/swa/swa.go#L49-L59) which allows deploying the built-in API.

**To Reproduce**

- Create any SWA application with an API (see [examples](https://github.com/MicrosoftDocs/mslearn-staticwebapp-api))
- Write Bicep infra for SWA and setup azd (following the official docs)
- run `azd init`
- run `azd deploy`
- Notice the API is not deployed. Only the static site is deployed.

**Expected behavior**

`azd deploy` should deploy the built-in API to SWA (not a standalone App Service instance).

**Additional context**

To fix this: 
- azd needs to either pass in the `--api-location` to SWA CLI (if the ./api/ folder is present)
- Or, the user needs to create a [`swa-cli.config.json`](https://azure.github.io/static-web-apps-cli/docs/use/deploy#55-deploy-using-the-swa-cliconfigjson) providing `apiLocation` (if they are using a built-in API)
- Users could also use the SWA CLI and run `swa init` (the CLI will scan their project, auto-detect their configuration and generate the config file)

Also, optionally, users can provide the location of the API in `azure.yml`:

```yaml
services:
  swa:
    project: ./src/web
    api: src/api
    dist: build
    language: js
    host: staticwebapp
```

**Comment by rajeshkamal5050** [comment]
@wbreza can you take a quick look on the recommended option above?

**Comment by rajeshkamal5050** [comment]
@vhvb1989 with the https://github.com/Azure/azure-dev/pull/3553 support. The above issue should be fixed?

**Comment by vhvb1989** [comment]
yes, let's close this by answering with the option:

- the user needs to create a [swa-cli.config.json](https://azure.github.io/static-web-apps-cli/docs/use/deploy#55-deploy-using-the-swa-cliconfigjson) providing apiLocation

That's the expected story how azd supports managed APIs for SWA
