### ISSUE TITLE
Failed to debug api test for todo-csharp-sql-swa-func in windows

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-dev#845]
**Describe the issue:**
Debug failed when we start the “Debug API” task.

**Repro Steps:**
1. Start the API and Web using VS Code tasks 
2. Set a breakpoint in the API.
3. Open debug panel, and start the “Debug API” task.

**Error Message:**
![屏幕截图 2022-10-08 160055](https://user-images.githubusercontent.com/20970631/194831282-b2e1a41e-d51f-48ef-8482-486482acf5a5.jpg)

**Environment:**
OS: Windows desktop
Template: https://github.com/Azure-Samples/todo-csharp-sql-swa-func
Branch: pr/551

**Expected behavior:**
Debug api test for todo-csharp-sql-swa-func in windows successfully.

@jongio for notification.

**Comment by madebygps** [comment]
@zzhxiaofeng can you try latest commit? For now, you'll have to manually start the Start API task, and then run the Debug API task (you'll be asked to pick from a list of running .NET processes, search for the name of your app and select it.) Issues have been filed to hopefully get this working as it does in other templates.

**Comment by zzhxiaofeng** [comment]
@madebygps I have debugged api test as you said step by step and return an error as following, please have a look when you are free.
![image](https://user-images.githubusercontent.com/20970631/194991071-36b7ace7-ac0a-4ac4-a66b-444396b827c4.png)

**Comment by madebygps** [comment]
Awesome, thanks for the update.
