### ISSUE TITLE
Add Command Completion to azd

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#846]
I was pinged about this from another user on Twitter this weekend. Converting to an issue so that folks can upvote!

### Discussed in https://github.com/Azure/azure-dev/discussions/125

<div type='discussions-op-text'>

<sup>Originally posted by **xaviermignot** July 17, 2022</sup>
Pretty much what title says, is there any plan to have command completion in terminal ?
Just like what we have with Azure CLI, autocompletion works great in my zsh shell 🤓 

Many thanks in advance 🙏</div>

**Comment by alexandair** [comment]
This will enable us to get tab completion for `azd` commands in PowerShell shell. Brilliant!
