### ISSUE TITLE
Support for package managers/installers

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#847]
I wanted to open an issue to track the request to add package manager support for installation. This will make updating much easier as well.

this was also [raised to me on Twitter this weekend](https://twitter.com/MCKLMT/status/1579038973384863746)

Common package managers/installers:
- Brew (on MacOS)
- apt (Ubuntu/Debian)
- winget
- chocolatey

**Comment by MCKLMT** [comment]
I think this feature is a must have for all command line tools. Azure CLI, Bicep,... all tools can be install with brew on macOS.
I upvote for this! 😀

**Comment by savannahostrowski** [comment]
@danieljurek @rajeshkamal5050 Are winget/chocolatey likely to land in January?

Let's make sure that we start on brew/apt next.

**Comment by danieljurek** [comment]
I think we can land winget and Choco in January after a release which includes the MSI.

**Comment by flcdrg** [comment]
Linking Chocolatey issue #744

**Comment by danieljurek** [comment]
Current status: 

| Channel | Manual Release | Automated Release | 
| ------- | -------------- | ----------------- | 
| brew    | Done           | Done              |
| WinGet  | Done           | [Pending](https://github.com/Azure/azure-dev/pull/1500/files) | 
| Choco   | Pending package release approval from Choco | [Waiting for merge](https://github.com/Azure/azure-dev/pull/1538) |
| apt/yum | In Progress    | In progress       |

**Comment by savannahostrowski** [comment]
@danieljurek I believe `choco` is also done now 😎

**Comment by bitcrazed** [comment]
Exciting new packages landing in WinGet make @denelon very happy :)

**Comment by denelon** [comment]
[PowerToys](https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml), and [Oh My Posh](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/.github/workflows/winget.yml) use [wingetcreate](https://github.com/microsoft/wingetcreate) as a CI/CD tool. It was built for automation.

**Comment by danieljurek** [comment]
> [PowerToys](https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml), and [Oh My Posh](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/.github/workflows/winget.yml) use [wingetcreate](https://github.com/microsoft/wingetcreate) as a CI/CD tool. It was built for automation.

We use it, too @denelon :) https://github.com/Azure/azure-dev/pull/1500/files#diff-e94801cff6da36d3b13f1370783b0355bc7f75d5436ff195b0d56c7e3ffbeb6aR17

**Comment by danieljurek** [comment]
Instructions for pmc onboarding: https://github.com/Azure/azure-dev-pr/issues/1506

**Comment by rajeshkamal5050** [comment]
@danieljurek can you share any internal docs information for @savannahostrowski and doc writer to consume the deb and rpm bits we have today.

@danieljurek anything else needs to be done for making the dep and rpm packages public?

**Comment by rajeshkamal5050** [comment]
Marking this as blocker for 0.8 April 5th release to publish deb and rpm bits/docs. If not needed, please clarify and remove blocker.

@savannahostrowski @ellismg

**Comment by rajeshkamal5050** [comment]
Removing blocker. Since the above PR's are merged for instructions on downloading and installing deb/rpm packages directly.

Moving to Gallium. For yum/apt publishing and automation changes.

**Comment by savannahostrowski** [comment]
@danieljurek This is completed now, right? apt/yum install instructions are in the docs now. Anything remaining?

**Comment by danieljurek** [comment]
Automation that publishes to packages.microsoft.com and documenting how to onboard your Linux distro to get apt/yum working are the final pieces here.

**Comment by rajeshkamal5050** [comment]
Currently this is the experience and is documented.
```
curl -fSL https://github.com/Azure/azure-dev/releases/download/azure-dev-cli_<version>/azd_<version>_amd64.deb -o azd_<version>_amd64.deb
apt update 
apt install ./azd_<version>_amd64.deb -y
```
```
curl -fSL https://github.com/Azure/azure-dev/releases/download/azure-dev-cli_<version>/azd-<version>-1.x86_64.rpm -o azd-<version>-1.x86_64.rpm
yum install -y azd-<version>-1.x86_64.rpm
```
@savannahostrowski moving this to Backlog since the remaining item is to get the bits published and onboarded to packages.microsoft.com

**Comment by danieljurek** [comment]
This is done for the most popular channels. Closing.
