### ISSUE TITLE
[Dev Hub] Update to run and debug tutorial

### ISSUE THREAD

**Issue by puicchan** [Azure/azure-dev#855]
https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/debug?pivots=ide-vs-code

For C# swa-func MS SQL template - add: 
"You'll have to manually start the Start API task, and then Debug API (F5). You'll be asked to pick from a list of running .NET processes, search for the name of your app and select it."

**Comment by hhunter-ms** [comment]
@puicchan is this note just for the VS Code instructions, or for both VS Code and Visual Studio?

**Comment by puicchan** [comment]
Just VS Code.

**Comment by puicchan** [comment]
Updated
