### ISSUE TITLE
[azd down] argument `--force` is not working when there are key vaults

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-dev#87]
running `azd --force` should not ask for any confirmation, however, it is asking to confirm if there is a key vault.

![image](https://user-images.githubusercontent.com/24213737/178613082-6b3d8e58-9276-4ed1-83c4-fb27aef647ed.png)

**Comment by JohnCarmichael3000** [comment]
Yes, should not ask anything. Related thought: Could be related to KV soft delete being enabled in created items which causes more prompts.
