### ISSUE TITLE
Audit devcontainer.json per template

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#88]
There are likely a couple ways that we can improve our devcontainer.json.

One example is that right now, we don't have key language extensions (e.g. `ms-python.python`) included in the devcontainer.json for Python templates but we do have `ms-dotnettools.csharp` and `ms-dotnettools.vscode-dotnet-runtime` which are unnecessary . Ideally, we should tailor the devcontainer.json so that the extensions support/complement the template language/technologies.

**Comment by jongio** [comment]
Devcontainer definitions are here:
https://github.com/Azure/azure-dev/tree/main/templates/common/.devcontainer

And are currently shared amongst all templates.

To customize for each template you'll need to:

1. Create a .devcontainer folder under the /templates/todo/projects/{name} folder
2. Copy the files from https://github.com/Azure/azure-dev/tree/main/templates/common/.devcontainer to that folder
3. Modify them to suit the needs of the template.
4. Update repo.yaml to remove the part that copies from common/.devcontainer
