### ISSUE TITLE
Leverage new VS Code localization API

### ISSUE THREAD

**Issue by karolz-ms** [Azure/azure-dev#904]
VS Code is introducing a new API for localization: https://code.visualstudio.com/updates/v1_72#_localization-as-part-of-the-api

We should:
- review the localizable strings that we have in `package.nls.json`, leaving only those that are referenced by `package.json` (and thus cannot leverage the new API)
- convert all the only-used-from-code strings to use the new API

**Comment by tonybaloney** [comment]
The API isn't totally formalized, so there is a likelihood of it changing in the next release (causing backward incompatibility issues).

**Comment by karolz-ms** [comment]
@tonybaloney roger. That is why this issue is in "Backlog" milestone.
