### ISSUE TITLE
[codespaces] Web app does not follow redirects from "private" port

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#914]
When hosting an API and Web app in codespaces the API URL must be made "Public" ... This is (partially) because the react app does not follow redirects when running in the client's browser. 

Repro steps: 
1. Create codespaces instance against a sample repo ([example](https://github.com/Azure-Samples/todo-csharp-sql)) 
2. Provision resources
3. Launch debug for the API 
4. Manually mark the port as "Private" (warning the "Ports" page may not reflect the accurate state of the port, use `gh codespace ports -c $CODESPACE_NAME` instead) using the `gh codespace ports visibility 3100:private -c $CODESPACE_NAME ` 
5. Start the web app (debug not required) 
6. Launch the debug app 

Expected: Page content loads properly 
Actual: Page content does not load 

The request to get lists is redirected to an authentication experience: 

![image](https://user-images.githubusercontent.com/2158838/196720113-484ff6db-62c9-4c93-850b-59707732f2f3.png)

Setting the port to `public` instead of private alleviates the problem. 

In its current state, using codespaces with public ports is not significantly different from deploying the application itself using `azd deploy`. That is, deploying the application exposes swagger and API endpoints publicly, which is similar to using codespaces with a public API endpoint enabled.

**Comment by weikanglim** [comment]
Even if we followed the redirect -- we would hit by the `nginx` proxy that Codespaces uses to route the traffic to the `Codespace` instance, so it will still not fix the requirement that the backend app needs to be `public`.

**Comment by rajeshkamal5050** [comment]
@danieljurek @weikanglim is this still applicable? Since it talks about debugging and Codespaces doesn't support?

cc @savannahostrowski

**Comment by danieljurek** [comment]
Web development works best on vscode desktop.
