### ISSUE TITLE
[vscode] Support Codespaces web launch without debugger experience

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#918]
From discussions in https://github.com/Azure/azure-dev/issues/370 

Web debug should work by clicking "play" 
* Insert a hosted `url` value in `launch.json` (in codespaces) or `localhost:3000` 

* Implement a task which can run commands like the Web npm start task, but with a dotenv file (location dynamically determined). This task would need to use matchers so that it could pass control back to the task system.
  * Values in the environment should accommodate debugging a local API or a deployed API... possibly updating based on what's currently being debugged.

* Implement a teardown task which ends tasks associated with a debug run. After debugging ends the task would end associated tasks that initiated the run.

**Comment by rajeshkamal5050** [comment]
@danieljurek @weikanglim is this relevant still? given that we identified Codespaces doesn't support or promote debugging? and we may not want to add customization on azd/extension side to make it work?

cc @savannahostrowski

**Comment by danieljurek** [comment]
This is in alignment with existing vscode debugging experiences.
