### ISSUE TITLE
[Issue] Prompted to run az login as part of azd up (failed running `az account get-access-token`)

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#919]
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 

**Describe the bug**
![image](https://user-images.githubusercontent.com/8949415/196747044-f6d00132-0334-44f2-85ec-7a5ec16fbe25.png)

**Expected behavior**
I should see a prompt to run `azd login`.

**Comment by rajeshkamal5050** [comment]
@ellismg with the move to `azd login` is the above still valid? do we need to handle this anymore?

**Comment by rajeshkamal5050** [comment]
Given that we have moved using native authn with `azd login`. Closing it as fixed.
