### ISSUE TITLE
[Issue] Hitting failed deploy due to `az` cli version upgrade prompt again

### ISSUE THREAD

**Issue by timheuer** [Azure/azure-dev#920]
I was running `azd up` and it failed on deploy.  When I re-ran `azd deploy` I saw a familiar message and realized I'm hitting the issue again where the underlying `az` cli was outdated and there was an interactive prompt waiting for input that caused the command to fail.

![image](https://user-images.githubusercontent.com/4821/196748772-3607c681-0458-4617-8f0f-02f43726b1a6.png)

**Comment by rajeshkamal5050** [comment]
We have almost removed Az CLI dependency. This should eventually go away once we release it in the upcoming release in Jan.

**Comment by rajeshkamal5050** [comment]
With the latest 0.5.0-beta.X release. Azd does not have Az CLI dependency. Closing it as fixed.
