### ISSUE TITLE
[Issue] Add with "Create with the Azure Developer CLI" to the resource creation options

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#924]
With the Azure Tools extension pack installed, a developer can create a new resource by clicking on the + in the resources pane. Once they click the button, they are provided with options (see below).

![image](https://user-images.githubusercontent.com/8949415/196810829-f30b6101-a78d-4f59-b769-53651833e663.png)

We should add an option to that says (I'm open to suggestions on the wording):
> Create with the Azure Developer CLI (azd)...
Use the Azure Developer CLI to set up all application resources

Upon clicking this, we trigger `azd provision` to create all the resources for the user based on their IaC assets in their project's infra/.

**Comment by savannahostrowski** [comment]
@philliphoff When are these bits being released? Before 11/2?

**Comment by philliphoff** [comment]
@savannahostrowski Good question; I didn't have any specific next release date in mind.  The biggest limiting factor for releases is the time required to reasonably test the fixes/changes.  Is there something on 11/2?

**Comment by savannahostrowski** [comment]
It's our last monthly release blog post of the year so I was wondering if I could mention it in there. If it's not feasible to get all the testing done in the next week, no worries. We can hold off until the new year and announce this enhancement + the tree view in one go. Might be a more exciting post anyway!
