### ISSUE TITLE
[codespaces] azd command does not launch new URLs

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-dev#928]
Repro steps: 

1. Create codespace from template repo ([example repo](https://github.com/Azure-Samples/todo-nodejs-mongo/))
2. Run `azd up`, follow auth procedure, wait for deployment
3. Run `azd monitor --live` 

Expected: metrics tab launches in browser
Actual: Error in console like

```
Opening https://app.azure.com/72f988bf-86f1-41af-91ab-2d7cd011db47/subscriptions/faa080af-c1d8-40ad-9cce-e1a450ca5b57/resourceGroups/rg-djurekcs27/providers/Microsoft.Insights/components/appi-fxwxyzi2vujba/quickPulse in the default browser...
warning: failed to open default browser: could not open resource: exec: "xdg-open": executable file not found in $PATH
```

**Comment by savannahostrowski** [comment]
I can't actually reproduce this. 

I tried running `azd monitor` via azure.yaml and also by typing `azd monitor --live` into the embedded terminal and both correctly prompted me to consent to opening the page. This worked as expected in my Codespace!

**Comment by danieljurek** [comment]
Fixed in https://github.com/Azure/azure-dev/pull/934
