### ISSUE TITLE
`daily` container images don't show up in `mcr.microsoft.com`

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#936]
`mcr.microsoft.com/azure-dev-cli-apps:daily` is currently an old build. Our daily `main` builds are not publishing this tag correctly.

**Comment by danieljurek** [comment]
We should either: 

* Update it with normal daily builds 
* Remove the `daily` tag as it is very old and misleading

**Comment by danieljurek** [comment]
This version is removed. Closing.
