### ISSUE TITLE
Should `azd init` also create a git repository?

### ISSUE THREAD

**Issue by weikanglim** [Azure/azure-dev#938]
This solves the problem of templates not able to preserve Linux filesystem `exec` bit permissions when `azd init` is ran on Windows.
See #893 for an example.

This also potentially helps with the extra step of creating a git repository.

## Proposed change

1. When `azd init` is ran on a non-git-initialized directory, a git repository is created with the default branch `main`. All files are staged in the git repository but not committed.
1. When `azd init` is on a git-initialized directory (with potentially existing files), `exec` bit permissions are set based on the template repository's git attributes.

## Pros

- Same experience as `Use this template` on GitHub
- Executable bit permissions are preserved on Windows
- Removes step for user needing to run `git init` 
- Encourages the novice developer to use `git`

## Cons

- A user might want to make additional changes to the template before making a commit for his application repository. This would require squashing history via rebase.
- A user might not want a git repository. And would have remove `.git` to get back to just a directory.
- If we diverge from using git repository for templates, we'll need to introduce exec bit permissions storage to support the same requirement.

## Implementation

1. After performing `git clone` to a temp directory, `azd` will use `git ls-files -s` to get all files with their `exec` bit permissions. We record all files that have `100755` defined in-memory.
2. Perform the copy to the new/existing directory. Wait for the user to accept the overwrite prompt if it's existing.
3. After copying the files, for each file that was recorded as `100755` in step 1, perform `git update-index --chmod=+x <file>`. No fs-related permission errors would be encountered since this only updates the git working index.

Strictly speaking, it isn't required to probe using `git ls-files -s` or `git update-index --chmod=+x <file>` on filesytems that support exec bit, however given that probing itself whether the FS supports it is less than non-trivial, it is easier to just always perform the operations.

**Comment by jongio** [comment]
Unless we have data that says we need to support devs using something other than git, then I'm okay saying that git is a requirement for azd.

**Comment by ellismg** [comment]
> When azd init is ran on a non-git-initialized directory, a git repository is created with the default branch main. All files are added to the git repository and committed with the commit message: "Initial commit"*.
A UX task to show "Initializing git repository" or "Initialized git repository"

Could we get away with doing the `git init` but not actually doing the commit or do we have to do the commit in order for the "update index" behavior to "persist" in some way on windows?  (I could imagine that the exec bit could get unset accidently on windows, perhaps if some additional changes were made and then `git add` was run?)

I think running `git init` itself is reasonable, I just worry a bit about how it feels to have a commit authored on my behalf.

**Comment by jongio** [comment]
How about we run the git-index update command without the commit?

**Comment by weikanglim** [comment]
We can run `git update-index` which stages the change but doesn't require the commit, so it is a doable alternative. The user experience is perhaps a little jarring though -- you see 100+ files all staged but uncommitted when you run `git status`.

> I think running git init itself is reasonable, I just worry a bit about how it feels to have a commit authored on my behalf.
> The user may very well need to configure a local name/email/signature prior to that first commit; the global settings may not be appropriate for that new repo and their organization may have rules/conventions regarding proper commit messages.

I think these are good points. I had overlooked what that would look like, mostly taking that was granted, as we already commit a message on-behalf of the user in `azd pipeline config` to trigger the pipeline run, and perhaps we shouldn't there either -- there's a different way we can trigger a CI pipeline via Rest APIs

The main perspective I was coming from is that I wanted parity between the experience of "Use this template" on GitHub and `azd init <template>`. It feels like we want to support both as equivalent paths. However, we don't have the user context in the template download, so forcing one seems incorrect.

**Comment by jongio** [comment]
I think the diff between 'use template' and azd is that azd would be local in terminal and probably noticable, whereas 'use template' is almost fully hidden from the user that it has happened.  Is that correct?

**Comment by weikanglim** [comment]
@jongio Just to make sure we're on the same page, this is the GitHub 'use template' experience that I'm referring to:


![Image](https://user-images.githubusercontent.com/2322434/202028734-ea590b88-0ba8-4177-a53f-6bccea7fce17.png)


Clicking on 'Use this templates' brings you to options for setting up the new repository:


![Image](https://user-images.githubusercontent.com/2322434/202028943-fa545c64-617f-47b2-8f0c-c1d477b0ef81.png)

And when it's done you can see the repository is initialized successfully with an initial commit:


![Image](https://user-images.githubusercontent.com/2322434/202261269-a209566c-2baf-4f23-8e3d-68a481bf8cef.png)

**Comment by weikanglim** [comment]
@savannahostrowski @puicchan Any concerns if we implemented the proposed changes so that `azd init` will create the local git repository and stage the files, but leave them uncommitted?

**Comment by savannahostrowski** [comment]
No - I personally think that this is an improvement!

**Comment by puicchan** [comment]
I can't think of why you should not. Do make sure you consider `azd init` when used to azdev-ify a project.

**Comment by savannahostrowski** [comment]
Is this completed now? If not, what remains?
