### ISSUE TITLE
[Issue] `azd pipeline config` cannot set AZURE_CREDENTIALS from Codespaces

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#948]
Feel free to close if we are tracking this elsewhere. This is the output I get in Codespaces when I run `pipeline config`. 

Note that I forked the template and then opened the Codespace.

```
Using pipeline provider: GitHub
Creating or updating service principal az-dev-10-21-2022-15-48-46.

Configuring repository savannahostrowski/codespaces-test.

Setting AZURE_CREDENTIALS GitHub repo secret.

Error: failed setting AZURE_CREDENTIALS secret: failed running gh secret set exit code: 1, stdout: , stderr: failed to fetch public key: HTTP 403: Resource not accessible by integration (https://api.github.com/repos/savannahostrowski/codespaces-test/actions/secrets/public-key)
: exit status 1

 *  The terminal process "/bin/bash '-c', 'azd pipeline config'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by danieljurek** [comment]
Possible solution:

Inside azd when running gh/git commands: 

1. unset GITHUB_TOKEN (i.e. call `gh secret ...` with no GITHUB_TOKEN environment variable)
2. Run `gh auth login` (the user needs to not use gh auth to do git operations... this will need more exploration) 
3. Run all `gh secret set` operations 
4. Ask user if they want to start a workflow
5. Start workflow using `workflow_dispatch` ... do NOT use an empty commit
6. Open workflow in the browser

**Comment by danieljurek** [comment]
Another solution: 

Use OIDC to auth with GitHub. Hardcode these values (somehow populate them from a template/file) 

```yaml
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
``` 

These values aren't technically secrets and should probably be viewable (gh action secrets are not viewable). 

This would prevent us from having to set secrets (in codespaces or anywhere) and we could use the default set of permissions granted to codespaces.

**Comment by vhvb1989** [comment]
There is a fundamental situation here.
`azd pipeline cofig` is meant to set up a repository (either create a new one or chose one) on GitHub or Azdo.

When running `codespaces`, IIRC, we need to start from a GitHub repository. 
The source from the repo is mounted to a container and then there's some sort of VSCode-online that is connected to the container.

So, when running `azd pipeline config` from codespaces:
- Do we want to create a new repo? `azd` will notice that it is running from a folder that contains a .git project and with at least one `remote` (most likely `origin`) set.  This means that the remote name needs to be set manually (using `--remote-name`) in case the `origin` (default) is already taken by the current git project.
- Do we want to use the existing repo (GitHub) and add a pipeline to it?  This would be a completely new feature for `azd pipeline config`

IMHO, codespaces is something where the notion of `azd pipeline config` should no longer apply...  Here's why:
As a developer without a local dev-environment, if I am using `GitHub Codespaces` in the browser, my starting point can't be `azd init`, as first I need to create a repository.  Most likely, I would go to Azure-Samples and click `use template` from one of the `todo` samples.  Or I would probably click `fork` from some template that I want to use.  Or at the very least, I would create an empty repository and set up `codespaces for it` (only in this case, `azd init` might be applicable).

I am planning on updating `azd` to return an error if `azd pipeline config` is run from codespaces, mentioning that it is not supported. Unless until we define what do we want to happen on that scenario.

@jongio what's your thoughts on this?

**Comment by weikanglim** [comment]
@vhvb1989 The error here has nothing to do with git repository though. It is simply a result of the codespaces GitHub token doesn't have authorization to set secrets, and there's also problems with overriding that token inside codespaces. @jongio has ran into this before and blogged about it. The scenario here is that the user is using `azd pipeline config` to bootstrap the remaining parts of setting up the pipeline access + environment variables for the environment.

> azd pipeline cofig is meant to set up a repository (either create a new one or chose one) on GitHub or Azdo.

This is an interesting notion. I think it's worth discussing what `azd pipeline config` is meant to accomplish, because I've seen multiple, different definitions of `azd pipeline config` up to this point: from bootstrapping pipeline secrets / environment variables, generating a usable pipeline from template, to setting up azure credentials.

**Comment by savannahostrowski** [comment]
A couple things:

1. What is the purpose of `azd pipeline config`?

I think that it's important to think about `azd pipeline config` holistically. In other words, what would a developer using azd be trying to accomplish by running `azd pipeline config`?

**The goal here is to be able to scaffold a CI/CD pipeline that tests my code against real Azure resources.**

The pieces where `pipeline config` set up secrets/env variables, sets up a new repository etc. are really a means to an end here and not the primary JTBD (otherwise, maybe we would have named the command something different). My expectation is that if I were to fork a template, open it in Codespaces and run `azd pipeline config`, that azd would help me set up a CI/CD pipeline (which includes setting secrets, allowing me to choose a CI/CD provider and set up a new repo, if necessary; note that these are subtasks on the way to the end goal!)

2. What should the experience be in Codespaces?

Codespaces is just VS Code in a VM, it's another editing experience. To make the UX intuitive, we should strive to have the same azd support in each client. Commands should behave in the same way and we should have the same commands available to the user. Otherwise, it gets very difficult to reason about from the consuming developer perspective (especially if you don't have deep expertise in how Azure etc. works).

Today, we support a very similar flow locally (in VSCode or in your terminal of choice). You can fork a template on GitHub, clone the fork, run `azd up`, and run `azd pipeline config`...and everything works (azd uses that existing repo and does not prompt the user to choose to create a new repo etc). We should strive to have that same flow work in Codespaces. However, if there are technical limitations here then we should be tracking them in our repo and following up with the appropriate team (if needed) to figure out how we might be able to light up this experience.

**Comment by jongio** [comment]
We have `pipeline config` to configure GH or AzDO so an existing pipeline can run successfully.

Templates ship with a placeholder pipeline definition.

At some point we thought we'd want to have something like `pipeline create` to create a new one.

**Comment by savannahostrowski** [comment]
I think a plausible scenario is that someone uses the template as a starting point and modifies the pipeline definition we've included to make it work for their use case. I'm not confident that the scenarios (modify vs. create) are actually as disjoint as you outline today.

**Comment by weikanglim** [comment]
We might be running off-topic here, I think we can gather more thoughts in our meeting today here and create an issue for tracking `azd pipeline config` improvements.

In the meantime, I've played around with codespaces and `azd pipeline config` more. Summarizing it all:

# Problem

In codespaces, GitHub sets a sticky environment variable `GITHUB_TOKEN`. Once this is set, `gh` CLI will now use `GITHUB_TOKEN` for all operations. The default `GITHUB_TOKEN` permissions are too permissive and doesn't include `repo` scope, which consequently prevents repo secrets modification that is required as part of `azd pipeline config`.

# Goal

Given the problem above, what we want is the ability to temporarily elevate user permissions to allow secret modifications. This would be done usually by requesting a new token with extra permissions, making the REST calls with the token, and discarding it when we're done. However, `gh` CLI's auth model is designed to be stateful around the storage of access tokens, and thus this API doesn't exist. There are hacks we can do to get around this, but I would advise against it.

# Workaround

Here's what the user needs to do when they hit `Resource not accessible by integration` errors in `azd pipeline config` inside Codespaces:
1. Verify that `gh auth status` contains "GITHUB_TOKEN"
2. Unset GITHUB_TOKEN: `export GITHUB_TOKEN=`
3. Log in with a user oauth token (by default `repo` scope is included): `gh auth login`
4. Run `gh auth setup-git` to restore Git credentials. `gh login` with user oauth token breaks the git credential setup in codespaces (See https://github.com/cli/cli/issues/3799)
6. Rerun `azd pipeline config`
