### ISSUE TITLE
[Issue] Codespaces reports issue with dotenv task on first build

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#949]
**Describe the bug**

When I open the https://github.com/Azure-Samples/todo-python-mongo sample in Codespaces (in the browser), I see these errors about the "dotenv" task type:

<img width="492" alt="Screen Shot 2022-10-21 at 9 14 20 AM" src="https://user-images.githubusercontent.com/297042/197242104-bbbeb3b9-a5bc-4dd2-80f4-88c7932ef414.png">

<img width="1013" alt="Screen Shot 2022-10-21 at 9 14 24 AM" src="https://user-images.githubusercontent.com/297042/197242070-6ecd0b4e-5ed7-4d59-b596-bc97cd3ee234.png">

I assume that's related to the final task in https://github.com/Azure-Samples/todo-python-mongo/blob/main/.vscode/tasks.json but am not dotenv-savvy.

**To Reproduce**

Open https://github.com/Azure-Samples/todo-python-mongo in Codespaces in the browser.

**Expected behavior**

I expect no errors.

**Environment**

Microsoft Edge, latest Codespaces

**Comment by rajeshkamal5050** [comment]
@pamelafox do you see these issues from local VS Code?

**Comment by weikanglim** [comment]
Could reproduce this, but only when the container is built the first time in codespaces in both browser and desktop. 

Based on the error, I suspect what's happening from a high-level:

1. Our extension provides the task definition of [dotenv](https://github.com/Azure/azure-dev/blob/main/ext/vscode/package.json#L177).
2. VSCode is loading and parsing `task.json` while the extensions are being installed. If `task.json` is loaded while our extension isn't yet installed, we get the error output as described.

In essence, there's a race condition between `task.json` and the extension loading.

@philliphoff Do you have a best guess of where this issue should go? It's unclear if it's the GitHub codespaces extension or VSCode Server is at fault here. I did not reproduce this issue in DevContainers, and it seemed from the output log that VSCode was not fully loaded until the extensions were all installed (in contrast to Codespaces).

**Comment by philliphoff** [comment]
It definately feels like a VS Code issue (rather than an issue, say with the AZD extension itself), though I'm not sure whether it'd be Codespaces or VS Code Server issue.  I'd try Codespaces and let them (suggeset to) move it elsewhere.

VS Code should statically know that AZD extension declared the `dotenv` task type (via its `package.json`), so it should halt any use of that task type until the extension has been activated (so it can register the task type).

**Comment by weikanglim** [comment]
Logged the issue for VSCode. Closing this out as a result.
