### ISSUE TITLE
[Issue] "Debug web" throws errors in Codespaces

### ISSUE THREAD

**Issue by savannahostrowski** [Azure/azure-dev#950]
> I am using the instructions outlined in https://github.com/Azure/azure-dev/pull/934#issuecomment-1285686284

I'm using the todo-nodejs-mongo-swa-func template in Codespaces and on clicking "Debug web" I see these errors and am unable to see the application if I click to navigate to port 3100 from the ports window (it infinitely loads).

![image](https://user-images.githubusercontent.com/8949415/197241416-8de44c6e-8a7d-4ccd-b297-f3bfdc8cb82a.png)
![image](https://user-images.githubusercontent.com/8949415/197241436-e5e6b3e1-eb30-4f71-9512-0eb83ce1624e.png)

I'm also using Chrome, FWIW.

**Comment by weikanglim** [comment]
Created https://github.com/microsoft/vscode-js-debug/issues/1440
