### ISSUE TITLE
[Issue] Codespaces suggests Azure-Dev extension even though it's installed

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#951]
**Describe the bug**

When I open https://github.com/Azure-Samples/todo-python-mongo in Codespaces (in the browser), I see a suggestion pop up at the start about installing the Azure Dev extension:

<img width="483" alt="Screen Shot 2022-10-21 at 9 14 28 AM" src="https://user-images.githubusercontent.com/297042/197242642-d7374c4c-8ee2-4445-b6a7-0cdf5c37f0df.png">

That's very peculiar, since the Azure Dev extension (with the same identifier) is already installed:
<img width="1068" alt="Screen Shot 2022-10-21 at 9 19 57 AM" src="https://user-images.githubusercontent.com/297042/197242736-dd06df8e-688c-4491-ac37-d9bc0679d5c9.png">

It's specified like this in devcontainer.json:
"ms-azuretools.azure-dev",

**To Reproduce**

Open https://github.com/Azure-Samples/todo-python-mongo in Codespaces in the browser, wait for it to load.

**Expected behavior**

I don't expect the suggestion, since it's already installed.

**Environment**

Microsoft Edge, Codespaces

**Comment by rajeshkamal5050** [comment]
@philliphoff do we see this extension issue on VSCode?

@pamelafox  does this go away once you reload/restart in codespaces?

**Comment by danieljurek** [comment]
Related to https://github.com/Azure/azure-dev/issues/949

Thanks for filing @pamelafox! The behavior you're describing matches behavior seen in https://github.com/Azure/azure-dev/issues/916 ... 

I can also reproduce the behavior in todo-python-mongo (on the main branch) as you noted. 
![image](https://user-images.githubusercontent.com/2158838/197633702-cf6474dc-3b8d-49b2-8cd0-568bcf6951f3.png)

Watching more closely I noticed that this error appears when a status of "Activating Extensions" appears in the lower left corner of the codespace vscode instance. 

The vscode plugin is eventually installed without user interaction. If I reload the page the error messages are not present anymore.

**Comment by philliphoff** [comment]
I've seen that redundant recommendation notification before (with other extensions).  I'd expect that to be a VS Code issue; there's no logic in our extension related to recommendations.  That said, is our extension listed in both the recommended.json *and* the CodeSpace dev container definition?  (It may be that having both is what causes it.)

**Comment by pamelafox** [comment]
I confirmed that removing it from extensions.json does seem to remove the pop-up. However, it's not intuitive to me that it should be necessary, it still feels like a VS Code bug, since I see them helping two audiences:
1) if someone can use a devcontainer (via Remote extension or via Codespaces), they will get it installed via devcontainer.json
2) but if someone can't use devcontainers, then it makes sense to recommend the azd extension (and possibly the others too)

So I left a note on the most related issue I could find (https://github.com/microsoft/vscode-remote-release/issues/6364) to see if they know if it's a bug or working as intended.

**Comment by weikanglim** [comment]
I've been trying to reproduce this, and it seems inconsistent and likely related to a race condition in how VSCode builds the first time in Codespaces. Logged a bug for VSCode. Closing this out as it doesn't related to `azd`'s VSCode extension.
