### ISSUE TITLE
[Issue] 'azd pipeline config --help' does not mention 'GitHub' is the default value for 'provider'

### ISSUE THREAD

**Issue by rpothin** [Azure/azure-dev#968]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
Run `azd version` and copy and paste the output here:

![image](https://user-images.githubusercontent.com/23240245/197428692-c9845ca2-5758-4645-9894-5bef858eb6f7.png)

**Output from `az version`** 
Run `az version` and copy and paste the output here (minimum required version is 2.38.0): 

![image](https://user-images.githubusercontent.com/23240245/197428723-f625437c-1074-4218-bf53-2466e6cee904.png)

**Describe the bug**
Running the `azd pipeline config --help` command I don't see an indication regarding the fact that `GitHub` would be the default value for the `provider` parameter:

![image](https://user-images.githubusercontent.com/23240245/197428913-1fc7a23a-3e48-49d8-aabc-fa6e74e1b21c.png)

> Also, I don't find this information clearly exposed in the documentation page: [azd-pipeline-config](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/reference#azd-pipeline-config)

**To Reproduce**
Run `azd pipeline config --help`.

**Expected behavior**
It could be interesting to have something like below for the `provider` parameter running the `azd pipeline config --help` command - to be consistent with the description of the `remote-name` parameter:

`--provider string         The pipeline provider to use (GitHub and Azdo supported). (default "GitHub")`

**Environment**
Information on your environment: Terminal with PowerShell on Windows 10

**Additional context**
Nothing more to add, but do not hesitate to ask me for me details if needed.

**Comment by Austinauth** [comment]
@rajeshkamal5050 Will do. I'll make a note to investigate when I start #822.
