### ISSUE TITLE
API page exception when Azure Dev Deploy finished

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-dev#969]
**Describe the issue:**
Run command: ` bash ./test-templates.sh -c false -t <template_name> -b pr/551 `, the log is correct and the web app can work normally. But the api page exception when we hit the deployed service api endpoint link.

**Repro Steps:**
1.Run command: ` bash ./test-templates.sh -c false -t <template_name> -b pr/551 `.
2. Hit the deployed service api endpoint link.

**Error Message:**

![image](https://user-images.githubusercontent.com/80496810/197492871-b1be62f1-301b-4484-80db-fa31d06280ec.png)

**Environment:**
OS: Windows desktop, Mac ,Codesapce and Dev Container.
Templates:
https://github.com/Azure-Samples/todo-csharp-sql-swa-func
Branch: pr/551

**Expected behavior:**
The api page is similar here.
![image](https://user-images.githubusercontent.com/80496810/197493385-a6001088-0afd-4f53-9f6f-24c6f57f7e05.png)

@jongio for notification.

**Comment by jongio** [comment]
Even if ithe root doesn't load the swagger UI, Does the app still work?

**Comment by v-jiaodi** [comment]
The app can work normally.
