### ISSUE TITLE
Documentation on secretOrRandomPassword?

### ISSUE THREAD

**Issue by pamelafox** [Azure/azure-dev#994]
### Discussed in https://github.com/Azure/azure-dev/discussions/940

This azd sample uses the secretOrRandomPassword function in the parameters file:

https://github.com/Azure-Samples/todo-csharp-sql/blob/a10ba78f1322443f70a4ce36bcde93c47beaa3fe/infra/main.parameters.json

```
      "databasePassword": {
        "value": "$(secretOrRandomPassword ${AZURE_KEY_VAULT_NAME} databasePassword)"
      }
```

That function is implemented here:

https://github.com/Azure/azure-dev/blob/c53a984deecf80d561cd0767a31e899a05e331db/cli/azd/pkg/cmdsubst/secretOrRandomPassword.go#L44

I think it would be helpful to document that, as it took me a while to figure out the right approach to secret generation and to understand how the Key_Vault argument was treated.

I'm happy to send a PR for the documentation, though I'm not sure where, since https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/reference is specifically about the CLI commands and this is about the parameters. It also seems that this special command is just for azd, so it doesnt belong in the generic bicep docs.

**Comment by TWolverson** [comment]
This came up in a private conversation and I found that its only mentions on all of GitHub were in various people's invocations of the Azure samples, this issue, and one other issue also remarking that it is undocumented, and it is not explained anywhere else in any way whatsoever. So definitely agree there is a need for documentation of this and anything similar.

**Comment by pamelafox** [comment]
If its helpful, I presented a few slides on how it works internally:

https://microsoft-my.sharepoint.com/:p:/p/pamelafox/EVc3KMKGbP1HvvnH_tCEfFEBXkgwmZdJfRWQXRrYJsZpYw?e=4arC9k&nav=eyJzSWQiOjE1ODgsImNJZCI6MTk5NDQ0OTQwNn0

With a diagram! *Everyone loves diagrams.

![Diagram of screenshot flow](https://user-images.githubusercontent.com/297042/216671847-1e18aa17-bb7f-4157-bc54-5f52d9e12d66.png)

**Comment by rajeshkamal5050** [comment]
@savannahostrowski @ellismg may be for GA, we need to have some documentation around our bicep modules and also some of the additional such functions we have?

**Comment by gkulin** [comment]
@rajeshkamal5050 this was addressed In February here: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4212

For some reason I still don't have permission to close issues, so apologies for not calling that out as complete sooner. 

But if there is more documentation we need about bicep modules for GA, we should track that in a separate issue

**Comment by pamelafox** [comment]
I agree that this one was covered in that FAQ, yep. Other output variables that might not be documented yet?

* SERVICE_*_ENDPOINTS
* Container App variables: https://github.com/Azure/azure-dev/discussions/1445

Those would be separate issues if so.
