### ISSUE TITLE
UX Research: azd getting started experience

### ISSUE THREAD

**Issue by irinasmoke** [Azure/azure-dev#999]
We are conducting unmoderated usability testing on the latest azd getting started experience. 

The study consists of asking people to do some light research on azd, get started with it by deploying a template to Azure (including setting up all pre-requisites, which we did not include in the previous UX study scope), and reflect on their experience.

**Comment by Austinauth** [comment]
**Update 11/07/2022**
- Discussed on standup
- Austin to sync with Irina over teams this week to receive guidance on how to review the stud and capture my notes.

**Comment by Austinauth** [comment]
**Update 11/07/2022**

- Completed initial unmoderated study review
- Captured findings/notes in Onedrive folder
- Debrief scheduled for 12/08/2022

**Comment by savannahostrowski** [comment]
Is this completed @irinasmoke ?

**Comment by irinasmoke** [comment]
@savannahostrowski sessions are completed and summarization work is ~50% of the way there. I expect we can send out the findings next week.
